Ivyo bivugwa mu kinyamakuru kimwe ( La Presse ) .
Hoba hari icavuyemwo ?
Reka ndabibasigurire .
Kubera iki ?
Bishaka kuvuga iki ?
Amazina amwamwe yarahinduwe .

*
Weho bite ?
Rimbura uturorero tumwetumwe .
Mu buryo ki ?
H .
Uti kubera iki ?
Reka tuyirabe .
Amazina yarahinduwe .
Casohowe n’Ivyabona vya Yehova mugabo ubu ntikigicapurwa .
Ifise akamaro akahe ?
Ni kubera iki ivyo ari ukwo biri ?
Oyaye !
Cane nyene !
Oya .
None uvyibazako iki ?
None ivyo vyavuyemwo iki ?
casohowe n’Ivyabona vya Yehova .
Rimbura ibi bikurikira .
Rimbura uburorero bukeyi .
Niwumire kw’ibanga !
Oya nawe !
Uti gute ?
Ihibambewe !
Cane nyene !
None ivyo bitwigisha iki ?
R .
None ingorane yabaye iyihe ?
None ico camwa ni ikihe ?
Rimbura aka karorero .
None ivyo vyavuyemwo iki ?
Ego cane .
IKIGANIRO GIHUYE N’IBIRI KU GIPFUKISHO
Rimbura ibikurikira :
Ivyo none bishaka kuvuga iki ?
Ntivyama ari ukwo .
Ariko rero hariho n’ibindi .
Uti kuki ?
None ivyo bisobanura iki ?
Ngiye kumukorera umufasha bikwiranye . ”
( Raba ahavuga ngo INYIGISHO ZO MURI BIBILIYA > INYISHU Z’IBIBAZO BISHINGIYE KURI BIBILIYA )
Ukwiye guca ukora iki ?
Weho bite ?
Yehova ni izina ry’Imana nk’uko rihishurwa muri Bibiliya .
Ukugomba kwawe nigukorwe kw’isi nko mw’ijuru . ”
Bibiliya ivuga ko “ ubupfu buboheye ku mutima w’umwana . ”
© 2016 Watch Tower Bible and Tract Society of Pennsylvania
UVYIBAZAKO IKI ?
Iki kinyamakuru si ico kugurisha .
Gitanzwe mu bijanye n’igikorwa kirangurirwa kw’isi yose c’ukwigisha Bibiliya gishigikirwa n’intererano zitangwa n’abavyishakiye .
Wipfuza gutanga intererano , nuje kuri www.jw.org .
Kiretse aho vyerekanywe ukundi , amajambo yo mu Vyanditswe yakoreshejwe yakuwe muri Bibiliya y’isi nshasha , yahinduwe hakoreshejwe imvugo ya none .
“ Amaganya mu mutima w’umuntu awutera kwicurikira , mugabo ijambo ryiza rirawunezereza . ”
3
5
2
1
4
© 2017 Watch Tower Bible and Tract Society of Pennsylvania
URUKUNDO
© 2018 Watch Tower Bible and Tract Society of Pennsylvania
9 , 10 .
4 , 5 .
8 , 9 .
“ Raba !
6 , 7 .
Ndakunda kuba ndi ku Ngoro y’Ubwami mu ba mbere , no kuhava mu ba nyuma igihe bishoboka .
15 , 16 .
Tanga ikirorezo .
11 , 12 .
Sigura .
3 , 4 .
5 , 6 .
( Raba akajambo k’epfo . )
20 , 21 .
Eka data !
16 , 17 .
Birimwo icigwa giki kuri twebwe ?
Ni ibibazo ibihe tuja kurimbūra ?
7 , 8 .
1 , 2 .
13 , 14 .
17 - 19 .
19 , 20 .
Habe namba .
Habe n’umuziriziri !
Habe n’intete !
Reka turimbure uburorero bukeyi .
14 , 15 .
12 , 13 .
17 , 18 .
Uko ni ko bimeze nyene muri iki gihe .
2 , 3 .
Mu buryo ki ?
10 , 11 .
Ivyo tubimenya dute ?
F .
Ivyo tubimenya dute ?
Vyagenze gute ?
Tweho bite ?
18 , 19 .
Bibiliya ntibivuga .
Babigirana uwuhe mugambi ?
Twoshobora kubutora dute ?
( b ) Ni ibiki tuja kurimbura mu kiganiro gikurikira ?
Mugabo haciye haba iki ?
Ni kuki ivyo bihambaye cane ?
Ivyo dushobora kubikora dute ?
Mu kiganiro gikurikira tuza kwihweza iki ?
Tanga uturorero .
Iryo ni ryo rihambaye rya mbere .
Ntimushobora gusaba Imana n’Itunga . ”
Yarakijije impumyi , ibimuga , abanyamibembe be n’ibipfamatwi .
Mbega ivyo bisaba iki ?
Tanga akarorero .
Dushobora gute kuvyemera tudakeka ?
Bite ho kubikwerekeye wewe ubwawe ?
6 - 8 .
Yezu yavuze ati : “ Nta n’umwe ashobora kuza kuri jewe Data yantumye atamukwegereye . ”
Kandi ntimukīte umuntu wo mw isi Data , kuko So ar’umwe , ar’uwo mw ijuru .
Umenga ako gatima nta ko wogira .
Arik’umukuru muri mwebge az’abe umukozi wanyu .
Ni ibiki tuja kurimbura mu kiganiro gikurikira ?
( b ) Ni ibibazo ibihe tugiye kurimbura ?
8 - 10 .
None yokoze iki ?
Emwe , raba nimba ushobora kwishura ibibazo bikurikira :
Kumbure ntiwovyipfuza .
Vyongeye ugushigikirwa n’abavukanyi n’abavukanyikazi banje bo mu buryo bw’impwemu vyarampumurije cane .
Kw ari wewe ufise amajambo y’ubu [ zima ] budashira . ”
None umuntu yoshobora kungira iki ? ’ .
Ivyo bishoboka gute ?
Biraboneka ko atari kukwumviriza .
Woba uri umwe muri bo ?
Na twebwe turashobora kugira nk’ukwo nyene .
Ivyo tubigira gute ?
Cane nyene .
3 : 14 .
Reka turimbure uburyo butatu .
Ni kubera iki ivyo bihambaye ?
3 : 17 .
11 - 13 .
3 : 15 .
None bari gukora iki ?
3 : 10 .
2 : 2 .
2 : 7 .
3 : 18 .
( b ) Tugiye kwihweza iki muri kino kiganiro ?
( b ) Ni ibihe bibazo bica bivyuka ?
1 - 3 .
5 : 12 .
Bitugendera gute iyo dupfuye ?
mu busuku ?
Ikiganiro gikurikira kirabitwereka .
6 : 4 .
8 : 10 .
( b ) Ni ibibazo ibihe tugiye guca irya n’ino ?
Ni igiki none kizodufasha kwihangana ?
2 : 15 .
4 : 16 .
4 : 4 .
4 : 5 .
15 : 4 .
Ni igiki kiganirwako mu kiganiro gikurikira ?
4 : 18 .
5 : 8 .
13 : 4 .
4 : 13 .
4 : 1 - 7 .
4 : 12 .
1 : 3 .
Iryo ni ryo rihambaye rya mbere ” .
Yezu yavuze ati : “ Mukunde bagenzi banyu nk’uko mwikunda ” .
“ Imana [ ni ] urukundo ” .
Uti bwari ubuhe ?
Ariko none yankiye iki ?
5 : 1 .
2 : 12 .
4 : 11 .
5 : 5 .
2 : 4 .
3 : 13 .
2 : 3 .
4 : 6 , 7 .
3 : 16 .
12 : 1 .
28 : 19 , 20 .
23 : 14 .
3 : 5 , 6 .
2 : 3 , 4 .
6 : 10 .
1 : 5 .
1 : 24 .
7 : 9 .
▪ Ni kubera iki Imana ireka abantu bagacumukura ?
4 : 8 .
2 : 8 .
2 : 21 .
2 : 17 .
10 : 24 , 25 .
13 : 17 .
6 : 33 .
41 : 10 .
Turakeneye gukora duhuza n’ivyo tuba twasavye mu masengesho yacu .
3 : 9 .
6 : 8 .
11 : 6 .
6 : 19 .
( Soma Abaheburayo 13 : 5 . )
6 : 1 .
12 : 13 .
5 : 16 .
( Soma 2 Timoteyo 3 : 1 - 5 , 13 . )
( Soma Zaburi 40 : 8 - 10 . )
5 : 11 .
3 : 12 .
40 : 8 .
13 : 5 .
4 : 15 .
24 : 13 .
11 : 9 .
( b ) Ni igiki wiyemeje kugira ?
6 : 13 .
( Soma Zaburi 97 : 10 . )
Ivyo ntivyahimbaye Yehova .
15 : 58 .
4 : 16 , 17 .
( b ) Ni ibibazo ibihe biza kurimburwa muri iki kiganiro ?
2 : 18 .
( Soma Abaheburayo 13 : 4 . )
3 : 1 .
10 : 31 .
( Soma Zaburi 19 : 7 - 11 . )
( Soma Abanyefeso 5 : 15 , 16 . )
( Soma . )
5 - 7 .
( Soma Matayo 13 : 52 . )
Yezu yagaragaje gute ko yakunda abandi ?
5 : 14 , 15 .
1 : 17 .
3 : 13 , 14 .
27 : 11 .
8 : 21 .
Impwemu ubwayo ishinga intahe hamwe n’impwemu yacu yuko turi abana b’Imana . ”
1 : 20 .
Nari gukora iki ?
5 : 9 .
( Soma 2 Ngoma 34 : 1 - 3 . )
• Ni umugambi uwuhe Imana ifitiye isi ?
( Soma 1 Timoteyo 6 : 17 - 19 . )
15 : 28 .
Ukwo ni ko bigenda no muri iki gihe .
6 : 9 , 10 .
9 : 7 .
( Soma Yakobo 1 : 5 - 8 . )
( Soma Abaroma 15 : 7 . )
144 : 15 .
133 : 1 .
6 : 9 .
8 : 23 .
( Soma Abaroma 13 : 1 , 2 . )
( Soma Yeremiya 10 : 23 . )
12 : 12 .
( Soma 1 Abakorinto 2 : 10 . )
None Shetani yoba avuga ukuri ?
( Soma Yuda 4 . )
148 : 12 , 13 .
( Soma Itanguriro 3 : 15 . )
( Soma 1 Abakorinto 6 : 9 - 11 . )
48 : 17 .
None ni igiki camufashije ?
28 : 20 .
Ivyo vyoba vy’ukuri bishoboka ?
Ivyo none bitwigisha iki ?
( Soma 2 Abakorinto 13 : 5 . )
None yakoze iki ?
Wiyemeje gukora iki ?
( Soma 1 Abakorinto 15 : 58 . )
Doruka “ yari agwije ibikorwa vyiza , agafasha cane aboro . ”
( Soma Yosuwa 24 : 15 . )
Soma Matayo 6 : 33 .
1 : 22 .
( Soma Imigani 3 : 5 , 6 . )
Nugire ubushakashatsi .
( Soma Abaheburayo 11 : ​ 24 - ​ 27 . )
6 : ​ 12 .
“ Ijambo ry’Imana [ ni ] rizima kandi rigira ububasha . ” ​ ​ —⁠ HEB .
Iyo mirongo igereranya Ijambo ry’Imana n’icirore dushobora kwibonamwo nk’uko Yehova atubona .
Naciye ntangura kwibaza nimba naribona nk’uko Yehova yambona .
Mu ntango , ico ciyumviro gishasha naranse kucemera .
Nari nciyumvamwo yuko kwitega ko Yehova yonkunda ari ukwitega ibidashoboka .
Sinari bwajijuke ko Yehova ashobora kunkunda , ariko naciye ntangura kuzirikana ku nkuka y’incungu ya Yezu .
Ubwo nyene naciye ntahura yuko Yehova yari amaze igihe kirekire anyihanganiye , anyereka mu buryo bwinshi ko ankunda .
Ni nk’aho nari nagumye mfata incungu nkayiterera Yehova ndayimusubiza .
( Soma Abakolosayi 3 : 13 . )
Woba warasomye witonze inomero z’Umunara w’Inderetsi za vuba ?
( Soma Matayo 24 : 37 - 39 . )
32 Ibibazo vy’abasomyi
( Soma 2 Abakorinto 1 : 3 , 4 . )
( Soma Tito 2 : 3 - 5 . )
( Soma Abaroma 7 : 21 - 23 . )
( Soma Yesaya 63 : 11 - 14 . )
31 Ivyo mu bushinguro bwacu
ABANYAGIHUGU
ABAMAMAJI
( Soma Zaburi 1 : 1 - 3 . )
None iyo nkuru itwigisha iki ?
30 Ibibazo vy’abasomyi
Tubayeho mu bihe biteye umunezero .
( Soma Abaroma 7 : 21 - 25 . )
ABATSIMVYI BASANZWE
( Soma 2 Petero 2 : 5 . )
( Soma Yesaya 48 : 17 , 18 . )
( Soma Abanyefeso 4 : 1 - 3 . )
INYIGISHO ZA BIBILIYA
● Kwiga amashure .
Ariko none bari barungitswe hehe ?
( Soma Abaheburayo 13 : 7 , 17 . )
( Soma Abaheburayo 11 : 17 - 19 . )
Muri Bibiliya , imisozi ishobora kugereranya ubwami canke intwaro .
INKURU Y’UBUZIMA
32 Wari ubizi ?
103 : 8 .
13 Ibibazo vy’abasomyi
Yemwe ba se , ntimuratse abana banyu , kugira ngo ntibavunike umutima . ”
Nimubabarirane ata gahigihigi .
IVYO MU BUSHINGURO BWACU
Turimbura iki muri iki kiganiro ?
( Raba ishusho itangura . )

( Raba akajambo ko ku mpera . )
NUSE n’uwubona ibi bintu .
( Soma 2 Timoteyo 1 : 7 . )
Raba ubu burorero bubiri :
Ni ibiki twihweza muri iki kiganiro ?
( Soma 1 Abatesalonika 5 : 1 - 6 . )
Kiraboneka no kuri www.jw.org
30 Ivyo mu bushinguro bwacu
16 : 24 .
( Raba ingingo ya 15 )
( Soma Luka 21 : 1 - 4 . )
( Raba ingingo ya 8 - 10 )
( Raba ingingo ya 15 , 16 )
( Raba ingingo ya 16 )
Raba ingingo ya 11 )
Raba ingingo ya 12 )
Tuzokwihweza iki mu kiganiro gikurikira ?
Ni ibibazo ibihe tugiye kwihweza muri iki kiganiro ?
( Soma Zaburi 32 : 8 . )
( Soma Ivyahishuwe 14 : 6 , 7 . )
( Soma 1 Abatesalonika 2 : 13 . )
Kandi azocira urubanza koko abantu batobato mu bugororotsi , atange igikangiro mu kugororoka ku neza y’abatekereza bo kw’isi . ”
Bishobora guterwa n’ibintu bitari bike .
Yezu yavuze ati : “ Aho itunga ryawe riri , ni ho n’umutima wawe uzoba . ”
( Raba ingingo ya 14 )
“ Hahiriwe abantu Imana yabo ari Yehova ! ” ​ — ZAB .
( Raba ingingo ya 6 , 7 )
( Soma Yakobo 5 : 14 - 16 . )
( b ) Ni ibiki tuzokwihweza mu kiganiro gikurikira ?
( Soma Abaroma 12 : 10 . )
13 : 14 .
( Raba ingingo ya 13 , 14 )
Ni akarorero keza akahe Yozefu yadusigiye ?
( Soma Abaheburayo 10 : 24 , 25 . )
( Soma 2 Abakorinto 8 : 13 - 15 . )
Yehova ni Imana ivuga ukuri .
( Raba ingingo ya 17 )
ABATSIMVYI
Ni ibiki tugira twihweze ?
Raba akandi karorero .
( Raba ingingo ya 11 - 13 )
Ubwami bwawe nibuze .
Kuko ingǒgo yanje yoroshe , n’umutwaro wanje ukaba uhwahutse . ”
Mubandanye kwihanganirana no kubabarirana ata gahigihigi iyo hari uwufise ico yidogera uwundi .
Nk’uko Yehova yabababariye ata gahigihigi , namwe nyene mugenze mutyo .
Iryo jisho ryawe ry’iburyo rero nimba rigutsitaza , rinogore urite kure yawe . ”
YEHOVA ni Imana itanga cane .
ICO BIBILIYA IVUGA
IBINDI BIBILIYA IVUGA
ISHUSHO YO KU GIPFUKISHO :
INDIRIMBO : 72 , 119
Urukundo rwa kivukanyi ni iki ?
Kubera iki bihambaye ko tubandanya kugaragarizanya urukundo rwa kivukanyi ?
Twogaragaza gute urukundo rwa kivukanyi ?
Kubera iki Paulo yandikiye abakirisu b’Abaheburayo ?
( Soma Abaheburayo 10 : 36 - 39 . )
Kubera iki dukwiye kwitwararika igitabu c’Abaheburayo ?
Icanditswe c’umwaka wa 2016 ni ikihe , kandi ni kubera iki kibereye ?
Ni nde umukirisu akwiye kubona ko ari umuvukanyi ?
Ni igiki dukeneye gukora ubu imbere y’uko ya makuru akomeye atangura ?
Nimuze twihweze butandatu muri bwo .
Kugaragaza ubwakiranyi bisobanura iki ?
( Raba ishusho itangura . )
“ Ntimwibagire ubwakiranyi . ”
( Soma Abaheburayo 13 : 2 . )
Dushobora gute ‘ kuguma twibuka abari mu mvuto ’ ?
“ Mugume mwibuka abari mu mvuto . ”
( Soma Abaheburayo 13 : 3 . )
Dushobora gute gutera iteka umubano wacu w’ababiranye ?
“ Umubano w’ababiranye nube uwuteye iteka muri bose . ”
Kubumbwa n’uko ivyacu vyifashe bidufasha gute kugaragaza urukundo rwa kivukanyi ?
Kugira “ umutima rugabo ” bidufasha gute kugaragaza urukundo rwa kivukanyi ?
( Raba ingingo ya 18 )
Tworushiriza gute kugaragaza urukundo rwa kivukanyi ?
INDIRIMBO : 121 , 63
Urukundo rwa Kristu rutugobera gukora iki ?
Kubera iki urukundo rw’Imana rukwiye kutugobera gukunda abavukanyi bacu ?
Kubera iki imbabazi z’Imana zikwiye gutuma tubabarira abavukanyi bacu ?
( Soma 2 Abakorinto 1 : 20 . )
Urukundo rwa Kristu rukwiye gutuma twiyumva gute , kandi ni igiki rukwiye gutuma dukora ?
Ni imikazo iyihe isi idushirako ?
Ni ibibazo ibihe twokwibaza muri iki kiringo c’Icibutso , kandi ivyo vyotuma dukora iki ?
( Soma Luka 14 : 12 - 14 . )
Ni igiki dutegerezwa gutahura ?
Urukundo rw’Imana rwafashije gute mushiki wacu umwe kwihanganira udusembwa tw’uwundi mushiki wacu ?
‘ Ingabirano ya gusa itagira uko yovugwa ’ Imana yatanze ikwiye gutuma dukora iki ?
INDIRIMBO : 109 , 108
Ni ibintu ibihe vyabaye maze bituma Pentekoti iba umusi udasanzwe , kandi ivyo vyashikije gute ico Ivyanditswe vyari vyaravuze ?
Soma Ivyakozwe 2 : 2 - 4 .
Tubwirwa n’iki ko abarobanuwe bose mu kinjana ca mbere batarobanuwe neza na neza mu buryo bumwe ?
Ni igiki abarobanuwe bose baronka , kandi ico kibafasha gute ?
Ni ibiki umukirisu yarobanuwe ashobora kwibaza , ariko ni igiki atigera akekeranya ?
Ivyiyumviro vy’umuntu bihinduka gute igihe arobanujwe impwemu nyeranda , kandi ivyo biterwa n’iki ?
Abarobanuwe babona gute ubuzima bwabo ng’aha kw’isi ?
INDIRIMBO : 65 , 122
Ibivugwa muri Zekariya 8 : 23 biriko biranguka gute ?
Ni kubera iki muri iki gihe tudashobora kumenya neza abazoba muri bamwe 144.000 ?
Ni ingabisho iyihe abarobanuwe bakwiye kurimbura ata gufyina , kandi kubera iki ?
Abakirisu barobanuwe bakwiye kubona gute ibiberekeye ?
Ni igiki abakirisu barobanuwe batitega , kandi kubera iki ?
Kubera iki dukwiye kwiyubara ku bijanye n’ukuntu dufafa abarya umukate bakanywa n’umuvinyu ku Cibutso ?
( Raba uruzitiro ruvuga ngo “ Urukundo ‘ ntirwigenza ukutabereye . ’ ” )
Yezu yabwiye abigishwa biwe ati : “ Mwebwe mwese muri abavukana . ”
Igihe twirinze ‘ gutangarira abahambaye , ’ tuba twikingiye gute ?
Kubera iki tudakwiye guhagarikwa umutima n’igitigiri c’abarya umukate bakanywa n’umuvinyu ku Cibutso ?
“ Yehova arazi abiwe . ”
Bibiliya ivuga iki ku bijanye n’igitigiri c’abarobanuwe bazoba bari kw’isi ya makuba akomeye niyatangura ?
Ni ibiki dukwiye gutahura ku bijanye na bamwe 144.000 Yehova yacaguye ?
Mu kinjana ca mbere , abakirisu barobanuwe bakeyi gusa ni bo bakoreshejwe mu kwandika Ivyanditswe vy’ikigiriki .
Ni ibiki twize muri iki kiganiro ?
INDIRIMBO : 75 , 74
gituma twiyegereza Imana n’abandi ?
kidukingira ?
Naho Yehova ari Musumbavyose , ni agateka akahe yateye abandi ?
Ni agateka akahe Yehova yateye Adamu , kandi yabitumwe n’iki ?
Nk’akarorero , yarateye Adamu agateka ko kwita amazina ibikoko .
Abandi bantu bakoranye n’Imana gute kugira ivyo igomba biranguke ?
Ni igikorwa ikihe dushobora kugiramwo uruhara , kandi ni kubera iki bitari ngombwa ngo Yehova adusabe kukigiramwo uruhara ?
Intumwa Paulo yanditse ati : “ Ko dukorana na we , turabinginga rero ngo ntimwemere ubuntu ata wari abukwiriye bw’Imana hanyuma ngo muhushe intumbero yabwo . ”
Umwana w’imfura w’Imana yavuze ko gukorana na Se vyatuma yiyumva gute ?
Uwitwa Franco , na we akaba akorera mu Butaliyano , avuga ati : “ Yehova abicishije kw’Ijambo ryiwe no ku ntunganyo zo mu vy’impwemu ashiraho , aratwibutsa buri musi yuko adukunda be n’uko ikintu cose tumukorera gihambaye , n’igihe nyene twoba tubona umengo utwigoro twacu nta co tuvuze .
Ni co gituma gukorana n’Imana bintera agahimbare , bikanatuma ubuzima bwanje bugira intumbero . ”
Yehova na Yezu bari bafitaniye ubucuti bumeze gute , kandi vyatumwe n’iki ?
Turamenya igituma biranga ubukerebutsi kuyizigira no gukurikiza ubuyobozi bwayo .
Kubera iki tuzorushiriza kwiyegereza Yehova n’abavukanyi bacu mw’isi nshasha ?
Igikorwa co kwamamaza kidukingira gute ?
Igikorwa co kwamamaza kiramfasha kuguma nicishije bugufi ; kikandonsa akaryo ko kwiheka kuri Yehova no kuri bene wacu na bashiki bacu . ”
Kubera iki kuba tubandanya kwamamaza vyerekana ko impwemu y’Imana iri kumwe natwe ?
Womara igihe kingana gute uriko urakora ako kazi ?
Kwamamaza inkuru nziza bihuye gute n’umugambi Imana ifitiye abantu ?
Igikorwa cacu co kwamamaza gihuye gute n’amategeko y’Imana asumba ayandi yose ?
Irigira kabiri rimeze nka ryo , ni iri : ‘ Utegerezwa gukunda mugenzawe nk’uko wikunda . ’ ”
Mbega ukuntu ari agateka gahambaye gukora ivyo Yehova adusaba be no gukorana n’iyo Mana yacu ! ”
IKI KINYAMAKURU Umunara w’Inderetsi , kiratera iteka Yehova Imana , we Mutegetsi ruheta w’ijuru n’isi .
Kirahumuriza abantu biciye ku nkuru nziza y’uko vuba Ubwami bw’Imana , buno bukaba ari intwaro iriho koko yo mw’ijuru , bugiye gukuraho ubukozi bw’ikibi bwose maze buhindure isi Iparadizo .
Kiraremesha abantu ngo bizere Yezu Kristu , uwapfuye kugira ngo dushobore kuronka ubuzima budahera kandi ubu akaba aganza ari Umwami w’Ubwami bw’Imana .
Iki kinyamakuru gisohorwa n’Ivyabona vya Yehova ubudahengeshanya kuva mu 1879 kandi nticisuka mu vya politike .
Kiguma cisunga Bibiliya .
Dawe na mawe ntibakunda ivy’idini , mugabo uko twari abana umunani baratubwira ngo tuje gusenga .
Narabigize , nca nsanga izina ry’Imana ari Yehova .
Gatoyi inyuma y’aho , narashinzwe igikorwa co kuyobora inyigisho y’igitabu y’ishengero .
Nararemesheje mawe be n’abo tuvukana ngo baze , kandi bose baratanguye kwitaba inyigisho y’igitabu nayobora .
Ariko rero , dawe ntiyashimishijwe .
Umucamanza yambwiye ati : “ Iyaba ari je nabigira , nari kugucira umunyororo wo guherayo .
Hari ico ufise uvuga ? ”
Naragiye ngana umugabo umwe yari apfunzwe , akaba yari muremure kandi afise ibitugu vyagutse , maze turahagarara ng’aho turabira mw’idirisha .
Yambajije ati : “ Wa mugabo mugufi we , kubera iki uri ng’aha ? ”
Namubwiye nti : “ Ndi Icabona ca Yehova . ”
Namwishuye nti : “ Ivyabona vya Yehova ntibaja mu ntambara kwica abantu . ”
Nasubijeyo nti : “ Eka ntivyumvikana . ”
Yaciye avuga ati : “ Naramaze imyaka 15 mu rindi bohero , maze ndasoma bimwebimwe mu bitabu vyanyu . ”
Ukwo ni ko twamamaza mu buryo burimwo urutonde .
Nasubijeyo nti : “ Ni vyiza , ariko jewe sinzoja mu gisoda . ”
Naciye nsubiramwo ibivugwa muri 2 Timoteyo 2 : 3 maze mvuga nti : “ Nsanzwe ndi umusoda wa Kristu . ”
Budakeye na kabiri , naritavye inama y’abipfuza kuja gukorera kuri Beteli , kw’ihwaniro ryabereye i Cincinnati muri Ohio .
Naragize abagenzi benshi kuri Beteli no mw’ishengero .
Narize igishinwa c’ikimandarini gikeyi , nkaba mpimbarwa no kuyagisha Abashinwa kw’ibarabara .
Mu ndwi yakurikiye , yarampaye telefone maze avuga ati : “ Hari umuntu wo mu Bushinwa yipfuza ko muvugana . ”
Nasubijeyo nti : “ Nta muntu n’umwe wo mu Bushinwa tuzinanyi . ”
Narasubiye mu Bushinwa . ”
Nanje nti : “ Mu Bushinwa ? ”
Inyuma y’aho gatoyi , naravuganye ubwa nyuma na mwene wabo na Katie .
Imana niyabishaka , incuti n’abagenzi bapfuye bazozuka babe mw’isi nshasha .
INDIRIMBO : 91 , 22
Ivyo Aburahamu yari azi be n’ivyo yiboneye vyakomeje gute ukwizera kwiwe ?
Aburahamu yakoze iki kugira akomeze ubugenzi yari afitaniye n’Imana ?
Ushobora gute kwigana Aburahamu mu gukomeza ubugenzi ufitaniye na Yehova ?
Aburahamu ashobora kuba yamenye gute ivyerekeye Yehova , kandi ubwo bumenyi bwamufashije gute ?
Ivyo yari azi .
Ivyo Aburahamu yiboneye vyakomeje gute ukwizera kwiwe ?
Ivyo yari yariboneye .
Ni ibiki vyodufasha gukomeza ubugenzi dufitaniye na Yehova ?
Ni kubera iki Aburahamu yahagaritse umutima ku vyerekeye Sodomu na Gomora , kandi Yehova yamufashije gute ?
Ni ibintu biteye umunezero ibihe Aburahamu azomenya mw’Iparadizo ?
Wiyemeje iki , kandi ni ibiki tuzokwihweza mu kiganiro gikurikira ?
Cokimwe na we , turakeneye kugira ubumenyi no kwihweza ivyo Yehova adukorera .
( Soma Abaheburayo 6 : 10 - 12 . )
Mu kiganiro gikurikira , tuzokwihweza ubundi burorero butatu bw’abantu b’abizigirwa babaye abagenzi somambike b’Imana .
INDIRIMBO : 106 , 118
Ni igiki twokwigira ku bugenzi Rusi yagiraniye n’Imana ?
Ni kubera iki Umwami Hezekiya yari umugenzi somambike wa Yehova ?
Ni ibiki vyatumye Mariya nyina wa Yezu aba umugenzi wa Yehova Imana ?
( Soma Rusi 2 : 12 . )
Ni ibiki vyofasha abagonanwa kwiyegurira Yehova ?
Hezekiya yakuze ibintu vyifashe gute ?
( b ) Kubera iki tudakwiye gushangashirirwa Imana ?
( c ) Kubera iki tudakwiye kwiyumvira yuko aho twakuriye ari ho hadushingira ico tuzoba ?
Abakiri bato benshi baremera ukuri naho baba bakuriye mu muryango umeze gute ( Raba ingingo ya 9 , 10 )
Ni ibiki vyatumye Hezekiya aba umwe mu bami beza kuruta abandi bose ba Yuda ?
( Soma 2 Abami 18 : 5 , 6 . )
Cokimwe na Hezekiya , ni gute abantu benshi bagaragaje ko ari abagenzi ba Yehova ?
Kubera iki agateka Mariya yatewe kasa n’akagoye cane , ariko yishuye gute Gaburiyeli ?
Muri ivyo bihe vyompi , Mariya yarumvirije , aribuka yongera arazirikana yitonze ivyo yari yarumvise . ​ — Soma Luka 2 : 16 - 19 , 49 , 51 .
Twokwigana ukwizera kwa Mariya mu buryo butandukanye ubuhe ?
Birashoboka rwose ko wahimbawe cane no gukorera Yehova kuva ubatijwe .
Twibuke ko Yezu yavuze ati : “ Nimuze kuri jewe , mwese abacumukura n’abaremerewe , nanje ndabaruhurira .
Avuga ati : “ Naho bimbabaza kubona umukenyezi wanje abandanya gusinzikara kandi ntibinyorohere kumwitwararika , sindeka ngo bintware umunezero nkura mu murimo ndangurira Imana y’ukuri .
Kuba nzi ko ubuzima bwanje ndabukesha Yehova , we yaremye umuntu afise umugambi , birahagije kugira ndamukunde cane nongere ndamukorere n’umutima wanje wose .
Ndihatira kuguma mfise umwete mu gikorwa co kwamamaza , kandi ndagerageza kugumiza umuzirikanyi wanje ku cizigiro c’Ubwami kugira sintakaze umunezero . ”
Yehova yaratanze inkuka y’incungu maze atuma bishoboka ko tugira ubuzima buhimbaye .
Mu vy’ukuri , “ Imana ya [ ra ] kunze isi cane ku buryo yatanze Umwana wayo w’ikinege , kugira ngo umuntu wese amwizera ntarandurwe ahubwo aronke ubuzima budahera . ”
Nariyeguriye rero Yehova , maze haciye imyaka 28 nkora ako kazi , mfata ingingo yo kugaheba kugira ntangure umurimo w’igihe cose . ”
Woba wibuka ukuntu ubuzima bwawe bwari bumeze utaramenya Yehova ?
Intumwa Paulo yibukije abakirisu b’i Roma yuko “ [ b ] ari abashumba b’igicumuro , ” mugabo ko bacitse “ abashumba b’ubugororotsi . ”
Iyo none si imvo yotuma tugira umunezero ?
Jaime avuga ati : “ Buhorobuhoro , naratahuye ko hariho Umuvyeyi akundana akaba n’Imana y’imbabazi .
Imyaka ihimbaye kuruta iyindi yose mu buzima bwanje ni iyo maze nkorera Yehova . ”
INDIRIMBO : 125 , 62
Yonatani umuhungu wa Sauli yabaye intahemuka kuri Yehova gute ?
Dushobora gute kuba intahemuka ku Mana igihe umuntu afise ubukuru asa n’uwutabereye kwubahwa ?
Dushobora gute kuba intahemuka kuri Yehova igihe abandi badutahuye nabi canke baturenganije ?
Ni kubera iki bitari vyoroshe ko Abisirayeli baba intahemuka ku Mana igihe Sauli yari umwami ?
Yonatani yafata gute se wiwe ?
Kwubaha ubukuru vyerekana gute ko turi intahemuka ku Mana ?
Urwo dukunda Imana rudufasha gute kutayihemukira ?
Kuba intahemuka ku Mana bishobora gute kudufasha gutorera umuti ingorane zo mu muryango ?
Sauli yarenganije gute Yonatani ?
Dukwiye kuvyifatamwo gute bishitse umuvukanyi akaturenganya ?
Iki cigwa cagufashije gute ?
Ni nde tudakwiye guhemukira ?
Kubera iki Yonatani na Abuneri bafashe Dawidi mu buryo butandukanye ?
Ni kamere izihe zizodufasha kuba intahemuka ku Mana , kandi zizodufasha gute ?
Ni icigwa ikihe dukura kw’ikosa rya Abishayi ?
Ni gute mushiki wacu umwe yabaye intahemuka ku Mana igihe yari mu kigeragezo kitoroshe ?
Inkuru zo muri Bibiliya zerekeye Abuneri , Abusalomu na Baruki zitwigisha iki ?
Ushobora gute kuba intahemuka kuri Yehova no ku mugenzi canke incuti yawe ?
Kubera iki Hushayi yari akeneye umutima rugabo kugira abe intahemuka ku Mana ?
Narasenze nsaba umutima rugabo wo kwumira ku ngingo nari nafashe .
Ubu baraturuye , kandi ndashobora kwama nja kubaramutsa . ” ​ — Soma Imigani 29 : 25 .
Iki cigwa cagufashije gute ?
( Soma Yohani 13 : 34 , 35 . )
Kirasigura kandi igikorwa ukwihangana gukwiye kunonosora muri umwumwe wese muri twebwe .
INDIRIMBO : 86 , 54
Akarorero ka Yefuta n’umukobwa wiwe kadufasha gute kunanira inyosha mbi z’isi ?
Ni ingingo ngenderwako zo muri Bibiliya izihe zogufasha gutorera umuti ingorane ?
Iki kiganiro cakuremesheje gute kugira ivyo uhevye ku bw’Ubwami ?
Ni ikintu kitoroshe ikihe cashikiye Yefuta n’umukobwa wiwe ?
Ni kubera iki akarorero ka Yefuta n’umukobwa wiwe gashobora kudufasha muri iki gihe ?
Ni ingeso mbi izihe zirangwa mw’isi muri iki gihe , kandi dutegerezwa gukora iki ?
Ni indagano iyihe Yefuta yagize , kandi ivyo vyasobanura iki ?
Amajambo ya Yefuta ari mu Bacamanza 11 : 35 ahishura iki ku vyerekeye ukwizera kwiwe ?
Ni indagano iyihe benshi muri twebwe twagize , kandi dushobora kwerekana gute ko turi abizigirwa ?
( Raba ingingo ya 16 , 17 )
INDIRIMBO : 135 , 139
Ni ibiki bizodufasha kwihangana ?
Ni uturorero tumwetumwe utuhe tw’abagaragaje ukwihangana ?
Kureka ‘ ukwihangana kukanonosora igikorwa cakwo ’ bisobanura iki ?
Mu bo turwana harimwo Shetani , isi yiwe be n’agasembwa kacu .
( Soma Luka 21 : 19 . )
None ukwihangana ni iki ?
Kubera iki twovuga ko urukundo ari rwo rutuma twihangana ?
Yehova ni “ Imana . . . itanga ukwihangana n’uruhoza . ”
Na Yezu vyarashitse arumva amerewe gutyo .
Kubera iki dukwiye kurimbura uturorero tw ’ “ abihanganye ” ?
Mu kwihangana ntituri ba nyamwigendako .
Ni igiki twigira ku karorero ka ba bakerubi bashirwa mu murima wa Edeni ?
Ni ibiki vyafashije Yobu kwihanganira ibigeragezo vyamushikiye ?
Intumwa Paulo .
( Soma 2 Abakorinto 1 : 6 . )
“ Twiyumvirane . . . , tudaheba kwa gukoranira hamwe kwacu . ” ​ — HEB . 10 : 24 , 25 .
INDIRIMBO : 20 , 119
ukuntu twungukira ku makoraniro y’ishengero .
ukuntu dufasha abandi igihe twitavye amakoraniro .
ukuntu Yehova avyakira igihe twitavye amakoraniro .
( Raba ishusho itangura . ) ( b ) Ni ibiki twihweza muri iki kiganiro ?
Emwe , vyaraturemesheje vyongera birakomeza ukwizera kwacu ! ”
Ni gute amakoraniro yacu aturemesha akongera akadufasha kuguma dukomeye ?
Amakoraniro araturemesha .
( Soma Yohani 10 : 16 . )
Naho nza mfise ububabare bwinshi mu mavi , nkagira ingorane z’umutima be na diyabeti , nama ntaha umengo ntoye ka mitende .
Maze kwumva amajwi y’abandi bose nkoresheje utwuma tumfasha kwumva , naciye ndirimbana na bo .
Kwitaba amakoraniro bidufasha gute guha Yehova ivyo abereye ?
Igihe tugamburutse itegeko Yehova yatanze ryo kwitaba amakoraniro , avyakira gute ?
Ni mu buryo ki twiyegereza Yehova na Yezu ku makoraniro ?
Ni gute kwitaba amakoraniro vyereka Imana ko twipfuza kuyigamburukira ?
ABITAVYE ICIBUTSO ( 2015 )
Ikime ni umuhezagiro uva kuri Yehova .
Ibubamfu : Ca kigo c’ababikira c’i Zaragoza muri Espanye ; iburyo : Bibiliya Nácar - Colunga
Ndibuka ko nasenze nti : “ Warakoze Yehova kubona utampevye , ukampa uturyo twinshi two kuronka ico narondera , ukandonsa ubumenyi nyakuri bwo muri Bibiliya . ”
Nasubijeyo nti : “ None Imana yoyo yovuga iki ? ”
INDIRIMBO : 33 , 137
Yehova abona gute intwaro z’abantu ?
Dukwiye kuvyifatamwo gute igihe bitoroshe kuguma ata ho duhengamiye ?
Twigira iki ku basavyi ba Yehova b’intahemuka bagumye ata ho bahengamiye ?
Dushobora gute kugamburukira Imana be n’intwaro z’abantu ?
Twerekana gute ko tuguma ata ho duhengamiye mu vya politike y’iyi si ?
( b ) Kubera iki ubu ari ho dukwiye kwimenyereza kuguma ata ho duhengamiye ?
Dukwiye kubona gute abategetsi mu vy’intwaro ?
Ni ibiki dukwiye kwirinda ?
Ni gute dukwiye ‘ kwiyubara ’ yamara ‘ tukaba intungane ’ igihe duhuye n’ibintu vyoshobora gutuma tudohoka ?
( Soma Matayo 10 : 16 , 17 . )
Ni ibiki dukwiye kubako maso igihe tuganira n’abandi ?
Ibiyago vyacu .
Gukunda amaronko .
Twigira iki ku basavyi b’Imana b’intahemuka bagumye ata ho bahengamiye ?
“ Kuzirikana ku bivugwa mu Migani 27 : 11 , muri Matayo 26 : 52 no muri Yohani 13 : 35 vyatumye ndushiriza kwiyemeza kutaja mu gisoda .
Ivyo vyanditswe vyaramfashije kandi kuguma ntekanye igihe nari imbere y’abategetsi . ” ​ — Andriy wo muri Ukraine .
“ Muri Yesaya 2 : 4 haramfashije kuguma nshikamye mu bigeragezo .
9 : 50 .
INDIRIMBO : 39 , 77
Ni impanuro iyihe Yezu yatanze idufasha gutunganya ingorane mu rukundo ?
Ni ibibazo ibihe umukirisu yokwibaza igihe ahitamwo ingene yotunganya ingorane afitaniye n’abandi ?
Intambwe zitatu zivugwa muri Matayo 18 : 15 - 17 zokoreshwa gute mu gutunganya amatati amwamwe ?
Ni amatati ayahe abantu bagiraniye avugwa mw ’ ​ Itanguriro , kandi kuyarimbura bidufasha gute ?
Ni agatima akahe kiraye mw’isi , kandi gatuma haba iki ?
Yezu yigishije gute abantu gutunganya amatati ?
6 , 7 . ( a ) Kubera iki bihambaye ko dutorera umuti tudatebaganye ingorane dufitaniye n’abandi ?
( b ) Ni ibibazo ibihe abasavyi ba Yehova bose bakwiye kwibaza ?
Umuvyeyi wacu wo mw’ijuru azokwumva amasengesho mwene ayo tumutura twicishije bugufi yongere ayishure . ​ — 1 Yoh . 5 : 14 , 15 .
Dukwiye gukora iki hagize uwutubabaza ?
( Soma Imigani 10 : 12 ; 1 Petero 4 : 8 . )
( a ) Igihe mushiki wacu umwe yumva amajambo yo kumunegura , yabanje kuvyakira gute ?
( b ) Ni icanditswe ikihe camufashije kuguma atekanye ?
11 , 12 . ( a ) Igihe umukirisu abonye ko “ hari ico apfa ” na mugenzi we , akwiye gukora iki ?
“ Twese dutsitara kenshi . ”
Umucungezi umwe yakoze iki igihe yabwirwa amajambo ababaza , kandi akarorero kiwe katwigisha iki ?
14 , 15 . ( a ) Ni ryari twokwisunga impanuro iri muri Matayo 18 : 15 - 17 ?
( b ) Ni intambwe zitatu izihe Yezu yerekanye , kandi dukwiye kuzikurikiza dufise intumbero iyihe ?
Ni igiki cerekana ko kwisunga iyo mpanuro ya Yezu ari ngirakamaro kandi ko biranga urukundo ?
Ni imihezagiro iyihe tuzokwironkera ‘ nitwarondera kugiranira amahoro ’ n’abandi ?
INDIRIMBO : 141 , 97
n’ubutumwa bamamaza be n’igituma babwamamaza ?
n’uburyo bakoresha mu kwamamaza ?
n’aho bashikana inkuru nziza ?
Ivyo Yezu yavuze muri Matayo 24 : 14 bituma havyuka ibibazo ibihe ?
Ni ibintu bine ibihe bivugwa muri Matayo 28 : 19 , 20 abayoboke ba Yezu bakwiye gukora ?
Gucika “ abarovyi b’abantu ” vyosavye iki ?
Ni ibibazo bine ibihe dukeneye kuronkera inyishu , kandi kubera iki ?
Soma Luka 4 : 43 .
Tubwirwa n’iki ko indongozi z’amadini zitariko ziramamaza ubutumwa nyabwo ?
Abavuga inkuru nziza bakwiye kwirinda kubigira bafise imvo iyihe ?
( Soma Ivyakozwe 20 : 33 - 35 . )
Ni uburyo ubuhe Yezu n’abigishwa biwe bakoresheje mu kwamamaza ?
Gereranya ivyo abitwa abakirisu bakora be n’ivyo abasavyi ba Yehova bakora mu bijanye no kwamamaza inkuru nziza .
Ni bo bonyene bigisha ko Yezu aganza kuva mu 1914 .
Inkuru nziza ikwiye kwamamazwa gushika hehe ?
Ni ibiki vyerekana ko Ivyabona vya Yehova bariko barashitsa ivyo Yezu yavuze ku bijanye n’aho inkuru nziza yoshikanywe ?
( Raba amashusho atangura . )
Urubuga rwacu rwemewe ruboneka mu ndimi zirenga 750 .
Tubwirwa n’iki ko Ivyabona vya Yehova bafise impwemu y’Imana ?
17 , 18 . ( a ) Twemezwa n’iki yuko Ivyabona vya Yehova ari bo bamamaza inkuru nziza y’Ubwami muri iki gihe ?
( b ) Ni nde adushoboza kuguma twamamaza ?
INDIRIMBO : 117 , 114
Ni igiki coshobora gutuma duhomba imfungurwa zimwezimwe zo mu vy’impwemu ?
Ni ibintu ibihe vyodufasha kwungukira ku bice vyose vya Bibiliya ?
Dushobora gute kwungukira ku kurimbura amayagwa agenewe abakiri bato be n’ayagenewe abantu bose ?
1 , 2 . ( a ) Ivyabona vya Yehova babona gute Bibiliya ?
( b ) Ni igice co muri Bibiliya ikihe ukunda kuruta ibindi ?
3 , 4 . ( a ) Tubona gute ibitabu vyacu ?
( b ) Ni amayagwa ayahe turonka agenewe imigwi kanaka y’abantu ?
Ni igiki dushobora kwemera tudakeka ko Yehova ashima ?
Kubera iki dukwiye gusoma Bibiliya twugurutse mu bwenge ?
Nusome wugurutse mu bwenge .
Noyakoresha gute mu gufasha abandi ? ’
( b ) Dushobora gute gukoresha ayo makuru mu gufasha abandi ?
12 , 13 . ( a ) Igihe dukoresha ibikoresho dufise , ni amakuru nk’ayahe twoshobora kurondera ?
( b ) Tanga akarorero k’ukuntu amakuru yiyongereye ashobora gutuma tubona ivyigwa bidashoka vyibonekeza .
Candikiwe hehe kandi ryari ?
Amayagwa agenewe abakiri bato abafasha gute , kandi ashobora gute gufasha n’abandi ?
Ni kubera iki abakirisu bakuze bakwiye kwitwararika gusoma amayagwa y’abakiri bato ?
Ni ikindi kintu ikihe ibitabu vyacu bifasha abakiri bato gukora ?
( Soma Umusiguzi 12 : 1 , 13 . )
Noshobora gute kuryoherwa no gusoma Bibiliya ? ”
Dushobora gute kwungukira ku gusoma amayagwa agenewe abantu bose ?
Dushobora gute kwerekana ko dukengurukira Yehova kubera ibifungurwa aturonsa ?
INDIRIMBO : 69 , 57
Ingingo dufata zishobora gute kugira ingaruka kuri twebwe no ku bandi ?
Igihe ata tegeko ridomako Bibiliya itanga , dushobora gute kumenya ibihimbara Yehova ?
Tworushiriza gute kumenya ingene Yehova yiyumvira ?
Amwamwe mu mategeko dusanga muri Bibiliya ni ayahe , kandi kuyakurikiza bitumarira iki ?
2 , 3 . ( a ) Kubera iki Bibiliya itadushingira amategeko mu bintu vyose ?
Dukwiye kwisunga iki mu gufata ingingo ?
Igihe Bibiliya idatanga itegeko ridomako , twomenya gute ico Yehova yoshima ko dukora ?
( Soma Matayo 4 : 2 - 4 . )
Ni igiki kizodufasha gufata ingingo ziranga ubukerebutsi ?
Igihe dusoma Bibiliya canke twiyigisha , ni ibibazo ibihe twokwibaza ?
Ibitabu vyacu n’amakoraniro yacu bishobora gute kudufasha kumenya ingene Yehova abona ibintu mu mice itandukanye ?
Tanga akarorero kerekana ingene dushobora gufata ingingo zibereye igihe turimbuye ivyiyumviro vya Yehova .
( Soma Luka 18 : 29 , 30 . )
Twomenya gute ko umuderi kanaka w’impuzu uhimbara Yehova ?
( c ) Twogira iki igihe tugomba gufata ingingo zihambaye ?
( Soma Itanguriro 6 : 5 , 6 . )
Ni ivyiza ibihe twironkera igihe dufashe ingingo zihimbara Yehova ?
Ariko rero tugize akigoro gakomeye , turashobora kuronka ubukerebutsi , ubumenyi n’ugutahura dukeneye kugira dufate ingingo zibereye .
i muhira ?
INDIRIMBO : 61 , 52
Ni kubera dukwiye kubandanya kugira ivyo duhinduye n’inyuma y’ibatisimu ?
Ni kubera iki Imana yiteze ko tugira akigoro kugira ngo dutsinde ubugoyagoye bwacu ?
Twokora iki kugira ngo Ijambo ry’Imana ribandanye guhindura ubuzima bwacu ?
1 - 3 . ( a ) N’inyuma yo kubatizwa , ni ibintu ibihe vyoshobora kutugora guhindura ?
( b ) Igihe kuryohora ibintu bitatworoheye nk’uko twavyiyumvira , ni ibibazo ibihe twokwibaza ?
Ni kubera iki tudashobora guhimbara Yehova mu vyo dukora vyose ?
6 , 7 . ( a ) Ni igiki gituma dushobora kugiranira ubucuti na Yehova naho tudatunganye ?
( b ) Kubera iki tudakwiye kwitinya gusaba imbabazi Yehova ?
Tubwirizwa gukora iki kugira ngo Bibiliya idufashe kuguma tugira ivyo duhinduye , kandi ni ibibazo ibihe twoshobora kwibaza ?
Kubera iki Yehova yiteze ko tugira akigoro kugira ngo dutsinde ubugoyagoye bwacu ?
Twokora iki kugira ngo dutsimbataze kamere zihimbara Yehova ?
( Raba uruzitiro ruvuga ngo “ Bibiliya be n’isengesho vyarahinduye ubuzima bwabo . ” )
Kubera iki tudakwiye kwihebura mu gihe tutagize amahinduka ningoga ?
Ni igiki gishobora kutujijura yuko Bibiliya ifise ububasha bwo kubandanya ihindura ubuzima bwacu ?
[ 1 ] ( ingingo ya 1 ) Si ko asanzwe yitwa kubera ko bitashimwe ko amenyekana .
Maria Victoria yarakunda kuvuga urusaku .
Russell : “ Icamfashije ni ugutakambira Yehova mw’isengesho no gusuzuma Bibiliya buri musi .
Kuzirikana ibivugwa muri 2 Petero 2 : 11 hamwe n’impanuro nahabwa n’abakurambere vyaratumye mpinduka cane . ”
Maria Victoria : “ Narasenze Yehova nshimitse ngo amfashe gucungera ururimi .
Naranabonye ko nkwiye guheba kwifatanya n’abantu bakunda kuvuga urusaku .
Muri Zaburi 64 : 1 - 4 haramfashije kubona ko ntakwiye kuba uwo abandi basaba Yehova ngo abarinde !
Nahavuye ntahura ko mbandanije kuvuga urusaku nari kuba ntanze akarorero kabi , maze ngasiga iceyi izina rya Yehova . ”
Linda : “ Narimenyereje gukoresha twa dupapuro twacu tw’inkuru nziza kugira nitegurire kudutanga .
Abantu bose barakora amakosa ashobora kubabaza abandi .
INDIRIMBO : 89 , 26
Yehova ahitamwo gute abo abumbabumba ?
Kubera iki Yehova abumbabumba abasavyi biwe ?
Imana ibumbabumba gute abayiyobokera ?
Ni kubera iki Yehova ari we Mubumvyi aruta abandi bose ?
Dushobora gute kwigana agatima k’Abisirayeli bari bigaye ?
Yehova ahitamwo gute abo akwegera kuri we ?
( Soma 1 Samweli 16 : 7b . )
Kuba twemera ko Yehova ari we Mubumvyi wacu bikwiye guhindura gute ukuntu tubona ( a ) abo mu cibare cacu ?
Mu nyuma , narahuriye n’umuryango umwe ahandi hantu , ndawutangarira kubera inyifato yawo nziza .
Ariko umusi umwe , naravunitse umutima : Nasanze ari Ivyabona vya Yehova !
Inyifato yabo yaratumye nibaza icatuma ndabinuba .
Bidatevye , narabonye ko nabitumwa n’ukutamenya be n’amabwire . ”
Kubera iki uha agaciro indero dutozwa na Yehova ?
( Soma Abaheburayo 12 : 5 , 6 , 11 . )
Yehova atwigisha gute muri iki gihe , kandi azorushiriza gute kutwigisha muri kazoza ?
Yezu yagaragaje gute ukwihangana n’ubuhanga vya wa Mubumvyi Ahambaye ?
( Soma Zaburi 103 : 10 - 14 . )
Ni mu buryo ubuhe Dawidi yabaye nk’ibumba ryoroshe , kandi twomwigana gute ?
Yehova atubumbabumba gute akoresheje impwemu yiwe nyeranda be n’ishengero rya gikirisu ?
Naho Yehova adufiseko ububasha , yerekana gute ko yubahiriza uburenganzira dufise bwo kwihitiramwo ?
Abatohoji ba Bibiliya berekana gute ko bipfuza ko Yehova ababumbabumba ?
( a ) Ni kubera iki uhimbarwa no kuba Yehova ari Umubumvyi wawe ?
( b ) Ni ibiki tuzorimbura ubutaha ?
INDIRIMBO : 60 , 22
Ni kamere izihe zotuma tuba nk’ibumba rigumaraye maze ntitwumve impanuro za Yehova ?
Ni ibiki bizodufasha kuguma tworohera Imana kutubumbabumba ?
Abavyeyi bokwerekana gute ko Yehova ari Umubumvyi wabo ?
Ni kubera iki Imana yabona ko Daniyeli ari ‘ umuntu ahimbaye cane , ’ kandi dushobora gute kugamburuka nka Daniyeli ?
( Soma Yeremiya 18 : 6 . )
Ni kamere izihe zishobora gutuma dukomantaza umutima ?
Mu Migani 4 : 23 havuga hati : “ Zigama umutima wawe kuruta ikindi cose kibwirizwa kurindwa , kuko ari wo uvamwo amasôko y’ubuzima . ”
( Soma 2 Ngoma 26 : 3 - 5 , 16 - 21 . )
Vyogenda gute hamwe twoguma dukora igicumuro ?
7 , 8 . ( a ) Ivyashikiye Abisirayeli vyerekanye gute ko kubura ukwizera bituma dukomantaza umutima ?
( b ) Ivyo bitwigisha iki ?
Ni kubera iki dukwiye ‘ kuguma dusuzuma ’ nimba turi mu kwizera , kandi twobigira gute ?
Ni igiki gishobora kudufasha kuba nk’ibumba ryoroshe mu minwe ya Yehova ?
Igikorwa co mu ndimiro gishobora kudufasha gutsimbataza kamere izihe , kandi havamwo ivyiza ibihe ?
Abavyeyi bategerezwa gukora iki nimba bipfuza kubumbabumba neza abana babo ?
Abavyeyi bokwerekana gute ko bizigira Imana igihe umwana wabo aciwe ?
( Soma 1 Abakorinto 5 : 11 , 13 . )
Ni kubera iki dukwiye kwama tugamburukira Yehova , kandi ivyo bizotumarira iki ?
INDIRIMBO : 138 , 112
Ni mu buryo ki Yehova Imana yacu ari “ Yehova umwe ” ?
Twokwerekana gute ko dusenga Imana yacu tuzi ko ari “ Yehova umwe ” ?
Twokora iki kugira tuzigame ubumwe n’amahoro ?
( b ) Kubera iki Musa yavuze ayo majambo ?
Ntasanzwe .
Iyindi nsobanuro y’imvugo ngo “ Yehova umwe ” ni iyihe , kandi Yehova yerekanye gute ko yama ari “ wa wundi nyene ” ?
Ntahindagurika kandi ntahemuka .
8 , 9 . ( a ) Yehova asaba iki abamusenga ?
( b ) Yezu yerekanye gute ko ya majambo Musa yavuga ahambaye cane ?
( Soma Mariko 12 : 28 - 31 . )
10 , 11 . ( a ) Twerekana gute ko Yehova ari we wenyene dusenga ?
( b ) Abasore b’Abaheburayo bari i Babiloni berekanye gute ko bari bihebeye Yehova wenyene ?
Kugira ngo twihebere Yehova wenyene , ni igiki dutegerezwa kubako maso ?
Ni ingeso izihe zoshobora kunyoha urukundo dukunda Yehova ?
Kubera iki intumwa Paulo yibukije abakirisu ko Imana ari “ Yehova umwe ” ?
16 , 17 . ( a ) Ni ubuhanuzi ubuhe buriko buraranguka muri kino gihe , kandi bivamwo iki ?
( b ) Ni ibiki vyoshobora guhungabanya ubumwe bwacu ?
18 , 19 . ( a ) Ni impanuro iyihe dusanga mu Banyefeso 4 : 1 - 3 ?
( b ) Twokora iki kugira dutume ishengero riguma ryunze ubumwe ?
Twokwerekana gute ko dutahura yuko ‘ Yehova Imana yacu ari Yehova umwe ’ ?
Ku nkengera y’amazinga ya Trinité na Tobago , hari ibisagara vyinshi bigirirwamwo uburovyi .
Ivyabona vya Yehova barakunda kuhagendera kugira ngo bayage n’abarovyi
INDIRIMBO : 121 , 75
Kubera iki ishirahamwe ry’Imana ridasanzwe ?
Bibiliya yerekana gute ko twese tudatunganye ?
Twokora iki ku bijanye n’amakosa yacu be n’ay’abandi ?
Bibiliya yamenyesheje gute ibijanye n’iyongerekana ry’abasavyi b’Imana ?
Abasavyi b’Imana berekanye gute urukundo ?
( Soma Mika 4 : 1 , 3 . )
Ivyo vyatumye baguma “ [ ba ] cuna ku maraso y’abantu bose . ” ​ — Ivyak . 20 : 26 .
Ni kubera iki iyongerekana ry’abasavyi ba Yehova ritangaje ?
Ni kubera iki vyoshika abandi bakatubabaza ?
( Soma Abaroma 5 : 12 , 19 . )
Iyo uza kuba uri muri Isirayeli mu gihe ca Eli n’abahungu biwe , wari kuvyifatamwo gute ?
Ni gute Dawidi yacumuye bimwe bikomeye , kandi Imana yakoze iki ?
( a ) Ni gute intumwa Petero yihindukije mw’ijambo ?
( b ) Inyuma y’aho Petero akoreye ikosa , kubera iki Yehova yabandanije kumukoresha ?
Ni ibiki Yezu yatahura ku bijanye n’amakosa ya Yuda Isikariyoti n’aya Petero ?
Bibiliya yavuze iki ku vyerekeye abasavyi ba Yehova bo muri kino gihe ?
Dukwiye kuvyifatamwo gute igihe abandi bakoze amakosa ?
13 , 14 . ( a ) Kubera iki dukwiye kwihanganirana ?
( b ) Ni umuhango uwuhe dukwiye kwama twibuka ?
Ariko rero ntiturashika mw’isi nshasha .
Dukwiye gukora iki igihe abandi bakoze amakosa ?
( Soma Matayo 5 : 23 , 24 . )
Nk’uko Yehova yabababariye ata gahigihigi , namwe nyene mugenze mutyo . ”
Vyoba vyari bibereye ko baba inzirabugunge ?
Ivyo tubibonera ku vyo Bibiliya ivuga ku bijanye n’ugutahura be n’ubukerebutsi .
Mu Migani 3 : 13 - 15 hagira hati : “ Hahiriwe umuntu yaronse ubukerebutsi , n’umuntu aronka ugutahura , kuko kubwunguka ari vyiza kuruta kwunguka ifeza , kandi kubwimbura ni vyiza kuruta kwimbura inzahabu .
Ni ubw’agaciro kuruta amabuye y’agaciro yitwa korali , mbere n’ibindi bintu vyawe vyose bihimbaye ntivyonganishwa na bwo . ”
None tuvuge iki ku bijanye no kuba inzirabugunge ?
Kubera ko nari umuyobozi w’iryo shirahamwe , nasabwa kuvyumvisha uwaza gusuzuma ivy’amakori , nkamuyengayenga kugira yirengagize ayo manyanga twakora .
Ivyo vyatumye menyekana ko ndangwa n’ubugunge .
Ndaha akarorero keza abahungu banje babiri kandi naratewe uduteka mw’ishengero .
Abasuzuma ivy’amakori be n’abandi dukorana urudandaza , ubu babona ko ndi umuntu w’inzirabugunge . ”
Rusi yarimukiye muri Isirayeli , aho yari gusenga Imana y’ukuri .
31 Ibibazo vy’abasomyi
1 : 16 .
INDIRIMBO : 95 , 13
Uburyo buhambaye kuruta ubundi bwose Yehova yagaragarije abantu ubuntu ata wari abukwiriye ni ubuhe ?
Twokwerekana gute ko tuganzwa n’ubuntu ata wari abukwiriye aho kuganzwa n’igicumuro ?
Ubuntu ata wari abukwiriye bwa Yehova butuma twironkera ivyiza ibihe ?
1 , 2 . ( a ) Vuga muri make ikigereranyo Yezu yatanze cerekeye umurimyi w’imizabibu . ( b ) Ico kigereranyo giserura gute umutima w’ugutanga cane be n’ukugaragaza ubuntu ata wari abukwiriye ?
None sinemerewe gukoresha ivyanje uko nshaka ?
( Soma 2 Abakorinto 6 : 1 . )
Ni kubera iki Yehova yagaragarije abantu bose ubuntu ata wari abukwiriye , kandi yabigize gute ?
Kuba ubuntu ata wari abukwiriye bwa Yehova ‘ bwerekanwa mu buryo butari bumwe ’ bisobanura iki ?
Intumwa Petero yanditse ati : “ Nk’uko umwe wese yaronse ingabirano , muyikoreshe mu gukoreranira nk’ababwiriza beza b’ubuntu ata wari abukwiriye bw’Imana bwerekanwa mu buryo butari bumwe . ”
Intumwa Yohani yanditse ati : “ Twese twaronse bivuye ku kunengesera kwiwe , egome , ubuntu ata wari abukwiriye ku buntu ata wari abukwiriye . ”
Twungukira gute ku buntu ata wari abukwiriye bwa Yehova , kandi twerekana gute ko tubukenguruka ?
( Soma 1 Yohani 1 : 8 , 9 . )
Ubuntu ata wari abukwiriye bw’Imana budushoboza iki ?
Uburyo Imana itugaragariza ubuntu ata wari abukwiriye : Agateka ko kwumva inkuru nziza ( Raba ingingo ya 11 )
Abarobanuwe bazana gute “ izindi ntama ” ku bugororotsi ?
( Soma Daniyeli 12 : 3 . )
Isengesho rifitaniye isano gute n’ubuntu ata wari abukwiriye bw’Imana ?
Ni gute ubuntu ata wari abukwiriye butuma ‘ dutabarwa ku gihe nyaco ’ ?
Ubuntu ata wari abukwiriye bwa Yehova bufasha gute imitima yacu ?
Ni icizigiro ikihe dukesha ubuntu ata wari abukwiriye bw’Imana ?
( Soma Zaburi 49 : 7 , 8 . )
Ni gute abakirisu bamwebamwe bafashe ukutari kwo ubuntu ata wari abukwiriye bw’Imana ?
Ni impanuro ikomeye iyihe Petero yatanze ?
Ubuntu ata wari abukwiriye bwa Yehova butuma tugira ibanga irihe ?
Ni igiki tuzorimbura mu kiganiro gikurikira ?

20 : 24 .
INDIRIMBO : 101 , 84
Ubuntu ata wari abukwiriye bwa Yehova bukwiye gutuma dukora iki ?
“ Inkuru nziza y’ubwami ” ishira ahabona gute ubuntu ata wari abukwiriye bw’Imana ?
Mw’isi nshasha , Yehova azokwerekana gute ubuntu ata wari abukwiriye bwiwe ?
Intumwa Paulo yerekanye gute ko yakenguruka ubuntu ata wari abukwiriye bw’Imana ?
Intumwa Paulo yavuze ati : “ Ubuntu ata wari abukwiriye [ bw’Imana ] nagiriwe ntibwabaye impfagusa . ”
( Soma 1 Abakorinto 15 : 9 , 10 . )
Ni ubusuku budasanzwe ubuhe Paulo yashinzwe ?
( Soma Abanyefeso 3 : 5 - 8 . )
Kubera iki twovuga ko “ inkuru nziza y’ubwami ” ari cokimwe n’inkuru nziza y ’ “ ubuntu ata wari abukwiriye bw’Imana ” ?
Igihe dusigurira abantu ibijanye n’incungu , ni gute tuba turiko tubamenyesha inkuru nziza y’ubuntu ata wari abukwiriye bw’Imana ?
Kubera iki abantu b’abacumuzi bakeneye gusubiza hamwe n’Imana ?
Intumwa Yohani yanditse ati : “ Uwizera Umwana arafise ubuzima budahera ; uwugambararira Umwana ntazobona ubuzima , ahubwo uburake bw’Imana buguma kuri we . ”
9 , 10 . ( a ) Ni ibanga irihe Kristu yashinze abavukanyi biwe barobanuwe ?
Iyo abantu batahuye ko bashobora gusenga Yehova , ni kubera iki aba ari inkuru nziza ?
Abantu benshi basenga kubera ko bituma bumva baremurutse , ariko ntibemera yuko vy’ukuri Imana yumva amasengesho yabo .
Barakeneye kumenya ko Yehova ‘ yumva amasengesho . ’
Umwanditsi w’amazaburi Dawidi yavuze ati : “ Wewe wumva amasengesho , emwe , abantu b’ubwoko bwose bazoza kuri wewe .
13 , 14 . ( a ) Ni uduteka tudasanzwe utuhe tubikiwe abarobanuwe ?
( b ) Ni igikorwa gishimishije ikihe abarobanuwe bazokorera abantu ?
Muri kazoza , Yehova azogaragariza gute abo mu “ zindi ntama ” ubuntu bwiwe ?
Abantu amamiliyoni bapfuye bataramenya Imana , na bo nyene bazozuka .
Ni igiki dukwiye kwama twibuka igihe dushinga intahe ?
Dushemeza gute ubuntu ata wari abukwiriye bwa Yehova ?
Bibiliya ivuga iti : “ Ivyaremwe na vyo bizogirwa ivyidegemvya [ bive ] mu buja bw’ukubora , [ bigire ] umwidegemvyo w’ubuninahazwa w’abana b’Imana . ”
Emwe , igihe tubwiye abandi inkuru nziza tubigiranye umwete , tuba dushemeje ubuntu ata wari abukwiriye bwa Yehova !
“ Mubandanye kurondera ubwami [ bw’Imana ] , ivyo bintu na vyo muzovyongerwa . ” ​ — LUKA 12 : 31 .
INDIRIMBO : 40 , 98
Ivyo dukeneye be n’ivyo twipfuza bitandukaniye he ?
Kubera iki twokwirinda guhahamira ibintu vy’umubiri ?
Kubera iki wemera udakeka ko Yehova ashobora kukuronsa ivyo ukenera buri musi ?
Bimwebimwe mu vyo abantu bipfuza ni ibihe ?
Shetani akoresha gute “ icipfuzo c’amaso ” ?
Niwibuke ko intumwa Yohani yatugabishije ati : “ Isi iriko irahita , n’icipfuzo cayo ni ukwo . ”
Ni ibiki bishobora gushikira abakora batiziganya kugira ngo barundanye ibintu vy’umubiri ?
Ivyashikiye Baruki bitwigisha iki ?
8 , 9 . ( a ) Kubera iki tudakwiye guhagarika umutima birenze ku bijanye n’ivyo dukenera ?
( b ) Ni ibiki Yezu yari azi ku bijanye n’abantu be n’ivyo bakenera ?
Soma Matayo 6 : 25 .
Igihe Yezu yigisha abayoboke biwe ingene bosenga , yavuze ko bakwiye gushira imbere iki ?
Ukuntu Yehova yitwararika inyoni zo mu kirere bitwigisha iki ?
Soma Matayo 6 : 26 .
Turakwiye ‘ kwihweza neza inyoni zo mu kirere . ’
Ni igiki cerekana ko turi n’agaciro kuruta inyoni zo mu kirere ?
Ni igiki umuntu yiganyira adashobora gukora ?
Soma Matayo 6 : 27 .
15 , 16 . ( a ) Ukuntu Yehova yitwararika amalisi yo mw’itongo bitwigisha iki ?
( Raba ishusho itangura . ) ( b ) Ni ibibazo ibihe twoshobora kwibaza , kandi kubera iki ?
Soma Matayo 6 : 28 - 30 .
Ni igiki coshobora kwonona ubucuti dufitaniye na Yehova ?
Soma Matayo 6 : 31 , 32 .
Ni ibiki Yehova azi ku bijanye n’umwe wese muri twebwe , kandi aca adukorera iki ?
Kubera iki tudakwiye guhagarika umutima ku bijanye n’ivyoshika muri kazoza ?
Soma Matayo 6 : 34 .
( b ) Wokora iki kugira ngo woroshe ubuzima ?
Ni igiki kizotuma urushiriza kwiyegereza Yehova ?
INDIRIMBO : 136 , 129
duhanzwe n’akosho ka Shetani ?
duhanzwe n’impwemu y’isi ?
turi abanyantege nke ?
Tanga akarorero kerekana igituma bihambaye ko tumenya aho igihe kigeze be n’ibiriko biraba .
Ni kubera iki Yezu yabwiye abigishwa biwe ngo ‘ bagume bari maso ’ ?
Kubera iki twitaho cane ingabisho Yezu yatanze ?
( a ) Kubera iki twokwemera ko ubu Yezu azi igihe Harumagedoni izozirako ?
( b ) Naho tutazi igihe ya makuba akomeye azotangurira , ni igiki tutokekeranya ?
( Soma Habakuki 2 : 1 - 3 . )
Tanga akarorero kerekana ko ivyo Yehova avumereye vyama biranguka ku gihe cashinzwe .
Ivyo Yehova yavumereye vyamye biranguka ku gihe cashinzwe .
Gatoyi inyuma y’aho , Yehova yabwiye Aburahamu ati : “ Umenye neza yuko uruvyaro rwawe ruzocika kavamahanga mu gihugu kitari icabo , kandi bazobwirizwa gukorera abantu baho , kandi bano bazobateza amarushwa imyaka amajana ane . ”
Yosuwa ni umwe muri abo bakuwe mu Misiri .
7 , 8 . ( a ) Kera inderetsi yari ijejwe iki , kandi ivyo bitwigisha iki ?
( b ) Tanga akarorero kerekana ivyashobora kuba , bishitse inderetsi zigasinzira .
Muri kino gihe , ni ibiki abantu benshi batazi ?
10 , 11 . ( a ) Ni igiki dukwiye kubako maso , kandi kubera iki ?
( b ) Wemezwa n’iki ko Shetani yoheje abantu ngo ntibiteho ubuhanuzi bwo muri Bibiliya ?
Kubera iki tudakwiye kwemera guhendwa na Shetani ?
Yezu yatugabishije ati : “ Mugume mwiteguye , kubera ko Umwana w’umuntu azoza kw’isaha mutiyumvira . ”
Impwemu y’isi yosha abantu gukora iki , kandi twokwirinda gute iyo nyosha iteye akaga ?
Ni ingabisho iyihe dusanga muri Luka 21 : 34 , 35 ?
( Soma Luka 21 : 34 , 35 . )
Ni igiki cashikiye Petero , Yakobo na Yohani , kandi ni gute na twebwe coshobora kudushikira ?
Twisunze Luka 21 : 36 , Yezu yavuze ko twokora iki kugira ‘ tugume turikanuye ’ ?
( Soma Luka 21 : 36 . )
4 : 7 . Twokora iki kugira ngo twitegurire ivyimirije gushika vuba ?
Kw’iteraniro rimwe , hari umuvukanyi yambajije nimba notangura kwamamaza .
Hari mushiki wacu umwe yigisha abana ivyigwa bishingiye kuri Bibiliya akoresheje igitabu Inanga y’Imana .
Twebwe dusabwa gusa kubwira abantu inkuru nziza , ivyo guca urubanza na vyo ni ivya Yehova . ”
Hari uwundi muvukanyi ahumuye yanyigishije yuko rimwe na rimwe bisaba kwihangana kugira turonke agahimbare kava ku gutanga .
Umukenyezi wiwe ntiyakunda Ivyabona vya Yehova .
Abo muri uwo muryango bose bahavuye babatizwa .
Ntitwari tuzi ko abapadiri ari bo bica bagakiza .
Kubera ko ntari bwigere ngendera mu mazi , nararyohewe cane .
Twamaze imyaka itanu twamamaza canecane mu mazinga ya kure , aho ata Cabona n’umwe yaharangwa .
Kenshi baraduha amafi , amavoka be n’ivyema .
Ntiworaba ingene bamwe muri bo bafatana uburemere iryo banga .
Dushitseyo , narahuye na mushiki wacu umwe w’umumisiyonari yasa n’irirenga yitwa Maxine Boyd , maze ndamukunda .
Nk’akarorero , mu kigwati ca Potala Pastillo , hari imiryango ibiri y’Ivyabona yari ifise abana benshi .
Yagira agende muri Équateur iyo yari arungitswe , maze atubaza ati : “ Muranyibuka ?
Nathan Knorr , akaba ari we yari ahagarikiye igikorwa c’Ivyabona vya Yehova , yaraje i Porto Riko .
Mu nyuma , yarankariye ambwira ko nkwiye kuba umuntu atunganya neza ibintu , yongera avuga ko ntari meze nk’uko yanziga .
Dawe ntiyakiriye ukuri igihe twe na mawe twizera .
Umukenyezi wanje nakunda Maxine yapfuye mu 2011 .
Ndashashaye cane gusubira kumubona yazutse .
Bamwe mu baza kundaba usanga bipfuza ko tuganira ibijanye n’ingorane zibega canke iz’umuryango wabo .
Aho dukorera Yehova haba hehe , turafise uturyo two kumushemeza .
Inkuru y’ubuzima ya Leonard Smith yasohotse mu Munara w’Inderetsi wo ku wa 15 Ndamukiza 2012 .
INDIRIMBO : 36 , 11
Ni kubera iki twovuga ko umubano w’ababiranye ari ingabirano iva ku Mana ?
Ivy’umubano vyari vyifashe gute kuva mu gihe ca Adamu gushika mu gihe ca Yezu ?
Ni igiki cofasha umukirisu kumenya nimba yokwubaka urwiwe ?
1 , 2 . ( a ) Umubano w’ababiranye watanguye gute ?
( b ) Ni igiki umugabo n’umugore ba mbere bategerezwa kuba baratahuye ku bijanye n’umubano ?
( Soma Itanguriro 2 : 20 - 24 . )
Intumbero nyamukuru y’umubano yari iyihe ?
Intumbero nyamukuru y’umubano kwari ukurondoka no kwuzuza isi .
Ni ibiki vyashikiye umubano wa mbere ?
Ni igiki twigira ku vyo Adamu na Eva bishuye Yehova ?
Wosigura gute ibivugwa mw’⁠Itanguriro 3 : 15 ?
( a ) Ni ibiki vyashikiye umubano inyuma y’ubugarariji bwa Adamu na Eva ?
( b ) Bibiliya isaba iki abagabo n’abagore ?
Ivy’umubano vyari vyifashe gute kuva mu gihe ca Adamu gushika kuri rya Segenya ?
Yehova yakoreye iki ababisha mu gihe ca Nowa , kandi ivyashitse ico gihe bitwigisha iki ?
( a ) Ni ingeso izihe zahavuye zibonwa nk’izisanzwe mu mihingo imwimwe ?
( b ) Aburahamu na Sara batanze gute akarorero keza mu mubano wabo ?
( Soma 1 Petero 3 : 3 - 6 . )
Itegeko rya Musa ryakingira gute Abisirayeli ?
( Soma Gusubira mu vyagezwe 7 : 3 , 4 . )
12 , 13 . ( a ) Mu gihe ca Malaki , abagabo bamwebamwe bafata gute abagore babo ?
( b ) Muri iki gihe , bishitse umukirisu akarenga ibigo n’umugore canke umugabo w’abandi , ingaruka zoba izihe ?
Ni uruhara uruhe rya Tegeko ryaranguye ?
( a ) Ni ingingo iyihe ishengero rya gikirisu ryokwisunze mu bijanye n’umubano ?
Yezu yavuze iki ku bijanye no kutubaka ?
Yongeyeko ati : “ Nimba bibananiye kwigumya , nibubake , kuko ari vyiza kwubaka kuruta kururumba . ”
18 , 19 . ( a ) Umukirisu akwiye kwubakana n’umuntu ameze gute ?
( b ) Ni ibiki tuzokwihweza mu kiganiro gikurikira ?
INDIRIMBO : 87 , 3
Ni uruhara uruhe Imana yashinze abagabo be n’abagore ?
Kubera iki urukundo n’ikibabarwe bihambaye cane mu mubano ?
Bibiliya ishobora gute gufasha , igihe mu mubano hadutse ingorane ?
Naho mu ntango abubaka izabo baba banezerewe , ni ibiki bokwitega ?
Ni ubwoko butandukanye ubuhe bw’urukundo abubatse bakwiye kugaragaza ?
Abubakanye bakwiye gukundana ku rugero rungana iki ?
Paulo yanditse ati : “ Bagabo , mubandanye gukunda abagore banyu nk’uko na Kristu yakunze ishengero akaryigura . ”
( Soma Yohani 13 : 34 , 35 ; 15 : 12 , 13 . )
4 , 5 . ( a ) Kuba umugabo ari umutwe w’urugo bituma agira ibanga irihe ?
( b ) Umugore akwiye kubona gute ubukuru bw’umugabo wiwe ?
( c ) Ni ibiki umugore umwe n’umugabo wiwe babwirijwe guhindura ?
Igihe nubaka vyarahindutse , kuko naciye niga kuza nditura umugabo wanje .
Naho bitari vyoroshe , kwisunga ubuyobozi Yehova atanga vyatumye turushiriza kwiyegerezanya . ”
Maze kwubaka vyarushirije kuba urugamba , kuko nazirikana abantu babiri .
Ni gute urukundo ruba “ umugozi utagira akanenge wunga ubumwe ” igihe havyutse ingorane mu mubano ?
7 , 8 . ( a ) Ni impanuro iyihe Bibiliya itanga ku bijanye no kurangura amabanga y’abubatse ?
( b ) Kubera iki abubakanye bakwiye kugaragarizanya ikibabarwe ?
( Soma 1 Abakorinto 7 : 3 - 5 . )
Akenshi usanga umugabo anyaruka kwumva ko avyiteguriye kuruta umugore .
Kubera iki bitemewe ko umuntu agirira inambu uwo batubakanye ?
10 , 11 . ( a ) Abantu bahukana ku rugero rungana iki ?
( b ) Bibiliya ivuga iki ku bijanye n’ugutandukana ?
( c ) Ni ibiki vyofasha umuntu kutihutira gutandukana n’uwo bubakanye ?
Ni ibiki vyoshobora gutuma abubatse biyumvira ivyo gutandukana ?
Ni imvo zumvikana izihe zotuma umuntu atandukana n’uwo bubakanye ?
Bibiliya ibwira iki abakirisu bubakanye n’abadasenga Yehova ?
( Soma 1 Abakorinto 7 : 12 - 14 . )
15 , 16 . ( a ) Ni impanuro iyihe Bibiliya iha abakenyezi bafise abagabo badasenga Yehova ?
( b ) Umukirisu yokora iki mu gihe uwo bubakanye atizera ahisemwo kugenda ?
Intumwa Petero ahanura abakenyezi bakirisu kuyobokera abagabo babo , “ kugira ngo nimba hari abatagamburukira rya jambo , bagondozwe ata jambo rivuzwe , biciye ku ngeso z’abagore babo , kubera biboneye ingeso [ zabo ] zitanduye ziri kumwe n’icubahiro kigera kure . ”
Bibiliya ivuga iti : “ Nimba uwutemera agiye , nagende ; mwene wacu canke mushiki wacu ntahambirwa igihe ibintu vyifashe gutyo , mugabo Imana yabahamagariye amahoro . ”
Ni ibiki abakirisu bubakanye bakwiye gushira imbere ?
Kubera iki abakirisu bashobora gutuma umubano wabo uroranirwa ?
[ 1 ] ( ingingo ya 5 ) Si ko basanzwe bitwa .
[ 2 ] ( ingingo ya 13 ) Raba amayagwa y’inyongera avuga ngo “ Ico Bibiliya ivuga ku bijanye n’ukwahukana be n’ugutandukana , ” mu gitabu “ Mwigumize mu rukundo rw’Imana . ”
INDIRIMBO : 45 , 70
Wokora iki kugira utere imbere mu vy’impwemu ?
Ushobora gute gutera imbere mu vy’impwemu ata kurambirwa ?
Ni ibiki wohindura bigatuma uba kirumara mu murimo ?
1 , 2 . ( a ) Ibivugwa muri Yesaya 60 : 22 biriko biranguka gute muri kino gihe c’iherezo ?
( b ) Muri iki gihe , hakenewe iki mu gice co kw’isi c’ishirahamwe rya Yehova ?
“ UMUTOYI azocika igihumbi , uwo hasi na we acike ihanga rikomeye . ”
Ni imigambi iyihe wokwishingira mu vy’impwemu ?
Soma 1 Timoteyo 3 : 1 .
Abakiri bato bokoresha gute inguvu zabo mu gikorwa c’Ubwami ?
( Soma Imigani 20 : 29 . )
6 - 8 . ( a ) Umusore umwe yahinduye gute ingene yabona ivyo gukorera Imana , kandi havuyemwo iki ?
( b ) Dushobora gute ‘ guhonja tukabona ko Yehova aryoshe ’ ?
Ivyiza yankoreye bituma numva ko ndamufitiye ideni , ngaca ndushiriza gukora vyinshi maze nkironkera imihezagiro myinshi . ”
( Soma Zaburi 34 : 8 - 10 . )
Ni kubera iki bihambaye ko uba umuntu ‘ arindira ’ ?
Ni kamere izihe twokwihatira gutsimbataza , kandi ni kubera iki zihambaye ?
Abagize ishengero bashobora gute kuba abizigirwa ?
Wokwigana gute Yozefu igihe abandi bakurenganije ?
Wokora iki bishitse abandi bakakurenganya ?
14 , 15 . ( a ) Kubera iki dutegerezwa ‘ kwama twiyubara ’ ku kuntu twigisha ?
( b ) Twohuza gute n’uko ibintu biba vyifashe ?
( Raba ishusho itangura be n’uruzitiro ruvuga ngo “ Woba wogerageza ubundi buryo ? ” )
Twokora iki kugira ngo ugushinga intahe ku mugaragaro bivemwo ivyiza ?
17 , 18 . ( a ) Ushobora gute guhera ubwoba igihe ushinga intahe ku mugaragaro ?
( b ) Ni kubera iki ubona ko icipfuzo Dawidi yari afise co gushemeza Yehova gihambaye mu gikorwa co mu ndimiro ?
Vyongeye , turasaba ibindi Vyabona bakaduterera ivyiyumviro . ”
Ubu Eddie si we abona harageze ko aja gushinga intahe ku mugaragaro .
( Soma 1 Timoteyo 4 : 15 . )
Bazoyaga ubuninahazwa bw’ingoma yawe , bongere bavuge ubushobozi bwawe , kugira abana b’abantu bamenyeshwe ibikorwa vyiwe vy’inkomezi , be n’ubuninahazwa bw’ubwiza bwakaka bw’ingoma yiwe . ”
Nimba ufise vyinshi ukora mw’ishirahamwe rya Yehova , ushobora gute kubera abandi umuhezagiro ?
Ubu Venecia avuga ati : “ Kwamamaza ukoresheje telefone ni ivya mbere ! ”
Ubu haraciye imyaka itatu umukenyezi wanje apfuye , mu mwaka uheze na ho , umuhungu wanje yarahitanywe n’isanganya . ”
Inyuma y’imyaka ibiri ihaciye , ndabandikiye narabatijwe . ”
INDIRIMBO : 93 , 96
Kubera iki dukwiye gufasha umutohoji wa Bibiliya gukunda kwiyigisha Bibiliya ?
Dushobora gute kumenyereza abashasha kuganiriza abo basanze ku muhana be n’abandi ?
Kubera iki dukwiye kugira utwigoro two kumenyereza abazoshobora kuba abungere b’ubusho bw’Imana ?
Ni kubera iki dukwiye kumenyereza abandi kugira babe abashoboye kurangura ibikorwa mw’ishirahamwe ?
3 , 4 . ( a ) Paulo yerekanye gute ko kwiyigisha Ivyanditswe bifitaniye isano no kuba kirumara mu gikorwa ?
( b ) Kugira turemeshe abatohoji ba Bibiliya kwiyigisha , ni igiki dukwiye kubanza gukora ?
Nuvuge ivyo twoshobora gukora kugira dufashe abashasha kwama biyigisha Bibiliya .
Hari aho wokwibaza uti : ‘ Noremesha gute umutohoji kwama yiyigisha Bibiliya ? ’
Numuremeshe gusoma buri nomero y’Umunara w’Inderetsi na Be maso !
( a ) Wofasha gute umutohoji gukunda Bibiliya bivuye ku mutima ?
( b ) Ni gute umutohoji akunda Bibiliya abikuye ku mutima yoshobora kwiyumva ?
Yezu yamenyereje gute abamamaji b’inkuru nziza ?
8 , 9 . ( a ) Yezu yaganiriza abantu gute ?
( b ) Twofasha gute abamamaji bashasha kwigana Yezu igihe bayagisha abantu ?
10 - 12 . ( a ) Yezu yakurikiranye gute abashimishwa n’inkuru nziza ?
( b ) Twofasha gute abamamaji bashasha kuryohora ubuhanga bwabo bwo kwigisha Ijambo ry’Imana ?
13 , 14 . ( a ) Uburorero bwo muri Bibiliya bw’abantu bitanze cane ku bw’ineza y’abandi bukwigisha iki ?
( b ) Ni mu buryo bufadika ubuhe womenyereza abashasha be n’abakiri bato kugaragariza urukundo abo basangiye ukwemera ?
Kubera iki bihambaye ko abakurambere bafasha abagabo bo mw’ishengero gutera imbere ?
16 , 17 . ( a ) Paulo yitwararitse gute iterambere rya Timoteyo ?
( b ) Abakurambere bomenyereza neza gute abazoba abungere b’ishengero ?
Kubera iki bihambaye ko tumenyereza abandi mu gikorwa ca Yehova ?
Kubera iki wokwemera udakeka ko utwigoro ugira mu kumenyereza abandi mu murimo wa Yehova tutazoba impfagusa ?
Mureka ibwirizwa ry’Imana , mukagumya umugenzo w’abantu . ” ​ — Mrk . 7 : 6 - 8 .
INDIRIMBO : 81 , 32
Yehova yakomeje gute amaboko ya Musa , aya Asa n’aya Nehemiya ?
Yehova akomeza gute amaboko yacu muri kino gihe ?
Ni mu buryo ngirakamaro ubuhe twokomeza amaboko y’abavukanyi na bashiki bacu ?
Woba utahura uwo mushiki wacu ?
( b ) Ni ibiki vyoshobora gutuma amaboko yacu aregera ?
Nk’akarorero , iravuga ukuboko incuro amajana n’amajana .
Woronka gute ingoga n’inkomezi vyotuma wihangana , ntutakaze umunezero ?
( b ) Ni ibiki tugiye kurimbura ?
Soma Zefaniya 3 : 16 , 17 .
Ariko rero amaboko ya Musa aremerewe agatangura kumanuka , Abamaleki baca batangura gutsinda .
( b ) Imana yishuye gute isengesho rya Nehemiya ?
( Soma Nehemiya 1 : 10 ; 2 : 17 - 20 ; 6 : 9 . )
Woba none wemera yuko Yehova akoresha ‘ ububasha bwiwe buhambaye be n ’ ‘ ikiganza ciwe gikomeye ’ kugira ngo akomeze abasavyi biwe bo muri iki gihe ?
10 , 11 . ( a ) Shetani agerageza gute gutuma amaboko yacu aregera ?
( b ) Yehova akoresha iki mu kuduha inkomezi ?
Arakoresha intwaro , indongozi z’amadini be n’abahuni kugira ngo batuvuge uko tutari kandi badutere ubwoba .
13 , 14 . ( a ) Umuvukanyi umwe yaremeshejwe gute inyuma y’aho aburiye umukenyezi wiwe ?
Isengesho be n’ukwiyigisha vyarambereye nka ka gakoti gakingira umuntu gusoma nturi .
Nahavuye ntahura ko bihambaye yuko tugiranira ubucuti bwiza na Yehova , imbere y’uko ingorane zaduka . ”
INDIRIMBO : 60 , 38
Yakobo na Rasheli ?
Yozefu ?
Paulo ?
Imana itumenyereza gute kurwanya abansi bacu ?
Vyongeye , aradufasha biciye ku bitabu vyacu bishingiye kuri Bibiliya , ku makoraniro , ku materaniro no ku mahwaniro .
Twokwirinda gute gutsindwa n’ikibi ?
( b ) Ni uburorero bwa bande tugiye kurimbura ?
Ni igiki catumye Yakobo yumirako , kandi yaronse impera iyihe ?
( Soma Itanguriro 32 : 24 - 28 . )
( Raba ingingo ya 10 , 11 )
Abakirisu babiri bafashijwe gute gucungera ivyipfuzo bibi ?
Yaciye avuga ati : “ Ku bw’ivyo , nibaza ko nshobora kuguma ndi umwizigirwa buri musi .
Ndakengurukira Yehova kubona akoresha ishirahamwe ryiwe kugira adufashe gusimba akaga buri musi muri iyi si mbi . ”
Rimbura kandi akarorero ka mushiki wacu wo muri Leta Zunze Ubumwe za Amerika .
Yanditse ati : “ Nshaka kubakengurukira ukuntu mwama mutugaburira ivyo nyene dukeneye , kandi ku gihe kibereye .
Akenshi mbona ko ivyo biganiro ari jewe nyene bigenewe .
Ndamaze imyaka n’iyindi nyinyana n’icipfuzo gikomeye co gukora ivyo Yehova yanka .
Birashika nkumva notana n’akabando .
Ndazi ko Yehova ari umunyembabazi be n’uko aharira . Ariko kubera yuko mfise ico cipfuzo kibi kandi muri jewe nkaba ntarakizinukwa , numva umengo simbereye gufashwa na we .
Iyo ntambara idahera yarangiriye nabi mu mice yose y’ubuzima . . . .
( a ) Paulo yabona gute urugamba yarimwo ?
Soma Abaroma 7 : 21 - 25 .
INDIRIMBO : 34 , 61
Itegeko Imana yahaye Abisirayeli ritwigisha iki ku bijanye n’inyambaro ?
( Soma Gusubira mu vyagezwe 22 : 5 . )
Ni igiki cofasha abakirisu guhitamwo neza impuzu bambara ?
Ni ryari canecane dukwiye kwambara mu buryo bubereye ?
Ariko ntiwumve , hari impuzu usanga zibereye mu karere kanaka ariko zitabereye mu kandi .
Soma 1 Abakorinto 10 : 31 .
Soma Abafilipi 2 : 4 .
( Soma 1 Abakorinto 10 : 32 , 33 . )
Ni ibiki vyofasha umuvukanyi kumenya nimba yotereka ubwanwa canke atobutereka ?
Rya Tegeko Imana yatanga biciye kuri Musa ryarasaba abagabo gutereka ubwanwa .
Ukuntu twambara n’ukuntu twitunganya bikwiye kugira ico bikoze gute ku bandi ?
INDIRIMBO : 41 , 69
Barayisuzugura cane ku buryo abanyeshure baca bemera ko ibiriho vyabayeho biciye kw’ihindagurika . ”
Uwundi mushiki wacu akiri muto wo mu Bufaransa yavuze ati : “ Abigisha bo kw’ishure iwacu , baratangara cane kubona hariho abanyeshure bacemera ivyo Bibiliya ivuga . ”
Naradusomye nitonze incuro n’izindi . ”
Birerekana ko abahinga karuhariwe boshobora kwigana ibintu , mugabo ko batazokwigera bigana ijana kw’ijana ibintu bihanitse biri mu bidukikije . ”
Kubera iki Imana yipfuza ko ukoresha ububasha bwawe bwo kwiyumvira ?
( Soma Abaroma 12 : 1 , 2 ; 1 Timoteyo 2 : 4 . )
Narafashe umwanya ndazirikana , ndabona ingene izo mfungurwa za Pasika zagereranya ikintu kidasanzwe ! ”
Ni igiki catumye uwo mushiki wacu atahura ibintu gutyo ?
Twararonse amahoro , turunga ubumwe kandi turakundana . ”
Abandi na bo usanga batacemera Imana kubera ko amadini yabavunye umutima .
Uwo muhinga yongeyeko ati : “ Umuntu aravye ukuntu mbere n’akanyabuzima gasanzwe cane usanga gahanitse , arumirwa . ”
Yanditse ati : “ Inzu yose yubakwa n’umuntu , mugabo uwubatse ibintu vyose ni Imana . ”
INDIRIMBO : 88 , 115
Ni kubera iki bihambaye ko umenya neza abana bawe ?
Abana bacu bagenda baragira ukwizera intambwe ku yindi . ”
Ambaza ati : ‘ Bibiliya ibivugako iki ? ’
‘ Woba wemera ivyo ivuga ? ’
‘ Kubera iki uvyemera ? ’
Ashaka ko nishura mu majambo yanje bwite , aho gusubiramwo ivyo we na mawe bambwira .
Uko nkura , ni ko ngenda ndatanga inyishu zagutse . ”
( Soma Luka 2 : 46 . )
Barishuye ibibazo vyanje vyose bakoresheje Bibiliya . ”
( Soma Gusubira mu vyagezwe 6 : 5 - 8 ; Luka 6 : 45 . )
Nimba none ibinyabuzima vyabanje kuba ibisanzwe mu nyuma bigahinduka ibihanitse , ni kubera iki ivyo binyabuzima vya kera vyari bisanzwe bihanitse ukuraho ?
Ico kintu carankoze cane ku mutima , nca ndakiganira n’umuhungu wanje . ”
Yaciye asaba umwe wese ngo amutegurire igikombe c’agakawa .
Asigura ati : “ Bagateguye bavyitondeye .
Ndababajije igituma , bambwiye yuko bashaka ko kamera nk’uko nyene ndavyipfuza .
Naciye ndabasigurira yuko Imana na yo nyene yavanze imyuka iri mu kirere ivyitondeye , ku rugero nyene tuyikeneyeko . ”
None hagati y’uwakoze indege n’Uwaremye inyoni , wumva ari nde afise ubwenge bwinshi ? ”
Sebibondo umwe yavuze ati : “ Ntiwigere urambirwa no kurondera uburyo bushasha bwo gusigura ivyo wigeze kubasigurira . ”
Kuva bakiri bato cane , buri musi narafata iminota 15 yo kubigisha , kiretse ku misi y’amakoraniro .
Buhoroburo , vyinshi muri vyo narabironkeye inyishu mu makoraniro , mu gusenga kwo muryango no mu kwiyigisha .
Ni co gituma abavyeyi bakwiye kwamizako mu kwigisha abana babo . ”
Nimureke abana banyu bibonere ko mwizigira Yehova koko .
Bavuga bati : “ Turabwira umukobwa wacu mukuru duti : ‘ Niwizigire Yehova uherejeko , ugume ufise vyinshi ukora mu murimo w’Ubwami , kandi ntiwiganyire birenze . ’
Iyo abonye ivyiza bivamwo , aca atahura ko Yehova ariko aradufasha .
Ivyo vyatumye yizigira Imana na Bibiliya bimwe bidasanzwe . ”
Ikiganiro ca mbere kirerekana ingene twokwongereza ukwizera kwacu kandi tukaguma tugukomeza .
Nk’uko vyavuzwe na Thomas Mclain
Reka ndababwire iyo ico kiyago cazananye .
NAVUKIYE i Wichita muri leta ya Kansas muri Amerika , ku wa 10 Kigarama 1936 , nkaba nari imfura mu bana bane .
Mu nyuma haraje umusoda , noneho nya mudogoteri aca aratontoma ati : “ Vugutira umuti iki kinyabwoba ! ”
Uwo musoda yarabonye ko nya mugabo yari yaborewe , aca amubwira ati : “ Ja kuryamika izo nzoga ! ”
Bompi baciye bagenda .
Aho i Wichita , dawe yari ahafise ibibanza bibiri vyo kumweramwo , kandi nya mudogoteri yari umukiriya wiwe .
Ndi kumwe n’abavyeyi banje , tugiye kw’ihwaniro i Wichita mu myaka ya 1940
Barakoranye umwete , Yehova na we arabahezagira , maze ishengero riravuka .
Mu nyuma , hari mushiki wacu ageze mu zabukuru yatanguye kwitaba amakoraniro .
Twahavuye turungikwa kuba abatsimvyi badasanzwe i Walnut Ridge muri Arkansas .
Mu 1962 , twarahimbawe no kuronka ubutumire bwo kwitaba Ishure rigira 37 rya Gileyadi .
Haciye igihe gito , twaribarutse agakobwa kacu k’imfura Kimberly , inyuma y’amezi 17 na ho twibaruka Stephany .
Vyongeye , twarajana na bo gukambika ahantu , maze tugatera ryarenga iruhande y’umuriro .
Twaratunganya ivy’uko abari mu murimo w’igihe cose baza iwacu bakahamara igihe .
Ntiworaba ingene bari babishashaye !
Barababaye cane batangura kurira , baca bavuga ko bipfuza kwiga .
Tubifashijwemwo n’ishirahamwe rya Yehova , twarihatiye kubafasha kumukunda .
Igihe basubirayo , Kimberly na we yaramenyanye na Brian Llewellyn , akaba yakorana na Paul .
Urumva rero ko batenyenye gushika bakwije n’imiburiburi imyaka 23 .
Ico gihe nyene , Brian na Kimberly baratewe agateka ko gukorera kuri Beteli y’i Londres , mu nyuma bimurirwa kuri Beteli yo muri Malawi .
Twaciye tuja mu Kigo ntanganyigisho c’i Patterson .
Mu nyuma twararungitswe kwigisha muri Zimbabwe , hanyuma muri Zambiya .
Mu 2006 , Brian na Kimberly barimukiye hafi yacu kugira ngo barere udukobwa twabo tubiri Mackenzie na Elizabeth .
Paul na Stephany baracari muri Malawi , Paul akaba ari mu bagize Komite y’ishami .
INDIRIMBO : 124 , 79
Kubera iki vyoshobora kuba ngombwa ko duhindura ingene tubona ba kavantara ?
Dushobora gute kugaragariza umutima mwiza ba kavantara ?
Ikirere na co nyene kari akaga .
Igihe nava ku kibuga c’indege , narumvise imbeho ntari bwigere numva mu buzima , nca ntangura kurira . ”
( Soma Kuvayo 23 : 9 . )
Abayuda bavuga ikigiriki baridoze ko abapfakazi babo batafatwa kumwe n’abandi .
Tubimenya canke tutabimenya , imico y’aho twavukiye iratugirako akosho gakomeye .
( Soma 1 Petero 1 : 22 . )
Niwihanganire abariko bagerageza kumenyera igihugu gishasha .
Mu ntango , hari aho vyotugora gutahura ivyiyumviro vyabo canke inyifato yabo .
Muri kino gihe , ni nde abimukira bokwigana mu bijanye no kugaragaza urupfasoni n’ugukenguruka ?
Ubwa mbere , yarubahirije imico y’igihugu yari yimukiyemwo , mu gusaba uruhusha rwo gutorora .
[ 1 ] ( ingingo ya 1 ) Si ko asanzwe yitwa .
INDIRIMBO : 142 , 92
Woba kumbure uri umumisiyonari canke ukaba wagiye gukorera mu gihugu gikeneye abamamaji kuruta ?
( Soma Nehemiya 13 : 23 , 24 . )
( b ) Intumbero yacu twoyishikako gute ?
Igihe twitegurira indimiro , amakoraniro canke insiguro , akenshi usanga tutiyerekezako ivyo dutegura .
Abandanya ati : “ Kubera ko ahanini nshira ubwenge ku majambo niga muri urwo rurimi , hari ukuntu ivyiyumviro vyo mu vy’impwemu mba ndiko ndasoma bincika ntibinkore ku mutima .
Ni co gituma nkunda gutegekanya umwanya wo kwiga Bibiliya be n’ibindi bitabu mu rurimi nonse . ”
Muriel avuga ati : “ Kwamamaza mu rundi rurimi ntiyavyerekwa , naho nyene kera yakunda kwamamaza mu gifaransa , ari rwo rurimi rwiwe kavukire . ”
Serge na we avuga ati : “ Igihe twabona ko biriko birabangamira iterambere ry’umwana wacu , twaciye dufata ingingo yo gusubira mw’ishengero twahozemwo . ”
Niwiyemeze neza ko abana bawe bariko baratahura ukuri ( Raba ingingo ya 14 , 15 )
Ariko kandi , turacishamwo tukagira udukino mw’ilingala canke tukimenyereza ingene tworikoresha mw’ishengero no mu ndimiro , kugira ngo bige urwo rurimi baryohewe . ”
Nugerageze kwiga ururimi runyamahanga kugira ngo ugire uruhara mu makoraniro ( Raba ingingo ya 16 , 17 )
Vyongeye , twarishingiye umugambi wo kwitaba amakoraniro mu gifaransa rimwe mu kwezi , kandi turafata akaruhuko kugira twitabe amahwaniro agirwa mu rurimi rwacu kavukire . ”
( Soma Abaroma 15 : 1 , 2 . )
Twokwerekana gute ko dukunda Ijambo ry’Imana ?
INDIRIMBO : 81 , 134
( Soma Ivyahishuwe 21 : 3 - 6 . )
None ni ibiki vyafashije Aburahamu n’umuryango wiwe kuguma bafise ukwizera gukomeye ?
Isengesho rishobora gute gukomeza ukwizera kwacu ?
( Soma 1 Yohani 5 : 14 , 15 . )
Ni ibigeragezo ibihe vyashikiye abahanuzi bamwebamwe kubera ukwizera kwabo ?
Abandi , nka Eliya , “ barayerereye mu bugaragwa no mu misozi no mu masenga no mu myobo y’isi . ”
( Soma Abaheburayo 12 : 3 . )
INDIRIMBO : 54 , 125
Akarorero ka Nowa kadufasha gute gutahura ico bisobanura kugira ukwizera ?
Ni mu buryo butandukanye ubuhe twogaragaza ko dufise ukwizera ?
Ni kubera iki ukwizera n’urukundo bihambaye ?
Mu Baheburayo 11 : 1 hadondora ukwizera mu buryo bubiri ubuhe ?
Urabona ko ukwizera kwiwe kwakoranye n’ibikorwa vyiwe kandi biciye ku bikorwa vyiwe ukwizera kwiwe kukagirwa ukutagira akanenge . ”
Nk’akarorero , Yohani yasiguye ati : “ Uwizera Umwana arafise ubuzima budahera ; uwugambararira Umwana ntazobona ubuzima , ahubwo uburake bw’Imana buguma kuri we . ”
( Soma Luka 10 : 21 . )
Hagati y’ukwizera n’urukundo , ni ikihe gihambaye kuruta ikindi ?
Yakobo yabajije abavukanyi biwe barobanuwe ati : “ Mbega Imana ntiyatoye aboro mu vy’isi ngo babe abatunzi mu kwizera na ba samuragwa b’ubwami , ubwo yasezeraniye abayikunda ? ”
Zimaze kumera zikayangika , ca catsi kibi na co gica kiraseruka . ”
INDIRIMBO : 116 , 102
Nimba kiriho , cabaye ryari ?
Ni ibiki Yehova yasezeraniye abasavyi biwe , kandi ni kubera iki uwo muhango wari uwudasanzwe ?
None Abisirayeli boba bosubiye gusenga mu buryo Imana yemera ata gahaze ?
Ku bw’ivyo , biragaragara ko abasavyi ba Yehova batagizwe imbohe na Babiloni Akomeye mu 1918 .
( Soma 1 Petero 2 : 9 , 10 . )
( Soma Matayo 13 : 24 , 25 , 37 - 39 . )
Emwe , bari baboshwe koko na Babiloni !
None abakirisu b’ukuri boba bokwigeze baronka umwidegemvyo wo gusenga Imana ku mugaragaro kandi mu buryo bwemewe ?
INDIRIMBO : 101 , 93
Ni ryari abarobanuwe babohowe bakava muri Babiloni ?
( Soma Ivyahishuwe 18 : 4 . )
Abo Batohoji ba Bibiliya bari abanyamwete pe !
Umuvukanyi Rutherford yaradusavye ko twotunganya amahwaniro mu bisagara vyinshi vyo mu burengero bwa Amerika no kurungika abashikirizansiguro kugira ngo baje kuremesha abo bavukanyi uko bishoboka kwose . ”
13 : 15 .
INDIRIMBO : 121 , 45
Emama ngo ndayayata , ngo ndi intumva canke ngo ndi ikijuju .
Numva umengo nta co maze . ”
Naramwiganiye ingene nari merewe , na we arantega yompi abigiranye ikibabarwe .
Yaciye anyibutsa ivyiza nariko ndarangura .
Yaranyibukije n’amajambo Yezu yavuze , yuko umwe wese muri twebwe aruta utujuri twinshi .
Akenshi ndibuka ico canditswe , kandi n’ubu kiracankora ku mutima .
Ni ibiki twigira ku kuntu Yehova , Yezu be na Paulo baremesheje abandi ?
( Soma Umusiguzi 4 : 9 , 10 . )
Ni ibiki dushobora kwigira ku kuntu Yezu yafashe abigishwa biwe ?
Aho amariye guca muri iyo mihingo akaremesha abahari akoresheje amajambo atari make , aza mu Bugiriki . ”
( Soma 1 Abatesalonika 5 : 12 , 13 . )
Ntiworaba ingene atubera isoko ry’indemesho . ”
Sebibondo umwe w’abana babiri yitwa Andreas , avuga ati : “ Kuremesha abana biratuma bakura mu kwizera no mu bwenge .
Iyo ubanje kubaremesha , impanuro ubaha bararushiriza kuyiha agaciro .
Naho abana bacu bazi iciza ico ari co , kwama tubaremesha bituma babaho bipfuza gukora iciza . ”
( Soma Luka 21 : 1 - 4 ; 2 Abakorinto 8 : 12 . )
( Soma Ivyahishuwe 2 : 18 , 19 . )
Nashaka kukumenyesha ko imvugo iranga ubuntu wakoresheje , haba ku mukiruruko be n’igihe twariko turayaga , yambereye nk’induhuro ivuye kuri Yehova . ”
[ 1 ] ( ingingo ya 1 ) Bamwebamwe si ko basanzwe bitwa .
INDIRIMBO : 105 , 107
( b ) Ni ibiki turimbura muri iki kiganiro ?
None amashengero yungukiye gute ku gukurikiza ubuyobozi bwatangwa n’inama nyobozi ?
Soma Ivyakozwe 16 : 4 , 5 .
( Soma 3 Yohani 9 , 10 . )
( Soma Matayo 5 : 23 , 24 ; 18 : 15 - 17 . )
INDIRIMBO : 114 , 113
Nari nzi ko turi abagenzi somambike . ’
Bibiliya iraduhimiriza kwama twitaba amakoraniro .
Ubwubatsi .
Woba umaze gukoresha jw.org mu busuku urangura no mu gusenga kwo mu muryango ?
( Soma Abaroma 14 : 12 . )
Ni imvo zimwezimwe izihe zikwiye gutuma dukengurukira Yehova ?
Hariho imvo nyinshi zotuma dukengurukira Imana !
Kiratwereka kandi ingene ico cizigiro kitugirira akamaro .
Nk’uko vyavuzwe na Denton Hopkinson
Ico gihe nari mfise imyaka umunani gusa .
Ariko naripfuza kubimenya kandi narakunda kubaza ibibazo .
Ku bw’ivyo , mawe yaca anyigisha igihe dawe yaba atari muhira .
Ivyo vyatumye na jewe mfata ingingo yo kwiyegurira Yehova .
Mawe yambwiye ko nkwiye kubanza kuvugana n’umusuku w’abavukanyi ( ubu akaba yitwa umucungezi w’umuzunguruko ) .
Inyuma y’amezi ane , naratoye umuvukanyi twogiye turakorana ubutsimvyi .
Mawe yari umutsimvyi mu rindi shengero , agakorana n’uwundi mutsimvyi .
Mu 1951 , narujuje urukaratasi rwo gusaba kwitaba Ishure ry’ivya Bibiliya rya Gileyadi .
Ndi mw’ibohero ni ho naronka ubutumire bwo kwitaba ivyigwa vy’umugwi ugira 22 w’Ishure rya Gileyadi .
Naciye mfata igariyamoshi ija i South Lansing muri New York , aho iryo shure ryabera .
Ndi kumwe na Janet kuri rimwe mu mazinga menshi yo muri Filipine
Turacakorera ku biro vy’ishami mu gisagara ca Quezon
INDIRIMBO : 60 , 23
Ushobora gute kuronka “ amahoro y’Imana ” ?
Ishengero ryogufasha gute kugabanya amaganya ?
( Raba ishusho itangura . ) ( b ) Ni ibiki twihweza muri iki kiganiro ?
None ivyo twobigira gute ?
Umwanditsi wa zaburi Dawidi yatakambiye Yehova ati : “ Ewe Mana , tega ugutwi isengesho ryanje . ”
Kubera iki isengesho rihambaye igihe turi mu maganya ?
Soma Abafilipi 4 : 6 , 7 .
Na wewe ivyo woshobora kuvyibonera .
( Soma Matayo 11 : 28 - 30 . )
8 - 12 .
“ Urukundo , akanyamuneza , amahoro . ”
“ Ukwiyumanganya , ubuntu , ukumera neza . ”
“ Ukwizera . ”
“ Ubwitonzi , ukwigumya . ”
Igihe Yezu yavuga ngo “ ntimukigere mwiganyira ” yashaka kuvuga iki ?
( Raba uruzitiro ruvuga ngo “ Ivyogufasha kugabanya amaganya . ” )
ABAFILIPI 1 : 10 , 11
UMUSIGUZI 7 : 16
MATAYO 14 : 23
Nuryohererwe ivyo Yehova yaremye .
ZABURI 104 : 24 , 25
Nube umuntu akunda gutwenza .
IMIGANI 17 : 22
Niwame winonora imitsi .
1 TIMOTEYO 4 : 8
UMUSIGUZI 4 : 6
Ni mu buryo ki insobanuro y’izina ry’Imana ikomeza ukwizera kwacu ?
Izina ryayo vyiyumvirwa ko risobanura ngo “ Atuma bicika ukuntu . ”
Kubera iki gukomeza ubucuti ufitaniye na Yehova bizogufasha ?
( a ) Ni gute twoterera amaganya yacu ku Mana ?
INDIRIMBO : 85 , 134
Twemezwa n’iki ko Yehova aha impera abasavyi biwe ?
Yehova yahezagiye gute abasavyi biwe muri kahise ?
Ni imihezagiro iyihe Yehova aduha muri iki gihe ?
1 , 2 . ( a ) Urukundo n’ukwizera bifitaniye isano irihe ?
None kwizigira ko tuzoronka impera bidufasha gute ?
( Soma Matayo 6 : 33 . )
Yezu yarerekanye ko abigishwa biwe boronse impera kubera utwigoro bagira ( Raba ingingo ya 5 )
Igihe kimwe , intumwa Petero yarabajije Yezu ati : “ Twebwe twarasize vyose turagukurikira ; none vy’ukuri tuzohakura iki ? ”
Muri ya nsiguro Yezu yashikiriza ari ku musozi , yavuze ati : “ Munezerwe musimbasimbishwe n’akanyamuneza , kuko impembo yanyu ari nini mw’ijuru ; kuko ukwo ari ko bahamye abahanuzi b’imbere yanyu . ”
Musa yabwiye ihanga rya Isirayeli ati : “ Yehova azoguhezagira ata kabuza mu gihugu . . . agira aguhe bwa ntoranwa ngo ucigarurire , niwakira gusa kwumviriza koko ijwi rya Yehova Imana yawe , ukaba maso ugashitsa iri bwirizwa ryose ndagutegetse uno musi .
Kuko Yehova Imana yawe azoguhezagira vy’ukuri nk’uko yagusezeraniye . ”
Yehova yahezagiye gute Yozefu ?
Uwugira kabiri yamwise Efurayimu , kuko yavuga ati : “ Imana yatumye ndondokera mu gihugu c’uburushwa bwanje . ” ’
Ijambo ry’Imana rigira riti : “ Ku bw’akanyamuneza yashizwe imbere yarihanganiye igiti co kubabarizwako , asuzugura ibimaramare . ”
Nta gukeka ko Yezu yahimbarwa no kweza izina ry’Imana .
Yehova abona gute ivyo tumukorera ?
Bibiliya igira iti : “ Uwugirira ubutoni umuntu mutoyi aba aguranye Yehova , kandi ivyo akoze azobimwishura . ”

( Soma 1 Yohani 3 : 19 , 20 . )
Vuga imwimwe mu mihezagiro twironkera ubu .
Abasavyi ba Yehova babona gute imihezagiro bironkera ?
Nk’akarorero , uwitwa Bianca wo mu Budagi avuga ati : “ Sinoronka uko nshimira Yehova kubera ukuntu amfasha mu maganya yanje n’ukuntu amba hafi buri musi .
Igihe cose ngize ivyo mpevye ku bwiwe , arabinyishura incuro ijana . ”
Ndafise agakaye nandikamwo ivyanditswe n’ivyiyumviro vyo mu bisohokayandikiro , ngaca nza ndabisoma kugira bindemeshe .
Ndakita ‘ Agakaye k’ubukiriro . ’
Igihe tugumiza umutima ku vyo Yehova yadusezeraniye , naho twocika intege biba ivy’akanya gato .
Yehova yama yiteguriye kudufasha , uko ibintu vyoba vyifashe kwose . ”
Naho ari ukwo , na wewe urashobora kubona ko Yehova yaguhezagiye hamwe n’abawe .
INDIRIMBO : 2 , 61
Ni gute Paulo n’abandi bakuwe mu buja bw’icaha n’urupfu ?
( Soma Abaroma 6 : 1 , 2 . )
Ni ihitamwo irihe umwe wese ategerezwa kugira ?
Yanditse ati : “ Jewe ndi uw’umubiri , nagurishijwe ngo ngabwe n’igicumuro .
Kubera iki dukwiye kuba imvugakuri ?
( Soma Imigani 14 : 5 ; Abanyefeso 4 : 25 . )
( Raba ingingo ya 19 )
INDIRIMBO : 57 , 52
( Soma Abaroma 4 : 20 - 22 . )
Soma Abaroma 8 : 4 - 13 .
( Soma Ivyakozwe 18 : 2 - 4 ; 20 : 20 , 21 , 34 , 35 . )
Ingenzi nyinshi ziraza mu gasagara ka Aveiro ko mu buraruko bwa Portigale , zije kuraba ibinogo bakuramwo umunyu .
Muri iki kiganiro , turabona ingene twoha agaciro ububasha Imana yaduhaye bwo kwihitiramwo , mu kubukoresha mu buryo buhimbara nyene kubutanga .
Mu kiganiro ca mbere , turabona ico ukwifata ruto bisobanura be n’ico bidasobanura .
INDIRIMBO : 133 , 63
kuri Nowa ?
kuri Dawidi ?
Yehova yiteze ko dukoresha gute ingabirano yaduhaye ?
Biragaragara rero ko Yehova yipfuza yuko dukora ivyo dushoboye ku bw’ineza yacu be n’iy’abandi .
Ni ibintu ibihe twebwe abantu tudashoboye ?
( Soma Zaburi 37 : 3 . )
Mu gihe ca Nowa , isi yari ‘ yuzuye ubukazi ’ n’ubushegabo .
Banse inkuru nziza ( Raba ingingo ya 6 - 9 )
6 , 7 . ( a ) Ni ibiki Nowa atari ashoboye gukora ?
( b ) Ni mu buryo ki ivyacu bimeze nk’ivya Nowa ?
Na twebwe tubaye mw’isi yuzuye ubukozi bw’ikibi , iyo Yehova yasezeranye kuzorandura .
Mu kurindira , ntidushobora guhata abantu ngo bemere “ inkuru nziza y’ubwami . ”
Ivyo Nowa yashobora gukora : Nowa ntiyacitse intege kubera ivyo atari ashoboye gukora . Ahubwo yashize umutima ku vyo yashobora gukora .
Twokwigana gute akarorero ka Nowa ?
None bimaze kumenyekana , Dawidi yaciye akora iki ?
Wibutse ibicumuro wigeze gukora ( Raba ingingo ya 11 - 14 )
11 , 12 . ( a ) Aho Dawidi acumuriye , ni ibiki atashobora gukora ?
Ni ibiki twigira ku karorero ka Dawidi ?
Ukitswe n’amagara ( Raba ingingo ya 15 )
Akarorero ka Hana katwigisha iki ?
Vyabaye ngombwa ko ashira ico kibazo mu maboko ya Yehova .
Rimbura akarorero k’umuvukanyi Malcolm , uwagumye ari umwizigirwa gushika apfuye mu 2015 .
Niwibande ku vyo ushoboye , aho kwibanda ku vyo udashoboye . ”
( b ) Uzoshira mu ngiro gute icanditswe c’umwaka wa 2017 ?
Icanditswe c’umwaka wa 2017 : “ Niwizigire Yehova , ukore iciza . ” — Zab . 37 : 3 .
INDIRIMBO : 62 , 65
Ni ingabirano iyihe Yehova yahaye umwe wese muri twebwe ?
Twokwerekana gute ko twubahiriza abandi mu ngingo bifatira ?
4 , 5 . ( a ) Ni nde Imana yatanguye guha ububasha bwo kwihitiramwo , kandi yabukoresheje gute ?
( b ) Ni ikibazo ikihe umwe wese muri twebwe akwiye kwibaza ?
Inyishu y’ico kibazo irafitaniye isano n’icizigiro cacu co kubaho ibihe bidahera .
Bibiliya igira iti : “ Atangura kubizanira nya muntu kugira arabe uko yokwita kimwekimwe cose . ”
Na twebwe turashobora guhitamwo gusenga Yehova .
Umwidegemvyo wacu dukwiye kwirinda kuwukoresha gute ?
Dufate ko hari umugenzi wahaye ingabire y’agaciro .
Bumwe mu buryo twokwirinda gukoresha nabi umwidegemvyo wacu ni ubuhe ?
( Soma 1 Petero 2 : 16 . )
Ingingo ngenderwako iri mu Bagalatiya 6 : 5 itwigisha iki ?
Niwibuke ingingo ngenderwako ivugwa mu Bagalatiya 6 : 5 .
Wokwerekana gute ko uha agaciro ububasha ufise bwo kwihitiramwo ?
INDIRIMBO : 38 , 69
Kubera iki kwifata ruto bihambaye ?
Kwifata ruto bifitaniye isano gute no kwicisha bugufi ?
( a ) Abantu benshi babona gute ivyo kwifata ruto ?
Kwifata ruto bisobanura iki , kandi ni igiki bidasobanura ?
( Soma Imigani 11 : 2 . )
Tanga akarorero ko muri Bibiliya .
Kubera iki twokwirinda gucira abandi urubanza ?
Ni ibiki twokwigira kuri Yezu igihe duhinduriwe igikorwa ?
( Raba ingingo ya 12 - 14 )
INDIRIMBO : 48 , 95
kwihangana igihe batuneguye canke badushemagije birenze ?
( Soma Mika 6 : 8 . )
Ni ibiki turimbura muri iki kiganiro ?
( Soma Abagalatiya 6 : 4 , 5 . )
( Soma Umusiguzi 11 : 4 - 6 . )
Tuzokwiga gushira abandi imbere .
Ni ibiki bizodufasha kuguma twifata ruto gushika ibihe bidahera ?
INDIRIMBO : 123 , 53
Abantu benshi babona gute igikorwa bakora ?
Ni kubera iki hari abo bigora kuzeza abandi amabanga ?
Yatumye Natani kubwira Dawidi ati : “ Si wewe uzonyubakira inzu yo kubamwo . ”
Dawidi yakiriye gute ingingo Yehova yafashe ?
Soma 1 Ngoma 22 : 5 .
( Soma Guharūra 11 : 24 - 29 . )
Oya , icompa abantu ba Yehova bose bakaba abahanuzi , kuko Yehova yoshira impwemu yiwe kuri bo ! ”
( Soma Abafilipi 2 : 20 - 22 . )
3 Umugambi wa Yehova uzoranguka ata kabuza
Nk’uko vyavuzwe na Douglas Guest
Ibiro vy’ishami vyaraturungikiye ibinyamakuru 800 twokoresheje mu ndimiro .
Narigishije i Manaus , i Belém , i Fortaleza , i Recife , no muri Salvador .
Muri Myandagaro 1964 , ni ho twashika i Lisbonne muri Portigale .
Ni ryo ryonyene ririko rirakora igikorwa Yezu yategetse abigishwa biwe , na co kikaba ari ukwamamaza inkuru nziza y’Ubwami bw’Imana ! ”
Igihe iki kiganiro cariko kirategurwa , Douglas Guest yarasandavye ari umwizigirwa kuri Yehova , ku wa 25 Gitugutu 2015 .
INDIRIMBO : 152 , 22
bafashwa n’impwemu nyeranda ?
bayoborwa n’Ijambo ry’Imana ?
Musa yakuye he ubushobozi bwo kuyobora Isirayeli ?
Impwemu nyeranda yarabafasha .
“ Impwemu ya Yehova [ yaratwikiriye ] Gideyoni . ”
Vyongeye , Bibiliya ivuga iti : “ Impwemu ya Yehova itangura gukorera kuri Dawidi . ”
Kubera iki Imana yasaba abasavyi bayo kwubaha indongozi za Isirayeli ?
( Soma Abaheburayo 1 : 7 , 14 . )
Musa yayobowe gute n’Itegeko ry’Imana ?
Ijambo ry’Imana ni ryo ryabayobora .
Rya Tegeko Abisirayeli bahabwa , Bibiliya iryita “ Itegeko rya Musa . ”
11 , 12 . ( a ) Yosuwa be n’abami baganje abasavyi b’Imana , basabwa gukora iki ?
Bibiliya igira iti : “ Umwami ngo yumve amajambo yo muri ico gitabu c’itegeko , aca atantamura impuzu ziwe . ”
Vy’ukuri , Yehova ni we yaziyobora .
Kubera iki Yehova yahanye indongozi zimwezimwe z’abasavyi biwe ?
Hari igihe Yehova yaca azihana canke akazisubiriza abandi .
( Soma Matayo 23 : 10 . )
Ni ibiki vyerekanye neza ko Yezu yakoreshwa n’impwemu nyeranda ?
Yezu yakoreshwa n’impwemu nyeranda .
Haciye igihe gito Yezu abatijwe , “ abamarayika bara [ je ] , batangura kumukorera . ”
Hasigaye amasaha makeya ngo acikane , haraje “ umumarayika avuye mw’ijuru aramubonekera , aramukomeza . ”
Yezu yisunze gute Ijambo ry’Imana mu buzima bwiwe no mu nyigisho ziwe ?
Yezu yayoborwa n’Ijambo ry’Imana .
Bansengera ubusa , kuko inyigisho bigisha ari amabwirizwa y’abantu . ”
Nta n’umwe ari mwiza , atari umwe , na we ni Imana . ”
Bibiliya igira iti : “ Ako kanya nyene umumarayika wa Yehova aramukubita , kuko atari yahaye ubuninahazwa Imana ; aca arigitwa n’inyo , aracikana . ”
Ikiganiro gikurikira kizorimbura inyishu z’ivyo bibazo .
Birashoboka ko mu ntango , ico gitabu canditswe na Musa .
INDIRIMBO : 125 , 43
Kubera iki iryo torwa ryari rihambaye kuri bo no kuri Yehova ?
Uko bose hamwe bari bagize inama nyobozi , ni bo baha ubuyobozi amashengero yose . ​ — Ivyak . 15 : 2 .
5 , 6 . ( a ) Impwemu nyeranda yayoboye gute inama nyobozi ?
( c ) Inama nyobozi yisunze gute Ijambo ry’Imana ?
Ubwa mbere , impwemu nyeranda ni yo yayobora inama nyobozi .
Ubwa gatatu , inama nyobozi yagumye yisunga Ijambo ry’Imana .
Tubwirwa n’iki yuko Yezu ari we yayobora abakirisu bo mu ntango ?
( a ) Yezu yagenye ryari “ umushumba w’umwizigirwa kandi w’ubwenge ” ?
Mu 1919 , inyuma y’imyaka itatu umuvukanyi Russell apfuye , Yezu yaragenye “ umushumba w’umwizigirwa kandi w’ubwenge . ”
Umunara w’Inderetsi wo ku wa 15 Mukakaro 2013 , wasiguye ko “ umushumba w’umwizigirwa kandi w’ubwenge ” ari umugwi mutoyi w’abavukanyi barobanuwe bagize Inama Nyobozi .
Inama nyobozi mu myaka ya 1950
None twokwishura gute ikibazo Yezu yabajije ati : “ None ni nde mushumba w’umwizigirwa kandi w’ubwenge ? ”
Impwemu nyeranda yafashije gute Inama Nyobozi ?
Ni kubera iki none ico gikorwa kiguma gitera imbere ?
( Soma Yohani 17 : 17 . )
Uburyo bumwe twibuka Inama Nyobozi ni ubuhe ?
Soma Abaheburayo 13 : 7 .
Kubera iki wiyemeje gukurikira Indongozi yacu Yezu ?
Yezu amaze gusubira mw’ijuru , ntiyahevye abayoboke biwe .
Vuba , azotuyobora adushikane ku buzima budahera .
Emwe , nta ndongozi n’imwe y’umuntu yotanga uwo muhango !
Kuva mu 1955 , urwo Rwego rwarahinduye izina ruba Watch Tower Bible and Tract Society of Pennsylvania .
Yehova ‘ araduhoza mu makuba yacu yose ’
“ Narabivuze ; no kubishitsa nzobishitsa .
INDIRIMBO : 147 , 149
1 , 2 . ( a ) Yehova yaduhishuriye iki ?
BIBILIYA yugururwa n’amajambo asanzwe mugabo atekeye insobanuro ikomeye . Agira ati : “ Mu ntango Imana yaremye amajuru n’isi . ”
( c ) Ni ibibazo ibihe tugiye kurimbura ?
Vyongeye , ni kubera iki incungu Yezu yatanze ari yo icira inzira iranguka ry’umugambi w’Imana ?
Yehova ni Umuremyi ateye akoba .
Zimwe mu ngabirano Yehova yahaye Adamu na Eva ni izihe ?
( Soma Yakobo 1 : 17 . )
Ni ibiki kandi vyari mu mugambi w’Imana ?
Ni nk’aho yavuze ati : ‘ Burya ntimushobora gukora ico mushatse cose ? ’
Mugabo Yehova arubahiriza ingingo ngenderwako ziwe . Ntiyigera azihonyanga .
Abana ba Adamu vyabagendeye gute ?
( Soma Gusubira mu vyagezwe 32 : 4 , 5 . )
Soma Yohani 3 : 16 .
Kubera iki incungu ari ingabire idasanzwe ?
Incungu ituma hashoboka iki ?
Kugira ngo Yehova atange incungu , vyabaye ngombwa ko aheba ikintu c’agaciro kanini .
Yehova azoba “ vyose ku muntu wese ” ryari ?
INDIRIMBO : 148 , 109
Twokwerekana gute ko dukunda izina rya Yehova ?
Ni mu kuntu twigenza .
( Soma 1 Petero 1 : 15 , 16 . )
Kubera iki Yehova ashobora kutwita abagororotsi naho nyene tudatunganye ?
Abamwiyegurira arabaha ikaze mu basavyi biwe .
Yezu yashatse kuvuga iki igihe yavuga ati : “ Ukugomba kwawe nigukorwe ” ?
Incungu imariye iki abapfuye ?
Imana yipfuriza iki “ isinzi rinini ” ?
( a ) Yehova aturonsa imihezagiro iyihe muri iki gihe ?
( Soma Ivyakozwe 3 : 19 - 21 . )
Kuba dukundwa na Yehova ubibona gute ?
Bibiliya igira iti : “ Twebwe ubwacu twaramenye kandi twaremeye urukundo Imana idufitiye .
Imana ni urukundo . ”
Hoba hari igihe vyokenerwa ko duhindura ingingo twafashe ?
Iki kiganiro kiradufasha kwishura ivyo bibazo .
Ariko Yehova yabonye ko bari bafise umutima ukwiye .
None natwe yoba azobona ko dufise umutima ukwiye , naho bishika tugakora amakosa ?
32 Izina ryo muri Bibiliya ku rwavya rwa kera
Nk’uko vyavuzwe na William Samuelson
Datawacu Alfred be na dawe
Twaba mu buseruko bwa Dakota yo mu Bumanuko , tukaba twari dufise agatongo gatoyi twarima .
Naho umuryango wacu witaho kurima no kworora , si vyo washira imbere .
Abavyeyi banje babatijwe mu 1934 , baba Ivyabona vya Yehova .
Dawe yitwa Clarence . Yarabaye umusuku w’ishengero ( umuhuzabikorwa w’inama y’abakurambere ) mw’ishengero ritoyi twarimwo ry’i Conde .
Jewe na mushikanje Dorothy , twabaye abamamaji dufise imyaka itandatu .
Igihe nari umutsimvyi mu 1952
Twaraha agaciro cane amateraniro n’amahwaniro .
Bibiliya ivuga iti : “ Uwugendana n’inkerebutsi azocika inkerebutsi . ” Mu muryango iwacu hari inkerebutsi nyinshi zashigikiye ingingo nafashe yo gukora ubutsimvyi .
Dorothy na we nyene ntiyatevye kuba umutsimvyi .
Igihe baba bagendeye amashengero yo mu micungararo iwacu , barantumako tugakorana mu ndimiro .
Igihe nari Umunyabeteli mushasha , ndi iruhande y’ikamyo ya Beteli
Ndi kumwe n’umuvukanyi Franz kuri WBBR
Muri ico kigo , hakorera Abanyabeteli bari hagati ya 15 na 20 gusa .
Abenshi muri twebwe twari tukiri bato kandi ntitwari bwamenye utuntu n’utundi .
Naho yitaho cane igikorwa yari ashinzwe kuri Beteli , ntiyibagira indimiro .
Twe na Angela na Etta Huth
Twe na Angela mu 1975 , imbere yo gutanga ikiganiro kuri televiziyo
Haciye imyaka itatu , twaciye duhamagarwa gukorera kuri Beteli .
Ndahimbarwa no kumenyana n’abanyeshure bo mu mihingo itandukanye y’isi
INDIRIMBO : 9 , 108
Kubera iki Yehova na Kristu babereye guterwa iteka ?
Abantu baremwe “ mw’ishusho y’Imana . ”
8 , 9 . ( a ) Ivyabona vya Yehova babona gute abategetsi ?
( Soma 1 Timoteyo 5 : 17 . )
Eka mbere ntimukitwe ‘ indongozi , ’ kuko Indongozi yanyu ari imwe , ni Kristu .
Uwo wese yishira hejuru azocishwa bugufi , kandi uwo wese yicisha bugufi azoshirwa hejuru . ”
INDIRIMBO : 81 , 70
Kubera iki tudakwiye kureka abandi ngo badufatire ingingo ?
( a ) Nimba twipfuza gufata ingingo nziza , dukwiye kwizera iki ?
None ni igiki codufasha gufata ingingo nziza ?
( Soma Abagalatiya 4 : 17 . )
( Soma 2 Abakorinto 1 : 24 . )
Abakurambere barafasha abandi kumenya ingene bokwifatira ingingo ( Raba ingingo ya 11 )
Abakurambere na bo nyene barakwiye gufata umwanya wo kugira ubushakashatsi .
Yoba izotuma mu rugo iwacu harangwa amahoro n’umunezero ?
Vyongeye , yoba izokwerekana ko nihangana be n’uko ndi umunyabuntu ? ’
Kubera iki Yehova atureka tukifatira ingingo ?
Asa , Yehoshafati , Hezekiya , Yosiya
INDIRIMBO : 52 , 65
Gukorera Yehova n’umutima ukwiye bisobanura iki ?
Muri abo bami bane woshima kwigana nde , kandi kubera iki ?
( Soma 2 Ngoma 14 : 11 . )
None umutima wawe wokubwira gukora iki ?
Yehoshafati mwene Asa , “ [ yagumye ] agendera mu nzira ya se wiwe Asa . ”
( Soma 2 Ngoma 20 : 2 - 4 . )
( Soma Yesaya 37 : 15 - 20 . )
( Soma 2 Abami 20 : 1 - 3 . )
( Soma 2 Ngoma 34 : 18 , 19 . )
INDIRIMBO : 11 , 61
Asa na Yehoshafati
Hezekiya
Yosiya
Kubera iki tugiye kurimbura ivyashikiye abami bane ba Yuda ?
( Soma 2 Ngoma 16 : 7 - 9 . )
Ikosa Asa yakoze turyigirako iki ?
Aratahura uko ivyacu vyifashe kandi aradukunda .
( Soma 2 Ngoma 32 : 31 . )
None yovyakira gute ?
( Soma 2 Ngoma 35 : 20 - 22 . )
Bibiliya ivuga ko amajambo ya Neko yari “ yavuye mu kanwa k’Imana . ”
Nimuze rero tuzirikane kuri izo nkuru zo muri Bibiliya twongere dukenguruke kubona Yehova yarazituronkeje !
3 “ Ico uraganye , gishitse ”
Ni ibintu bingahe umaze kuraganira Yehova ?
Ubona gute indagano wagize y’ukwiyegurira Yehova canke y’ukwabirana ?
Igihe twiyumvira ko twarenganijwe canke ko uwundi muntu yoba yarenganijwe , ukwizera kwacu , ukwicisha bugufi kwacu n’ukudahemuka kwacu birashobora kuja ku munzane .
“ Isi iriko irahita , n’icipfuzo cayo ni ukwo , mugabo uwukora ukugomba kw’Imana agumaho ibihe vyose . ” ​ — 1 YOH . 2 : 17 .
INDIRIMBO : 134 , 24
Yehova azokorera iki ababisha be n’amashirahamwe yononekaye ?
Nkako , Bibiliya ivuga iti : “ Isi iriko irahita . ”
Ababisha batugirako ingaruka gute ?
None Yehova azokora iki ?
( Soma Zaburi 37 : 10 . )
Nta mwiza canke igitutu kizitanye biriho ngo abakora ibintu bibabaza binyegezeyo . ”
Muri iyo zaburi nyene , dusoma kandi duti : “ Abagororotsi bazokwigabira isi , kandi bazoyibako ibihe bidahera ” None abo “ batekereza ” n’abo “ bagororotsi ” ni bande ?
Abatekereza ni abicisha bugufi bakemera inyigisho n’ubuyobozi Yehova atanga .
Amashirahamwe yononekaye atugirako ingaruka gute ?
Amashirahamwe yononekaye atugirako ingaruka gute ?
Ayo madini azokurwaho burundu .
( Soma Ivyahishuwe 6 : 14 . )
Twemezwa n’iki yuko isi nshasha izoba itunganijwe neza ?
Amashirahamwe yononekaye azosubirirwa n’iki ?
Inyuma ya Harumagedoni , hoba hari ishirahamwe rizoba riri kw’isi ?
“ Isi nshasha ” rero izoba itunganijwe neza .
Ibikorwa bibi vyiraye aho iwanyu ni ibihe , kandi bikugirako ingaruka gute n’umuryango wanyu ?
Ibikorwa bibi bitugirako ingaruka gute ?
Kuba Yehova yarashikije urubanza kuri Sodomu na Gomora bitwigisha iki ?
Yehova azokora iki ku bijanye n’ibikorwa bibi ?
( Soma 2 Petero 2 : 6 - 8 . )
Ibikorwa bibi bizosubirirwa n’iki ?
( Soma Zaburi 46 : 8 , 9 . )
Ubukene na bwo azobukuraho .
Inyuma ya Harumagedoni , ni ibintu ibihe bizoba vyagiye burundu ?
Tanga uburorero . ( b ) Twokora iki kugira ngo tuzokwigumireho iyi si ishaje niyakurwaho ?
Ntituzi n’ingene twobivuga .
INDIRIMBO : 112 , 89
Mika 7 : 7
Imigani 19 : 3
Matayo 18 : 15
“ MBEGA Umucamanza w’isi yose ntazokora ibigororotse ? ”
Ni kubera ko Yehova ari we Karorero ntangere mu gukurikiza ubutungane n’ubugororotsi .
Ni ryari ukwizera kwacu kwoshobora gushirwa ku munzane ?
Mu bisanzwe , abakirisu bitega ko akarenganyo kagirwa hanze y’ishengero .
Rimbura ivyashikiye umuvukanyi Willi Diehl .
Mu 1946 , yaritavye Ishure rya Gileyadi i New York muri Amerika , mu mugwi ugira umunani .
Arangije iryo Shure , yaciye arungikwa kuba umucungezi w’umuzunguruko mu Buswise .
Ni uburorero ubuhe turimbura muri iki kiganiro no mu gikurikira ?
Muri iki kiganiro , turimbura akarorero ka Yozefu umwuzukuruza wa Aburahamu be n’ivyabaye hagati yiwe na benewabo .
10 , 11 . ( a ) Yozefu yagiye ararenganywa gute ?
Soma Itanguriro 40 : 14 , 15 .
( Soma Matayo 5 : 23 , 24 ; 18 : 15 . )
Kuba intahemuka kuri Yehova no ku bavukanyi bacu bizotuma tudakora iryo kosa .
Ntiyigeze ata umwikomo kuri Yehova .
Ikiruta vyose , ntiyaretse amakosa y’abandi be n’ibibi bamukoreye ngo bimutandukanye na Yehova .
Bishitse hakagira uwo mw’ishengero aturenganya , kubera iki dukwiye kurushiriza kwiyegereza Yehova ?
Twokwerekana gute ko twizigira wa “ Mucamanza w’isi yose ” ?
Raba inkuru y’ubuzima ya Willi Diehl ifise umutwe uvuga ngo “ Yehova ni we Mana yanje nzokwizigira , ” mu Munara w’Inderetsi ( mu gifaransa ) wo ku wa 1 Munyonyo 1991 , rup . 25 - 29 .
ABITAVYE ICIBUTSO ( 2016 )
INDIRIMBO : 63 , 59
indagano wagize yo kwiyegurira Imana ?
indagano wagize y’ukwabirana ?
( Raba amashusho atangura . ) ( b ) Ni ibibazo ibihe vyishurwa muri iki kiganiro ?
Barabera akarorero keza abagore n’abagabo muri iki gihe bahitamwo kugira ico baraganiye Yehova .
Kugira ico uraganiye Imana bihambaye ku rugero rungana iki ?
Ni ibiki twigira kuri Yefuta na Hana ?
2 , 3 . ( a ) Indagano ni iki ?
( b ) Ivyanditswe bivuga iki ku bijanye no kugira ivyo uraganiye Imana ?
Ico uraganye , gishitse . ”
( a ) Kubera iki gusezeranira Imana ikintu atari ivyo gukinisha ?
( b ) Dukeneye kumenya iki ku bijanye na Yefuta be na Hana ?
None ivyo vyasobanura iki kuri uwo mukobwa ?
( a ) Vyoba vyari vyoroshe ko Yefuta n’umukobwa wiwe bashitsa ivyo yari yasezeraniye Imana ?
Yavuze ati : “ Jewe nateranuriye akanwa Yehova , nkaba rero ntashobora kwisubirako . ”
( b ) Indagano ya Hana yasobanura iki kuri Samweli ?
Woba uriko urashitsa ivyo wasezeraniye Yehova ?
Indagano yo kwiyegurira Imana ( Raba ingingo ya 10 )
Emwe , Yehova ategerezwa kuba yarahimbawe cane !
Indagano y’ukwabirana ( Raba ingingo ya 14 )
Indagano ya kabiri ihambaye kuruta izindi zose umuntu yogira ni iy’ukwabirana .
Bibiliya ivuga iki ku bijanye n’ukwahukana be n’ugutandukana ?
( Soma 1 Abakorinto 7 : 10 , 11 . )
Hari abubakanye bavuze bati : “ Kuva dutanguye kwiga aka gatabu , twararushirije kugira agahimbare mu mubano . ”
Emwe , iyo videwo yaje hageze .
Ubu twempi turiko turaryohora ibintu . ”
18 , 19 . ( a ) Abavyeyi benshi bakoze iki ?
( b ) Twovuga iki ku bijanye n’abari mu murimo udasanzwe w’igihe cose ?
Indagano y’umurimo udasanzwe w’igihe cose ( Raba ingingo ya 19 )
Abo basuku si bo badasanzwe , mugabo ibikorwa barangura ni vyo bidasanzwe .
Abigisha bo mu ndimiro ni abavukanyi bigisha Ishure ry’abamamaji b’Ubwami , Ishure ry’abakurambere canke Ishure ry’abacungezi b’ingenzi n’abakenyezi babo .
INDIRIMBO : 150 , 10
Hari agahimbare Mushoboravyose agira ngo ni uko ugororotse , canke hari inyungu ahakura ngo ni uko urinda inzira yawe umugayo . ”
( b ) Isirayeli yatsinze gute ingabo za Yabini ?
( Soma Abacamanza 4 : 14 - 16 . )
Raba ikiganiro kivuga ngo “ Amaganya yerekeye amahera ” , mu Munara w’Inderetsi wo ku wa 1 Mukakaro 2015 .
INDIRIMBO : 110 , 2
Gusubira mu vyagezwe 32 : 4
1 Petero 5 : 5
Matayo 6 : 14
1 , 2 . ( a ) Naboti n’abahungu biwe barenganijwe gute ?
( b ) Muri iki kiganiro turimbura kamere zibiri izihe ?
Naboti yari umuntu ameze gute , kandi yankiye iki ko Umwami Ahabu amugurira umurima wiwe w’imizabibu ?
Naboti yagumye ari umwizigirwa kuri Yehova mu gihe Abisirayeli benshi bariko barigana akarorero kabi k’Umwami Ahabu n’umugore wiwe , wa mwamikazi w’umubisha Yezebeli .
Soma 1 Abami 21 : 1 - 3 .
Yasiguye n’icubahiro cinshi ati : “ Ni ibitokwiyumvirwa kuri jewe , nisunze uko Yehova abona ibintu , ko noguha intoranwa ya ba sogokuruza banje . ”
Mbega ukwicisha bugufi !
Kubera iki ukwicisha bugufi kwokingiye incuti n’abagenzi ba Naboti ?
( Soma Gusubira mu vyagezwe 32 : 3 , 4 . )
( b ) Ni mu buryo ubuhe ukwicisha bugufi kuzodukingira ?
Nivyashika abakurambere bagatangaza ingingo udashigikiye , uzovyakira gute ?
Tugiye kurimbura inkuru iyihe , kandi kubera iki ?
Petero yakosowe gute , kandi ni ibibazo ibihe bica bivyuka ?
Soma Abagalatiya 2 : 11 - 14 .
Boba bararetse bikabatsitaza ?
Petero yungukiye gute ku mbabazi za Yehova ?
Nkako , mu nyuma Imana yaramukoresheje mu kwandika amakete abiri ari mu bigize Bibiliya .
3 Nufashe “ ba kavamahanga ” kugira ‘ bakorere Yehova banezerewe ’
Ikiganiro kigira kabiri kirerekana ingene kwisunga ingingo ngenderwako zo muri Bibiliya bishobora gufasha abavyeyi b’abimukira gufata ingingo ku bw’ineza y’abana babo .
INDIRIMBO : 84 , 73
Hirya yacu , twarabona ingene abantu biruka bacanacanako .
Abavyeyi bacu be na twebwe abana uko turi 11 , twahunganye utuntu dukeyi gusa .
Vyagenze gute ngo Yezu hamwe n’abigishwa biwe batari bake babe impunzi ?
Yavuze ati : “ Nibabahama mu gisagara kimwe , muhungire mu kindi . ”
Ico gihe nari mfise imyaka 12 .
Naravyimvye ibirenge gushika n’aho mbwira abo mu muryango wacu ngo bansige ng’aho bigire .
Dawe yaciye ampeka kubera ko atashaka kunsiga mu karere k’abaroberi .
( Soma 1 Yohani 3 : 17 , 18 . )
( b ) Kubera iki bakeneye ko tubafasha twihanganye ?
Baba bakeneye kubona ko tubitwararika .
( b ) Impunzi zokwerekana gute ko zikenguruka ?
Twofasha gute abavukanyi bacu b’impunzi ?
Bidatevye , bose uko ari bane barabaye abatsimvyi .
( a ) Impunzi zikwiye kwirinda iki ?
Ivyarimwo si vyo twari dukeneye vy’ukuri ! ’ ” ​ — Soma 1 Timoteyo 6 : 8 .
Baba rero bakeneye kwibonera urukundo rwa Yehova n’impuhwe ziwe , biciye ku bakirisu bagenzi babo .
Impunzi nyinshi muri iki gihe ziva mu bihugu usanga igikorwa cacu kiburabuzwa .
Avuga ati : “ Abavukanyi batwakiriye nk’incuti zishika , baraturonsa ibifungurwa , impuzu , uburaro , baradufasha no kwiyunguruza .
Hari abandi none bokwakira mu nzu zabo abo batazi , ngo ni uko gusa basangiye idini ?
Emwe , nta bandi uretse Ivyabona vya Yehova ! ” ​ — Soma Yohani 13 : 35 .
Abakurambere bakimara kwumva ko hari impunzi yashitse , barakwiye kwisunga ubuyobozi buri mu gitabu Ishirahamwe rikora ivyo Yehova agomba , ikigabane ca 8 , ingingo ya 30 .
Mu kurindira , barashobora kuyibaza babigiranye ukwiyubara ibijanye n’ishengero yavuyemwo be n’ubusuku bwiwe , kugira ngo bamenye ingene ivyiwe vyifashe mu vy’impwemu .
“ Nta kindi mfise contera gukenguruka kiruta ibi bintu : ni uko nokwumva ko abana banje babandanya kugendera mu kuri . ” ​ — 3 YOH . 4 .
INDIRIMBO : 88 , 41
Abavyeyi boha gute akarorero keza abana babo ?
Serugo yokwisunga iki mu guhitamwo ishengero umuryango wojamwo ?
Abandi bofasha gute abavyeyi b’abimukira be n’abana babo ?
1 , 2 . ( a ) Abana benshi b’abimukira bahura n’ingorane iyihe ?
( b ) Muri iki kiganiro turimbura ibibazo ibihe ?
Ariko maze gutangura ishure , naciye ntangura kwiyumvamwo ururimi rw’igihugu twimukiyemwo .
Mu myaka mikeya , ni rwo nari nsigaye mvuga gusa .
Sinari ngitahura ivyavugwa mu makoraniro , kandi sinari nciyumvamwo imico y’abavyeyi banje . ”
Ivyashikiye Joshua birashikira n’abandi benshi .
Mbega hoho , abandi bogira ico bafashije gute ?
3 , 4 . ( a ) Abavyeyi bashobora gute kubera akarorero keza abana babo ?
( b ) Ni igiki abavyeyi badakwiye kwitega ku bana babo ?
Abana banyu nibabona “ mubanza kurondera ubwami , ” bazokwiga guhanga amaso Yehova kugira abaronse ivyo bakenera buri musi .
Ntimwigere mucurumba muri vyinshi , ku buryo muburira umwanya abana banyu .
Igihe abana bawe bazi ururimi rwawe kavukire , bibafasha gute ?
Bavyeyi , nimba bimeze gutyo ku bana banyu , mubona gute mwize amajambo na makeyi y’urwo rurimi runyamahanga ?
N’umwana akoresha urundi rurimi rero ukwiye kumwitwararika gutyo nyene .
Nimba ivyawe bimeze gutyo , ntucike intege . Biracashoboka ko ufasha abana bawe kumenya Yehova no kumukunda .
Mugabo tubonye ingene yiyigisha , ingene yasenga , n’ingene yakora uko ashoboye kwose kugira ngo ayobore inyigisho y’umuryango buri ndwi , twaciye dutahura ko kumenya Yehova vyari bihambaye . ”
Abavyeyi bofasha gute abana usanga bakeneye kwiga ivyerekeye Yehova mu ndimi zibiri ?
( a ) Ni nde akwiye gufata ingingo ku bijanye n’ishengero umuryango wojamwo ?
Ariko si ko vyomera igihe abana badatahura neza ururimi .
( Soma 1 Abakorinto 14 : 9 , 11 . )
None abavyeyi b’abimukira bokora iki ?
Twahavuye dusanga ururimi rwobafasha , twebwe rutatworohereza .
Mugabo tumaze kubona ko batungukira cane ku makoraniro yo mu rurimi rwacu , twahisemwo kwimukira mw’ishengero rikoresha ururimi rwo muri ico gihugu .
Uko tugize umuryango twaritaba amakoraniro yose , tukaja no mu ndimiro .
Vyongeye , twaratumira abagenzi kugira dusangire akajumpu no kugira tujane gutembera .
Ivyo vyose vyarafashije abana bacu kumenyana n’abavukanyi , bongera baramenya ko Yehova atari Imana yabo gusa , mugabo kandi ko ari Umuvyeyi wabo n’umugenzi wabo .
Ivyo twasanze bihambaye cane kuruta ko bomenya ururimi rwacu . ”
Samuel yongerako ati : “ Kugira ngo jewe n’umukenyezi wanje tugume dukomeye mu vy’impwemu , twaritaba n’amakoraniro yo mu rurimi rwacu .
Abana bacu bose uko ari batatu , bari mu murimo w’igihe cose . ”
Uwitwa Kristina yigana ati : “ Sinari nzi neza ururimi rw’abavyeyi banje . Tugeze mu makoraniro hoho naca ntakara rwose .
Igihe nari mfise imyaka 12 , naritavye ihwaniro ryo mu rurimi twakoresha kw’ishure .
Erega bwari bwo bwa mbere ntahura ko ivyo nariko ndumva ari ukuri .
Yemwe bakiri bato , mwoba mubona ko vyoba vyiza mugiye mw’ishengero ry’ururimi rwo mu gihugu mwimukiyemwo ?
Nimba ari ko biri , nimwibaze igituma mushaka kujayo .
Uwitwa Nadia ubu akorera kuri Beteli , avuga ati : “ Igihe jewe n’abo tuvukana twagera mu buyabaga , twaripfuje kwimukira mw’ishengero ry’ururimi rwo mu gihugu twabamwo . ”
Abandanya ati : “ Ubu turashima cane kubona abavyeyi bacu baritaye ku rutare kugira ngo batwigishe ururimi kavukire rwabo , bigatuma tuguma mw’ishengero rikoresha nya rurimi .
Vyaratwunguye cane mu buzima , vyongera biraturonsa uturyo twinshi two gufasha abandi kumenya Yehova . ”
( b ) Abavyeyi boronka gute imfashanyo mu bijanye no kwigisha ukuri abana babo ?
( Soma Imigani 1 : 8 ; 31 : 10 , 27 , 28 . )
Ivyo ntibiba bisobanura ko bahevye ibanga ryo gufasha abana babo mu vy’impwemu .
Abana n’abavyeyi barungukira ku kwifatanya n’ishengero ( Raba ingingo ya 18 , 19 )
( b ) Abavyeyi bategerezwa kuguma bakora iki ?
Igihe cose baba bamfashije gutegura ibiganiro nashikiriza mu makoraniro , narahigira vyinshi .
Vyongeye , narakunda cane ibiringo twahurira hamwe tukinezereza . ”
Bavyeyi , nimwiture Yehova abafashe , ariko namwe mugire akigoro kose gashoboka .
( Soma 2 Ngoma 15 : 7 . )
Nimushire imbere ubucuti umwana wanyu afitaniye na Yehova , aho gushira imbere ivyo mwikundira .
Nk’uko vyavuzwe na Walter Markin
Ariko nagiye gutahura neza ukuri mu 1946 .
Reka ndabiganire ingene vyagenze .
Nahavuye menya ururimi rw’ibimenyetso , maze ndahimbarwa no kuza ndakina n’abandi bana .
Nariko ndamamaza kw’ibarabara , mu ntango z’imyaka ya 1950
Mu 1950 , narimukiye i Vancouver .
Yaremeye ko noza ndamurungikira ibinyamakuru , aca ansaba n’uko noja kuganira n’umugabo wiwe Gary .
Mu nyuma , narasubiye kuba i Saskatoon .
Erega batanu muri bo bahavuye baba Ivyabona vya Yehova !
Umwe muri bo ni Eunice Colin .
Ico gihe yarampaye imbombo , mu nyuma ansaba ko twoba abagenzi .
Ndi kumwe na Eunice mu 1960 no mu 1989
Igihe yipfuza kubatizwa , abavyeyi biwe bamubwiye bati : “ Ukaramuka ubaye Icabona ca Yehova , uzoce umenya iyo uja ! ”
Yarabandanije kwiga Bibiliya , mu nyuma arabatizwa .
Igihe twubakana mu 1960 , abavyeyi biwe ntibaje ku bugeni bwacu .
Umuhungu wanje Nicholas n’umugore wiwe Deborah , bakorera kuri Beteli y’i Londres
Faye na James ; Jerry na Evelyn ; Shannan na Steven
Ubu turi mw’ishengero rya Calgary rikoresha ururimi rw’ibimenyetso , kandi ndacari umukurambere .
INDIRIMBO : 60 , 135
Twokora iki kugira ngo turushirize gukunda Yehova ?
Twokora iki kugira ngo turushirize gukunda ukuri kwo muri Bibiliya ?
Kubera iki gukunda abavukanyi bacu bihambaye ?
Ni igiki gishobora kuba caratumye urukundo rw’abakirisu bamwebamwe rukanya ?
Urukundo abantu bakunda Imana muri iki gihe ruguma rurushiriza kugabanuka .
Nugaragaze ko ukunda Yehova ( Raba ingingo ya 10 )
( Soma Zaburi 119 : 97 - 100 . )
Nugaragaze ko ukunda ukuri kwo muri Bibiliya ( Raba ingingo ya 14 )
Mw’ijoro rya nyuma Yezu yamaze ng’aha kw’isi , yabwiye abigishwa biwe ati : “ Ndabahaye ibwirizwa rishasha : mukundane . Nk’uko nabakunze , abe ari ko namwe mukundana .
Iki ni co bose bazomenyerako yuko muri abigishwa banje : nimwagiriranira urukundo hagati yanyu . ” ​ — Yoh . 13 : 34 , 35 .
Intumwa Yohani yanditse ko “ uwudakunda mwene wabo yabonye adashobora kuba akunda Imana atabonye . ”
Nugaragaze ko ukunda abavukanyi ( Raba ingingo ya 17 )
Ni ibintu bimwebimwe ibihe twokora vyerekana ko dufise urukundo ?
Soma 1 Abatesalonika 4 : 9 , 10 .
21 : 15 .
INDIRIMBO : 128 , 45
Baciye baruterera , “ mugabo ntibaba bagishobora kurukwega kubera ko ifi zari indiri . ” ​ — Yoh .
21 : 1 - 6 .
( b ) Ni icigwa gihambaye ikihe umuvukanyi umwe wo muri Tayilande yize ku bijanye n’akazi yakora ?
Ivyo vyatuma nsigarana umwanya w’ivy’impwemu muto cane ubaho .
Nahavuye mbona ko nkwiye guhindura akazi kugira ngo nshire imbere ivy’Ubwami . ”
None yokoze iki ?
Asigura ati : “ Haciye nk’umwaka ndabizirikanako , naciye mfata ingingo yo kudandariza mw’ibarabara utuntu dusosa tumeze nk’ibarafu ( crème glacée ) .
Mu ntango , naracitse intege kuko ninjiza amahera make cane .
Abo twahoze dukorana bambonye baratwenga , bakambaza igituma nahisemwo gucuruza utwo tuntu aho gukora ama orodinateri nibereye mu nzu irimwo ivyuma bitanga akayaga .
Narasenze Yehova ndamusaba ngo amfashe kwihangana no gushika kw’ihangiro ryanje ryo kuronka umwanya munini wo gukora ivy’impwemu .
Ibintu ntivyatevye kugenda neza .
Nahavuye menya ivyaryohera abakiriya banje , hanyuma nsigara ndi umuhinga mu vyo gukora utwo tuntu .
Kuva ico gihe , buri musi nta na kamwe nasubirana i muhira .
Amahera naronka yararuta kure n’iyo ayo naronka ngikora ama orodinateri .
Ubu ndahimbawe cane kubera ko ntagifise imyitwarariko n’amaganya nk’ivyo nari mfise mu kazi nahoze nkora .
N’igihambaye kuruta , ndumva ko narushirije kwiyegereza Yehova . ” ​ — Soma Matayo 5 : 3 , 6 .
Amaze kubatizwa , yavuze ati : “ Ikintu conyene nicuza ni uko natakaje umwanya munini imbere yo gutahura ko gukorera Yehova bizana umunezero mwinshi kuruta kwiruka inyuma y’ibinezereza vy’iyi si . ”
Yezu yavuze ko “ [ ata ] woshobora gushumbira ba shebuja babiri . ”
Yongeyeko ati : “ Ntimushobora gushumbira Imana n’Ubutunzi . ”
( Soma 1 Abakorinto 2 : 14 . )
Raba ikiganiro kivuga ngo “ Ukuntu wiruhura vyoba bikugirira akamaro ? ”
Vyongeye , twaraja mu ndimiro tudahorereza . ”
Twari tubabajwe cane n’ingene twohavuye dutandukana n’inyigisho zacu za Bibiliya . ”
Mugabo haciye ukwezi , bararonse agakuru keza .
Miriam avuga ati : “ Twari twagenywe kuba abatsimvyi badasanzwe .
Ese ukuntu twanezerewe cane no kwumva ko tuzoguma mu cibare cacu ! ”
Barizigiye umuhango dusanga muri Zaburi 37 : 5 , ugira uti : “ Nuragize Yehova inzira yawe , kandi umwizigire , na we ubwiwe azogira ico akoze . ”
Ubu ni bwo tubayemwo , kandi nta kintu na kimwe ca nkenerwa tubura . ”
None ni igiki kibanezereza kuruta ?
9 Nugumize umutima kw’itunga ryo mu vy’impwemu
INDIRIMBO : 38 , 56
Kubera iki twokwitega ko abubatse bashikirwa n’amakuba mu mubano wabo no mu muryango ?
Turashobora kwemera tudakeka yuko atwipfuriza ineza , nk’uko yabigirira abasavyi biwe ba kera . ​ — Soma Yeremiya 29 : 11 , 12 .
( Raba ingingo ya 9 , 12 )
( Soma 1 Samweli 1 : 4 - 7 . )
( Soma Zaburi 145 : 18 , 19 . )
“ Aho itunga ryanyu riri , ni ho n’imitima yanyu izoba . ” ​ — LUKA 12 : 34 .
INDIRIMBO : 153 , 104
Uko tubirimbura , nuzirikane ukuntu wewe ubwawe worushiriza gukunda iryo tunga ryo mu vy’impwemu .
Soma Matayo 13 : 45 , 46 .
Iyumvire nawe ukuntu yahaye agaciro cane iyo maragarita !
( Soma Mariko 10 : 28 - 30 . )
( a ) Kubera iki intumwa Paulo yavuze ko igikorwa co kwamamaza ari “ itunga mu vyombo vy’ivu ” ?
( Soma Abaroma 1 : 14 , 15 ; 2 Timoteyo 4 : 2 . )
Bamwe ni Abanyabeteli , abandi n’abatsimvyi canke abakurambere .
Irene avuga ati : “ Iyo nzirikanye iyindi migambi nari gushobora gukurikirana , nta n’umwe mbona ko wari gutuma ngira umunezero nk’uwo nifitiye ubu . ”
( Raba ingingo ya 11 , 12 )
None tuzokwigisha iki abandi ?
Reka turimbure irindi tunga Imana yaduhaye .
“ Ububiko bw’itunga ” Yezu yavuze muri Matayo 13 : 52 ni nyabaki ? Kandi tubwuzuza gute ?
( Soma Imigani 2 : 4 - 7 . )
Impwemu nyeranda ishobora gute kudufasha ?
Rimbura akarorero k’umuvukanyi yitwa Peter .
Yaciye ageza Peter mu kumubaza ati : “ None ga mwana , woba uzi ururimi igitabu ca Daniyeli canditswemwo mu ntango ? ”
Sinumva aho iyo nyishu yari ivuye .
Igihe nataha nkaraba mu Minara na Be maso !
vyo mu mezi y’imbere yaho , narabonye ikiganiro casiguye ko igice c’igitabu ca Daniyeli canditswe mu giharameya . ”
Niwabigira , uzokwirundaniriza “ ubutunzi butigera buhera mw’ijuru , aho igisuma kitegera canke ngo udukoko dukegete . ”
Yezu ati : “ Kuko aho itunga ryanyu riri , ni ho n’imitima yanyu izoba . ” ​ — Luka 12 : 33 , 34 .
“ Nari mfise ingorane yo kutumvikana n’umuvukanyi twakorana .
Igihe kimwe turiko turashwana , haraje abantu babiri maze barabona ingene duhazuka . ” ​ — CHRIS .
“ Hari umuvukanyikazi twakunda gukorana mu ndimiro , bukwi na bukwi mbona arahevye kuza arasohokana nanje .
Sinari nzi icabitumye . ” ​ — JANET .
“ Nariko ndaganira n’abantu babiri dukoresheje ubuhinga bwa none .
Umwe yarasezeye , nca nibaza ko yamaze gukupa .
Naciye ntangura kumuvuga nabi mbwira uwo wundi , ntazi ko umwe wa mbere atari bwakupe . ” ​ — MICHAEL .
“ Mw’ishengero iwacu , hari abatsimvyi babiri bari bafitaniye ingorane .
Harageze aho umwe akankamira uwundi .
Uguhazuka kwabo kwaraciye intege abandi . ” ​ — GARY .
“ Ntimutaneko ishavu mu nzira . ”
“ Imigambi irapfa ahatagira ikiyago c’akabanga . ”
Michael avuga ati : “ Uwo muvukanyi wanje yarambabariye abikuye ku mutima . ”
“ Mubandanye kwihanganirana no kubabarirana ata gahigihigi iyo hari uwufise ico yidogera uwundi . Nk’uko Yehova yabababariye ata gahigihigi , namwe nyene mugenze mutyo . ”
Ubu bamamaza inkuru nziza bafatanye mu nda .
Naho umengo ubwo budasa ntibuhambaye , burashobora gutuma haba ingorane zikomeye . ”
Vyarangeze ahantu , nca ntangura kuza ndirinda kumuvugisha .
Nibwira nti : ‘ Kubera ko atansonera , nanje sinzomusonera . ’ ”
Yigana ati : “ Naratanguye kubona utunenge ubwanje nari mfise , nca numva ndiyanse cane .
Narabonye ko nari nkwiye kwikubita agashi .
Maze gusenga Yehova ku bijanye n’iyo ngorane , naciye ngurira agakado uwo muvukanyikazi nongera ndamwandikira agakete ko kumusaba imbabazi kubera inyifato mbi nagaragaje .
Twarahoberanye duca dusezerana ko tugiye kuvyibagira .
Ntiturasubira kugiranira ingorane n’imwe . ”
INDIRIMBO : 46 , 136
ABANTU benshi muri iki gihe , babona ko amahera ari co kintu gihambaye .
Kubera iki ikibazo c’uwukwiye kuba Segaba gitegerezwa gutorerwa inyishu ?
( Soma Zaburi 83 : 18 . )
Ukwemezwa kw’ubusegaba bwa Yehova bihambaye ku rugero uruhe ?
Erega , kuva umusi ba sogokuruza bacu basinzira mu rupfu , ibintu vyose bibandanya neza na neza nko kuva mu ntango y’irema . ”
( Soma Yesaya 55 : 10 , 11 . )
( Soma Yobu 1 : 7 - 12 . )
None Yehova yamubwiye iki ?
( Soma Yobu 38 : 18 - 21 . )
Inkuru yerekeye Yobu itwigisha iki ?
( Soma Abaroma 5 : 3 - 5 . )
INDIRIMBO : 112 , 133
Imvo ya mbere ni uko Yehova ategeka abigiranye urukundo .
Iritwararika ivyacu kuruta uko ubwacu tuvyitwararika .
Abakurambere be n’abahagarikiye imiryango bokwigana gute Yehova ?
Zaburi ya 147 iratera akamo abasavyi ba Yehova ngo bamushemeze .
Ni igiki none cakoze ku mutima cane umwanditsi w’iyo zaburi , ku buryo yipfuza ko Yehova ashemezwa ?
Abavukanyi na bashiki bacu benshi bakiri bato bariko barakora n’umwete umurimo w’igihe cose .
“ Mwironderere abagenzi biciye ku butunzi butagororotse . ” ​ — LUKA 16 : 9 .
INDIRIMBO : 122 , 129
Dushobora gute kwirinda kuba abaja b’urudandaza rwo muri iyi si ?
Kubera iki mw’isi ya none hazokwama hariho abakene ?
Soma Luka 16 : 1 - 9 .
None iyo mpanuro ya Yezu itwigisha iki ?
Twemezwa n’iki yuko ibijanye n’urudandaza rwo muri iyi si bitari mu nteguro y’Imana ?
Soma Luka 16 : 10 - 13 .
Uburyo bumwe twerekana ko turi intahemuka mu vyo dutunze , ni ugutanga intererano ku bw’igikorwa co kwamamaza kw’isi yose Yezu yavuze ko coranguwe .
Ubu ndababarira abandi bivuye ku mutima , nkabihanganira , nkirengagiza amakosa bankorera kandi nkemera impanuro . ”
Aburahamu yagaragaje gute ko yizera Imana ?
( b ) Iyo mpanuro twoyishira mu ngiro gute muri iki gihe ?
Timoteyo yari n’ukwizera gukomeye .
Paulo amaze kwita Timoteyo “ umusoda mwiza wa Kristu Yezu , ” yaciye amuhanura ati : “ Nta muntu akora nk’umusoda aja mu vy’urucuruza vyo mu buzima , kugira ngo ashimwe n’uwamwanditse ngo abe umusoda . ”
Ubutunzi butuma umuntu ahimbarwa cane mu buzima ni ubuhe ?
Yehova ahezagira “ abatunzi mu bikorwa vyiza . ”
Imbaho , ivyuma be n’amabuye vyizavyiza , bizoba ari ivya gusa kugira tuvyubakishe amazu ateye igomwe .
Kugira ngo utange intererano uciye kuri internet , nuje kuri jw.org urabe amaja hepfo , maze ufyonde ahavuga ngo “ Gutanga intererano ku bw’igikorwa turangurira kw’isi yose ” .
INDIRIMBO : 90 , 111
UWITWA Susi yavuze ati : “ Igihe umwana wacu yapfa , twaramaze hafi umwaka wose dufise intuntu n’umubabaro mwinshi . ”
Igihe cose twaba tubigize , amahoro y’Imana yararinda vy’ukuri imitima yacu n’imizirikanyi yacu . ” ​ — Soma Abafilipi 4 : 6 , 7 .
Yezu yagaragaje gute impuhwe igihe Lazaro yapfa ?
Nimba nawe ufise intuntu yo kubura uwawe , urashobora guhumurizwa n’ivyanditswe bikurikira :
( Soma 1 Abatesalonika 5 : 11 . )
Dukwiye kwibuka iki ku bijanye n’ugutuntura ?
Mbere n’igihe aseruye ingene yiyumva , ntivyama vyoroshe ko abandi batahura ico aba ashaka kuvuga .
Bigenze gutyo , nca mbona ko abandi basangiye nanje umubabaro . ”
Uwitwa Juni avuga ati : “ Iyo umukirisu mugenzanje anyandikiye akajambo k’indemesho canke akantumira kumarana umwanya na we biramfasha cane .
Nca mbona ko abandi bankunda kandi ko banyitwararika . ”
Umwe Dalene avuga ati : “ Igihe abo dusangiye ukwemera baba baje kundemesha , rimwe na rimwe narabasaba ko botura isengesho turi kumwe .
Naho akenshi mu ntango wasanga bibabera urugamba , bamaze kuvuga amungane nk’angahe , ijwi ryabo ryararushiriza gushikama maze bagatura isengesho rikora cane ku mutima .
Ukwizera kwabo gukomeye n’urukundo rwabo be n’ukuntu banyitwararika , vyarakomeje cane ukwizera kwanje . ”
Bibiliya ivuga iti : “ Umugenzi nyakuri akundana igihe cose , kandi ni uwo muvukana yavukiye kuhaseruka mu gihe c’amarushwa . ”
Umuvukanyi umwe avuga ati : “ Umukenyezi wanje amaze gupfa , nari nzi ko itariki y’ubugeni bwacu niyagera nzogira intuntu ikomeye , kandi ntivyanyoroheye .
Mugabo rero hari abavukanyi na bashiki bacu batunganije ivy’uko twohurira hamwe n’abagenzi banje somambike kugira ngo uwo musi sinzobe ndi jenyene . ”
Umwe Junia avuga ati : “ Akenshi baba bakeneye ko tubafasha tukongera tukababa hafi no mu bindi bihe atari ku musi mukuru gusa .
Ibiringo nk’ivyo bisanzwe ni ngirakamaro cane kandi biraremesha rwose . ”
Mu vy’ukuri , batumye numva umengo Yehova arambumbatiye . ”
Kubera iki ivyo Yehova yadusezeraniye ari isôko ry’uruhoza rukomeye ?
Yehova asezerana ko “ urupfu azorumira miyonzwa gushitsa ibihe bidahera , kandi Umukama Segaba Yehova azohanagura koko amosozi mu maso ha bose . ”
Ibindi vyanditswe vyaremesheje abatari bake ni Zaburi 20 : 1 , 2 ; 31 : 7 ; 38 : 8 , 9 , 15 ; 55 : 22 ; 121 : 1 , 2 ; Yesaya 57 : 15 ; 66 : 13 ; Abafilipi 4 : 13 ; na 1 Petero 5 : 7 .
Raba kandi ikiganiro kivuga ngo “ Nuremeshe ababuze , nk’uko Yezu yabigize ” , mu Munara w’Inderetsi wo ku wa 1 Munyonyo 2010 .
“ Ntitubona ico turi buvuge uretse gusa kubabwira ko tubakunda .
Naho twebwe tudatahura neza na neza intuntu mufise , Yehova wewe arayizi kandi azokwama abashigikira .
Turizigira yuko amasengesho dutura ku bwanyu azogira ico afashije . ”
“ Ese Yehova yobandanya kubashigikira muri iki gihe kitoroshe murimwo . ”
“ Ese mwohumurizwa no kumenya ko Imana itazokwibagira uwo mwabuze mutanka , be n’uko izomuzura . ”
“ Uwo mwabuze mutanka ntazokwigera asubira guhura na wa mwansi wa nyuma rupfu .
Ibikorwa vyiwe vy’ukwizera bizogumaho gushika asubiye kuba muzima mw’Iparadizo . ”
“ Naho ubu ata majambo tworonka adondora intuntu mufise , turashashaye igihe tuzobura amajambo yo kudondora umunezero muzogira Data wa twese wo mw’ijuru niyazura uwo mwabuze mutanka . ”
Mu gihe ca ya makuba akomeye , abakirisu bazokwiheka kuri Yehova aho kugerageza kwirwanira
Umwamamaji ariko arabwira inkuru nziza umukozi umwe ari mu mirima y’amapome , mu karere ka Grójec
INDIRIMBO : 59 , 3
( b ) Iyo zaburi iduhimiriza gukora iki ?
( Soma Zaburi 147 : 5 . )
Nipfuza ko wogira umunezero mu buzima kubera ko uri Icabona canje ! ”
( Soma Zaburi 147 : 8 , 9 . )
Mutsuo avuga ati : “ Nabona ko ari nk’aho Yehova yari iruhande y’umwe wese muri twebwe , ariko aramwitwararika .
Ese ukuntu vyaduhumurije ! ”
12 , 13 . ( a ) Dukwiye kwirinda iki nimba twipfuza gufashwa n’Imana ?
Ku rundi ruhande , Yehova “ a [ ra ] manura ababisha gushika hasi . ”
‘ Yehova ahimbarwa n’abamutinya , abarindira ubuntu bwuzuye urukundo bwiwe . ’
( Raba ingingo ya 15 - 17 )
15 - 17 . ( a ) Ingorane zidushikira zishobora gutuma twiyumva gute , ariko Yehova adufasha gute biciye kw’Ijambo ryiwe ?
Muri iki gihe , Yehova atuyobora akoresheje Ijambo ryiwe Bibiliya .
( Soma Zaburi 147 : 19 , 20 . )
INDIRIMBO : 135 , 81
Ni imigambi iyihe yotuma ugira kazoza keza ?
Gukora ubutsimvyi bishobora kugushikana ku duteka utuhe ?
YEMWE rwaruka , ngira ngo muremera ko imbere y’uko umuntu afata urugendo , biba vyiza abanje gutegekanya iyo azoja .
Ubuzima ni nk’urugendo , kandi mu gihe c’ubuto ni ho umuntu ategura urwo rugendo .
Wemezwa n’iki ko Yehova yipfuza ko utegura neza kazoza kawe ?
Yipfuza ko uhimbarwa .
Yehova yipfuza ko wokwishingira imigambi iyihe ?
None ni imigambi iyihe Yehova yipfuza ko wokwishingira ?
Umuremyi wawe ni “ Imana y’urukundo , ” “ Imana ihimbawe , ” iyaremye abantu “ mw’ishusho yayo . ”
Niwigana iyo Mana yacu y’urukundo , uzohimbarwa .
Ni ibiki vyatumye Yezu ahimbarwa ?
Yezu Kristu yarabereye akarorero keza mwebwe abakiri bato .
Vyongeye , Yezu yariyegereza Yehova mu kwiga Ivyanditswe .
Bibiliya ivuga iti : “ Imigambi irapfa ahatagira ikiyago c’akabanga , mugabo mu bajanama indiri haragira igishitsweko . ”
Nk’uko biri no ku yindi myuga , bizogusaba igihe kugira ngo ube umuhinga muri ico gikorwa .
Mu ntango , sinashobora kuronka inyigisho ya Bibiliya n’imwe . Mugabo igihe nimukira mu kandi karere , mu kwezi kumwe gusa naratanguje inyigisho zitari nke .
Umwe muri bo yaratanguye kuza ku Ngoro y’Ubwami .
Nk’akarorero , uwitwa Jacob wo muri Amerika ya Ruguru , avuga ati : “ Igihe nari mfise imyaka indwi , abenshi mu bo twigana bari Abanyaviyetinamu .
Kubera ko nipfuza kubabwira ivyerekeye Yehova , nahavuye niga ururimi rwabo .
Ahanini , narwiga mu kuza ndagereranya Umunara w’Inderetsi w’icongereza n’uw’ikiviyetinamu .
Nararondeye n’abagenzi mw’ishengero ribanyi ryakoresha ikiviyetinamu .
Igihe nari mfise imyaka 18 , naratanguye ubutsimvyi .
Mu nyuma , naritavye Ishure ry’ivya Bibiliya ry’abavukanyi batubatse .
Ivyo vyaramfashije cane mu cibare nkoreramwo ubu , aho ndi umukurambere umwe gusa mu mugwi ukoresha ikiviyetinamu .
Abanyaviyetinamu benshi baratangazwa no kubona mvuga ururimi rwabo .
Barantumira iwabo , kandi akenshi nca ndabigisha Bibiliya .
Bamwe muri bo barateye imbere barabatizwa . ” ​ — Gereranya n ’ ​ Ivyakozwe 2 : 7 , 8 .
Natanguye ubutsimvyi nkirangiza amashure .
Ndaryoherwa no kuremesha abavukanyi bakiri bato bo mw’ishengero iwacu no kwibonera ingene batera imbere mu vy’impwemu .
Igihe narangiza Ishure ry’ivya Bibiliya ry’abavukanyi batubatse , naciye ndungikwa gukorera mu kandi karere .
Naho muri ako karere ntarigera ndonka uwutera imbere akabatizwa , abandi barabaronse .
Hariho uturyo twinshi two gukorera Yehova .
Haracakenewe Ingoro z’Ubwami nyinshi cane .
Ubutsimvyi bushobora gute gutuma umuntu ashikira utundi duteka ?
Umuvukanyi yitwa Kevin avuga ati : “ Kuva nkiri umwana mutoyi , namye nipfuza gukorera Yehova mu murimo w’igihe cose .
Nahavuye ntangura ubutsimvyi mfise imyaka 19 .
Kugira ngo nibesheho , naza ndisumamwo ku muvukanyi umwe yakora ivyo kwubaka .
Narize gusakara , gutera imiryango n’amadirisha .
Mu nyuma , naramaze imyaka ibiri nkorana n’umugwi watabara abatewe n’igihuhusi , ugasanura Ingoro z’Ubwami n’amazu y’abavukanyi .
Igihe numva ko muri Afrika y’Epfo hari hakenewe abubatsi , naciye nuzuza urupapuro rwo gusaba maze baranyemerera .
Ino muri Afrika , mu ndwi nka zingahe tuba turangije kwubaka Ingoro y’Ubwami tugaca twimukira ahandi .
Abagize umugwi nkoreramwo ni nk’umuryango .
Turabana , tukigira hamwe Bibiliya tukongera tugakorana .
Vyongeye , ndahimbarwa no gukorana indimiro buri ndwi n’abavukanyi bo mu karere tuba turimwo .
Imigambi nishingiye nkiri muto yaratumye ngira agahimbare ntigeze niyumvira . ”
Umurimo wo kuri Beteli uratera umunezero kuko igikorwa cose umuntu ashingwa ari ica Yehova .
Haciye umwaka n’igice , narahamagawe kuri Beteli . Narahigiye gukoresha imashini zicapura , mu nyuma na ho niga ibijanye no gutunganya amaporogarama ya ordinateri .
Kuri Beteli , ndahimbarwa no kwumva raporo zijanye n’iterambere ririko riraba mu gikorwa co kwamamaza kw’isi yose .
Ndakunda gukorera kuri Beteli kuko dufasha abantu kwiyegereza Yehova . ”
Yehova yipfuza ko ‘ ucakira ’ kazoza keza .
( Soma 1 Timoteyo 6 : 18 , 19 . )
Nuce rero utegekanya gukora ibimuhimbara .
URAGABA !
Yatanguye kugendereza abantu kuva bakiremwa .
None worwanya gute ivyiyumviro vyiwe ?
Ni ikintu utegerezwa kwironderera . ”
Yezu yavuze ati : “ Ntimutinye abica umubiri , inyuma y’ivyo ntibashobore kugira ikindi kintu na kimwe . ”
None Yehova yavyakiriye gute ?
Bariko baraguhenda ! ’
Niwumvirize Yehova kandi umwizigire mu vyo ukora vyose .
3 Woba uzorindira wihanganye ?
Ica kabiri , kirimbura ingene Yehova ashobora gukora ibintu bitangaje tutaba twiteze .
27 Urukundo ​ — Kamere y’agaciro
INDIRIMBO : 114 , 79
Nka kurya kw’umurimyi , turakeneye kurindira twihanganye .
Twigira iki ku karorero k’umuhanuzi Mika ?
( Soma Mika 7 : 1 - 3 . )
Nimba dufise ukwizera nk’ukwa Mika , tuzorindira Yehova n’umutima ukunze .
Ni co gituma ‘ twihangana bimwe bishitse kandi tukiyumanganya tunezerewe . ’
Aburahamu yararindiriye imyaka myinshi imbere y’uko abuzukuru biwe Esawu na Yakobo bavuka ( Raba ingingo ya 9 , 10 )
Rimbura akarorero ka Aburahamu na Sara .
Kubera iki none Aburahamu yari akeneye kwihangana ?
( Soma Abaheburayo 11 : 8 - 12 . )
Iyumvire rero umunezero azogira niyazukira mw’isi y’iparadizo !
Ni uko yizera Yehova .
Mugabo Imana yiyumviriye kugihinduramwo iciza kugira ikore ibintu nk’uko biri uyu musi : kugira izigamire ubuzima abantu benshi . ”
( b ) Ni igiki cafashije Dawidi kurindira yihanganye ?
Ni igiki none catumye Dawidi yihangana n’umutima ukunze ?
Nzoririmbira Yehova , kuko yangiriye neza . ”
( Soma 2 Petero 3 : 9 . )
Ni ibiki bizodufasha kurindira twihanganye ?
INDIRIMBO : 112 , 58
Ivyashikiye intumwa Paulo i Filipi bitwigisha iki ?
( Soma Ivyakozwe 16 : 8 - 10 . )
Paulo amaze igihe gito ashitse i Makedoniya , yaciye atabwa mw’ibohero .
Ni kubera iki none Yehova yaretse bikamushikira ?
We na Silasi baciye batangura ‘ gusenga no gushemeza Imana mu kuririmba . ’
4 , 5 . ( a ) Dushobora gute gushikirwa n’ivyashikiye Paulo ?
( b ) Ivya Paulo vyahindutse gute mu buryo atari yiteze ?
Ese ingene ibintu vyahindutse mu kanya isase !
Tugiye kwihweza iki ?
( Soma 1 Petero 5 : 6 , 7 . )
Rimwe na rimwe aradukorera n’ivyo tutaba twiteze .
Yehova yarungitse umumarayika umwe maze aratikiza ingabo 185.000 za Senakeribu mw’ijoro rimwe gusa .
( a ) Ivyashikiye Yozefu bitwigisha iki ?
Nta gukeka ko Yehova yakoreye Yozefu ibirengeye ivyo yari yiteze .
Zirikana kandi ivyerekeye Sara inakuruza wa Yozefu .
Kubera iki dukwiye kwizigira Yehova tudakeka ?
( Soma Yesaya 43 : 10 - 13 . )
Tuba tuzi ko Yehova atwitwararika kandi ko atwipfuriza ineza .
INDIRIMBO : 121 , 142
Ni igiki gituma umuryango wacu w’abavukanyi ukwiye kw’isi yose uba uwudasanzwe ?
Ni ibiki vyodufasha kwambura wa muntu wa kera ?
Mu 1939 , abashika 6.000 barapfungiwe mu [ makambi y’itunatuniro ] . ”
Kandi iyi stade mwarayisukuye neza cane .
Igitangaje kuruta , ni uko mudasangiye ibara ry’urukoba . ”
Ni igiki gituma umuryango wacu w’abavukanyi uba uwudasanzwe ?
Ubusambanyi .
Ariko uko naryamana n’abahungu ni ko narushiriza kwumva ntatekanye . ”
Sakura yarabandanije iyo ngeso kugeza ashikanye imyaka 23 .
Ubuhumane .
Harageze n’aho ntari nkirindira ko umugore twabana asohoka , kugira ndabe amavidewo y’ibiterasoni . ”
Ni igiki cafashije Stephen guheba uburake no gutukana ?
Avuga ati : Urugo rwacu rwaragize amahoro y’igitangaza .
Ubu Stephen ni umukozi w’ishengero , umukenyezi wiwe na we akaba amaze imyaka itari mike ari umutsimvyi asanzwe .
Ariko rero si ko yamye .
Ivyanditswe vyandemesheje ni Yesaya 55 : 7 , ahagira hati : ‘ Umubisha nahebe inzira yiwe , ’ be na 1 Abakorinto 6 : 11 , ahavuga ku vyerekeye abahevye ingeso mbi bahoranye hati : ‘ Yamara ukwo ni ko bamwe muri mwebwe bari bameze . ’
Yehova yaramaze imyaka myinshi amfasha kwambara umuntu mushasha , biciye ku mpwemu yiwe nyeranda . ”
Vyongeye , turakwiye gukoresha neza ibikoresho bitandukanye ishirahamwe rya Yehova rituronsa .
Muri iki kiganiro , bamwebamwe si ko bitwa .
Raba igitabu Ibibazo urwaruka rwibaza ​ — Inyishu ngirakamaro , Igitabu ca 1 , ikigabane ca 25 .
INDIRIMBO : 126 , 28
( Soma Abakolosayi 3 : 10 - 14 . )
Avuga ati : “ [ Nta ] Mugiriki canke Umuyuda , ukugenyerwa canke ukutagenyerwa , umunyamahanga canke Umusikite , umushumba , [ canke ] uwidegemvya . ”
( a ) Abasavyi ba Yehova bakwiye gufata abandi gute ?
( Raba ishusho itangura . ) ( b ) Ivyiza vyavuyemwo ni ibihe ?
Igihe kimwe yaragiye ku makoraniro y’Ivyabona vya Yehova .
Naho wimuka , umengo wagumye mu gisagara iwanyu .
Uribonera umuryango wacu w’abavukanyi ukwiye kw’isi yose , ukibonera n’ubumwe butangaje bafitaniye . ”
( Raba ingingo ya 10 )
Tuberetse ivyanditswe muri Bibiliya yabo y’igiportigale , nk ’ ​ Ivyahishuwe 21 : 3 , 4 canke Zaburi 37 : 10 , 11 , 29 , barakurikira bitonze , mbere rimwe na rimwe bagakorora amosozi . ”
Ntiworaba ingene dukengurukira Yehova . ” ​ — Soma Ivyakozwe 10 : 34 , 35 .
( Gereranya na Ezekiyeli 28 : 17 . )
Soma Imigani 22 : 4 .
Yezu yatubereye gute akarorero mu bijanye n’ukwitonda be n’ukwihangana ?
Yezu na we nyene ‘ yaritonda . ’
Tweho none twogaragaza gute ukwitonda n’ukwihangana ?
Kubera iki ukwitonda n’ukwihangana bihambaye ?
Yaciye yongerako ati : “ Nimba mubandanya kugira nkunzi , muriko mukora igicumuro . ”
Kubera iki bihambaye ko twambara urukundo ?
Vyongeye , urukundo “ ruriyumanganya kandi rugira ubuntu , ” eka kandi “ ntirwivyimvya . ”
UKWIYUMANGANYA
UBUNTU
UKUMERA NEZA
UKWIZERA
UBWITONZI
UKWIGUMYA
Paulo yavuze ko atarufise yoba ari “ ubusa . ”
Muri ivyo urukundo ni uru : si uko twakunze Imana , ahubwo ni uko ari yo yadukunze igatuma Umwana wayo ngo abe ikimazi c’impongano ku bw’ibicumuro vyacu . ”
Nta muntu yari gushobora kugaragaza bene urwo rukundo .
Yezu yavuze ati : “ Nta wufise urukundo ruruta uru : ko umuntu yigura abagenzi biwe . ”
Reka turimbure ukungene twobikora .
Yohani yanditse ati : “ Bana bato , dukundane , atari mu majambo canke ku karimi , ahubwo mu bikorwa no mu kuri . ”
Vyarambabaje cane .
Ariko naciye nibaza nti : ‘ Iyaba yari Yezu yari gukora iki ? ’
Maze kuzirikana ku co Yezu yari gukora , sinabigize birebire , naciye ndavyirengagiza .
Mu nyuma naramenye ko uwo mukozi yari yifitiye indwara ikomeye kandi ko atari yorohewe .
Naciye mbona ko atabivuze abikuye ku mutima .
Kuzirikana ku kuntu Yezu yagaragaje urukundo n’igihe yaba abwiwe nabi , vyaramfashije kugaragariza urukundo uwo mukozi twakorana . ”
Igihe yava mw’ijuru , “ yarahevye vyose ” ku bwacu mbere no “ gushika ku rupfu . ”
Twungukira gute ku kugaragaza urukundo ?
AMAHORO : ‘ Kwihanganirana mu rukundo ’ bituma turyohererwa uwo “ umugozi w’amahoro wunga ubumwe . ”
Ntiwemera none ko ayo mahoro ari imbonekarimwe muri iyi si yuzuyemwo ivy’ukwicamwo ibice ?
Ihwaniro ryo mu 1941 , ku murwa mukuru wa Megizike
Bukeye , aho bagiriye igikorane hari huzuye no ku bunwa . ”
Ishengero rimwe ryavuze ko ata gariyamoshi n’imwe yashika iwabo .
Abandi barara mu Ngoro z’Ubwami .
Muri Megizike , abantu 2.262.646 ni bo bitavye Icibutso mu 2016 .
Inkuru ya Matayo ishimika kuri Yozefu .
3 Nube umuntu yigumya
Kuba umunyempuhwe bisobanura iki ?
INDIRIMBO : 121 , 36
1 , 2 . ( a ) Kutigumya bivamwo ingaruka izihe ?
Ariko twebwe ntidutunganye .
Akarorero ka Yehova katwigisha iki ?
Wokwitegurira gute gutsinda inyosha mbi ?
Ni ibiki vyashikiye umuvukanyi umwe , kandi ni kubera iki inyifato tugira mu bihe nk’ivyo ihambaye ?
Abavyeyi bashobora gute gufasha abana babo kugira ngo barushirize kwigumya ?
Ushobora gute gufasha abana bawe kugira barushirize kwigumya ?
INDIRIMBO : 57 , 147
( Soma Kuvayo 34 : 5 - 7 . )
( b ) Kubera iki twokwitaho ivyo Bibiliya ivuga ku bijanye n’impuhwe ?
( a ) Kubera iki Yehova yarungitse abamarayika i Sodomu ?
( Soma Kuvayo 22 : 26 , 27 . )
Dusoma duti : “ Yehova Imana ya ba sekuruza babo aguma abarungikira imburi biciye ku ntumwa ziwe , akazirungika incuro n’izindi , kuko yumvira impuhwe abantu biwe n’aho aba . ”
“ [ Yaciye ] atangura kubigisha ibintu vyinshi . ”
Uruhara rwacu ni ugukora uko dushoboye kwose kugira dufashe abantu .
Nufashe abandi mu buzima bwa misi yose .
Imwe mu nsobanuro y’ijambo impuhwe ni “ ukubabarana . ”
Nufashe mu bikorwa vyo gutabara .
Ni we Karorero ntangere mu kugaragaza impuhwe .
“ Gira umutima rugabo kandi ukomere , ukore .
INDIRIMBO : 38 , 34
Abakiri bato be n’abavyeyi babo bogaragaza gute umutima rugabo ?
1 , 2 . ( a ) Salomo yashinzwe igikorwa gihambaye ikihe ?
Kugira ngo Salomo ashobore ico gikorwa , vyomusavye kugira umutima rugabo , agakora .
Salomo yigiye gute kuri se wiwe ibijanye no kugaragaza umutima rugabo ?
Kubera iki Salomo yari akeneye umutima rugabo ?
Kubera iki dukeneye umutima rugabo ?
Ni igiki gitangaje ku bijanye n’umutima rugabo Yozefu yagaragaje ?
Akandi karorero ni aka Rahabu .
Umutima rugabo Yezu yagaragaje wafashije gute intumwa ?
Nimuze twihweze imice ibiri dukeneramwo kugira umutima rugabo : mu muryango no mw’ishengero .
( b ) Abakiri bato bomwigana gute ?
Azobafasha kuronsa imiryango yabo ivyo ikeneye .
( Raba ingingo ya 13 - 17 )
Yandika ati : “ Nakuze ndi umunyamasoni .
Vyarangora kuyagisha abantu ku Ngoro y’Ubwami , icibagiwe coco kwari ukuja kudodora ku muhana kanaka . ”
Afashijwe n’abavyeyi biwe be n’abandi bo mw’ishengero , uwo mushiki wacu yahavuye ashika kw’ihangiro ryiwe ryo kuba umutsimvyi asanzwe .
Abavyeyi na bo nyene barakeneye kugira umutima rugabo .
Zaburi 37 : 25 be n ’ ​ Abaheburayo 13 : 5 , hofasha gute abavyeyi ?
( Soma Zaburi 37 : 25 ; Abaheburayo 13 : 5 . )
Umuvukanyi umwe afise abana babiri yanditse ati : “ Abavyeyi benshi bakoresha umwanya munini n’amahera menshi mu gufasha abana babo gushika ku migambi y’ivyo kwinonora imitsi , kwiruhura canke ivy’amashure .
Birarushirije rero kwumvikana ko twogira akigoro gakomeye kandi tugakoresha uburyo bwinshi kugira dufashe abana bacu gushika ku migambi ituma baguma bafitaniye ubucuti bwiza na Yehova .
Turahimbarwa no kubona ko ako kigoro katabaye impfagusa , kuko abana bacu bashitse ku migambi bishingiye . ”
Ni ibintu bimwebimwe ibihe bisaba kugaragaza umutima rugabo mw’ishengero ?
Ni ryari vyokenerwa ko bashiki bacu bitereye mu myaka bagaragaza umutima rugabo ?
( a ) Ni ibiki vyofasha abavukanyi babatijwe kugira umutima rugabo ?
( Soma Abafilipi 2 : 13 ; 4 : 13 . )
Yemwe bavukanyi mwese mwabatijwe , tubaremesheje kugira umutima rugabo maze mukorere ishengero !
Nimuze rero tugire ‘ umutima rugabo , dukore . ’
INDIRIMBO : 95 , 97
amahinduka ajanye n’ururimi ?
amahinduka ya politike ?
abarirwanije ngo ntirishirwe mu zindi ndimi ?
1 , 2 . ( a ) Ubuzima buba bumeze gute iyaba Bibiliya itariho ?
Intumwa Petero yarasubiyemwo amajambo yo muri Yesaya 40 : 8 .
( Soma 1 Petero 1 : 24 , 25 . )
( Soma Ivyahishuwe 14 : 6 . )
N’impinduro zayo zasohotse mu nyuma , zakoresheje izina “ UMUKAMA ” mu ndome nkuru mu mirongo imwimwe y’Ivyanditswe vy’ikigiriki .
Ni kubera iki dukenguruka Bibiliya y’isi nshasha ?
( b ) Bibiliya yitwa Septante ni iki ?
Ni igiki none cari kubafasha ?
( Soma Zaburi 119 : 162 - 165 . )
Ku wa 3 Ndamukiza 2017 , ku cicaro gikuru cacu kiri i Warwick muri Leta Zunze Ubumwe za Amerika , haruguruwe iratiro ry’ivya Bibiliya .
Igice nyamukuru c’iryo ratiro cataziriwe ngo “ Bibiliya be n’izina ry’Imana . ”
Kaze wirabire iryo ratiro be n’ayandi ari ku cicaro gikuru cacu .
Nuje kuri www.jw.org kugira ngo umenyeshe igihe wipfuza kuza .
Raba ahavuga ngo IBITWEREKEYE > AMABIRO / GUTEMBEREZWA .
igihe wigisha mw’ishengero ?
Yamusomeye mu 2 Abakorinto 1 : 3 , 4 , ahagira hati : “ Se w’imbabazi zuzuye ikibabarwe ikaba n’Imana y’uruhoza rwose , [ iraduhoza ] mu makuba yacu yose . ”
Abavukanyi bigisha mw’ishengero bafise ibanga irihe ?
None ntidukengurukira Yehova kuba dufise Ijambo ryiwe Bibiliya ?
Raba uruzitiro ruvuga ngo “ Ihinduka rikomeye . ”
Niwame urisoma
Nurizirikaneko
Nushire mu ngiro ivyo usoma
Nusome icanditswe , ugisigure , ugitangire ikigereranyo , werekane n’ingene coshirwa mu ngiro
“ Haciye nk’imyaka 15 mbatijwe , harabaye ihinduka rikomeye .
Mu nsiguro imwe yashikirijwe mu Ngoro y’Ubwami . . . , uwariko arayishikiriza yarakoresheje icanditswe co muri Yakobo 1 : 23 , 24 .
“ Haciye imisi mikeyi , narasomye icanditswe cahinduye ubuzima bwanje .
Ico canditswe ni Yesaya 1 : 18 , aho Yehova avuga ati : ‘ Nimuze rero tugorore ibintu hagati yacu . . . .
Naho ibicumuro vyanyu vyoba bimeze nk’agahama , bizogirwa ivyera derere . ’
Numva umengo ni jewe Yehova yariko abwira , ati : ‘ Enda nuze Vicky tugorore ibintu hagati yacu .
Ndakuzi , ndazi ibicumuro vyawe n’umutima wawe , kandi ndagukunda . ’
“ Iryo joro sinagohetse .
Ariko jewe ni nk’aho nariko ndamubwira nti : ‘ Urukundo rwawe ntiruhagije ku buryo rwonshikira .
Incungu y’Umwana wawe ntihagije ku buryo yopfuka ibicumuro vyanje . ’
Mugabo aho nzirikaniye kuri iyo ngabirano y’incungu , naza natangura kwiyumvamwo ko Yehova ankunda . ”
Ibi biganiro biraca irya n’ino ivyo Zekariya yabonye mw’iyerekwa rya gatandatu , iry’indwi n’iry’umunani .
31 Igikorwa kiranga ubuntu
Nk’uko vyavuzwe na Olive Matthews
Reka mbanze ndabacire ku mayange kahise kanje .
NAVUTSE mu 1923 , mvukira i Hemsworth mu gisagara co mu Bwongereza citwa Yorkshire .
Musazanje mukuru yitwa Bob .
Mu mwaka wakurikiye , naciye mba umutsimvyi adasanzwe , hamwe na Mary Henshall .
Twarungitswe mu karere katakorerwamwo , mu ntara ya Cheshire .
Namenyanye na Arthur Matthews mu 1946 .
Mu nyuma twaza turandikirana udukete .
I Hemsworth , inyuma y’ubugeni bwacu mu 1949
Musazanje be n’umugore wiwe Lottie , bari abatsimvyi badasanzwe muri Irlande ya Ruguru .
Mu 1952 , twe n’umugabo wanje hamwe na bo twaritavye ihwaniro ry’intara ryabereye i Belfast .
Twaciye tuja kurondera inzu , mugabo turayibura .
Ni ko twaciye tubamwo .
Igishimishije , abarimyi bo muri ako karere baratureka tukarara muri ako kazu kacu ku matongo yabo .
Ntiworaba ingene igikorwa co kugendera amashengero caturyoheye !
Emwe , wabaye umuhezagiro ntangere !
Ihwaniro mpuzamakungu rya mbere ryo muri Irlande ryabereye i Dublin mu 1965 .
Ryitabwe n’abantu 3.948 , habatizwa 65 .
Arthur ariko aramutsa Nathan Knorr igihe yari aje kw’ihwaniro mu 1965
Igihe Arthur yasohora Igitabu Canje c’Inkuru za Bibiliya mu rurimi rwitwa gayelike , mu 1983
Mu 2011 , harabaye ihinduka rikomeye mu buzima bwacu igihe ishami ryo muri Irlande ryashirwa hamwe n’iry’i Londres mu Bwongereza .
Bari bamutoye indwara y’urujugumizi ( maladie de Parkinson ) .
Muri iyi myaka mikeya iheze , naravunitse umutima , ndagira intuntu n’umubabaro .
Ariko iyo umuntu ashikiwe n’ibintu nk’ivyo , ararushiriza kwiyegereza Yehova .
“ Dukundane , atari mu majambo canke ku karimi , ahubwo mu bikorwa no mu kuri . ” ​ — 1 YOH . 3 : 18 .
INDIRIMBO : 106 , 100
Urukundo rurengeye urundi rwose ni uruhe ?
“ Urukundo ruzira ubwiyorobetsi ” rumeze gute ?
Yehova yaragaragarije abantu gute urukundo ruzira ubwikunzi ?
Yehova yagaragarije abantu urukundo n’imbere yuko arema Adamu na Eva .
Ni mu buryo butandukanye ubuhe dushobora kugaragaza urukundo nyakuri ?
6 , 7 . ( a ) “ Urukundo ruzira ubwiyorobetsi ” rumeze gute ?
Dukwiye kwibaza ikibazo ikihe ?
( Soma Matayo 6 : 1 - 4 . )
Kubera iki dukwiye gukeza abandi tubikuye ku mutima ?
Twogaragariza gute abandi ubwakiranyi tubigiranye urukundo nyakuri ?
Nube umwakiranyi .
( Soma 1 Yohani 3 : 17 . )
Nubane amahoro n’abandi .
( Soma Abaroma 12 : 17 , 18 . )
Twokwerekana gute ko twababariye umuntu vy’ukuri ?
Niwihebere abandi .
Ni kubera iki urukundo nyakuri ruhambaye cane ?
Urukundo ni yo kamere irengeye izindi zose .
INDIRIMBO : 123 , 128
“ Inkota ” Yezu yavuze ko yozanye ni nyabaki ?
Ushobora gute kuguma uri umwizigirwa kuri Yehova igihe incuti zawe zirwanya ugusenga kw’ukuri ?
3 , 4 . ( a ) Inyigisho za Yezu zituma haba ingorane iyihe ?
Yezu yavuze ati : “ Ntimwiyumvire ngo naje gushira amahoro kw’isi ; sinaje gushiraho amahoro , atari inkota .
Kuko naje gucanishamwo abantu : umuhungu akarwanya se , n’umukobwa akarwanya nyina , n’umukazana akarwanya inabukwe .
Abayoboke ba Yezu bihanganiye ibiki ?
Abakirisu bokwigisha gute abana babo gutera iteka umuvyeyi atizeye ?
Ahubwo , nusigurire abo bana ko umwe wese afise uburenganzira bwo gusenga Yehova canke kutamusenga .
Nuvugane ubwitonzi .
Bibiliya ivuga iti : “ Imvugo yanyu yamane igikundiro . ”
( Soma 1 Petero 3 : 1 , 2 , 16 . )
Niwitegure imbere y’igihe .
Bishitse ukumva ko wiyagiriza kubera ko udahuza n’incuti zawe , wokora iki ?
Niwubahirize intunganyo yo gutozwa indero na Yehova .
( Soma Abaheburayo 12 : 11 . )
Kimwe mu bibanza vyinshi Ivyabona bamamazamwo ku mugaragaro i Lagos .
INDIRIMBO : 89 , 86
Ivy’Abisirayeli vyari vyifashe gute ico gihe ?
( Soma Zekariya 1 : 3 , 4 . )
Ikigabane ca 5 c’igitabu ca Zekariya gitangurwa n’ikintu gitangaje yeretswe .
( Soma Zekariya 5 : 1 , 2 . )
Soma Zekariya 5 : 3 , 4 .
8 - 10 . ( a ) Umuntu arahira kubera iki ?
Ivyo Zekariya yabonye mw’iyerekwa rya gatandatu bitwigisha iki ?
( Soma Zekariya 5 : 5 - 8 . )
( Soma Zekariya 5 : 9 - 11 . )
INDIRIMBO : 61 , 22
Ubona gute igikorwa gihambaye cane co kwubaka kiriko kirarangurwa muri iki gihe ?
( Soma Zekariya 6 : 1 - 3 . )
Yehova aracakoresha abamarayika mu gukingira abasavyi biwe no mu kubakomeza
7 , 8 . ( a ) Ya misozi ibiri igereranya iki ?
( b ) Kuba ari iy’umujumpu bitwibutsa iki ?
Kubera iki iyo misozi ari iy’umujumpu ?
Ya mikogote n’abayigenderako bigereranya iki , kandi bashinzwe ibanga irihe ?
( Soma Zekariya 6 : 5 - 8 . )
Uwo musi uzoba ukomeye koko !
( Soma Zekariya 6 : 9 - 12 . )
( Soma Zekariya 6 : 13 . )
Emwe , ugusenga kw’ukuri kuzoba kwiganje hose !
( Soma Zekariya 6 : 15 . )
Yehova ntazokwigera yibagira urukundo tumukunda !
( Raba ingingo ya 18 , 19 )
SE WA John yabatirijwe mu gasagara k’i Gujarat mu Buhindi , mu mpera z’imyaka ya 1950 .
Uwo mukenyezi yarabonye ko John yari yikomerekeje ku rutoke aca amubaza ko yoshima ko amuvura .
Yaciye aja kuraba umupadiri amubaza vya bibazo bibiri .
Nyereka aho Bibiliya ivuga ko Yezu atari Imana .
Nyereka aho ivuga ko udakwiye gusenga Mariya .
Hanyereke ! ”
Emwe , imvugo yabaye ingiro !
3 Ririmbana umunezero !
Turashobora gukura ivyigwa ngirakamaro kuri vya bisagara vy’ubuhungiro vyo muri Isirayeli ya kera .
INDIRIMBO : 10 , 2
Kuririmba bifise uruhara uruhe mu gusenga kw’ukuri ?
( b ) Twobigenza gute igihe turirimbira Yehova amashemezo , kandi ni bande bakwiye gufata iya mbere ?
Soma amajambo yarwo n’ijwi ryumvikana .
( a ) Guteranura akanwa bidufasha gute mu kuririmba ?
( Raba ingingo ya 11 - 14 )
Kwega impemu zikwiye
Nimwimenyereze indirimbo mu gusenga kwo mu muryango ( Raba ingingo ya 18 )
( Soma Yesaya 12 : 5 . )
INDIRIMBO : 8 , 54
( Soma Zaburi 34 : 22 . )
( Soma Guharūra 35 : 24 , 25 . )
Atereje amaso inyuma , avuga ati : “ Ntabeshe , narumva ubwoba bwo kubitura .
( Soma Yosuwa 20 : 4 . )
Yavuze ati : ‘ Ehe ico kintu nyene , ni ukuvuga ukubabara kwanyu guhuye n’ukugomba kw’Imana , ingene cabazanyemwo ubwira bwinshi , ukwikurako ibara , ishavu , ubwoba , icipfuzo gikomeye , umwete , n’ugusubiza ibintu mu buryo ! ’
Iyo Yehova ababariye umuntu , biba biheze .
Kubera iki wohungira kuri Yehova ?
Woba uriko urahungira kuri Yehova ?
Nta handi woronka ubuhungiro !
INDIRIMBO : 125 , 88
Twokwigana gute imbabazi za Yehova igihe abandi baducumuyeko ?
1 , 2 . ( a ) Yezu yabona gute Itegeko ry’Imana ?
None bari bafise ingorane iyihe ?
( b ) Ivyo bitwigisha iki ku vyerekeye Yehova ?
( Soma Ivyakozwe 20 : 26 , 27 . )
Kubera iki bihambaye ko abasavyi b’Imana birinda amasanganya ?
( Soma Guharūra 35 : 20 - 24 . )
Nimugende rero mwige ico ibi bisobanura ngo : ‘ Ico nshaka ni imbabazi , si ibimazi . ’
Kuko ntaje guhamagara abagororotsi , ahubwo naje guhamagara abacumuzi . ”
Ibifungurwa si vyo vyonyene vyari vyabazanye kwa Matayo .
Ubwa mbere , nusabe Imana ubukerebutsi n’ugutahura .
Rya Tegeko rya Musa cari “ igikanka c’ubumenyi n’ic’ukuri . ”
Bashiki bacu babiri bariko barabwira ubutumwa bwo muri Bibiliya umudandaza mu gisagara ca Tipitapa
INDIRIMBO : 38 , 31
Ni impanuro iyihe iranga urukundo intumwa Paulo yatanze ku bijanye n’ivyiyumviro vy’isi ?
Tanga akarorero k’iciyumviro c’isi , n’ingene twocamirira kure .
Mwiyubare : hari aho hogira uwubigarurira nk’isahu ryiwe biciye kuri filozofiya no ku ruhendo rugaragara bishingiye ku migenzo y’abantu , bishingiye ku bintu vy’intango vyo mw’isi , bidashingiye kuri Kristu . ”
“ N’uwutemera Imana araba umuntu mwiza . ”
( Soma Zaburi 10 : 4 . )
“ N’uwutagira idini aragira agahimbare . ”
( Soma Matayo 5 : 3 . )
Yehova arafise uburenganzira bwo kudushingira amategeko kuko ari we yaturemye .
Yezu yavuze ati : “ Nta woshobora gushumbira ba shebuja babiri ; kuko azokwanka umwe akunde uwundi , canke azokwumira kuri umwe asuzugure uwundi .
( Soma 1 Abatesalonika 2 : 13 , 19 , 20 . )
“ Abantu barashoboye gutorera umuti ingorane zabo . ”
Wokwirinda gute ivyiyumviro vyo muri iyi si ?
INDIRIMBO : 122 , 139
Dushobora gute kurondera agashimwe uko tugize umuryango ?
( b ) Ni igiki kidufasha kugumiza amaso kuri ako gashimwe ?
Twokwikingira gute igihe dushikiwe n’ibintu vyotuma turenga ku ngingo ngenderwako za Yehova ?
Kugira ngo twice ivyipfuzo vy’ubusambanyi , turakwiye kwirinda ukwisamaza kurimwo ivy’ubuhumbu .
( Soma Umusiguzi 7 : 21 , 22 . )
10 , 11 . ( a ) Kubera iki ishari ari ribi ?
Ijambo ry’Imana rivuga riti : “ Urukundo ruriyumanganya kandi rugira ubuntu .
Urukundo ntirugira ishari . ”
Twoba twokwigana ubuntu n’urukundo Yonatani yagaragaje ?
Yemwe bagabo , mugume mukunda abagore banyu kandi ntimubagirire ishavu ry’umururazi .
Yemwe bana , mugamburukire abavyeyi banyu muri vyose , kuko ivyo bihimbaye rwose mu Mukama .
Umugabo akwiye gukora iki nimba umugore wiwe badasangiye ukwemera atamwubaha ?
( Raba ingingo ya 13 - 15 )
Ijambo ry’Imana rivuga riti : “ Uwo wese atangira amajambo yiwe aba afise koko ubumenyi , kandi umuntu w’ugutahura agira umutima utekanye . ”
3 “ Ndazi ko azozuka ”
Ibi biganiro biraza gukomeza icizigiro ufise c’izuka .
11 : 11 .
INDIRIMBO : 142 , 129
Ni inkuru izihe zo muri Bibiliya zatumye Marita yizera izuka adakekeranya ?
Nka kumwe kwa Marita , ni igiki witeganye umushasharo ?
Ahubwo yavuze ati : “ Ndazi ko azozuka . ”
Mu nyuma , umwana wiwe yararwaye hanyuma arapfa .
( Soma 1 Abami 17 : 17 - 24 . )
( Soma 2 Abami 4 : 32 - 37 . )
Petero yafashije gute mushiki wacu yari yapfuye ?
Igihe kimwe , intumwa Paulo yari mw’ikoraniro mu cumba co hejuru i Tirowa , ubu akaba ari mu buraruko bushira uburengero bwa Tirkiya .
Umusore yitwa Eyutiko yariko arumviriza yicaye kw’idirisha .
Vyongeye , yari yavuze ko uwo muhezagiro wobonetse “ biciye kuri Izahaki . ”
Ariko ntiwumve , ivyo ntibisobanura ko Imana idashobora kuzura umuntu .
( Soma Yobu 14 : 13 - 15 . )
INDIRIMBO : 151 , 147
( b ) Kubera iki izuka rihambaye cane ?
Ariko none , woba woshiramwo yuko icizigiro c’izuka kiri mu nyigisho uha agaciro cane ?
( Soma 1 Abakorinto 15 : 12 - 19 . )
Ariko rero turazi ko Yezu yazutse .
Ni igiki cerekana ko Zaburi ya 118 yerekeza kuri Yezu ?
‘ Abubatsi barataye ’ Mesiya ( Raba ingingo ya 7 )
Yezu yocitse gute “ ibuye nyamukuru rigumya imfuruka ” ?
Ko Yezu bamwanse bakongera bakamwica , ni gute yocitse “ ibuye nyamukuru rigumya imfuruka ” ?
( a ) Ni ibiki muri Zaburi 16 : 10 hari haravuze ?
Ntuzokwemera ko intahemuka yawe ibona icobo . ”
( Soma Ivyakozwe 2 : 29 - 32 . )
( Soma Ivyakozwe 2 : 33 - 36 . )
( Soma Ivyakozwe 13 : 32 - 37 , 42 . )
Hariho ivyerekeye “ ibihe canke ibiringo Data yashize mu bubasha bwiwe bwite . ”
Paulo yanditse ati : “ Kristu yarazuwe mu bapfuye , aba umushuzo w’abasinziriye mu rupfu . ”
Abarobanuwe bizobagendera gute mu gihe ca ya makuba akomeye ?
Kuko nimba twizera yuko Yezu yapfuye akongera akazuka , n’abasinziriye mu rupfu . . . na bo nyene Imana izobazanana na we . . .
Twebwe abazima bazoba bakiriho gushika mu gihe c’ukuhaba kw’Umukama [ ntitu ] zotanga mu buryo na bumwe abasinziriye mu rupfu ; kuko Umukama ubwiwe azomanuka avuye mw’ijuru n’akamo k’ugutegeka , . . . maze abapfiriye muri Kristu bazobanza kuzuka .
Abarobanuwe bazoba bakiriho mu gihe ca ya makuba akomeye “ [ ba ] zojanwa mu bicu . ”
Nk’uko vyavuzwe na Felix fajardo
Ugarutse na ho , ndakuvuna amaguru . ”
Navutse ku wa 29 Mukakaro 1929 , mu karere ko mu ntara ya Bulacan muri Filipine , akaba ari ho nakuriye .
Narakunda gusoma Bibiliya , canecane za Njili zine , ivyo bikaba vyatuma nipfuza gukurikira Yezu . ​ — Yoh .
10 : 27 .
Muri ico gihe , abavyeyi banje baransavye kugaruka i muhira .
Icabona umwe akuze ni we yaje muhira maze aradusigurira ivyo Bibiliya ivuga ku vyerekeye “ imisi ya nyuma . ”
Yaciye adutumira ku nyigisho ya Bibiliya yabera mu kigwati cari hafi yacu .
Muri iryo joro twaramaze umwanya munini tuganira kuri Bibiliya .
Nishuye nti : “ Ego ndabishaka . ”
Naripfuza ‘ gushumbira Databuja Kristu . ’
Twaragiye ku ruzi rwari hafi maze tubatizwa turi babiri , ku wa 15 Ruhuhuma 1946 .
Abo mu muryango wa Cruz baciye bansaba kuja kuba iwabo i Angat .
Yayitanga mu congereza nanje nkayisobanura muri make mu gitagalogi .
Nari mu batumiwe .
Hakiri kare mu gitondo , nafasha mu gikoni .
Maze kurangiza iryo shure , naciye ndungikwa kuba ndakora ubutsimvyi budasanzwe i Bronx mu gisagara ca New York .
Mu ndwi ya mbere y’ubugeni , twagendeye ishengero ryo mw’izinga ryitwa Rapu Rapu .
Ndiko ndasobanura insiguro y’umuvukanyi Albert Schroeder
Twaranaguze ikibanza ca wa mugabo yatubwira ngo “ Twebwe Abashinwa ntitugurisha . ”
Iyo nda yaca ija mu mugende akabuto k’umugore gashikiramwo canke mu gitereko .
Ivyo bituma iyo nda ikoroka .
Akanyuzi karimwo umujumpu muke usanga atari kirumara cane . ”
INDIRIMBO : 141 , 134
kumenya ivyanditswe vyeranda ?
kwumvishwa ukemera ?
kuba inkerebutsi ku bw’ubukiriro ?
( a ) ‘ Kwumvishwa ukemera ’ bisobanura iki ?
( b ) Ni igiki cerekana ko Timoteyo yumvishijwe akemera inkuru nziza yerekeye Yezu ?
Imbere ya vyose , nube umuntu yihangana .
( Soma Abaroma 12 : 1 . )
Turakunda ko atubaza ibibazo .
Mu vy’ukuri , nohagarika umutima hamwe yoza aremera ikintu cose atarinze kubaza ibibazo . ”
Boba bemera ivyo Bibiliya isigura ?
Ni igiki udakwiye kwirengagiza igihe wigisha ?
Uwitwa Stephanie , akaba afise abakobwa batatu , avuga ati : “ Kuva abana banje bakiri bato , naribaza nti : ‘ Noba mbwira abana banje igituma najijutse ko Yehova ariho , ko afise urukundo , kandi ko inzira ziwe zigororotse ?
Abana banje boba babona neza ko nkunda Yehova vy’ukuri ? ’
Sinokwitega ko abana banje bajijuka , jewe ubwanje ntajijutse . ”
Ni igihushane c’ubupfu . ”
Ubukerebutsi mwene ubwo burakenewe kugira umuntu aronke ubukiriro .
( Soma Imigani 24 : 14 . )
Kubera iki bihambaye ko umuvyeyi abandanya kugira utwigoro ?
( Raba ingingo ya 14 - 18 )
( Soma Mariko 12 : 30 . )
Abavyeyi bofasha gute abana babo kuba “ inkerebutsi ku bw’ubukiriro ” ?
Raba ahavuga ngo INYIGISHO ZO MURI BIBILIYA > IMIYABAGA .
INDIRIMBO : 133 , 135
Woshitsa gute ubukiriro bwawe ?
Kubera iki ibatisimu ari intambwe ihambaye ?
Kubera iki bihambaye ko wibuka ico kintu ?
Mugabo haciye imyaka mikeya , igihe inambu y’umubiri iba imaze gukomera , aba akeneye kujijuka rwose ko kwubaha amategeko ya Yehova vyama ari ngirakamaro .
( b ) Mu Bafilipi 4 : ​ 11 - ​ 13 hatwigisha iki ?
Gushitsa ubukiriro bwawe ‘ utinya kandi ujugumira ’ bisobanura iki ?
Yehova yipfuza ko umubera umugenzi .
( Raba ingingo ya 8 - 11 )
Ni ibikoresho ibihe vyagufashije mu kwiyigisha kwawe ?
( Soma Abafilipi 4 : 6 . )
Na wewe vyogufasha !
None ni igiki cogufasha ?
Hari igihe rero nivugira gusa nti : ‘ Umusi umwe nariko ndigisha Bibiliya umuntu , hanyuma . . .
’ Nca nduga kw’ijambo .
Naho iyo nkuru ubwayo itaba yerekeza kuri Bibiliya , kenshi abandi baca bipfuza kumenya ingene nigisha Bibiliya .
Rimwe na rimwe baca bambaza ibibazo .
Uko ndushiriza gukoresha ubwo buryo , ni ko binyorohera .
Kandi mu nyuma , nca numva ndyohewe cane ! ”
Ni twebwe gusa babona .
Uko tuvyifatamwo rero , birashobora gutuma bavyakira uku canke kuriya .
Hamwe twogira isoni canke bikatugora kubabwira ivyerekeye ukwizera kwacu , canke na ho tukajugumira iyo turiko turabayagira , boshobora guca babona ko tutiyumvamwo ivyo twemera .
Boshobora mbere kuvyakira nabi kubera ko tutavugana ubujijutsi .

Ariko igihe tubayagira ivyo twemera ata bwoba kandi tujijutse , tukabigira nko mu kiyago gisanzwe , vyoshoboka ko bazovyakira neza . ”
Yezu yavuze ati : “ Nimba umuntu ashaka kunkurikira , niyiyanke atore igiti co kubabarizwako ciwe hanyuma agume ankurikira . ”
27 Ubudasa hagati y’abakorera Yehova n’abatamukorera
INDIRIMBO : 3 , 47
Yesaya 40 : 26
Matayo 11 : 28 - 30
2 Abakorinto 12 : 9 , 10
Muri Yesaya 40 : 26 hatwigisha iki ?
Soma Yesaya 40 : 26 .
Nta n’umwe arashobora guharura inyenyeri ziriho .
Twemezwa n’iki ko Yehova ashoboye kuduha inkomezi ?
Soma Yesaya 40 : 28 .
Soma Yesaya 40 : 29 .
Yaciye yongerako ati : “ Muzokwumva muruhuriwe .
Mugabo none twiyumva gute iyo dutashe ?
Uwayishikirije yayitanganye impuhwe n’ikibabarwe ku buryo nakoroye amosozi .
Narabonye ko nkwiye kwama nitaba amakoraniro . ”
Intumwa Paulo yashaka kuvuga iki igihe yandika ngo “ iyo ngoyagoya [ ni ] ho ngira ububasha ” ?
Soma Yesaya 40 : 30 .
Yaririmvye ati : “ Kuko ku bwawe nshobora gukinagiza akagwi k’abambuzi ; kandi ku bw’Imana yanje ndashobora kwurira uruhome . ”
Soma Yesaya 40 : 31 .
None twovuga ko Imana yari yamuhevye ?
Soma Abanyefeso 4 : 26 .
Canke tuzokurikiza impanuro ziranga ubukerebutsi zo muri Bibiliya kugira twihutire gutorera umuti izo ngorane ?
Yehova aramukunda .
Woshobora gutangura ico kiyago uti : “ Hari aho noba natwawe n’agashavu , mugabo ivyo wambwiye ejo , vyatumye . . .
Kuko ukuboko kwawe kwandemēra umurango n’ijoro . ”
Yanditse ati : “ Igicumuro canje naratevye ndakikwaturira . . . . Nawe warahariye ikosa ry’ibicumuro vyanje . ”
INDIRIMBO : 18 , 14
kitwungura ?
Iki kiganiro kiza kwishura ibibazo ibihe ?
( 4 ) Hoba hazokwigera haba Icibutso ca nyuma ?
( Soma Yohani 3 : 16 ; 17 : 3 . )
( a ) Muri rya joro Yezu yatanguza Imfungurwa z’Umukama zo ku mugoroba , yasenze asaba iki ?
( b ) Ni igiki cerekena ko Yehova yishuye isengesho rya Yezu ?
( Soma Yohani 17 : 20 , 21 . )
( Soma Ezekiyeli 37 : 15 - 17 . )
Tworemesha gute ubumwe mu basavyi b’Imana ?
( Soma Matayo 18 : 35 . )
Twokwerekana gute ko “ [ t ] wihanganirana mu rukundo ” ?
Ivyo biratandukanye .
Tuzi gute ko hazobaho Icibutso ca nyuma ?
( Soma Zaburi 133 : 1 . )
I Riberalta mu ntara ya Beni , abagabo babiri n’abagore babo , bose bakaba ari abatsimvyi , bariko barapakira ibitabu mu ndege .
INDIRIMBO : 80 , 50
Kubera iki Yehova adusaba kumuha ku bintu vyacu vy’agaciro ?
Ishirahamwe rikoresha gute intererano zitangwa muri iki gihe ?
Iyo dushigikiye igikorwa ca Yehova tuba tumweretse iki ?
( Soma Imigani 29 : 21 . )
Intererano nyinshi zitangwa mw’ibanga .
( Soma 2 Abakorinto 8 : 18 - 21 . )
N’ishirahamwe rya Yehova ni ukwo .
Intererano utanga zirashigikira igikorwa turangurira kw’isi yose ( Raba ingingo ya 14 - 16 )
Ku bw’ivyo , birashika tukabona ko turi twenyene kandi tukibagira ingene igikorwa ca Yehova kingana .
Ariko iyo turavye ibiganiro bitandukanye bica kuri ya televiziyo yacu , duca twibuka ko turi mu muryango w’abavukanyi ukwiye kw’isi yose .
Abavukanyi bacu twikundira bo ng’aha barakunda cane iyo televiziyo .
Twama twumva bavuga ko iyo bahejeje kuraba ibiganiro vya buri kwezi , baca bumva biyegereje abagize Inama Nyobozi .
Ubu kuruta ikindi gihe cose , barishimira kuba bari mw’ishirahamwe rya Yehova . ”
( Soma Imigani 11 : 24 , 25 . )
Iki kiganiro cakuremesheje gute ?
INDIRIMBO : 111 , 109
Ukwo ni ko Yehova yaturemye .
Uwukunda umugore wiwe aba yikunda , kuko ata muntu yigeze kwanka umubiri wiwe bwite ; ahubwo arawugaburira akawubungabungana urukundo . ”
( Soma Abaroma 12 : 3 . )
Twokwirinda gute ubwikunzi ?
Paulo yavuze ko abantu bobaye “ inkunzi z’amahera . ”
Haraciye imyaka mike umutsimvyi wo muri Irlande yiganiye umugabo umwe ivyerekeye Imana .
Bibiliya ivuga iki ku bijanye n’ubutunzi be n’ubworo ?
( Soma Umusiguzi 5 : 12 . )
Yanditse ati : “ Simpave mpaga hanyuma nkakwihakana vy’ukuri , nkavuga ngo : ‘ Yehova ni nde ? ’ ”
Yahora ambwira ngo ‘ Jeho nifitiye umukoresha mwiza igitangaza ! ’
Ubu na jewe ndi umutsimvyi , tukaba twempi dukorera Umukoresha umwe , ni ukuvuga Yehova . ”
Twokwirinda gute gukunda amahera ?
( Raba ingingo ya 13 )
Usobanura nyabuna ko batayikunda namba . ”
Twokwirinda gute gukunda ibinezereza ?
INDIRIMBO : 127 , 101
ingene twibona ?
Vyongeye , turazi ko urukundo ‘ rutiyemera kandi rutivyimvya . ’
Ivyo vyaramfasha kubagamburukira .
Narabona ko banyitwararika , kandi vyatuma nipfuza kubashimisha . ”
Ukwo ni ko vyamye kuva kera .
( Soma Yesaya 11 : 6 , 7 . )
Urashobora gusoma inkuru zimwezimwe nk’izo mu rukurikirane rw’ibiganiro bivuga ngo “ Bibiliya irahindura ubuzima bw’abantu , ” kuri jw.org .
Turakwiye kumenyesha abandi ko turi Ivyabona vya Yehova .
3 Niwigane ukwizera n’ukugamburuka kwa Nowa , Daniyeli na Yobu
28 Akanyamuneza ​ — Kamere dukura ku Mana
INDIRIMBO : 89 , 119
Daniyeli ?
Yobu ?
9 , 10 . ( a ) Twokwigana gute ukwizera n’ukugamburuka kwa Nowa ?
( Soma Malaki 3 : 17 , 18 . )
( b ) Yehova yabona gute Daniyeli ?
( b ) Muri iki gihe abavyeyi bokwigira iki ku bavyeyi ba Daniyeli ?
( Soma Yobu 1 : 9 , 10 . )
19 , 20 . ( a ) Twokwigana gute ukwizera n’ukugamburuka kwa Yobu ?
INDIRIMBO : 126 , 150
1 - 3 . ( a ) Ni igiki codufasha kuguma turi abizigirwa ku Mana muri iyi misi ya nyuma ?
( Soma Daniyeli 6 : 7 - 10 . )
Yobu ntiyari Umwisirayeli .
( Soma Yobu 31 : 24 - 28 . )
( Soma Zaburi 11 : 5 ; 26 : 4 . )
Niwibaze rero uti : ‘ Noba nzi neza Yehova nk’uko Nowa , Daniyeli na Yobu bari bamuzi ? ’
Henoki sekuruza wa Nowa , na we nyene “ yaguma agendana n’Imana y’ukuri . ”
Yezu yavuze ati : “ Aburahamu so yaranezererwa cane icizigiro co kubona umusi wanje . ”
Sinumva ingene nobabwira umunezero dufise . ”
Kuko ari twebwe Imana yabihishuriye biciye ku mpwemu yayo . ”
Yezu yavuze ati : “ Ivyo ndabibabwiye , kugira ngo akanyamuneza kanje kabe muri mwebwe kandi ngo akanyamuneza kanyu kabe akuzuye . ”
Yambaye igitambara abo muri ico gihugu bambara
INDIRIMBO : 17 , 13
Umuntu akomeye mu vy’impwemu ameze gute ?
( 3 ) Kwihatira kugira “ umuzirikanyi wa Kristu ” bidufasha gute kuba abantu bakomeye mu vy’impwemu ?
( Soma 1 Abakorinto 2 : 14 - 16 . )
Paulo aturemesha kuba abantu bakomeye mu vy’impwemu .
Bibiliya ivuga iki ku bijanye n’abantu bakomeye mu vy’impwemu ?
Ni igiki codufasha gukomera mu vy’impwemu ?
Ni ibiki twigira ku karorero ka Yakobo ?
Ni ibiki twigira ku karorero ka Mariya ?
( Soma Luka 1 : 46 - 55 . )
( Soma Yesaya 63 : 9 ; Mariko 6 : 34 . )
Mushiki wacu wo muri Brezile yitwa Rachel avuga ati : “ Narakunda kujana n’imideri y’isi .
Ku bw’ivyo , sinambara ngo nikwize .
Mugabo maze kumenya ukuri naragize akigoro kugira mbe umuntu akomeye mu vy’impwemu .
Naho bitanyoroheye kugira amahinduka , nararushirije kugira agahimbare kandi ubuzima bwanje buragira intumbero . ”
Ku bw’ivyo , twiganye Yezu duca turushiriza kumera nka Yehova .
Bavuze bati : “ Twebwe turi ivyabona vy’ibintu vyose yakoze . ”
Kwiyumvira nka Kristu bidufasha gute ?
INDIRIMBO : 22 , 75
Kugira umuzirikanyi wa Kristu bidufasha gute mu buzima bwacu bwa misi yose ?
Avuga ati : “ Sinigera nkora ikibi , ariko ivyo nakora kwari nko guheza umwuga gusa .
Nasa n’uwukomeye mu vy’impwemu , nkama nja ku makoraniro yose , mu bihe bimwebimwe mu mwaka ngakora ubutsimvyi bwo gufasha .
Ariko hari ico nari mpajije . ”
Avuga ati : “ Ni nk’aho ata na kimwe nari nzi .
Naciye niyumvira nti ‘ Nimba nkwiye kuyobora umukenyezi wanje mu vy’impwemu , ntegerezwa kugira ico nkoze . ’ ”
Avuga ati : “ Nariyigishije Bibiliya , ndayiga nongera ndasubira , maze ndatangura gutahura .
Nahavuye ndabitahura . N’igihambaye kuruta naragiraniye ubugenzi somambike na Yehova . ”
( 3 ) Kuba abantu bakomeye mu vy’impwemu bishobora gute kudufasha mu buzima bwacu bwa misi yose ?
( b ) Igihe twiyigisha twongera tuzirikana tuba dufise intumbero iyihe ?
( b ) Ni akarorero akahe ko muri Bibiliya twokwigana ?
12 , 13 . ( a ) Ni ibiki vyodufasha gushira mu ngiro ibivugwa mu Baroma 15 : 5 ?
Niwibuke intumwa Petero .
( Soma 2 Petero 1 : 5 - 8 . )
Kuba abantu bakomeye mu vy’impwemu bigira ico bikoze gute mu buzima bwacu ?
Iyaba ari Kristu , yokora iki ?
None “ ibikorwa bipfuye ” twokwirinda ni ibihe ?
Ingingo mfata zoba zituma nishingira imigambi yo mu vy’impwemu ?
Imigambi y’ivy’impwemu .
Kubera iki wipfuza gutera imbere mu vy’impwemu ?
Narahimbawe cane . ”
3 Ibatisimu ni igisabwa ku bakirisu
Intumwa Petero yahimirije abakirisu bo mu kinjana ca mbere ati : “ Mwakirane . ”
Vyongeye , ni gute twoba abashitsi beza ?
Dukwiye kwakira gute indero idutoza ?
Inyishu turazisanga muri ibi biganiro .
“ None utebejwe n’iki ?
Haguruka , ubatizwe . ” ​ — IVYAK . 22 : 16 .
INDIRIMBO : 51 , 135
Abakolosayi 1 : 9 , 10
Umusiguzi 12 : 1
Yakobo 4 : 17
Ni igiki abavyeyi bakirisu biyemeza imbere y’uko abana babo babatizwa ?
“ NARAMAZE amezi mbwira papa na mama ko nipfuza kubatizwa , kandi na bo nyene barakunda kumbwira ibijanye no kubatizwa .
Baripfuza kumenya neza yuko ntahura ko iyo ngingo ihambaye .
Ku wa 31 Kigarama 1934 , narateye iyo ntambwe idasanzwe mu buzima bwanje . ”
Soma Matayo 28 : 19 , 20 .
5 , 6 . ( a ) Bibiliya ivuga ko Timoteyo yabaye umwigishwa angana gute ?
( Soma Abakolosayi 1 : 9 , 10 . )
( Soma Yakobo 4 : 17 . )
Hari ikintu coza gihambaye kuruta ico ?
Yabwiye Yehova ko yari ahimbawe cane n’ingingo agakobwa kiwe kafashe yo kumwiyegurira . ”
INDIRIMBO : 52 , 41
1 Petero 3 : 20 , 21
Matayo 28 : 19 , 20
Ivyakozwe 22 : 16
( Soma 1 Petero 3 : 20 , 21 . )
Soma Ivyakozwe 8 : 35 , 36 .
Kubera iki tudakwiye guhata umuntu ngo abatizwe ?
Nimba uri umuvyeyi , ushobora kuba umaze kwibaza uti : ‘ Umwana wanje yoba vy’ukuri ageze kubatizwa ?
Ica mbere ni iki : “ Wisunze inkuka ya Yezu Kristu , woba warigaye ivyaha vyawe utako uriyegurira Yehova kugira ngo ukore ivyo agomba ? ”
INDIRIMBO : 100 , 87
None kuba abakiranyi vyobafashije gute ?
Twogaragaza gute ubwakiranyi igihe turi ku makoraniro ?
( Soma 3 Yohani 5 - 8 . )
Avuga ati : “ Nabanje gutinya kubera ko twari tukiri abageni kandi tukaba twaba mu kazu gato .
Ariko guha indaro abo banyeshure vyaratumye duhimbarwa .
Narirya twari tukiri abageni , twariboneye ingene abubakanye bahimbarwa iyo bakorera Yehova kandi bagakurikirana imigambi y’ivy’impwemu bari kumwe . ”
Kubera iki abimukiye mw’ishengero ryanyu bakeneye kugaragarizwa ubwakiranyi ?
( Soma Luka 10 : 41 , 42 . )
Umusi umwe ku mugoroba , umukenyezi wanje inkumbu zari zimwishe , kandi naragerageje kumufasha ariko biranka .
Rero nk’isaha imwe n’igice z’ijoro , twagiye twumva umuntu adodoye .
Twasanze ari umutohoji wa Bibiliya yari atuzaniye imicungwe itatu .
Yari aje guha ikaze abamisiyonari bashasha .
Twaramuhaye ikaze mu nzu maze tumuha amazi .
Twaciye dutegura icayi be n’ishokola .
Nimba kwakira abashitsi biguhagarika umutima , si wewe wenyene .
Umukurambere umwe wo mu Bwongereza yiyemerera ati : “ Umuntu arashobora guhagarika umutima igihe yitegurira kwakira abashitsi .
Ariko nk’uko vyama bigenda mu gikorwa cose dukorera Yehova , ivyiza n’umunezero bivamwo biraruta kure n’iyo umwitwarariko wose twogira .
Kwicarana vyonyene n’abashitsi tugasangira agakawa n’ikiyago birampimbara . ”
Uwundi mukurambere avuga ati : “ Kwakira abagenzi bo mw’ishengero biramfasha kubamenya neza , na canecane nkamenya ukuntu bize ukuri . ”
Umugore w’umwe mu bigisha yaransubirije umutima mu nda .
Yambwiye ko igihe we n’umugabo wiwe bari mu gikorwa co kugendera amashengero , bahimbarwa igihe bahawe indaro n’umuntu akunda ivy’impwemu naho atoba atunze ibintu vyinshi ariko akaba yihatira gukorera Yehova no kworosha ubuzima nk’uko na bo babigira .
Vyaciye binyibutsa ivyo mawe yahora atubwira tukiri abana ati : ‘ Icibo c’imboga ahari urukundo kiruta vyose . ’ ”
( Soma Imigani 25 : 21 , 22 . )
Iyo twiteze abashitsi turabitegurira neza ( Raba ingingo ya 20 )
Umwanditsi wa zaburi Dawidi yabajije ati : “ Ewe Yehova , ni nde azoba umushitsi mw’ihema ryawe ? ”
Birahambaye kandi kwubahiriza imico kama y’aho tubaye .
Kubera iki bihambaye cane ko ‘ twakirana ’ ?
Ariko akigoro kacu ntikabaye impfagusa .
Abavukanyi babiri bahaye agapapuro k’inkuru nziza umuntu asiga amarangi ari ku kiraro imbere y’inyubakwa yitwa Kaštilac hafi y’igisagara ca Split , yubatswe mu kinjana ca 16
INDIRIMBO : 123 , 86
Wohava umena ikintu . ”
( Soma Tito 2 : 11 - 14 . )
Uwo mukurambere yigana ati : “ Graham yari afise ingorane y’ubwibone .
Yaratora amahinyu abakurambere bari muri komite ncarubanza igihe yacibwa .
Mu nyigisho namugirira twaciye tuza turafata umwanya wo kwihweza ivyanditswe bivuga ivy’ubwibone be n’ingaruka zabwo .
Graham yaciye atangura kwisuzuma neza akoresheje Ijambo ry’Imana asanga ntahuje n’ivyo risaba !
Emwe vyaragize ico bikoze kuri we !
Amaze kubona ko yari yarahumishijwe n ’ ‘ ikigiga ’ c’ubwibone kandi ko ingorane yiwe kari agatima ko gutorana amahinyu , yaciye atangura kugira ivyo aryohoye .
Yaratanguye kwitaba amakoraniro adahorereza , kwiga Ijambo ry’Imana abigiranye umwete , no kwama asenga buri musi .
Yambwiye ati : ‘ Haraciye imyaka myinshi menye ukuri , kandi narakoze n’ubutsimvyi .
( Soma Luka 4 : 22 . )
Intumwa Petero yanditse ati : “ Muragire ubusho bw’Imana mujejwe , mutagoberewe , ahubwo mubikunze ; mutabitumwe n’ugukunda inyungu mbi , ahubwo mubishashaye ; atari nko mu gukandamiza abari intoranwa y’Imana , ahubwo mu kubera uburorero ubusho . ”
( Soma Yesaya 11 : 9 . )
INDIRIMBO : 56 , 89
Abavyeyi borera gute abana babo bisunze indero Yehova atanga ?
( Soma Abaheburayo 12 : 5 - 11 . )
Umwana yiga gute kwicungera ?
4 , 5 . ( a ) Kubera iki kwicungera ari umuce uhambaye ugize “ wa muntu mushasha ” ?
( Soma Abafilipi 4 : 13 . )
Dushobora gute kuba abantu biga neza Ijambo ry’Imana ?
Niwumvirize Yehova .
Umuvukanyi umwe yanditse ati : “ Ndakengurukira cane abavyeyi banje ukuntu bandeze .
( b ) Umuryango umwe wungukiye gute ku kuntu abavyeyi bagamburukiye Yehova ?
Haciye imyaka , uwo mukobwa yaragarukanywe .
Turafitaniye ubucuti bwiza igitangaza . ”
( b ) Ni gute twotuma abakurambere barushiriza guhimbarwa n’umurimo barangura ?
Ntibankarira canke ngo banegure , ahubwo barandemesha bakongera bakankomeza .
Igihe cose inyuma y’amakoraniro , naho baba bafatiriwe gute , ntihabura n’umwe ambaza ukuntu merewe .
Kubera ivyanshikiye muri kahise , vyarangora kubona ko Imana yonkunda .
Ariko Yehova yarakoresheje kenshi ishengero n’abakurambere kugira anjijure ko ankunda .
Ico nsaba n’uko ntokwigera ndamuhemukira . ”
Niwahindukira ugakora iciza , ntuzoshirwa hejuru ?
Mugabo nutahindukira ngo ukore iciza , hari igicumuro kibunze ku bwinjiriro , kandi ni wewe gihahamiye ; mbega wewe uzokirusha inguvu ? ”
Nimuze rero ‘ twumvirize indero tube inkerebutsi . ’
3 Ingene tworonka umwidegemvyo nyakuri
Kw’isi , abantu baraharanira cane umwidegemvyo .
None abakirisu bakwiye kubona gute ivy’umwidegemvyo ?
15 Niwigane Yehova , Imana iremesha
8 : 36 .
INDIRIMBO : 54 , 36
Kugira umwidegemvyo uri n’aho ugarukira bisobanura iki ?
Umwidegemvyo nyakuri watakaye gute ?
( Soma 1 Ngoma 29 : 11 , 12 . )
Kugira ngo abantu bironkere ico ‘ ciza , ’ bategerezwa kwizigira Imana kandi bakayigamburukira .
Iyo bayigambarariye , ica ibareka bakihitiramwo iciza . . . n’ikibi . ”
Cokimwe n’uwo mudereva , Adamu na Eva bashimye gukora ibintu uko bishakiye .
Tworonka gute umwidegemvyo nyakuri ?
Yavuze ati : “ Nimwaguma mw’ijambo ryanje , muri abigishwa banje vy’ukuri , kandi muzomenya ukuri , kandi ukuri kuzobagira abidegemvya . ”
Yezu yaciye asigura ati : “ Uwukora igicumuro wese aba ari umushumba w’igicumuro . . . .
Kubera iki umwidegemvyo Yezu yadusezeraniye ushobora kutugira “ abidegemvya koko ” ?
Dushobora gute kuba abidegemvya koko ?
( Soma Abaroma 8 : 1 , 2 , 20 , 21 . )
INDIRIMBO : 49 , 73
( c ) Ni ibibazo ibihe dukeneye kurimbura ?
( Raba ahavuga ngo IBIGANIRO N’INKURU Z’IVYABAYE > KWIHANGANIRA IBIGERAGEZO . )
Vyose biremerwa , mugabo si vyose vyubaka . ”
Nowa n’umuryango wiwe badusigiye akarorero akahe ?
Baba mw’isi yuzuyemwo ububisha n’ubuhumbu .
Yehova adutegeka gukora iki muri iki gihe ?
( Soma Luka 4 : 18 , 19 . )
Naratahuye neza ico amajambo ari muri Yakobo 4 : 8 asobanura , ayagira ati : ‘ Mwiyegereze Imana , na yo izobiyegereza . ’
Nararonse ico narondera , na co akaba ari ubuzima bufise intumbero . ”
Umugabo n’umugore wiwe b’abatsimvyi badasanzwe , bariko bamamaza mu karere kari ukwa konyene , hafi y’igisagara ca Balykchy
ABITAVYE ICIBUTSO ( 2017 )
INDIRIMBO : 7 , 3
Intumwa zaremesheje gute abavukanyi ?
Yehova yaremesheje gute Nowa ?
( b ) Yehova yaremesheje gute Umwana wiwe ?
Injira mu kanyamuneza ka shobuja . ”
Hezekiya yaremesheje gute abakuru ba gisirikare be n’abantu bo muri Yuda ?
Ivyo vyaravunye umutima Yefuta .
Ni gute Petero ‘ yakomeje bene wabo ’ ?
Mugabo natakamvye ku bwawe kugira ngo ukwizera kwawe ntikudegere ; nawe , niwamara kugaruka , ukomeze bene wanyu . ” ​ — Luka 22 : 31 , 32 .
INDIRIMBO : 90 , 87
Ni bande bashobora kuremesha abakirisu bagenzi bacu ?
Ni bande dukwiye kuremesha muri iki gihe , kandi kubera iki ?
Soma Yesaya 32 : 1 , 2 .
Abakurambere botanga gute impanuro mu buryo buremesha ?
Nugire umwete rero , wigaye . ”
Bavyeyi , mwoba muriko muramenyereza abana banyu kuremesha abandi ?
Vyongeye , yaranyiganiye ukuntu na we yigeze gushikirwa n’ivyariko biranshikira , nca numva ko ndi mu bandi . ”
Umwami Salomo yanditse ati : “ Ijambo rije ku gihe caryo , ewe kuntu ari ryiza !
Ukwakaka kw’amaso kunezereza umutima ; agakuru keza kadohesha amagufa . ”
INDIRIMBO : 135 , 144
Tugiye kurimbura iki muri iki kiganiro ?
Turaza kurimbura imvo zitatu .
Kuko watumye nezerwa , ewe Yehova , kubera igikorwa cawe ; kubera ibikorwa vy’amaboko yawe , ndiha akamo k’umunezero . ”
Ntukavuge ngo ndacari muto ntiharagera kwishingira imigambi .
Mu Migani 21 : 5 havuga hati : “ Imigambi y’umunyamwete ntibura kuvamwo akarusho . ”
Niwishingira imigambi myiza hakiri kare , ntuzoteba kuroranirwa .
Iyo nza kwiga ivy’amategeko muri kaminuza , nari gushobora kuronka amahera menshi ariko ntivyari kunyorohera kuronka akazi k’igihe gito . ”
Woba ushobora gukora ubutsimvyi ?
Ivyo ni vyo uwitwa Luca yagize .
17 , 18 . ( a ) Yehova yipfuriza iki abakiri bato muri iki gihe ?
Shetani ni umwansi wacu .
Navukiye mu kagwati kitwa Liberty ko muri Indiana , muri Leta Zunze Ubumwe za Amerika , mvukira mu kazu k’imbaho .
Mu nyuma , mawe yaravyaye abandi bahungu babiri n’uwundi mukobwa w’umuhererezi .
MU MYAKA namaze ndi ku ntebe y’ishure , nta kintu kinini cahinduka .
Ico kigwati ca Liberty cari gikikujwe n’imirima , ahanini bakaba barima ibigori .
Vyarambereye amayobera pe !
Bashaka ko nihebera igisoda .
Ico gihe ho bantumiye mu Nyigisho y’igitabu y’ishengero yabera muhira iwabo , rikaba ryari ikoraniro ritoyi ryo kwiga no kuyaga kuri Bibiliya .
Nababwiye ko ngiye kuvyiyumvira .
Imyaka atari mike imbere y’aho , nari narabajije mawe ivyerekeye Ivyabona vya Yehova maze ambwira ati : “ Ni abantu basenga umutama yitwa Yehova . ”
Mugabo ico gihe hoho , naramenye aho ukuri kuri .
Yezu yari umugabo atagira akanenge .
Haciye umwaka , naratanguye ubutsimvyi mu 1958 .
Sinigeze nicuza kuri iyo ngingo .
Gloria yari ikirezi ico gihe , kandi n’ubu ni ko biri .
Yatubwiye ko ico gihe hari hakenewe abavukanyi batubatse gusa .
Yamara rero , twaragira ibihe vyiza turi kumwe n’abavukanyi kandi twarakunda cane ubusuku .
Muri ico gihe nyene , naratanguye kwigisha Bibiliya umukobwa w’uwo muvukanyi be n’umugabo wiwe .
Uwo mugore be n’umukobwa wiwe barafashe ingingo yo gukorera Yehova maze barabatizwa .
Twari dufise abagenzi bashika muri rya shengero ry’abazungu .
Ico gihe , akagwi karemesha amacakubiri n’ububisha ( Ku Klux Klan ) karabica bigacika .
Mu 1962 , nararonse ubutumire bwo kwitaba Ishure ry’ubusuku bw’Ubwami ryabereye i South Lansing , muri New York .
Yamara rero , nari narakoze ikibazo mw’ishirahamwe rimwe ryo gutumatumanako amakuru ry’i Pine Bluff .
Rimpaye akazi , nari kuba mbaye umwirabure wa mbere arikozemwo .
Yavuze ati : “ Genda kw’ishure wige vyinshi bishoboka , hama uzogaruke utwigishe natwe . ”
Gloria aribuka ibihe twaciyemwo i Pine Bluff . Yigana ati : “ Narakunze cane ico cibare !
Nari mfise inyigisho za Bibiliya ziri hagati ya 15 na 20 .
Mu gitondo rero twakora inzu ku nzu , umwanya usigaye na wo tukayobora inyigisho za Bibiliya , rimwe na rimwe tugashikana isaha zitanu z’ijoro .
Umuvukanyi Leon Weaver , ubu akaba ari umuhuzabikorwa wa Komite y’ishami rya Leta Zunze Ubumwe za Amerika , ico gihe nyene yaragenywe ngo abe umucungezi w’umuzunguruko .
Narahagaritse umutima igihe nagenwa kuba umucungezi w’umuzunguruko .
Ico gihe , umucungezi w’umuzunguruko ntiyamenyerezwa cane .
Umusi umwe , ka kagwi ( Ku Klux Klan ) karagize imyiyerekano mu gisagara twariko turagendera muri Tennessee .
Mu kwezi kwakurikiye , twaratanguye gukorera kuri Beteli .
Gloria yari ikirezi igihe twubakana , kandi n’ubu ni ko biri
Twe na Gloria turakunda ubuzima bwo muri Beteli .
Mu 1999 na ho , narabaye mu bagize Inama Nyobozi .
Muri Yesaya 32 : 17 havuga hati : “ Igikorwa c’ubugororotsi nyakuri kizotegerezwa gucika amahoro ; umurimo w’ubugororotsi nyakuri na wo ucike impore n’umutekano gushika igihe kitagira urugero . ”
Ubwa kabiri , dutegerezwa gusaba impwemu nyeranda y’Imana .
None ni igiki cabimufashijemwo ?
Naciye rero ndamuramutsa muri urwo rurimi .
Yaratangaye , aca ambaza ati : ‘ Ugenzwa n’amaki ? ’
Naramubwiranye urupfasoni ko nipfuza kubonana n’uwuserukira ca gihugu .
Yaramuterefonye , aca araza kundaba maze arandamutsa mu rurimi rwiwe kavukire .
Inyuma y’ivyo , yaranteze yompi igihe nariko ndamusigurira ibijanye n’igikorwa kirangwa amahoro Ivyabona vya Yehova barangura . ”
‘ Nayo izo mw’ivu ryiza , ni bamwe bama ivyamwa bihanganye . ’ ​ — LUKA 8 : 15 .
INDIRIMBO : 68 , 72
Ni ibiki bizodufasha kuguma twama ivyamwa twihanganye ?
( Raba ishusho itangura . ) ( b ) Yezu yavuze iki ku bijanye no kwamamaza mu “ karere iwabo ” ?
Ku muhingamo baca bataha .
“ Ubwizigirwa bwabo burandemesha kwumirako no kugira umutima rugabo mu murimo ndangura . ”
“ Akarorero kabo karankora ku mutima cane . ”
Tugiye kurimbura ibibazo bitatu ibihe , kandi kubera iki ?
Naho ari ukwo , nta kindi gikorwa numva nokora . ”
Soma Yohani 15 : 1 - 5 , 8 .
Ni igikorwa co kwamamaza inkuru nziza y’Ubwami bw’Imana .
Soma Luka 8 : 5 - 8 , 11 - 15 .
Ni gute ‘ twama ivyamwa twihanganye ’ ?
Kuko ndabashingira intahe yuko bafitiye Imana umwete ; mugabo si mu bumenyi butagira amakosa . ”
Twokwigana gute Paulo ?
( Soma Umusiguzi 11 : 6 . )
Igihe twasubirayo , abahita baguma batubaza bati : ‘ Mwahora he ?
Twari tubakumbuye . ’ ”
Mbere baradusaba ibinyamakuru . ”
Kubera iki wiyemeje ‘ kwama ivyamwa wihanganye ’ ?
15 : 8 .
INDIRIMBO : 53 , 60
( Soma Yohani 15 : 1 , 8 . )
Yezu yabwiye intumwa ziwe ati : “ Dawe araninahazwa muri ibi : ko muguma mwama ivyamwa vyinshi . ”
( b ) Ubona gute agateka ufise ko kweza izina ry’Imana ?
Bituma nipfuza kuguma namamaza . ”
( a ) Imvo ituma twamamaza dusanga muri Yohani 15 : 9 , 10 ni iyihe ?
Soma Yohani 15 : 9 , 10 .
Twerekana gute ko twipfuza kuguma mu rukundo rwa Kristu ?
Bibiliya ivuga ko Nowa yari “ umwamamaji . ”
( a ) Imvo yo kwamamaza dusanga muri Matayo 22 : 39 ni iyihe ?
Barakeneye kwumva inkuru nziza . ”
13 , 14 . ( a ) Ni ikintu ikihe kidufasha kivugwa muri Yohani 15 : 11 ?
Umunezero .
( Soma Yohani 15 : 11 . )
( a ) Ni ikintu ikihe kidufasha kivugwa muri Yohani 14 : 27 ?
Amahoro .
( Soma Yohani 14 : 27 . )
( a ) Ni ikintu ikihe kidufasha kivugwa muri Yohani 15 : 15 ?
( b ) Intumwa zari gushobora gute kuguma ari abagenzi ba Yezu ?
Ubugenzi .
( Soma Yohani 15 : 14 - 16 . )
Turashobora kwemera tudakeka ko Yehova yishura amasengesho yacu ( Raba ingingo ya 18 )
INDIRIMBO : 150 , 32
Ni ibiki twize ku bijanye n’umwansi wacu ?
Intumwa Petero avuga ko Shetani ari “ intambwe iroha , ” Yohani na we amwita “ inzoka , ” akongera akamwita “ igisato . ”
( Soma Yakobo 4 : 7 . )
Abemera ico kinyoma usanga babaho bashumbiye “ Ubutunzi ” aho gushumbira Imana .
Turakeneye kumenya umwansi wacu , ariko si ngombwa ngo tumutinye .
Nitwamurwanya azoduhunga .
INDIRIMBO : 79 , 140
Ni ibiki bigize umwambaro w’ibirwanisho vy’impwemu ?
Soma Abanyefeso 6 : 14 .
Vyongeye , abavyeyi be n’abagenzi banje baca banyizigira . ”
Ariko igihe cose urironkera ivyiza biboneka : Urashira umutima mu nda , ukarushiriza kwiyegereza Yehova , kandi ukubahwa n’abagukunda . ”
Gukenyeza ukuri ( Raba ingingo ya 3 - 5 )
Vyarashitse ndamara igihe numva umenga nta co maze , nataye n’umutwe . ”
Bamwe mu bitwa abagenzi banje baratanguye kunywa ibiyayuramutwe , abandi na bo baraheba ishure .
Baciye bagira ubuzima buteye agahinda .
Vy’ukuri , Yehova aradukingira . ”
Agira ati : “ Nca nibuka ko nitirirwa izina rya Yehova be n’uko ibigeragezo ari imyampi Shetani akoresha kugira andase .
Igihe ndamunaniye , nca numva ndyohewe . ”
Ubugororotsi nk’igikingirizo c’igikiriza ( Raba ingingo ya 6 - 8 )
Soma Abanyefeso 6 : 15 .
Ivyo bica bituma menya icobafasha .
Igihe mba niteguye , nca ndababwira ibintu bishobora kubungura . ”
Nditwararika gusoma amayagwa yose yerekeye urwaruka umushumba aba yasohoye .
Gutyo , nca ndaberekeza ku bivugwa muri Bibiliya canke ku rubuga rwa jw.org bishobora kubafasha . ”
Ibirenge vyambaye inkuru nziza ( Raba ingingo ya 9 - 11 )
“ Imyampi . . . yaka umuriro ” imwimwe Shetani akoresha ni iyihe ?
Soma Abanyefeso 6 : 16 .
Ariko ubu , ndategura amakoraniro kandi nkishura kabiri canke gatatu .
Naho bitoroshe , iyo ndabigize ndaryoherwa cane .
Vyongeye , abavukanyi barandemesha rwose .
Nama mva ku makoraniro najijutse ko Yehova ankunda . ”
Inkinzo yagutse y’ukwizera ( Raba ingingo ya 12 - 14 )
Soma Abanyefeso 6 : 17 .
Inkofero y’ubukiriro ( Raba ingingo ya 15 - 18 )
None woryohora gute ubuhanga bwawe ?
Nasanze bavyakira neza igihe babonye ko wiyumvamwo Bibiliya be n’uko ukora uko ushoboye kugira ubafashe . ”
Inkota y’impwemu ( Raba ingingo ya 19 - 20 )
Tubifashijwemwo na Yehova , turashobora kumurwanya dushikamye !
