Okungaphakathi
10 Indlela Ongarhelebha Ngayo Umngani Ogulako
Kubayini athiywa ibizwelo ?
Njani ?
Amanye amabizo atjhentjhiwe .
*
Kubayini batjho njalo ?
Belingawa lidojwe ziinkukhu !
3 : 15 .
1 , 2 .
4 , 5 .
6 , 7 .
12 , 13 .
5 : 1 .
Akusinjalo .
16 , 17 .
18 , 19 .
7 : 9 .
7 , 8 .
14 , 15 .
17 , 18 .
egadangiswe BoFakazi BakaJehova ngesiZulu .
Waba yini umphumela ?
11 : 6 .
( Funda . )
28 : 20 .
8 , 9 .
4 : 16 .
13 , 14 .
Awa .
2 : 12 .
6 : 1 .
133 : 1 .
4 : 7 .
3 , 4 .
2 , 3 .
9 , 10 .
2 : 7 .
Kutjho ukuthini lokho ?
Sikwazi njani lokho ?
Uzokwenza njani lokho ?
Kwamambala !
Cabangela nanzi ezinye iimbonelo .
Kubayini lokhu kuqakathekile ?
Awa , akusinjalo !
6 : 33 .
( b ) Ngimiphi iimbuzo esizoyicabangela ?
Fanekisa .
6 : 10 .
10 , 11 .
Ngayiphi indlela ?
( Qala umtlolo ophasi . )
Ngisiphi isifundo esisifundako ?
4 : 5 .
5 : 8 .
3 : 13 , 14 .
19 , 20 .
Amabizo atjhentjhiwe .
Cabangela nasi isibonelo .
27 : 11 .
15 , 16 .
20 , 21 .
28 : 19 , 20 .
2 : 17 .
Wenzani ?
11 , 12 .
4 : 4 .
4 : 8 , NW .
4 : 11 .
Uzimisele ukwenzani ?
Angekhe !
3 : 12 .
Nikela isibonelo .
48 : 17 .
5 , 6 .
( Funda yoku - 1 KwebeKorinte 15 : 58 . )
Hlathulula .
15 : 58 .
UDorkasi “ gade azinikele ukwenza okulungileko ngeenkhathi zoke nakwabadududu . ”
4 : 13 .
1
2
3
4
5
5 : 12 .
6 : 8 .
( Funda uJoshuwa 24 : 15 . )
Kuthiwani ngawe ?
Funda uMatewu 6 : 33 .
4 : 6 , 7 .
Akhe sibone .
Pheze ngeze .
Sikwazi njani lokho ?
( Funda Iziyema 3 : 5 , 6 . )
23 : 14 .
( b ) Khuyini esizoyicabangela esihlokwenesi ?
13 : 5 .
2 : 3 .
Cabangela okulandelako
UJehova libizo lakaZimu njengombana lembulwe eBhayibhilini .
1 : 5 .
Yenza irhubhululo .
13 : 4 .
( b ) Yini esizoyicabangela esihlokweni esilandelako ?
Kwaba namuphi umphumela ?
UCABANGANI ?
2 : 21 .
Ngizoyenzela umsizi , abe mphelelisi wayo . ” ( Gen .
4 : 18 .
( Funda KumaHebheru 11 : 24 - 27 . )
6 : 19 .
4 : 15 .
3 : 14 .
3 : 18 .
Awa !
2 : 2 .
Kubayini ?
3 : 9 .
2 : 8 .
6 : 12 .
Awa !
Pheze ngeze .
2 : 18 .
“ Ilizwi lakaZimu liphilile linamandla . ” — HEB .
4 : 12 .
Kodwana akupheleli lapho .
Ucabangani wena ?
Ungomunye wabo ?
( 2 Samuweli 6 : 20 - 23 ) Ngisiphi isifundo esisitholako ?
‘ Qala !
Cabangela iimbonelo ezimbalwa .
Awa .
Iye .
2 : 4 .
( Funda KwebeKholose 3 : 13 . )
Uwafunde kuhle amagadangiso weSithalasokulinda wamva nje ?
Nekunjalo , hlola bonyana ungayiphendula na iimbuzo elandelako :
13 : 17 .
12 : 13 .
12 : 1 .
( Funda uMatewu 24 : 37 - 39 . )
Waba yini umphumela ?
32 Iimbuzo Evela Kubafundi
12 : 12 .
3 : 1 .
10 : 31 .
1 : 3 .
( Funda 2 KwebeKorinte 1 : 3 , 4 . )
1 : 20 .
( Funda KuTitosi 2 : 3 - 5 . )
10 : 24 , 25 .
Singakwenza bunjani lokhu ?
5 : 14 , 15 .
( Funda KwebeRoma 7 : 21 - 23 . )
5 : 16 .
6 : 9 .
3 : 13 .
Ngimaphi ?
( Funda u - Isaya 63 : 11 - 14 . )
3 : 5 , 6 .
31 Ezivela Ebulungelweni Lethu
INANI LABANTU
ABARHUWELELI
( Funda iRhalani 1 : 1 - 3 . )
Akhe siqale iimbonelo ezimbalwa .
1 - 3 .
Singafundani esenzakalweneso ?
Ngayiphi ihloso ?
IBhayibhili alitjho .
F .
Awa , akutjho lokho !
30 Iimbuzo Evela Kubafundi
Bengizokwenzani ?
Kubandakanyani lokho ?
Siphila eenkhathini ezithabisako .
Singakwenza njani lokho ?
3 : 17 .
UJesu wathi : “ Akakho noyedwa ongeza kimi , lokha uBaba ongithumileko nangamdoseli kimi . ”
8 : 10 .
( Funda KwebeRoma 7 : 21 - 25 . )
Khengihlathulule .
AMAPHAYONA WESIKHATHI ESIZELEKO
( Funda 2 KaPitrosi 2 : 5 . )
3 : 16 .
▪ Kubayini uZimu avumela ukutlhaga ?
15 : 4 .
( Funda U - Isaya 48 : 17 , 18 . )
( Funda Kwebe - Efesu 4 : 1 - 3 . )
Ebeyigadangiswa boFakazi bakaJehova kodwana kwanjesi ayisagadangiswa .
IIMFUNDO ZEBHAYIBHILI
5 : 9 .
Iinkulumo zakaR .
H .
15 : 28 , NW .
2 : 15 .
6 : 13 .
Kodwana kuphi ?
Kuthiwani ngathi ?
( Funda amaHebheru 13 : 7 , 17 . )
Nikela iimbonelo .
Kwenzekani ?
1 : 24 , NW .
( Funda uHebheru 11 : 17 - 19 . )
Godu , iimbusiso nesivikelo zihlobaniswa nentaba kaZimu .
4 : 16 , 17 .
Ziyini iinzuzo zokwenza njalo ?
6 : 9 , 10 .
32 Bewazi ?
5 - 7 .
103 : 8 .
5 : 11 .
Ningapheli amandla !
UMLANDO WOKUPHILA
13 ImiBuzo Evela KubaFundi
( Funda u - Efesu 5 : 15 , 16 . )
Bobaba , ningabathukuthelisi abantwana benu , khona bangazukudana . ”
Libalelanani ngokutjhaphulukileko .
EZIVELA EBULUNGELWENI LETHU
Khuyini esizoyidemba esihlokwenesi ?
( Qala isithombe esisekuthomeni kwesihloko )
Singakwenza njani lokho ?
( Funda IRhubo 97 : 10 . )
( Qala isigaba 7 )
Inga - kghani wena uyamvumela ?
( Qala isilungelelo . )
CABANGA ngalokhu .
Singaqiniseka njani ?
Kubayini kunjalo ?
ISIHLOKO ESINGAPHANDLE
( Qala iingaba 13 , 14 )
1 : 22 .
Akhe sicabangele iindlela ezintathu zokwenza njalo .
40 : 8 .
( Funda 2 Thimothi 1 : 7 . )
1 : 17 .
41 : 10 .
Cabanga ngeembonelo eembili :
24 : 13 .
Sizokucoca ngani esihlokwenesi ?
( Funda 1 Thesalonika 5 : 1 - 6 . )
( Qala ngaphasi kwesihlokwana esithi , UKWAZI NGATHI > OKUBUZWAKO )
148 : 12 , 13 .
30 Ezivela Ebulungelweni Lethu
( b ) Ngimiphi imibuzo ephakamako ngomtjhado lo ?
2 : 3 , 4 .
16 : 24 .
( Qala isigaba 15 )
( Funda uLuka 21 : 1 - 4 . )
( Qala iingaba 8 - 10 )
( Qala iingaba 15 , 16 )
UJesu bekalinga ukusifundisani ?
( Qala isigaba 16 )
3 : 10 .
6 : 4 .
( Qala isigaba 11 )
( Qala isigaba 12 )
( Funda 1 Korinte 6 : 9 - 11 . )
Sizokucoca ngani esihlokweni esilandelako ?
Ungayidawnloda ku - www.jw.org / nr
( b ) Sizokucoca ngamiphi imibuzo ?
Ngimiphi imibuzo esizokucoca ngayo esihlokwenesi ?
Waqinisekisa iKosi uDavida bona uzomfundisa , ‘ amphose ilihlo ’ ( Funda iRhubo 32 : 8 . )
( Funda IsAmbulo 14 : 6 , 7 . )
( Funda 1 Thesalonika 2 : 13 . )
16 : 1 - 9 ) Thina sifundani kilokhu ?
11 : 9 .
Iye , izakugweba abadududu ngokulunga , kwabasweleko bephasi iqinte ngokulinganako . ’
Kunezinto ezingenza bona kube njalo .
11 - 13 .
UJesu wathi : “ Lapha kunomnothwako khona nehliziywakho ilapho . ”
( Qala isigaba 14 )
“ Bayathaba abantu uZimabo onguJehova ” — RHU .
144 : 15 .
Sizokudemba ini esihlokweni esilandelako ?
17 - 19 .
( Qala iingaba 6 , 7 )
( Funda uJakopo 5 : 14 - 16 . )
Watlola : “ Kodwana mina ngingowenyama , ngathengiselwa ebukhobokeni ngaphasi kwesono .
Phela uJehova unguZimu weqiniso .
“ UZimu ulithando . ”
© 2016 Watch Tower Bible and Tract Society of Pennsylvania
UMAGAZINI LO , isiThala , udumisa uJehova uZimu uMbusi wezulu nephasi .
Ududuza abantu ngeendaba ezimnandi zokuthi umBuso kaZimu osezulwini uzoziqeda zoke izinto ezimbi ezenzeka ephasinapha , bewulitjhugulule libe yipharadesi .
Ukhuthaza abantu bona bakholelwe kuJesu Krestu owasifelako ukuze sifumane ukuphila okungapheliko . Usitjela nokobana sikhuluma nje uyiKosi yomBuso kaZimu .
Umagazini lo wathoma ukugadangiswa ngo - 1879 begodu awuzibandakanyi kwezepolotiki .
Koke okutjhiwo ngumagazini lo kusekelwe eBhayibhelini .
Umagazini lo awuthengiswa .
Ugadangiselwe ukufundisa abantu ngeBhayibheli ephasini loke . Umsebenzi lo usekelwa ngeminikelo yokuzithandela .
Nawufuna ukunikela , sibawa ungene ku - www.jw.org / nr .
Ngaphandle kobana kutjengiswe ngenye indlela , imiTlolo edzujulwe kumagazini lo ithethwe eBhayibhelini eliCwengileko lesiNdebele .
OKUTJHIWO LIBHAYIBHELI
KHUYINI OKHUNYE ESINGAKUFUNDA EBHAYIBHELINI ?
Isihloko esilandelako sizokuhlathulula ngalokhu .
31 Imibuzo Evela Ebafundini
1 : 16 .
IINGOMA : 95 , 13
Ngiliphi igama elingahlathulula umusa kaJehova ngabantu bakhe ?
Singakutjengisa njani ukuthi sesibuswa mumusa esikhundleni sesono ?
Ngiziphi iimbusiso ezibe bufakazi bomusa kaJehova ?
1 , 2 . ( a ) Hlathulula umfanekiso kaJesu okhuluma ngomninisidiribe . ( b ) Indaba le izifanekisa njani izenzo zomusa nokuphana ?
Ninomona ngokuthi ngenze umusa na ? ’ — Mat .
( Funda 2 Korinte 6 : 1 . )
UJehova ubatjengise njani abantu boke umusakhe ?
Sisuke sikhuluma ngani nasithi , umusa “ uhlathululwe ngeendlela ezinengi ? ”
( Qala iinthombe ezisekuthomeni . )
UPitrosi yena wathi : “ Loyo naloyo owamukele isipho somusa , akasisebenzise ukusiza abanye njengenceku elungileko yomusa owandileko wakaZimu . ”
Umpostoli uJwanisi wathi : “ Ngokuzala kwakhe umusa saphiwa soke umusa phezu komusa . ”
Umusa kaJehova usizuzisa njani , begodu singatjengisa njani ukuthi siyawuthokoza ?
( Funda u - 1 Jwanisi 1 : 8 , 9 . )
Ngiziphi izinto ezisithokozisako ngebanga lomusa kaJehova ?
Ihlathululo yomusa kaZimu : Lilungelo lokuzwa iindaba ezimnandi ( Qala isigaba 11 )
Abantu abakhethiweko bazilethe njani ‘ ezinye izimvu ’ ekulungeni ?
( Funda uDanyela 12 : 3 . )
Umthandazo uhlobana njani nomusa kaZimu ?
Umusa kaJehova “ usisiza njani ngesikhathi esifaneleko ” ?
Umusa kaJehova uzizuzisa njani iinhliziyo zethu ?
Kubayini singawuvali umlomo ngomusa kaZimu lo malungana nethemba esinalweli ?
( Funda IRhubo 49 : 7 , 8 . )
AmaKrestu wendulo bewadlala njani ngomusa kaZimu ?
UPitrosi wawayala wathini amaKrestu wendulo ?
Ngebanga lomusa kaZimu , ngiwuphi umsebenzi esiwenzako ?
Ngiwuphi umsebenzi esiwenzako esizokucoca ngawo ngokuzako ?
[ 1 ] ( isigaba 2 ) Qala igama elithi “ Undeserved kindness ” ku “ Glossary of Bible Terms ” eBhayibhelini le - New World Translation elibuyekeziweko .
20 : 24 .
IINGOMA : 101 , 84
Umusa uJehova asenzele wona kufuze usikhuthaze ukuthi senzeni ?
‘ Iindaba ezimnandi zomBuso ’ ziwuveza njani umusa uZimu asenzele wona ?
UJehova uzosenzela njani umusa ephasini elitjha ?
Umpostoli uPowula watjengisa njani ukuthi uyamthokoza uZimu ngomusa amenzele wona ?
UMPOSTOLI uPowula watjho kufanele nakathi : “ Isirhawu sakhe kimi azange sibe lilize . ”
( Funda 1 Korinte 15 : 9 , 10 . )
Ngiwuphi umsebenzi uPowula anikelwa wona ?
( Qala isithombe esisekuthomeni . )
( Funda be - Efesu 3 : 5 - 8 . )
Kubayini sithi ‘ ivangeli lombuso ’ ‘ nevangeli lomusa kaZimu ’ mlayezo owodwa ?
Sizirhatjha njani iindaba ezimnandi zomusa kaZimu nasihlathululela abantu ngesihlengo ?
Kubayini abantu abanesono kufuze babuyisane noZimu ?
Umpostoli uJwanisi watlola wathi : “ Loyo okholwako eNdodaneni unokuphila okungapheliko ; kodwana ongakholwa eNdodaneni ngekhe akubona ukuphila , kodwana uzakuhlala ngaphasi kobukhali bakaZimu . ”
9 , 10 . ( a ) Ngiwuphi umsebenzi uKrestu awunikele abakhethiweko ?
Kubayini kuziindaba ezimnandi ebantwini ukwazi ukuthi bangakghona ukuthandaza kuJehova ?
Abantu abanengi bathandaza ngombana bathi batjho kubenza bazizwe bangcono , kodwana abakukholelwa ukuthi uZimu uyayilalela imithandazwabo .
Okufuze bakwazi kukuthi uJehova ‘ Uzwa imithandazo . ’
Umrhubi uDavida wathi : “ Kuwe ozwa imithandazo . Abantu boke beza kuwe .
13 , 14 . ( a ) Ngibuphi ubuhle obuzokufunyanwa ngabakhethiweko ?
( b ) Ngiwuphi umsebenzi ozokwenziwa ngabakhethiweko ?
UJehova uzozenzela njani umusa ‘ ezinye izimvu ’ ?
Namamiliyoni wabantu abangakhenge bafumane ithuba lokufunda ngoZimu , nabo bazokuvuswa .
Khuyini okufuze sihlale siyikhumbula nasitjhumayelako ?
Siwuphazimulisa njani umusa kaJehova ?
IBhayibheli lithi : “ Indalo leyo ngokwayo izokutjhatjhululwa ekubotjhweni kwayo , ibole bese ilethwa ekululekweni ephazimulako yabantwana bakaZimu . ”
Nasitjhumayela iindaba ezimnandi sisuke siphazimulisa umusa kaJehova !
ISITHOMBE ESISESIGUBUZESWENI :
EBEBAKHONA ESIKHUMBUZWENI ( 2015 )
“ Kodwana funani umbuswakhe , yeke koke lokhu nakho nizakuphiwa khona . ” — LUK 12 : 31 .
IINGOMA : 40 , 98
Uyini umahluko phakathi kwesikutlhogako nesikufunako ?
Kubayini kufuze silawule isifiso sethu nakuziwa endabeni yezinto zakanokutjho ?
Khuyini ekwenza uqiniseke ngokuthi uJehova anganakekela iindingo zakho mihla namalanga ?
Ngiziphi izinto abantu abazigijimisa ngemva ?
USathana uzisebenzisa njani “ iinkanuko zamehlo ” ?
Khumbula isiyeleliso sakampostoli uJwanisi nakathi : “ Iphasi neenkanuko zalo kuyadlula . ”
Khuyini engenzeka nange abantu bakhandlekela ukuba nezinto ezinengi ?
Indaba kaBharurhu isifundisani ?
8 , 9 . ( a ) Kubayini kungakafaneli sitshwenyeke khulu ngezinto esizitlhogako ?
( b ) Khuyini ebeyaziwa nguJesu malungana nabantu neendingo zabo ?
Funda uMatewu 6 : 25 .
UJesu nakafundisa abalandeli bakhe ukuthandaza , wathi khuyini okufanele ibe ngeqakathekileko ekuphileni kwethu ?
Sifundani endleleni uJehova atlhogomela ngayo iinyoni zomkayi ?
Funda uMatewu 6 : 26 .
Kufuze ‘ siqaleni , iinyoni zomkayi . ’
Sibona ngani ukuthi siqakatheke ukudlula iinyoni ?
Ukutshwenyeka ngeendingo zethu khuyini okungeze kwavuka kusilethele yona ?
Funda uMatewu . 6 : 27 .
15 , 16 . ( a ) Sifundani endleleni uJehova atlhogomela ngayo amabhlomu wommango ?
( Qala isithombe esisekuthomeni . ) ( b ) Ngimiphi imibuzo ekungenzeka sizibuze yona , begodu kubayini kunjalo ?
Funda uMatewu 6 : 28 - 30 .
Khuyini engonakalisa isingani sethu noJehova ?
Funda uMatewu 6 : 31 , 32 .
Khuyini uJehova ayaziko ngathi , begodu khuyini angayenza ngalokho ?
Ngiliphi ibanga elisenza singatshwenyeki ngengomuso ?
Funda uMatewu 6 : 34 .
( b ) Ungakwenza njani ukuphila kwakho kube lula ?
Khuyini ezokusiza utjhidele hlanu kwakaJehova ?
IINGOMA : 136 , 129
nokukhohliswa nguDeveli ?
nommoya wephaseli ? ?
nobuthakathaka bethu ?
Itjho isibonelo sokuthi kuqakatheke ngani ukwazi ukuthi sikuphi nesikhathi nje , nokuthi kwenzekani njenganje .
Wahlathulula wathi : “ Qaphelani ! Yelelani !
Kubayini silwela ukulalela isiyeleliso sakaJesu ?
( a ) Kubayni kunengqondo ukukholelwa ukuthi uJesu sekayazi ukuthi i - Arimagedoni izokufika nini ?
( b ) Khuyini esingaqiniseka ngayo ngitjho nanyana singazi ukuthi iinhlupheko ezimbi zizokuthoma nini ?
( Funda uRhabakhukhu 2 : 1 - 3 . )
Itjho isibonelo esitjengisa ukuthi iimphorofido zakaJehova zizaliseka njengombana atjho ?
Esikwaziko kukuthi zoke iimphorofido uJehova azibikezelako zenzeka njengokutjho kwakhe .
Ngokukhamba kwesikhathi uJehova watjela u - Abrahamu wathi : “ Yazi mbala bona iinzukulwana zakho zizakuba ziinkhonzi enarheni engasiyo yazo . Zizakulotjha abantu benarha leyo abazazigandelela iminyaka emakhulu amane . ” ( Gen . 15 : 13 ; IzE .
Kubayini kufuze siqiniseke ukuthi uJehova uzosisindisa ?
7 , 8 . ( a ) Ekadeni bewuyini umsebenzi kanogada , begodu kusifundisani thina lokho ?
( b ) Iza nesibonelo sokuthi kungenzekani nange abonogada bangalala .
Yini abantu abanengi namhlanjesi abangayiyeleliko ?
10 , 11 . ( a ) Yini okufuze siyitlhogomele begodu kubayini ?
( b ) Yini ekwenza uqiniseke bona uDeveli uyifiphazile imikhumbulo yabantu ukuze bangafuni nokuzwa ngesiphorofido seBhayibheli ?
Khumbula ukuthi wena wazi kuhle ukuthi kuqakathekile ukuhlala ulindile .
NoJesu wasiyelelisa wathi : “ Kumele nihlale nilungile ngombana iNdodana yoMuntu izakufika ngesikhathi eningakayilindeli ngaso . ”
Ummoya wephaseli uba nesandla njani ebantwini , thina - ke singawubalekela njani ?
Ngisiphi isiyeleliso esisifumana kuLukasi 21 : 34 , 35 ?
( Funda uLukasi 21 : 34 , 35 . )
Kwenzekani kuPitrosi , uJakopo noJwanisi , begodu lokho kungenzeka njani nakithi ?
Ngokutjho kwakaLukasi 21 : 36 uJesu wathi abafundi bakhe kufuze benzeni ‘ nabazakuhlala balindile ’ ?
( Funda uLukasi 21 : 36 . )
4 : 7 . Singazi njani ukuthi sikulindele lokho okuzokwenzeka esikhathini esingaphelisi ihliziyo ?
Kwathi ngelinye ilanga sisemhlanganweni , omunye umzalwana wangibuza ukuthi angifuni ukutjhumayela na .
Nangineminyaka engaba li - 9 , umma wathoma ukuya ewolweni le - International Bible Students Association , ngokukhamba kwesikhathi babizwa ngokuthi boFakazi bakaJehova .
Okufuze sikwenze thina kukuthi sitjele abantu ngeendaba ezimnandi begodu sikuthabele lokho , bese yokugweba yona asiyitjhiyele uJehova . ”
Omunye umzalwana naye ongumakadabona , wangifundisa ukuthi ukuze ngithabele ukupha , ngezinye iinkhathi kuzokufuze ngibekezele .
Phela umkakhe bekangafuni nokubabona aboFakazi bakaJehova .
Okuthabisa khulu kukuthi abantu bemzini loyo babhajadiswa boke njalo .
Kazi thina besingazi ukuthi umpristi bekalawula kangangani .
Bengithabe kwamanikelela , phela bengithoma ukukhwela isikepe .
Iminyaka emihlanu yoke , besitjhumayela eenhlengeleni ezimaqalanga begodu bekunganaboFakazi lapho .
Kukanengi basipha iimfesi , ama - avokhado namantongomani .
Bekuthabisa ukubona ukuthi abanye basithathela phezulu isabelwesi .
Sathi nasifika lapho , ngafumana isiphalaphala sentombi uMaxine Boyd obekasithunywa sevangeli .
Isibonelo salokho , ePotala Pastillo bekunemindeni emibili eboFakazi begodu inabantwana abanengi mina - ke bengikuthanda ukubabethela iflute .
Bese akulungele ukutjhinga esabelweni sakhe e - Ecuador , wathi kithi , “ Nisangibona ?
Phela bekuza uNathan Knorr obekadosa aboFakazi bakaJehova phambili .
Wangikhalimela kabuhlungu khulu wathi kufuze ngihleleke , wabe wathi nakungimi yena abe akasangithembi .
Sathi mina noMma nasithatha iqiniso ubaba yena wabetha ngenyawo phasi .
Unakwami uMaxine wahlongakala ngomnyaka ka - 2011 .
Ngikulinde ngabovu ukumbona godu nakavuswako .
Iqiniso kukuthi banengi abantu abeza kimi babawe isizo , abanye beza ngeendaba ezithinta bona nje kwaphela , bese kuthi abanye - ke bona beza nemiraro yemindenabo .
9 : 7 .
Kodwana iqiniso kukuthi nanyana kukuphi lapha sikhonza khona uJehova , sinamathuba amanengi wokumdumisa .
Umlando kaLeonard Smith wavela esiThaleni sangomhlaka 15 ku - Apreli 2012 .
IINGOMA : 36 , 11
Sikutjho ngaliphi ukuthi umtjhado sisipho esisiphiwe nguZimu ?
Ungawuhlathulula njani umlando womtjhado kusukela ngesikhathi saka - Adamu kufikela esikhathini sakaJesu ?
Yini engasiza umKrestu azi bona ukulungele na ukutjhada ?
1 , 2 . ( a ) Wathoma njani umtjhado ?
( b ) Yini abatjhadikazi bokuthoma ebekufuze bayiyelele ngomtjhado ?
( Funda uGenesisi 2 : 20 - 24 . )
Yini ihloso eqakathekileko yomtjhado ?
2 : 18 ) Ihloso eqakatheke khulu yomtjhado bekukukuthi abatjhadikazi bazalise iphasi ngenzalwabo .
Kwenzekani ngomtjhado wokuthoma ?
Yini esiyifunda endleleni u - Adamu no - Eva abaphendula uJehova ngayo ?
Ungamhlathulula njani uGenesisi 3 : 15 ?
( Funda uGenesisi 3 : 15 . )
( a ) Kwenzekani ngomtjhado kusukela ekuhlubukeni kwaka - Adamu no - Eva ?
( b ) Yini iBhayibheli elithi amadoda nabafazi kufuze bayenze ?
Uthini umlando womtjhado kusukela esikhathini saka - Adamu kufikela ngoMthwalela ?
UJehova wenzani ngobukhohlakali bangeenkhathi zakaNowa ? Thina kufuze sifundeni kekwenzeka ngesikhatheso ?
( a ) Emasikweni amanengi , ngikuphi ukuhlanganyela amabhayi okusele kwenziwe indlela yokuphila ?
( b ) U - Abrahamu noSara baba sibonelo esihle ngayiphi indlela emtjhadwenabo ?
( Funda 1 Pitrosi 3 : 3 - 6 . )
UmThetho kaMosi bewuwavikela njani ama - Israyeli ?
( Funda uDuteronomi 7 : 3 , 4 . )
12 , 13 . ( a ) Amanye amadoda bekabaphatha njani abomkabo ngemihla kaMalaki ?
( b ) Namhlanjesi kungenzekani nangabe umuntu obhajadisiweko utjhada nomlingani womunye umuntu ?
Ngiyiphi ihloso ebeyifezwa mThetho kaMosi ?
( a ) Ebandleni lobuKrestu ngiyiphi ikambiso yomtjhado ?
UJesu wathini ngokungatjhadi ?
Wangezelela ngokuthi : “ Nangabe abakghoni ukuzibamba , kumele batjhade ngombana kungcono ukutjhada kunokutjhiswa yikanuko . ”
18 , 19 . ( a ) Umtjhado wamaKrestu kufuze uthome njani ?
( b ) Sizokucoca ngani esihlokweni esilandelako ?
IINGOMA : 87 , 3
Ngimiphi imithwalo uZimu ayinikela amadoda nabafazi ?
Kubayini ithando nepatho ehle kuqakatheke kangaka emtjhadweni ?
IBhayibheli lingasiza njani nakuqubuka imiraro emtjhadweni ?
Nanyana umtjhado uthoma ngethabo nje , abatjhadilekwabo bangalindela ukuhlangabezana nani ?
Mihlobo bani yamathando okufuze abe khona phakathi kwamalunga womtjhado ?
Kufuze libe namandla kangangani ithando labatjhadileko ?
UPowula wathi : “ Madoda , thandani abafazi benu njengombana uKrestu athanda ibandla , wadela ukuphila kwakhe ngebanga lalo . ”
( Funda uJwanisi 13 : 34 , 35 ; 15 : 12 , 13 . )
4 , 5 . ( a ) Ngiyiphi indima yendoda njengombana iyihloko yomndeni ?
( b ) Umfazi kufuze azizwe njani ngobuhloko ?
( c ) Omunye umma nobabakwakhe kwatlhogeka benze maphi amatjhuguluko ?
Kodwana umtjhado waletha itjhuguluko elikhulu njengombana besekufuze ngithembele kubabakwami .
Bekungasi lula ngaso soke isikhathi , kodwana sinaye sigcine sesitjhidelene khulu ngokwenza izinto ngendlela kaJehova . ”
Umtjhado wangezelela omunye umuntu , kwaba budisi khulu .
Ithando likubopha njani “ koke ndawonye kuzwane ” lokha nakuqubuka imiraro emtjhadweni ?
7 , 8 . ( a ) IBhayibheli inasiphi isiluleko ngezomseme emtjhadweni ?
( b ) Kubayini abatjhadileko kufuze bacabangelane ?
( Funda 1 Korinte 7 : 3 - 5 . )
Zomseme nazo akukafaneli zenziwe ngokuzikhuja namkha ngokukatelelwa , kodwana kufuze zenziwe ngethando elingokwemvelo .
Kubayini kukumbi kangaka ukukhanukela umuntu ongakatjhadi naye ?
10 , 11 . ( a ) Kwande kangangani ukutlhalana ?
( b ) Ithini iBhayibheli ngokuhlala ngokuhlukana ?
( c ) Khuyini okungasiza otjhadileko angagijimeli isehlukaniso ?
Khuyini okungabangela ilunga lomtjhado licabangele isehlukaniso ?
Ngimaphi amabanga azwakalako wokuhlala ngokuhlukana ?
Ithini iBhayibheli ngamaKrestu atjhade nelunga elingasi yinceku kaJehova ?
( Funda 1 Korinte 7 : 12 - 14 . )
15 , 16 . ( a ) IBhayibheli ibeluleka ngokuthini abafazi abamaKrestu abatjhade namadoda angamlotjhiko uZimu ?
( b ) Kutjho ukuthini ngomKrestu “ nakube ongakholwako uyatlhala ” ?
Umpostoli uPitrosi weluleka abafazi abamaKrestu bona bazithobe emadodeni wabo , “ ukuze kuthi nanyana kukhona amanye angalaleli ilizwi , azuzeke ngaphandle kwekulumo , kodwana ngokuziphatha kwabafazi bawo . ”
Lapho iBhayibheli ithi : “ Nakube ongakholwako uyatlhala , akatlhale .
Khuyini okufuze kuze qangi emaKrestwini atjhadileko ?
Kubayini kukghonakala ngomKrestu ukuba nomtjhado othabisako nophumelelako ?
[ 1 ] ( isigaba 5 ) Amabizo atjhentjhile .
[ 2 ] ( isigaba 13 ) Qala incwadi ethi “ Hlalani Ethandweni LakaZimu , ” isithasiselo , “ Umbono WeBhayibhili Ngokutlhala Nokuhlala Ngokuhlukana , ” kk . 219 - 221 .
AMAPHAYONA
IINGOMA : 45 , 70
Khuyini ongakwenza ukuze uthuthukise itjhebiswano lakho noZimu ?
Ungenza njani bona uthuthukise itjhebiswano lakho noZimu ngaphandle kokudinwa ?
Ngiziphi iinlungiso ezingakwenza uthuthuke emsebenzini wobuKrestu ?
1 , 2 . ( a ) U - Isaya 60 : 22 uzaliseke njani emihleni yokuphela le ?
( b ) Ngikuphi okutlhoga izandla engcenyeni yehlangano kaJehova esephasini ?
“ OPHASI ngesibalo uzakuba yikoro nomncani abe sisizwe esinamandla . ”
Kutjho ukuthini kuwe ukuthuthukisa itjhebiswano lakho noZimu ?
Funda 1 Thimothi 3 : 1 .
Abantu abatjha bangawasebenzisa njani amandlabo ekusebenzeleni umBuso kaZimu ?
( Funda izAga 20 : 29 . )
6 - 8 . ( a ) Elinye isokana layitjhugulula njani indlela ebelizizwa ngayo ngekonzo kaZimu , begodu waba yini umphumela ?
( b ) Singezwa njani ‘ besibone bonyana [ uJehova ] muhle ’ ?
Indlela angibusisa ngayo ingenza ngizizwe ngimkoloda , ngikho ngizimisele ukumsebenzela kangaka ngombana imiphumela yalokho ziimbusiso ezinengi . ”
( Funda iRhubo 34 : 9 - 11 ; [ 34 : 8 - 10 , NW ] . )
Kuqakatheke ngani ukuzimisela ‘ ukulinda ’ ?
Ngiziphi izinto esingasebenzela ukuthuthuka kizo , begodu ziqakatheke ngani ?
Amalunga webandla kungabonakala ngani ukuthi athembekile ?
Ungasilandela njani isibonelo sakaJosefa nawuphethwe makghwakghwa ?
Ungenzani - ke lokha abanye nabakuphatha madlakadlaka ?
14 , 15 . ( a ) Kubayini kufuze ‘ sikhuthalele ’ indlela esitjhumayela ngayo ?
( b ) Ungazivumelanisa njani nobujamo obutjhugulukako ?
( Qala isithombe esisekuthomeni nebhoksi elithi , “ Uzimisele Na Ukulinga Iindlela Ezitjha ? ” )
Ukutjhumayela tjhatjhalazi kungaba namiphi imiphumela ?
17 , 18 . ( a ) Ungawuthola njani umdlandla wokutjhumayela tjhatjhalazi ?
( b ) Umoya kaDavida wokudumisa uJehova ukukhuthaza njani njengombana utjhumayela ?
Wasizwa yini ?
Sibuza nabanye aboFakazi , sizwe yabo imibono . ”
Sikhuluma nje u - Eddie ukuthanda kwamambala ukutjhumayela tjhatjhalazi .
( Funda 1 Thimothi 4 : 15 . )
Bazakhuluma ngephazimulo yombuswakho , bamemezele izenzo zakho zamandla , bazise abantu izenzo zakho zamandla nokuhlonitjhwa kwephazimulo yombuswakho . ” ( Rhu .
Nawuphathiswe umsebenzi omnengi ehlanganweni kaJehova , ungaba njani sibusiso kwabanye ?
Njenganje uVenecia uthi : “ Ukutjhumayela ngomtato kungenye yeendlela ezisebenzako ! ”
Ngabhujelwa ngumkami iminyaka emithathu edlulileko , umnyaka odlulileko indodami ife engozini yekoloyi . ”
Ngemva kweminyaka emibili , sengingudadwenu omKrestu . ”
IINGOMA : 93 , 96
Kubayini kufuze sikhuthaze abantu esifunda nabo bona bakuthande ukufunda iBhayibheli ?
Singabasiza njani abantu abasanda ukuhlanganyela bona bajayele ukukhuluma nabaninimuzi bakghone nokukhuluma nabanye ?
Kubayini kufuze kubandulwe abelusi abazokwelusa umhlambi kaZimu ?
Kubayini kufuze sibandule abanye bona benze umsebenzi kaJehova ?
3 , 4 . ( a ) UPowula wakuhlanganisa njani ukufunda imiTlolo nokuba mumuntu othuthukako ekonzweni ?
( b ) Ngaphambi kobana sikhuthaze abantu esifunda nabo iBhayibheli yini thina ngokwethu okufuze siyenze ?
Itjho ukuthi yini engasiza abantu abatjha ekuhlanganyeleni bona bafunde iBhayibheli qobe .
Ungafese ubuze , ‘ Ngingambandula njani umuntu engifunda naye bona afunde iBhayibheli qobe ? ’
zenyanga nenyanga .
( a ) Ungamsiza njani umuntu ofunda naye iBhayibheli bona ahlawulele ukuthanda ukufunda iBhayibheli ?
( b ) Yini umfundi weBhayibheli angayenza nangabe uyalithanda iBhayibheli ?
UJesu wababandula njani abatjhumayeli beendaba ezimnandi ?
8 , 9 . ( a ) UJesu wakhulumisana njani nabantu abafumana nakatjhumayelako ?
( b ) Thina singabasiza njani abatjhumayeli abatjha bona bakghone ukukhulumisana nabantu esimini njengombana kwenza uJesu ?
10 - 12 . ( a ) UJesu wayithuthukisa njani ikareko yabantu nakatjhumayela iindaba ezimnandi ?
( b ) Thina singabasiza njani abatjhumayeli abatjha bona bathuthuke njengombana babafundisi bamaqiniso weBhayibheli ?
13 , 14 . ( a ) Ucabangani ngeembonelo eziseBhayibhelini ezikhuluma ngalabo abazidela bona benzela abanye okuhle ?
( b ) Ungababandula njani abatjhumayeli abatjha bona batjengise ithando kubazalwana nabodade ?
Kubayini abadala kufuze bafake isandla ekuthuthukiseni amadoda ebandleni ?
16 , 17 . ( a ) UPowula waba njani nekareko etuthukweni kaThimothi ?
( b ) Abadala bangababandula njani abelusi bebandla bengomuso ?
Kubayini kufuze sikuqale njengokuqakathekile ukubandula abanye emsebenzini kaJehova ?
Kubayini kufuze uqiniseke bona imizamwakho yokubandula abanye bona balotjhe uJehova kuhle izokuphumelela ?
Nilahle imiyalo kaZimu nadzimelela emasikweni wabantu . ” — Mar . 7 : 6 - 8 .
IINGOMA : 81 , 32
UJehova waziqinisa njani izandla zanapa abantu abalandelako , uMosi , u - Asa noNerhemiya ?
UJehova uziqinisa njani izandla zethu namhlanjesi ?
Thina - ke singaziqinisa njani izandla zabazalwana nabodadwethu ?
Uyayizwisisa na indlela udade lo azizwa ngayo ?
( b ) Yini engabangela izandla zethu bona zinyefe ?
Ngokwesibonelo isandla kukhulunywa ngaso iinkhathi ezinengi .
Ungasifumanaphi isikhuthazo nokuqiniswa bona ukghodlhelele begodu uthabe ?
( b ) Sizokhe sicoce ngani esihlokwenesi ?
Funda uZefaniya 3 : 16 , 17 .
Kodwana kuthe uMosi nakathoma ukunyefisa izandla zakhe ama - Amalekhi athoma athumba .
( b ) UZimu wawuphendula njani umthandazo kaNerhemiya ?
( Funda uNerhemiya 1 : 10 ; 2 : 17 - 20 ; 6 : 9 . )
Uyakholwa na ukuthi uJehova usebenzisa ‘ amandlakhe amakhulu ’ ‘ nesandla sakhe esiqinileko ’ bona aqinise iinceku zakhe namhlanjesi ?
10 , 11 . ( a ) USathana ulinga njani ukunyefisa izandla zethu ?
( b ) UJehova usebenzisa ini bona asiphe amandla ?
Ukwenza njalo usebenzisa amanga nokuthuselwa ngurhulumende , abarholi bekolo namahlubuka .
13 , 14 . ( a ) Umzalwana owafelwa mkakhe waqiniswa njani ?
Kusafana - ke nanamhlanjesi .
Ukuthandaza nokuthi sifunde iBhayibheli kwaba njengetayere lokududa ebelikhiphela ihlokwami ngaphandle kwamanzi .
Okhunye okwangisizako kududuzwa bazalwana nabodade .
Koke lokhu kwangenza ngabona indlela okuqakatheke ngayo ukuba nesingani noJehova . ”
IINGOMA : 60 , 38
Jakopo noRarheli ?
Josefa ?
Powula ?
UZimu usibandula njani ukwenzela ukuthi sikwazi ukulwa namanabethu ?
Abuye asisize nangeencwadi zethu ezisekelwe eBhayibhelini , kube sifundo nemihlangano emincani nemikhulu .
Singakubalekela njani ukwehlulwa bubumbi ?
( b ) Ngibaphi abantu ekukhulunywa ngabo eBhayibhelini esingabalingisa ?
Khuyini eyasiza uJakopo wakghodlhelela , begodu wabusiswa njani ?
( Funda uGenesisi 32 : 24 - 28 . )
( Qala iingaba 10 , 11 )
AmaKrestu amabili la asizwe njani ekulawuleni iimfiso ezimbi ?
Nakanabako uthi , “ Isizathu sabantwaba ngiso esangenza ukuthi qobe langa ngilwela ukuhlala ngithembekile .
Ngimthokoza kanganani uJehova ngokusebenzisa ihlanganwakhe kube ngiyo esisiza sivikeleke ilanga nelanga ephasini elonakelekweli . ”
Kanengi ngizizwa ngasuthi iinhlokwezi bezitlolelwe mina .
Sekuminyaka ngikikirizisana nemicabango ehloywe nguJehova .
Ngasikhathi khengifikelwe kulisa koke .
Ngazi kuhle ukuthi uJehova unomusa begodu uyalibalela , kodwana ihliziywami yona ayisinyenyi isifisweso , lokho - ke ngikho okungenza ngibone ngathi angilitholi isizo lakhe .
Into le ingonele ipilwami yoke . . . .
( a ) UPowula bekazizwa njani ngokudosa okungakokhu ?
Funda kwebeRoma 7 : 21 - 25 .
IINGOMA : 34 , 61
Yini esingayifunda emthethweni uZimu awubekela ama - Israyeli ?
( Funda uDuteronomi 22 : 5 . )
Yini engasiza amaKrestu akhethe kuhle izembatho afuna ukuzimbatha ?
Kunini lapho okufuze sitjheje khulu khona indlela esimbatha ngayo ?
Iqiniso kukuthi izembatho ezihloniphekileko kwenye indawo kungenzeka zingahlonipheki kwenye indawo .
Funda yoku - 1 Korinte 10 : 31 .
Funda beFilipi 2 : 4 .
( Funda yoku - 1 Korinte 10 : 32 , 33 . )
Khuyini okhunye okungenza bona umzalwana akhethe ukuba netjebe namkha angayifuyi ?
UmThetho kaMosi bewuwavumela amadoda bona abe netjebe .
Abantu kufuze baboneni endleleni esimbatha ngayo ?
IINGOMA : 41 , 69
Abakuthatheli ehloko ukuthi abafundi bakholelwa ekutheni zoke izinto zazivelela . ”
Bese omunye udade weFrance wathi : “ Kubarara khulu abanye abotitjhere besikolweni nababona abafundi abakholelwa eBhayibhelini . ”
Ngicabanga ukuthi sengizifunde kanengi khulu . ”
Zangenza ngabona ukuthi ngitjho nanyana abososayensi bangalinga kangangani ukulingisa indalo kaJehova , lokho angeze kwafika kiyo . ”
Kubayini uZimu afuna ukuthi sisebenzise iingqondo zethu ?
( Funda beRoma 12 : 1 , 2 , NW ; 1 Thimothi 2 : 4 . )
Kwatlhogeka bona ngijame kancani ngicabangisise ngesiphorofido sePhasikesi ! ”
Kubayini udade lo azizwa ngendlela le ?
( Funda iRhubo 19 : 7 - 11 . )
Besinokuthula , sibumbene begodu sithandana . ”
Kungakho kuqakathekile ukuthi nawukhuluma nomuntu ngendalo , uthome umbuze imibuzo .
Wathi : “ Indlela okungayo nepilo ngokwayo iyarara , ngitjho nezintweni ezincani . ”
Wathi : “ Ngileyo naleyo indlu yakhiwe mumakhi wayo , kodwana uZimu umumakhi wakho koke okukhona . ”
IINGOMA : 88 , 115
Kuqakatheke ngani ukuthi ubazi kuhle abantwana bakho ?
Abantwana bethu bafumana ukukholwa ngokuthi bakwakhe kancanikancani . ”
Vane angibuze athi , ‘ Lithini iBhayibheli ? ’
‘ Wena ukuyakukholelwa na lokho elikutjhoko ? ’
‘ Kubayini ukukholelwa ? ’
Bekafuna ngiphendule ngamagamami , bekangafuni ngimane ngibuyelele amagama kaMma .
Njengombana ngikhula ngafunda ukunabisa ihlathululo yami . ”
( Funda uLukasi 2 : 46 . )
Baphendula yoke imibuzo ebenginayo , bakwenza lokho basebenzisa iBhayibheli . ”
( Funda uDuteronomi 6 : 5 - 8 ; Lukasi 6 : 45 . )
Nangabe kukukuthi ekadeni izinto bezibulula yeke kubayini iimbandanezi kungezakade nje kodwana ziyiphicabadala ?
Lokho kwangikara khulu , ngacocela umsanyanami ngakho . ”
Ngemva kwalokho wababawa bona bamenzele ikofi .
Uyahlathulula uthi : “ Bakwenza kuhle khulu lokho .
Ngathi nangibabuzako bona kubayini bazimisele kangaka nabangenzela ikofi le , bathi bafuna bona ibe ngendlela engiyithanda ngayo .
Bese ngabahlathululela ukuthi noZimu naye bekazimisele nakahlanganisa amarhasi ebhodulukweni , lokho ukwenzele thina . ”
Nasimadanisa umdumo wesiphaphamtjhini nendlela iinyoni ezivuma ngayo ngiyiphi evuma kamnandi ? Yeke ngubani ohlakaniphe khulu ?
Mumuntu owenze isiphaphamtjhini namkha Mdali weenyoni ? ”
Omunye ubaba wathi , “ Ungalisi ukufunda iindlela ezitja ongafundisa ngazo abantwabakho . ”
Kusukela babancani bengifunda nabo qobe langa imizuzu eli - 15 , ngaphandle kwamalanga esiya ngawo esifundweni .
Eminengi yemibuzo leyo yaphendulwa esifundweni eminye yaphenduleka nasenza ukukhulekela komndeni .
Ngikho kuqakathekile bona ababelethi bangalisi ukufundisa abantwana babo . ”
Abantwana bakho ababone ukuthi uJehova ungowamambala kuwe .
“ Sitjela indodakazethu ekulu ukuthi ‘ Kufuze uthembele kuJehova , usebenze ngamandla ekonzweni begodu ungazikhathazi khulu ngezinto eziseqadi . ’
Nakabona umphumela walokho uyabona ukuthi sisizwe nguJehova .
Lokho kwaqinisa ukukholwa kwakhe kuZimu nokuthemba iBhayibheli . ”
Sokuthoma sitjengisa bona ukukholwa kungakhula bekunzinze njani .
Ilandiswa nguThomas McLain
Akhengikucocele ukuthi safika njani endabeni le .
NGABELETHELWA eWichita , eseKansas , enarheni ye - U.S.A . , ngomhlaka - 10 Disemba 1936 , ngilizibulo ebantwaneni bakwethu abane .
Kwadlula ijoni hlanukwethu , udorhodere loya walirhuwelela wathi , “ Akhese nenzele isidlhadlhesi iplani ! ”
Ijoneli belibona ukuthi indoda le iburhiqwa , lathi kuye , “ Khamba uyekwakho uyokuphumula . ”
Bakhamba bobabili njalo .
UBaba bekaneentolo ezimbili zokukera abantu iinhluthu eWichita , udorhodere loya bekalikhastama lakhe .
Nginababelethi bami , siya emhlanganweni eWichita ngeminyaka yabo - 1940
Indlela ebebatjhiseka ngayo kwabe kwathonywa ibandla .
Ekukhambeni kwesikhathi sajoyinwa ngudade osele aluphele .
Sathunyelwa eWalnut Ridge , ese - Arkansas ukuthi sibe maphayona akhethekileko .
Ngo - 1962 safumana isimemo seGiliyadi seklasi lama - 37 .
Ngemva kokubelethwa kwendodakazethu uKimberly , kwathi sekudlule iinyanga ezili - 17 , salamisa ngoStephany .
Kesinye isikhathi besithatha nekhambo lokuyokulala emangweni , sithatjiswe kucoca sothe nomlilo .
Besihlela nokuthi sihlale nomuntu osekonzweni yesikhathi esizeleko emzinethu .
Amadodakazethu bewakufuna khulu ukuya lapho .
Bathukwa khulu bathoma ukulila , bathi bona bafuna ukufunda .
Ngesizo lehlangano kaZimu , senza koke ebesingakwenza ukubakhulisa bathande uJehova .
Ekhambweni elalandela , uKimberly wahlangana nesokana ebekasebenza nalo uBrian Llewellyn .
Vele bawaphilela amezwi wokuhlala bebahlanganise okungenani iminyanaka ema - 23 .
Khonokho uBrian noKimberly nabo bababawa ukuyokusebenza eBethel yeLondon , kwathi kamva bathunyelwa eBethel yeMalawi .
Ngemva kwelanga esakhamba ngalo nasiya e - Watchtower Educational Center ePatterson , uLinda wasifowunela wasitjela ukuthi uMma akasekho .
Ngokulandelako sayokufundisa iklasi ebeliseZimbabwe saya neZambia .
Ngo - 2006 uBrian noKimberly baba bomakhelwana bethu , bakhulisa abantazinyana babo ababili uMackenzie no - Elizabeth .
UPaul noStephany bona basakhonza enarheni yeMalawi , uPaul ulilunga leKomidi yeGatja .
IINGOMA : 124 , 79
Kungenzeka kufuze sitjhentjhe indlela esithatha ngayo eminye imihlobo yabantu , kubayini kunjalo ?
Thina - ke singayamukela njani eminye imihlobo yabantu ?
Ngapha nobujamo bezulu nabo bebungiqeda amandla .
Ngathi nje nangiqeda ukusuka e - doyelweni laboflayi ngezwa amakhaza engingazange khengiwezwe epilwenami , iinyembezi zavele zazehlela . ”
( Funda u - Eksodusi 23 : 9 . )
AmaKrestu akhuluma isiGirigi anghonghoyila athi kubayini abafelokazi abakhuluma isiGirigi bangaphathwa njengabanye .
Kungakhathaliseki bona siyalemuka namkha awa , indlela esikhuliswe ngayo soke iba nomthelela omkhulu kithi .
( Funda yoku - 1 Pitrosi 1 : 22 . )
Akhubabekezelele abantu abasalinga ukujayela enye inarha .
Kungenzeka ekuthomeni singayizwisisi indlela abenza ngayo izinto nabacabanga ngayo .
( Qala iingaba 16 , 17 )
Namhlanjesi abantu abavela kwezinye iindawo bangalingisa siphi isibonelo nakuziwa endabeni yokuthokoza neyehlonipho ?
Kokuthoma nje , waba nehlonipho nakafika enarheni etjha ngokuthi abawe ukuburuja . ( Rut .
[ 1 ] ( isigaba 1 ) Igama litjhentjhiwe .
IINGOMA : 142 , 92
Inga - kghani nawe uhlangana nalabo abafunda elinye ilimi ?
( Funda uNerhemiya 13 : 23 , 24 . )
( b ) Singawufikelela njani umgomo loyo ?
Kufuze sitjheje ukuthi nasilungiselela ukuya esimini , ukuya esifundweni namkha nasilungiselela ikulumo , esikulungiselelakokho kungenzeka kungasebenzi kithi ngesikhatheso .
Njengombana umkhumbulwami ulwela ukufunda ilimi nje , lokho kwenza ihliziywami ingadzimeleli ekwakheni itjhebiswano noZimu .
Ngikho ngibekela eqadi isikhathi sokuthi ngifunde iBhayibheli nezinye iincwadi ngelimi lami . ”
UMuriel uthi : “ Bekasilingeka khulu nakufuze ayokutjhumayela ngelinye ilimi kukulapho ngesikhathi sisemini yesiFrench bekakuthanda ukutjhumayela ngelimi lakhe . ”
Nakanabako uSerge uthi : “ Sithe nasilemuka ukuthi ukuba sesimini ekhuluma elinye ilimi kukhandela ituthuko yomntwanethu , saqunta ukubuyela esimini yesiFrench . ”
Qiniseka bona iqiniso liyayifikelela ihliziyo yabantwana bakho ( Qala iingaba 14 , 15 )
Kodwana sithi nasilungiselelako nalokha nasidlalako , sisebenzise ilimi lesiLangala khona bazokufunda ilimeli bathabile . ”
Linga ukufunda ilimi elikhulunywa lapho uhlala khona begodu uphendule ngalo esifundweni ( Qala iingaba 16 , 17 )
Sizibekele umgomo wokuthi kanye ngenyanga siye esifundweni sesiFrench , sithi nasisemalangeni wokuphumula siye emihlanganweni emikhulu yelimi lethu . ”
( Funda beRoma 15 : 1 , 2 . )
Singalitjengisa njani ithando lethu ngeliZwi lakaZimu ?
IINGOMA : 81 , 134
( Funda isAmbulo 21 : 3 - 6 . )
13 : 14 .
Umbuzo kukuthi u - Abrahamu nomndenakhe bakghona njani ukuhlala banokukholwa okuqinileko ?
( Rhu . 1 : 1 - 3 ; funda izEnzo 17 : 11 . )
( Funda yoku - 1 Jwanisi 5 : 14 , 15 . )
Ngiziphi iinlingo abanye abaphorofidi ebebaqalana nazo ngebanga lokukholwa kwabo ?
Bese kuthi abanye abanjengo - Eliya “ bandinda emarhalawumbeni neentabeni , emikghotheni nemadongeni wephasi . ”
( Funda amaHebheru 12 : 3 . )
IINGOMA : 54 , 125
UNowa usibekela siphi isibonelo esisisiza sizwisise okutjhiwo kukuba nokukholwa ?
Singakutjengisa njani ukuba nokukholwa ?
Kubayini kuqakatheke kokubili ukuba nokukholwa nethando ?
Ngiziphi iindlela ezimbili umtlolo webeHebheru 11 : 1 ohlathulula ngazo ukukholwa ?
Uyabona - ke bonyana ukukholwa kwasebenza kanye nezenzo zakhe , nokobana ukukholwa kwapheleliswa ngemisebenzi . ”
Ngokwesibonelo , uJwanisi wahlathulula wathi : “ Loyo okholwako eNdodaneni unokuphila okungapheliko ; kodwana ongakholwa eNdodaneni ngekhe akubona ukuphila , kodwana uzakuhlala ngaphasi kobukhali bakaZimu . ”
( Funda uLukasi 10 : 21 . )
Nalimadaniswa nethando , ikholo liqakatheke kangangani ?
UJakopo wabuza abafowabo abazesiweko wathi : “ UZimu akakakhethi abachakileko bephaseli kobana banothe ngokukholwa , babe ziindlalifa zombuso awuthembisa labo abamthandako na ? ”
Kwathi lokha ikoroyi nayikhulako ithoma nokuphalaza nekhula nalo lazipha amandla . ”
IINGOMA : 116 , 102
Nangabe kunjalo , athunjwa nini ?
UJehova wabathembisa ini abantu bakhe , begodu kubayini isithembisweso siqakatheke kangaka ?
Kghani ama - Israyeli bewazakubuyela na endleleni efaneleko yokulotjha uZimu ?
Yeke , kubonakala ngasuthi abantu bakaJehova khenge bathunjwe yiBhabheli eliKhulu ngo - 1918 .
( Funda u - 1 Pitrosi 2 : 9 , 10 . )
( Funda uMatewu 13 : 24 , 25 , 37 - 39 . )
Nakunjalo - ke bewathunjwe yiBhabheli !
Kazi amaKrestu weqiniso azakhe alotjhe uZimu atjhaphulukile ?
Iye !
IINGOMA : 101 , 93
Abazesiweko batjhatjhululwa nini ekuthunjweni yiBhabheli ?
( Funda IsAmbulo 18 : 4 . )
AbaFundi beBhayibheli besikhatheso bebakhuthele !
Umzalwana uRutherford wabawa bona sihlele imihlangano emadorobheni ambalwa wetlhagwini ye - United States , siwathumelele nabazalwana abazobakhuthaza ngendlela abangakghona ngayo . ”
13 : 15 .
IINGOMA : 121 , 45
Wangilalelisisa ngomusa lokha nangimtjela ngamazizwami .
Wangikhumbuza ngezinto ezihle engizenzako .
Wangikhumbuza nangamezwi kaJesu nakathi siqakatheke khulu kuneenyoni ezinengi .
Nanamhlanjesi ngisawukhumbula umtlolo loyo begodu usangithinta ihliziyo .
Khuyini esingakufunda endleleni uJehova , uJesu noPowula abakhuthaza ngayo abanye ?
( Funda uMtjhumayeli 4 : 9 , 10 . )
Khuyini esingayifunda endleleni uJesu aphatha ngayo abapostoli bakhe ?
Umpostoli uPowula .
Sele adabule eemfundenezo bewakhuthaza amakholwa ngamezwi amanengi , wafika eGirisi . ”
( Funda amaHebheru 10 : 24 , 25 . )
( Funda yoku - 1 Thesalonika 5 : 12 , 13 . )
Nanyana abantwabethu bakwazi okulungileko , nasisolo sibakhuthaza bazokwenza okulungileko kunokobana bakwazi kodwana bangakwenzi . ”
( Funda uLukasi 21 : 1 - 4 ; 2 Korinte 8 : 12 . )
( Funda IsAmbulo 2 : 18 , 19 . )
[ 1 ] ( isigaba 1 ) Amanye amagama atjhentjhiwe .
IINGOMA : 105 , 107
( b ) Sizokufunda ngani esihlokwenesi ?
Alo iinqophiso ezivela emkhandlwini zawasiza njani amabandla ?
Funda IzEnzo 16 : 4 , 5 .
( Funda yesi - 3 Jwanisi 9 , 10 . )
( Funda uMatewu 5 : 23 , 24 ; 18 : 15 - 17 . )
IINGOMA : 114 , 113
Bengicabanga ukuthi mina naye sibangani abakhulu . ’
Umsebenzi wokwakha .
Ifundo .
Uyayisebenzisa na i - jw.org nawutjhumayelako nekukhulekeleni kwenu komndeni ?
( Funda yebeRoma 14 : 12 . )
nencwajana ethi , Bobani Abenza Intando kaJehova Namhlanjesi ?
Ngiziphi iinzathu esinazo zokuthokoza uJehova ?
Sineenzathu ezinengi zokobana sithokoze uJehova !
Sisitjengise nokuthi ithembeli lisizuzisa njani thina .
Ilandiswa NguDenton Hopkinson
Kazi mina - ke ngesikhatheso bengineminyaka ebunane kwaphela .
Nakungubaba yena bekangafuni nokuthi umma angitjele ngezinto ebakazifunda eBhayibhelini .
Kodwana bekuthi ubaba nakasaphumile sinomma sifunde , phela benginelulukelo lokwazi ngapha nginemibuzo - kazi eminengi .
Ngebanga lokufunda kwamokho , nami ngaqunta ukunikela ipilwami kuJehova .
Umma wathi akhengiyokukhuluma ne - brethren ( kwanjesi babizwa ngokuthi bajikelezi ) .
Ngemva kweenyanga ezine , ngakhetha omunye umzalwana ukuthi siyokuphayona soke .
Bese umma yena waphayona nomunye udade kelinye ibandla .
Ngomnyaka ka - 1951 ngazalisa iforomo lokuya esiKolweni seBhayibhili seGiliyadi .
Yeke ngabotjhwa iinyanga ezisithandathu .
Bese ngakhamba ngesitimela ngaya eSouth Lansing , eNew York la bekunesikolo khona .
NginoJanet sikwesinye seenhlengele zePhilippines
Bekube nje sisasebenza egatjeni ledorobheni leQuezon
IINGOMA : 60 , 23
Ungakufumana njani ‘ ukuthula okuvela kuZimu ’ ?
Ibandla lingakusiza njani bona wehlise ukutshwenyeka kwakho ?
( Qala isithombe esisekuthomeni . ) ( b ) Khuyini esizokucoca ngakho esihlokwenesi ?
Singakwenza njani lokho ?
UmRhubi uDavida wabawa , wathi : “ Zimu , beka indlebe emthandazwenami . ”
Nasitshwenyekileko , kubayini ukuthandaza kuqakathekile ?
Funda yebeFilipi 4 : 6 , 7 .
Nakuwe lokho kungenzeka .
( Funda uMatewu 11 : 28 - 30 . )
8 - 12 .
‘ Ithando , ithabo , nokuthula . ’
Kubayini kunjalo ?
“ Kubekezela , kulunga , kukwethembeka . ”
Ukukholwa .
“ Bumnene nokuzithiba . ”
UJesu bekanqophe ukuthini nakathi : “ Ningakhathazeki ” ?
BEFILIPI 1 : 10 , 11
UMTJHUMAYELI 7 : 16
UMATEWU 14 : 23
Thanda indalo kaJehova .
IRHUBO 104 : 24 , 25
Hlala uthabile .
IZAGA 17 : 22
Iba nesikhathi sokuzibandula .
1 THIMOTHI 4 : 8
UMTJHUMAYELI 4 : 6
Ungaqalana njani namatshwenyekwakho wangesikhathi esidlulileko ?
( Rhu . 55 : 3 - 6 , [ 55 : 2 - 5 , NW ] ) Nanyana kunjalo , khenge avumele ukutshwenyeka bona kuvimbele ukuthembela kwakhe kuJehova .
“ Obalabala ngehliziyo uyawurubajeka , kodwana ilizwi elakhako liyamthabisa . ”
Kubayini ungaqiniseka ngokuthi ubuhlobo bakho noZimu buzokunikela amandla ?
( a ) Singawaphosela njani amatshwenyekwethu kuZimu ?
IINGOMA : 85 , 134
Kubayini siqiniseka bonyana mbala uJehova uyabavuza abantu bakhe ?
UJehova wazibusisa njani iinkhonzi zakhe zekadeni ?
Ngiziphi iimbusiso esizifunyana kuJehova ?
1 , 2 . ( a ) Ukukholwa kuhlobana njani nethando ?
Ukwazi bonyana uJehova uyasibusisa kusisiza njani ?
( Funda uMatewu 6 : 33 . )
UJesu wathi abafundi bakhe bazokubusiswa ngokuzidela kwabo ( Qala isigaba 5 )
Umpostoli uPitrosi khewabuza uJesu wathi : “ Sitjhiye koke kobana sikulandele . Alo , sizakuzuzani ngalokho na ? ”
ETjumayelweni yeNtabeni uJesu wathi : “ Thabani nithokoze ngombana umvuzo wenu mkhulu ezulwini . Nabaphorofidi ababakhona ngaphambi kwenu babazuma ngayo indlela le . ”
UMosi watjela ama - Israyeli wathi : “ [ uJehova ] uzonibusisa enarheni aniphe yona kobana ibe lilifa lenu , kwaphela nakube nilalela ilizwi [ lakaJehova ] uZimenu , niyelele ukwenza yoke imiyalo enginiyala ngayo namhlanje .
Ngambala uJehova uZimenu uzanibusisa njengombana anithembisa . ”
UJehova wambusisa njani uJosefa ?
Indodana yesibili wayithiya bona ngu - Efrayimu wathi : “ Kungebanga lokobana uZimu ungiphumelelisile enarheni yokurhubutjhwa kwami .
IBhayibheli lithi : “ Okwathi esikhundleni setokozo ebe ibekwe phambi kwakhe , wanyamezelela [ ukubethelwa esigodweni ] angakhathaleli ukurhubutjhwa . ”
Abe akubuzwa bonyana uJesu wakuthabela kwamambala ukuphazimulisa ibizo lakaZimu .
UJehova uzizwa njani ngomsebenzi esimenzela wona ?
“ Onomusa kochakileko , uboleka [ uJehova ] , yeke uzamvuza ngalokho . ” ( IzA .
Begodu ukuthembisa bonyana uzokubusisa .
( Funda yoku - 1 Jwanisi 3 : 19 , 20 . )
Sifunyana ziphi iimbusiso namhlanjesi ?
Iinkhonzi zakaJehova zizizwa njani ngeembusiso ezizifunyanako ?
Ngokwesibonelo , uBianca ohlala eJarimani uthi : “ Angikghoni ukumthokoza ngokwaneleko uJehova ngokungisiza ngeenkinga zami nokungisekela qobe langa .
Qobe nangizidelako ngenze izinto ezimthabisako , ungibusisa ngendlela erarako . ”
Bonyana ngizikhuthaze , nginencwadi engitlola kiyo imitlolo namaphuzu engiwafunyana eencwadini zehlangano .
Ngiyibiza ngokuthi ‘ Yincwadami Yepumelelo . ’
Amatshwenyeko awanamandla nange sithembele kuJehova .
UJehova uhlala akulungele ukusisiza kungakhathaliseki bonyana siqalene namiphi imiraro . ”
Kodwana kungakusiza ukucabanga ngendlela uJehova akusiza ngayo namkha ngendlela asiza ngayo abahlanukwakho .
IINGOMA : 2 , 61
( Funda uJuda 4 . )
UPowula nabanye batjhatjhululwa njani esonweni nekufeni ?
( Funda yebeRoma 6 : 1 , 2 . )
Ngiziphi iinqunto ezikhona esingakhetha ukuzithatha ?
Kubayini kufuze sikhulume iqiniso ?
( Funda IzAga 14 : 5 ; Efesu 4 : 25 . )
( Qala isigaba 19 )
IINGOMA : 57 , 52
( Funda beRoma 4 : 20 - 22 . )
Funda yebeRoma 8 : 4 - 13 .
( Funda IzEnzo 18 : 2 - 4 ; 20 : 20 , 21 , 34 , 35 . )
5 : 5 .
Idorobho le - Aveiro elisetlhagwini yePortugal likweriyelwa khulu , abantwaba bafuna ukuzokubona indlela itswayi elikhitjhwa ngayo emanzini .
© 2017 Watch Tower Bible and Tract Society of Pennsylvania
Akhesicoce nganaku okulandelako :
UmBuso loyo ungurhulumende osezandleni zakaJesu Krestu ozokuqeda yoke imibuso yabantu .
Esihlokwenesi sizokubona ukuthi singasisebenzisa njani isipho sekululeko uZimu asiphe sona ngendlela etjengisa ukuthi siyamthokoza uMuphi waso .
Isihloko sokuthoma sizosifundisa ukuthi nasikhuluma ngokuthobeka vane sikhuluma ngani .
IINGOMA : 133 , 63
kuNowa ?
kuDavida ?
Sazi njani bona uJehova ufuna siwasebenzise amakghonwethu ?
Kusemtarini - ke ukuthi uJehova ufuna sizisize , besisize nabanye .
Amakghono wabantu akhamba afikephi ?
( Funda iRhubo 37 : 3 . )
Ngesikhathi sakaNowa iphasi ‘ beligcwele umguruguru ’ begodu nabantu baziphethe kumbi . ( Gen .
Abantu nabangafuni ukukulalela esimini ( Qala iingaba 6 - 9 )
6 , 7 . ( a ) Ngiziphi izinto uNowa ebengeze akghone ukuzenza ?
( b ) Alo thina - ke sifana ngani noNowa ?
Nathi - ke namhlanjesi siphila ephasini elizele ubumbi . Nokho okusiduduzako kukuthi uJehova usithembise ukuthi uzobuqeda .
Kodwana angeze sakatelela abantu ukuthi balalele ‘ ivangeli lomBuso ’ esilitjhumayelakweli .
Izinto uNowa ebekangazenza : UNowa akhenge avumele izinto ebengeze akghone ukuzenza ukuthi zimqede amandla , kunalokho waqala khulu izinto ebekangazenza .
Singamlingisa njani uNowa ?
Alo uDavida wathini nakabona ukuthi nakuyifihlo yona ivelile ?
Nawucabanga ngezono zakho owazenza kade ( Qala iingaba 11 - 14 )
11 , 12 . ( a ) Njengombana uDavida bekenze isono , yini ebengeze akghone ukuyenza ?
Singafundani kuDavida ?
Nawugulako ( Qala isigaba 15 )
Yini esiyifunda kuHana ?
8 : 1 - 3 ) Okukuphela kwento ebekangayenza , kuliselela koke kuJehova .
Akhesikhulume ngomfoweth ’ uMalcolm , wahlala athembekile bekwaba mnyaka ahlongakala ngawo ngo - 2015 .
Ungazitshwenyi ngezinto ongeze wakwazi ukuzenza , kodwana dzimelela kilezo ongazenza . ”
( b ) Uzosisebenzisa njani isihloko somnyaka ka - 2017 ekuphileni kwakho ?
Umtlolwethu womnyaka ka - 2017 uthi : “ Thembela KuJehova , Wenze Okulungileko ” — Rhu . 37 : 3 , NW
IINGOMA : 62 , 65
Iyini ikululeko ?
Singatjengisa njani ukuthi siyazihlonipha iinqunto abanye abantu abazenzako ?
4 , 5 . ( a ) Ngubani umuntu wokuthoma owafumana isipho sakaZimu sekululeko begodu wasisebenzisa njani ?
( b ) Ngiwuphi umbuzo okufuze umuntu ngamunye azibuze wona ?
Kghani singakghona ?
Ipendulo yombuzo lo ingatjengisa bona sizokuphila isiphelani namkha awa .
Awa , ngekhe satjho njalo .
UZimu “ waziletha emuntwini ukuze abone bonyana uzithiya amabizo athini . ”
Nathi singakhetha ukukhonza uJehova .
Yini okungakafuzi bona siyenze ngesipho sethu sekululeko yokuzikhethela ?
Akhucabange nganapu ubujamo , uphe umnganakho isipho esihle nesikhethekileko .
Ngiyiphi indlela esingenza ngayo bona sibalekele ukusebenzisa kumbi ikululekwethu ?
( Funda yoku - 1 Pitrosi 2 : 16 . )
Isifundisani incwadi yebeGalatiya 6 : 5 ?
Khumbula ikambiso ekwebeGalatiya 6 : 5 .
Uzokutjengisa njani bona wena uyasithabela isipho sakho sekululeko ?
IINGOMA : 38 , 69
Kubayini ukuthobeka kuqakatheke kangaka ?
Ukwazi lapha amandlakho aphelela khona kuhlangana njani nokuthobeka ?
( a ) Abantu abanengi bathini ngokuthobeka ?
Sisuke sikhuluma ngani nasikhuluma ngokuthobeka , begodu khuyini ekungasikho ?
( Funda IzAga 11 : 2 . )
Iza neembonelo eziseBhayibhelini .
Kubayini kungakafuzi sahlulele abanye abantu ?
Nasitjhentjhwa emsebenzini esiwenzako , yini esingayifunda kuJesu ?
( Qala iingaba 12 - 14 )
IINGOMA : 40 , 95
Begodu singathwali amahlombe abanye nabasibukako ?
Into ayenzako le yamzwisa ubuhlungu tle uJehova .
( Funda uMikha 6 : 8 . )
Sizokufunda ngani esihlokwenesi ?
( Funda beGalatiya 6 : 4 , 5 . )
( Funda UMtjhumayeli 11 : 4 - 6 . )
Sizokufunda nokubeka izinto ezisiza abanye abantu phambili .
Yini engasisiza sihlale sithobekile umlibe ?
IINGOMA : 123 , 53
Umsebenzi uqakatheke kangangani ebantwini abanengi ?
Kubayini kwabanye abantu abadala kubudisi ukutjhiyela abantu abatjha iintambo ?
Wabe wathuma noNathani ukuthi afike athi kuDavida : “ Akusuwe ozongakhela indlu kobana ngihlale kiyo . ”
UDavida wenzani nakezwa ihlelo lakaJehova ?
Funda zoku - 1 IinKronike 22 : 5 .
( Funda uNumeri 11 : 24 - 29 . )
mina bengingafisa ngathana boke abantu [ bakaJehova ] bekungaba baphorofidi , nokobana sengasuthi [ uJehova ] bekangathela ummoya ovela kuye phezu kwabo . ”
( Funda beFilipi 2 : 20 - 22 . )
3 Ihloso KaJehova Nakanjani Izokufezeka !
Ilandiswa NguDouglas Guest
Igatja lakhe lathumela abomagazini abama - 800 abakhanjiswako .
Ngafundisa amaklasi eManaus , eBelém , eFortaleza , eRecife neSalvador .
Safikela eLisbon esePortugal ngo - Arhostesi 1964 .
Nanyana ungayaphi uyephi angeze wayifumana ihlangano elalela umyalo kaJesu wokutjhumayela iindaba ezimnandi zomBuso kaZimu njenga le ! ”
Siyatlhuwa ukutjho ukuthi kuthe kusalungiselwa bona isihlokwesi sigadangiswe , umfoweth ’ uDouglas Guest wahlongakala ngomhlaka - 25 Okatoba 2015 .
IINGOMA : 152 , 22
bebasizwa mumoya ocwengileko ?
bebalandela iliZwi lakaZimu ?
Yini eyasiza uMosi bona arhole ama - Israyeli ?
Ummoya kaZimu wabasekela abantu ebebamjamele .
34 : 9 ) ‘ Ummoya [ kaJehova ] wehlela kuGidiyoni . ’
( Khok . 6 : 34 ) Libuye lithi , ‘ ummoya [ kaJehova ] wehlela phezu kwakaDavida . ’
Kubayini uJehova bekafuna ama - Israyeli ahloniphe abarholi ebekabakhethile ?
( Funda amaHebheru 1 : 7 , 14 . )
UMosi wawulalela njani umThetho kaZimu ?
Abantu ebebajamele uJehova bebanqotjhiswa liliZwi lakhe .
ImiThetho ebeyibekelwe ama - Israyeli ibizwa ngokuthi ‘ mthetho kaMosi . ’
11 , 12 . ( a ) UJotjhuwa namanye amakhosi ebekarhola abantu bakaZimu , yini ebekufuze bayenze ?
“ Ikosi nayizwa amezwi wencwadi yomthetho , yatlebhula izambatho zayo . ”
Asinakho nokuncani ukungabaza ukuthi uJehova nguye ebekarhola abantu bakhe .
Kubayini uJehova ajezisa abanye babarholi bakwa - Israyeli ?
Kobunye ubujamo uJehova bekajezisa abarholabo bekabasuse nemsebenzini loyo afake abanye .
( Funda uMatewu 23 : 10 . )
Yini efakazela bona uJesu bekasizwa mmoya ocwengileko ?
Ummoya ocwengileko wamsiza uJesu .
( Qala isigaba 17 )
Kwathi nakaqeda nje ukubhajadiswa “ iingilozi zeza zamsiza . ”
Bese kwathi nakusele ama - awara ambalwa bona ahlongakale “ kweza kuye ingilozi ivela ezulwini yamqinisa . ”
IliZwi lakaZimu lamnqophisa njani uJesu nakakhulumako nalokha nakafundisako ?
UJesu bekalalela iliZwi lakaZimu .
Bangidumisa ngelize , iimfundiso zabo zimithetho nje kwaphela efundiswa babantu . ”
Akakho noyedwa olungileko , ngaphandle koZimu yedwa tere . ”
Ngemva kwalokho asingabazi ukuthi akunamuntu obekangathi uHerode bekakhethwe nguJehova bona arhole abantu bakhe .
Sizokufunda ngani esihlokweni esilandelako ?
Isihloko esilandelako sizoyiphendula yoke nje imibuzo le .
Kungenzeka ukuthi incwadi le , ngile eyatlolwa nguMosi .
IINGOMA : 121 , 43
Bebazokwenzani ?
Kubayini ukukhethokhu bekuqakathile kuJehova nakibo ?
15 : 2 .
5 , 6 . ( a ) Ummoya ocwengileko wasisekela njani isihlopha esibusako ?
( c ) IliZwi lakaZimu lasinqophisa njani isihlopha esibusako ?
Kokuthoma , mumoya ocwengileko ebewusekela isihlopha esibusako .
Kwesithathu , iliZwi lakaZimu lanqophisa isihlopha esibusako .
Kubayini sithi uJesu bekawanqophisa namaKrestu wekadeni ?
( a ) UJesu wayikhetha nini “ inceku ethembekileko nehlakaniphileko ” ?
Eminyakeni emithathu ngemva kokuhlongakala kwakaMzalwana uRussell ngo - 1919 , uJesu wanyula “ inceku ethembekileko nehlakaniphileko ” bona ilawule umsebenzi .
IsiThala sakaJulayi 15 2013 sayihlathulula kuhle indaba ‘ yenceku ethembekileko nehlakaniphileko , ’ sathi siqhema esincani sabazalwana abazesiweko abenza isiHlopha esiBusako .
Isihlopha esibusako ngeminyaka yabo - 1950
Yeke , singawuphendula njani umbuzo othi : “ Ngiyiphi - ke inceku ethembekileko nehlakaniphileko ? ”
Ummoya ocwengileko usisize njani isiHlopha esiBusako ?
( Funda yoku - 1 Korinte 2 : 10 . )
Yini eyenze umsebenzi lo bona uphumelele ?
( Funda uJwanisi 17 : 17 . )
Ngiyiphi indlela esingasikhumbula ngayo isiHlopha esiBusako ?
Funda yebeHebheru 13 : 7 .
Kubayini uzimisele ukulandela uMrholakho , uJesu ?
Ngesikhathi uJesu abuyela ezulwini , khenge abalahle abalandeli bakhe .
Esikhathini esingaphelisi ihliziyo , uzosirholela ekuphileni isiphelani .
Akakho namunye umuntu ongasinikela lokho !
Kusukela ngo - 1955 bekube nje , ukusebenzisanokho kwaba yihlangano esele yaziwa ngokuthi yi - Watch Tower Bible and Tract Society of Pennsylvania .
UJehova usiduduza “ kizo zoke iinhlupheko zethu ”

IINGOMA : 147 , 149
1 , 2 . ( a ) Yini uJehova asambulele yona ?
IBHAYIBHELI linamezwi wokuthoma azwakala abulula kodwana adephileko , amezwi lawo athi : “ Koke kwathoma lokha uZimu nakadala izulu nephasi . ”
( c ) Ngimiphi imibuzo esizokucoca ngayo ?
Yini eyatjharaganisa izinto ?
Begodu kubayini isihlengo sakaJesu kungiso esibangela bona kuzaliseke ihloso kaZimu ?
UJehova Mdali omangalisa tle !
Ngiziphi izipho uJehova azinikela u - Adamu no - Eva ?
( Funda uJakopo 1 : 17 . )
Yini enye ebeyiyingcenye yehloso kaZimu ?
Kuhlekuhle bekathi kibo : ‘ Nitjho ukuthi aninakululeko yokwenza enikuthandako ? ’
Kodwana uJehova uthembekile begodu akazitjhentjhi iinkambisolawulo zakhe .
Yini eyenzeka ebantwaneni baka - Adamu ?
( Funda uDuteronomi 32 : 4 , 5 . )
Funda uJwanisi 3 : 16 .
Kubayini isihlengo sisisipho esiligugu ?
Isihlengo sivula liphi ithuba ?
UJehova wazidela khulu nakazasenzela isihlengo .
8 : 21 .
UJehova uzokuba nini “ ngongaphezu kwakho koke ” ?
IINGOMA : 148 , 109
( Funda iRhubo 40 : 9 - 11 , [ 40 : 8 - 10 , NW ] . )
Thina - ke , kuzokubonakala njani bona siyalithanda ibizo lakaZimu ?
Kuzokubonakala ngendlela esiziphatha ngayo .
( Funda 1 Pitrosi 1 : 15 , 16 . )
Khuyini eyenza uJehova asiqale njengabantu abalungileko ngitjho nanyana sinesono nje ?
Labo abazinikela kuye uyabamukela bona bamlotjhe .
Kuhlekuhle uJesu bekatjho ukuthini nakazakuthi : “ Intando yakho yenziwe ” ?
Isihlengo sibazuzisa njani abantu abahlongakeleko ?
Yini uZimu ayihlosileko ‘ ngesiqubutho esikhulu ’ ?
( a ) Njengombana sikhuluma nje , ngiziphi iimbusiso uJehova asiphe zona ?
( Funda IzEnzo 3 : 19 - 21 . )
Ngebanga lokuthi uZimu uyasithanda , uzosenzelani ?
Yeke “ siyalazi besiyalikholwa ithando uZimu analo kithi .
Iye , uZimu ulithando . ”
Begodu inga - kghani ngasikhathi kungaba kuhle na ukutjhentjha isiqunto ebesele sisithethe ?
Isihlokwesi sizosisiza siphendule imibuzo le yoke nje .
Nanyana kunjalo uJehova wathi amakhosi la bewazinikele kuye ngeenhliziyo zawo zoke .
Alo , inga - kghani uJehova uzakutjho okufanako nangathi , athi sizinikele kuye ngeenhliziyo ezipheleleko ngitjho nanyana sitjhapha kangaka ?
32 Igama EliseBhayibhelini Livele Emjekeni Wakade
Ulandiswa NguWilliam Samuelson
Umalum ’ u - Alfred nobaba
Besihlala eplasini elincani epumalanga yeSouth Dakota .
Iplasi kuphela kwento ebeyiqakathekile kwethu , kodwana belingasiyinto eza phambili ekuphileni kwethu .
Phela abazali bami babhajadiswa ngomnyaka ka - 1934 .
UBaba uClarence waba mthintanisi wesihlopha sabadala , bese umalume u - Alfred wangena esikhundleni sakhe ebandleni lethu elincani leConde , eSouth Dakota .
Kazi mina nodadwethu uDorothy sathi nasineminyaka esithandathu saba batjhumayeli .
Bengiphayona ngomnyaka ka - 1952
Imihlangano emikhulu nemincani nayo besiyithathela phezulu .
IBhayibheli liqinisile nalithi : “ Okhambisana nabahlakaniphileko naye uyahlakanipha , ” begodu ekhaya bengihlangana nabantu abanengi abahlakaniphileko .
NoDorothy naye khenge asariyada , wavele wasijoyina waphayona .
Bekuthi nabavakatjhela amabandla aseduze nekhaya , ngasikhathi bangibize nami ngikhambe nabo esimini .
Ngazo zona iinkhathezo , ngafumana isimemo sokuyokusebenza eBethel .
Benginomzalwana uFranz sisemrhatjhweni we - WBBR
Kiwo woke umndeni weBethel , abantu ebebasebenza emasimini bekubabantu abangaba li - 15 kufikela kwabama - 20 .
Inengi lethu besisesebancani begodu nelwazi nalo singanalo .
Naye - ke bekakhethiwe begodu akunanto ebekayithanda njengesimu .
La - ke ngimi no - Angela kunye no - Etta Huth
Bengino - Angela bekungaphambi kwekulumiswano e - tv ngo - 1975
Bese kwathi nakuphela iminyaka emithathu , sabizwa bona siyokusebenza eBethel .
Kube mnandi khulu ukuba nabafowethu nabodade abozokufunda abavela ephasini loke nje
IINGOMA : 9 , 108
Kubayini uJehova noKrestu kufuze banikelwe idumo ?
Abantu nabo badalwe ‘ ngomfanekiso kaZimu . ’
8 , 9 . ( a ) AboFakazi bakaJehova baziqala njani iinkhulu zakarhulumende ?
( Funda 1 Thimothi 5 : 17 . )
Godu ningabizi noyedwa ephasinapha ngokuthi ‘ Baba ’ ngombana ninoBaba oyedwa osezulwini .
Begodu ningabizwa ngokuthi ‘ Mfundisi ’ ngombana ninomfundisi oyedwa onguKrestu .
IINGOMA : 81 , 70
Kubayini kungakafuzi abanye abantu basithathele iinqunto ?
( a ) Yini engasisiza bona sithathe iinqunto ezivuthiweko ?
Alo umbuzo ukukuthi yini engasisiza sithathe iinqunto ezivuthiweko ?
( Funda uJakopo 1 : 5 - 8 . )
( Funda beGalatiya 4 : 17 . )
( Funda 2 Korinte 1 : 24 . )
Abadala abanethando basiza abanye bona bafunde ukuzenzela iinqunto ( Qala isigaba 11 )
Soke sifuna ukuthatha iinqunto ezivuthiweko .
21 : 9 - 12 ) Abadala nabo kufuze benze irhubhululo ngaphambi kokuthatha iinqunto .
Kghani sizokuletha ukuthula kunye nethabo emndeninami ?
Sizokutjengisa na ukuthi ngimumuntu okghodlhelelako begodu nobacabangelako abanye abantu ? ’
Kubayini uJehova alindele bona sizithathele zethu iinqunto ?
U - Asa , UJehotjhafathi , UHezekhiya , UJosiya
IINGOMA : 52 , 65
Kutjho ukuthini ukulotjha uJehova ngehliziyo epheleleko ?
Ngiyiphi ikosi emakhosini amane la ongathanda ukuyilingisa , begodu kubayini ?
Khuyini esizokucoca ngayo nje ?
( Funda 2 IinKronike 14 : 11 . )
Ihlizywakho izokutjhukumisela bona wenzeni ?
Indodana ka - Asa uJehotjhafathi ‘ yakhamba eendleleni zakayise u - Asa . ’ ( 2 Kron .
( Funda 2 IinKronike 20 : 2 - 4 . )
( Funda u - Isaya 37 : 15 - 20 . )
( Funda 2 AmaKhosi 20 : 1 - 3 . )
( Funda 2 IinKronike 34 : 1 - 3 . )
( Funda 2 IinKronike 34 : 18 , 19 . )
( b ) Esihlokweni esilandelako sizokucoca ngani ?
IINGOMA : 11 , 61
U - Asa noJehotjhafathi
UHezekhiya
UJosiya
Kubayini sizokucoca ngamakhosi amane wakwaJuda ?
( Funda 2 IinKronike 16 : 7 - 9 . )
Thina singafundani emtjhaphweni ka - Asa ?
16 : 9 ) UZimu uyabuzwisisa ubujamo oqalene nabo begodu uyakuthanda .
( Funda 2 iinKronike 32 : 31 . )
Yini okufuze ayenze ngalokho ?
( Funda 2 iinKronike 35 : 20 - 22 . )
IBhayibheli lithi lokho uNeko amtjela khona bekumamezwi kaZimu .
Akhesizindle ngabantu abaseBhayibhelinaba , simthokoze uJehova ngokuthi asitlolele ngabo .
3 Yenza Ngokweemfungo Zakho
Zingakhi iimfungo owazenza kuJehova ?
Uthini - ke ngesifungo sakho sokuzinikela kuJehova namkha somtjhadwakho ?
Ukukholwa , ukuthobeka , nokuthembeka kwethu kuyazizinywa lokha nasibona ngasuthi asikaphathwa ngobulungiswa .
“ Iphasi neenkanuko zalo kuyadlula ; kodwana loyo owenza intando kaZimu unokuphila okungapheliko . ” — 1 JWA . 2 : 17 .
IINGOMA : 134 , 24
UJehova uzokwenzani ngabantu abakhohlakeleko , neenhlangano ezibhebhedlhisa ukukhohlakala ?
IBhayibheli lithi : “ Iphasi neenkanuko zalo kuyadlula . ”
Kusithinta njani ukuthi kube nabantu abakhohlakeleko ephasini ?
Yini uJehova azoyenza ?
( Funda iRhubo 37 : 10 . )
Akunandawo emnyama , ngitjho nobumnyama obunzima tshu , lapha abenza okumbi bangabhaca khona . ” ( Job .
Nasiraga nokufunda irhubweli sifumana nokuthi : “ Abalungileko bazakuzuza inarha , bahlale kiyo nini nanini . ” ( Rhu .
37 : 11 , 29 ) Bobani “ abathobekileko ” begodu bonani “ abalungileko ” ?
Uyini umphumela owenziwa ziinhlangano ezikhuthaza abantu bona bakhohlakale ?
Iinhlangano ezikhuthaza abantu bona bakhohlakale zisithinta njani thina namhlanjesi ?
Amasondo lawo azokubhujiswa aqedwe .
( Funda isAmbulo 6 : 14 . )
Kubayini siqiniseka ukuthi ihlangano etjha yephasini izabe ihlelekile ?
Yini ezokuthatha isikhundla seenhlangano ezikhuthaza abantu bona bakhohlakale ?
Ngemva kwe - Arimagedoni , zizokuba khona na iinhlangano ephasini ?
Yeke “ iphasi elitjha ” lizabe lihlelekile .
Ngiziphi izinto ezingakalungi ezenzeka khulu endaweni yangekhenu , wena nomndenakho kunithinta njani lokho ?
Izenzo ezingakalungi zisithinta njani namhlanjesi ?
Sifundani esahlulelweni sakaJehova seSodoma neGomora ?
Yini uJehova azoyenza ngezenzo ezingakalungi ?
( Funda 2 Pitrosi 2 : 6 - 8 . )
Yini ezothatha indawo yezenzo zokungalungi ?
( Funda iRhubo 46 : 8 , 9 , [ 46 : 9 , 10 , NW ] . )
( Isa . 25 : 8 ) Uzokuqeda ukutlhaga bekube phakade .
Ngiziphi izinto ezizokuqedwa unomphela ngemva kwe - Arimagedoni ?
Fanekisa . ( b ) Singaqiniseka njani bona sihlala siphila ngemva kobana iphasi elidaleli selidlulile ?
Akusibulula ukucabanga ukuthi kuzabe kunjani .
IINGOMA : 112 , 89
Mikha 7 : 7
IzAga 19 : 3
Matewu 18 : 15
“ UMGWEBI wephasi loke uzagweba ngokulungileko . ”
Kungombana uJehova umthombo opheleleko wobulungiswa nokulunga .
Kungavivinyeka njani ukukholwa komKrestu ?
AmaKrestu ayilindele ngaphandle kwebandla lobuKrestu ipatho embi .
Khewucabange ngokwabonwa nguWilli Diehl .
Ngemva kokuthola iziqu , wathunyelwa ebujikelezini eSwitzerland .
Ziimbonelo bani esizokucoca ngazo endabeni le nakwelandelako ?
Endabeni le sizokuthi fahlafahla ngomzukulu ka - Abrahamu , uJosefa nendlela abafowabo abamphatha ngayo .
10 , 11 . ( a ) UJosefa waqalana naziphi izinto ezingakalungi ?
Funda uGenesisi 40 : 14 , 15 .
( Funda uMatewu 5 : 23 , 24 ; 18 : 15 . )
Nasithembekileko kuJehova nakubafowethu sizokuvikeleka ekutheni singayenzi imitjhapho enjalo .
45 : 5 - 8 ) Azange asole uJehova ngomraro ebekaqalene nawo .
Okuqakatheke kunakho koke , azange avumele ukungapheleli nepatho embi evela kwabanye imhlukanise noJehova .
Kubayini kufuze sitjhidelane khulu noJehova nasiqalene nepatho embi ebandleni ?
Kungabonakala ngani ukuthi siyamthemba “ uMgwebi wephasi loke ” ?
Qala umlando wokuphila kaWilli Diehl , esihlokweni esithi , “ UJehova UnguNkulunkulu Wami Engiyothembela Kuye , ” esiThaleni sesiZulu sakaNovemba 1991 .
EBEBAKHONA ESIKHUMBUZWENI NGO - 2016
IINGOMA : 63 , 59
isifungo sokuzinikela kwakho ?
isifungo somtjhadwakho ?
( Qala iinthombe ezisekuthomeni . ) ( b ) Sizokuphendula miphi imibuzo esihlokwenesi ?
Baziimbonelo zokulingiswa nakuziwa endabeni yokulotjha uJehova .
Ukufunga kuZimu kuqakatheke kangangani ?
Sifundani - ke kuJafta noHana ?
2 , 3 . ( a ) Isifungo siyinto bani ?
( b ) Ithini imiTlolo ngokwenza isifungo kuZimu ?
UZimu akathatjiswa ziindlhadlha , ngalokho zalisa isithembiso sakho . ”
( a ) Ukufunga kuZimu kuyinto ezike kangangani ?
( b ) Thina khuyini esiyifundako kuJafta noHana ?
11 : 30 - 34 ) Intwe le beyitjho ukuthini kuye ?
( a ) Bekulula na kuJafta ukufeza isifungo asenza kuZimu ngomntazanakwakhe ?
UJafta wathi : “ Ngirhabe ngakhuluma [ “ kuJehova , NW ” ] , nje - ke angisakwazi ukujika amezwami . ”
( b ) Isifungo sakaHana besitjho ukuthini ngoSamyela ?
Ngimiphi imibuzo ekufuze iphendulwe ?
Isifungo sokuzinikela kuZimu ( Qala isigaba 10 )
Yeke isenzo sakhweso samthabisa khulu uJehova !
Isifungo somtjhado ( Qala sigaba 14 )
Isifungo sesibili naso esingesiqakatheke khulu umuntu angasenza ngesomtjhado .
Lithini iBhayibheli ngokuhlukanisa umtjhado nokuhlala ngokuhlukana ?
( Funda 1 Korinte 7 : 10 , 11 . )
Abanye abatjhadikazi bathi : “ Solo sithome ukufunda ibrotjha le umtjhadwethu uthabisa ngendlela erarako . ”
Ividiyo le ifike ngesikhathi !
Nje sesenza kuhle khulu njengabatjhadikazi . ”
18 , 19 . ( a ) Ababelethi abanengi abamaKrestu khuyini abayenzileko ?
( b ) Bakhulunyelwa njani labo abasekonzweni yesikhathi esizeleko ?
Isifungo sekonzo yesikhathi esizeleko ( Qala isigaba 19 )
Baphila ipilo elula , begodu bazikhethele ukungenzi imisebenzi ebhadelako bangakavunyelwa .
Yeke angekhe kwenzeka ukuthi umuntu angathi yena bekangazi ukuthi ukubhajadiswa kuqakatheke kangangani . Funda incwadi ethi ‘ Hlalani Ethandweni LakaZimu , ’ kk . 219 - 221 .
IINGOMA : 150 , 10
OSabekako ujatjuliswa kulunga kwa b kho na ? Uzuzani ngobumsulwa beendlela zakho ? ”
( b ) U - Israyeli walihlula njani ibutho lakaJabhini ?
( Funda AbaKhokheli 4 : 14 - 16 . )
Umlanjana iKhitjhoni wabakhukhula . ”
Qala isihloko esithi “ Ukukhathazeka Ngemali ” esiThaleni sango Julayi 1 2015 esifumaneka ngesiZulu .
IINGOMA : 110 , 2
UDuteronomi 32 : 4
1 Pitrosi 5 : 5
UMatewu 6 : 14
1 , 2 . ( a ) Ngikuphi ukungabi nobulungiswa okwabonwa nguNabhothi namadodanakhe ?
( b ) Ngibuphi ubuntu esizokucoca ngabo endabeni le ?
UNabhothi bekamhlobobani womuntu , begodu khuyini eyamenza wabhala ukuthengisela iKosi u - Arhabi isimu ?
UNabhothi wathembeka ipilwakhe yoke kuJehova ngesikhathi ama - Israyeli alandela isibonelo esikhohlakeleko seKosi u - Arhabi eyatjhada neNdlovukazi engazisiko u - Izebeli .
Funda 1 amaKhosi 21 : 1 - 3 .
Wakuhlathulula ngehlonipho lokho : “ UZimu angeze avuma bonyana ngikunikele ilifa labobamkhulu . ”
Wagcina azithobile !
Kubayini ukuthobeka kwaba sivikelo emndenini kunye nebanganini bakaNabhothi ?
( Funda uDuteronomi 32 : 3 , 4 . )
( b ) Ukuzithoba kungasivikela ngayiphi indlela ?
Uzokwenzani nange abadala bathatha isiqunto ongavumelani naso ?
Ngiwuphi umlando esizokucoca ngawo , begodu kubayini ?
UPitrosi walungiswa njani , begodu ngimiphi imibuzo ephakamako ?
Funda kwebeGalatiya 2 : 11 - 14 .
Kghani bebazokuvumela ukukhubeka kudlale ngabo ?
UPitrosi wazuza njani ekulibaleleni kwakaJehova ?
Kunalokho , watjhukunyiswa mummoya ocwengileko watlola iincwadi ezimbili ezaba yingcenye yeBhayibheli .
3 Siza ‘ Abantu Abavela Kwezinye Iinarha Balotjhe UJehova Bathabile ’
Sesibili - ke sona sizokudemba yokuthi ababelethi abavela kwezinye iinarha ngiziphi iinkambiso zeBhayibheli ezingabasiza bona bathathe iinqunto ezingazuzisa abantwana babo .
IINGOMA : 84 , 73
Besibabona abantu babaleka , sizwa netjhada leengidi .
Mina nababelethi bami nabantwana bekhethu abali - 10 , sabaleka sisabela amaphilwethu , besiphethe nje iimpahla kwaphela emgodlenethu .
Thina abanye saphadlhalala nenarha . ”
Kwenzeka njani bona uJesu nenengi labafundi bakhe babe babaleki ?
Wathi : “ Nabanizumako kelinye idorobho , balekelani kelinye . ”
Ngesikhatheso bengineminyaka eli - 12 ubudala .
Kazi iinyawo zami zavuvuka kangangobana ngabhalelwa kukhamba , yeke ngatjela bekhaya bona bakhambe bangitjhiye .
Nakungubaba yena , awa akhenge avuma bona ngisale , wangitjatha sakhamba .
Bebahlalela ukuhleba , ukusela , ukugembula , ukweba begodu bebenza izenzo ezisilapheleko . ”
( Funda 1 Jwanisi 3 : 17 , 18 . )
( b ) Kubayini batlhoga isizo lethu ?
Kuqakatheke khulu bona babone ukuthi siyabathanda .
( b ) Ababaleki bangatjengisa njani bona bayalithokozela isizo abanikelwa lona ?
Singabasiza njani abafowethu nabodadwethu abababaleki ?
( Qala iingaba 11 - 13 )
Msinyana nje , bobane njalo babamaphayona .
( a ) Ngiziphi iinlingo ababaleki okufuze bazibekezelele ?
Ngilokhu kwaphela enikutlhogako ! ’ ” — Funda 1 Thimothi 6 : 8 .
Bayakutlhoga ukuzwa ithando lakaJehova nethando labafowabo abamaKrestu .
Inengi lababaleki livela eendaweni lapho kuvinjelwe khona umsebenzi wokutjhumayela .
U - Alganesh uyaraga , uthi : “ Abafowethu basiphatha njengeenhlobo zabo zamambala , basinikela ukudla , izembatho , indawo yokulala kunye nezinto zokukhamba .
Ngubani omunye ongamukela iinkhambi angazaziko ngebanga lokuthi balotjha uZimu munye ?
Akekho omunye ngaphandle kwaboFakazi bakaJehova ! ” — Funda uJwanisi 13 : 35 .
Nakufika ababaleki ebandleni , abadala bebandla kufuze balandele iinqophiso ezisencwadini ethi , Ukuhlelelwa Ukwenza Intando KaJehova esahlukweni 8 , isigaba 30 .
Nakusesenjalo , bona bangaragela phambili ngokufuna imininingwana ngokuthi babuze imibuzo engekhe ibalimaze ababaleki kodwana ngesikhathi esifanako ezobanikela ilwazi abalitlhogako ngobujamo bombaleki , ibandla abuya kilo kunye nobuhlobo bakhe noZimu .
“ Akukho okungithokozisa kangaka ngaphandle kokuzwa bona abantwana bami bakhamba eqinisweni . ” — 3 JWA . 4 .
IINGOMA : 88 , 41
Ababelethi bangaba njani ziimbonelo ezihle ebantwaneni babo ?
Ngiziphi izinto iinhloko zemindeni okufuze zicabange ngazo nakufuze zikhethe ilimi elikhulunywa ebandleni abazokuhlanganyela kilo ?
Abanye abantu bangayisiza njani imindeni evela kwezinye iinarha ?
1 , 2 . ( a ) Abantwana abavela kwezinye iinarha baqalana namiphi imiraro ?
( b ) Ngimiphi imibuzo ezokuphendulwa esihlokwenesi ?
Izinto zathoma ukugaya ngomunye umhlathi nangithoma ukufunda , ngathoma ukuthanda ilimi ebelikhulunywa endaweni ebesifudukele kiyo .
Bese ngemva kweminyaka embalwa ngabe sengilazi kuhle ilimelo .
Phela nesifundweni bengingasalizwisisi ilimi engalimunyako nesiko lababelethi bami bese ngingasalizwisisi . ”
Into eyehlakalela uJoshua le , banengi abantwana abaqalene nayo .
Abanye bangasiza ngani ?
3 , 4 . ( a ) Ababelethi bangaba njani sibonelo ebantwaneni babo ?
( b ) Yini ababelethi okungakafuzi bayilindele ebantwaneni babo ?
Phela nabanibona ‘ nifuna umBuso kaZimu qangi , ’ nabo bazokufunda ukuthembela kuJehova bona abatlhogomele .
Okhunye godu okufuze nikubalekele kukuba majadu khulu kangangobana nize ningasabi nesikhathi nabantwana benu .
Abantwana bakho bangasizeka njani ngokufunda ilimi elikhulunywa nguwe ?
Babelethi nange umntwanenu athoma ukuzizwa njalo ngelimi lenu , nitjho bona angeze kwaba kuhle na nange ningafunda okungasenani linye lamalimi akhulunywa endaweni enifudukele kiyo ?
Ukufunda elinye ilimi akusimdlalo , yeke umntwana ofunde elinye ilimi utlhoga ukubukwa .
Ngitjho nanyana uqalane nomraro - kazi wakosodiye lo , ungakghona ukusiza abantwana bakho bona bathande uJehova .
Sikhuluma nje uShan ungumdala webandla .
Abantwana nabakhuluma amalimi amabili , ababelethi bangaba fundisa njani ?
( a ) Emndenini ngubani okufuze athathe isiqunto sokuthi umndeni kufuze uhlanganyele nebandla elikhuluma liphi ilimi ?
Kungaba yinto ehlukileko - ke abantwana nabangazwisisi ilimi kuhle .
( Funda 1 Korinte 14 : 9 , 11 . )
Alo yini engenziwa babelethi abavela kwezinye iindawo ?
Wasiphendula ngendlela ebesingakayilindeli .
Sathi nasilemuka bona akunalitho abalidobhako emihlanganweni yebandla eragwa ngelimi lethu , sathuthela ebandleni elikhuluma ilimi lendawo leyo .
Besiya qobe esifundweni nesimini .
Besimema abantu bona bazokudla nathi sizithabise .
Koke lokho kubasizile abantwabethu , kwabenza bajayelana nabanakwethu nabodadwethu . Kwabenza bathatha uJehova njengoBababo noMnganabo khenge bamthathe njengoZimabo kwaphela .
Lokho bekuqakatheke ukudlula ukufunda nokuzwisisa ilimi lethu . ”
USamuel unaba uthi : “ Nasizakuhlala sitjhidelene noZimu , mina nomkami bekufuze siye emihlanganweni eragwa ngelimi lethu .
Besihlala simajadu , begodu besihlala sidiniwe .
Kodwana siyamthokoza uJehova ngokubusisa lokho ebesilinga ukukwenza nalokho esikudelileko .
Abantwabethu bobathathu njalo basebenzela uJehova isikhathi esizeleko . ”
UKristina nakakhumbulako uthi : “ Bengilazi lapha nalapha ilimi elikhulunywa babelethi bami , kodwana bengingalizwa nakuragwa ngalo imihlangano .
Nangineminyaka elitjhumi nambili , ngaya emhlanganweni omkhulu ngelimi engilikhuluma esikolweni .
Kwaba kukhani ngilizwa kuhle iqiniso .
Bantu abatjha , nicabanga bona ningaphumelela na nange ningahlanganyela nebandla elisebenzisa ilimi lendawo ?
Nange nicabanga njalo akhenizibuze bona kubayini nicabanga njalo .
UNadia osebenza eBethel uthi : “ Mina nabantwana bakwethu sathi nasithoma ukungena eminyakeni yobutjha , sakhetha ukuthuthela ebandleni elisebenzisa ilimi lalapho . ”
Uyaraga uthi , “ namhlanjesi siyabathokoza ababelethi bethu ngokusebenza kwabo ngamandla bona basifundise ilimi labo nokusihlalisa ebandleni elikhuluma ilimi esalimunyako .
Kusisize khulu ekuphileni kwethu begodu kwasivulela namathuba amanengi wokwazi uJehova . ”
( b ) Yini engasiza ababelethi bona bafundise abantwana babo amaqiniso ?
( Funda izAga 1 : 8 ; 31 : 10 , 27 , 28 . )
Yeke ababelethi abangalazi kuhle ilimi elikhulunywa endaweni abathuthele kiyo , bangatlhoga ukusizwa bona bakghone ukufikelela iinhliziyo zabantwana babo .
Ababelethi nabantwana kukhulu abakufundako nababa nesikhathi namalunga webandla ( Qala iingaba 18 , 19
( b ) Ababelethi yini okufuze baragele phambili bayenza ?
Bengithi nangineenkulumo esikolweni sekonzo , bangisize begodu kunengi khulu engakufunda kibo .
Bekuba mnandi khulu ngitjho nalokha nasiba neenkhathi zokuzigedla . ”
Babelethi bawani uJehova anisize , begodu nani nisebenze ngamandla .
( Funda 2 IinKronike 15 : 7 . )
Ubuhlobo bomntwanakho noJehova abuze phambili ekuphileni kwakho , udele nanyana yini oyithandako ngebanga lalokho .
Ulandiswa nguWalter Markin
Kodwana bengingalizwisisi iqiniso eliseBhayibhelini bekwaba ngo - 1946 .
Akhenginindlalele umlandwami .
Ekhaya bengiza nakuvalwa iinkolo nangamawolideyi . Ngokukhamba kwesikhathi ngafunda ilimi lezandla .
Ngitjhumayela endleleni ngabo - 195
Ngo - 1950 ngathuthela eVancouver .
Wavuma ukulethelwa abomagazini qobe nyanga begodu wathi ngizokubona ubabakwakhe uGary .
Ngemva kwesikhathi ngabuyela eSaskatoon .
Abahlanu ebebafunda nabo eklasini baba boFakazi bakaJehova .
Omunye wabo bekungu - Eunice Colin .
Wakhe wangipha iswidi umntazana lo , wangibawa bona sibe bangani .
Ngino - Eunice ngo - 1960 nango - 1989
Nasele afuna ukubhajadiswa , ababelethi bakhe bathi , “ Akhube nguFakazi kaJehova nawufuna ukubona ukuthi uzokuraga nokuhlala ekhayapha na ! ”
Waraga nokufunda bewabhajadiswa .
Nasitjhadako ngo - 1960 ababelethi bakhe khenge beze emtjhadweni .
Indodanami uNicholas nomkakhe uDeborah , abaseBetheli yeLondon
UFaye noJames , uJerry no - Evelyn , uShannan noSteven
Sikhuluma nje sihlanganyela ebandleni labakhuluma ngezandla eCalgary . Okwanje ngingumdala ebandlenelo .
Nguwe onamezwi wokuphila okungapheliko . ”
IINGOMA : 60 , 135
Singahlala njani sithanda uJehova ?
Singalithuthukisa njani ithando lethu ngeqiniso leBhayibheli ?
Kuqakatheke ngani ukuthanda abafowethu nabodadwethu ?
Yini okungenzeka yabangela ithando lamaKrestu amanengi laphola ?
Abantu abanengi abasamthandi uZimu .
Lo myalo wokuthoma nongomkhulu . ”
Tjengisa ukuthi uyamthanda uJehova ( Qala isigaba 10 )
( Funda iRhubo 119 : 97 - 100 . )
Tjengisa ukuthi uyalithanda iqiniso leBhayibheli ( Qala isigaba 14 )
Ngobusuku bakaJesu bamaswaphela asephasina wathi ebalandelini bakhe : “ Nginipha umyalo omutjha ngithi ; Thandanani . Njengombana nginithandile , nje - ke nani nifanele ukuthandana .
Ngalokhu boke abantu bazakwazi bona nibafundi bami , nanithandanako . ” — Jwa . 13 : 34 , 35 .
Umpostoli uJwanisi watlola wathi : “ Loyo ozonda umzalwana wakhe ambonako angekhe athanda uZimu angazange akhe ambone . ”
Tjengisa ukuthi uyabathanda abafowenu nabodadwenu ( Qala isigaba 17 )
Ngiziphi iindlela esitjengisa ngazo ukuthi siyabathanda abafowethu nabodadwethu ?
Funda 1 Thesalonika 4 : 9 , 10 .
21 : 15 .
IINGOMA : 128 , 45
Wathi kibo : “ ‘ Phoselani inede yenu ngesigomeni somkhumbi nizakubamba . ’
Yeke bayiphosela , babhalelwa kuyidosa ngebanga lobunengi beenhlambi . ” — Jwa . 21 : 1 - 6 .
( b ) Wafunda ini umnakwethu weThailand ngomsebenzakhe ?
Ngebanga lalokho , bewungidlela pheze soke isikhathi sokwenza umsebenzi kaZimu .
Yeke ngabona ukuthi nange ngifuna ukwenza umsebenzi wokutjhumayela ngomBuso kaZimu uze qangi , bekufuze ngilise umsebenzi lo ngombana bowuthatha isikhathi sami esinengi . ”
Yeke , yini umnakwethu lo ayenza ?
Naku akutjhoko : “ Ngemva komnyaka woke ngihlela , ngaqunta ukuthengisela abantu ama - Ice cream endleleni .
Nangisathoma nehlelweli kwaba budisi ngombana besele ngingasayifumani imali eyaneleko , lokho kwangidanisa .
Lokha nangihlangana nabantu ebegade ngisebenza nabo , bebangihleka bebangibuze nokuthi kubayini bengicabanga ukuthi ukuthengisa i - ice cream kungcono kunokusebenza ngamakhompyutha endaweni epholileko nehlelekileko .
Ngathandaza ngabawa uJehova bona angisize ngiqalane nobujamo bamobu begodu ngibe nesikhathi esinengi ngenza umsebenzakhe .
Esikhathini esingaphelisi ihliziyo , izinto zathoma ukuba ngcono .
Ngathoma ukwazana ngcono nabathengi bami ngafunda nekghono lokwenza kuhle i - ice cream .
Msinyana ngemva kwalokho bekuthi nakuphela ilanga i - ice cream yami ibe sele iphelile .
Nangikhuluma iqiniso , nje khona ngingcono khulu ngokweemali kunangesikhathi ngisebenza ngamakhompyutha .
Ngithabe khulu ngombana anginakho ukugandeleleka ebenginakho emsebenzinami wokulungisa amakhompyutha .
Okuqakatheke khulu kukuthi nje ngizizwa ngitjhidelene khulu noJehova . ” — Funda uMatewu 5 : 3 , 6 .
Ngemva kokubhajadiswa , wathi : “ Okukuphela kwento engizisola ngayo kukuthi ngimotjhe isikhathi esinengi ngaphambi kobana ngibone ukuthi ukulotjha uJehova kuthabisa khulu kunokuthanda izinto ezilethwa liphaseli . ”
UJesu wathi : “ Akakho ongasebenzela abaphathi ababili . ”
Wangezelela wathi : ‘ Anikwazi - ke ukulotjha uZimu khibe ngapha nilotjhana [ nobunjinga ] . ’
( Funda 1 Korinte 2 : 14 . )
( Qala isigaba 18 )
Qala isihloko esithi “ Ukuzithabisa Kwakho Kuyazuzisa ? ”
Isimu yona besingayivilapheli nokho . ”
Iinhliziyo zethu bezibabuhlungu tle nasicabanga ukutjhiya abantu ebesibafundela iBhayibheli . ”
Kodwana ngemva kwenyanga eyodwa bafumana iindaba ezimnandi kwamambala .
UMariam uthi : “ Samenywa bona sibe maphayona akhethekileko .
Kwasithabisa khulu ukwazi bona singakghona ukuraga nesabelo sethu . ”
Bathembela esithembisweni esifumaneka emtlolweni weRhubo 37 : 5 othi : “ Nikela indlelakho [ “ kuJehova , NW ” ] , umethembe . ”
Sikhuluma nje , akunanto esitjhoda ngayo esingathi iqakathekile . ”
Alo yini ebathabisa kangaka ?
9 Beka Ihliziywakho Emagugwini Avela KuZimu
IINGOMA : 38 , 56
Kubayini kufuze silindele bona abantu abatjhadileko nabantu abanabantwana kuzokukhamba kuba nemiraro abaqalana nayo ?
Izinto ezinjalo zisenza singabi ngitjho nokuncani ukungabaza bokuthi uJehova usifisela okungcono khulu ekuphileni begodu bekasolo abafisela okungcono nabantu bakhe bekadeni . — Funda uJoromiya 29 : 11 , 12 .
6 - 8 .
( Qala iingaba 9 , 12 )
( Funda 1 Samyela 1 : 4 - 7 . )
( Funda iRhubo 145 : 18 , 19 . )
12 : 34 .
IINGOMA : 153 , 104
Njengombana sizabe sifunda , wena akhulinge ukuzindla ngawo , uzibuze ukuthi yini ongayenza bona uwathande khulu amagugu la .
Funda uMatewu 13 : 45 , 46 .
Lokho kuyasitjela bona ilitjeli beliqakatheke khulu kuye .
( Funda uMarkosi 10 : 28 - 30 . )
( a ) Kubayini umpostoli uPowula athi isimu ‘ injengamagugu ngezitjeni zomdaka ’ ?
( Funda beRoma 1 : 14 , 15 ; 2 Thimothi 4 : 2 . )
Abanye basebenza eBethel , abanye maphayona abanye badala emabandleni .
U - Irene uyayithanda isimu tle , uthi , “ Kube ngakhetha eminye imigomo , angiboni ukuthi ukhona nowodwa ebewungangenza ngithabe njengalo engiwukhethileko . ”
( Qala isigaba 11 , 12 )
Alo kanti yini le okufuze siyifundise abantu ?
Akhesikhulume ngenye into eligugu elivela kuZimu .
Ngiliphi ‘ ibulungelo lamagugu ’ uJesu akhuluma ngalo kuMatewu 13 : 52 , begodu singalizalisa njani ?
( Funda uMatewu 13 : 52 . )
( Funda izAga 2 : 4 - 7 . )
Ummoya ocwengileko usisiza njani ?
Akhucabange nganasi into eyenzeka kumnakwethu uPeter .
Yabuza uPeter ifuna ukubona ukuthi uyalazi iBhayibheli na , yathi : “ Akhungitjele la msana , incwadi kaDanyela beyitlolwe ngaliphi ilimi ? ”
Nami angazi bona ipendulo yombuzwakhe ngayikhumbula njani .
Ngathi nangifika ekhaya ngathatha isiThala nePhaphama !
ngafunda esinye isihloko esihlathulula yona indaba le yokuthi incwadi kaDanyela yatlolwa ngelimi lesi - Aramu . ”
Ngambala lapha umnonwakho ukhona , ilapho nehliziywakho . ’ — Luk .
12 : 33 , 34 .
“ Bengingazwani nomfowethu ebengisebenza naye .
Ngelinye ilanga nasisaphikisana kabuhlungu , kwangena abantu ababili babona ukungazwani kwethu . ” — Kutjho uCHRIS .
“ Udade othileko ebengijayele ukutjhumayela naye , walisa ukutjhumayela nami .
Bengingazi bona kubayini . ” — Kutjho uJANET .
“ Kufunjathwakwami bengikhuluma nabantu abathathu ngasikhathi sinye .
Omunye wabo wangilayelisa begodu nami ngacabanga ukuthi vele sekakhambile .
Ngathoma ngakhuluma izinto ezingasizihle ngaye khonapho komunye ebengikhuluma naye kufunjathwako , kodwana ngafumana ukuthi umuntu ongilayelisileko lo bekangakawuvali ufunjathakwakhe . ” — Kutjho uMICHAEL .
“ Ebandleni , amaphayona amabili athoma ukungazwani .
Omunye wathoma wabiza omunye ngamagama angasimahle , wamtjela kwasala angalaziko .
Ukulwa kwabokhu kwabadanisa abanye . ” — Kutjho uGARY .
‘ Ningaphikisani endleleni . ’ ( Gen .
“ Lapha kunganakubonisana khona , amaqhinga ayatjhabalala . ” ( IzA .
UMichael uthi : Umfowethu wangilibalela ngokusuka ehliziyweni . ”
“ Bekezelelanani nakube omunye uneensolo ngomunye , libalelanani . ”
Nje bazwana kuhle , baragela phambili nokutjhumayela ngeendaba ezimnandi .
Umehluko lo ungabonakala ngasuthi awutjho litho ; kodwana ungabanga ukungezwani okukhulu . ”
Njengombana bengisebujamwenobo , ngathoma ukumkhulumisa kumbi .
Nakhu engangizitjele khona : ‘ Akangitjengisi ihlonipho engifaneko yeke nami angeze ngimhloniphe ! ’ ”
Uthi : “ Ngathoma ngahlolisisa ubutjhapho bami begodu akhenge ngikuthande engakubona kimi .
Ngabona ukuthi kufuze ngilungise indlela engicabanga ngayo .
Ngemva kokuthandaza ngikhulume noJehova , ngathengela udade lo ebengingazwani naye isipho esincani , ngamtlolela ikarada ngambawa bona angilibalele .
Sasingathana , savuma ukulisa izinto zakade bona zisale emuva .
Akhenge sisaba nomraro wokungazwani phakathi kwethu . ”
IINGOMA : 46 , 136
INTO eqakathekileko ebantwini namhlanjesi yimali .
Kubayini ipikiswano yobukhosi bakaZimu kufuze iphenduleke kuhle ?
( Funda iRhubo 83 : 19 , [ 83 : 18 , NW ] . )
Ukulwelwa kobukhosi bakaJehova kuqakatheke kangangani ?
( Funda u - Isaya 55 : 10 , 11 . )
( Funda uJobho 1 : 7 - 12 . )
Wathini kuye uJehova ?
( Funda uJobho 38 : 18 - 21 . )
Yini esingayifunda kilokho uJobho aqalana nakho ?
( Funda beRoma 5 : 3 - 5 . )
IINGOMA : 112 , 133
Bekaqinisile na uSathana ngokutjho njalo ?
Elinye ibanga elenza bona kuphume phambili kukuthi ubusa ngethando .
Indlela asitlhogomela ngayo idlula indlela thina ngokwethu esizitlhogomela ngayo .
Iinhloko zemindeni nabadala bangamlingisa njani uJehova ?
AmaRhubo isahluko 147 akhuthaza abantu bakaJehova bona bamdumise .
Yini le eyakara umrhubi kangaka ngoJehova beyamenza wakubuyelela kanengi ukuthi uJehova akadunyiswe ?
Inengi labantu abatjha likhonza uJehova isikhathi esizeleko .
16 : 9 .
IINGOMA : 32 , 154
Yini engasisiza bona singabi ziingqila zemali nezinto zephaseli ?
Kubayini sithi ephasineli angeze kwaphela ukutlhaga ?
Ngimiphi imibuzo esizokucoca ngayo ?
Funda uLukasi 16 : 1 - 9 .
Yini esingayifunda eselulekweni sakaJesu ?
Sazi njani ukuthi uZimu akakasidaleli ukuthi sigandelelane ngemali ?
Funda uLukasi 16 : 10 - 13 .
Akhusicocele bona abanye abafowethu nabodadwethu bawusebenzise njani umnono wephaseli .
Sengilibalela khudlwana , ngiyababekezelela nabanye abantu , nakunento engidanisileko ngiyamukela , nalokha nangelulekwako ngiyazithoba . ”
( Funda 2 Korinte 8 : 13 - 15 . )
U - Abrahamu watjengisa njani bona uyakholwa ?
( b ) Singasisebenzisa njani iseluleko sakaPowula namhlanjesi ?
UThimothi naye bekayindoda enokukholwa .
Ngemva kokuthi uPowula abize uThimothi ‘ ngesotja elihle lakaKrestu ’ watjho amezwi naka : “ Akakho ophuma ipi khisibe usazilibazisa ngokwekhaya ; ibutho liphikelela ukuthokozisa indunalo . ”
Ngiwuphi umnono owanelisako ?
Phela uJehova ubusisa abantu bona ‘ banothe ngemisebenzi emihle . ’
( Funda 1 Thimothi 6 : 17 - 19 . )
Nezindlu zethu sizozakha ngamagodo , amatje nangeensimbi ezisezingeni eliphezulu , kwamambala siyokwakha izindlu ezihle .
Nawufuna ukunikela nge - inthanethi ngena ku - jw.org ugandelele lapho kuthi khona “ Nikelela Umsebenzi Wethu Wephasi Loke . ”
IINGOMA : 121 , 75
USUSI uthi : “ Nanyana bese kudlule umnyaka woke sihlongakalelwe yindodanethu , besisasolo sizwa ubuhlungu . ”
Isikhathi ngasinye , uZimu wasilethela ukuthula eenhliziyweni neemkhumbulwenethu . ” — Funda uFilipi 4 : 6 , 7 .
UJesu walitjengisa njani izwela ngesikhathi kuhlongakele uLazaru ?
Nakhibe uqalene nesizi , imitlolo nasi ingakukhuthaza beyikududuze :
( Funda yoku - 1 Thesalonika 5 : 11 . )
Yini okufuze siyikhumbule ngabantu abaqalene nesizi ?
( IzA . 14 : 10 ) Ngitjho nanyana umuntu angayiveza indlela azizwa ngayo , ngezinye iinkhathi akusibulula ngabanye bona bakuzwisise lokho .
Okwanje angizizwa ngasuthi ngingedwa . ”
Nawutlolako ungadzubhula imitlolo eduduzako , tlola okuhle okukhumbulako ngomufi , utlole nangeenkhathi ezimnandi enibe nazo .
UJunia uthi : “ Ukufumana umlayezo omfitjhani okhuthazako namkha isimemo esivela emKrestwini kungisiza khulu tle , ” ungezelela ngokuthi : “ Amezwi anjengalawo angenza ngizizwe ngithandwa . ”
UDalene uyakhumbula , uthi : “ Ngababawa ukuthi bangithandazele .
Bathoma bangithandazela , nanyana ekuthomeni bekubudisi ukukhuluma , kodwana ngokukhamba kwesikhathi amaphimbwabo aqina batjho umthandazo othinta ihliziyo .
Ukukholwa kwabo okuqinileko , ithando labo , nokukhathazeka kwabo ngami kwangiqinisa . ”
“ Umngani uhlala athembekile , iye , ungumfo obelethelwe iinkhathi ezibudisi . ” ( IzA .
Omunye umnakwethu uthi : “ Bengilindele ukuthi umnyaka wami wokuthoma ngitjhadile uzokuba budisi khulu , begodu vele waba njalo .
Kodwana abanakwethu bahlela bona kuhlanganwe nabafowethu nabodadwethu abambalwa engitjhidelene nabo ukwenzela bona ngingabi ngedwa ngelanga ebengihlanganisa ngalo umnyaka ngitjhadile . ”
UJunia uthi : “ Ngokuvamileko kuyasiza abantu baba nawe nangezinye iinkhathi , ingasi ngeenkhathi ezikhethekileko kwaphela . ”
Uraga uthi : “ Ukwenza lokho kuqakatheke khulu begodu ngikho okuletha induduzo . ”
Bangenza ngalizwa ithando lakaJehova . ”
Kubayini iinthembiso zakaJehova zimthombo omkhulu wenduduzo ?
UJehova uthembisa godu ukuthi “ uzakuqeda ukufa unomphela . USomandla [ “ uJehova , NW ” ] uzokusula zoke iinyembezi kibo boke ubuso . ” ( Isa . 25 : 8 . )
Eminye imitlolo eduduzako nginasi : IRhubo 20 : 2 , 3 [ 20 : 1 , 2 ; NW ] 31 : 8 [ 31 : 7 NW ] 38 : 9 , 10 , 16 ; [ 38 : 8 , 9 , 15 , NW ] 55 : 23 , [ 55 : 22 , NW ] ; 121 : 1 , 2 ; Isaya 57 : 15 ; 66 : 13 ; Filipi 4 : 13 ; no - 1 Pitrosi 5 : 7 .
Qala nesihloko esithi “ Duduza Abashonelwe , Njengoba Kwenza UJesu , ” esiThaleni sangoNovemba 1 , 2010 .
“ Asazi bona singathini kodwana sifuna wazi bona siyakuthanda .
Angekhe sathi siyayizwisisa indlela ozizwa ngayo , kodwana esiqiniseka ngakho kukuthi uJehova wazi kuhle bona uzizwa njani begodu uzokuhlala anawe .
Sifisa kwanga imithandazwethu ingakwenza uzizwe ngcono . ”
“ Kwanga uJehova angaba nawe akududuze esikhathini esibudisesi . ”
“ Kwanga ungafumana induduzo ekwazini ukuthi uJehova uzokuhlala amkhumbula umuntu omthandako lo , uzokukhumbula koke ngaye begodu uzomvusa . ”
“ Umufi angekhe kusatlhogeka aqalane godu nenaba lethu ukufa .
Kodwana singatjho ukuthi ukukholwa kwakhe uJehova uzokukhumbula begodu sizombona ePharadesi . ”
“ Amezwi angekhe abuhlathulula ubuhlungu bokuhlongakalelwa , kodwana sisiqale ngabovu isikhathini lapho amezwi angekhe ahlathulula indlela esizabe sithabe ngayo ngesikhathi uBabethu wezulwini nakavusa umuntu omthandako lo . ”
Ngitjho nangesizi elikhulu amaKrestu ngeze azilwela , kodwana azokuthembela kuJehova bona awavikele
IINGOMA : 104 , 152
( b ) Singafundani nasingahlolisisa iRhubo 147 ?
Mabanga bani - ke lawo ?
Kusesenjalo nanamhlanjesi .
( Funda iRhubo 147 : 5 . )
Ngifuna ukuthabele ukuba nguFakazami ! ”
( Funda iRhubo 147 : 8 , 9 . )
UMutsuo uthi : “ Ngezwa ngasuthi uJehova unathi soke , begodu uyasitlhogomela .
Siduduzekile tle ! ”
12 , 13 . ( a ) UZimu nakazasisiza , khuyini okufuze sikubalekele ?
Ngakelinye ihlangothi uZimu ‘ uthobisa abakhohlakeleko . ’
UJehova “ uthaba ngabamesabako , iye , abaqalelela ukwethembeka kwakhe . ” ( Rhu .
Wenza ukuthula ngemikhawulwenakho . ”
( Qala iingaba 15 - 17 )
15 - 17 . ( a ) Iinlingo esiqalene nazo zingasenza sizizwe njani , kodwana uJehova usisiza njani ngeliZwi lakhe ?
Namhlanjesi , uJehova usinqophisa ngeliZwi lakhe iBhayibheli .
( Funda iRhubo 147 : 19 , 20 . )
IINGOMA : 89 , 140
Ngiwaphi amahlelo angaphumela ekutheni ube nengomuso elithabisako ?
Ukuphayona kungakulethela miphi imiphumela ?
ABANTU abatjha bazokuvuma nasithi umuntu nakazokuthatha ikhambo eliya ndawana kufuze ahlele kuhle izinto zakhe .
Ipilo injengokuthatha ikhambo , begodu singatjho ukuthi isikhathi esihle sokuhlela izinto zakho kulokha usesemutjha .
Wazi njani ukuthi uJehova ufuna uhlele kuhle begodu ube nengomuso elithabisako ?
( UMtj . 12 : 1 ; Mat .
Yini uJehova akufunela yona ?
UJehova ufuna uhlele njani ?
UMdalakho ‘ nguZimu wethando , ’ uZimu othabako , ‘ uZimu owadala umuntu ngomfanekiswakhe . ’
Nawulingisa uZimethu onethando , uzokuthaba .
Yini eyathabisa uJesu ?
UJesu wabekela abantu abatjha isibonelo esihle .
( UMtj . 3 : 4 ) UJesu bekatjhidelene noJehova , lokho wakwenza ngokuthi afunde imiTlolo .
“ Lapha kunganakubonisana khona , amaqhinga ayatjhabalala ; kodwana ngabeluleki abanengi ayaphumelela . ”
Njengelinye nelinye ibizelo ongalikhetha utlhoga isikhathi bona ube namakghono akhethekileko .
Ekuthomeni , bekungibhalela ukuthomisa iimfundo zeBhayibheli , kodwana ngokukhamba kwesikhathi ngafudukela kwenye isimu , kungakapheli iinyanga ezingakhi besele ngineemfundo ezinengi .
Omunye wabantu ebengifunda nabo wathoma ukuza esifundweni .
Ngokwesibonelo uJacob weNorth America utlola uthi : “ Nabengineminyaka eli - 7 abantwana abanengi ebengifunda nabo bebamaVietnam .
Bengifuna ukubatjela ngoJehova yeke ngenza amahlelo wokufunda ilimi labo .
Bengisizwa kumadanisa isiThala sesiNgisi nesesiVietnam .
Okhunye engakwenzako kujayelana nabantu ebesakhelene nabo abakhuluma isiVietnam ebandleni .
Ngathoma ukuphayona nangineminyaka eli - 18 .
Ngokukhamba kwesikhathi ngaya esiKolweni seBhayibheli sabaZalwana abangakaTjhadi .
Isikolwesi sangisiza ekuphayoneni kwami , sikhuluma nje ngimi kwaphela umdala ebandleni elisakhasako elikhuluma isiVietnam .
Abantu abanengi abakhuluma isiVietnam kuyabamangaza ukuthi ngifunde ilimi labo .
Bayangamukela emizinabo , begodu kanengi bayangivumela ukuthi ngifunde nabo iBhayibheli .
Abanye babo sikhuluma nje sele babhajadisiwe . ” — Madanisa nezEnzo 2 : 7 , 8 .
Ngathoma ukuphayona nangiqeda isikolo .
Kuyangithabisa ukukhuthaza nokubona ituthuko yelutjha ebandleni engikilo .
Ngemva kokuthi ngiye esiKolweni seBhayibheli sabaZalwana abangakaTjhadi ngafumana isabelo esitjha sokuphayona .
Esimini le akhenge khengifundele namunye abhajadiswe kodwana abanye bakghonile ukukwenza lokho .
Zinengi iindlela ongalotjha ngazo uJehova .
Kusese netlhogeko yamaWolo amanengi .
Ukuphayona kungakurholela njani keminye imikhakha yekonzo ?
UKevin uthi : “ Kusukela ngisesemsanyana bengisolo ngifuna ukusebenzisa isikhathi sami soke ngilotjha uJehova .
Yeke ngathi nangineminyaka eli - 19 ngathoma ukuphayona .
Ukwenzela bona ngikghone ukuzondla , bengisebenza umsebenzi wesikhatjhana , ngisebenzela umzalwana omumakhi .
Ngafunda ukufulela , ukufaka amafesdera neminyango .
Ngokukhamba kwesikhathi ngasebenza ngesiqhema esisiza nakuneenhlekelele zemvelo , esakha ngobutjha amaWolo womBuso nezindlu zabazalwana .
Ngathi nangizwa bona kutlhogeka abantu abazokwakha eBethel yeSewula Afrika , ngafaka isibawo , ngamukelwa .
ESewula Afrika bengikhamba ngiyokusebenza emaWolweni ahlukahlukeneko qobe .
Sinjengomndeni nesiqhema engisebenza naso .
Sihlala ndawonye , sifunda iBhayibheli ndawonye besisebenza ndawonye .
Kuyangithabisa ukutjhumayela nabazalwana nabodade qobe veke .
Amahlelo engawenza ngisemsanyana angithabisa ngeendlela ezinengi ebengingakazitjheji nangisakhulako . ”
Ikonzo yeBethel iyathabisa ngombana lapho yoke into oyenzako uyenzela uJehova .
Ngemva komnyaka nesiquntu , ngamenywa eBethel , lapha ngafunda ukusebenza ngomtjhini wokugadangisa iincwadi ngokukhamba kwesikhathi ngayokusebenza ngamakhomphyutha .
Engikuthabelako eBethel kukuthi ngihlangana nabantu abazizwa zisatjhisa iindaba ezimayelana netuthuko yomsebenzi wokwenza abafundi ephasini loke .
Ngiyakuthanda ukusebenza la ngombana sisiza abantu batjhidelane noJehova . ”
Qiniseka bona uJehova ufuna abantu “ babambelele ” engomusweni elithabisako .
( Funda 1 Thimothi 6 : 18 , 19 . )
Yenza lokho owazi bona kuzokuthabisa uJehova .
USATHANA uyakuhlasela !
Kade khulu azazi iindlela zabantu , kusukela kusadalwa umuntu .
Singakubalekela njani ukuphambukiswa nguSathana ?
Leyo yinto okufuze uzifumanele yona wena . ”
UJesu wathi : “ Ningabesabi labo ababulala umzimba ngemva kwalokho bangasakghona ukwenza ilitho . ”
Kodwana wathini uJehova ngalokhu ?
Banamala ! ’
26 : 24 , 25 ) Lalela uJehova , umthembe kikho koke okwenzako .
3 Uzimisele Na Ukubekezela ?
Bese kuthi sesibili - ke sona sidembe yokuthi uJehova angazenza njani izinto ebesingacabangi bona zingenzeka .
27 Ithando Bubuntu Obuhle Kwamambala
IINGOMA : 78 , 139
Nathi kufuze sibekezele njengomlimi .
Umphorofidi uMikha usifundisani ?
( Funda uMikha 7 : 1 - 3 . )
Nasingaba nokukholwa njengoMikha , sizokulinda uJehova ngombana sithanda .
Ngikho ‘ sibekezela silinde ngethabo . ’
U - Abrahamu kwafuze bona alinde iminyaka eminengi ngaphambi kokubelethwa kwaka - Esewu noJakopo ( Qala iingaba 9 , 10 )
Akhesicoce ngo - Abrahamu no - Sara .
Kubayini kanti bekutlhogeka bona u - Abrahamu abekezele ?
( Funda beHebheru 11 : 8 - 12 . )
Akhucabange ukuthi uzozizwa njani nakavukako epharadesi .
Wasizwa kukholwa kwakhe ngoJehova .
Nina nanihlele ukungilimaza kodwana uZimu wakujika lokho kwaba ngokuhle ukuze asindise amaphilo wabanengi njengombana kunjalo namhlanje . ” ( Gen .
( b ) Yini eyasiza uDavida bona abekezele ?
Kubayini uDavida bekazimisele ukubekezela ?
[ “ UJehova , NW ” ] ngizamrhubela ngombana ungenzele okuhle . ”
( Funda 2 Pitrosi 3 : 9 . )
Yini engasisiza bona sibekezele ?
IINGOMA : 76 , 141
Ngiziphi iimfundo esizifumanako kilokho okwenzeka kuPowula eFilipi ?
( Funda izEnzo 16 : 8 - 10 . )
Yini eyenzeka ngemva kwalokho ?
Wathi nakaqeda ukufika eMasedoniya , walilelwa ziinsimbi !
Kubayini uJehova avumela lokho bona kwenzeka kuPowula ?
Bobabili noSilasi bathoma “ bathandaza bavuma iingoma badumisa uZimu . ”
4 , 5 . ( a ) Ubujamo bakho bungafana njani nobujamo bakaPowula ?
( b ) Ubujamo bakaPowula batjhuguluka njani angakalindeli ?
Akhucabange nje bona izinto zatjhuguluka msinyana njani !
Yini esizokucoca ngayo , begodu yini esizoyibuyekeza esifundwenesi ?
( Funda 1 Pitrosi 5 : 6 , 7 . )
Kufuze senze ngokuvumelana nalokho esikuthandazelako .
Ngezinye iinkhathi angasimangaza ngokusenzela izinto esingakazilindeli .
UJehova wathumela ingilozi , yabulala amasotja kaSanirheribu azii - 185 000 ngobusuku bunye .
( a ) Sifundani kilokho okwenzeka kuJosefa ?
40 : 15 ; 41 : 39 - 43 ; 50 : 20 ) Kwamambala , uJehova wenza okudlula lokho uJosefa ebekakulindele .
Cabanga godu nangokhokho kaJosefa uSara .
Kubayini singamthemba uJehova ?
( Funda u - Isaya 43 : 10 - 13 . )
Siyazi ukuthi uJehova unendaba nathi begodu ufuna ukusibona siphumelela .
IINGOMA : 83 , 129
Yini ekarako ngabazalwana ephasini loke ?
Singabuhlubula njani ubuntu obudala begodu sihlale sibuhlubulile ?
Bekungumnyaka ka - 1939 ngesikhatheso , begodu bebazii - 6 000 aboFakazi ebebabanjiwe . ”
Yini eyenza ubuzalwana bethu buhluke ?
Indlela abantu abakhuluma ngayo malungana naboFakazi bakaJehova , ikhuthaza tle !
Ukuziphatha kumbi ngokwamabhayi .
USakura waraga nokuziphitha okumbokhu bewaba neminyaka ema - 23 ubudala .
Ukusilaphala .
Kwaba kumbi khulu kangangobana besele ngingasakghoni , bengihlala ngilinde ithuba lokuthi umma engihlalisana naye lo aphume ngendlini khona ngizokubukela iinthombe zomseme ezisilapheleko . ”
Yini eyasiza uStephen bona alahle itukuthelo ?
Nakazikhulumelako , uthi : “ Izinto zatjhuguluka emndeninami .
Nje , uStephen uyinceku ekhonzako ebandleni begodu sele kuminyaka embalwa umkakhe aliphayona lesikhathi esizeleko .
UHans akusimumuntu ebekasolo athobekile .
Imitlolo yeBhayibheli eyangikhuthazako ngu - Isaya 55 : 7 , othi : ‘ Isikhohlakali asilahle indlelaso embi , ’ nebe 1 Korinte 6 : 11 , ethi ngalabo esele balahle iindlela zabo zesono : ‘ Abanye benu beninjalo . ’
5 : 17 ) Siyazuza godu eliZwini lakaZimu nemmoyenakhe ocwengileko lokha nasilungiselela imihlangano kunye nalokha sisemihlanganweni yebandla .
Amanye amagama endabenethu le atjhugululiwe .
Qala isahluko 25 sencwadi ethi Intsha Iyabuza — Izimpendulo Ezisebenzayo , Umqulu 1 - ZU .
IINGOMA : 43 , 106
( Funda beKolose 3 : 10 - 14 . )
Wathi : “ Akusekho umGirigi nomJuda , osokiweko nongakasokwa , otjhili , umSkithi , amakhoboka nabatjhaphulukileko . ”
( a ) Iinkhonzi zakaJehova kufuze zibaphathe njani abanye ?
( Qala isithombe esisekuthomeni . ) ( b ) Waba yini umphumela ?
Waya emhlanganweni waboFakazi bakaJehova .
( Qala isigaba 10 )
Nasibatjengisa okutjhiwo mitlolo eBhayibhelinabo , njengesAmbulo 21 : 3 , 4 ; iRhubo 37 : 10 , 11 , 29 , bebalalelisisa kuhle ngasikhathi bebalile . ”
( Madanisa noHezekiyeli 28 : 17 . )
Funda izAga 22 : 4 .
UJesu wabeka siphi isibonelo endabeni yokubekezela ?
UJesu ‘ bekamnene . ’
Singabekezela njani ?
Kubayini kuqakathekile ukubekezela nokuba nommoya ophasi ?
Wangezelela wathi : “ Nanibandlululako , nenza isono . ”
Kubayini kuqakathekile bona simbathe ithando ?
Ithando “ liyabekezela , linesisa ” begodu “ alizikhukhumezi . ”
ITHANDO
UKUBEKEZELA
UMUSA
UKULUNGA
UKUKHOLWA
UBUMNENE
UKUZIBAMBA
UPowula wathi ngaphandle kwethando ‘ akasililitho . ’
Ithando ngilokhu : “ Akusingithi esamthandako uZimu , kodwana nguye owasithandako bewasithumela neNdodanakhe bona ibe mhlabelo oyihlawulo yezono zethu . ”
Akunamuntu ongaba nethando elingaka .
UJesu wathi : “ Ithando elikhulu umuntu angaba nalo kudela ipilwakhe ngebanga labangani bakhe . ”
Akhesibone ukuthi bangakwenza njani lokho .
UJwanisi watlola wathi : “ Bantwana , asingabi nethando ngamezwi namkha ngekulumo kodwana ngeqiniso nangezenzo . ”
Kodwana ngazibuza , ‘ Ngingamlingisa njani uJesu ekulungiseni indaba le ? ’
Ngemva kobana ngicabange ngokuthi uJesu bekazokwenza njani ngakhetha ukuyilisa idlule indaba le .
Ngokukhamba kwesikhathi , ngatjheja bona umuntu engisebenza naye okhulume ngami kumbi loya uphethwe kugula okumbi tle begodu ugandelelekile emkhumbulweni .
Ngaphetha ngokuthi kungenzeka bekangakanqophi ukutjho akutlole e - imeyilini leya .
Ukucabanga ngesibonelo sakaJesu sokuba nethando ngitjho nanyana sisilingekile lokho kwangisiza ngatjengisa ithando elifanako emuntwini engisebenza naye . ”
UJesu nakatjhiya izulu “ wazehlisa . . . bekwaba sekufeni . ”
Sizuza ngani nasiba nethando ?
UKUTHULA : “ Ninyamezele benibekezelelane ngethando , ” lokho kwenza ‘ silonde ubunye . ’
Lokho kuyatjengisa ukuthi sihlukile endleleni iphasi elenza ngayo . ( Rhu . 119 : 165 ; Isa .
Umhlangano omkhulu eDorobheni leMexico wango - 1941
Ngelanga elilandelako , abantu bazala endaweni abamenyelwe kiyo . ”
Elinye ibandla latlola lathi : “ Okukuphela kwendlela ehlanu kwala , siporo sesitimela . ”
Abanye bebalale emaWolweni womBuso .
Abantu abazi - 2 262 646 eMexico baya esiKhumbuzweni ngomnyaka ka - 2016
Incwadi kaMatewu ikhuluma khulu ngeendaba ezibandakanya uJosefa .
3 Zifundise Ukuzibamba !
Kutjho ukuthini ukuba nezwela ?
IINGOMA : 83 , 52
1 , 2 . ( a ) Ukubhalelwa kuzibamba kulethe miphi imiphumela ?
( Dut .
Yini esingayifunda esibonelweni uJehova asibekela sona ?
Ungazilungiselela njani ukuqalana neenlingo ?
Omunye umfowethu wenzakalelwa yini , begodu nathi kubayini kuqakathekile ukuthi sizibambe nakwenzeka izinto ezinjengalezi ?
Ababelethi bangabafundisa njani abantwana babo ukuzibamba ?
Alo ungabasiza njani abantwana bakho bafunde ukuzibamba ?
IINGOMA : 142 , 12
( Funda u - Eksodusi 34 : 5 - 7 . )
( b ) Kubayini kufuze wazi okutjhiwo liBhayibheli ngesirhawu ?
( a ) Kubayini uJehova athumela iingilozi eSodoma ?
( Funda u - Eksodusi 22 : 26 , 27 . )
Nakhu esikufundako : “ [ “ UJehova , ” NW ] uZimu waboyisemkhulu wabathumelela ilizwi ngeenthunywa zakhe kanenginengi ngombana warhawukela abantu bakhe nendawakhe yokuhlala . ” ( 2 Kron .
“ Wathoma wasifundisa okunengi . ”
Kunalokho , Kutlhogeka senze okusemandlenethu bona sibasize khona bazokusinda .
Yiba lisizo ngaso soke isikhathi .
Ukuba nezwelo kubuye kutjho “ ukuzwelana nabantu . ”
Faka isandla ekuhlanguleni abehlakalelwe ziinhlekelele .
14 : 31 ) Yena wasibekela isibonelo esihle khulu .
“ Qina , ungapheli amandla ! Yenza umsebenzi !
IINGOMA : 60 , 29
Kubayini ababelethi nabantu abatjha kufuze babe nesibindi ?
1 , 2 . ( a ) USolomoni waphathiswa muphi umsebenzi ?
Kuyatjho - ke ukuthi uSolomoni nakazakuthatha umsebenzi lo bekufuze abe nesibindi .
Yini okungenzeka uSolomoni wayifunda ngesibindi kuyise ?
Kubayini uSolomoni kwafuze abe nesibindi ?
( Funda 1 IinKronike 28 : 20 . )
Kubayini kufuze sibe nesibindi ?
Yini ekukarako ngesibindi sakaJosefa ?
URarhabu ngomunye wabantu ababa nesibindi .
Ukuba nesibindi kwakaJesu kwabasiza njani abapostoli ?
Akhesicoce ngezinto ezimbili ezizokutlhoga sibe nesibindi : emndenini nebandleni .
( b ) Abantu abatjha bangamlingisa njani uMosi ?
UJehova uzobasiza batlhogomele imindenabo .
( Qala iingaba 13 - 17 )
Watlola wathi : “ Ngakhula ngineenhloni khulu .
Yeke nanyana ngisesifundweni bekuba budisi ukukhuluma nabantu , bekuba budisi khulu - ke nakufuze ngitjhumayele .
Kuyathabisa ukwazi ukuthi udade lo ngokukhamba kwesikhathi wawufinyelela umgomo wokuba liphayona lesikhathi esizeleko . Wasizwa yini ?
Ababelethi abamaKrestu nabo kufuze babe nesibindi .
IRhubo 37 : 25 namaHebheru 13 : 5 abasiza njani ababelethi ?
( Funda iRhubo 37 : 25 ; Hebheru 13 : 5 . )
Omunye umfowethu onabantwana ababili uthi : “ Ababelethi abanengi benza koke abangakwenza bona basize abantwana babo baphumelele kwezemidlalo , zokuzithabisa nakwezefundo .
Yeke nathi kufuze sisebenzise koke esinakho sisize abantwana bethu bahlale banobuhlobo obuhle noJehova .
Akhenge sithatjiswe kukuthi abantwana bethu bayifinyelele imigomwabo yokukhonza uZimu kwaphela , kodwana nakukuthi simsebenzela soke . ”
Iza neembonelo ezitjengisa ukuthi isibindi siyatlhogeka nebandleni .
Abodade abakhulileko kukuphi lapho kufuze babe nesibindi khona ?
( a ) Yini engasiza abafowethu ababhajadisiweko bona babe nesibindi ?
( Funda Filipi 2 : 13 ; 4 : 13 . )
Yeke bafowethu ababhajadisiweko siyanibawa hle , yibani nesibindi begodu nisebenze ngamandla ebandleni !
Yeke “ qina , ungapheli amandla ! Yenza umsebenzi ! ”
IINGOMA : 116 , 115
yokutjhuguluka kwamalimi ?
yokuthuthuka kwezepolotiki ?
yabantu abalinga ukukhandela ukutjhugululwa kwalo ?
1 , 2 . ( a ) Bekuzokuba njani ukuphila kube iBhayibheli belingekho ?
Umpostoli uPitrosi wadzubhula incwadi ka - Isaya 40 : 8 .
( Funda 1 Pitrosi 1 : 24 , 25 . )
( Funda isAmbulo 14 : 6 . )
Bese kwathi nakamva nase ligadangiswa godu , imitlolo yamaKrestu yesiGirigi kwasetjenziswa ibizo elithi “ KOSI ” ngamaledere amakhulu .
Kubayini sithabe kangaka ngeBhayibheli i - New World Translation ?
( b ) Yini i - Greek Septuagint ?
Alo yini ebeyizokuba sisombululo somraro lo ?
( Funda iRhubo 119 : 162 - 165 . )
Sizokucoca ngani esihlokweni esilandelako ?
Ngo - Apreli 3 , 2017 kwavulwa i - museum yeBhayibheli emzimkhulu wethu oseWarwick , eNew York , e - U.S.A .
Indawo le inesihloko esithi , “ The Bible and the Divine Name . ”
Yeke siyanimema yenize nizokubona i - museum yeBhayibheli namanye ama - museum akhona emzimkhulu !
Nangabe uzokuhlela ukuza , sibawa utjhinge ku - www.jw.org bese ufaka isibawo .
Ungasithola nawungaya lapha kuthi khona , UKWAZI NGATHI > AMA - OFISI NEZOKUVAKATJHA .
emsebenzini wokutjhumayela ?
nawufundisa endaweni yesikhulumi ?
Wayifundela yesi - 2 Korinte 1 : 3 4 , ethi : ‘ UYise wesirhawu noZimu wenduduzo yoke , osiduduza kizo zoke iinhlupheko zethu . ’
Ngimuphi umthwalo abanakwethu abafundisa endaweni yesikhulumi abanawo ?
Asimthokozi na uJehova ngokusinikela iliZwi lakhe , iBhayibheli ?
Qala ibhoksi elithi , “ Ukutjhuguluka Kwezinto . ”
Lifunde qobe
Zindla ngalo
Kusebenzise okufundako
Zinikele isikhathi sokuhlathulula , ufanekise , begodu uveze indlela amavesi owafundako asebenza ngayo
“ Ukutjhuguluka kwezinto kwathoma lokha ngineminyaka eli - 15 , ngemva kokubhajadiswa kwami .
Bengisewolweni ngilalele ikulumo nangizakuzwa isikhulumi sidemba ngomtlolo kaJakopo 1 : 23 , 24 .
Amavesi la amadanisa iliZwi lakaZimu nesiboniboni okufuze siziqale kiso nasizakubona indlela uJehova asiqala ngayo .
Ngathoma ukuzibuza ukuthi kghani indlela engizibona ngayo iyafana na nendlela uJehova angiqala ngayo .
Eqinisweni ngathoma ngokungakwamukeli okutjhiwo mtlolo lo .
Bengisolo ngizitjela ukuthi akukafuzi ngilindele ukuthandwa nguJehova . ”
“ Ngemva kwamalanga ambalwa ngisacabanga njalo , ngafunda umtlolo owatjhugulula ipilwami .
Ngezwa ngasuthi uJehova ukhuluma nami bunqopha , uthi kimi : ‘ Iza , Vicky , asikhulumisane .
Ngiyakwazi , ngiyazazi nezono zakho , nehliziywakho ngiyayazi begodu ngiyakuthanda . ’
“ Ngabhalelwa nakulala ebusukwinobo .
Nalapho bengisolo ngizaza ukuthi mbala uJehova angangithanda , kodwana ngathoma ukucabanga ngomhlatjelo kaJesu .
Khonapho , kwangikhanyela ukuthi uJehova ungibekezelele isikhathi eside khulu , angitjengisa ngeendlela ezinengi bona uyangithanda .
Nanyana kunjalo , mina ebengikutjho ngokungamkholwa kwami bona uyangithanda , bengithi : ‘ Ithando lakho alisilikhulu kobana lingafikelela kimi .
Umhlatjelo weNdodanakho awusimkhulu bona ungagubuzesa izono zami . ’
Bekungasuthi angimthokozi begodu anginandaba nalokho uJehova angenzele khona .
Kodwana nje , akusekho koke lokho , ngombana ngazindla ngesihlengo , sengiyalizwa nethando lakaJehova . ”
Iinhlokwezi zidemba ngemibono kaZakariya yesithandathu , yekhomba , neyobunane .
31 Isenzo Esitjengisa Ithando LobuKrestu
Ulandiswa ngu - Olive Matthews
Kokuthoma akhenginitjele ngomlandwami .
NGABELETHELWA eHemsworth ngo - 1923 edorobheni le - Yorkshire , e - England .
Ngibelethwa nomfowethu u - Bob .
Ngomnyaka owalandelako sinoMary Henshall senziwa amaphayona akhethekileko .
Sathunyelwa esimini engatjhunyayelwa qobe , enarheni yeCheshire .
Sino - Arthur Matthews sahlangana ngo - 1946 , naye akhenge asekele zepi ngebanga lakanembezakhe .
Ngokukhamba kwesikhathi sathoma ukutlolelana .
Lapha siseHemsworth siqeda ukutjhada ngo - 1949
Kuyasithabisa ukwazi ukuthi sikhuluma nje sekunaboFakazi abanengi endaweni leyo .
Umfowethu nomkakhe uLottie nabo besele kukade batjhumayela eTlhagwini ye - Ireland , ngo - 1952 sobane njalo saya emhlanganweni omkhulu eBelfast .
Sobane njalo salala ngekoloyini .
Lelo kwaba likhaya lethu .
Okurarako kukuthi akhenge sibe nomraro ukujamisa ikharavanethu hlanu kwemizi yabosomasimu abanomusa .
Bekusithabisa ukujikeleza .
Leso kwaba sibusiso samambala .
Umhlangano wokuthoma weentjhaba e - Ireland waba ngo - 1965 eDublin .
Emhlanganweni lo bekunabantu abazii - 3 948 , kwabhajadiswa abama - 65 .
U - Arthur ulotjhisa uNathan Knorr lokha nakafikako emhlanganweni ngo - 1965
U - Arthur utjhaphulala incwadi ethi Incwadami Yeendaba ZeBhayibhili eGaelic ngo - 1983
Ngo - 2011 igatja leBritain nele - Ireland nakahlanganiswako ukuphila kwethu kwatjhuguluka ngokupheleleko , sathunyelwa eBethel yeLondon .
Udorhodera wathi u - Arthur uphethwe yi - Parkinson ukugula okubangela bona umuntu ahlengezele .
Eminyakeni embalwa edlulileko bengigandelelekile begodu ngizwa ubuhlungu khulu .
Kodwana nawuqalana nobujamo obunje , utjhidelana noJehova .
“ Asingabi nethando ngamezwi namkha ngekulumo kodwana ngeqiniso nangezenzo . ” ​ — 1 JWA . 3 : 18 .
IINGOMA : 72 , 124
Ngiyiphi indlela ephuma phambili yokutjengisa ithando ?
Ngelinjani ithando elinganakuzenzisa ?
UJehova wakutjengisa njani ukuthi abantu ubathanda ngokungazenzisiko ?
UJehova watjengisa ukuthi uyabathanda abantu ngitjho nangaphambi kobana adale u - Adamu no - Eva .
Singalitjengisa njani ithando lamambala ?
6 , 7 . ( a ) Liyini ithando ‘ lamambala ’ ?
Ngimiphi imibuzo ekufuze sizibuze yona ?
( Funda uMatewu 6 : 1 - 4 . )
( Funda beRoma 12 : 10 . )
Kubayini nasibuka abantu lokho kufuze kuphume ehliziyweni ?
Singatjengisa njani ukuthi sinethando lamambala nasenzela abanye umusa ?
Iba nomusa .
( Funda 1 Jwanisi 3 : 17 . )
Buyisana nabantu .
( Funda beRoma 12 : 17 , 18 . )
Singatjengisa njani ukuthi silibalele ngokusuka ehliziyweni ?
Dela izinto ozithandako .
Ithando lamambala liqakatheke ngani ?
Ithando libubuntu obuhle ukubudlula boke .
IINGOMA : 125 , 135
Ngiyiphi “ isabula ” uJesu ebekakhuluma ngayo ?
Ungathembeka njani kuJehova ngitjho nanyana iinhlobo zakho ziphikisa iqiniso ?
3 , 4 . ( a ) Umlayezo kaJesu ubathinta njani abantu ?
UJesu wathi : “ Ningadlumbani bona ngilethe ukuthula ephasinapha .
Awa , angikalethi ukuthula , kodwana ngilethe isabula . Ngize bona ngizokuraranisa indodana noyise , indodakazi nonina , umalukazana nonosokana .
Yini abalandeli bakaJesu abaqalana nayo ?
Ababelethi bangabafundisa njani abantwana bona bahloniphe umbelethi ongakholwako ?
Kunokwenza njalo bafundise ukuthi woke umuntu kufuze azikhethele yena ukulotjha uJehova .
Iba nomusa nawukhuluma nazo .
“ Ikulumo yenu ayibe nomusa njalo . ”
( Funda 1 Pitrosi 3 : 1 , 2 , 16 . )
Hlela kusese ngaphambili .
Ungalwisana njani nokuzizwa kabuhlungu ngokungathabisi iinhlobo zakho ?
Hlonipha indlela uJehova akhalimela ngayo abantu .
( Funda beHebheru 12 : 11 . )
Elinye lamadorobho amakhulu ekutjhunyayelwa kiwo eLagos , lidorobho elinabantu abaningi khulu e - Afrika .
IINGOMA : 120 , 117
Ngesikhatheso ubujamo bama - Israyeli bebujame njani ?
( Funda uZakariya 1 : 3 , 4 . )
Isahluko 5 sencwadi kaZakariya sithoma ngombono ongakajayeleki .
( Funda uZakariya 5 : 1 , 2 . )
Funda uZakariya 5 : 3 , 4 .
8 - 10 . ( a ) Siyini isifungo ?
Yini esiyifundako ngombono wesithandathu kaZakariya ?
( Funda uZakariya 5 : 5 - 8 . )
Alo , kutjho ukuthini lokho ?
( Funda uZakariya 5 : 9 - 11 . )
IINGOMA : 28 , 136
Uzizwa njani ngomsebenzi omkhulu wokwakha owenziwa namhlanjesi ?
( Funda uZakariya 6 : 1 - 3 . )
UJehova usazisebenzisa iingilozi bona avikele bekaqinise abantu bakhe
7 , 8 . ( a ) Iintaba ezimbilezi zijamele ini ?
( b ) Kubayini iintabezi zenziwe ngedzila namkha ikoporo ?
Kubayini iintabezi zenziwe ngedzila namkha ikoporo ?
Bobani abatjhayeli beenkoloyana begodu uyini umsebenzabo ?
( Funda uZakariya 6 : 5 - 8 . )
Akhuthi uyalicabanga ilangelo .
( Funda uZakariya 6 : 9 - 12 . )
( Funda uZakariya 6 : 13 . )
UJehova wabaqinisekisa njani abeJuda ?
( Funda uZakariya 6 : 15 . )
UJehova angeze avuke alilibale ithando esimthanda ngalo !
( Qala iingaba 18 , 19 )
UYISE lakaJohn wabhajadiswa wabanguFakazi kaJehova ekupheleni kwaka - 1950 , wabhajadiselwa eGujarat e - India .
Nakathatha i - emvilobhu walemuka ukuthi uJohn ulimele umuno , yeke wafuna ukumsiza .
Waya kumphristakhe wambuza yona imibuzo ayibuze umma onguFakazi loya .
Ngitjengisa lapho iBhayibheli elitjho khona ukuthi uJesu akasi nguZimu .
Ngitjengisa nalapho elitjho khona ukuthi akukafuzi sithandaze kuMariya .
Ngitjengisa yong ! ”
Kwamambala akhenge aphinde .
3 Bhina Ngethabo !
Singafumana isifundo esiqakathekileko elungiselelweni ledorobho zokubalekela zakwa - Israyeli wekadeni .
IINGOMA : 10 , 2
Ukuvuma kudlala yiphi indima nasilotjha uZimu ngeqiniso ?
( b ) Kufuze simvumele njani uJehova , begodu bobani okufuze badose phambili endabeni le ?
Naku ongakwenza : Khetha iingoma ozithandako .
( a ) Ukuvula umlomo ngokwaneleko nasibhinako kungasisiza njani ?
( Qala iingaba 11 - 14 )
Bhinela phezulu
Phrakthizani iingoma zethu ekukhulekeleni kwenu komndeni ( Qala isigaba 18 )
( Funda u - Isaya 12 : 5 . )
IINGOMA : 8 , 54
( Funda iRhubo 34 : 22 . )
( Funda uNumeri 35 : 24 , 25 . )
Kuqakatheke ngani lokho ?
( Funda uJotjhuwa 20 : 4 . )

Isono sadlula sidlulile .
Alo wena uyaphephela na kuJehova ?
Kuphela komuntu esingaphephela kuye !
IINGOMA : 125 , 88
Singamlingisa njani uJehova endabeni yomusa abanye nabatlhoga sibalibalele ?
1 , 2 . ( a ) UJesu bekazizwa njani ngomThetho kaZimu ?
Alo kanti umraro bewukuphi ?
( b ) Yini - ke thina esiyifunda ngoJehova endabeni le ?
( Funda IzEnzo 20 : 26 , 27 . )
Kubayini ukuphepha kuqakathekile ebantwini bakaZimu ?
( Funda uNumeri 35 : 20 - 24 . )
Kodwana khambani niyokufunisisa bona umtlolo lo uthini lokha usithi , ‘ Ngilulukela ukwethembeka , ingasi umhlabelo . ’
Angikazeli ukuzokubiza abantu abalungileko , kodwana ngizele ukuzokubiza izoni . ’
Bebangakezeli ukuyokudla emzini kaMatewu .
Kokuthoma , thandazela ikghono lokuhlukanisa nokuhlakanipha .
Amadorobho asiphephelo akufundisani wena ?
Abodade ababili abamaKrestu batjhumayeza umuntu othengisako edorobheni leTipitapa
IINGOMA : 38 , 31
UPowula wakhupha siphi isiyeleliso malungana nokucabanga njengabantu abangakholwako ?
Ngisiphi isibonelo sendlela yokucabanga kwabantu abangakholwako begodu singakubalekela njani ukucabangokho ?
Yelelani - ke bona kungabikhona namunye onithumba ngobuhlakani nangekohliso elilize , ngokwefundiso yabantu esekeleke phezu kwemimoya yephasi , ingasi kuKrestu . ”
“ Ngingaba mumuntu olungileko ngaphandle kokukholelwa kuZimu . ”
( Funda iRhubo 10 : 4 . )
( Funda uJoromiya 10 : 23 . )
“ Ungathaba ngaphandle kokuya esondweni . ”
( Funda uMatewu 5 : 3 . )
UJehova unelungelo lokusibekela imithetho , angitjho nguye owasidalako .
Nakube ilihlo lakho langesigomeni likwenza wone , ligobhodlhe ulilahle ! ”
Uzakuzonda omunye athande omunye namkha azinikele ngokupheleleko komunye bese unyaza omunye .
Anikwazi - ke ukulotjha uZimu khibe ngapha nilotjhana [ noburego ] . ’
( Funda 1 Thesalonika 2 : 13 , 19 , 20 . )
“ Abantu bangazilungisela iinkinga zabo . ”
Singakubalekela njani ukucabanga njengabantu abangamlotjhiko uZimu ?
IINGOMA : 122 , 139
Singawufumana njani umvuzo njengomndeni ?
( b ) Yini esisiza sihlale sikhumbula umvuzo ?
Singazivikela njani ebujamweni obuyingozi ?
Ukubulala iimfiso ezisisono kutlhoga bona sibalekele zokuzithabisa ezisilapheleko .
Bekezelelanani nakube omunye uneensolo ngomunye ; libalelanani njengombana neKosi yanilibalela , iye nani kumele nilibalele .

( Funda uMtjhumayeli 7 : 21 , 22 . )
10 , 11 . ( a ) Kubayini ukuba nomona kuyingozi ?
IliZwi lakaZimu lithi : “ Ithando liyabekezela . . .
Alinamona . ”
23 : 16 - 18 ) Singalihlawulela na ithando elinjengelakaJonathani ?
Madoda , thandani abafazi benu , ningabakhahlamezi .
Bantwana , lalelani ababelethi benu kikho koke ngombana lokho kuyayithokozisa iKosi .
Yini ekufuze amadoda amaKrestu eyenze nangabe abomkabo abangakholwako abawahloniphi ?

IliZwi lakaZimu lithi ? “ Owazi ilwazi ulonda amezwakhe nonommoya ophasi umumuntu ozwisisako . ” ( IzA .
3 “ Ngiyazi Uzakuvuka ”
Iinhlokwezi zizokuqinisa ukukholwa kwakho evukweni .
11 : 11 .
IINGOMA : 142 , 129
Lokho okutjhiwo liBhayibheli mayelana nevuko kwamnikela njani isibindi uMarta ?
NjengoMarta ngisiphi isenzakalo osiqale ngabomvu ?
Uthe : “ Ngiyazi uzakuvuka aphile . ”
17 : 8 - 16 ) Kwathi ngokukhamba kwesikhathi indodanakhe yahlongakala .
( Funda 1 AmaKhosi 17 : 17 - 24 . )
( Funda 2 AmaKhosi 4 : 32 - 37 . )
UPitrosi wenzani komunye udade omKrestu obekahlongakele ?
Ngelinye ilanga umpostoli uPowula nakasemhlanganweni othileko ngekamerweni eliphezulu eTrowasi , nje ebizwa ngokuthi yi - northwest Turkey .
Isokana elithileko elingu - Ewuterhusi belilalele , lihlezi efesidereni .
4 : 17 , 18 ) UJehova bewatjho nokuthi iimbusiswezi zizokuvela “ ngo - Isaka . ”
89 : 49 , [ 89 : 48 , NW ] ) Lokho akutjho ukuthi uZimu angabhalelwa kuvusa umuntu ohlongakeleko .
( Funda uJob 14 : 13 , 15 . )
IINGOMA : 151 , 147
( b ) Kubayini ivuko liqakatheke kangaka ?
Kodwana umbuzo kukuthi ivuko ungalibala ezintweni ezikuthabisa khulu ozikholelwako ?
( Funda 1 Korinte 15 : 12 - 19 . )
Siyazi bona uJesu wavuswa .
UJesu wabandakanyeka njani ekuzalisekeni kweRhubo 118 ?
‘ Abakhi ’ baphika uMesiya ( Qala isigaba 7 )
UJesu waba njani ‘ lilitje eliqakathekileko ’ ?
Nangabe uJesu waphikwa bewabulawa , kwenzeka njani ukuthi ‘ abelilitje eliqakathekileko ’ ?
( a ) IRhubo 16 : 10 labikezela ngani ?
16 : 10 ) UDavida bekangatjho ukuthi angeze afe namkha angeze abulungwa .
( Funda izEnzo 2 : 29 - 32 . )
( Funda izEnzo 2 : 33 - 36 . )
( Funda izEnzo 13 : 32 - 37 , 42 . )
Wathi kunemininingwana emalungana ‘ neenkhathi namkha amalanga uBaba awabeke ngentando yakhe . ’
UPowula watlola wathi : “ UKrestu uvusiwe kabafileko , yena osithelo sokuthoma sabaleleko . ”
Kuzokwenzekani ngabaye abazesiweko hlangana nesikhathi ‘ sokubaya ’ kwakaKrestu ?
Sinitjela lokhu ngelizwi leKosi kobana thina esiphilako , esiseleko bekubuye iKosi , angeze sabandulela nakanye abahlongakeleko .
IKosi ngokwayo izokwehla ivela ezulwini ngelizwi elikhulu , ngephimbo lengilozi ekulu nangokuzwakala kweporompita kaZimu , abahlongakalele kuKrestu bazokuvuka qangi .
Abazesiweko abazokuphila hlangana nesikhathi seenhlupheko ezimbi ‘ bazokuhlwithelwa emafini . ’
Ulandiswa NguFelix Fajardo
Nange ungabuya uzowukhomba onotjwala ! ”
Ngabelethwa ngeen - 29 Julayi 1929 , ngakhulela ethresteni elisesifundeni seBulacan ePhilippines .
Bengikuthanda khulu ukufunda iBhayibheli khulukhulu nangifunda ngamavangeli amane .
Ukuyifunda bekungenza ngifune ukulandela isibonelo sakaJesu . — Jwa . 10 : 27 .
Ngesikhatheso ababelethi bami bangibawa bona ngibuye ekhaya .
Omunye uFakazi osekakhuliwe weza ekhaya azosihlathululela lokho okutjhiwo liBhayibheli “ ngemihla yokuphela . ”
Wasimema bona siyokufunda iBhayibheli kenye indawo eseduze nekhaya .
Sacoca ngeBhayibheli ubusuku boke .
Mina ngaphendula ngathi : “ Iye , ngiyafuna . ”
Bengazi ukuthi ngifuna ‘ ukulotjha iKosi . ’
Ngomhlaka 15 Febherbari 1946 , sabhajadiswa sibabili emlanjeni ebewuhlanu kwalapho besihlanganyela khona .
BakwaCruz bathi ngizokuhlala nabo e - Angat .
Bekakhuluma ngesiNgisi , bese kamva ngarhunyeza ikulumwakhe ngesiTagalog .
Bengihlangana kwabanakwethu abamenywako .
Ekuseni bengisiza ekhwitjhini .
Ngemva kokuphela kwesikolo , ngaba liphayona elikhethekileko isikhatjhana ngikhonza eBronx eNew York City .
Ngeveke yokuthoma sitjhadile savakatjhela ibandla lesihlengele seRapu Rapu .
Bengitologela uMfoweth ’ u - Albert Schroeder
Kazi sabe sathenga nendawo yendoda leya eyathi , “ AmaTjhayina awathengisi . ”
Bese njengombana livundile , lingakhulela ku - Fallopian tube namkha litjhinge esibelethweni .
Lokho kuzabe kukurhulula umbungu .
Yeke i - IUD enganakoporo enengi angeze yasebenza kuhle hle . ”
IINGOMA : 141 , 134
ukwazi imitlolo ecwengileko ?
ukwenziwa bona ukholelwe izinto ozifundileko ?
ukuhlakaniphela ukusindiswa ?
( a ) Itjho ukuthini ikulumo ethi ‘ ukwenziwa bona ukholelwe izinto ozifundileko ’ ?
( b ) Sazi njani ukuthi uThimothi wenziwa bona akholelwe iindaba ezimnandi ngoJesu ?
Kokuthoma , bekezela .
( Funda yebeRoma 12 : 1 NW . )
Nakhibe inombuzo , awa lokho kuhle .
Eqinisweni , bengizokutshwenyeka nakhibe bekazakwamukela esimfundisa khona ngaphandle kokubuza imibuzo . ”
Bayizwisisa kuhle na ihlathululo yeBhayibheli ngokufa ?
Yini eqakathekileko okufuze uyikhumbule nawufundisako ?
UStephanie , umma wamadodakazi amathathu uthi : “ Kusukela abantwana bami basesebancani , bengisolo ngizibuza ukuthi kghani ngiyakhuluma na nabo ngokuthi kubayini ngikholelwa kangaka ukuthi uJehova ukhona uyaphila , unethando nokuthi iindlela zakhe zilungile ?
Bayabona na ukuthi mbala ngiyamthanda uJehova ? ’
Angekhe ngalindela abantwana bami bona bakholelwe izinto abazifundako nakhibe mina ngapha angizikholelwa . ”
Kuphambene khulu nobudlhadlha . ”
IBhayibheli lithi : “ Ubudlhadlha bubotjhelelwe ehliziyweni yomntwana . ”
Ihlobelo lokuvuthwa liqakathekile umuntu nakazakusindiswa .
( Funda izAga 24 : 14 . )
Kubayini imizamo yababelethi iqakathekile ?
( Qala iingaba 14 - 18 )
( Funda uMarkosi 12 : 30 . )
Ababelethi bangabasiza njani abantwana babo ‘ bahlakaniphele ukusindiswa ’ ?
Qala ngaphasi kwesithi IZIMFUNDISO ZEBHAYIBHELI > AMATHULUZI OKUTADISHA IBHAYIBHELII .
IINGOMA : 133 , 135
Ungayenza njani isindiswakho iphumelele ?
Kubayini ukubhajadiswa kuqakatheke kangaka ?
Umuntu angangenzani na ? ”
Kubayini kuqakathekile ukukhumbula lokho ?
Ngombana angeze wazi ukuthi uzokuqalana namiphi imiraro ekuphileni kwakho ngaso soke isikhathi . ”
( b ) Yini ongayifunda encwadini yebeFilipi 4 : 11 - 13 ?
Kutjho ukuthi ukwenza isindiswakho iphumelele “ ngokwesaba nangokuthuthumela ” ?
UJehova ufuna ube mnganakhe .
( Funda beFilipi 4 : 6 . )
Yeke nawe kungakusiza !
Alo yini engakusiza ?
Yeke nangicoca nabo , ngivele ngikhulume into ehlobana nokukholwa kwami , njengokuthi ‘ ngelinye ilanga bengifundisa ngeBhayibheli . . . bese ngirage nalokho ebengifuna ukukutjho .
Ngasikhathi babe babuze nemibuzo ngalo iBhayibheli .
Indlelami le kwamambala ingenzela izinto zibe lula .
Begodu qobe ngemva kokukhuluma nabo ngizizwa ngithabe khulu ! ”
Kodwana ngithi kwaphela esingahlathulula aboFakazi .
Yeke indlela esenza ngayo izinto , izokuba nomthelela omkhulu ekutheni bazokuthini nasibatjhumayezako .
Alo ithiwani - ke nange sineenhloni , sinevalo lokukhuluma ngeenkolelo zethu ?
Lokho kungenza abantu bacabange ukuthi asizikhakhazisi ngalokho esingikho .
Bangabe bangawamukeli nomlayezwethu ngebanga lokuzinyaza .
Kodwana nasitjhaphulukako besitjengise nokuthi siyaqiniseka ngalokho esikhuluma ngakho , bangasihlonipha . ”
UJesu wathi : ‘ Nanyana ngubani ofuna ukungilandela , akazidele , atjathe isiphambano sakhe angilandele . ’
27 Abantu BakaZimu Bahluke Njani ?
IINGOMA : 3 , 47
Isaya 40 : 26
Matewu 11 : 28 - 30
2 Korinte 12 : 9 , 10
Yini esingayifunda emtlolweni ka - Isaya 40 : 26 ?
Funda u - Isaya 40 : 26 .
Akekho umuntu okhewabala zoke iinkwekwezi .
Yini esenza siqiniseke bona uJehova angasipha amandla wokukghodlhelela ?
Funda u - Isaya 40 : 28 .
Funda u - Isaya 40 : 29 .
UJesu wathi ebafundini bakhe : “ Thathani ijogi lami . ”
Waraga wathi : ‘ nizozifumanela ukuphumula ngombana ijogi lami ngelomusa nomthwalo wami ulula . ’
Umbuzo uthi nasibuyako sizizwa njani ?
Umnakwethu obekasibekela ikulumo ngelangelo wayibeka kuhle , ngombana bekanezwela .
Ngakhunjuzwa ukuthi kuqakathekile ukuba khona esifunweni . ”
Umpostoli uPowula bekatjho ukuthi nakathi : “ Nangibogabogako , kulapho - ke nginamandla khona ” ?
Funda u - Isaya 40 : 30 .
Wabhina wathi : “ Ngesizo lakho ngingathelekela ibutho , ngoZimami ngingeqa umthangala wedorobho . ”
Funda u - Isaya 40 : 31 .
Alo inga - kghani lokho kutjho ukuthi uZimu besele alibele ngoJosefa ?
Omunye owaba sibonelo nguDavida .
Funda be - Efesu 4 : 26 .
Kghani uzokulalela lokho okutjhiwo liBhayibheli ngokulungisa iindaba msinyana ?
( Rhu . 25 : 14 ) UZimu uyamthanda .
Ungathoma ngokuthi : “ Ungangizwa kumbi kungenzeka ukuthi ngikhubeka msinya , sekukuthi indlela okhulume ngayo nami kizolo ingenze ngazizwa . . .
Nokho okuthabisako kukuthi uDavida waba nesibindi sokwenza intando kaJehova .
( Rhu . 32 : 3 - 5 ) Nakhibe wenze isono esikhulu , uJehova uzimisele ukukusiza ulungise .
IINGOMA : 18 , 14
sisisiza njani ?
Sizokuphendula miphi imibuzo esihlokwenesi ?
( Funda 2 Korinte 13 : 5 . )
( Funda uJwanisi 3 : 16 ; 17 : 3 . )
( a ) Yini uJesu ayithandazelako ngobusuku bokuthoma besiDlo seKosi saNtambama ?
( b ) Ngibuphi ubufakazi bokuthi uJehova wawuphendula umthandazo kaJesu ?
( Funda uJwanisi 17 : 20 , 21 . )
( Funda uHezekiyeli 37 : 15 - 17 . )
Singabuthuthukisa njani ubunye ebantwini bakaZimu ?
( Funda uMatewu 18 : 35 . )
‘ Singabekezelelana njani ngethando ’ ?
Kunomehluko .
Sazi njani ukuthi kuzakuba nesiKhumbuzo samaswaphela ?
( Funda iRhubo 133 : 1 . )
Abanakwethu nabodadwethu beRiberalta , eBeni bafaka iincwadi eflayini .
IINGOMA : 80 , 50
Kubayini uJehova alindele bona simuphe izinto esinazo ?
Ihlangano iyisebenzisa njani iminikelo namhlanjesi ?
Ihlangano iyisebenzisa njani iminikelo namhlanjesi ?
( Funda izAga 29 : 21 . )
Iminikelo eminengi akutjhiwo bona ivelaphi .
( Funda 2 Korinte 8 : 18 - 21 . )
Ihlangano kaJehova nayo yenza okufanako .
Iminikelwakho isekela imisebenzi eyenziwa ephasini loke ( Qala iingaba 14 - 16 )
Kodwana sithi nasiqeda ukubukela amavidiyo ahlukahlukeneko , sikhumbule ukuthi sinabanakwethu nabodadwethu ephasini loke .
Abanakwethu nabodadwethu bayithanda khulu i - JW Broadcasting .
Khesibezwe kanengi ngemva kokubukela ihlelo laqobe nyanga bathi bazizwa batjhidelene nesiHlopha esiBusako .
Sikhuluma nje bazikhakhazisa khulu ngokuba sehlanganweni kaZimu . ”
( Funda izAga 11 : 24 , 25 . )
Isihlokwesi sikukhuthaze bona wenzeni ?
IINGOMA : 111 , 109
UJehova usibumbe njalo .
UJesu wathi : ‘ Kufuze uthande umakhelwanakho njengombana uzithanda wena . ’
Indoda ethanda umkayo izithanda yona , ngombana akakho umuntu owakhe wazonda umzimbakhe , kunalokho uyawondla begodu awuthande . ”
( Funda beRoma 12 : 3 . )
Singakubalekela njani ukuzithanda khulu ?
UPowula watlola bona emihleni yokuphela kuzakuba nabantu “ abathanda imali . ”
Eminyakeni eyadlulako iphayona elithileko lesihlengeleni latjela enye indoda ngoZimu .
U - Aguri , umsa kaJakhe wathini ngokunjinga nokuchaka ?
( Funda uMtjhumayeli 5 : 12 . )
Yathi : ‘ Nangingasutha khulu ngizakukhohlwa ngithi : “ Konje phana ngubani uSomnini loyo ? ” ’ ( IzA .
Bekahlala athi : ‘ Mina nginomqatjhi ongithanda tle ! ’
Nje - ke nami sengiyaphayona , sobabili nomkami sisebenzela uJehova . ”
Singakubalekela njani kuthanda imali ?
( Qala iingaba 13 )
Litjho ukuthi angeze bamthanda . ”
Singakubalekela njani ukuthanda zokuzithabisa ?
IINGOMA : 127 , 101
ukuthuthukisa indlela esiziqala ngayo ?
( Funda 2 Thimothi 3 : 1 - 5 , 13 . )
Begodu siyazi nokuthi “ Ithando alizigqaji , alizikhakhazisi . ”
Lokhu kungenza ngitjhaphuluke , ngikghone ukukhulumisana nabo begodu ngibalalele .
Koke lokhu kwenza ngibone ukuthi banendaba nami begodu nami ngilwela ukubathabisa . ”
Lokhu bekusolo kuliqiniso bekube nje .
( Funda uJwanisi 13 : 34 , 35 . )
Yini uJesu ayenzako etjengisa indlela athanda ngayo abanye abantu ?
Walapha abarholopheleko , wavula amehlo weemphofu , wahlambulula abanobulepheru begodu wavula iindlebe zabangezwako .
( Funda u - Isaya 11 : 6 , 7 . )
Ungafunda ngemilandwabo esihlokweni esithi “ IBhayibheli Litjhugulula Amaphilo ” esifumanaka ku - jw.org .
Kufuze sibatjele abantu ukuthi siboFakazi bakaJehova .
8 : 23 .
3 Lingisa UNowa UDanyela NoJobho
28 Ithabo — Bubuntu BakaZimu Okufuze Sibe Nabo
IINGOMA : 89 , 119
Danyela ?
Jobho ?
9 , 10 . ( a ) Singakulingisa njani ukukholwa nokulalela kwakaNowa ?
( Funda uMalaki 3 : 17 , 18 . )
( b ) UJehova wathini ngoDanyela ?
( b ) Yini ababelethi abangayifunda esibonelweni sababelethi bakaDanyela ?
( Funda uJobho 1 : 9 , 10 . )
19 , 20 . ( a ) Singakulingisa njani ukukholwa kwakaJobho nokulalela kwakhe ?
IINGOMA : 126 , 150
1 - 3 . ( a ) Yini ezosisiza sihlale sithembekile kuZimu emalangeni wokuphela la ?
Kuthiwani ngawe ?
( Funda uDanyela 6 : 7 - 10 . )
Kodwana bekahlobene no - Abrahamu , u - Isaka noJakopo .
( Funda uJobho 31 : 24 - 28 . )
( Funda amaRhubo 11 : 5 ; 26 : 4 . )
1 : 1 - 3 ) Umbuzo ongazibuza wona ngothi , ‘ Njengombana uNowa , uDanyela noJobho bebamazi kuhle uJehova , wena umazi njengabo na ? ’
Ukhokho kaNowa u - Inogo naye “ gade atjhidelene noZimu . ” Nanyana kunjalo “ uZimu wamhlwitha ebantwini . ”
11 : 10 ) UJesu wathi : “ U - Abrahamu uyihlo wakuthabela khulu ukubona ilanga lami , begodu walibona wathaba . ”
Awakho amezwi angahlathulula indlela esizizwa ngayo . ”
Ngombana uZimu usambulele zona ngommoyakhe . ”
UJesu wathi : “ Izintwezi ngizikhulume kini , bona ithabo lami libe kini , nethabo lenu lizaliswe . ”
ABATJHUMAYELI
IINGOMA : 17 , 13
Singambona njani umuntu othanda uZimu ?
( 3 ) Ukusebenza ngamandla bona sibe “ nomkhumbulo kaKrestu ” kuzosisiza njani bona sibe nobuhlobo noZimu ?
( Funda 1 Korinte 2 : 14 - 16 . )
UPowula usikhuthaza bona sinqotjhiswe mmoya kaZimu .
Lithini iBhayibheli ngabantu abathanda uZimu ?
Begodu singabuthuthukisa njani ubuhlobo bethu noZimu ?
Yini esingayifunda endabeni kaJakopo ?
Yini esingayifunda endabeni kaMariya ?
( Funda uLukasi 1 : 46 - 55 . )
( Funda u - Isaya 63 : 9 ; Markosi 6 : 34 . )
URachel udade weBrazil uthi : “ Bengizithanda izinto zakanokutjho , khulukhulu izembatho .
Lokho kwangenza bona ngingambathi ngendlela ehloniphekileko .
Kodwana ukufunda ngoZimu kwangisiza ngabona itlhogeko yokobana ngitjhugulule indlela engiphila ngayo , ngilotjhe uZimu .
Ukwenza amatjhuguluko khona akhenge kube bulula , kodwana kwangithabisa ukuwenza ngombana ukuphila kwami kwaba nomnqopho . ”
Yeke ukuba nomkhumbulo kaJesu kuzosenza simlingise ngcono uJehova .
Lokho kwabenza bathi : “ Sibofakazi bazo zoke izinto azenzako . ”
Ukucabanga njengoKrestu kuzosisiza njani ?
IINGOMA : 22 , 75
Nawucabanga njengoKrestu uzokuphila njani ?
Uthi : “ Akunantwembi ebengiyenza , sekukukuthi bekunezinto ebezingangiphathi kuhle .
Nawungiqalileko bewungathi ngitjhidelene khulu noZimu , phela bengihlala ngikhona esifundweni , nakuvela amathuba wokuphayona ngiphayone .
Kodwana kukhona ebengingakwenzi kuhle . ”
Uthi : “ Bewungafunga uthi akunalitho engilaziko ngeBhayibheli .
Yeke , ngahlala phasi ngazibuza , ‘ kazi ngimi okufuze adose phambili ezintweni zakaZimu , kuyatjho ukuthi kufuze ngidose amakowusu . ’ ”
Ngathoma ukuzwisisa begodu okuqakatheke khulu kukuthi indlela ebengithanda ngayo uZimu yathuthuka . ”
( 3 ) Nawuthanda uJehova ngehliziywakho yoke , uzokuphila njani ?
( b ) Ukufunda nokuzindla kuzosisiza ngani ?
( b ) Ngisiphi isibonelo esiseBhayibhelini esingasilingisa ?
12 , 13 . ( a ) Yini ezosisiza sisebenzise okutjhiwo yincwadi yebeRoma 15 : 5 ?
Singakhumbula umpostoli uPitrosi .
Nathi singenza okufanako .
( Funda 2 Pitrosi 1 : 5 - 8 . )
Ukucabanga njengoKrestu kuzosisiza njani ?
UKrestu bekangenzani nabekangaqalana nobujamo engiqalene nabobu ?
Ngiyiphi ‘ imisebenzi efileko ’ ekufuze siyilise ?
Iinqunto engizithathako zizongisiza na bona ngizibeke imigomo yokwenza intando kaZimu ?
Imigomo yokusebenzela uZimu .
Kubayini ufuna ukuthuthukisa ithando lakho ngoZimu ?
Besenganelisekile begodu ngithabile . ”
3 Ukubhajadiswa — Sibopho Sawo Woke UmKrestu
Umpostoli uPitrosi wayelelisa amaKrestu ebekaphila ngesikhathi sakhe wathi : “ Yibani nommoya wokwamukela iimvakatjhi . ”
Yini esingayenza ukutjengisa ukuthokoza nasimenyiweko ?
Thina - ke kufuze sisabele njani nakasikhalimako ?
Imibuzo le yoke nje , sizokufumana iimpendulo zayo eenhlokwenezi .
“ Alo - ke uriyadelani ?
Sikima , ubhajadiswe . ” — IZE . 22 : 16 .
IINGOMA : 51 , 135
UKolose 1 : 9 , 10
UMtjhumayeli 12 : 1
UJakopo 4 : 17
Yini ababelethi ekufuze baqiniseke ngayo ngaphambi kokuthi umntwanabo abhajadiswe ?
UBLOSSOM Brandt uthi : “ Kwaphela iinyanga ngisolo ngitjela ubaba nomma ukuthi ngifuna ukubhajadiswa , kazi bekusematheni ekhaya .
Bebafuna ngilemuke bona igadangweli liqakatheke kangangani .
UDisemba 31 1934 lilanga eliqakathekileko khulu kimi , lilanga engabhajadiswa ngalo . ”
Funda uMatewu 28 : 19 , 20 .
5 , 6 . ( a ) IBhayibheli elikutjhoko ngoThimothi kusenza siphethe ngokuthini malungana nokubhajadiswa kwakhe ?
( Funda uKolose 1 : 9 , 10 . )
( Funda uJakopo 4 : 17 . )
Inga - kghani kukhona okuqakatheke ukudlula lokhu ?
Watjela uJehova ukuthi uthabe khulu ngesiqunto esenziwe yindodakazakhe sokuzinikela kuye . ”
IINGOMA : 52 , 41
1 Pitrosi 3 : 20 , 21
Matewu 28 : 19 , 20
IzEnzo 22 : 16
( Funda 1 Pitrosi 3 : 20 , 21 . )
Funda izEnzo 8 : 35 , 36 .
Kubayini kungakafuzi sikatelele abanye bona babhajadiswe ?
Nawumbelethi kungenzeka khewazibuza ukuthi , ‘ kazi umntwanami ukulungele na ukuthi angabhajadiswa ?
Umbuzo wokuthoma uthi : “ Ngesisekelo somhlatjelo kaJesu Krestu , sele utjhugulukile na ezonweni zakho begodu wazinikela kuJehova bona wenze intando yakhe ? ”
IINGOMA 100 , 87
Alo ukuwamukela iimvakatjhi bekuzowasiza njani ?
Sizamukela njani iimvakatjhi emihlanganwenethu ?
( Funda 3 Jwanisi 5 - 8 . )
Nakasitlolelako uthi : “ Bengingabaza ekuthomeni , ngombana besisanda ukutjhada nendlwethu iyincani .
Kodwana ukubamukela bekusithabisa khulu .
Nanyana besisanda ukutjhada nje , safunda ukuthi abantu abatjhadileko bangathaba nabalotjha uJehova banomgomo wokumsebenzela bobabili . ”
Kubayini abantu anasanda ukufika ebandleni kufuze bamukelwe ?
( Funda uLukasi 10 : 41 , 42 . )
Ngelinye ilanga umkami khabe akhumbule ekhaya , ngathi ngiyamduduza kodwana akhenge kusize kangako .
Kwathi ngo - 7 : 30 ntambama , kweza umuntu wakokoda emnyango .
Nasivulako , umma esifunda naye iBhayibheli uphethe ama - orentji amathathu .
Bekazosamukela .
Samngenisa samseza amanzi .
Ngemva kwalokho senza itiye ne - hot chocolate .
Nangabe uyatshwenyeka qobe nakufuze umukele iimvakatjhi , yazi bona awusiwedwa .
Udade olupheleko weBhrithani uthi : “ Nawazi bona iimvakatjhi ziza kwakho , uyatjharagana .
Kodwana nasele uzamukele , uyabona bonyana ithabo oba nalo ngemva kwalokho lidlula ukutshwenyeka ebewunakho . Zinjalo - ke zoke izinto ozenzela uJehova .
Ngikuthabela khulu ukuhlala phasi neemvakatjhi zami , sicoce . ”
Omunye umdala nakasitlolelako uthi : “ Ukumema abangani bebandleni kungenza ngibazwisise khudlwana , ngazi nokuthi balifumene njani iqiniso . ”
Umka mnakwethu obekafundisa eenkolwenezo wathi ngitjhaphuluke .
Bewathi yena nobabakwakhe bebabajikelezi , kodwana bebaba nesikhathi esimnandi nomuntu othanda uJehova nonemigomo efana neyabo nanyana anganazinto ezinengi . Ngombana ulotjha uJehova anganazinto ezinengi ezimthikamezako .
Lokho kwangikhumbuza umma obekahlala athi : ‘ Singcono isabelo semirorho lapha kunethando khona . ’ ( IzA .
( Funda IzAga 25 : 21 , 22 . )
Umuntu oneemvakatjhi uyatinazela azilungisele kuhle ( Qala isigaba 20 )
Umrhubi uDavida wabuza uJehova wathi : “ Ngubani ongakhosela ngetendeni lakho ? ”
Kuqakathekile nokuhlonipha amasiko wabanye .
Kubayini kuqakathekile ‘ ukwamukela iimvakatjhi ’ ?
Kodwana ngeze sathi siyazisola ngakho koke lokho .
Abazalwana ababili banikela indoda ependa ibriji iphetjhana , baphambi kweKaštilac , umakhiwo olirubhi owakhiwa ngeminyaka yabo - 1501 - 1600 hlanu kweSplit
IINGOMA : 123 , 86
Uzokuphadlha izinto . ”
( Funda uTitosi 2 : 11 - 14 . )
Umzalwana lo uyakhumbula , uthi : “ UGraham bekanekinga yokuzikhukhumeza .
Bekabahloye kumbi abazalwana abademba indabakhe nakazakukhitjhwa ebandleni .
Yeke sathatha iimveke ezimbalwa sifunda imitlolo ekhuluma ngokuzikhukhumeza nemiphumela yakho .
UGraham wathoma ukuzihlolisisa amadanisa lokho angikho nalokho okutjhiwo liliZwi lakaZimu malungana nokuzikhukhumeza , akhenge akuthanda lokho ebekangikho .
Kwamthinta khulu lokho !
Ngemva kokuvuma ukuthi mbala bekavalwe ‘ sigodo ’ esikuzikhukhumeza begodu nobujamo bomkhumbulwakhe bebungakalungi , yeke wathoma ukulungisa umkhumbulwakhe wabangcono .
Wathoma ukuya emhlanganweni qobe , wafunda iliZwi lakaZimu ngokuzikhandla , kwaba mukghwakhe ukuthandaza .
( Funda uLukasi 4 : 22 . )
Umpostoli uPitrosi watlola wathi : “ Yelusani umhlambi kaZimu ongaphasi kwetjhejo lenu , nisebenze njengabatlhogomeli , ingasi ngokukatelelwa , kodwana ngokuzithandela phambi kwakaZimu ; ingasi ngethando lenzuzo yokungathembeki , kodwana ngetjiseko ; ningazenzi amakhosi phezu kwalabo abalilifa lakaZimu , kodwana nibe ziimbonelo emhlanjini . ”
( Funda u - Isaya 11 : 9 . )
IINGOMA : 56 , 89
Ababelethi bangabakhulisa njani abantwana babo ngeemfundiso zakaJehova ?
( Funda beHebheru 12 : 5 - 11 . )
Yini esiza umntwana akghone ukuzikhalima ?
4 , 5 . ( a ) Kubayini ukuzikhalima kuyingcenye eqakathekileko ‘ yobuntu obutjha ? ’
( Funda beFilipi 4 : 13 . )
Yini engasisiza sikhuthalele ukufunda iliZwi lakaZimu ?
8 - 10 .
Lalela uJehova .
Omunye umzalwana wathi : “ Nangikhumbula indlela ababelethi bami abangikhulisa ngayo , ngiyathaba tle !
( b ) Omunye umndeni wazuza njani ababelethi nabalalela uJehova ?
Ngemva kweminyaka ethileko indodakazethu yabuyiselwa .
Siyathandana tle ! ”
( b ) Singawenza njani umsebenzi wabadala ube lula ?
Bebangilalelisisa bangangiqaleli phasi begodu bangikhuthaze .
Ngitjho nanyana bangaba majadu kangangani kodwana qobe nakuphuma isifundo bekubakhona oza kimi angibuze ukuthi ngivuke njani .
Njengombana khengatjho phambilini , izinto ezenzeka ekuphileni kwami bezingenza ngingakholwa nakancani ukuthi mbala uJehova uyangithanda .
Kodwana uJehova wasebenzisa abadala babanami kikho koke lokhu , bangiqinisekisa ukuthi uyangithanda .
Into engiyithandazelako kukuthi ngingasalahlekelwa buhlobo bami noJehova . ”
Kubayini ubuso bakho bunyukubele nje ? Kanti nawenza okuhle uzakhe umomotheke na ?
Nawenza okungakalungi , yelela isono sikulindile nawusuka lapha . Sikhanukela ukukubinda kodwana wena kufuze uqine kunaso . ’
( IzA . 1 : 24 - 31 ) Yeke ‘ asilaleleni ukusola ’ kwakaJehova , nasenza njalo sizokuhlakanipha .
3 Indlela Etjhinga Ekululekweni
Ephasini loke nje abantu bafuna ikululeko .
Alo amaKrestu wona ayiqala njani ikululeko ?
15 Lingisa UJehova ​ — Ngokududuza Abanye
8 : 36 .
IINGOMA : 54 , 36
Yikululeko enjani ekhamba ibe nala iphelela khona ?
Kubayini namhlanje singasanakululeko yamambala ?
( Funda 1 IinKronike 29 : 11 , 12 . )
Nguye owaziko godu ukuthi yini engakabalungeli , yeke abantu nabafuna ukuthaba kufuze bathembe uZimu bebamlalele .
Nabangalaleliko kufuze bazihlukanisele okulungileko nokungakalungi . ”
Lokhu kuyafana nendabeni ka - Adamu no - Eva , njengomtjhayeli wesiphaphamtjhini ongalaleliko , nabo bakhetha ukwenza izinto ngendlelabo .
Yini okufuze siyenze bona sifumane ikululeko yamambala ?
Wathi : “ Nanihlala elizwini lami , kwamambala nibafundi bami , nizolazi iqiniso , begodu iqiniso lizonitjhaphulula . ”
Kodwana ikululeko le ngeyani ?
Kubayini sithi ikululeko uJesu ayithembisako ingasenza ‘ sitjhaphuluke kwamambala ’ ?
Yini engasenza sitjhaphuluke kwamambala ?
( Funda beRoma 8 : 1 , 2 , 20 , 21 . )
IINGOMA : 49 , 73
( c ) Ngimiphi imibuzo ekufuze sizibuze yona ?
( Qala ngaphasi kwesithi INTERVIEWS AND EXPERIENCES > ENDURING TRIALS . )
Zoke izinto zivumelekile , kodwana akusizo zoke ezakhako . ”
UNowa nomndenakhe basibekela siphi isibonelo ?
Bebaphila ephasini elonakeleko nelizele inturhu .
UJehova uthi senzeni thina namhlanjesi ?
( Funda uLukasi 4 : 18 , 19 . )
Kwanjesi ngikuzwisisa ngcono okutjhiwo mtlolo kaJakopo 4 : 8 nawuthi : ‘ Tjhidelani kuZimu , naye uzokutjhidela kini . ’
Ngagcina ngikutholile ebesolo ngikufuna , lokho kwakuyipilo eyanelisako . ”
Abatjhadikazi abamaphayona akhethekileko batjhumayela endaweni ekude , ehlanu kweBalykchy
ABANTU EBEBAKHONA ESIKHUMBUZWENI NGO - 2017
IINGOMA : 7 , 3
UPowula wabaduduza njani abafowabo ?
UJehova wamkhuthaza njani uNowa ?
( b ) UJehova wayikhuthaza njani iNdodanakhe ?
Yewuze uzokuhlanganyela ithabo lekosakho . ”
UHezikhiya wazikhuthaza njani iinkhulu zamabutho nabantu bakwaJuda ?
UJafta nakabona ukuthi yindodakazakhe emhlangabezako , wezwa ubuhlungu khulu .
UPitrosi ‘ wabakhuthaza njani abafowabo ’ ?
22 : 31 , 32 .
IINGOMA : 90 , 87
Ngubani okufuze akhuthaze abanye ?
Bobani okufuze sibakhuthaze , begodu kubayini ?
Funda u - Isaya 32 : 1 , 2 .
Yini engasiza abadala bebandla bakhalime ngendlela ekhuthazako ?
Nje - ke tjhiseka begodu utjhuguluke . ”
Babelethi , niyabafundisa na abantwana benu bona bakhuthaze abanye ?
Ngemva kwesikhathi esithileko ngahlangana nomunye udade osele aluphele , wangitjengisa ukuthi uyangithanda wabe wazwelana nami .
IKosi uSolomoni yakhe yathi : “ Maye lihle kangangani ilizwi elifike ngesikhathi !
Ubuso obuthokozileko buthabisa ihliziyo neendaba ezimnandi zinepilo emathanjeni ! ”
IINGOMA : 135 , 144
Sizokucoca ngani esihlokwenesi ?
Sizokudemba amabanga amathathu enza sitjho njalo .
( Rhu . 92 : 2 , 5 ) Zibuze muntu omutjha ukuthi umkoloda kangangani uJehova .
Muntu omutjha , zibekele imigomo khona nje , ungathi usafuna ukukhulakhula .
Incwadi yezAga 21 : 5 ithi : “ Amaqhinga wokhutheleko aletha inzuzo . ”
Nawuhlela imigomakho kusesenesikhathi uzokuphumelela .
Nangabe bengifundele zomthetho , bengizokurhola imali enengi , kodwana bekuzokuba budisi ukufumana umsebenzi ongivumela bona ngisebenze amalanga ambalwa . ”
Ungakghona ukuphayona ?
Ngilokho uLuca akwenza .
17 , 18 . ( a ) Yini uJehova ayifunako ebantwini abatjha namhlanjesi ?
USathana linaba lethu .
Ngabelethelwa endaweni encani ebizwa ngokuthi yiLiberty , e - Indiana ese - U.S.A .
Ngingowesine ngakwethu , nginomnakwethu nabodadwethu ababili engibalamako , ngemva kwami kuza abafowethu ababili nodadwethu .
NGATHI nangithoma isikolo , zange kube nomehluko ongako .
Endawenekhethu le bekunamasimu amanengi , into ebeyitjalwa khulu emasiminapho bekusiphila .
Ukukhuluma iqiniso , vele nakimi beyihlangahlangene khulu .
Bebafuna ngenze zobusotja zibe libizelo lami .
Nokho kilokhu , bangimemela esiFundweni seNcwadi seBandla , bekumhlangano omncani ebewubanjelwa ekhabo , kucocwa ngeBhayibheli .
Ngathi kibo , ngizakucabanga ngayo .
Kazi ngakhe ngabuza umma ngaboFakazi bakaJehova , wavele wathi kimi : “ Abantwabo balotjha iqhegu elibizwa ngokuthi nguJehova . ”
Kodwana ngesikhatheso ngavele ngabona ukuthi ikungu isukile emehlweni .
Esinye isibonelo salokho nguJesu , kazi bekayindoda epheleleko .
Ngomnyaka olandelako ka - 1958 ngathoma ukuphayona .
Angizisoli nakancani ngesiqunto engasithathakweso .
UGloria bekanjengelanga liphuma , nanamhlanjesi usesenjalo .
Wasitjela ukuthi okwanjesi , abantu abatjhadileko ababizwa eBethel .
Ngakelinye ihlangothi , bekumnandi tle ukuba nabanakwethu begodu besikuthanda ukutjhumayela .
Mina - ke ngathoma ukufunda iBhayibheli nendodakazi yabatjhadikazaba kunye nobaba wakwayo .
Bese kwathi umma nendodakazi bakhetha ukuzinikela kuJehova babhajadiswa .
Besinabangani ebandleni lamakhuwa .
Bekunehlangano yama - Ku Klux Klan ( KKK ) ebeyikhuthaza abantu bona bakhethululane ngokobuhlanga , beyinamandla khulu ngesikhatheso .
Ngo - 1962 ngamenyelwa esiKolweni seKonzo somBuso ebesiseSouth Lansing , eNew York .
Kodwana ngaphambilini bengifake isibawosomsebenzi kenye ikhamphani yamafowuni esePine Bluff .
Ukungiqatjha kwabo bekuzokutjho ukuthi ngimumuntu wokuthoma onzima ozokusebenzela ikhamphani le .
Udade lo wathi , “ Khamba uye esikolweni , ufunde okunengi ubuye ngapha uzozifundisa . ”
Nasi indlela uGloria asikhumbula ngayo isikhathi esaba naso ePine Bluff : “ Bengiyithanda khulu isimakhona .
Benginabantu ebengibafundela iBhayibheli abali - 15 kuya kwabama - 20 .
Yeke ekuseni besitjhumayela emzini ngomuzi , bese sifunde nabantu iBhayibheli beliyokutjhinga , ngeezinye iinkhathi besiqeda pheze nge - awara le - 11 ebusuku .
NoMnakweth ’ u Leon Weaver nje osekamthintanisi weKomidi leGatja le - United States wakhethwa bona abe mjikelezi ngesikhatheso .
Benginevalo nangicabanga ukuthi ngizokuba mjikelezi .
Ngeenkhathezo umjikelezi bekangabandulwa khulu .
Ngelinye ilanga sathi sivakatjhele ibandla eTennessee isiqhema sama - KKK seza sazokumatjha lapho .
Sathoma ukukhonza eBethel ngemva kwenyanga sifumene isimemo .
UGloria bekamuhle njengelanga naliphumako , nanamhlanje usesenjalo
SinoGloria siyakuthanda ukuba seBethel .
Kwathi ngo - 1999 ngaba lilunga lesiHlopha esiBusako .
U - Isaya 32 : 17 uthi : “ Iinthelo zokulunga zizakuletha ukuthula , iye , umphumela wokulunga ube kuzotha nokuvikeleka nini nanini . ”
Kwesibili , kufuze sithandaze sibawe ummoya ocwengileko .
Alo , wakuthola njani ukuthulokhu ?
Ngafika - ke ngamlotjhisa ngelimi lakhe .
Ngamangala sekangibuza athi , ‘ ubekwa yini la ? ’
Ngazithoba ngathi ngizokubona uKomitjhinara omKhulu .
Wamdosela umtato , weza wazongihlangabeza wangilotjhisa ngelimi lendawo .
Ngemva kwalokho wangilalelisisa njengombana ngimhlathululela ngomsebenzethu nokuthi aboFakazi babantu bokuthula . ”
8 : 15 .
IINGOMA : 68 , 72
Yini ezosisiza sithele iinthelo ngokubekezela ?
( Qala isithombe esisekuthomeni . ) ( b ) Wathini uJesu ngokutjhumayela ‘ eendaweni zemakhaya ’ ?
Bese kuthi emini babuyele ekhaya .
Ukubona indlela abathembeke ngayo kuyangikhuthaza bona nami ngikghodhlelele nangitjhumayelako . ”
“ Isibonelo sabo esihle siyangithabisa . ”
Ngimiphi imibuzo emithathu esizokucoca ngayo begodu kubayini ?
Nanyana kunjalo , awukho omunye umsebenzi engifuna ukuwenza ngaphandle kwalo . ”
Funda uJwanisi 15 : 1 - 5 , 8 .
Funda uLukasi 8 : 5 - 8 , 11 - 15 .
Sizithela njani “ iinthelo ngokukghodlhelela ” ? (
Ngombana ngiyabafakazela ukuthi bayamtjhisakalela uZimu , kodwana ingasi ngokuvumelana nelwazi elinembileko . ”
Singamlingisa njani uPowula ?
( Funda uMtjhumayeli 11 : 6 . )
Kwathi nasibuyelako , abantu evane basidlule basibuza bona besiyephi .
Bebatjho nokuthi basihlulukele . ”
Babe babawa nabomagazini . ”
Kubayini kufuze uzimisele ukuthela “ iinthelo ngokukghodlhelela ” ?
15 : 8 .
IINGOMA : 53 , 60
( Funda uJwanisi 15 : 1 , 8 . )
UJesu watjela abafundi bakhe wathi : “ UBaba uphazinyuliswa kuragela kwenu phambili nokuthela iinthelo . ”
( b ) Uzizwa njani ngelungelo onalo lokucwengisa ibizo lakaZimu ?
Lokho kukodwa nje kungenza ngiragele phambili ngitjhumayela . ”
( a ) Ngokomtlolo kaJwanisi 15 : 9 , 10 kubayini sitjhumayela ?
Funda uJwanisi 15 : 9 , 10 .
Yini ezokutjengisa ukuthi sifuna ukuhlala sithandwa nguKrestu ?
IBhayibheli lithi uNowa ‘ bekamtjhumayeli . ’
( a ) Ngiziphi iinzathu zokutjhumayela ekukhulunywa ngazo kuMatewu 22 : 39 ?
13 , 14 . ( a ) UJwanisi 15 : 11 ukhuluma ngasiphi isipho ?
Ithabo .
( Funda uJwanisi 15 : 11 . )
( a ) UJwanisi 14 : 27 ukhuluma ngasiphi isipho ?
Ukuthula .
( Funda uJwanisi 14 : 27 . )
( a ) UJwanisi 15 : 15 ukhuluma ngasiphi isipho ?
( b ) Abapostoli bebazokuhlala njani babangani bakaJesu ?
Ubungani .
( Funda uJwanisi 15 : 14 - 16 . )
Singaqiniseka ngokuthi uJehova uyayiphendula imithandazwethu ( Qala isigaba 18 )
© 2018 Watch Tower Bible and Tract Society of Pennsylvania
IINGOMA : 150 , 32
Khuyini okufundileko ngenaba lethu uSathana ?
Umpostoli uPitrosi ubiza uSathana uDeveli ngokuthi ‘ libhubezi elibhodlako , ’ kanti noJwanisi umbiza ngokuthi ‘ yinyoka ’ ‘ nedragoni . ’
( Funda uJakopo 4 : 7 . )
( IzA . 18 : 11 ) Bese kuthi labo abawakholelwako amanga la , isikhathi sabo esinengi basisebenzisela ukuzifunela ‘ ubuGwili ’ kunokulotjha uZimu .
Iye khona kuqakathekile ukwazi inaba lethu , kodwana lokho akutjho ukuthi kufuze silisabe .
Yeke nasijamelana naye uzosibaleka .
IINGOMA : 79 , 140
Ngiziphi izembatho zepi ezisisiza sivikele ubuhlobo bethu noZimu ?
Funda kwebe - Efesu 6 : 14 .
Ababelethi bami nabangani bami bayangithemba . ”
Kodwana kunengi okuhle okutholako ngokwenza njalo , ufunda ukuzithemba , utjhidelana noZimu begodu nabantu abakuthandako bayakuhlonipha . ”
Ibhande leqiniso ( Qala iingaba 3 - 5 )
Lokho kwenza ngagandeleleka begodu ngangasazithemba isikhatjhana . ”
Abanye ‘ babangani ’ bami bathoma ukusebenzisa kumbi iindakamizwa , abanye balisa nesikolo .
Indlela abaphetha ngayo yaba buhlungu khulu .
Nambala uJehova uyasivikela . ”
Uthi , “ Ngihlala ngizikhumbuza ukuthi kazi nanginje ngithwele ibizo lakaJehova begodu isilingweso siyindlela kaSathana yokulwisana nami .
Qobe nangihlula iinlingo zakhe ngithaba khulu . ”
Isivikelo sesifuba sokulunga ( Qala iingaba 6 - 8 )
Funda kwebe - Efesu 6 : 15 .
Lokho kungenza ngibe sebujamweni obuhle bokucabanga ngokuthi yini ezobasiza .
Nangilungiselele kuhle , ngingakghona ukukhuluma nabo , ngisize ngamunye wabo ngento ayitlhogako . ”
Ngenza isiqinisekiso sokuthi ngifunda zoke iincwadi ezikhitjhwe yihlangano zabantu abatjha .
Lokho kungisiza bona ngikghona ukusiza iintanga zami ngeBhayibheli namkha ngizitjele zingene ku - jw.org bona zisizeke . ”
Amanyathelo wokulungela ukutjhumayela ( Qala iingaba 9 - 11 )
Ngiziphi ezinye iindlela uSathana asihlasela ngazo ezifana ‘ nemisubela evuthako ’ ?
Funda kwebe - Efesu 6 : 16 .
Kodwana nje ngiyalungiselela ngaphambi kokuthi ngiye esifundweni begodu ngilinge ukuphendula kabili namkha kathathu .
Nanje kusesebudisi kodwana ngizizwa kamnandi khulu nakhe ngaphendula .
Abafowethu nabodadwethu bayangikhuthaza tle !
Qobe nakuphela isifundo ngiyaqiniseka ukuthi uJehova uyangithanda . ”
Isihlangu esikhulu sokukholwa ( Qala iingaba 12 - 14 )
Funda kwebe - Efesu 6 : 17 .
Isikoporo sesindiso ( Qala iingaba 15 - 18 )
Ungayithuthukisa njani indlela olisebenzisa ngayo iBhayibheli ?
Ngitjhejile ukuthi esimini , abantu bayazimisela ukukulalela nababona ukuthi iBhayibheli uyalazi , uyalithanda bewenza koke okusemandlenakho ukubasiza . ”
Iyisabula yommoya ( Qala iingaba 19 - 20 )
UJehova angasisiza sibambelele ngokuqinileko ekukholweni kwethu begodu silwe noSathana .
Kodwana kubayini bekazizwa ngalendlela ?
Lo myalo wokuthoma nongomkhulu .
UJEHOVA UNGUMUPHI ONOMUSA .
IINGOMA : 72 , 119
Liyini ithando lobuzalwana ?
Kubayini kuqakathekile ukuragela phambili sitjengisa ithando lobuzalwana ?
Singalitjengisa njani ithando lobuzalwana ?
Kubayini uPowula atlolela amaKrestu wamaHebheru incwadi ?
( Funda amaHebheru 10 : 36 - 39 . )
Kubayini kufuze sibe nelulukelo encwadini yamaHebheru ?
Uthini umtlolo wonyaka ka - 2016 , begodu kubayini ufaneleka ?
AmaKrestu ayizwisisa njani ihlathululo yethando lobuzalwana ?
Sitlhoga ukwenzani ngaphambi kobana kuthome imihla yesizi ?
Akhe sihlole iindlelezo ezisithandathu .
Kutjho ukuthini ukwamukela abayeni ?
“ Ungalibali ukwamukela abayeni . ”
( Funda amaHebheru 13 : 2 . )
Singaba ‘ khumbulani njani ababotjhiweko ’ ?
“ Khumbulani labo ababotjhiweko . ”
( Funda amaHebheru 13 : 3 . )
Singayihlonipha njani imitjhadwethu ?
“ Ukuthathana akuhlonitjhwe ngibo boke . ”
( Funda amaHebheru 13 : 4 . )
Ukwaneliseka kusirhelebha njani ekutjengiseni ithando lobuzalwana ?
( Funda amaHebheru 13 : 5 . )
“ Ukuba nesibindi , ” kungasisiza njani sitjengise ithando lobuzalwana ?
Singaragela phambili ngayiphi indlela ekutjengiseni ithando lobuzalwana ?
IINGOMA : 121 , 63
Ithando lakaKrestu lisikhuthaza bona senzeni ?
Ithando lakaZimu lisikhuthaza bona senzeni ebazalwaneni bethu ?
Indlela uZimu alibalela ngayo kubayini kufuze isikhuthaze bona nathi silibalele abazalwana ?
( Funda 2 Korinte 1 : 20 . )
Ithando uKrestu asithande ngalo kufuze lisenze sizizwe njani ? Begodu lisibasela bona senzeni ?
Ngiliphi igandelelo esingaphasi kwalo ?
Ngimiphi imibuzo esingazibuza yona ngesikhathi sesiKhumbuzo ?
( Funda uLukasi 14 : 12 - 14 . )
Yini okufuze siyikhumbule ?
Ithando lakaZimu limrhelebhe njani uLily ukuthi abekezelele ubuthakathaka baka Carol ?
‘ Isipho [ sesihle ] esingahlathululekiko ! ’ uZimu asiphe sona , sizosibasela bona senzeni ?
IINGOMA : 109 , 108
Ngiziphi izehlakalo ezenza umnyanya wePentekoste waba ngoqakathekileko , begodu izehlakalwezo zakuzalisa njani okwakhulunywa miTlolo ?
Funda izEnzo 2 : 2 - 4 .
Sazi njani ukuthi abantu abakhethwa mumoya , abakhethwa ngendlela efanako ?
Khuyini emukelwa babantu boke abakhethwe nguZimu , begodu lokhu kuba namuphi umphumela kibo ?
Yeke ngaye siyabiza sithi : “ Aba , Baba ! ” : Umoya ngokwawo ufakazela ummoya wethu bonyana sibantwana bakaZimu . ’
Khuyini amaKrestu akhethiweko evane azibuze yona , kodwana khuyini ebenza bangangabazi ?
Umcabango womuntu okhethwe mumoya kaZimu utjhentjha njani , begodu yini ebangela itjhentjhwelo ?
Abantu abakhethiweko bazizwa njani nabasaphila ephasina ?
IINGOMA : 65 , 122
Umtlolo kaZakariya 8 : 23 uzaliseke njani ?
Kubayini singeze saqiniseka ukuthi bobani abazokuya ezulwini ?
Ngisiphi iseluleko abakhethiweko okufuze bacabangisise ngaso , begodu kubayini ?
Abakhethiweko kufuze baziqale njani ?
Yini abakhethiweko abangakayilindeli , begodu kubayini ?
Kubayini kufuze uyelele khulu ukuthi kufuze baphathwe njani labo abadlako esiKhumbuzweni ?
( Qala ibhoksi elithi “ Ithando ‘ Aliziphathi Ngendlela Engakafaneli . ’ ” )
UJesu wathi : “ Nina noke nje nibafo . ”
Sizivikela njani nange sibalekela ukuphathela abanye phezulu ?
Kubayini kungakafuzi sitshwenyeke ngesibalo salabo abadlako esiKhumbuzweni ?
“ [ UJehova ] uyabazi labo ekungebakhe . ”
IBhayibheli ithini ngesibalo sabakhethiweko abazabe basesesephasini nakuthoma iimbandezelo ezikulu ?
Yini okufuze siyizwisise ngabayi - 144 000 abakhethwe nguJehova ?
Ngekhulu lokuthoma ambalwa khulu amaKrestu akhethiweko asetjenziswa bona atlole imiTlolo yamaKrestu yesiGirigi .
Yini oyifundileko esihlokwenesi ?
IINGOMA : 75 , 74
kusitjhideza kuZimu nebazalwaneni ?
kuyasivikela ?
Ngitjho nanyana uJehova anguMninimandla woke nje , yini amela abantu bona bayenze ?
UJehova wamema u - Adamu bona enzeni , begodu kubayini enza njalo ?
Isibonelo salokho sisifumana lokha nakazakumema u - Adamu bona athiye iinlwana amagama .
Iinceku zakaZimu zasebenza njani naye ekuzaliseni ihloswakhe ?
Ngimuphi umsebenzi esingafaka isandla kiwo ? Inga - kghani uJehova bekangeze akghona ukwenza umsebenzi lo ngaphandle kwethu ?
Umpostoli uPowula watlola wathi , “ Njengombana sibambisene noZimu emsebenzini wakhe , siyanincenga bona ningamukeli umusa wakaZimu nidlale ngawo . ”
Izibulo lakaZimu lithini nalihlathulula indlela ebelizizwa ngayo nalisebenza noYise ?
Ngokufanako , uFranco , naye ulotjha uJehova ase - Italy , yena - ke uthi , “ UJehova usebenzisa iliZwi lakhe nomoyakhe bona asikhumbuze qobe langa ukuthi uyasithanda nokuthi koke esimenzela khona kuqakathekile kuye , ngitjho nanyana ngasikhathi thina sibona ngasuthi imizamwethu ayibonakali .
Ngikho - ke okwenza ngithabele ukusebenza noZimu bekunginikele ihloso yokuphila . ”
UJehova noJesu banobuhlobo obunjani , begodu kubayini ?
Sifunda bona kubayini kukuhlakanipha ukuthembela nokulandela uZimu .
Kubayini ephasini elitjha sizokutjhidelana noJehova besitjhidelane nabazalwana ?
Ukutjhumayela kusivikela njani ?
Ukutjhumayela kungirhelebha bona ngithobeke , kubuye kungenze ngikghone ukuthembela kuJehova nakubafowethu nabodadwethu . ”
Kubayini ukukghodlhelela nasitjhumayelako kutjengisa bona umoya kaZimu unathi ?
Uzokubekezela isikhathi esingangani emsebenzini onjalo ?
Ukutjhumayela kuhlangana njani nehloso kaZimu ngabantu ?
Ukutjhumayela kuhlangana njani nomyalo kaZimu omkhulu kunayo yoke ?
Wesibili ofana nawo ngothi : ‘ Thanda umakhelwanakho njengombana uzithanda wena . ’ ”
Akhuthi uyaqala bona kulilungelo elingangani ukwenza lokho uJehova athi sikwenze nokusebenza naye ! ”
Ababelethi bami bekubabantu abangazwani nesondo , kodwana batjela mina nabantwana bakwethu abayi - 7 bona siye esondweni .
Ngawavula , ngafunyana bona ibizo lakaZimu nguJehova .
Msinyazana ngemva kwalokho ngabelwa ukuraga isifundo sencwadi sebandla .
Ngabe ngamema umma nabantwana bakwethu , begodu boke beza .
Kwenzeka koke lokho nje , nakungubaba yena bekangakuthabeli nakancani lokho .
Ngemva kweemveke eembili ngaya ekhotho , umahluleli wathi , “ Ngokuya ngami bekufuze uthole isigwebo sokufela ejele . ”
Wabuye wathi “ Kghani kukhona ongakutjho ? ”
Ngazithela phezu kwendoda ede esidlakela nayo beyisibotjhwa , sajama sobabili sahlola ngaphandle efesidirini .
Wangibuza , “ Akhungitjele ukuthi ubotjhelweni . ”
Ngamphendula ngathi , “ NginguFakazi kaJehova . ”
Ngamphendula ngathi , “ AboFakazi bakaJehova abayi epini begodu ababulali nabantu . ”
Ngathi kuye , “ Awa . ”
Wabuye wathi , “ Iminyaka eyi - 15 yoke bengikwelinye ijele , lapho ngafunda ezinye iincwadi zenu . ”
Leyo bekuyindlelethu ehleliweko yokutjhumayela .
Ngaphendula ngathi , “ Kulungile kodwana angiyi epini . ”
Ngadzubhula umtlolo we - 2 Thimothi 2 : 3 , NW othi , “ Ngilijoni lakaKrestu . ”
Ingasikade ngemva kwalokho ngaya emhlanganweni wesifunda ebegade useCincinnati , e - Ohio .
Nabenza koke lokhu , boke bazokuhlala babangani bakaJehova .
Ngafunda isiTjhayina sesiMandarin , nangihlangana nabantu abakhuluma ilimeli endleleni ngithabela ukubatjhumayeza .
Evekeni elandelako umntazana loyo wanginikela ifowunakhe wathi kimi , “ Ukhuluma noChina . ”
Ngathi kuye , “ Akunamuntu engimaziko eTjhayina . ”
Sengibuyele eTjhayina . ”
Ngarareka ngathi , “ ETjhayina ? ”
Msinyazana ngemva kwalokho ngakhuluma nodadwabo likaKatie , okubuhlungu kukuthi lokho kwaba kokugcina ngikhuluma nabo .
Nakhibe uZimu ubone kukuhle , umndenami nabangani bami abahlongakalako bazokuvuka ephasini elitjha .
IINGOMA : 91 , 22
Izinto u - Abrahamu akhamba azibona epilweni nelwazi , zakwakha njani ukukholwa kwakhe ?
Yini u - Abrahamu akwenzako bona anzinzise isikhozi sakhe noZimu ?
Wena - ke ungamlingisa njani u - Abrahamu wakhe isikhozi sakho noJehova ?
Ngiyiphi indlela okungenzeka u - Abrahamu wafunda ngayo ngoJehova ? Ilwazelo lamenza wazizwa njani ?
Ilwazi .
Izinto u - Abrahamu akhamba ahlangabezana nazo zakuqinisa njani ukukholwa kwakhe ?
Izinto akhamba ahlangabezana nazo .
Singalifumana njani ilwazi elizokunzinzisa isikhozi sethu noJehova ?
Kubayini u - Abrahamu bekatshwenyekile ngokubhujiswa kweSodoma neGomora ?
Yini u - Abrahamu azoyithabela ePharadesi ?
Yini ozimisele ukuyenza ? Esihlokweni esilandelako sizokufunda ngani ?
Kwanga omunye nomunye kithi angazimisela ukulingisa isibonelo sokukholwa kwaka - Abrahamu .
( Funda amaHebheru 6 : 10 - 12 . )
Esihlokweni esilandelako sizokufunda ngeembonelo ezintathu zabantu abathembekako baba bangani abatjhidelene noZimu .
IINGOMA : 106 , 118
Sifundani esinganini uRute abanaso noZimu ?
Yini eyenza iKosi uHezekhiya yaba mkhozi kaJehova omkhulu
Bubuntu obunjani obenza uMariya ongunina likaJesu wabamkhozi kaJehova ?
( Funda uRute 2 : 12 . )
Khuyini engarhelebha labo abangabaza ukunikela uJehova ipilwabo ?
Akhuhlathulule indlela uHezekhiya akhuliswa ngayo .
( b ) Kubayini kungakafaneli sikwatele uZimu ?
( c ) Kubayini kungakafaneli sithi indlela esakhuliswa ngayo ngiyo esiquntela bona sizokuba lihlobo elinjani labantu ?
Inengi labantu abatjha lamukele iqiniso kungakhathaliseki bona likhuliswe ngendlela enjani ( Qala iingaba 9 , 10 )
Yini eyenza uHezekhiya waba yikosi ephuma phambili kwaJuda ?
( Funda 2 AmaKhosi 18 : 5 , 6 . )
Namhlanje abantu abanengi bakutjengise njani ukuthi babakhozi bakaJehova ?
Yini eyenza kubonakale ngasuthi umsebenzi uMariya anikelwa wona bewumkhandla , khonapho wasabela njani emezwini kaGabhariyeli ?
Ezehlakalwenezi zombili , uMariya walalela , wakhumbula , wakudlela amathambo wengqondo ebekakuzwile . — Funda uLukasi 2 : 16 - 19 , 49 , 51 .
Ngiziphi iindlela esingalingisa ngazo ukukholwa kwakaMariya ?
Kungenzeka bona kusukela ngelanga owabhajadiswa ngalo wafumana ithabo ekulotjheni uJehova .
Khumbula amezwi kaJesu athi , “ Yizani kimi noke nina enidiniweko nenidisibezekako , mina ngizaniphumuza .
Nakalandisako uthi , “ Khona bekungidanisa ukubona ipilo kanakwami ifadalala , nokumtlhogomela bekungasilula , kodwana akhenge ngikuvumele lokho kungenze ngingakuthabeli ukulotjha uZimu .
Ukwazi bona ngikoloda uJehova ipilwami owadala umuntu ngehloso , kwaba ngunobangelami wokuthi ngimthande ngehliziywami yoke nokuthi ngimlotjhe .
Ngilinga ngamandla ukuya esimini qobe , begodu angidinwa ukucabanga ngomBuso , lokho kungenza ngihlale ngithabile . ”
UJehova wasenzela umhlatjelo wesihlengo , ukwenzela bona sithabele ukuphila .
Kuliqiniso bona , “ Mbala uZimu walithanda kangaka iphasi , wabe wanikela ngeNdodanakhe ebelethwe yodwa , khona kuzakuthi loyo okholwa kiyo angabhubhi , kodwana abe nepilo engapheliko . ”
Yeke nganikela ipilwami kuJehova ngemva kobana ngisebenzele ikhamphani le iminyaka eyi - 28 , ngalisa umberego ngangenela umsebenzi wokutjhumayela isikhathi esinengi . ”
Usakhumbula na bona bowuphila ipilo enjani ngaphambi kobana wazi uJehova ?
Umpostoli uPowula wakhumbuza amaKrestu weRoma bona ‘ amakhoboka wesono ’ kodwana ngokukhamba kwesikhathi aba “ njengamakhoboka wokulunga . ”
Lokho kuthabisa kwamambala !
“ Kancanikancani ngathoma ukutjheja bona kunoBaba onguZimu onesirhawu . ”
Iminyaka ethabisa khulu engayiphilako ngile engiyiphile ngilotjha uJehova . ”
IINGOMA : 125 , 62
UJonathani indodana yeKosi uSawula yathembeka ngayiphi indlela kuJehova ?
Singahlala njani sithembekile kuZimu , ngitjho nanyana umuntu osegunyeni aziphatha ngendlela emenza singamhloniphi ?
Singathembeka njani kuJehova ngitjho nanyana abanye abantu bangasizwisisi nofana basiphatha makghwankghwa ?
Yini ebeyenza kube budisi esitjhabeni sakwa - Israyeli nakufuze sithembeke kuZimu ngesikhathi kusabusa ikosi uSawula ?
UJonathani bekamphatha njani uyise ?
Nasihlonipha abasemagunyeni sisuke sithembeka kuJehova ngayiphi indlela ?
( Funda kwebeRoma 13 : 1 , 2 . )
Ukuthanda kwethu uZimu kusisiza njani bona sihlale sithembekile kuye ?
Ukuthembeka kwethu kuZimu kungasirhelebha njani nasiqalene nemiraro yemindeni ?
USawula bekamphatha kumbi ngayiphi indlela uJonathani ?
Nange umzalwana angasiphathi ngokulingana , kufuze senzeni ?
Khuyini esiyifundileko esihlokwenesi ?
Ngubani okufuze sithembeke kuye ?
UJonathani noAbineri bebahluke ngani endleleni ebebaphatha ngayo uDavida ?
Ngibuphi ubuntu obungasirhelebha bona sithembeke kuZimu , begodu njani ?
Ngisiphi isifundo esisifunda emtjhaphweni ka - Abitjhayi ?
U - Anne wahlala njani athembekile ngaphasi kobujamo obubudisi ?
Yini esiyifunda ekulandiseni kweBhayibheli okumalungana no - Abineri , u - Absalomu noBharuku ?
Ungathembeka njani kuJehova , ebanganini neenhlobeni zakho ?
Kubayini uRhutjhayi bekufuze abe nesibindi ukuze athembeke kuZimu ?
Ngathandazela ukuthi ngibe nesibindi ukuze ngingawutjhugululi umkhumbulwami .
Kwanjesi nokho sebathambile , ngingabavakatjhela nanyana kunini . ” — Funda izAga 29 : 25 .
Yini oyifundileko esihlokwenesi ?
Yini - ke okufuze uyenze nakunjalo ?
Godu sisihlathululela ngemisebenzi ekufuze ivezwe kunyamezela kwethu .
IINGOMA : 86 , 54
Isibonelo sakaJafta nendodakazakhe singasirhelebha njani sibalekele umthelela wephasi ?
Ngiziphi iinkambiso zeBhayibheli ezingakurhelebha urarulule imirarwakho ?
Isihlokwesi sikukhuthaze njani ukuthi uzidele ngebanga lomBuso kaZimu ?
Ngisiphi isitjhijilo uJafta nendodakazakhe abaqalana naso ?
Kubayini isibonelo sakaJafta nendodakazakhe singaba lisizo kithi ?
Ngiziphi izinto okufuze sizigegede ephasineli , begodu yini okufuze siyenza ngalokho ?
UJafta wenza siphi isifungo , begodu lokho bekuhlanganisani ?
AbaKhokheli 11 : 35 basitjelani ngokukholwa kwakaJafta ?
Ngisiphi isifungo inengi lethu elasenza ? Singahlala njani sithembekile ?
IINGOMA : 135 , 139
Khuyini ezokurhelebha ukghodlhelele ?
Ngiziphi iimbonelo zokukghodlhelela esinazo ?
Kutjho ukuthini ukuvumela ‘ ukunyamezela kuveze imisebenzi ’ ?
Siqalene noSathana nephasi lakhe , ngapha siphila nesono .
( Funda uLukasi 21 : 19 . )
Kuyinto bani ukukghodlhelela ?
Yini engasirhelebha sikghodlhelele ?
Sikutjhwiso yini ukuthi ukukghodlhelela kukhuthazwa lithando ?
UJehova ‘ unguZimu wokubekezela newokukhuthazeka . ’
Ngitjho noJesu wakhe wazizwa njalo .
Kubayini kufuze sifunde ezintweni zalabo ‘ abanyamezelako ’ ?
Akusithi sodwa esikghodlhelelako .
Sifundani esibonelweni samakerubhi ebewagade e - Edeni ?
UJobho wakwazi njani ukghodlhelela iinlingo zakhe ?
( Funda kwebe 2 Korinte 1 : 6 . )
Banobudlelwana . ’ ​ — IZENZO 2 : 42 .
IINGOMA : 20 , 119
sizuza njani esifundweni .
sibarhelebha njani abanye nasiya esifundweni .
uJehova uzizwa njani nasiya esifundweni .
( Qala isithombe esisekuthomeni . ) ( b ) Sizokhe sicoce ngani esihlokwenesi ?
Imihlangano le beyikwakha ukukholwa kwethu . ”
Ukuya esifundweni kusikhuthaza njani bona sidzimelele kesikukholelwako ?
Ukuya esifundweni kuyasikhuthaza .
( Funda uJwanisi 10 : 16 . )
Ngitjho nanyana ngibulawa madolo , nginobulwele behliziyo , netjhukela nayo ayikazibeki phasi , kodwana nakuphela isifundo ngizizwa kamnandi khulu .
Umtjhinami wokuzwa wangirhelebha ukuzwa amaphimbo wabo boke ebebavuma , nami ngavuma nabo .
Ukuya esifundweni kusisiza njani bona sinikele uJehova okumfaneleko ?
Nasilalela isiyalo sakaJehova sokuthi siye esifundweni kutjho ukuthini lokho kuye ?
Nasisesifundweni sitjhidelana noJehova noJesu ngayiphi indlela ?
Nasiya esifundweni simtjengisa njani uJehova ukuthi sifuna ukumlalela ?
Nakukghonekako ngithanda ukuthi ngifike qangi eWolweni nakukhanjwako ngithanda ukuba ngowokugcina .
Umbethe usibusiso esivela kuJehova .
Isondo leZaragoza , eSpain ( ngesinceleni ) iBhayibheli etjhugululiweko ebizwa nge - Nácar - Colunga ( ngesidleni )
Ngikhumbula ngelinye ilanga ngithandaza ngithi , “ Ngiyakuthokoza Jehova ngokungibekezelela nokungipha amathuba wokufumana into ebengiyifuna — iqiniso leBhayibheli . ”
Ngambuza ngathi , “ UZimu yena uzokuthini ? ”
IINGOMA : 33 , 137
UJehova uzizwa njani ngemibuso yephaseli ?
Kufuze senze njani navane kuba budisi ukungazibandakanyi kwezepolotiki ?
Ungafundani eencekwini ezithembekileko ezingakhenge khezifake isandla kwezepolotiki ?
Singamhlonipha njani uZimu , khisibe nangapha sihlonipha aborhulumende babantu ?
Singakutjengisa njani ukungazibandakanyi kwethu kwezepolotiki ?
( b ) Kubayini kufuze sizibandule kusese nje ukungafaki isandla kwezepolotiki ?
Kufuze siziphathe njani iimphathiswa zakarhulumende ?
Yini okufuze sibalekele ukuyicabanga ?
Navane sekunyukela bona singafaki isandla kwezepolotiki , ‘ singahlakanipha ’ njani kodwana kube ngapha ‘ simsulwa ’ ?
( Funda uMatewu 10 : 16 , 17 . )
Yini okufuze siyiyelele nasikhuluma nabantu ?
Nawucoca nabantu .
Ukuthanda izinto zakanokutjho .
Yini esingayifunda nasicabangisisa ngabantu bakaZimu abangakhenge bazibandakanye kwezepolotiki ngitjho nalokha nabalingwako ?
( b ) Yini okufuze sizimisele ukuyenza ?
“ Ukucabangisisa ngomtlolo wezAga 27 : 11 , uMatewu 26 : 52 ; nowakaJwanisi 13 : 35 kwaqinisa ukukholwa kwami , yeke ngala ukuyokubandulelwa ubujoni .
Amavesi la angisiza nokuthi ngihlale nginomoya ophasi ngeekhathi ezibudisezi . ” — Kutjho u - Andriy , we - Ukraine .
“ Umtlolo ka - Isaya 2 : 4 wangisiza ekutheni ngingazibandakanyi kwezepolotiki ngitjho nebujamweni obubudisi .
“ Nibe nokuthula komunye nomunye . ” — MARKOSI 9 : 50 .
IINGOMA : 39 , 77
Ngisiphi isiyeleliso uJesu asipha sona nasiza endabeni yokulungisa ukungaboni ngelihlo linye ?
Ngimiphi imibuzo umKrestu angazibuza yona nakunomuntu agadangene naye amakhona ?
Amagadango amathathu akuMatewu 18 : 15 - 17 angaberegiswa njani ukurarulula imiraro ?
Ngiziphi izipi esifunda ngazo kuGenesisi , thina - ke singafundani kizo ?
Mhlobo bani wokucabanga okwarhatjheka ephasini , begodu umphumela walokho waba yini ?
UJesu wayala abafundi bakhe bona basabele njani nabahlangabezana nemiraro ?
6 , 7 . ( a ) Kubayini kuqakathekile ukulungisa msinyana ukungazwani ?
( b ) Ngimiphi imibuzo boke abantu bakaJehova abenza kuhle ukuthi bazibuze yona ?
UBabethu wezulwini uzowulalela umthandazo owenza ngokuthobeka loyo . — 1 Jwanisi 5 : 14 , 15 .
Kufuze senze njani nasilinyaziweko ?
( Funda izAga 10 : 12 ; 1 Pitrosi 4 : 8 . )
( a ) Udade othileko wasabela njani ekuthomeni abantu nabasola ukutjhumayela kwakhe ?
( b ) Ngimuphi umTlolo owamsiza waba nokuthula ?
11 , 12 . ( a ) UmKrestu kufuze asabele njani nakhibe umzalwana ‘ unamavundo naye ’ ?
“ Soke siyakhubeka . ”
Umbonisi omutjha wasabela njani emezwini alumelako , thina singafundani esibonelwenesi ?
14 , 15 . ( a ) Umtlolo kaMatewu 18 : 15 - 17 ungasebenza kibuphi ubujamo begodu njani ?
( b ) Ngiwaphi amagadango amathathu uJesu akhuluma ngawo , begodu nasiwalandelako umnqophwethu kufuze ube yini ?
Khuyini etjengisa ukuthi ukulandela isiyalo sakaJesu kulithando kithi ?
Ngiziphi iimbusiso esizozithokozela ‘ nasifuna ukuthula ’ nabanye abantu ?
IINGOMA : 141 , 97
yomlayezo abawutjhumayelako , nokuthi kubayini batjhumayela ?
yeendlela abazisebenzisako ?
yezinga lomsebenzabo ?
UMatewu 24 : 14 ubangela ukuthi kuphakame miphi imibuzo ?
Ngokuya ngokutlolwe kuMatewu 28 : 19 , 20 , ngiziphi izinto ezine okufanele abalandeli bakaJesu bazenze ?
Khuyini ebandakanyekako nasizakuba “ babambi babantu ” ?
Ngimiphi imibuzo emine etlhoga ukuphendulwa , begodu kubayini ?
Funda uLukasi 4 : 43 .
Sazi njani ukuthi abafundisi belobuKholwa abatjhumayeli umlayezo oliqiniso ?
Ngiyiphi ihloso engakalungi nakuziwa endabeni yokutjhumayela ?
( Funda IzEnzo 20 : 33 - 35 . )
Ngiziphi iindlela uJesu nabafundi bakhe abazisebenzisa nabatjhumayelako ?
Imizamo eyenziwa ngelobuKholwa nayimadaniswa nomsebenzi wokutjhumayela iindaba ezimnandi owenziwa babantu bakaJehova , kusuke kube namuphi umahluko ?
Sengibo bodwa abatjhumayela ngokuthi kusukela kwango - 1914 , uJesu wathoma ukuba yiKosi .
Umsebenzi lo kufuze wenziwe ngezinga elingangani ?
Sikubona ngani ukuthi aboFakazi bakaJehova bazalise isiphorofido sakaJesu ngezinga ebenze ngalo umsebenzabo ?
Izinzolwazi lethu lona lifumaneka ngamalimi angaphezu kwayi - 750 .
Sazi njani ukuthi aboFakazi bakaJehova banomoya kaZimu ?
17 , 18 . ( a ) Kubayini singaqiniseka ngokuthi aboFakazi bakaJehova ngibo abatjhumayela iindaba ezimnandi zomBuso namhlanjesi ?
( b ) Yini esenza sithi kungakghonakala ukuraga nomsebenzi lo ?
IINGOMA : 117 , 114
Yini engasibangela bona kube nala singazuzi khona eemfundiswe ezivela kuJehova ?
Ngiziphi iimbonelo ezingasirhelebha sizuze kizo zoke iimfundiso zeBhayibheli ?
Singazuza njani nasingafunda ngitjho neencwadi ezenzelwe ilutjha namkha abantu bemphakathini ?
1 , 2 . ( a ) AboFakazi bakaJehova bazizwa njani ngeBhayibheli ?
( b ) Wena - ke ngimuphi umtlolo weBhayibheli owuthandako ?
3 , 4 . ( a ) Sizizwa njani ngalokho uJehova asenzela khona ?
( b ) Phakathi neencwadi zethu esizifumanako , ngikuphi okhunye okwenzelwe abantu abathileko ?
Yini ethabisa uJehova ?
Kubayini kufuze sifunde iBhayibheli ngomkhumbulo ovulekileko ?
Nawufundako vula umkhumbulwakho .
Ngingabasiza njani abanye abantu ? ’
( b ) Singalisebenzisa njani ilwazelo ukuze sirhelebhe abanye ?
12 , 13 . ( a ) Nasisebenzisa koke uJehova asenzele khona , ngiliphi irhubhululo esingalenza ?
( b ) Iza nesibonelo sokuthi ilwazi elinabileko ngamavesi weBhayibheli lingasirhelebha njani bona sifunde iimfundo ezisithekileko .
Yatlolelwa kuphi begodu nini ?
Iincwadi ezitlolelwe abantu abatjha zingabasiza njani , abantu abakhulu abafunda iincwadezo bona zingabasiza njani ?
Kubayini abantu abadala nabo kufuze bazifunde iincwadi zabantu abatjha ?
Khuyini godu okuphethwe ziincwadi zabantu abatjha , begodu zingabasiza njani ?
( Funda uMtjhumayeli 12 : 1 , 13 . )
Ngingakwenza Kanjani Ukufunda IBhayibheli Kujabulise ? ”
Singafundani eencwadini ezenzelwe umphakathi ?
Singamtjengisa njani uJehova ukuthi siyakuthabela lokho asenzela khona ?
IINGOMA : 69 , 57
Iinqunto zethu zingasithinta njani thina nabanye abantu ?
Nange iBhayibheli ingakhulumi bunqopha ngomthetho othileko , singazi njani ukuthi iyini intando kaJehova ?
Singajayelana njani nendlela kaJehova yokucabanga ?
Iza nesibonelo seminye yemithetho efumaneka eBhayibhelini , begodu ukuyilalela kusisiza njani ?
2 , 3 . ( a ) Kubayini iBhayibheli lingasibekeli imithetho kizo zoke izinto ?
( b ) Sizokuphendula miphi imibuzo esihlokwenesi ?
Yini ezosisiza ukuze sithathe iinqunto ezivuthiweko ?
Nasifuna ukuthatha isiqunto ngendaba iBhayibheli engasibekeli umthetho ngayo , singazi njani ukuthi isiqunto esisithathako siyamthabisa uJehova ?
( Funda uMatewu 4 : 2 - 4 . )
Yini engasirhelebha bona sithathe iinqunto ezivuthiweko ?
Ngimiphi imibuzo ekufuze sizibuze yona nasifunda iBhayibheli ?
Iincwadi zethu nemihlangano kungasirhelebha njani sazi iindlela uJehova acabanga ngazo ?
Iza nesibonelo , esitjengisa ukuthi singasenza njani isiqunto esihlakaniphileko nasazi indlela uJehova acabanga ngayo .
( Funda uLukasi 18 : 29 , 30 . )
Yini engakurhelebha wazi ukuthi uJehova uzizwa njani ngendlela ombatha ngayo ?
( c ) Singazenza njani iinqunto ezivuthiweko ?
( Funda uGenesisi 6 : 5 , 6 . )
Nasithatha iinqunto ezivumelana nentando kaZimu , thina sizuza njani ?
Iqiniso kukuthi angeze saqeda ukufunda ngoJehova .
ekhaya ?
IINGOMA : 61 , 52
Kubayini kufuze sihlale senza amatjhentjho ngemva kokubhajadiswa ?
Kubayini uJehova afuna sihlule ubuthakathaka bethu ?
Yini ekufuze siyenze nasizakuvumela iliZwi lakaZimu liragele phambili litjhugulula ukuphila kwethu ?
1 - 3 . ( a ) Ngimaphi amatjhuguluko okungaba budisi ukuwenza ngemva kokubhajadiswa ?
( b ) Singazibuza miphi imibuzo nange kubudisi ukuhlula ubuthakathaka bethu ?
Kubayini sibhalelwa ukuthabisa uJehova ngaso soke isikhathi ?
6 , 7 . ( a ) Yini esenza bona sisole sibangani bakaJehova ngitjho nanyana sizizoni nje ?
( b ) Kubayini kufuze singasabi ukubawa ukulitjalelwa nguJehova ?
Yini thina okufuze siyenze nasizaku fumana isizo leliZwi lakaZimu , ngimiphi imibuzo esingazibuza yona ?
Kubayini uJehova angamane enze kube bulula bona sihlule imikhubethu emimbi ?
Ngimiphi imizamo esingayenza bona sibe nobuntu obuthandwa nguJehova ?
( Qala ibhoksi elithi “ IBhayibheli Nomthandazo Kwatjhugulula Amaphilwabo . ” )
Kubayini kufuze singazipheleli ihliziyo nasifumana bona kusese nezinto ezinengi okusafuze sizilungise ?
Singaqiniseka njani bona iBhayibheli linamandla wokutjhugulula ukuphila kwethu ?
[ 1 ] ( isigaba 1 ) Ibizo litjhugululiwe .
UMaria Victoria yena - ke bekamumuntu othanda ukuhleba .
URussell : “ Ngangithandaza kuJehova qobe ngapha ngihlala ngifunda iBhayibheli , lokho kwangirhelebha khulu .
Okhunye okwenza umahluko kuzindla ngomtlolo ka - 2 Pitrosi 2 : 11 neseluleko ebengisifumana kubadala naso senza umahluko omkhulu . ”
UMaria Victoria : “ Bengithandaza qobe kuJehova ngimbawa bona angirhelebhe ngikghone ukulawula indlela engikhuluma ngayo .
Ngabona ukuthi kungaba bhedere nanginga lisa nabangani abathanda ukuhleba .
Umtlolo weRhubo 64 : 2 - 5 [ 64 : 1 - 4 NW ] wona wangirhelebha ngabona ukuthi angifuni abantu bathandaze ngami babawe uJehova bona abavikele kimi .
Ngalemuka nothi ukuragela phambili nokuhleba kuzongenza ngibe sibonelo esimbi ebantwini begodu kuzokuhlazisa ibizo lakaJehova . ”
ULinda : “ Ngangifunda amaphetjhanami , ngenzela bona ngikghone ukuwakhambisela abantu .
Soke nje siyawenza amaphoso besilimaze nabanye abantu .
IINGOMA : 89 , 26
indlela uJehova akhetha ngayo labo azobabumba ?
isizathu uJehova abumba abantu bakhe ngaso ?
ukuthi uZimu ubabumba njani abantu abazithoba kuye ?
Khuyini eyenza uJehova abe Mbumbi ophuma phambili ?
Singasilingisa njani isibonelo sama - Israyeli aphendukako ?
UJehova ubakhetha njani labo abadosela kuye ?
( Funda 1 Samyela 16 : 7b . )
Indlela esimthemba ngayo uJehova njengoMbumbi wethu iwuthinta njani umbonwethu ( a ) ngabantu esibatjhumayezako ?
Kwathi nakukhamba isikhathi , kobunye ubujamo obuhlukileko ngazana nomndeni engawuhlonipha khulu ngebanga lezenzo zawo ezihle .
Laba linye ilanga ngazifumana ngibambe ongenzasi , umndeni loyo bewuboFakazi bakaJehova !
Ukuziphatha kwabo kwangitjhutjhumeza ngahlola iinsusa zami ezingenza ngibe nebandlululo .
Kungakabiphi besele ngibona ukuthi ubuntu bami bebusekelwe ekwenqiseleni izinto amehlo ngikholwe namahlebezi wezinto ezibozwangobatjho , amaphuzu ekungiwo ngiwo bengingawathatheli ehloko . ”
Khuyini ekwenza uthokoziswe siyalo sakaJehova ?
( Funda amaHebheru 12 : 5 , 6 , 11 . )
UJehova usifundisa njani namhlanjesi , begodu ifundiso le izokuthuthuka njani ngengomuso ?
UJesu wakwazi njani ukulingisa umusa namakghono woMbumbi omKhulu ?
( Funda iRhubo 103 : 10 - 14 . )
UDavida ufaniswa nomdaka othambileko ngayiphi indlela , thina - ke singamlingisa njani ?
UJehova ulisebenzisa njani ibandla lobuKrestu nomoya ocwengileko ukuze asibumbe ?
Nanyana anelawulo phezu komdaka , uJehova ubatjengisa njani abantu ukuthi uyalihlonipha ilungelo labo lokuzikhethela ?
Abafundi beBhayibheli bakutjengisa njani ukuthi bafuna uJehova ababumbe ?
( a ) Khuyini efika engqondwenakho nawucabanga ngoJehova njengoMbumbakho ?
( b ) Ngimiphi eminye imikhakha yokubumba esizokucoca ngayo ngokuzako ?
IINGOMA : 60 , 22
Ngiziphi iinqabo ezingenza kube budisi ukuthi silalele uJehova ?
Ngibuphi ubuntu obungasisiza sibumbeke esandleni sakaZimu ?
Ababelethi abamaKrestu bangatjengisa njani ukuthi uJehova uMbumbabo ?
Kubayini uZimu athi uDanyela ‘ mumuntu othandwa khulu ’ ? Thina - ke singalalela njani njengoDanyela ?
( Funda uJoromiya 18 : 6 . )
Ngimiphi imikghwa engasibangela bona sibe nehliziyo eqinileko ?
IzAga 4 : 23 zithi , “ Kikho koke okulondako , yelusa khulu ihliziywakho , ngombana imuthombo wokuphila . ”
( Funda 2 IinKronike 26 : 3 - 5 , 16 - 21 . )
Kungenzekani kithi nasisolo senza isono ?
7 , 8 . ( a ) Ama - Israyeli wekadeni ayitjengisa njani imiphumela yokungabi nokukholwa ?
( b ) Thina - ke sifundani kilokhu ?
Kubayini kufuze sinande ‘ sihlolisisa ’ ukukholwa kwethu begodu singakwenza njani lokho ?
Yini engasirhelebha sibe mdaka othambileko ezandleni zakaJehova ?
Ngibuphi ubuntu ukutjhumayela okusirhelebha bona sibe nabo , thina - ke sizuzani kilokho ?
Yini ababelethi ekufuze bayenze nabafuna ukubumba abantwana babo ?
Ababelethi kufuze batjengise njani ukuthi bathembele kuZimu nakwenzeka umntwanabo asuswe ekuhlanganyeleni ?
( Funda 1 Korinte 5 : 11 , 13 . )
Kubayini kufuze silalele uJehova , begodu lokho kuzosizuzisa ngani thina ?
IINGOMA : 138 , 112
UJehova unguZimu ‘ oyedwa ’ ngayiphi indlela ?
Singatjengisa njani ukuthi silotjha ‘ uJehova oyedwa ’ ?
Yini engasirhelebha ukuze sibulunge ukuthula nebumbano ?
( b ) UMosi wawatjhwelani ?
Uhlukile .
Amezwi athi ‘ [ uJehova ] yedwa ’ atjho ukuthini , begodu afezeke njani kuye ?
Uhlala athembekile .
8 , 9 . ( a ) Yini uJehova ayilindele ebantwini abamkhulekelako ?
( b ) UJesu wakugandelela njani ukuqakatheka kwamezwi kaMosi ?
( Funda uMarkosi 12 : 28 - 31 . )
10 , 11 . ( a ) Thina sizinikela kuJehova kwaphela ngayiphi indlela ?
( b ) Amasokana amaHebheru akutjengisa njani ukuthi azinikele kuJehova kwaphela ?
Nasifuna ukuzinikela kuJehova kwaphela , yini okufuze singayenzi ?
Yini esingathoma ukuyithanda ukudlula uJehova ?
Kubayini uPowula akhumbuza amaKrestu bona uZimu ‘ [ unguJehova ] oyedwa ’ ?
16 , 17 . ( a ) Ngisiphi isiphorofido esizalisekako emihlenethu le , begodu ube yini umphumela walokho ?
( b ) Yini engasiqedela ukuthula ?
18 , 19 . ( a ) Ngisiphi iseluleko esifumaneka kwebe - Efesu 4 : 1 - 3 ?
( b ) Yini esingayenza ukuze sibulunge ukuthula ebandleni ?
Singatjengisa njani ukuthi siyawazwisisa amezwi athi ‘ [ uJehova ] uZimethu [ nguJehova ] oyedwa ’ ?
ITrinidad neTobago zinamathreste amanengi asendaweni emagegana nelwandle .
Yeke aboFakazi bakaJehova kanengi basebenzisa ithubelo bacocisane nabathiyi beemfesi evane bahlangane nabo eendawenezo
IINGOMA : 121 , 75
Kubayini ihlangano kaZimu ikhetheke kangaka ?
IBhayibheli ikuveza njani ukuthi soke sinesono ?
Singabona senzeni ngemitjhaphwethu kunye neyabanye ?
IBhayibheli yakubikezela njani ukwanda kwabantu bakaJehova ?
Iinceku zakaZimu zilitjengise njani ithando lazo ?
( Funda uMikha 4 : 1 , 3 . )
Lokhu kubarhelebhe bahlala ‘ banganamlandu eengazini zabo boke abantu . ’ — IzEnzo 20 : 26 .
Khuyini eyenza ukwanda kwabantu bakaJehova kube yiqophamlando kangaka ?
Khuyini evane ibangele ukuthi ngasikhathi abanye basilimaze ?
( Funda kwebeRoma 5 : 12 , 19 . )
Ngathana bewuhlala kwa - Israyeli emihleni yokuphila kwaka - Eli namadodanakhe , bewuzokubona wenzeni ?
UDavida wonela uJehova ngezinga elingangani ?
( a ) Umpostoli uPitrosi wabhalelwa ngaliphi ukuthembeka emezwini awatjho ngomlomwakhe ?
( b ) Ngemva kokuphosisa okungaka kwakaPitrosi kubayini uJehova araga nokumsebenzisa ?
Yini ebeyizwisiswa nguJesu ngemitjhapho eyenziwa nguJuda Iskariyodi noPitrosi ?
Yathini iBhayibheli nayibikezela ngeenceku zakaJehova emalangeni la ?
Kufuze siwaqale njani amaphoso wabanye abantu ?
13 , 14 . ( a ) Kubayini kufuze sibekezelelane ?
( b ) Ngisiphi isithembiso okungakafuzi sisilibale ?
UJesu wathi kufanele senzeni abanye nabasiphosiselako ?
UJosefa waba sibonelo esihle ngaliphi ?
Uzimisele ukwenzani abanye nabakuphosiselako ?
( Funda uMatewu 5 : 23 , 24 . )

Ucabanga ukuthi vele bekufuze bathembeke na ?
Lokho singakubona kilokho okutjhiwo yiBhayibheli ngokuhlakanipha .
IzAga 3 : 13 - 15 zithi , “ Ubusisiwe umuntu ofunyana ubuhlakani , iye , umuntu ozuza ukuzwisisa , ngombana ingcono inzuzo yakhona kuneyesiliva , iye , imbuyiselo yakhona kuneyegolide .
Kuligugu ukudlula amaparele ; mbala akunalitho olifisako elingafana nakho . ”
Singathini - ke ngokuthembeka ?
Njengombana bengisikhulu ekhampanini le , mina bekufuze ngenze ‘ isivumelwano ’ nabantu bezomthelo ngibafumbathise .
Lokho kwenza bona ngaziwe njengomuntu ongakathembeki .
Ngisibonelo esihle ebasanyaneni bami ababili , begodu ngikghona nokuberegiswa ebandleni .
Ebantwini ababhadelisa umthelo nakilabo engiberegisana nabo ngaziwa njengomuntu othembekileko . ”
URute wafudukela kwa - Israyeli lapho ebekazokukghona ukulotjha khona uZimu weqiniso .
