Ho ba Sieo ha Bo - ntate ke Bothata , 9 / 8
Ke ’ nete hore maemo a leholimo le ho fetoha ha linako tsa selemo ho ama tsela eo re aparang ka eona .
’ Me o ile a ba bōpa e le hore ba ka phela ka ho sa feleng lefatšeng lena — haeba ba utloa melao ea hae .
Lino tse theolang boima ba ’ mele li fokotsa boima ka potlako , ka ntle ho mathata .
Moeta - pele oa Bajode Bar Kokhba o ile a ipaka e le Messia oa bohata , ka hore ka ntle ho katleho a etelle pele borabeleng khahlanong le Roma ka 132 C.E .
Hoseng ho hong ka Mantaha ho ella bofelong ba November ka 1984 , ke ile ka qeta nako e telele ke rapela , ke kōpa Molimo ka tieo hore a nthuse ho ba motho ea molemo le hore ke utloisise lintho tse etsahalang le ho utloisisa morero oa bophelo .
Lik’hamphani tse mamellang ho hleka - hlekoa ke ba batona kapa ba batšehali li ka ’ na tsa e - ba boimeng ba bahiruoa ba nang le moea o tlaase oa tšebetso , ho lofa haholo , ho se tsoe tema le lenane le phahameng la ba tlohelang mosebetsi — ho se ho sa thoe letho ka koluoa ea lichelete haeba bahlaseluoa ba bang ba etsa qeto ea ho qosa .
Ka mohlala , malapa a Bethele lefatšeng ka bophara a tsoha hoseng haholo hoseng ho hong le ho hong bakeng sa ho buisana ka temana ea letsatsi .
Le hoja a ile a utloa bohloko haholo ha a ne a sebetsana le ho ba molata , Nguyen oa lumela : “ Ke khotsofetse . ”
E mong oa bona e ne e le Shield Toutjian , eo e neng e le molebeli ea tsamaeang , ’ me o ile a nkhothatsa a ba a ntataisa moeeng ka nako eo ke neng ke hlile ke hloka khothatso .
Ho Lumellanya Saense le Bolumeli
Motsoal’a ka o ile a ngola : “ Re hlolloa ke mohlolo oa tsoalo le bophelo , ’ me re makala ka ho tšoanang ha o sa atlehe . ”
( a ) “ Maholimo ” le “ lefatše ” la batho tse tla felisoa haufinyane ke life ?
U ntse u phela , u sa na le ba heno le metsoalle . ”
Hape o ne a ruta toka , ’ me a etsa mohlala oa seo a se rutang ka ho khomarela se nepahetseng ka tsela e seng leeme , ho ea ka molao - motheo .
Ka hona monahano oa Bathessalonika ba bang o ne o hloka ho lokisoa .
Pafose , setsebi sa thuto ea bolumeli seo e bileng e leng moprista , se ile sa leka ho kholisa batho ba bararo ba fapaneng hore ba khaotse ho ithuta Bibele le Lipaki tsa Jehova .
Zauder e bolela hore “ sena ke se theiloeng lineanong , se sa ntse se le lefifing , ’ me ha se tšehetsoe ke bopaki ba bongaka kapa ba liphuputso . ”
Haeba ho joalo , na ke molato oa batho ?
Kabelo ea hae ea boromuoa e ile ea e - ba ofising ea lekala ea Mokhatlo oa Watch Tower ea Nigeria , ’ me re ile ra ngollana ka nako e itseng .
Empa joalokaha ho tlalehoa hore sebini sa ’ mino oa rap se tsejoang e le Ice - T se lumetse , se kenya mantsoe a tšosang lipineng tsa sona hore feela li fumane lebitso le joalo ; sena se tiisa hore li tla hohela batho ba ratang litaba .
Borapeli ba Jehova bo ne bo le sebakeng sefe bophelong ba ba tšepahalang ha Jesu a ne a le lefatšeng ?
Moholo o tla be a behela mohlape mohlala oa mofuta ofe haeba a sa natse melao ea Cesare ea sephethephethe kapa haeba a hlōleha ka boomo ho e boloka ? — 1 Petrose 5 : 3 .
Leha ho le joalo , kapele feela mobishopo oa Roma e K’hatholike oa Itu o ile a mo etela ’ me a mo bolella hore a re leleke , empa a ema a tiile , a re : “ Ha monna oa ka a e - shoa , ha lea ka la ntšelisa ka letho .
’ Muso oa leholimo oa Molimo matsohong a Kreste Jesu , “ Morena oa khotso , ” o tla etsa sena . — Esaia 9 : 6 ; Daniele 2 : 44 .
Mohlomong e ne e le motsoali oa motsoali oa hao , motsoali , molekane oa lenyalo , kapa ngoana .
Haeba li ne li ka tsoa kotsi , o ne a tlamella maqeba a tsona , mohlomong a li tlotsa ka oli e thobang .
Ka tsela eo , bana ba lōna ba tla hōla ba etsa seo le ha e se e le batho ba baholo .
Hoo e ka bang motho a le mong ho ba bararo ba Mongolia , ke bo - hloma - u - hlomole .
Bibele e beha taba tjena ka bonolo : “ Lerato lea haha . ”
Ke ka lebaka lena e leng eena feela ea bitsoang “ ea Matla ’ Ohle . ”
* Letsatsing leo litho tsa eona li ile tsa fuoa ka mohlolo tsebo ea ho bua ka maleme a sele , kahoo e li nolofalletsa ho bua le Bajode le basokolohi ba linaha tse ling ba neng ba tlile moketeng Jerusalema .
Jehova o tšoarela bo - mang ?
Ho e - na le hoo , joaloka Mikea , re lokela ho “ letela Molimo oa poloko ea [ rōna ] . ”
Ak’u nahane hape ka Judase Iskariota .
All photos : Courtesy and permission of Sultan Ibrahim Mbombo Njoya , Foumban , Cameroon
Jesu o hlahetse motseng oa Judea o bitsoang Bethlehema . Kosepele ea Luka e re : “ Naheng eona eo ho ne ho boetse ho e - na le balisa ba phelang naheng ’ me ba lebela mehlape ea bona bosiu . ”
Selemong sena , la 1 April le lumellana le la 14 Nisane , 33 C.E . , e leng letsatsi leo Jesu a ileng a shoa ka lona .
Ha Pauluse a ngola o re : “ Ke bolella e mong le e mong moo har’a lōna hore a se ke a inahana haholo ho feta kamoo ho hlokahalang ho nahana . ”
Jehova o mosa , ’ me le Mora oa hae o mosa .
Leha ho le joalo , ha rea lokela ho buella meriana kapa litlolo tsa letlalo pele ho liboka kapa ka mor’a tsona ha re le Holong ea ’ Muso kapa likopanong .
Ho lokela ho etsoa ho hong ho thibela ntoa e joalo hore e se qhome hape .
Ho na le lintho tse ngata tseo batsoali ba ka li etsang ho thusa bana ba bona hore ba lapele lintho tsa moea .
Ho e - na le hoo , hang - hang Molimo o ile a etsa litokisetso tsa hore a felise bokhopo le mahlomola .
Ho lelekoa ho etsoa ho sireletsa liithuti tse batlang ho rua molemo lenaneong la thuto ntle le ho hatelloa ka liketso tse mabifi .
Ka lebaka lena , ba bangata ba kenetse tšebeletso ea nako e tletseng , ’ me ba e etsa ka boitelo .
Lintho tsee tsohle li tla etsahala neng ?
A se a sa tsebe ho li thibela , o itihela betheng ea hae , a sisa pelo , “ Hobane’ng ha ke siuoa kamehla ? ”
Ka bokhutšoanyane , hlalosa se boleloang ke Baroma 8 : 15 - 17 .
E ne e e - na le beteri , seea - le - moea le microprocessor ( k’homphieutha e nyenyane ) .
Letsatsi la hae le tla fihla hantle ka nako ea lona , ka hora eo batho ba sa le lebellang ka eona . — Mareka 13 : 33 ; 2 Petrose 3 : 9 , 10 .
“ Ha se utloa hore ke Paki , sefahleho sa sona sa phutholoha ho se hokae .
Ak’u nahane feela a bua ka lentsoe le matla ’ me a nyefola lebotho la Iseraele hammoho le morena oa lona e leng Saule .
Li qoba ho phosumela lenyalong ka mohopolo o fosahetseng oa hore qeto ea ho hlala kapa ho arohana ea amoheleha haeba lenyalo le sa atlehe .
Leha ho le joalo , hamorao o ile a lumela hore molao oa Russia ha o qobelle baahi hore ba keteke Keresemese .
Thoto e Lahlehang
Ka hona ba sebeletsang e le baholo ba phutheho kajeno ba tlameha ho qoba ho lumella setsoalle kapa likamano tsa lelapa ho khopamisa kahlolo ea bona .
Eaba o letsetsa ofisi ea Mokhatlo e Brooklyn , ’ me ’ na le mosali oa ka re ile ra laeloa ho tsoa hape letsatsing lona leo ka liplakate le limemo ho fana ka motheo oa bopaki ba nyeoe ea tlhahlobo .
KAROLELANO EA BAHOELETSI BA BO - PULA - MALIBOHO : 1 780
Le hoja buka ena ea boitsebiso e tsoela pele ho nyenyefatsa linnete tsena ’ me e bolela hore thuto ea Boraro - bo - bong e ne e amoheloa nakong eo ea pele , linnete li hanana li seo .
Ba bonahala ba itšepa haholonyane ho mpheta . ” — Alex .
Katleho e khōlō e hlahisoa ke ho beha mabaka ka tsela e sebelisang lekhotsa , ‘ hakaakang , ’ eo Jesu a neng a e sebelisa nako le nako .
“ Rerang esale pele .
Ka July 1953 , re ile ra lumelisa baromuoa ba makholo ba neng ba tlile kopanong ea machaba New York City , ba e - tsoa linaheng tse ling .
Ho hlakile hore lipheo lia fapana .
Ho pholletsa le Mehla e Bohareng , Kereke ea Roma e K’hatholike e ile ea itlhahisa e le bona bolumeli ba ’ nete .
Ke eng e ileng ea etsa hore u ipotse ka morero oa bophelo ?
Sena se boetse sea sebetsa haeba nakong e tlang motho e mong a se a sa tšoanelehe hore e ka ba mohoeletsi ea sa kolobetsoang ’ me hamorao a bontša pako .
Ho boetse ho loketse ho hlompha liqeto tsa boahloli tsa baholo .
[ Liketso 9 : 36 - 39 ] ) Ka ho hlakileng , ho etsa sena ha ho amane le litumelo tsa bohata , ba bang ho Lipaki tsa Jehova ba tloaetse ho fana ka lipalesa tse hlasimollang ho motsoalle ea kulang kapa ea hlahetsoeng ke lefu .
Jesu o ile a bontša hore ho ne ho tla ba joalo , ho pholletsa “ ho fihlela qetellong ea tsamaiso ea lintho . ”
Ho feta moo , tšepo — joaloka tšepo ea ho pholoha ‘ mahlomoleng a maholo ’ ho kena lefatšeng le lecha — ea fela ha se neng se tšepiloe se phethahala .
Leha ho le joalo , ho thoe’ng haeba re ne re mo tšoaea liphoso ka lebaka la mefokolo ea hae kapa re mo bapisa hampe le ba bang ba kileng ba etela phutheho ea rōna pele ?
Hobane o ne a e - na le tumelo e matla ho Jehova .
Kaha ke thato ea Molimo hore “ batho ba mefuta eohle ba pholohe ’ me ba fihle tsebong e nepahetseng ea ’ nete , ” basebeletsi bana ba etsa boiteko bo matla ba ho etela batho ba libakeng tseo ho leng thata ho li finyella ka molaetsa o fanang ka bophelo o tsoang Bibeleng .
Leha ho le joalo , bamameli ba ne ba sa tsebe hore ho ile ha e - ba le mathata .
La 24 - 30 January , 2011
Ho fapana le ho lahla lintho tsa gauda tse senyehileng , batei ba gauda ba sebelisa thepa eo ea bohlokoahali hape ho etsa mosebetsi o mocha oa botsebi hobane gauda ha e lahleheloe ke bohlokoa ba eona .
Empa haeba re potlakela ho tšoarela ba bang re bile re ba etsetsa lintho tse molemo ho ka rena khotso har’a rōna ’ me Jehova a ka re hlohonolofatsa .
Li thusa ho felisa masoabi . ”
O ile a oeloa ke koluoa ha mosali oa hae a ne a hlokahala ka tšohanyetso .
Joalokaha mongolo o tlaase ho leqephe o bontša , Codex W , hammoho le buka ea loli ea Chester Beatty ( P ) le buka ea loli ea Bodmer ( P ) , tseo e leng tsa lekholong la boraro la lilemo C.E . , e lumellana le ho fetoleloa hona ho qetellang .
Tsela ea ho Hlōla ho Nyahama
Jesu o phethela setšoantšo sa hae ka ho re : “ Hobane ba bitsoang ba bangata , empa ba khethiloeng ha ba bakae . ”
Buka ea boitsebiso ea Prostanta e hlalosa lihele e le “ sebaka sa tlhokofatso ea ka moso bakeng sa ba khopo . ”
Mor’abo rōna Mantz o ile a re : “ Ba tseba tsela ea ho buisana le bahoebi ba sebakeng seo ka litheolelo .
Bibele e na le bopaki ba hore mehleng ea baapostola , barutuoa ba sa tsoa latela Jesu ba ne ba utloisisa bohlokoa ba kolobetso .
Khasong ea thelevishene ea NOVA , Stephen Jay Gould o itse thuto ea mahlale “ hangata e bontša leeme le leholo la ba etsang mosebetsi . ”
Haeba u fumana hore ho na le chelete e ngata haholo e tsoang ho feta e kenang , talima litšenyehelo tsa hao e le hore u fumane motso oa bothata .
Mosebetsi oo oa liphallelo o ile oa hlophisoa joang ?
◆ Ke linotlolo life tseo Petrose a li filoeng , ’ me li sebelisitsoe joang ?
Ke hobane’ng ha Bibele e le buka eo batho ba bangata ba sa e tsebeng , ’ me see se re hlahisetsa phephetso efe ?
Haufinyane ba tla lokela ho kotula litholoana tsa boetsalibe ba bona .
Ho Hlōloa Khanyetso ea Baruti
Phello e ile ea e - ba efe ha liphutheho tsa lekholong la pele la lilemo li mamela melao - taelo e fanoeng ke sehlopha se busang ?
Ponton o bolela hore ka sebele “ ho phahama , ho tsoela pele le ho oa ha Soviet Union ” e bile “ e ’ ngoe ea liketsahalo tse hapang tlhokomelo ka ho fetisisa lekholong la mashome a mabeli la lilemo . ”
“ Bontšanang Kamohelo ea Baeti , ” 1 / 15
Maemo ana a akarelletsa ho phela hantle ’ meleng ; mosebetsi o nang le morero ; lijo tse lekaneng , bolulo le liaparo ; ho khotsofatsa takatso ea ho qapa lintho ; le metsoalle ea sebele .
Jehova , ea matla , o kōpuoa hore a bontše mosa o lerato , kapa lerato le tšepahalang ho ea hlokang , e leng Davida .
Na Kathleen o ne a tla khona ho tlohela lithethefatsi ha a se a sa tšabe hore o tla cha liheleng ?
Ka nako ea Jehova e loketseng , lipotso tsa rōna kaofela li tla arajoa ka mokhoa o khotsofatsang ka ho feletseng .
Hape ke phephetso ho qoba lintho tse fetelletseng le ho boloka botsitso kelellong le maikutlong . — Ba - Efese 5 : 17 , NW ; 1 Timothea 4 : 8 ; 1 Petrose 1 : 13 .
Ba bang ba ne ba bile ba seba Pauluse , ’ me tsena tsohle o ne a li utloa . — 2 Ba - Korinthe 10 : 10 .
Chase , e leng Letona la Tsa Lichelete o ile a ngola a re : “ Ha ho sechaba se ka bang matla haeba Molimo a sa se fe matla , kapa se ka sireletsehang haeba A sa se sireletse .
26 Ngoana ea Bileng le Tumelo
Tseo ke lintho tseo ke neng ke atisa ho leka ho li hatisa ho liithuti ha li le Gileade .
Ea pele , e tiisa hore ba na le lintho tseo ba li hlokang e leng lijo , liaparo le bolulo .
Lilemong tsa bo - 1990 , libetsa tse joalo li ile tsa bolaea batho ba fetang limilione tse ’ nè .
Na thuto ea Jesu ea ho beha Molimo pele bophelong ba rōna e sa sebetsa le kajeno , ha batho ba bangata hakaale ba lumela hore chelete e rarolla mathata ’ ohle ?
Empa ha Belgium le Jeremane li simolla bora , sena se ile sa potlakisa lintho .
Ho phaella moo , The Times e tlaleha hore tšilafalo ea moea e “ phahame ka makhetlo a 70 ka matlong ho feta kantle . ”
Tsela eo re nahanang ka eona e ka re thusa ho amohela boemo , esita le haeba e se boo re neng re bo lebeletse .
Linaheng tse ngata tsa Latin America , neano e hloka hore balumeli ba likete - kete ba phuthehele litšeng tsa mabitla ’ me ba etse lithapelo tse ngotsoeng ’ me ba fe bafu babona limpho .
Joalokaha motho a shoa , phoofolo e shoa ka mokhoa o tšoanang ; kaofela ba na le moea o le mong , hoo motho a sa phahamang ho feta phoofolo , kaha ntho e ’ ngoe le e ’ ngoe ke lefeela .
O ile a ngola : “ E mong le e mong ea noang lebese ha aa tloaelana le lentsoe la ho loka , kaha ke ngoana .
Jehova o lekanyetsa ba tla pholoha mahlomola a maholo motheong ofe ?
Kahoo , seo Alan a lokelang ho ipotsa sona ke hore , ‘ Haeba ke ne ke le mor’abo rōna eo , ke ne nka rata hore batho ba etse’ng le ’ na ? ’
Lipaki tsa Jehova li ile tsa lokisetsa libaka tsa botho tse 22 000 tsa ho robala bakeng sa baeti , tsa hlokomela bolulo bakeng sa baahi ba Soviet Union ’ me li ne li na le lefapha la tsona la meriana . ”
Ena ke teko e khōlō ea botšepehi , haholo - holo litsong tseo ho tsona ho hleka - hleka ka likamano tsa botona le botšehali , tšenyeho le ho hloka botšepehi li khothalletsoang kapa li lumelloang .
Haeba re haha ka tsela eo lerato la Kreste le tlang ho hōla lipelong tsa liithuti tsa rōna ka eona , ho hlakile hore sena se tla haha lerato ho Jehova Molimo .
Ho bala e ka ba habohlokoa mohatong ona .
Lithapelo tsa mofuta oo li senola hore na re batho ba mofuta ofe le hore na re nka bara le barali babo rōna joang .
400 ° C → MESALETSA E boetse e ea hloekisoa ho
Hangata ke nakong eo ho qalehang lekhalo le thibelang kamano ea batsoali le bana ; ke seoelo lekhalo leo le emelang ha ba kena lilemong tsa bocha .
Eaba o tsoela pele ho re ho eena : ‘ Peō ea hao e tla ba joalo . ’ ”
Monokotšoai ona , o oelang lelapeng la cranberry , o atile haholo Finland le Sweden .
Nakoana ka mor’a hore ’ Muso o tsoaloe ka 1914 , batlotsuoa bohle ba tšepahalang ba robetseng lefung , ba ile ba tsosetsoa ho ea phela leholimong moo ba tla busa le Jesu . — Tšen .
Empa Jehova o ile a bona hore re ka khona ho ba ba lokileng .
Khopolo e kotsi ea lefatše e se ke ea u susumelletsa ho nahana hore ho na le se phoso ka uena haeba u tšoarella litekanyetsong tsa Bibele .
Molimo o ne o tla lokela hore o hlokomolohe litekanyetso tsa oona tse lokileng , hore o etse toka ea oona ea molao lefeela ha o ne o ka tšoarela boetsalibe ba batho !
Joale ke ile ka hopola hore ha ke le tlelaseng ea filosofi univesithing eo ke neng ke le ho eona Russia , re ile ra bolelloa hore Lipaki ke lequloana le hore li ne li etsa mahlabelo ka bana ebe li noa mali a bona .
Ho tšaba Molimo ho lokela ho re susumelletsa ho ba baboleli ba chesehang ba molaetsa oa ’ Muso .
Jesu o re ho rōna : “ Kotulo ke qetello ea tsamaiso ea lintho , ’ me bakotuli ke mangeloi . ”
Seo se re kholisa hore e tla ba eng kapa eng e hlokahalang hore a phethe litšepiso tsa hae .
“ Hore ba phelang ba se hlole ba iphelela , ba mpe ba phelele ea shoeleng , . . . bakeng sa bona . ” — 2 BAKORINTHE 5 : 15 .
Jehova o Nka Bonolo e le ba Bohlokoa
Leha mocha oa Mokreste a hlokomela hore bokoetliso ba ’ mele bo molemo hanyenyane , ho phahamisa litšepe ho ka tlatsetsa ’ meleng o phetseng hantle .
Ka hona Bokreste ke bolumeli bo hlomphang ba hōlileng .
Kahoo , basali ba bangata ha ba itekanya lieta ba fumana hore haeba li ba lekana hantle menoaneng , liretheng lia khoehla ; empa haeba li ba lekana hantle liretheng , li ba tiisa menoaneng .
Na ba ne ba beola litelu feela ?
Ntle le pefo e amanang le ntoa , ho na le e amanang le lipapali , lithethefatsi , lihlopha tsa litlokotsebe , sekolo le mosebetsi , hammoho le e amanang le boithabiso .
Ke ne ke e - na le barab’abo rōna ba bang ba tsoang likarolong tse ling tsa lefatše , re letile sebakeng seo litho tsa Sehlopha se Busang li tšoarelang seboka ho sona .
Ha ho mantsoe a thoriso ao ho ka thoeng a phahame haholo ha ho rokoa Jehova !
“ Boprofeta ” ba hae bo ile ba iketsa eka bo fana ka matla a ho iketsetsa liqeto le tokoloho ho Molimo .
LILEMONG tse fetang 3 000 tse fetileng , mopatriareka Jobo o ile a hlokomela hore linonyana tsa leholimo li ka ruta motho lintho tse ngata ka mesebetsi ea Molimo .
◇ U se ke ua sebelisa litepisi tsa lere ho tšehetsa mapolanka ao u sebeletsang ho ’ ona .
Joalokaha mopesaleme Davida a boletse , “ khopotso ea Jehova ea tšepahala , e hlalefisa ea se nang phihlelo . ”
Tiiso ena eo ho bonahalang ho le thata ho e lumela e tlalehiloe ho 1 Johanne 5 : 14 , NW .
Mosali e mong o ile a tletleba , a re : “ Ke ikutloa joaloka motho ea hlaliloeng le hoja ke ntse ke nyetsoe .
Ntho e utloiloeng le eona e teng ka lentsoe le mabapi le Kreste . ” — Baroma 10 : 17 .
Ke ne ke qhaqhasela , ke thothomela .
Lerato le bonngoe tse teng ka har’a phutheho ea Bokreste li ile tsa ba le tšusumetso e matla lelapeng la rōna .
U ka Tsamaea le Molimo Joang Hona e le ka Lebaka Lefe ?
‘ Na ke Tla Etsa Ntho e Tšoanang ? ’
Tšepiso ea Molimo ea ho felisa ntoa e tla phethahatsoa joang ?
Ka tsela e tšoanang , rōna joaloka Bakreste re ka inka re le basebetsi ba bacha .
Lintho tse phelang li na le litšobotsi tse ngata tse fanang ka bopaki ba hore ho bile le ponelo - pele le morero — sesupo sa hore ho na le ea bohlale ea li rerileng .
EMPA e ka ’ na ea e - ba ho fapaneng ha u qeta nako e telele u sebetsana le boemo bo u imelang kelellong .
“ E le hore . . . ba ka haptjoa [ kapa ba ruuoa ] ka ntle ho lentsoe ka boitšoaro ba basali ba bona . ”
Lihlopha tsa bolumeli tsa Maprostanta tse ileng tsa hlaha ka lebaka la Phetoho li ile tsa boloka lithuto tse ngata tseo eseng tsa mangolo .
Empa ho hlokahala ho leka - lekana .
Kantle ho lekholo la bo20 la lilemo , ha ho e - s’o be le nako e ’ ngoe historing eo ka eona batho ba bangata tjena ba kileng ba ameha litlokotsing tse ngata hakana tse sisinyang lefatše ka nako e lekanang le eo .
O ile a re : “ Ke phasele ea eng ? ”
Mafelo - beke , re na le liboka le tšebeletso ea tšimo eo re sa rateng ho e fosa .
’ Me joalokaha lentsoe la Molimo le boleloa ka phuthehong esita le “ nakong e likhathatso , ” ka tsela e tšoanang re phehella ho bolela lentsoe tšimong esita le maemong a thata . — 1 Bathesalonika 1 : 6 .
Ha ba leke ho laola banna ’ me ha ba eke barab’abo bona ka bohlola ba moea kapa ba nama .
Ka mohlala , Moscow ba bileng teng Sehopotsong selemong sena ba ne ba le 7 549 , ha ho bapisoa le ba bileng teng selemong se fetileng ba 3 500 .
PHUTHEHO ea Bokreste e ile ea hōla ho tloha ho litho tse batlileng ho ba 120 ho ea ho tse ka holimo ho 3 000 ka mor’a lihoranyana e theiloe .
Joalokaha ho boletse Polytimi Venetsianos
Ka ho fetola litloaelo tsa hae , ho ntlafatsa tikoloho ea hae le ho ntlafatsa tlhokomelo ea hae ea meriana , ka sebele motho o khonne ho eketsa nako e tloaelehileng ea bophelo le nako eo a lebeletsoeng ho e phela .
Stanfield / NGS Image Collection
Ka 1961 bafetoleli ba ile ba qala ho fetolela Phetolelo ea Lefatše le Lecha ea Senyesemane ka lipuo tse ling .
Ba neng ba fana ka ’ ona e ne e le Maafrika .
O ile a feta maemong a mangata a thabisang tšebeletsong ea Molimo .
Leha ho le joalo , ka mor’a lilemo tse 70 ka mosa Molimo o ile oa khutlisetsa masala a tšepahalang a Baiseraele lefatšeng la oona .
Setšoantšong sa Mosamaria ea Molemo , o hlalositse ka ho hlakileng se boleloang ke lerato la moahisani , e leng ho bontša thahasello e hlokang boithati boiketlong ba batho ba bang . — Luka 10 : 29 - 37 .
Ka sebele Davida o ne a fositse pakane .
Re tseba joang hore bolumeli bo nepahetseng bo etsa sona seo ?
Leha ho le joalo , kaha ho ne ho se mohla a kileng a sebetsana le Lipaki tsa Jehova , a ile a hlolloa !
Ha u ntse u tsoela pele , u tla khona ho ja seo moapostola Pauluse a se bitsitseng “ lijo tse tiileng ” — ke hore , linnete tse tebileng haholo .
Ke hlompha litho tse ling tsa Komiti ea Lekala ebile ke li ananela haholo .
Ha li kopana le batho ba hlokofalitsoeng , Lipaki li leka ho abela batho bana tšepiso ea Bibele ea bokamoso bo khanyang .
‘ Bo Tsoa Lichabeng Tsohle , Melokong Eohle , Mefuteng Eohle ea Batho le Malemeng ’ Ohle ’
Mofumahali e mong o ile a re hoeletsa , ‘ Ke eng eo le e etsang bakeng sa mosebetsi oa ntoa ? ’
Lihloohong tse latelang ho tla sebelisoa Bibele ea Mak’hatholike le ea Maprostanta ho arabela lipotso tsena tse tharo : ( 1 ) Ha e le hantle ke’ng se etsahalang ha motho a e - shoa ?
Hore na Areka eo e ne e ile ea tlosoa ke morena e mong ea khopo pejana ho moo kapa hore na Josiase o ne a ile a e isa sebakeng se seng hore e bolokoe teng ha ho ntse ho etsoa mosebetsi o moholo oa ho lokisa tempele , Bibele ha e bolele .
Le bua joang ?
Hopola hore ba ‘ jalang haholo le hona ba tla kotula haholo . ’
Ka ho khetheha Moeklesia 3 : 7 ea sebetsa ha beng ka motho ba hanyetsa .
( a ) Ke hobane’ng ha tšabo ea Petrose bosiung ba ho tšoaroa ha Jesu e sa ka ea mo etsa hore e be oa “ mofuta o ikhulang ” ?
Libokeng tsena ho ea motho e mong le e mong .
LENGOLO le latelang le ea ho Santa Claus le tšoana le a mangata a ngotsoeng ke bana ’ me a filoe batsoali le matichere ka tšepiso ea hore mangolo ao a tla romeloa Ntlheng e ka Leboea ea Lefatše :
Ba bangata ba na le tšabo ea hore ho joalo .
Tse likete li ile tsa shoa li tšepahala — tse ling tsa bolaoa , tse ling ke ho kula le ho se je hantle .
Taba eo ho buuoang ka eona ke pula e nang le metsoako e chefu , e silafatsang matša le linōka ’ me e thusa ho bolaea lifate tse limillione .
Ho e - na le hoo , ho itšetlehile ka hore na re batho ba mofuta ofe — kamoo re nahanang , seo re se etsang , kamoo re tšoarang ba bang , kamoo re phelang bophelo ba rōna ka teng .
E ne e le tlamo ho etsa lintho tsena , empa leha ho le joalo eseng hore ho hlokomolohuoe lintho tse ling . ” — Matheu 23 : 23 .
Ha ho fuoa batho ba 10 000 lijo , ho tšoana feela le taba ea ho nehelana ka mahobe a se makae le litlhapi .
Liphetoho tseo ke ileng ka li etsa boitšoarong ba ka li ile tsa susumelletsa batsoali ba ka hore ba ithute Bibele .
Ho Lokolloa le ho Fallela Kazakhstan
Mohlomong u tseba tlaleho eo ea histori .
Kaha e se e le mafutsana , ha ho seo ba ka se etsang ntle le haeba motho e mong ea mosa le ea ruileng a ka reka banka eo eaba o ba khutlisetsa lichelete tsa bona , ’ me o ba ntša sekolotong .
Ke ho sebelisa tokoloho ea Bokreste hampe hakaakang !
Ka 1985 ho ile ha khantšoa leseli tabeng ea hore na ho bolela eng hore motho a boleloe a lokile “ bakeng sa bophelo ” le hore a boleloe a lokile hore ke motsoalle oa Molimo .
Moaborigine oa Australia , Moafrika ea lumelang hore moea o arohane le ’ mele , Moshinto , esita le Mobuddha , kaofela ba ruta lintho tse sa tšoaneng sehloohong sena se tšoanang .
Jesu o ile a nahana ka melemo e larileng ka pele , ’ me habohlokoa le ho feta , a lemoha hore o kenya letsoho ho halaletseng lebitso la Molimo le ho tšehetseng bobusi ba hae .
Ka bomalimabe ha baa ka ba mamela . — Genese 2 : 17 ; 3 : 6 .
Ke hobane’ng ha motho ea ratang chelete a ke ke a thaba ?
Na ho ne ho ke ke ha bontša boikhabi bo fetelletseng ?
Moahloli e mong oa lekhotla le lenyenyane la molao Massachusetts o ile bohōleng ba ho ahlola ka hore ha ntate a etile “ ha a lokela ho bala Bibele le bana kapa ho ba isa litšebeletsong tsa kereke ( kapa ho ba balla Melao e Leshome ) . ”
Waltraud o ile a tlameha ho tloha naheng eo a neng a lula ho eona eaba o fallela naheng e ’ ngoe Afrika ka lebaka la ntoa .
◆ Barutuoa ba qophella ka eng ha e e - ba mantsiboea , empa ke joang Jesu a hlokomelang batho ?
Satane o sebelisa mekhoa efe kajeno ho leka ho kholisa batho hore hase ba bohlokoa ebile ha ba ratoe ?
Ka sebele , ho ananela lerato le tebileng leo Molimo le Kreste ba re bontšitseng lona ho ile ha re qobella hore re nehele bophelo ba rōna ho Molimo le ho ba barutuoa ba Kreste . — Johanne 3 : 16 ; 1 Johanne 4 : 10 , 11 .
Emily : “ Ke ile ka beha fereko fatše kaha ke ne ke sa ikutloe hantle .
Afrika , Asia , le libakeng tse ling , matla a tlhaho , liphoofolo , le batho kapa lintho tse ling tse bonoang , li rapeloa joaloka melimo .
Ke Satane Diabolose . — Tšenolo 12 : 9 .
Ka mor’a nakoana ke ile ka tenoa ke bophelo ba Lagos ’ me ka 1981 , ke ile ka fallela London .
Lintho tsena li ka etsahala hobane ha rea phethahala .
Haeba re utloisoa bohloko ke ho ba liphofu tsa ho hloka toka , re ka leboha hore ebe boholo ba tsamaiso ea boahloli bo na le mecha ea molao e ka ’ nang ea re nolofalletsa ho lokisa boemo bona .
Na nka khona ho kopanela tšebeletsong ee ?
Moeletsi oa lelapa Judith McCleese o re : “ Hase motsoalle e mong le e mong eo e tla ba oa hlooho ea khomo .
28 Bophelo ba Mehleng ea Bibele — Sehoai
Ba ikutloa ka tsela e tšoanang le ea Mopesaleme ea ileng a re : “ Molao oa hao ke o rata hakaakang !
Sarajevo
Kaha marabele a ne a lebeletse hore masole a tla a hlasela , a ile a itokisetsa ka hloko hore a tle a itšireletse .
Ka holimo ho tsohle , hobane Jehova — ea fanang ka “ limpho tseo e leng banna ” — ke Molimo ea qenehelang .
Pauluse o ile a bua ho fihlela ka khitla .
Ke tletse khauta Afrika , empa bakeng sa khauta , ke fumane litaemane . ”
Ho e - na le hoo , e le ha a beha tumelo e felletseng ho Jehova Molimo , o ile a bua ka menyetla ea hae ea pele , a re : “ Ke lebala tse ka morao , ’ me ke hahamalla ho tse ka pele ; ke titimela moo ho lekanntsoeng teng , e leng pheo eo re e biletsoang holimo ke Molimo , ka Jesu Kreste . ”
Ho ile ha boela ha hahoa libaka tseo ho tsona ho shejoang lintho tse sepakapakeng metseng e meng e mengata e Bochabela bo Hare .
Ke ne ke khahliloe ke Sri Lanka , kahoo ke ile ka khutlela teng ka December 1999 , lekhetlong lena ke e - na le mohats’a ka .
O re : “ Kea leboha hore ebe Jehova o ile a nkhauhela a ba a ntšoarela . ”
Mosali oa ka Evelyn , o ntse a sebeletsa Jehova le ’ na .
O re : “ E ka khona ke etse mesebetsi ea ea nthomileng , letsatsi le e - so ho likele ; bosiu boa tla , boo motho a sitoang ho sebetsa ka jona .
Leha ho le joalo , kamoo ho bonahalang kateng , ketsahalong eo Nathane o ile a bolela maikutlo a hae ho e - na le hore a bue seo Jehova a neng a itse a se bue .
Ho beha litaba maemong a tsona , u hopole hore nakong eo , Liithuti tsa Bibele le tsona li ne li keteka la 25 December e le sehopotso sa tsoalo ea Jesu , kapa letsatsi la hae la tsoalo .
Re sebelisa keletso eo re e amohetseng , re lokela ho lokisa tsela ea rōna kapele .
Ho etsa papiso : Haeba motho e mong a u kolota chelete e ngata empa ka lebaka la bomalimabe bo itseng a iphumana a sitoa ho u lefa .
Mokhoa oo ba sisinyehang ka oona , haholo - holo matekatse a tempele , o tsosa takatso ea botona le botšehali ebile ke oa nama .
Ha Satane a mo leka , Jesu o ile a bua ka Deuteronoma 6 : 13 ’ me a re : “ U lokela ho rapela Morena Molimo oa hao , ’ me u sebeletse eena feela . ”
Eva o ile a mamela noha ’ me Adama eena a mamela mosali oa hae .
Hape ruri e khetholloa ka toka ea Molimo .
Haeba u mocha oa Mokreste , ka linako tse ling u ka ’ na ua ikutloa u sa tšoanelehe .
TSE SENG KOTSING HAHOLO
Karolo 4 : Mona u tla fumana boitsebiso bo hlollang ba kamoo boboleli ba ’ Muso oa Molimo bo ileng ba fihla linaheng tse khōlō le lihleke - hlekeng tse hōle ho pota lefatše .
Nahana feela se seng sa lichaba tsa kajeno se se se e - na le molao oo ha e le hantle o neng o batla lerato !
Ha lelapa le etsa lintho tsa moea le le ’ moho seo se etsa hore le thabe e le kannete .
Mobishopo e moholo oa Toledo o ile a kenngoa teronkong lilemo tse supileng ka bopaki ba bohata ho sa tsotellehe boipelaetso bo boholo ba bapapa .
Empa hang ha a bua ka thōmo ea hae ea ho bolela litaba tse molemo ho Balichaba , ho boetse ho tsoha morusu .
Ho kōpa tšoarelo ka tieo ho ka ’ na ha lokisa lintho .
Liproverbia 19 : 17 e re fa lebaka le ka sehloohong la ho ba mohau ha e re : “ Ea bontšang mohau ho ea tlaase o alima Jehova , ’ me O tla mo buseletsa tšoaro ea hae . ”
Ha ke ntse ke batlisisa ka malumeli a eketsehileng , ke ne ke nyahama le ho feta .
Ka Sontaha se seng ka 1938 , ha re fihla sebokeng , baralib’abo rōna ba babeli ba hōlileng ba ile ba re lumelisa , eaba e mong o re : “ Mohlankana , na u se u emela Jehova ?
Morena oa motse oo , ea neng a apere seaparo sa ka holimo se selelele se sesoeu , o ile a re : “ Ba ne ba sa tsebe hore na ke hobane’ng ha ba ne ba foufala motseng ona oa khale .
Ke ile ka makatsoa ke ho bona kamoo ke neng ke sa hlokomela lintlha tse ngata kateng .
Ke mehlala e metle e le kannete !
□ Ke hobane’ng ha Pauluse a ile a ngolla Bakreste ba Baheberu keletso e matla hakaalo ?
U bona eka u etsisa ntate oa hao mekhoeng e metle kapa e mebe ?
Ho ithuta ka cheseho ketso e ’ ngoe le e ’ ngoe ea rabi , le polelo ea hae , ha hoa atametsa Bajuda haufi le Molimo .
“ Ntoa ke ea Jehova ” ( Davida ) , No .
Fana ka mohlala o bontšang kamoo ho tšaba Molimo ho ka fellang ka thabo le har’a mahloriso .
Se tsoetse pele ka hore : “ Masole a kang millione e le ’ ngoe a Vietnam a sa ntse a tlameha ho lebala ntoa e ntseng e a khathatsa ho fihlela kajeno . . .
Bosiung bo bong ke ile ka sithabela hoo ke ileng ka kōpa Jehova hore a mpe a ntlohele ke shoe , moralinyana oa ka a phele . ”
O ile a nahana a re , ‘ Ke tla fallela naheng eo , ke fumane mosebetsi , ebe ke lata lelapa la ka hore le tl’o lula le ’ na . ’
Batšoantšisi ba sebele ke bona ba bapalisang lipopae tsena ka mor’a sethala — kapa ho bua ’ nete — ka holim’a sethala moo ba sebetsang ba eme borokhong .
Linnete tsena li buella ho nepahala ha Bibele .
Ho hlakile hore Jesu o ile a bolela molaetsa oa ’ Muso le libakeng tse ling tsa Iseraele .
Moshe a ka ama bophelo ba hao joang kajeno ?
Ha ho pelaelo hore ba na le tšepo e tšoanang le ea e mong oa batlōli ba molao ba neng ba fanyehiloe pel’a Jesu .
Sena se ne se bolela hore o ne a etsa litlhophiso tsohle tsa tšebeletso ea tšimo .
Ka mohlala , Carol , morali oa ausi oa ka e moholo , Ester , o ile a qala ho bula maliboho ka 1953 .
□ Re na le mabaka afe a ho ‘ khaphatseha litebohong ’ ?
Li - “ gannet ” tsa leboea
Empa a re hlahlobeng maele a mang a Maakane .
Se lumelle Satane ho u amoha moputso oa bophelo .
Ke ’ nete , lingaka tse ling li ikutloa hore lifilimi tse tšosang ha li kotsi , ha li bake letho ha e se feela ho hlobaela haholo bosiu .
Nakong ena ea Keresemese , u ka ’ na ua eteloa ke e mong oa Lipaki tsa Jehova .
Mekete ena e meraro e ne e lebelloa ka matla a maholo , hobane e ne e le liketsahalo tse hahang moeeng le tsa thabo e khōlō . — Levitike 23 : 40 - 43 .
Litšebo ke “ puo e se nang motheo , eo hangata e seng ’ nete , e buang ka batho ba bang le litaba tsa bona . ”
A re nahaneng ka lintlha tse ling , kapa litšoaneleho tse tla nontša ‘ mobu ’ oa lipelo tsa rōna e le hore o nolofatse khōlo e molemo .
Ho hahamalla ho loka nakong ea bophelo bo bolelele ho tlisa tlhompho .
Jemima e bile pula - maliboho ka lilemo tse fetang tse tšeletseng , a iphelisa ka ho rōka .
Ke hobane’ng ha Habakuke a tletse tšepo le kholiseho ?
Na o ne a tla etsa hore ntate oa hae le moen’ae ba mo hauhele e le hore a se ke a ea moo a sa tsebeng ?
kapa “ Ke kahoo u ntšoarang ka thata hakaale ! ”
Re ka fumana thuso efe ea botho ho Sefela sa Lifela ?
Na ho na le motho eo u mo tsebang ea shoetsoeng ke molekane ?
Empa e - ba mosa , u be masene .
O tla ruta ba bonolo tsela ea hae . ”
Empa hona joale , esita le linaheng tse tsoelang pele moruong , likatakata le mefuta e meng ea likhofu ke tsona tse etsang mosebetsi oa ho cheka , ho laela le ho thotha .
A li ke li hlahise lipaki tsa tsona , hore li tle li boleloe e le tse lokileng , kapa a li ke li utloe ’ me li re , ‘ Ke ’ nete ! ’ ”
Ha a ne a pota - potiloe ke bahanyetsi , Davida o ile a tšehetsoa le ho khothatsoa , e leng se ileng sa etsa hore a re ho Jehova : “ Ha ke tšabe letho le lebe , kaha u na le ’ na . ”
E ka ’ na ea e - ba ho ratha patsi kapa ho khōfa lehloa .
E ne e le karolo ea bolumeli ba lelapa leso le tsela eo re phelang ka eona .
Ka tsela eo u etsa hore litaba tsa botho li be le nako ea tsona .
Mariah
Le hoja bothata ba ho bala bo ’ nile ba ntšitisa ho etsa lintho tse itseng , bo boetse bo ntsoetse molemo .
Ka August 1945 , ke ile ka isoa Lebothong la Sesole sa Metsing le sa Moeeng la Otsu .
Haeba u sa khone ho buisana le eo e ka bang mohiri oa hao , siea karete e nyenyane — ha ho khoneha e be e boholo ba lisentimithara tse 10 bophara le tse 15 bolelele — e nang le lebitso la hao , aterese , nomoro ea mohala , aterese ea e - mail hammoho le kakaretso e khutšoanyane ea tsebo ea hao ea mosebetsi le seo u se finyelletseng .
Le hoja e le ntho e utloahalang ho utloa bohloko ha motho e mong a re utloisa bohloko , na leo ke lebaka le utloahalang la ho khaotsa ho kopanela tšebeletsong ea Bokreste ?
Ka 1932 molebeli ea tsamaeang ea tsoang Greece o ile a etela Albania bakeng sa ho ea khothatsa barab’abo rōna le ho ba matlafatsa .
Kajeno , boitšoaro bo bobe , bokebekoa , pefo , bobolu le ho nyelisa melao ea Molimo ke kobo - anela .
* Setsebi sa moruo Renato Brunetta , se supa hore boemo bo “ mpefatsoa ke keketseho ea ho hloka mosebetsi le ho senyeha ho akaretsang ha boleng ba mesebetsi e leng teng . ”
Na “ Taolo ea Lefatše le Lecha ” ea Motho e Haufi ?
Jesu Kreste , “ ea sefubeng sa Ntate , ” ke mohlala o ka sehloohong o tšoaneloang ke ho lateloa .
Karabo e sa fellang e ka fumanoa mantsoeng a John F .
Ntlha e ka sehloohong ea Baheberu 10 : 24 , 25 ke efe ?
Basali ba ile ba sebeletsa Jesu le baapostola ba hae
Hlokomela hore Jesu o ile a bolela esale pele hore nakong eo ho tla ba le litlala le litšisinyeho tsa lefatše .
O Ahloloa Hore ke Mokhelohi
Leha ho le joalo , ke eleletsoe hore ha re qeta nako e telele re le hammoho , re teneha feela le ho ngangisana ntle ho mabaka .
Ka likhoeli tse tšeletseng li ne li nahana hore li ntse li loantša malaria .
( b ) Ke eng e re thusang ho ema re tiile , hona see ke bopaki ba eng ?
Ha Elia a fihla Sarepta , o ile a bona mosali e mong ea futsanehileng oa mohlolohali a ntse a roalla patsi .
“ MOLIMO o entseng lefatše le tsohle tse ho lona , e leng eena Morena oa leholimo le oa lefatše , o ke ke oa aha litempeleng tse entsoeng ka matsoho ; . . .
Na u ikemiselitse ho nyalana le motho eo haufinyane ?
( b ) Boikutlo ba Molimo ke bofe ka ba bolelang hore baa o sebeletsa empa ba le molato oa mali ?
Ho phomola ka tsela ena ho molemo .
Sebata seo ho buuoang ka sona ho Tšenolo 13 : 1 , setšoantšo sa sona hammoho le sebata se linaka li peli , li tla timetsoa .
Na ba kholisehile hore ho tlōla molao oa Molimo e ka ba ho tebileng hoo ho ka behang tebello ea Mokreste ea bophelo bo sa feleng kotsing ?
Sena se ka ’ na sa baka mathata a sa tšoaneng , ka mohlala ha ho uoa lechatong kapa lepatong la seng .
Na u tla khutlela morao kapa u tla batla tsela ea ho rarolla mathata ao ’ me u tsoele pele ?
Re ne re ngangisana nako le nako .
Ho na le litlaleho tse ngata ka Mangolong tse bontšang hore batho ba mehleng ea Bibele , haholo - holo bahlanka ba Molimo , ba ne ba talima ho hlokomela baeti e le ntho ea bohlokoa hakae .
Ka mor’a hore litokisetso tsena li etsoe , baemeli ba tsoang lekaleng ba ile ba ea Bilene , motsaneng o lebōpong , moo ba ileng ba palama sefofane se hiriloeng ho ea Maputo .
Empa ho teng khohlano e eketsehang mahareng a lipolotiki le bolumeli : “ Likhohlano tse fokolang mahareng a baetapele ba ’ muso le ba bolumeli ke bothata ba lefatše lohle . ”
Mona Jesu o ne a bua ka moea o halalelang oa Molimo , o ileng oa tšolleloa holim’a barutuoa ba hae matsatsi a 50 ka mor’a tsoho ea hae .
Ba bane ke baholo ’ me ba babeli ba bona ke bo - pula - maliboho ba kamehla , e leng se bontšang bonnete ba Liproverbia 17 : 6 : “ Litloholo ke moqhaka oa maqheku , ’ me khanya ea bana ke batsoali ba bona . ”
Haeba re bontša botšepehi ka litsela tsena , re ka kholiseha hore le ka mohla a ke ke a re lahla .
Sullivan o hlokometse hore ho sa ntse ho e - na le khatello e khōlō ea hore batho ba tsube .
Molula - setulo oa lenaneo lena e ne e le Theodore Jaracz , setho sa Sehlopha se Busang .
Moemeli oa Malaysia o ile a re ka ho toba : “ Ho hang ha re boloke meru ea rōna bakeng sa ba sentseng ea bona ’ me ba leka ho bolela hore meru ea rōna ke karolo ea letlotlo la moloko oa batho . ”
Ho na le lintho tse peli tseo Jakobo a li boletseng tse ka etsoang .
KAJENO puisano e thahasellisa haholo ho feta nakong leha e le efe historing .
O ile a botsa potso ka Sabatha ’ me ke Paki feela e ileng ea mo fa karabo e khotsofatsang e thehiloeng Mangolong .
Le hoja Colombia e tsebahala ka khauta le liemerauda , batho ke bona bao e leng letlotlo la eona la bohlokoa ka ho fetisisa .
Joale ho latela lensisi , meroho ea sebaka seo , le tlhapi ea letamong e le hore ho ka jelelloa reisi ka tsona .
Hopola , ho chesoa ke letsatsi kajeno ho ka u bakela kankere ea letlalo lilemong tse 20 kapa ho feta tse tlang .
Thuto ea botho e re thusa hore re be le teboho .
Hangata o ne a batla ho ba mong ka morero .
Ka thapelo nahanisisa : Na u hlile u boemong bo botle ’ meleng , maikutlong , moeeng le licheleteng hoo u ka tsebang ho hlokomela litlhoko tsa ngoana ?
Liphetolelo tse ling tsa Bibele mona li sebelisa lentsoe “ baikaketsi . ”
Ke ’ na ka ho le letona
Empa joalokaha ho ile ha etsahala mehleng ea Esthere , Jehova o tla tlisetsa barapeli ba hae “ phomolo le topollo . ” — Ezekiele 38 : 16 - 23 ; Esthere 4 : 14 .
Eaba joale ke hona ke hlakeloang hore seboka seo se ne se hlophiselitsoe Lipaki tse tsejoang feela tse bileng li tšeptjoang .
Batho ba baloang ka limilione lefatšeng ka bophara ba ikutloa ka tsela eo .
O ile a sebetsa ka thata ’ me a fumana maemo a phahameng k’hamphaning eo a neng a e sebeletsa .
E le hore re fihlele khōlo e feletseng ho hlokahala hore re koetlise matla a rōna a ho lemoha .
Ha ho na lesole le ileng la ahlamisa molomo . — Pesaleme ea 65 : 1 , 2 .
O li boloka li eme ka ho sa feleng . ” — Pesaleme ea 104 : 5 ; 148 : 3 - 6 .
Ha ketsahalo eo e fihlile eaba ea feta , ka potlako oa hlokahala .
Ho ne ho se na Lipaki sehleke - hlekeng seo ka nako eo .
Ho sa tsotellehe mokhoa ona o sa nepahalang , makholong a lilemo a fetileng bo - rasaense ba bokeletse tsebo e ngata haholo ea saense .
Ke eng se tla thusa ho thibela ho se utloisisane hamorao ?
Boikarabelo bo akaretsang ba baholo ke bofe kajeno ?
E ne eka ke ntse ke hatakela sehlabelo seo Jehova a mphileng sona ka maoto .
▪ Phuputso e ’ ngoe e bontša hore Marussia a lumela hore lintho tse ka sehloohong tseo ’ muso o lokelang ho sebetsana le tsona ke ho loantša “ bobolu ” le “ ho fokotsa litheko tse nyolohang ka sekhahla . ” — PRAVDA , EA RUSSIA .
Kasarda o hlokomela lebaka le leng le tummeng : “ Ho na le khopolo ea hore metse e meholo e kotsi haholoanyane kajeno .
Jehova o ile a hlohonolofatsa Louis le Perrine ka lebaka la mamello ea bona .
Nakong ea bocha , bacha ba bangata ka ho khethehileng ba tšoaetsoa habonolo ke moea ’ ona oa borabele .
Ka tsela e itseng ba tlameha ho fumana chelete e lekaneng ho lefella ntlo , lijo le liaparo tse lokelang .
Ha le ntse le hōla , hanyane ka hanyane , ba tšoeroeng ke lona ba sitoa ho etsa lintho .
Ebe u sebelisa melao - motheo eo ha u etsa liqeto .
Empa haesale ke sebeletsa Jehova , ke bile le bana ba bang ba supileng .
Lira tsa Molimo li ke ke tsa hlola li khona ho hooa ka tlhōlo ka lebaka la batho ba Jehova , kaha Moeta - pele oa bona , Jesu Kreste , o hatela pele ho ea tlhōlong ea ho qetela !
Ba fumana matlotlo a moea le temohisiso ea moea .
Joalokaha ho boletse Anthony Morris III
Khaolo ea boraro ea buka ea Bibele ea Liproverbia e fana ka likarabo .
Ka mor’a hore a tsamaee , o ile a nkamohela ka tsela eo masole a macha a amoheloang ka eona .
U se ke ua ea le khongoana holimo ha u bona eka ba rata ho itaola — bacha ba hloka motheo o tiileng oa lelapa ho feta leha e le neng pele .
Hase hore bacha bohle ba rera ho kopanela boitšoarong bo belaetsang bosiu bohle .
Ho bolela hore libuka tsa boitšoaro bo bobe ha li na tšusumetso e mpe ho tšoana le ho bolela hore libuka tse buang ka boitšoaro bo botle ha li na tšusumetso e ntle .
Na u tloaetse ho khetha hore na u ja eng ha u je eng ?
Ho ba le pono ea ho rata lintho tse bonahalang ka mokhoa o joalo ho ka khelosa motho habobebe peisong ea bophelo kapa ha mo thibela esita le ho e simolla .
Na re lokela ho nka boroko e le boiketlo kapa e le ntho e hlokahalang ?
Motho ea ikhohomosang ka boikakaso ke ea joang ?
Liproverbia 17 : 17 e re : “ Kamehla metsoalle e bontša lerato la eona .
Ho lula sepetlele ka nakoana ke ho tloaelehileng .
E se eka u ka talima ho Jehova bakeng sa ho u fa matla le ho u phahamisa joaloka ntsu .
Leha ho le joalo , ho hlokahala boiteko bo kopanetsoeng ba batho ka bomong hore motho e be “ mosebetsi eo ho seng letho leo a ka hlajoang ke lihlong ka lona , ea tšoarang lentsoe la ’ nete ka nepo . ”
Motho a ka hlahisa litšoantšo tse thetsang ka matsoho a hae ( bomene - mene ba matsoho ) , a hopotse hore hangata letsoho le ka etsa lintho ka potlako ho feta kamoo leihlo le ka hlokomelang ka teng .
Pereze . — Luka 3 : 33 .
E meng ea melao - motheo ea Bibele e neng e laola boikokobetso bo lekanyelitsoeng ba Bakreste ba pele ho balaoli ba batho ke efe ?
40 : 5 , 12 .
* E ka ’ na eaba ba bang bao e ileng ea e - ba balumeli ka lebaka la boboleli ba Saule Damaseka le bona ba ile ba thusa , hobane Liketso 9 : 25 e re : “ Barutuoa ba hae ba mo nka ’ me ba mo theolela tlaase bosiu ka lesoba le lerakong , ba mo theola ka baskete . ”
Thapelo e phetha karolo efe ho tsosoloseng kamano ea Jehova le mofosi ?
Joaloka mopesaleme , re kōpa Molimo : “ Etsa hore pelo ea ka e sekamele likhopotsong tsa hao , eseng liphaellong , ” ke hore phaello e sa lokang .
Setefane ha aa ka a bua letho ka selekane sa Molimo le Abrahama , empa ho Genese 12 : 1 - 3 , selekane seo se amahanngoa le taelo ea ho ea Kanana .
Ke ile ka a fa lisebelisoa tsa ka eaba kea tsamaea .
Batsoali ba hao baa u rata ’ me ba u tseba hamolemo ho feta mang kapa mang .
“ Ba thabile ebile ba khotsofaletse ho sebeletsa Jehova ba momahane . ”
Thutong ea hae ea Thabeng Jesu o ile a bua ka tlhoko ea bohlokoa eo re bōpeletsoeng le eona ha a re : “ Ho thaba ba elang hloko tlhoko ea bona ea moea , kaha ’ muso oa maholimo ke oa bona . ”
A hlalosa , “ Hangata li tlala ho feta - feta mona , empa ha li lefelloe haboima , e leng ho bolelang hore re ka khona ho palama [ lik’hilomithara tse 10 ho ea ho tse 15 ] letsatsi le leng le le leng ho ea likarolong tse hojana tsa motse ho ea bolela . ”
Ke mathata afe ao batho ba Molimo ba thulanang le ’ ona ?
Nahana ka mashano a phatlalatsoang kajeno , ha hoa lokela ho re makatsa hore ebe batho ba bangata ba “ hlōleha ho chechisetsa ho ikhotsofatsa nakong e tlang . ”
Ho re shoa ! hanyenyane ho ka u liehisa , empa ho ka pholosa bophelo
Ka lehlakoreng le leng , ho ananela lintho tsa moea ho khotsofatsa litlhoko tsa rōna tsa bohlokoa ka ho fetisisa — e leng ho ratoa , ho ba le morero le ho rapela Jehova , Molimo ea lerato .
O ile a etsa litlhaloso tse ngata tsa Mangolo ’ me a khothaletsa ka matla ho khomarela lithuto tsa Jesu Kreste le baapostola ba Hae .
Se neng se ananeloa ka ho tšoanang e ne e le thuso e neng e fanoa ke banna le basali ba neng ba mo amohela boeting .
Batho ba limillione Poland , Jeremane e ka bochabela le libakeng tse ling ba hlokometse hore phetoho ena ho tloha moruong o laoloang ke ’ muso ho ea khoebong e seng tlas’a taolo ea ’ muso qetellong e tla qala pele ka ho tlisa ho hloka mesebetsi le masisa - pelo .
Ke hobane’ng ha e ile ea etsoa ?
Ba hanang ka boomo ho e mamela ha ba sa amoheleha ka mokhatlong oa batho ba hae .
Ha e le hantle , ba bang ba ka ’ na ba e - ba le a mang a ’ ona kapa ba se ke ba ba le ’ ona ho hang .
Ka lebaka la keketseho e khōlō , ho hahiloe Liholo tse ngata tsa ’ Muso , ’ me hona joale naha eo e na le Lipaki tse mafolo - folo tse ka holimo ho 18 000 .
“ O ile a fana ka ba bang e le baapostola , ba bang e le baprofeta , ba bang e le baevangeli , ba bang e le balisa le mesuoe , ka sepheo sa ho khutlisetsa bahalaleli tseleng , bakeng sa mosebetsi oa bosebeletsi , bakeng sa ho haha ’ mele oa Kreste , ho fihlela bohle re fihlela bonngoeng tumelong . ” — Baef .
Leha ho le joalo , ho sa tsotellehe khotso ea nakoana , e ne e tla amoheloa ka thabo .
Ka lehlakoreng le leng , e ka ipiletsa haholo hoo litho tsa lelapa li ka lemallang ho e shebella , ’ me sena se ka fella ka hore ho se be le puisano .
Ho ntse ho le joalo , litho tsa Sehlopha se Busang li ile tsa tsoela pele li sebeletsa e le batsamaisi le balaoli ba Mokhatlo .
Nka hore ka mor’a moo o re o ne a sa utloisise ka botlalo seo a neng a se etsa nakong ea ha a ne a kolobetsoa ’ me o re kannete kolobetso ea hae e ne e sa amohelehe .
Khaello ea Phepo e Nepahetseng — E Atile Hakae ?
Anna o ne a tseba hore na mohalitsong oa hae o tl’o itšoara joang .
Nako le nako , Phula ea Lefu e khaba ka lithunthung tsa naha .
Lilemong tsa bocha ke ne ke laoloa ka ho feletseng ke ho tšaba lefu , empa ho rua tsebo e nepahetseng ea Bibele ho mphile tšepo e tiileng ea ho phela ka ho sa feleng — e leng bophelo boo Jesu a itseng ke bophelo ‘ bo bongata . ’
E le eena ea laolang maemo ka linako tsohle , Jehova a ka fetisa lira tsa hae ka ho nahana ’ me a laola maemo bakeng sa ho pholosa batho ba hae .
BABUELLI ba molao kapa metsoalle kapa mecha ea phatlalatso kapa “ litsebi ” li ke ke tsa utloisoa bohloko ke liphello tsa tlhalo .
Ho hatisitsoe feela karolo e le ’ ngoe ho tse tharo ea litlaleho tsena .
Lula U Tšepahala ka Linako Tsohle
Le ile la mo laela hore a le bule le ntse le tletse pelaelo .
Mofuta o mong oa dinoflagellate ke Gambierdiscus toxicus .
Mocha e mong o ile a hlalosa : “ Ka mor’a khitla bosiu , ho na le bakhanni ba bangata ba tahiloeng tseleng , ’ me ho molemo hore uena u be sieo tseleng . ”
Kaha ‘ bohle re hlaheloa ke nako le ketsahalo e sa lebelloang , ’ re ke ke ra bolela hore na re tla phela halelele hakae .
Ka mohlala , ka 1971 tšisinyeho ea lefatše ea tekanyo ea 6,6 sekaleng sa Richter e ile ea etsahala San Fernando , California , United States , ’ me ea bolaea batho ba 65 .
Ke mang ea ka balang maru hantle ka bohlale , kapa linkho tsa metsi tsa leholimo — ke mang ea ka li thulamisang , ha lerōle le tšoloha joalokaha eka le tšolohela ka nthong e entsoeng ka ho qhibilihisoa , makote a khomarelana ? ”
Ke rata ho itaola , empa ke batla ho bula pelo ea ka .
Jesu le eena o na le moea o joalo oa ho amohela , o nka bohato ba ho atamela baetsalibe le balekhetho , ba emeloang ke mora ea lehlasoa papisong ena .
Ka mor’a moo , ka ntša leino la haka , ’ me ka sitoa ho ja .
Mehleng ea kajeno , “ bara ba Levi ” ba Malakia 3 : 3 ke bafe ?
Ena ke tlhaloso ea motho ka phihlelo ea hae ea pele ea ho bua “ puo e sa tsejoeng . ”
Jobo o ile a fumana litlaleho tse latellanang tsa hore o lahlehetsoe ke likhomo tsa hae , liesele tsa hae , linku tsa hae , likamele tsa hae le bahlanka ba hlokomelang liphoofolo tseo .
12 : 19 , 21 .
Na u hlokometse hore le uena u ka ba le karolo tabeng ea ho pholosa ba bang , ho akarelletsa beng ka uena bao u ba ratang haholo ?
Ke bo - mang ba u khothatsang , hona hobane’ng ?
Kamoo ho bonahalang kateng , thohako eo Molimo a neng a rohakile lefatše ka eona e ile ea fela . — Genese 13 : 10 .
’ Me hlokomela boiteko bo boholo bo entsoeng ke baena ba rōna linaheng tseo pele li neng li thibetsoe empa joale li hlaha tlalehong ea lefatše ka bophara — Bulgaria , Cameroon , Czechoslovakia , Ethiopia , Mozambique , Nicaragua , Rwanda , le U.S.S.R .
Sheba Molula - Qhooa oa April 15 , 1999 , leqepheng la 28 - 30 moo ho tšohloang melao - motheo ea Bibele e amanang le litaba tsa mosebetsi .
Mohlomong ke hona moo “ Lota a [ ileng a ] phahamisa mahlo ’ me a bona Setereke sohle sa Jordane , hore kaofela ha sona e ne e le sebaka se noselitsoeng hantle pele Jehova a felisa Sodoma le Gomora , se tšoana le serapa sa Jehova , se tšoana le naha ea Egepeta ho ea fihla Zooare . ” — Genese 13 : 8 - 10 .
Kapa ka baka la ho phela tumellanong le ’ nete , li ka ’ na tsa fumana molemo ka tsela e ’ ngoe licheleteng , kahisanong , kapa lapeng .
Lelapa Lea Sokeloa , 4 / 1 Leta U sa Fele Pelo , 6 / 1
Makhoba a mangata a tahi a bile le mathata a ho noa a sa le manyenyane
Mosali ea bitsoang Vera o bolela hore ha a qala ho fetoha Mokreste , ka mehla o ne a bua le monna oa hae ka ’ nete ea Bibele , ’ me monna o ile a tenoa ke hoo .
( b ) Ke lipotso life tseo e leng bohlale hore bacha ba li nahane ?
Ho “ Khaphatseha Tumelo Litebohong ”
Ba - Heberu 12 : 1 - 3 , ( NW ) e baleha tjena : “ Kahoo , kaha re pota - potiloe ke leru le leholo joalo la lipaki , le rōna a re lahleng boima bohle le sebe se re tšoasang habonolo , ’ me a re matheng ka mamello peisong e behiloeng ka pel’a rōna , re ntse re talimile ka hloko ho Moemeli e Moholo le Mophethahatsi oa tumelo ea rōna , Jesu .
Ka mohlala , ho na le batho ba ka bang 400 000 United States ba lahlehetsoeng ke maoto kapa matsoho .
Khotsofalla ho ba ’ Mè , 2 / 1
Ho tea mohlala : Lilemong tse ’ maloa tse fetileng , ho ile ha etsoa boiteko ba ho felisa Lipaki Tsa Jehova sebakeng se seng Angola .
Sehlopha sa Bo132 sa Sekolo sa Bibele sa Gileade sa Watchtower se Abetsoeng Mangolo
400 MI
Empa ba lekang ho e fetola ba fumana melemo e mengata haholo !
Mohlala ke mooki ea neng a lakatsa ho eloa hloko ka tsela e sa tloaelehang .
Se tla thusa batho ba kang ’ na hore re boele re tsoele pele ka bophelo .
Herbert Freudenberger le bafuputsi ba bang ba ile ba qala ho sebelisa poleloana ena bohareng ba bo - 1970 , ’ me e ile ea bolela “ boemo ba ho khathala bo bakoang ke ho sebelisana le batho bo khathatsang maikutlo . ”
Libokeng tsa bona tsa Sontaha , hangata ba bang teng libokeng tsa liphutheho tsena tse 7 ke batho ba ka bang 1 700 .
Ke ’ nete hore libuka tse fanang ka likeletso li ka ’ na tsa e - ba le likeletso tse molemo .
Na Molimo o Amohela Borapeli bo Bong le bo Bong ?
Motho a ka bua poleloana eo a phefumolohile hanngoe .
Ka mor’a lihora tse hlano ke le ka phaposing e ka tlaase e sebupetsane , ke ile ka fumana sosara e nang le lebitso la Jehova , e le Litlhaku tse ’ nè tsa Seheberu tse Emelang Lebitso la Molimo .
Ke ile ka qala ho tloaelana le bacha ba sa rateheng ba sebakeng seo ke lulang ho sona ’ me ka qala ho tsuba le ho becha lihukung tsa seterata .
Batho ba na le bolokolohi ba ho ikhethela ’ me ba ka ikhethela tsela eo ba batlang ho phela ka eona , esita le maemong a thata haholo .
Ha li ne li falla — ka bongata ba limilione tse likete kapa ho feta — li ne li fifatsa sepakapaka matsatsi a ’ maloa .
Leha ho le joalo bacha ba bang ka sebete feela ba hlompholla litekanyetso tsena tsa bomolimo .
Hang ha Komiti e Ngolang e lumetse hore Bibele e fetoleloe puong e itseng , e khetha sehlopha sa Bakreste ba inehetseng hore ba sebetse e le sehlopa se fetolelang .
Eric ea lulang Philippines , o re : “ Ha ke sebelisa karete ea ho reka ka mokitlane , hangata ke reka haholo ho feta ha ke tšoere chelete .
Mosali ea boletsoeng ka holimo o ile a tla , ’ me a sa re letho ho Jesu , a ama seaparo sa hae a le ka morao ’ me “ hang - hang phallo ea hae ea mali ea ema . ”
U ee u ikutloe joang ha u thola ntho ea bohlokoa ea motho e mong ?
Frédéric Dumoulin , o qetile lilemo tse fetang leshome a sebetsa setsing se etsang liphuputso tse amanang le meriana Univesithing ea Ghent e Belgium .
Machaena ke batho ba khothetseng le ba bohlale .
Qoba lipolelo tse sa hlakang tse kang , “ U mpolelle haeba ho e - na le seo u se hlokang . ”
Kaofela ha rōna re batla ho etsa liqeto tseo re ke keng ra ikoahlaea ka lebaka la tsona , haholo - holo haeba liqeto tseo li ama tsela eo re phelang ka eona .
14 , 15 . ( a ) Litšebelisano tsa Jesu le Matheu Levi li senola eng ka litsela tsa Bafarisi ?
Hamorao ke ile ka utloa hore o ne a ithiba ka thata hore a se ke a tšeha , kaha o ne a ikutloa hore ke itšenotse le ho feta .
Ho ka etsahala hore ebe ha e sa le buka e baloang ka ho fetisisa lefatšeng .
Esita le nako e loketseng e ka ameha .
E , hohle moo re leng teng , ho ntse ho e - na le “ ho hongata ho ka etsoang mosebetsing oa Morena . ”
29 : 3 - 9 — Ho tšoantša lentsoe la Jehova le sefefo sa lia - luma se tšosang ha se tsamaea ho bontša eng ?
Ka nako e tšoanang , ’ mè oa Anna le eena o ile a mo ruta litsela tse ling tse sebetsang .
Tlaleho eo e bolela hore lelapa le leng le le leng le na le “ boikarabelo ba hore na bana ba shebella lifilimi le mananeo a thelevishene a mofuta ofe . ”
Na U Lokela ho Tšaba Leihlo le ka U Ntšang Kotsi ?
Joale o re ho barutuoa ba hae : “ A re keneng Judea hape . ”
Ruri , Jehova o tla felisa lintho tsohle tse mpe , a etse joalo ka tsela eo ho hang re neng re sa e lebella .
Ruri ha ho bohlale hore motho a etse liqeto tse tebileng a itšetlehile ka lintho tseo a inahanelang tsona le ka tsela eo a ikutloang ka eona .
A ne a sasanka ka likoloi tsa ntoa tse ka bang 900 , tse nang le mahare mabiling .
Jezebele o ile a khothalletsa batho ho rapela Baale ho e - na le ho rapela Jehova , a bolaea baprofeta ba Molimo a ba a silafatsa batho ka “ bohlola ” le “ boloi ” ba hae .
Ha batho ba Jehova ba ntse ba loanela ho boloka litekanyetso tsa hae , Bokreste - ’ motoana bo ntse bo tetebela haholoanyane qhafutsong ea litšila tsa lefatše lena .
Batsoali ba sa laoleng bana ba bona hase batsoali . ”
Leha ho le joalo , marotholi a pula hammoho le makhasi a oeleng a hloka ho thusoa e le hore a fetohe limatlafatsi .
Hamorao , “ e mong oa bona a matha eaba o nka seponche ’ me o se kolobisa ka veine e bolila le ho se beha holim’a lehlaka eaba o qala ho mo fa ho nooang . ” — Mat .
Sena se ile sa ba tšehetsa e le bo - pula - maliboho ho fihlela ba ea Sekolong sa Bibele sa Watchtower sa Gileade ’ me ba amohela likabelo tsa boromuoa .
Moferefere oa lipolotiki o ile oa fella ka ntoa ea lehae ka September 2002 .
Mohlomong ea tlang ho eletsa o nahanne haholo ka mantsoe kapa katamelo e ka sebelisoang .
Hape , joalokaha Andrè e mocha a hlokometse : “ Ha e mong a u bolella taba e itseng ’ me hamorao u fumana hore e ne e le leshano hoo ho halefisa haholo . ”
Kahoo a ke ke a ba sebakeng se seng hape ka nako e le ’ ngoe .
Baboleli ba sebete ba litaba tse molemo ba ikemiselitse ho thulana le phephetso ena ’ me ba arabetse ka moea o tšoanang le oa moprofeta Esaia : “ Ke ’ na enoa !
Lintho tsohle tse mpe — ho akarelletsa le ho ferekana maikutlo — li tla be li le sieo , hobane Molimo o tla ‘ khotsofatsa takatso ea lintho tsohle tse phelang . ’ — Pesaleme ea 145 : 16 .
Morao koana ka 1920 , makasine ena e ile ea re ha e tšohla keletso ea Bibele e mabapi le hore na ke hobane’ng ha re lokela ho ikokobetsa : “ Joalokaha re bona kamoo Morena a talimang boikokobetso e le ba bohlokoa kateng , barutuoa bohle ba ’ nete ba lokela ho loanela ho bontša tšobotsi ena letsatsi le leng le le leng . ”
Ebile nakong eo ha kereke e ne e etsa qeto ea qalisa mokete oa tsoalo ea Kreste ( nativitas ka Selatine ) .
Batho ba etsang qeto ea ho noa joala ba ka ipotsa lipotso life ?
Motho eo o re : “ Maria ! ”
Ho e - na le hore Gloria a khopisoe ke seo , o ile a itšehela , eaba ba qala ho buisana ka hore na ke hobane’ng ha a ne a le Mexico .
Ke ne ke sitoa .
Re ile ra qeta likhoeli tse ngata re se na chelete e kenang . ”
Na ka linako tse ling u ee u bone eka bophelo bo bokhutšoaane ?
Oa hlalosa : “ Ke ile ka ikutloa ke le molato hore ebe ke ile ka mo roma .
Dan le Sam , Bakreste ba babeli bao e leng bara ba motho ba nama , ka cheseho ba ne ba bapala papali e itseng e neng e tšepisa ho rarolla mathata a thuto ea lipalo .
Makasine ena eo u ntseng u e bala e bua ka molaetsa oo oa Bibele .
Ba bang ba lumelang ho tsoaloeng hangata ba etsa tlhahiso ea hore kaha monna enoa o ne a tsoetsoe a foufetse , e tlameha ebe sebe sa hae se ne se etsahetse bophelong ba nakong e fetileng .
Kahoo , a re ke re hlahlobeng tse ling tsa litsela tseo re ka thusang bana hore ba ithute ka ho eketsehileng ka mokhatlo oa Molimo .
Ba bang ba nka hore le hoja ho sa tsejoe letsatsi leo Jesu a hlahileng ka lona , Bakreste ba ntse ba lokela ho le keteka .
SWEDEN , Kereke le Naha li ’ nile tsa thabela kamano e haufi - ufi ka lilemo tse fetang 400 .
Na re ipoloka re le boemong bo hloekileng moeeng ?
Mosebetsi oa Tsosoloso
Ha Anna a ntse a lla a bile a rapela , o ile a nyarosoa ke lentsoe la motho ea buang .
“ Jehova o phahame , leha ho le joalo o bona ea ikokobetsang ; empa ea iphahamisang o mo tsebella hōle . ” — Pesaleme ea 138 : 6 ; Liproverbia 8 : 13 .
Sena se fapana ho ea ka linaha .
Joale , nahana u se u le naheng esele ’ me u le ka kamoreng e entsoeng ka khalase e sa kenyeng molumo .
Na ngoana ea esong ho tsoaloe o na le litokelo leha e le life tsa molao ?
Ke’ng e ileng ea u kholisa hore ’ Mōpi o teng le hoja pele u ne u sa lumele hore o teng ?
Ka lebaka leo , batšehetsi ba leka ho laola hore na ho hlaha eng ’ me ha ho hlahe eng mecheng eo .
Bekeng e fetileng , ke bile le tse 40 kampong ea ka ea boikhathollo , ’ me ha lia ka tsa mpakela mathata leha e le afe .
Ka lehlakoreng le leng , mekhatlo e hlophisitsoeng ea bolumeli , ea lipolotiki , le ea khoebo ea lefatše lena hangata e bonahatsa seo Bibele e se bitsang mesebetsi ea nama : “ bōra , liqabang , mohōnō , khalefo , likhang , liphapang , likhaohano , mōna , botahoa , bonyollo , le tse ling tse joalo . ”
Ho latela bafuputsi , lisosa tse belaelloang li akarelletsa livaerase , ho haelloa ke liprotheine , ho ba le khaello e itseng liphatseng tsa lefutso ( haholo - holo mofuta o futsoang oa ALS ) , manya a tšepe , lintho tse chefo methapong ea boko ( haholo - holo ALS ea Guam ) , ho se sebetse hantle ha tsamaiso ea ’ mele ea ho itšireletsa mafung le ho se sebetse hantle ha motsoako o potlakisang tšebetso ea lik’hemik’hale ’ meleng .
Ha re tšohe .
E na le tšusumetso bophelong ba ba e sebelisang .
( Bapisa Johanne 19 : 38 . )
Hape a rata ho tantša — banna ba arohane le basali — a tsamaisa liphaka le matsoho ka tsela e khahlehang .
Leha ho le joalo , bakeng sa bacha ba bangata label ha se letšoao la boleng empa e le letšoao la boemo — letšoao la seriti .
Kaholim’a tsohle , re lokela ho kōpa tataiso ho Molimo le thuso e re tiisang ea moea oa hae .
Lihloohong tsena tse tharo , re tšohlile lintlha tse hlano tse amanang le boikutlo ba kelello ba Jesu le kamoo re ka etsisang mokhoa oa hae oa ho nahana le tsela eo a neng a etsa lintho ka eona .
Lipaki tse ling li khathile tema mosebetsing ona ka lilemo - lemo , empa ha nako e ntse e feta tsa fokolloa ke tumelo ho Jehova , eaba li khaotsa ho kopanela le phutheho ea Bokreste .
Kabo ea Mangolo ea Bo126 ea Gileade
Joaloka bacha ba bangata , u batla ho ratoa le ho amoheloa ke ba bang .
Monel Metal ke motsoako oa nickel le koporo o nang le matla a phahameng a mamellang khatello , ’ me ha e tsoe mafome .
Nakong ea seboka sena , Lipaki tse lephepheng li ile tsa bua le lingaka tse ka bang 480 — bongata ba tsona li ile tsa khutla bakeng sa ho fumana boitsebiso bo eketsehileng , tsa ba tsa tlisa basebetsi - ’ moho le tsona .
Ha re bua haholo , re ba kotsing e khōlō ea ho bua ntho e itseng e booatla kapa e ka utloisang ba bang bohloko .
Le hoja buka ena e bua ka liphatlalatso tse khahlanong le Juda , Iseraele le linaha tse e pota - potileng , taba e ka sehloohong eo e buang ka eona hase kahlolo .
Bibele e bontša hore letsoalo ke boikutlo bo ka hare ho motho bo etsang hore a hlahlobe liketso tsa hae le ho li sekaseka .
Hona joale ho tlalehoa hore tšilafalo ea fokotseha ka lebaka la mehato e matla ea ho laola lead mesing ea makoloi .
Ruri , Molimo a ke ke a bua leshano !
“ Morali oa Hao o na le Lefu la Tsoekere ! ”
Ka letsatsi le leng o ile a khothaletsa Theodore ho tsoa mosebetsing .
Ha le eo [ libukeng tse ngotsoeng ka letsoho tsa ] khale kapa liphetolelong . ”
Mashano a ka ipaka ho ba teko ea tumelo ea rōna ka litsela life ?
Bibele e hlalosa Jehova ka mantsoe ana : “ Ke Lefika , mosebetsi oa hae o phethahetse , etsoe litsela tsohle tsa hae ke toka .
Ba ne ba ipolela hore ba emela Molimo .
Ka 1972 moaho oa liofisi o mocha o motle oa lekala , o botleng Nairobi , o ile oa neheloa .
Ka ho tšoanang , ha re ithuta Bibele le batho , re ba ruta litaelo tsa Kreste .
Maemo a batho aa fapana , ’ me a tlameha hore a nahaneloe .
Ba ne ba se ba qetile lilemo tse tharo ba ntse ba e lefella .
Na seo se bolela hore u lokela ho apara joaloka motho ea lilemo li 40 ?
Ho fapana le George le Patricia , Rachel eena o ile a tsamaea ka sefofane ho ea Europe , moo a neng a il’o sebetsa malapeng .
Ho Hopola Matsatsi a ho Qetela a Jesu Lefatšeng
a thabe bophelong ?
Ka linako tse ling batsoali ba ka ’ na ba hlōloa ho bontša tholoana ea moea baneng ba bona .
Ha re le moo re ile ra mamela ha Mor’abo rōna Nathan H .
Mosali oa Mokreste a ka leka - lekanya botšepehi ba hae ho Molimo le ho ikokobeletsa monna oa hae ea sa lumelang joang haeba monna a kopanela liketsong tsa bolumeli tsa matsatsi a phomolo a bolumeli ?
Lenaneo le Thabisang
Qalong , ha rea ka ra bua ka bolumeli .
O akarelletsoa har’a Bakreste ba ka bang 12 kapa ho feta ba ileng ba loanela tumelo mehleng ea hae .
Empa le bontšane mosa , le be le qenehelo e bonolo , le tšoarelane ka bolokolohi feela joalokaha Molimo le eena ka Kreste a ile a le tšoarela ka bolokolohi . ” — Baefese 4 : 31 , 32 .
Molimo o itse : “ Leholimo ke terone ea ka , ’ me lefatše ke bonamelo ba maoto a ka . ”
Ha ba le moo , lerato la Ruthe le tlhokomelo ea hae ho matsal’ae li ile tsa khahla baahelani hoo ba ileng ba nka hore o “ molemo ho [ Naomi ] ho feta bara ba supileng . ”
Jesu o itse : “ Ho lehlohonolo [ “ ho thabile , ” NW ] ba utloang lentsoe la Molimo , ’ me ba le boloka . ” — Luka 11 : 28 .
“ Lentsoe ” la Jesu le akarelletsa taelo ea hae ea hore re kopanele ka cheseho ho phethahatseng thomo e reng : ‘ Ka hona e - eang ’ me le etse batho ba lichaba tsohle barutuoa , le ba kolobetse . ’
“ Nepisisa lintho tsa bohlokoa haholo . ” — BAFILIPI 1 : 10 .
Lihora tseo tsa bohlokoa Holong ea ’ Muso kapa Thutong ea Buka ea Phutheho li ka re hlasimolla ka mor’a lihora tse telele tseo re li qetileng re leka ho ipoloka re phela lefatšeng la Satane le tletseng bora .
Molimo ea Seng Leeme o Tšoaretse Bohle Molaetsa
Gathany
Ho sebelisoa mefuta e meraro ea sesepa , eo o mong le o mong o nang le ’ maloa oa oona .
Bo - rasaense ba bangata ba lumela hore mashala le oli ke mesaletsa e bolileng ea lifate le limela tse fumaneng matla a tsona letsatsing .
José o ne a labalabela ho ba mohlanka ea sebeletsang ka phuthehong .
Robert o ne a atisa ho ipotsa ka morero oa sebele oa bophelo .
Tlaleho ea UNICEF e bolela hore “ ha ho mohla Afrika e tla hlaphoheloa ntle le boiteko ba machaba ka tekanyo e khōlō eo ho seng mohla ho kileng ha nahanoa ka eona . ”
Ha a le lilemo li 25 a qala ho busa ’ me kapele a qala ho khutlisetsa borapeli ba ’ nete Juda . — 2 Marena 18 : 1 - 5 .
E le hore ’ molai a khone ho balehela motseng oa setšabelo ka potlako a bile a sa sokole .
E re ke u etsetse ’ ona . ”
Na u utloisisa ho senya nako le ho etsa boiteko kamehla e le hore u ka bokella bopaki bo hlokahalang ho haha tumelo ?
Ho sebelisoa ha gase e chefu ka lekhetlo la pele kampong ea mahloriso Auschwitz
Ke nahana hore se etsahetseng se entse hore A . a hōle ho feta tebello e tloaelehileng kapa khōlo ea motho ea lilemo li 15 .
Hangata re lokela ho leta likhoeli tse peli kapa tse tharo pele re lefshoa bakeng sa mosebetsi oo re o entseng .
Ke hobane’ng ha lipetlele tse ngata hakale li kōpa bakuli ho saena foromo ea tumello e lokollang sepetlele boikarabellong ba liphello tse kotsi tsa tšelo ea mali ?
Re sebetsa lihora tse seng kae , empa re na le chelete e eketsehileng .
Sehlopha sa bobeli sa batho bao e neng e se Baiseraele se ileng sa qolloa e ne e le bara ba bahlanka ba Salomone .
Na ho Tšoha Apocalypse ho Loketse ?
13 : 11 , Bibele — Phetolelo e Ncha .
Ke hobane’ng ha moroetsana eo a ile a etsa boiteko bo bokaalo ba hore a khutlise chelete eo ?
Tlhaloso e ho Numere 4 : 6 e buang ka ‘ ho kenya lipalo ’ e ka ’ na ea bolela ho lokisoa ha lipalo hore ho jaroe lekese lena le boima ho le isa moo ho neng ho tla hlongoa liahelo bocha teng .
Histori e bontša hore ’ muso oa lefatše o ileng oa hlahlama oa Babylona , ke oa Bamede le Bapersia .
Litlhahlobo tse entsoeng ka carbon 14 ( k’habone e ntšang mahlaseli a kotsi ) hammoho le ho ithuta lingoliloeng tsa boholo - holo li tiisa hore meqolo ea khale - khale ho ena ke e ngotsoeng ho tloha hoo e ka bang lekholong la lilemo la 200 B.C.E . ho ea ho la 100 B.C.E .
LETSATSI e ne e le la 16 July , 1942 , ha ke ne ke le ngoananyana ea lilemo li hlano feela .
Esaia o ile a bona ka pono batho ba tsoang lichabeng tsohle ba phallela borapeling ba ’ nete .
Ke mang ea bo entseng joalo ?
Kaha tsebo ea mofuta o itseng e ile ea etsa hore ba nang le eona ba ikhohomose , e tlameha ebe Pauluse o ne a bolela hore lerato le lona le haha ba bontšang tšoaneleho eo .
O re : “ Ke ile ka khutlela ho Jehova ka mor’a hore ke hlokomele se ntahlehetseng .
Joale , phaella ka tšusumetso ea thelevishene le libaesekopo .
Phihlelo eo motho a e fumanang moo e nchafatsa botho ba hae le pelo ea hae hore li tšoane haholoanyane le mohlala oa Kreste Jesu .
Ha ke ne ke le moo , ke bile le thabo ea ho etela ntlo - khōlō ea lefatše ea Lipaki tsa Jehova e haufi le moo Brooklyn , New York !
Empa o ile a boela a kenyelletsa le nako ea boikhathollo kemisong eo ea hae .
Ha e le hantle , batho ba Jehova , le hoja e se karolo ea lefatše lena , ba ke ke ba qoba ho angoa ke pherekano ea lichaba .
Ba korotse maikutlo a hao , eseng mokhoa o utloahalang oo u nahanang ka oona .
Mor’abo rōna John Chimiklis le Ted Jaracz bao ka nako eo e neng e le masoha ba bile ba sa tsoa fumana mangolo sehlopheng sa bosupa sa Sekolo sa Gileade , ba ne ba abetsoe mosebetsi oa potoloho sebakeng sa heso .
Ba hlokometse lerato , kutloano , le bonngoe tsa Lipaki esita le tlas’a maemo a lekang ka ho fetisisa , a kang lintoa tsa lehae , liqabang tsa meloko , le bora ba merabe .
Ha ho na batho bafe kapa bafe mona lefatšeng ba ratanang ho feta batho ba Molimo .
Ho na le menyetla e ka bang limillione tse 14 e khahlanong le monyetla o le mong oa ho hapa ha hao lottery .
Ka tsela e tšoanang , moapostola Petrose o ile a fa banna ba baholo ba tlotsitsoeng khothatso ena : “ Lisang mohlape oa Molimo o tlhokomelong ea lōna , eseng ka ho qobelloa , empa ka ho rata ; eseng ka lebaka la lerato la leruo la ho se tšepahale , empa ka tabatabelo ; eseng ka ho rena ka thata holim’a bao e leng lefa la Molimo , empa le e - ba mehlala ho mohlape . ” ​ — 1 Pet .
Lentsoe “ kankere ” ka bolona lea tšosa .
Ha nako e ntse e ea , ngoanana o ile a khaotsa ho sebeletsa Jehova ’ me a kena kereke hobane a batla ho nyaloa ke mohlankana eo .
“ Mohlatsoana ” ka lesakeng le leng o tla busa le Kreste leholimong , ’ me “ linku tse ling ” ka lesakeng le leng li tla phela lefatšeng la Paradeise .
Leha ho le joalo , ho ka ’ na ha nka nako e itseng hore kamano ea rōna le mofosi e loke , ’ me re ka ’ na ra se ke ra hlola re thabela katamelano e haufi e tšoanang le eo re neng re e - na le eona pele .
O ne a ke ke a mo kenya eona ka mohlolo o itseng .
Lefu la Tsoekere ke Eng ?
Le hoja ka linako tse ling batho bao ba ka bonahala eka ba molemo , ha e le hantle morero oa meea e khopo ke ho thetsa batho .
’ Musong oa Molimo , moloko oa batho o tla folisoa ka mohlolo
E ka ’ na eaba lebaka le ka sehloohong la hore Pauluse a hloee Bokreste ka ho tebileng e ne e le hobane a kholisehile hore Bokreste bo tla silafatsa Bolumeli ba Sejuda ka ho bo tsoakanya le likhopolo tse sa rateheng tsa Balichaba .
Mosali oa Adam , e leng Irena , o re : “ Lithapelong tsa rōna , re ile ra bolella Jehova boemo ba rōna le hore re ikemiselitse ho nolofatsa bophelo ba rōna haholo .
Ho ntse ho le joalo , ba bangata ba talima mantsoe a somang e mpa e le tsela e ’ ngoe ea ho bontša ho tšeha .
Mangeloi a boleloa ka makhetlo a ka bang 400 ka Bibeleng , ’ me sehlopha sa ’ ona se akarelletsa lirafime le likerubime .
O ile a ima ha a le lilemo li 17 .
Kaha kajeno ho na le baboleli ba ’ Muso ba fetang limilione tse supileng liphuthehong tse fetang 100 000 lefatšeng lohle , ho lula ho hlokahala banna ba ka etellang pele linthong tsa moea .
Linaheng tse ling re qosoa ka hore re kotsi Naheng , feela joaloka Nehemia a ne a qosoa ka hore o fetohela morena .
U tla be u nepile ha u bolela hore ka tsela e itseng ke mosebetsi oa ho tšoasa ha mohlolo o tšoanang le oo baapostola ba ileng ba o latsoa ha ba akhela matlooa a bona a sebele ka taelo ea Jesu .
Moloko oa Batho o Batla Molimo ( Buka ) , 4 / 1
Jehova o re bōpa a sebelisa Bibele , moea oa hae o halalelang le phutheho .
Ho se boletsoeng , rea hlokomela hore Pauluse o ngotse Timothea oa Bobeli bonyane ka mabaka a latelang : ( 1 ) O ne a tseba hore o haufi le ho shoa , ’ me o ne a batla ho lokisetsa Timothea nako ea ha a se a ke ke a hlola a mo tšehetsa .
Leka ho kopana le ba hirileng moo — ba kenang sekolo , basebetsi bao e leng masooa , bahlolohali , le ba bang .
“ E Fihlile ka Nako e Tšoanetseng ”
Ka mosa molebeli ea tsamaeang o ile a mo phehella hore a se lumelle boikarabelo ba khoebo ho pupetsa bomoea ba hae .
Ka linako tse ling , sechaba sa Iseraele se ile sa inehela molekong oa ho ipelaetsa ka borabele , ’ me ka nako e ’ ngoe se ile sa ba sa bua Moshe le Molimo hampe !
E ke ke ea e - ba bohlale ho hlokomoloha ho haelloa hona ke tsebo ea ho hlahloba mokuli , haholo - holo haeba motho a khetha ho phekoloa ka ho hlajoa ka linalete bakeng sa ho imoloha matšoaong a maloetse a sa foleng .
Re lokela ho bontša maikutlo afe mabapi le tsebo ea Molimo ?
Joale , seo e leng sa bohlokoa ho Jehova hase hore u etse se lekanang le seo e mong a se etsang empa ke hore u etse seo uena — moea oa hao — u ka se etsang .
Ka baka leo , Molimo , Molimo oa hao , o u tlotsitse ka ole ea nyakallo . ” — Pesaleme ea 45 : 2 , 4 , 7 .
Ho ile ha nkuka nako e teletsana hore ke khutlele bophelong bo botle ba ’ mele , empa ke ile ka latsoa bonnete ba tšepiso ea Molimo : “ Nke ke ka u tlohela , nke ke ka u lahla . ”
Ho Tlotlisa Molimo oa Tšepo , 12 / 15
Lipaki tse ling tsa Albania mehleng eo ea pele le tsona li ile tsa ithuta ho bala Segerike e le hore li ka bala Bibele kaofela .
HO IMA ha bacha , ho ba imetsa ka moroalo oa ho etsa liqeto tsa batho ba baholo .
Hape ea eletsa : “ Thabela bocha ba hao . ”
Bahlanka ba Molimo ba hloka tlhohonolofatso ea hae e le hore ba tsebe ho boloka melao ea hae e lokileng .
Batšoaruoa : Ba fetang 1 000
Haeba re batla ho atamela haufi le Jehova , ke habohlokoa hore re ithute Bibele ka sepheo se nepahetseng .
Ntate o ne a tla ba fa “ mothusi , moea o halalelang . ”
Na u arabetse ’ me ua batla matšeliso botsoalleng le Molimo ?
Empa beke pele kopano e qala ho ne ho hlakile hore ho tla ba le khanyetso .
Ed Rumsey , molebeli Homestead , o ile a bolella Tsoha !
( b ) Abrahama o ile a etsa joang ha Molimo a mo laela ?
Kajeno , histori e tummeng hampe ea Bokreste - ’ mōtoana e tsebahala hohle .
( b ) Batsoali ba bang ba fane ka litlhahiso life ?
Likopano tsa setereke tsa lefatše lohle tse nang le sehlooho sa 1990 se reng “ Puo e Hloekileng ” li ile tsa tšoareloa metseng ea Brasov le Cluj - Napoca .
Lipalo tsena li hlalosa karolo e itseng feela ea se etsahalang .
Ho tloha moo , molebeli eo o ile a ntša sethunya , a se beha hloohong ea ka , eaba o etsa hore ke lumele hore o tl’o nthunya joalokaha ke boletse qalong ea pale ena .
Motho o lokela ho nahana ka kolobetso ha a le lilemo li kae ?
Jesu o ile a supa tsela e isang tokolohong ea ’ nete le khatholohong ea meea ea rōna joang ?
Lipaki tsa Jehova li tsoela pele ho arolelana molaetsa oa Molimo o tšelisang le baahisani ba tsona Rwanda
Joale re ka khona ho etsa qeto ea hore na ke sefe seo re tla se etsa haeba re thulana le maemo a joalo .
Ha litheko li ntse li theoha , matlotlo a fela ka bosiu bo le bong .
Ho ne ho hlakile hore sena e ne e le bothata ha re e - ea le eena hohle moo a neng a lebeletsoe ho lula a khutsitse — haholo - holo libokeng tsa phutheho .
Leha ho le joalo , ho na le keketseho ea mofuta o mong e ntseng e totobala haholoanyane Taiwan — ke keketseho ea mosebetsi oa Lipaki Tsa Jehova .
Ho ne ho tšosa hobane ha u ne u utloa enjene e tima , u ne u tseba hore sefofane seo se mothating oa ho phatloha .
Ho ea ka setsebi se seng , “ lerato la bara ba motho ” ke “ lerato le bontšang kameho e mofuthu , mosa , qenehelo le le ithaopelang ho thusa . ”
Bibele e bontša hore re lokela ho ba le “ moea o thōtseng le o bonolo ” le hore re be le “ moea o khutsitseng . ”
E ne eka ntho e khōlō e tšosang e nkile mohaho ’ me e u tsukutla ka mahlakore ’ ohle .
Hangata ke ne ke tsamaea ke sa roala lieta kaha re ne re se na chelete ea ho li reka .
Ha ho mohla ho kileng ha e - ba le batho ba bangata hakana lefatšeng ba ratang Molimo ba bile ba rata batho ba bang .
Baiseraele ba habo ba lahlile borapeli bo hloekileng ’ me ba sebeletsa melimo ea Sidone , Moabe , Ammone le Filistia .
Jesu o ile a fana ka tlhaloso e latelang ho Bajuda ba ileng ba mo nyatsa ka lebaka la seo a neng a se entse : “ Mora a ke ke a etsa ntho le e ’ ngoe e le ho itsoelang ho eena , haese feela seo a bonang Ntate a se etsa . ”
Molaetsa oa Habakuke le oona o ne o le matla , ’ me o ne o bile o sa ratehe hantle feela joaloka oa Jeremia ea neng a bululetsoe ke Molimo , hore a bolele esale pele ka timetso ea Juda ea lilemo tse 70 .
Hoetla ka 1621 , Ma - pilgrim a ne a se a ruile hoo a bileng a khetha nako eo a tla leboha Molimo ka eona ha e le moo a ba hlohonolofalitse .
Litumelo tsa bolumeli ba Bababylona li ile tsa atolohela lefatšeng la India le batlileng le lekana le k’honthinente joang ?
Haeba Eric a ne a ile a phehella lipapali a ka be a ile a tuma a ba a rua .
Ba bangata ba hana ho ithuta thuto ea boitšoaro bo botle ho tsoa ho se etsahalang .
Ka baka leo , Jehova o phethahalitse tšepiso ea hae ’ me o ba tšolletse tlhohonolofatso ka tekanyo e fetisisang .
Esita le haeba uena kapa litho tse ling tsa lelapa la hao le nka hore ha ho letho le phoso ka ho ea lechatong la motho eo e seng Paki , na ho etsa joalo ho ka ama bara le barali beno ba moea hampe ?
Le hoja lingoliloeng tsa hae li ne li reretsoe ho lokolla Bajode ho itšetleheng ka litlhaloso tse eang lolo - lolo , kapele - pele ho ile ha ngoloa litlhaloso tse telele ka libuka tsa hae .
Re lokela ho hlokomela hore ha re rapela re bua le ’ Mōpi oa rōna , Ea Phahameng ka ho Fetisisa bokahohleng .
Jehova o ile a arabela : “ Ho fihlela metse e heleha , e hloka baahi , le matlo a hloka batho , le naha e senyeha , e e - ba lesupi . ”
Mongoli e mong o re bolella ka “ ho iphapanyetsa lipolotiki ho hōlang Fora . ”
O ne a thusa haholo phuthehong ea Liithuti tsa Bibele sebakeng seo .
Leha ho le joalo , hore ba tle ba thabele sena sohle , Adama le Eva le bana ba bona ba ne ba tšoanela ho ba le kamano e ntle le Molimo .
Ntate oa rōna oa leholimo , Jehova , o re fa litaelo tse ngata tse tobileng ka Lentsoe la hae , Bibele .
Ho bonolo hore batho ba utloe lentsoe lena ’ me ba arabele .
Empa mocha eena o tla hloka hore u mo tlohelle hore a habole lesheleshele leo a iphehletseng lona . — Liproverbia 6 : 27 .
Ho sa tsotellehe mohoo oa “ tokoloho qetellong , ” boemo ba sebele ba batho ke bofe ?
O ile a qala ho nyefola Lipaki tsa Jehova phatlalatsa , ka hore li sentse lelapa la hae .
Ka ho khetheha , ha ke le sekolong se phahameng , ke ile ka nahana kamoo liithuti - ’ moho le ’ na li feletsoeng ke tšepo kateng bophelong li bileng li sa thabang .
Le hoja a ne a tseba hore o tsoa Galilea , Pilato o ile a mo botsa : “ U tsoa hokae ? ”
Jesu o qala phutuho ena ka ho khetha barutuoa ba 70 ’ me a ba rōma ka bobeli .
Ho laetsana le motho ea hōle ho ka ba le mathata , empa ho ka boetse ha ba le meputso .
8 , 9 . ( a ) Ke hobane’ng ha re sa lokela ho tšoenyeha haholo ka lintho tseo re li hlokang ?
Ba ile ba bontša tumelo ho eena motheong oa bopaki bo bongata bo neng bo le teng , ’ me butle - butle kutloisiso ea bona e ile ea hōla ; liphiri tsa hlaka .
Esita le ho melata e bolotseng , ena e ne e le tokelo .
Ke ’ nete hore ho latela Jesu ha ho bonolo kamehla , ’ me joalokaha Jesu a ile a lemosa , sena se entse hore ba bang ba shoe tsamaisong ena ea lintho .
Ha re lumella Bibele hore e re tataise , re tla ba le letsoalo le hloekileng re be re khotsofatsoe ke hore re khahlisa Jehova .
Taba ke hore , baromuoa ba kereke ba ile ba re bolella hore ho fosahetse hore re noe lino tse tahang .
Ke hobane’ng ha Petrose a sekamela ‘ kamehla ho hopotseng ’ barab’abo ?
( To Teach — The Journey of a Teacher ) Hona tabeng eo , Janet Reno , eo e kileng ea e - ba ’ muelli - kakaretso oa molao oa United States , o itse ka November 2000 : “ Re ka romela batho khoeling . . . .
4 / 8 Ho ba Motsoalle oa Molimo , 3 / 8
SEPTEMBER ke khoeli ea kotulo ho balemi , empa mosebetsi oa kotulo o bohlokoa haholoanyane o ile oa hohela letšoele le leholo Holong ea Kopano ea Lipaki tsa Jehova e Jersey City , mose ho Nōka ea Hudson ha o tloha Motseng oa New York , ka September 8 , 1991 .
Jehova o ile a laela moprofeta Jeremia hore a fane ka molaetsa oa kahlolo o khahlanong le Juda le Jerusalema .
Bo - khaitseli ba tšepahalang ka phuthehong ba phetha mosebetsi o moholo oa bohlokoa o hahang .
Hangata ba etsa joalo ba ntse ba tšohile litšisinyeho tse nyenyane tsa lefatše tse latelang .
Paki e ’ ngoe e neng e boetse ho batho ba thahasellang e ile ea kopana le mora oa mosali ea neng a bontšitse thahasello nakong e fetileng ’ me ea hlalosa hore e amehile ka hore na baahelani ba ikutloa joang ka mor’a tlokotsi e sa tsoa etsahala .
Ke ile ka tseba ho se ho fetile likhoeli hore ba bolailoe ka sehlōhō .
Hape , u ka ’ na ua khona ho hulela ba bonolo borapeling ba ’ nete , ha u ntse u etsa tšebeletso ena .
Ha Moshe a le haufi le ho shoa , o ile a kōpa Molimo hore a khethe motho ea tla mo hlahlama e le hore Baiseraele ba se ke ba “ tšoana le linku tse se nang molisa . ”
Litšepiso tsa hae tsa ho tlisetsa batho ba hae mahlohonolo a sa feleng ruri li tla phethahala . — Joshua 21 : 45 .
Ba bang ba batla ho ba bo - pula - maliboho kapa ba sebetse moo ho hlokehang bahoeletsi ba eketsehileng .
Seo se ile sa boleloa ke lipaki tse boneng ka mahlo ha Jesu hang - hang a folisa ka mohlolo monna ea neng a shoele litho .
Seithuti sa lekholo la bo17 la lilemo Leibniz se iqapetse lentsoe lena bakeng sa ho leka ho sireletsa Molimo : theodicy , kapa “ ho lōkafatsa Molimo . ” — Bona leqephe 6 .
Re ke ke ra Sitisoa ke Khanyetso
Mohlomong lelapa leo le hloka ho thusoa ho fihla libokeng .
Ka Bibeleng .
PELE : KE NE KE NYETSE SETHEPU KE BILE KE SA BATLE LIPAKI TSA JEHOVA
A sebetsa ka chelete e ka tlaase ho limilione tse peli tsa lidolara bakeng sa phuputso ea ente e thibelang lefu la pholio , rasaense oa Leamerika Jonas Salk le bafuputsi - ’ moho le eena ba ile ba sehla lihora tse ngata laboratoring ba etsa liente tse ngata - ngata , ba etsa liteko ka makhetlo .
Leha ho le joalo , molemong oa Bakreste ba neng ba tla be ba le Jerusalema ka nako eo , Jesu o itse : “ Joale ba leng Judea a ba qale ho balehela lithabeng , ’ me ba ka hare ho eona a ba tlohe , ’ me ba libakeng tse ka thōko a ba se ke ba kena ka har’a eona . ”
Gestapo e ne e ferekantsoe ke ho pepesoa hona le ke bokhoni ba Lipaki ba ho atleha ho e pepesa .
Lipaki tsa Jehova li lumela hore Jehova ke Molimo ea matla ’ ohle le hore Jesu ke Mora oa hae , eseng karolo ea melimo e meraro ho a le mong .
Manakana a nako a holimo karolong e ka morao a ne a bontša kamano e teng pakeng tsa likhoeli , lilemo le linako tsa Lipapali Tsa Bagerike
Ka sebele ho tšaba Jehova hoa sireletsa !
Ho e - s’o ho ee kae , mocha o ba leqe ho ea sekolong .
Eaba botho ba ka boa fetoha ’ me ka qala ho tšoara monna oa ka le bana ba ka hampe .
2 , 3 . ( a ) Ke matla afe ao Jehova a ileng a a sebelisa lilemong tse ngata - ngata tse fetileng ?
Thapelo e tiileng le e tobileng mabapi le mohato ona oa bohlokoa e ka ba susumetsa ’ me ea ba fa sebete sa hore ba lumellane ka botlalo le Lentsoe la Molimo , ba etse boinehelo bo feletseng ho Jehova Molimo ’ me ba kolobetsoe .
O talima lenyalo e le kopano e halalelang , ea ka ho sa feleng .
Leha ho le joalo , Mak’hatholike a mang a ikutloa hore morero ona ke “ leano la Babishopo ho fetola Makh’atholike ho ba batho ba emelang lehlakore le itseng la lipolotiki , ” ho hlalositse mobishopo oa Johannesburg , Reginald Orsmond .
tungsten W 74
Kahobane Antonio a thahasella haholo mosebetsi oa hae , a tela lelapa la hae bakeng sa mosebetsi .
Aesculapius
Ba ka thusoa joang ?
Har’a liphutheho tse hlano tsa sebaka seo tsa Lipaki Tsa Jehova , tse tharo li sehlopheng sa Tongatapu se nang le baahi ba bangata , e ’ ngoe e Ha’apai ’ me e ’ ngoe e Vava’u .
Lerato .
Ba lokela hore ba se ke ba leka le ho sebelisa lintho tse joalo , hobane ha ba bohele - hele mabapi le lintho tse tebileng tsa Satane .
Ka qala ho nahana lintho tse ngata .
Ka mor’a lilengoana li se kae , haeba monna a khona , o tlisa mosali e mocha lapeng , ea ntseng a le mocha , eo e tlang ho ba eena thatohatsi ea hae .
Ba tšoanelehang bakeng sa kolobetso baa amohela hore ke ka Jesu Molimo a faneng ka “ thekollo e le phapanyetsano bakeng sa ba bangata . ”
Daniela o ile a tsoela pele ho re : “ Leha ho le joalo , ke ne ke bona seo e le ho phethahala ha boprofeta ba Bibele , hobane ke ne ke ithutile hore Jesu o itse balateli ba hae ba ne ba tla hlouoa ba be ba hlorisoe ka lebaka la lebitso la hae .
Esau ea eba setsomi se masene , motho oa linaha ; Jakobo eena ea e - ba motho ea se nang mokhoa , ea lulang litenteng .
Jesu o ile a lokolla batho ka litsela life ?
Ho e - na le hoo , ke “ limpho tseo e leng banna , ” tse fanoeng ke Jehova hore li u thuse .
O bile o ba arolela litokelo tsa hae .
Ezekiel ea lilemo tse ka bang 20 , o re : “ Qalong ke ne ke ikutloa joaloka motho ea khannang koloi empa a sa tsebe moo a eang .
Ha ho le joalo , ke re’ng ?
Mopesaleme Davida o ile a ngola : “ Mahlomola a ea lokileng a mangata . ”
Bakreste ba ’ nete ba bitsoa “ batsamaisi ba khabane ba mosa o sa tšoanelang oa Molimo o bontšitsoeng ka litsela tse sa tšoaneng . ”
Histori e ’ nile ea fana ka bopaki ba ho phethahala ha bona .
Hape li hasitse litaba tse molemo tsa ’ Muso ka lingoliloeng .
Nahana le ka Abigaile , eo e neng e le mosali oa Nabale .
Ke hobane’ng ha le sa tšehetse ntoa ? ”
Nakong eo , Stavros le Dora Kairis ba ile ba re fa bolulo ka tlung ea bona .
JOSEBA ea lulang Spain , o ile a botsoa hore na ke hobane’ng ha a ile a kena mokhatlong oa baitseki .
Na ho ka etsahala hore ebe melaetsa ee ea kajeno e ntlafatsa Bibele ?
Jehova o na le bahlanka ba bangata ho pota lefatše , ’ me kaofela ha bona ha ba tšoane .
E le hore re utloe hore na ba bang ba ne ba hlalosa lintho joang khale , ha re khutlele lekholong la bone la lilemo B.C.E . , hoo e ka bang lilemo tse lekholo ka mor’a hore ho qetoe ho ngoloa Testamente ea Khale — e leng karolo ea Bibele ea Mangolo a Seheberu .
Baeti ba ne ba ka bona Bibele ea New World Translation ka lipuo tse 31 tseo e hatisitsoeng ka tsona .
Phapang ee e bakiloe ke eng ?
Ka mohlala , lik’homphieutha li sebelisa lipalo - palo hore li phethe mosebetsi oo kaofela .
‘ Bolela Lentsoe la Molimo ka Sebete ’
Peō ea ’ nete e ile ea sala pelong ea hae , ’ me hoo e ka bang selemong se fetileng o ile a amohela ho ithuta Bibele le e mong oa Lipaki tsa Jehova ’ me a qala ho ea libokeng .
Bohlokoa ba sena bo bonoa ho seo Jesu a se buileng ka baeta - pele ba bolumeli ba Bajode ba mehleng ea hae .
Ka mohlala , Genese 3 : 8 , ( NW ) e re bolella hore e ne e le “ karolong ea letsatsi e moea o pholileng ” ha Jehova a ne a bua le Adama le Eva letsatsing leo ka lona ba neng ba entse sebe .
Kajeno , baruti ba Bokreste - ’ mōtoana ba ipolela e le balisa ba seo ho boleloang hore ke phutheho ea Bokreste , empa boemo ba eona ba ho kula moeeng bo paka hore baruti bana ba tšoana le batho ba khopo ba neng ba ikhakanya ba neng ba sa tsotelle batho ’ me ba ba tšoere hampe ha Jesu a le lefatšeng .
Chelete eo a neng a e sebelelitse ka thata e ile ea fela ka potlako .
E se e le eena ea u laolang .
Lilemong tsa bo - 1400 , Christopher Columbus ea neng a pota lefatše ka nako eo , o ile a nahana hore o haufi le ho fumana serapa sa Edene nakong eo a neng a fihla sehlekehlekeng sa Hispaniola , seo hona joale e seng e le Dominican Republic le Haiti .
Ho phethahala ha Tšenolo 16 : 16 le Daniele 2 : 44 ho u ama joang ?
Ipehe maemong a motho e mong ka ho talima litaba ho ea ka pono ea motho e mong .
Leka ho sebelisa chate ena borapeling ba lelapa !
Batsoali ba Bakreste ba lokela ho thaba haholo ha bana ba bona ba kolobetsoa , empa ka linako tse ling thabo eo e tsamaea le ho tšoenyeha .
Acta ke thuso ea ho utloisisa liketsahalo tsa nakong e fetileng , e bontša ka ho hlaka seo litho tsa Mokhatlo oa Bonngoe ba Bara ba Motho li neng li se lumela .
’ Mè ea Tšabang Molimo
Ke hobane’ng ha ba le ka tsela eo ?
Selemong sa ka sa bobeli sekolong sena , ke ile ka etela batsoali ba ka nakong ea phomolo ea sekolo .
Le hoja Hodgkinson a re hopotsa hore lekhoba le tla hlōla ntoeng ea lona ha feela le “ hlokomela hore ho na le molemo oa ho ikhula — le hore ho na le se eketsehileng seo bophelo bo ka fanang ka sona ho feta boiteko ba ho leka ho khotsofatsa bokhoba bona . ”
Leha ho le joalo , ka thuso ea Jehova ka mehla re ’ nile ra khona ho lokisetsa litlhoko tsa rōna .
Kapa ntate oa lelapa le eena a ka ’ na a bona ho hlokahala hore a be le inshorense ea ha a ka shoa , a kula , a holofala kapa a etsahalloa ke ntho leha e le efe , e le hore a sireletse ba lelapa la hae .
Libakeng tse ling litonki li hula likosekara , kapa ka linako tse ling litonki tse peli li hula kariki e batlang e le khōlō .
E tla ba thabo e kaakang ha batho bana ba boela ba kopana le baratuoa ba bona !
Phetla Bibele ea hao , ’ me u bale litemana tse bontšitsoeng e le hore u ka bona seo Jesu le baapostola ba hae ba ileng ba se ruta mabapi le taba ena ea bohlokoa .
Motho eo a re , “ Robby , ke ’ na Katie .
Molimo o ile a talima tšobotsi ee ea borapeli ba Baale joang ?
Ho etsa joalo ho tla u thusa hore u be le kamano e ntle le ba bang le boemo bo botle ho Molimo .
Na ha ua ka ua hlolloa ke ho bona linaleli tse ngata - ngata tse bonahalang sepaka - pakeng se lefifi ?
MOCHA e mong ea bitsoang Jackie o re : “ Ke nahana hore ho bōpeletsoe ka ho rōna ho rata ’ mino hobane o ka tsebahatsa maikutlo a hao .
O ile a bona mosali a beha lebone le bonesitsoeng holim’a seluloana sa lebone eaba o sebelisa hoo e le papiso .
Liphoofolo tse ruuoang lapeng li tsoela le batho ba hōlileng molemo .
Mongoli e mong o itse’ng ka Lipaki tsa Jehova , hona li eketsehile hakae ?
Selemong se hlahlamang seo , ke ile ka ipabola ka ho matha lebelo la sekaja la limithara tse 100 ka nako e khutšoanyane ho feta baatlelete bohle ba Finland .
Ha e le hantle , re ile ra etsa qeto ea ho bula maliboho .
Jehu o ne a batla ho tiisa hore ho ke ke ha e - ba le khanyetso e joalo .
( a ) Ke eng e ileng ea etsa hore maemo a fetohe ka tšohanyetso har’a lira tsa Nehemia ?
Auschwitz
Ha melao ea kereke e ntse e eketseha , e ile ea hlophisoa ka libuka .
Ha ho se ho se motho e mong eo a ka mo bolaeang , bahlōli bana ba ile ba etsa mokoloko ho pholletsa le literata tsa motse . . . ho ea Kerekeng ea Holy Sepulchre ho ea leboha Molimo . ”
Ke hobane’ng ha baruti ba Bokreste - ’ mōtoana ba tšoana le baprofeta ba bohata ba Jerusalema , hona see se amme litho tsa likereke joang ?
Ka hare ho eona , ’ Mōpi oa leholimo le lefatše , e leng Molimo ka boeena , o senola hore na ke mang le hore na lebitso la hae ke mang .
Sally o re : “ John o ne a imetsoe ke boikutlo ba ho ba molato .
Libukeng tseo e tsitlella hore boikoetliso , phepo e nepahetseng le ho phela ka mokhoa o hloekileng li ka ntlafatsa bophelo ba motho ’ me mohlomong tsa lebisa bophelong bo bolelele .
Mopesaleme oa botsa : “ Mohlankana o tla hloekisa tsela ea hae joang ? ”
Hangata re ne re thulana le ba chesehelang bolumeli ka ho feteletseng , ba hlahafalitsoe ke baprista ba Orthodox .
Ho phaella moo , bana ba banyenyane ba lumela habonolo hore Molimo o teng .
O ile a ba a bona esale pele hore Cyruse o ne a tla fumana menyako e meholo ea motse e mamati a mabeli e tlohetsoe feela e sa koaloa , e leng ho neng ho tla etsa hore Cyruse a hlōle habonolo . ​ — Esaia 44 : 24 – 45 : 7 .
Haeba u ntse u lula ho sona u ka lokisetsa hore mokhatlo o tle o se nke ha u se u hlokahetse .
Ea pele , o fana ka tataiso ka Lentsoe la hae le bululetsoeng , Bibele .
O re ha ho mohla batsoali ba hae ba ileng ba mo qobella hore a kolobetsoe .
Ha e le hantle , sekhohola seo se sa lebelloang e ka ’ na eaba se ile sa etsa hore liphoofolo tse se nang palo le batho — libōpuoa tse matla haholo ho feta palesa leha e le efe — li mathele ho ea itšireletsa .
Motho a ka nona habonolo ha a bolela mona !
Leha ho le joalo khatello kelellong ha e le hantle hase ntho e mpe ka boeona .
□ Ke hobane’ng ha boitšoaro ba Mokreste mabapi le batho ba khaotsoeng bo fapana le boitšoaro ba hae ka baetsalibe ba lefatše ?
Hona joale Jehova o etsa liketso tse khōlō le tse lokeloang ke thoriso mabapi le mosebetsi oa rōna oa ho bolela .
Ho kukunela ha litulo le ho ngongoreha ka tsa letsatsi leo ho ne ho tla tloha ho lebaloa ha bashebelli ba bohile lipapali tsena tse behang bophelo kotsing .
“ Qetellong ke ile ka khathala .
CLOUDBERRY ( Rubus chamaemorus )
Ka sebele , Jesu o lebeletse hore batho bohle ba mo nkang e le Morena oa bona , ba phelele mantsoe a bona joaloka moapostola Pauluse .
Joaloka Kore , re ka ’ na ra honohela ba nang le litokelo tseo re li lakatsang .
Gandhi bakeng sa batho ba maemo a tlaase .
Na u se u kile ua kopana le batho ba semelo se fapaneng le sa hao ?
Oa hopola : “ Ka linako tsohle ho ne ho e - na le seo batsoali ba ka ba lokisetsang hore re se etse .
Kahoo Honorata o ile a fumana karabelo .
Na ho na le lerako le nang le ’ mala o khanyang kapa sebaka se hlakileng se se nang letho se ka sebelisoang bakeng sa ho nkela batho lifoto ?
□ Ke ka tsela efe e ikhethang Jesu a bonahatsang botho ba Ntate oa hae ?
Mokhatlo ona feela o tla pholosoa o phela o ‘ tsoa mahlomoleng a maholo . ’ — Tšenolo 7 : 14 .
Joaloka “ baokameli ba liphiri tse halalelang tsa Molimo , ” ba ne ba tla etsa barutuoa le ho ba abela lijo tsa moea . — 2 Ba - Korinthe 5 : 20 , NW ; 1 Ba - Korinthe 4 : 1 , 2 , NW .
Eka nka be ke ile ka fumana thuso kapele . ”
O ile a hohela Bajuda le Balichaba ba bangata .
Pauluse o ile a thulana le matšoenyeho afe Lystra ?
Ba bang ba bolela hore lilemong tsa bo - 1950 , li - dolphin tsena li ne li khannela litlhapi karolong e sa tebang ea metsi — ’ me mokhoa ona o ntse o ka bonoa le kajeno .
Ho phaella moo , phapang e teng tabeng ea setso le puo e ka etsa hore batho ba nahane ba be ba etse lintho ka litsela tse sa tšoaneng .
Lentsoeng la hae , Bibele , Jehova oa botsa : “ Na ’ na ke thabela lefu la ea khopo , ho e - na le hore a furalle litsela tsa hae , ’ me a phele ? ”
Ho ne ho hlokahala lishaoara le lisinki tsa metsi a chesang le a batang , matloana hammoho le motlakase .
Ho totobetse hore ke eona tsela eo ka eona Ruthe oa Moabe a neng a talima ’ mè - matsale oa hae oa Moiseraele , Naomi .
Bibele e buile ntlha ena lilemong tse likete tse fetileng ha e re : “ Ea tsamaeang le ba bohlale o tla hlalefa ; empa ea tloaelaneng le maoatla o tla senyeha . ” — Liproverbia 13 : 20 .
Metsi a Sehlekehlekeng sa Fraser le ’ ona a tletse ka lintho tse ngata tse phelang , ho akarelletsa le maruarua a leetong ho tloha leoatleng le batang haholo la Antarctic ho ea Great Barrier Reef , moo a fihlang a tlōlelana le ho tsoalla teng .
Ha a ne a bua le baeta - pele ba bolumeli ba neng ba ikemiselitse ho mo bolaea , o ile a re : “ Le tsoa ho ntat’a lōna Diabolose , ’ me le lakatsa ho phetha litakatso tsa ntat’a lōna .
Leha ho le joalo , tlhokomeliso ke ena : Hangata sena se bolela ho ba letsatsing ka ho eketsehileng .
Kajeno , lintlha tseo re li hlokang e le hore re ka rapela Molimo “ ka moea le ka ’ nete , ” ke karolo ea lintho tseo a li ngotseng ka Lentsoeng la hae .
Leha ho le joalo , thuto e fokolang e eketsa bofutsana haholoanyane .
* Bana ba qetang nako e ngata le batho ba hōlileng ba ba le kutloelo - bohloko haholoanyane ’ me ba ananela batho ba baholo .
Ha a sa le mocha , o ne a lumela thutong ea ho iphetola ha lintho , empa hamorao o ile a etsa qeto ea hore lintho li bōpiloe .
Diabolose o tšoana le batho ba ileng ba fetohela Jehova mehleng ea Moshe .
ea October 8 , 1988 le ea April 8 , 1995 .
Joale lelapa leso le ne le se le falletse Bandung , e leng motse o moholo o Java Bophirimela .
“ Molimo ha a leeme , empa sechabeng se seng le se seng motho ea mo tšabang le ea sebetsang ho loka oa amoheleha ho eena . ”
Ho bona ngoana a le bohloking — haholo - holo eo u amanang le eena haufi - ufi — ke ntho e utloisang bohloko .
Leha ho le joalo , Lentsoe le bululetsoeng la Molimo le re , “ moloko oa batho o [ ke ke ] oa fumana mosebetsi oo Molimo oa ’ nete a o entseng ho tloha qalong ho isa qetellong . ” — Moeklesia 3 : 11 .
2 : 7 .
․
Baratani ba bangata ba se ba khetha ho lula hammoho ba sa nyalana . ” — THE GUARDIAN WEEKLY , BRITHANI .
Empa ke ikemiselitse hore ke se ke ka felloa ke tšepo .
Ha e le hantle , o ne a le matla mantsoeng le liketsong tsa hae . ”
Lilemong tsa morao tjena ha ke sa bona hantle ka lebaka la lera la mahlo .
Bibele e na le ‘ lipolelo tsa Molimo ’ tseo Jesu a itseng rea li hloka hore re ipoloke re phela moeeng .
Kamohelo eo ke ileng ka e fumana ho Lipaki tsa Jehova e ne e le ea bohlokoa haholo .
Mongolo oa cuneiform o moqomong oa letsopa oa boholo - holo o bontšitsoeng mona o lumellana le tlaleho e ’ ngoe ea Bibele .
Palo ea baahi ba kajeno ba Chaena le India feela ea tšosa — kakaretso e kopaneng e ka bang limillione tse 1 800 !
Ka letsatsi leo ke ile ka nyalana le Mildred Willett ’ me haesale ho tloha ka nako eo e bile setšehetso se tšepahalang ho ’ na tšebeletsong ea Bethele .
Lehae la ka , lelapa le baratuoa li bohlokoa hakae bophelong ba ka ? ’
Upper war scene : U.S .
• Re bontša joang hore re hlompha khalalelo ea Kreste ?
( b ) Tsela eo re utloisisang matla a Jesu ka eona e lokela ho ama joang pono ea rōna ka taelo ea ho etsa barutuoa ?
Ke tlotla ho tseba melao ea Jehova , ho e mamela le ho phela ka tsela e tlotlisang lebitso la hae .
Le hoja Jesu a ne a le mosa , ho ntse ho le joalo ka tieo o ne a tšehetsa se nepahetseng mahlong a Ntate oa hae oa leholimo .
Ha e le hantle , Molao e ne e le “ motataisi ” oa nakoana , ea ba lebisang ho Kreste . — Bagalata 3 : 23 , 24 .
Ke joang e ka u tsoelang molemo le lelapa la hao ?
Ba bang ba qala ho ea ho litsebi tsa bonohe kapa ho lingaka tsa litaola .
Leha ho le joalo , Jehova o fana ka tataiso e hlakileng ho ba ikemiselitseng ho e latela .
Ke hobane’ng ha lipelo tsa ba bang li e - s’o tsitse , ’ me hoo ho ka ’ na ha lebisa ho eng ?
Ke ne ke bona a le molelele a bile a le sephara joaloka monyako oa lapeng o ka pele .
Hona re ka ema re tiile joang khahlanong le ’ ona ?
O ne o pota - potile Mediterranean ka ho feletseng , eo o neng o e bitsa Mare Nostrum ( Leoatle la Rōna ) .
Kahoo haeba ka lebaka le itseng u sa khone ho fumana tšehetso lapeng , ho lokile ho fumana motsoalle eo u ka mo phetlelang sefuba , empa tiisa hore o na le phihlelo bophelong le tsebo ea melao - motheo ea Bibele .
Ho ile ha nka lilemo tse fetang 200 le ho sibolloa ha libuka tse ling tsa khalenyana tse ngotsoeng ka letsoho ho tiisa hore phetolelo ea “ eo ” kapa “ e leng ea ” ke eona e nepahetseng .
Khohlano eo ebile selelekela sa mofuta o mocha oa ntoa , ntoa ea pele e akarelletsang eo batho ba kileng ba ba le phihlelo ea eona .
15 Tumelo e Phelang Har’a Tlokotsi
Ho batla thuso ho baholo ba khethiloeng ke moea ka phuthehong ke tsela e ’ ngoe ea ho bontša hore re itšetlehile ka Jehova .
Bona buka U Ka Phela ka ho sa Feleng Paradeiseng Lefatšeng , khaolo 25 .
‘ Phehellang Lintho Tse Tlisang Khotso ’
Ho boleloa hore o tsamaile sebaka se fetang lik’hilomithara tse 1 600 000 e le morupeli oa phatlalatsa ’ me o ne a fane ka linehelano tse fetang 30 000 pele ho lefu la hae ka 1916 .
Kaofela ha rōna re ananela haholo tšepo le lefa tseo re li filoeng ke Molimo .
Ha ke sa batla ho ba boemong boo hape .
E ile ea fa banna ba kang Abele le Noe lebaka la ho lumela hore Molimo o ne a tla khutlisa mahlohonolo a ileng a lahloa ke Adama .
Ho sa tsotellehe hore na mofosi ke monna kapa mosali , ho senyeha ha lenyalo ho ka tlisa masisa - pelo a maholo ho molekane ea se nang molato , bana le batho ba bang .
Nahana hape ka ho fapana ho hoholo ha lirafshoa tsa lik’hemik’hale .
Kaha ntate oa Timothea e ne e le Mogerike ’ me ho hlakile hore o ne a sa lumela , e ne e le ’ mè oa hae oa Mojuda , Eunise le nkhono oa hae , Loise ba ileng ba koetlisa moshemane enoa ‘ ho tloha boseeng ka lingoliloeng tse halalelang . ’
Phuputsong e ’ ngoe , banana ba etsang karolo ea 58 lekholong ba pakeng tsa lilemo tse 5 le 17 ba ne ba lumela hore ba batenya , athe ha e le hantle , e ne e le ba etsang karolo ea 17 lekholong feela ba neng ba hlile ba le batenya .
La 30 Phupjane la fihla , le bata le bile le le moea !
Leha ho le joalo , bahlanka ba ’ nete ba Jehova Molimo ba inehetse “ tšebeletsong ea lentsoe . ”
Ebe o fetola mabenyane ana lintho tse ke keng tsa ba hopotsa manyalo a bona a qhalaneng .
Linako tsa lithuto tsena li ka fapana ho ea ka mofuta oa khoebo kapa mosebetsi o khethiloeng .
Ho bonahala eka Ruthe o ile a ithuta ka Jehova ho monna oa hae kapa ho Naomi .
Batho ba bangata ba nka hore ho hloeka ke feela ho hloka litšila kapa ho se silafale .
Livideo tsena tse nkang metsotso e meraro ho isa ho e mehlano , li ka ’ na tsa nyakallisa bashebelli joalokaha eka ba konsareteng ea ’ mino le ho bontša batho libini tseo .
O ile a se fa buka ea Is There a Creator Who Cares About You ?
Tumelong ea Mak’hathari , pholoho e ne e sa itšetleha ka sehlabelo sa thekollo sa Jesu Kreste , empa ho e - na le hoo ka consolamentum , kapa kolobetso ea moea o halalelang .
Ke ne ke e - na le lipotso tse ngata haholo ka seo ke se balang .
Ke tla tšollela moea oa ka esita le holim’a bahlanka le holim’a makhabunyane matsatsing ao . ”
Hoba a itšoantše le “ motho ea etang , eo eitseng hobane a bitse bahlanka ba hae , a ba neela letlotlo la hae , ” Kreste o ile a phaella : “ Tšiu tse ngata ha li fetile , morena oa bahlanka bao a fihla , ’ me a hlahloba litaba le bona . ”
Ho tloha ka nako eo , Bakreste ba tlotsitsoeng ba ’ nile ba phatlalatsa lebitso leo lefatšeng ka bophara ho feta leha e le neng pele .
Le hoja re feta litekong tse sa tšoaneng , re lula re thabile ’ me re bolela litaba tse molemo ka cheseho .
Nakong eo , barab’abo rōna ba ka bang 20 ba ne ba le teronkong Adelaide ba tšoaretsoe ho se nke lehlakore , ’ me ka mor’a nakoana ke ile ka koalloa le bona .
Ka puo ea tšoantšetso , re tsoka makala a palema , re thoholetsa Molimo e le ’ Musi oa Bokahohle re kopane ’ me ka thabo re bolela ka pel’a leholimo le lefatše hore poloko ea rōna ‘ re e kolota ’ eena le Mora oa hae , Konyana , Jesu Kreste .
Mekhatlo e phatlalatsang e romella melaetsa ea eona e hanyetsang .
✔ NA Ll NGATA HAHOLO ?
O ile a re sebaka seo ke “ lefatše le sa tsejoeng . ”
U ka ba tšelisa ka ho re’ng kapa ka ho etsa’ng ?
Jubile ea Bokreste E Fihla Tlhorong Lilemong tse Sekete
Ke joang re neng re ka tseba baena ba motse - moholo oa Japane ?
A sebelisa Davida le baprofeta ba bang , Molimo o ile a ’ na a senola ho eketsehileng ka Mesia .
Pele ho bofelo ba tsamaiso ea lintho , balateli ba ’ nete ba Jesu ba ne ba tla bolela “ ’ nete ea litaba tse molemo ” lefatšeng ka bophara .
’ Maraka oa Piraeus ( koung ea Athene ) o ne o lula o e - na le lijo tse lekaneng tse ncha bakeng sa ho fepa motse hammoho le lebotho .
Ho itšetlehiloe ka mehlala ea Jehova Molimo le Jesu Kreste , re ka sebeletsa ho ba le botho ba bomolimo .
Sena ke sona seo Jehova a se etsang ka “ thepa [ ea hae ] e khethehileng . ”
Haeba ho joalo , le bontša hore le bohlale e le ka ’ nete .
Phutheho ea Nafisi , Malawi , ea tlaleha : “ Kaha joale re na le Holo ea ’ Muso e loketseng , e fana ka bopaki bo botle .
․ ․ ․ ․ ․ o sepheo
Adama le Eva ba ne ba tla shoa hafeela ba fetohela Molimo ’ me ka tsela eo ba hlōloa ke teko .
Bona sehlooho sa Molula - Qhooa se reng “ Ba Alosa Linku tse Nyenyane ka Kutloelo - bohloko , ” September 15 , 1993 , maqephe 20 - 3 .
Ke eng e neng e ameha mosebetsing oa boholo - holo oa ho hloekisa ?
Oa hopola : “ Ka mor’a moo , ha kea ka ka hlola ke tsotella bophelo ba ka .
Har’a bana ke Zakea , molaoli oa ba - lekhetho Jeriko le ho e pota .
Setsebi E .
Mebuso e mengata ea batho e sebetsa ka thata ho ruta baahi ba eona .
Coati — Tseba ka Phoofolo Ena e sa Tloaelehang
Na kannete ba lokela ho utloa bohloko bakeng sa ho hlakisa ntlha e itseng ea molao ? ’
Ke Ile ka Hlōleha ka Makhetlo Empa Qetellong ka Atleha 12
Hlokomela hore na Molimo o tšepisa eng Lentsoeng la hae .
Ho tloha lilemong tsa pele tsa bolumeli bo bocha , re bona batšehetsi ba bona ba nkela molimo oa letsatsi ( Phoebus Apollo ) sebaka ka Moprofeta Elija , ba haha likereke holim’a lithako tsa litempele kapa litempelana tsa boholo - holo tsa molimo ona kapa pel’a tsona , haholo - holo holim’a maralla le lithaba , sebakeng se seng le se seng moo Bagerike ba boholo - holo ba neng ba hlompha Phoebus Apollo ea fanang ka leseli . . . .
Hape e sebelisetsoa ho thusa batho ba hlahetsoeng ke likoluoa , ho fetolela lingoliloeng tsa rona le livideo le ho haha Liholo Tsa ’ Muso .
Ka letsatsi le leng moruti oa kereke ea hae o ile a phahamisa sengoliloeng se seng sa rōna eaba o bolella bohle ba teng hore ba se ke ba se bala hobane se tla ba furallisa tumelo ea bona .
Likhakanyo li bontša hore lenane la ba nang le AIDS le tla tsoela pele ho eketseha ka sekhahla .
Ntate oa teng , e leng Joe McGrath , o ne a re ruta Bibele hammoho le barali ba hae ba bararo .
O ile a boela a lumela ho khanneloa thuto ea Bibele ke e mong oa banna ba phutheho .
O ile a re ka bohale : “ Ke tla chesa le ntlo ena ! ”
Lehlabula la mona le chesa hoo hangata mocheso o fihlang ho 40 ° C !
Molimo ke Mohloli oa matla a maholo .
Basali ba Jerusalema ba bona eng ha ba tsoela ka ntle ?
( b ) Fana ka mehlala e ka Mangolong e ka re thusang ha re lokela ho etsa liqeto tse boima .
Har’a lintho tse hlokometsoeng e ne e le ‘ ho ja haholo ha batsoali , ho se bue , ho robala kapele , ho se lumelise ha ba tla lapeng ba tsoa mosebetsing , ho halefela e mong le e mong , ho hlokomoloha lipotso tsa hao , ’ le ‘ ho tonela TV mahlo ka mokhoa o sa bontšeng thahasello . ’
Ho latela tlaleho e bululetsoeng , ‘ letlalo la sefahleho sa [ Moshe ] le ne le khanya , ’ me [ batho ] ba ne ba tšaba ho mo atamela . ’
LEQEBA LE HLOOHONG
Leha ke thimola feela , lesapo le ne le ka ’ na la tletlerana .
Joale ho qetela tlhaloso ea Hawaii , motho a ka nahana hape ka mokete oa semetletsa oa batho ba Polynesia oo ho oona ho nang le phaenapole , sejo se bitsoang poi se entsoeng ka likotolana tsa semela sa taro , salate ea tlhapi ea salmon , hammoho le kolobe e feletseng e phuthetsoeng ka makhasi a sefate sa banana ea ntan’o pheheloa fatše .
Bukana ea Ha Eo U Mo Ratang A E - shoa e araba lipotso tse kang e reng : Nka phela le ho sareloa ha ka joang ?
E ile ea romeloa Engelane ho tsoa k’honthinenteng ea Europe ’ me ka potlako feela ea tuma haholo .
Pauluse joale a re : “ Ho ngoloe [ lethathamong la ba amohelang thuso ea lichelete ] mohlolohali eo lilemo tsa hae li sa haelleng ho phetha mashome a tšeletseng . ”
Ha re ntse re tsilatsila , o re bontša hore o tla re selakha haeba re hana ho mo fa tsona .
Ba bang ba ka ’ na ba ikutloa hore , ‘ Litšelo tsa mali li kotsi , empa na ho na le mekhoa leha e le efe e meng ea phekolo e ka sebelisoang ? ’
O hopola hore kopanong ea potoloho ea pele eo a bileng ho eona — ea Hokkaido kaofela — ho bile teng ba 70 feela .
Tiisa hore ntho eo u khang metsi ka eona e hloekile .
Kahoo , tlaleho ea boboleli bo chesehang le mohlala o motle oa boitšoaro ba Lipaki tsa Jehova tsa Italy li thusitse ho felisa lehloeo le tobaneng le tsona . — Matheu 5 : 14 - 16 ; 1 Petrose 2 : 15 .
Kaha ka ho utloahalang Jakobo o khathatsehile , o batla hore Jehova a mo tiisetse hore lelapa la hae le tla atleha naheng e ka mose ho Nōka ea Jordane .
Ka tsela eo u ka talingoa u le ‘ mohlala ho ba tšepahalang . ’ — 1 Timothea 4 : 12 .
Bryant G .
La pele , ka lithapelo tsa rōna re lumela hore lintho tsohle tse ntle li tsoa ho Molimo .
Batla ’ me u bone hore ha ho moprofeta ea tla hlahisoa Galilea . ” — Johanne 7 : 1 , 10 , 32 , 45 - 52 .
( 5 : 1 - 11 ) Ba ile ba rekisa tšimo ’ me ba ipolokela chelete e ’ ngoe empa ba etsa eka ba e file baapostola kaofela .
Ba bacha le ba hōlileng ba ne ba feta literateng tsa motse ba halefile , ba siea ba entse mophula oa tšenyo e neng e bontša liphello tsa lebala la ntoa .
Nahana ka matsatsi a Noe .
Ho li khaola manaka ke o mong oa mekhoa e fapa - fapaneng e reretsoeng ho khaotsa tloaelo ea ho li bolaea ntle le tumello .
Ha ho ne ho liheloa libomo motseng oa Hargeysa , baahi ba ile ba tlameha ho baleha .
Nakong ea “ palesa ea bocha , ” litakatso tsa botona le botšehali li matla .
Ha motho oa pele , Adama , a ne a utloa mantsoe ana , o ne a tseba seo a lokelang ho se lebella .
Exoda 36 : 3 e re : “ Joale ba nka ka pel’a Moshe monehelo oohle oo bara ba Iseraele ba neng ba o tlisitse bakeng sa mosebetsi oa tšebeletso e halalelang e le hore o etsoe , ’ me , ha e le bara ba Iseraele , ba ’ na ba mo tlisetsa nyehelo ea boithaopo hoseng ho hong le ho hong . ”
Eitse ha moprofeta oa Molimo Samuele a mo bua hantle , ka boikokobetso Saule o ile a araba : ‘ Ha ke re ke mo - Benjamine , oa leloko le lenyenyane ho meloko ea Iseraele , ’ me mothapo oa ka ke o monyenyane ho methapo eohle ea leloko la Benjamine na ?
Samuel o sitoa ho lebala se ileng sa etsahala letsatsing leo .
Ka litsela tse itseng , ho ikopanya ha lichaba tsa lefatše moruong ho ka ba ha tlatsetsa ho se utloaneng ha batho .
Tumellanong le boprofeta bo joalo , lekholo lena la lilemo le bile litlokotsing tse latellanang .
Pesaleme ea 65 : 9 - 13 e re ka eena : “ U lebisitse tlhokomelo ea hao lefatšeng , e le hore u ka le fa nala ; u le entša haholo .
Ka tšohanyetso har’a mp’a motšehare , ka mor’a hoba Jesu a be thupeng nakoana , lefifi le tšosang le tsoang ho Molimo le aparela sebaka seo ka lihora tse tharo .
Ho feta moo , makasine ea Nature e hlokomela hore hase bo - rasaense bohle ba lumellanang ka tlhaloso ea bopaki ba lipatlisiso tsa molao tse amanang le saense .
E ka ’ na eaba u motho ea sa bueng haholo empa molekane oa hao eena oa bua .
Ke eng se ileng sa susumetsa Baiseraele hore ba nke bohato ka tsela ee ?
Ho ne ho se mohla re kileng ra arohana lilemong tse 12 .
Lipaleise , Lelapa la Borena le Mekete ea Maemo ho Iphaphatha le Nōka
Ho ka ba molemo hore u nahane ka ntho e tšehisang haholo kapa e sa tloaelehang !
Lifahleho tsa likerubime li lokela ho talima sekoahelong .
Empa haeba ho bonahala eka litlhoko tsa hao lia hlokomolohuoa kapa hore khafetsa u jarisoa molato oa lintho tse entsoeng ke banab’eno , ntle ho pelaelo lehloeo le ba teng .
Ho ile ha boela ha sebelisoa maloala a maholo a neng a huloa ke liphoofolo kahoo mosebetsi oa ho sila o ne o etsoa ke mong’a leloala ho e - na le hore o etsoe ke mosali . — Matheu 18 : 6 .
“ Ka linako tse ling ke ee ke utloe menyenyetsi ea hore ke laetsana le motho ea itseng — eo ke bileng ke sa mo tsebeng !
U tšoarele batho ba bang ka bolokolohi .
Ha a bontša tumelo ea hae tsohong e tlang , Jesu o ile a ’ molella ka ho hlaka : “ Ke ’ na tsoho le bophelo ; ea lumelang ho ’ na , leha a shoele , o tla phela . ” — Johanne 11 : 20 - 25 .
Claude , e leng ntate e mong ea lilemo li 60 , eo hona joale a qetang nako e ngata a bolella ba bang litaba tse molemo Afrika , o re : “ Bophelo e ntse e le mpho ea bohlokoa le ka mor’a ho utloa bohloko ba ho shoeloa ke molekane . ”
Ho tla etsahala’ng ka baruti ba Bokreste - ’ mōtoana le Babylona e Moholo kaofela ?
20 923
Buka How to Talk so Kids Will Listen & Listen so Kids Will Talk e hlokometse taba ena ka ho loketseng : “ Ha u ntse u leka ka ho eketsehileng ho qhelela maikutlo a ngoana a ho se thabe ka thōko , u tla hlōleha ho felisa maikutlo a fosahetseng ka ho eketsehileng .
Joale ho ile ha latela puo ea hoseng , e ileng ea fanoa ke setho se seng sa Sehlopha se Busang , Karl Klein , ea ileng a khetha sehlooho “ Ho Hlaolela Puisano ea Bokreste . ”
Buka Lipotso Bacha Baa Botsa — Likarabo Tse Sebetsang e na le karolo e nang le sehlooho “ Sekolo le Mosebetsi . ”
Ea jang nama ea ka , le ho noa mali a ka , o na le bophelo bo sa feleng ; ’ me ke tla mo tsosa ka letsatsi la bofelo .
Ho Fumana Tšepo le Bophelo bo Molemo
Hopola keletso ea Jesu ho mosali ea neng a tšoarehile ka ho lokisa lijo tse ngata tse hlophisitsoeng hantle : “ Ho hlokahala lintho tse seng kae , kapa e le ’ ngoe feela . ”
Leha ho le joalo , moo Nōka ea Tsirku e kenang Nōkeng ea Chilkat , ho hohlomela ha lefatše le ho ritsa ha liqhoqhoane ho ile ha etsa letamo le leholo le nang le botebo ba limithara tse fetang 230 ka tlaase ho bophahamo ba leoatle .
The New English Bible e fetolela Pesaleme ea 96 : 1 tjena : “ Binelang MORENA , batho bohle ba lefatše . ”
’ Nete e nyarosang ke ea hore re tseba ho fokolang haholo ka pōpeho e khethehileng ea motho ho feta kamoo re tsebang likaroloana tsa mechine eo le mananeo a e tsamaisang . ”
Tlhaloso ea CFS
Phehella Thapelong
Ketsahalong e ’ ngoe , eitse ha a bona mohlolohali ea saretsoeng ke lefu la mor’a hae ea sa tsoa hlokahala , a potlakela mokolokong oa lepato ’ me a tsosa mohlankana eo bafung . — Luka 7 : 11 - 15 .
Ka hona , tsela eo Jehova a ileng a nyatsa sechaba sa Iseraele ka eona e bontša hore o nyatsa le Bokreste - ’ mōtoana ka tsela e tšoanang kajeno .
Lipaki Tsa Jehova li bile teng Liechtenstein ka bo - 1920 .
Ho khutla ha batho bao e seng Baiseraele Babylona ho ka tšoantšoa le eng ?
“ Ke Rata Tsela eo e Behang Litaba ka Eona ”
Joaloka lekholong la pele la lilemo , kajeno , ‘ bohle ba nang le tšekamelo e nepahetseng bakeng sa bophelo bo sa feleng ’ ba amohela ’ nete eo ba e bolelloang .
Ka tsela e tšoanang , haeba re thabela boithabiso bo bontšang “ batho ba tloaetseng ho etsa se kotsi , ” re ka ’ na ra fumana ho batla ho le thata ho ba “ le khotso le batho bohle . ”
