Paulo yavuze ati : “ Ndagomba ko mumenya k’umutwe w’umugabo wese ari Kristo , kandi k’umutwe w’umugore ar’umugabo , kandi k’umutwe wa Kristo ar’Imana ” .
• Shetani afise ububasha bungana gute ?
Iyo mu rugo ari ahantu harangwa amahoro biratuma haba agahimbare
Yezu yari ntangere mu vyo gukoresha ibigereranirizo .
Yarakiriye ico gitabu ata ngorane .
Vyoshika nkakizingurura nkagisoma , nkongera nkiyumvira ibintu vyiza twaciyemwo .
Naho Bibiliya kenshi idatomora ingene Yezu yaronka aho arara igihe yaba yagiye kwamamaza , we n’abigishwa biwe bategerezwa kuronka aho bakika umusaya .
Naho kera nari mfise ishavu n’uburake bimeze nk’ibombe ishobora guturitswa n’akantu ubusa , Yehova yaramfashije kugira amahoro n’ugutekana bidasanzwe . ”
Naho nari mfise imyaka 17 gusa , jewe n’uwo twakorana twarashinzwe guhagarikira amakoraniro kuko muri iryo shengero rishasha hari abavukanyi bakeyi bakwije ibisabwa .
Mbega ikintu gitangaje cashitsweko mw’isi ya Shetani yiciyemwo ibice !
Icitwa Lares be n’icitwa Penates vyari ibimana vy’imiryango .
Jaime yaratanguye kwitaba amakoraniro ya gikirisu maze arakorwa ku mutima n’urukundo yahasanze .
Ku bijanye n’abanyeshure biganye mw’ishure ryakira abana b’incabwenge , umunyeshure umwe yiyemereye ati : “ Twese . . . twaratirisha ; twari dukeneye amanota yo kwinjira mu mashure mezameza .
None si ko bikwiye kumera no ku bijanye n’ubucuti tugiranira n’Imana ?
Umugabo wiwe ntiyipfuza ko agenda , ariko yavuze ko atomutangiriye aramutse ahisemwo kugenda .
N’ikindi kandi , yaragira ubwoba igihe cose yaba abonye umuntu asa na wa musore yari yitwaje inkoho canke afise agasakoshi batwara ku mugongo kameze nk’akiwe .
Mu kiringo gisa na kigufi Yezu yamaze avuga inkuru nziza , hafi cose yakimaze aca mu gihugu , “ yamamaza inkuru nziza y’ubwami . ”
Ico “ gisata ” kigizwe n’abakirisu barobanuwe hamwe n ’ “ izindi ntama ” za Yezu amamiliyoni zibafata mu mugongo . ​ — Yoh . 10 : 16 .
Mu kubwira abigishwa biwe ibijanye n’ibintu vyobaye mu gihe “ c’insozero ry’urunkwekwe rw’ibintu ” ( NW ) , Yezu yarerekanye iyindi mvo ituma Yehova areka abasavyi biwe bagashikirwa n’uruhamo .
Muri ubwo buryo , turagaragaza ko twemera uburyo Imana itegeka .
13 : 1 .
Ubwa mbere , vyaragoranye kubonana na Consuelo kubera ko abo babikira bagize amakenga bavuga ko Consuelo adashobora kubakira .
Abavukanyi bari biteguriye gukora ikibereye , mugabo bari bakeneye kumenyerezwa .
Birabanezera kubera ko , nk’uko babivuga , baba bagize ‘ ico bahaye Yehova . ’
Nk’akarorero , igihe Yakobo yasaba umumarayika yari yamugendeye ngo amuhishurire izina ryiwe , nya mumarayika yaranse kurihishura .
Hari n’abo imiti yafashije , ituma bataza barafatwa n’intandara .
Ivuga iti : “ Umuntu wese nayobokere abakuru bari hejuru [ ni ukuvuga intwaro z’abantu ] , kuko ata bukuru buriho bitavuye ku Mana ; abakuru bahari bashizwe n’Imana mu bibanza vyabo bigereranye .
Alegizandere Mukuru yahavuye yigarurira igice kinini c’isi , maze ikigiriki cavugwa n’abantu batobato ari co koyine gicika ururimi ruvugwa mu bihugu vyinshi .
Ndahimbawe kuba yaramfashije nkabandanya kumukorera . ”
Petero yarifatanije na ba bigishwa bagenziwe mu kuvuga ati : “ Uri Umwana w’Imana vy’ukuri . ”
Abisirayeli bari barabonye ibimenyamenya vyinshi cane vyerekana yuko Yehova ari we Mana y’ukuri .
Ivyo vyoba bikuraba wewe ugeze mu zabukuru ?
Naho ukuri kw’agaciro Yezu yari yarabigishije kwabanezera cane , bari bazi neza ko atari bose kwanezera .
Igihe babaza abanyeshure nimba hari abashaka kwitanga ngo baje gukorera mu bindi bihugu ari abamisiyonari , twaciye twemera kwitanga tubikunze hamwe n’abandi .
Inyigisho za Yezu n’intumwa ziwe ziracafise ububasha nk’uko vyari mu kinjana ca mbere .
Ubona gute none ushize ivyiyumviro bikurikira muri porogarama y’umugoroba uhariwe Ugusenga kwo mu muryango kugira ngo utume umuryango wawe urushiriza gutahura no gukenguruka ishirahamwe rya Yehova ?
Nkorana ubutsimvyi n’abahungu banje
Niba dushaka kuroranirwa mu gikorwa ico ari co cose tugomba gukora , dutegerezwa guhezagirwa na Yehova .
Yari isugi itagira agahaze .
Abanditsi b’igitabu kimwe kivuga ibijanye n’ukutarengerwa n’umukazo , bagira bati : “ Niwiyumvire ivyiza biva ku kureka inyifato wahorana ” .
Nk’akarorero , inkuru zo mu Njili zitwibutsa ibi : “ Mwame mugavye ” , “ mwame mwiteguye ” ; “ mwiyubare , mube maso ” ; “ mugume mwiteguye ” .
Ikigeretseko , gutahura ivyiza biva ku kugaragaza imbabazi bizotuma tugaragaza iyo kamere mu buryo burushirije kuba ubushitse mu buzima bwacu .
Uti none ishirahamwe ryiwe umuntu yorimenya gute ?
Muri Ndamukiza 1951 , umuvukanyi Nathan H .
Narabandanije kumubwira ibintu vyinshi nariko niga .
Igishimishije , Ijambo ry’Imana riratwereka igituma twokwemera ko buzohera .
Niwihe ishusho uwo muhanuzi ariko arakoresha ibihe bitekanye vyo mw’ijoro mu gusenga Yehova , aserura ivyiyumviro vyiwe bigera ibwina kuruta kandi aronderana ishaka ubuyobozi bwa Yehova .
Inyuma yo mu 33 G.C . , vyahishurwa biciye kw’ishengero ry’Abakirisu basizwe ryo mu kinjana ca mbere .
Mu gitabu ciwe A Biblia em Portugal ( Bibiliya mu giporotigali ) , G .
Cabandanije kivuga giti : “ Buca haba Noweli , ni kuvuga ku wa 24 Kigarama , abantu bokwibutse Adamu na Eva , ivyo bakabigira bafise mu bwenge ibintu bizwi cane vyabaye vyerekeye ca Giti cari mw’Iparadizo yari kw’isi . . . .
Abantu bagendesha amato muri ivyo bihe bagenda bibangikanije urutonde ruriko iminara y’amatara ayobora ubwato , iyo na yo bakaba barashobora kuyibona mu gihe c’urugendo rwabo .
Abavukanyi rero barakenguruka cane igihe naba ndabafashije gutunganya amakoraniro n’indimiro mu buryo ngirakamaro .
Uwundi yazigamye ukutadohoka yari Yobu .
Aba Miskito ni umwe mu migwi myinshi y’abantu b’imvukira bo muri Nikaragwa babayeho imbere yuko Abanyaburaya bashikayo mu kinjana ca 16 .
Ntiyigera yiciraho canke ngo akoreshe agahahazo .
Ivyo bisobanura ko gukunda Imana vy’ukuri harimwo n’ibindi uretse gusa kuvyiyumvamwo .
32 Be maso ! ikurikira ntize igucike
Yari yararondeye inyishu z’ibibazo yari afise bijanye n’ivy’Imana ariko ntiyari bwaronke izimara akanyota mw’idini yarimwo .
Naho iyindi miyabaga ishobora kwiyumva nabi rimwe na rimwe , Anna na Julia bobo wasanga bashobora kumara indwi nka zingahe canke amezi bafise akabonge .
Raba ahavuga ngo IVYASOHOWE > AMAVIDEWO
Ivyo vyatumye ahangana n’ingorane yo gukora akazi no kuronsa abana biwe ivy’umubiri .
No muri iki gihe , Yehova ariko aragaragaza ukwihangana guhambaye , kandi ukwo kwihangana kuriko kumara igihe kirekire kuruta uko bamwebamwe bashobora kuba bari bavyiteze .
( A ) ․ ․ ․ ․ ․ urudandaza .
Kubera yuko twipfuza kuzosangwa ‘ tutariko umugayo ’ , vyoba vyiza dusuzumye imvo zidusunika mu vyo dukora vyose .
Ukutadohoka ntikugarukira gusa ku muce munaka w’inyifato y’umuntu , nk’akarorero ukuyoboka mu vy’idini .
Ku bw’ivyo , naho umuntu avuga ko yumvise amajwi canke yiyumvisemwo ibindi bintu biteye ubwoba ashobora kutemera kwikuramwo ivy’uko yaturubitswe n’amadayimoni , nta nkeka ko akwiye kuremeshwa gusuzuma neza kugira arabe ko ibimushikira bitoba biva ku ngorane z’umubiri .
Gutyo , Aburahamu n’abandi bantu bari bafise ukwizera babayeho mu gihe c’imbere y’ubukirisu bari mu bazozurwa . ​ ​ —⁠ Soma Abaroma 3 : 24 , 25 ; Zab .
Balamu yaraburiwe kenshi , izo mburizi zigategerezwa kuba zava kw’isoko rirengeye ubutahuzi — eka n’ingamiya yiwe ubwayo yaravuganye na we !
Nuhitemwo abagenzi bawe ubigiranye ubukerebutsi
Kuko , uko muhinyura abandi , ari ko muzohinyurwa namwe ; kand’ingero mugeramwo muzoyigererwa namwe .
Kubera ko uherutse gutangura gukora akazi k’igihe cose , urabona ukuntu bigoye kwitaho imirimo yo mu rugo wongera urondera icobabeshaho .
Mu kuduhanura ngo dutakambe , Yezu yarashimitse ku vy’uko iki atari igihe co gufata minenerwe ibijanye n’impagararo dufise imbere yiwe n’imbere ya Se wiwe .
Umumenyeshakazoza Yesaya yanditse ati : “ Ni mukengurukire [ “ Yehova ” , NW ] , mwambaze izina ryiwe , mwamamaze ibikorwa vyiwe mu mahanga , mumenyekanishe izina ryiwe ko rishizwe hejuru ” . — Yesaya 12 : 4 .
Icigwa co kwumira kw’ibanga naho tworwanywa
( a ) Kumenya yuko intambwe iriko iriyerereza mu micungararo vyotuma abavyeyi baca bakora iki ?
Twarakoranye ubutsimvyi i Vancouver , mu nyuma i Kaliforniya , maze turungikwa mu gikorwa co kugendera amashengero muri Missouri no muri Arkansas .
Nakare , Bibiliya ubwayo itubwira yuko “ Imana itarobanura abantu ku butoni , ariko mu mahanga yose ūyubaha , agakora ivy’ukugororoka , iramwemera . ”
Abisirayeli baridodomvye ku bijanye n’ibifungurwa , bavuga bati : “ Uhoraho iy’apfuma atwicira mu gihugu ca Egiputa , tucīteretse inkono z’inyama , tukirya ivyo kurya tugahāga ; none mwadukūyeyo mutuzana mur’ubu bugaragwa kugira ngw iri shengero ryose mutwicishe inzara ” . ​ — Kuvayo 16 : 1 - 3 .
Abandi barashashaye kuzokwibonera ibizoba kuri uwo musi .
Twese turakeneye ‘ kuguma duharurira ibirenge vyacu inzira zigororotse ’ .
Abahindu , Ababuda , Abisilamu , Abajayini n’abo mw’idini rya Tao , bemera ko hariho ubwoko kanaka bw’umuriro udahera .
Schroeder avuye ku cicaro gikuru c’Ivyabona vya Yehova i Brooklyn yaratugendeye , maze avuga ko hoshingwa iyindi nzu y’abamisiyonari mu kandi gace ka Lima .
Turazi neza yuko bizokwibutsa imfungurwa umukimba zo mu vy’impwemu winovoye be n’uko bizokwigisha .
Adamu na Eva bari baremwe batunganye , kandi abana babo bose bovutse batunganye .
Ako gatima k’uwo muyabaga w’Umunyamisiri ntigakomeza amahoro yo mu rugo .
Ni igiki coshobora kwonona ubucuti dufitaniye na Yehova ?
Vyongeye , Umwana w’Imana Yezu Kristu yarahaye abayoboke biwe itegeko ritoroshe mugabo riteye umunezero , rigira riti : “ Nimugende . . . muhindure abantu bo mu mahanga yose abigishwa , mubabatiza mw’izina rya Data n’iry’Umwana n’iry’impwemu nyeranda , mubigisha kwubahiriza ibintu vyose nabategetse .
Ariko nibabashengeza , ntimuze mwiganyire ku vy’ingene muzovuga canke ku vyo muzovuga ; kuko ivyo muzovuga muzobihabwa muri iyo saha ; kuko atari mwebwe gusa muzovuga , mugabo impwemu ya So ni yo izovuga biciye kuri mwebwe . ”
Isi yaracitse ivutu kubera urupfu rw’abantu barenga 500.000 , harimwo abagabo , abagore n’abana .
Narakoreye mu nzego zitandukanye imbere y’uko mba umwanditsi w’ikinyamakuru ca Leta casohoka buri ndwi .
Narasenze Imana ndayisaba inkomezi n’umutima rugabo .
17 , 18 . ( a ) Imana yabona Aburahamu gute yisunze ukwizera kwiwe ?
Uwo musi wa Yehova washitse mu 70 inyuma ya Kristu , igihe Abaroma bashitsa urubanza rwa Yehova kuri Yeruzalemu .
Kitwigisha iki ku vyerekeye Yehova be n’ingene afata abantu mu vyo agirana na bo ?
Ico mwene ivyo vyiyumviro bivamwo ni inyigisho z’idini zidondora Imana uko zishakiye , ugasanga amadini ashimika ku muntu ku giti ciwe no ku vyotuma umuntu arushiriza kwiha agaciro , aho gushimika ku Mana no ku vyo idusaba gukora .
( b ) Ugupima nabi ivy’ubutunzi bishobora gute gutuma umuntu akengera ya mburizi iri muri 1 Timoteyo 6 : 9 ?
Mbega ibiremwa vy’ibiburirane !
Yarisutse mu Ntambara y’Abanyagihugu
Mw’Ijambo ryiwe , Yehova avuga ko ari “ se w’impfuvyi [ a ] kaba n’umucamanza w’abapfakazi . ”
Ivyagiye birashika biremeza ko ivyo bishoboka .
Rolf - Michael be n’umugore wiwe Ursula bararonderanye umwiheburo insobanuro y’ubuzima hamwe n’ukuri .
Yezu yariyamirije abiyorobetsi basenga kugira ngo gusa abantu bababone bongere bumve ivyo bavuga
Umubazibazi wava mu giti citwa bois d’aigle
Yehova asezerana kuduha inkomezi dukeneye kugira ngo dukore ivyo agomba , ariko ntidukwiye kwiyahagura mu kurondera gukora ibirengeye ubushozi bwacu tugerageza gukora ivyo atatwitezeko .
Agatima ko kwitanga yari afise katuma aronka umwanya muto cane wo gukora ivyiwe , mugabo yarahimbarwa no gusukurira abandi .
Ni bande umuherezi mukuru w’Abisirayeli yatangira ikimazi c’isuguru y’impene , kandi ivyo cari igitutu c’iki ?
Igihe abavukanyi b’i Yeruzalemu bari bakeneye imfashanyo z’ivy’umubiri , Abanyafilipi barerekanye ko biteguriye gutanga intererano mbere zinarengeye ivyo bari bafise .
Yehova yakoresheje gute umumarayika kugira ngo aremeshe umuhanuzi Daniyeli ?
N’utwigarukanire , Uhoraho we , natwe turakugarukira ; dukomōrere imisi yacu nk’iyo twahoranye ubga mbere ” . ​ — Gucura intimba 5 : 1 , 19 , 21 .
UMUSI uhambaye wa Yehova uregereje cane .
Ego ni ko , nk’uko twamaze kuvyerekana , kuvuga gusa ingingo zigenga inyifato runtu wisunga ntibisobanura yuko umuhungu wawe canke umukobwa wawe azoca ahitamwo kubaho azisunga .
Hannelore abandanya ati : “ Twaranaronsa ibifungurwa vyo mu buryo bw’impwemu abavukanyi bacu bari mw’ibohero .
Naho bitanyoroheye , nagiye ndahindura intambwe ku yindi imico nagenderako be n’ukuntu nari mbayeho . ”
Abo natoye bazokwinovora bimwe bishitse igikorwa c’amaboko yabo . ”
Kubera iki abantu baheba amadini ?
Narahevye kubesha no gukoresha imvugo ihumanye , maze nca ntangura kwitaba amakoraniro y’Ivyabona vya Yehova .
Hoba hariho ahacishwa ikinga ry’ibimuga ?
Abo bagabuwemwo imigwi mininiminini ibiri y’abaririmvyi bagenda bahimbaza , umwumwe wose ugakurikirwa n’urugendo rw’abantu .
Kugira ngo turonke inyishu y’ico kibazo , rimbura izindi nkuru zibiri z’abigeze kurokorwa .
Hari uwari yiteze ivyo bintu none ?
Ahabu
Ivyo bisobanura ko mu bisanzwe uturimbi kanaka dukenewe , kugira ngo abagize ikibano bose baronke umwidegemvyo ubereye .
‘ Nimubandanye kwironsa inkomezi mu Mukama ’
Abantu ba Yehova bo mu gihe ca none bobo baragaragaje ko ari intahemuka mu bihe hagize igihinduka .
Kubera ko ari i buryo bwanje , sinzonyiganyizwa .
Vyemere , umwe Ruheta mu gushinga no mu kwubahiriza igihe ni inkerebutsi akaba n’umunyabubasha kuruta abandi bose .
Babiloni ya none imeze nk’aho ha kera , kandi igereranya inganji y’isi yose y’idini y’ikinyoma .
Niwinjire rwose mw’Ijambo ry’Imana .
Abagabo n’abagore barashobora kuryohora ubucuti bafitaniye mu gukurikiza ingingo ngenderwako za Bibiliya .
Uwo muce w’ubwo buhanuzi utegerezwa kuranguka no muri iki gihe cacu nyene .
Kugira ngo uronke ikiganiro gisigura iyo mirongo mu buryo bushika ibwina , raba ikigabane ca 28 c’igitabu La Révélation : le grand dénouement est proche ! , casohowe n’Ivyabona vya Yehova .
Nta mazinda , iyo nzeduka ikwiye kutubera imburizi kugira ntitugaragaze agatima k’ubugarariji , k’ukwidoga , canecane kwidogera Imana n’intondeko zayo za gitewokarasi .
Umwe Pranas twavuga kare , agira ati : “ Imiziki , amavidewo canke ibitabu twebwe abavyeyi dukunda ni vyo n’umuryango wacu uca wisunga mu guhitamwo .
Mu buraruko bw’urusengero hari ikidengeri citwa Bezata , Yezu akaba yahasanze umugabo arwaye .
Bibiliya iravuga ivyo Yehova yipfuriza abamurondera ikoresheje aya majambo asanzwe mugabo aryoshe , iti : “ Imitima yanyu nibeho ibihe bidahera . ” ​ — Zaburi 22 : 26 .
Dawidi yoba yarashavuriye Imana ?
GUKOMERETSWA KU MUTWE
Igihe hatari bwaboneke abaganga bitwararika amagara y’abana , abahinga mu bijanye n’inyifato y’abana , be n’ubwo buhinga bwa Internet , ni hehe none abavyeyi baronderera impanuro ?
Kubera ko ico kibazo kiri muri Yesaya 40 : 28 gihambaye gutyo , birakenewe ko tucicarira twitonze .
Abo bantu babajijwe n’ikinyamakuru Be maso ! , ni bake gusa mu bantu amamiliyoni bo hirya no hino kw’isi Bibiliya yafashije kuba abaremesha amahoro mu ngo zabo .
Bibiliya zimwezimwe , aho gukoresha muri uwo murongo “ ukuboko ” , zikoresha ingero y’umwanya , nk’akarorero “ akanya na gatoyi ” ( Ubwuzure Bushasha ) , canke “ umunuta umwe ” ( Bibiliya yitwa Impinduro yo mu rurimi rw’abanyagihugu [ mu congereza ] , yahinduwe n’uwitwa Charles B .
Ariko rero , ico ntikibuza ko muri iki gihe Ababuda benshi bo mu ntara za Aziya yo mu Buseruko bwa kure bemera ko iyo umuntu apfuye umutima w’ubwenge umuvamwo ukimukira mu kindi kiremwa * .
Yehova ntiyashinze kazoza kawe uko kazomera .
Kubera yuko ibihugu bimwebimwe biriko birahingura ibirwanisho ruhonyanganda , abantu barafise ubushobozi bwo kuzimanganya igice kinini cane c’abantu baba kw’isi .
Nk’akarorero , Paulo yarahaye ubuyobozi abavukanyi biwe .
Abantu bemera Umuremyi mugabo bakaba batemera Bibiliya , ntitwobayagisha cokimwe n’abantu batemera ko Imana ibaho .
Igihe Yohani yegereje kurangiza ubuzima bwiwe , akaba yatwawe inyagano mw’izinga rya Patimo , arahishurirwa ibintu ushizemwo n’ibimenyetso vyavyo vyose bitangaje vy’ubuhanuzi bwerekeye ivyobaye mu “ musi w’Umukama ” ( UB ) .
7 , 8 . ( a ) Bamwebamwe bavuze ibiki ku vyerekeye umugoroba ugenewe Ugusenga kwo mu muryango ?
Ijambo ry’Imana ryari ryaravuze ko “ mu misi y’iherezo . . . abantu babi , bo n’abahūmbūzi , bazorushiriza kuba babi , bazimiza bakazimizwa . ” — 2 Timoteyo 3 : 1 , 13 .
Ni kubera iki Adamu na Eva , Kayini hamwe na Yuda Isikariyoti
Muri Isirayeli ya kera , kuvyara abana cari ikintu gihabwa agaciro cane , kandi wasanga imiryango ari mininiminini rwose .
Yehova aritwararika ibikorwa vy’ukwizera vyose , mbere na bitobito .
• Ubwibone ni iki ?
Urubanza ruzoba rwaciriwe Shetani ruzoza rurisungwa ibihe bidahera .
Yapfuye mu 2005 , afise imyaka 98 .
Kugira umutima wigabuye ntibihimbara Yehova .
Gutera imbere ni “ ukurushiriza gukora ikintu gusumvya ukwo wahora , ukagira ivyo uryohoye . ”
Abavukanyi bacu twikundira bo ng’aha barakunda cane iyo televiziyo .
Ni kubera iki bibereye ko twemera icese yuko Yehova ari “ Imana nzima ” ?
Uko tumenya Yehova n’imihango yiwe , ni ko tumukunda tukongera tugashima ivyo yadukoreye vyose .
Umukirisu yarobanuwe yari guhemuka , ntiyari kuronka “ rwa rugori rudakabirana rw’ubuninahazwa ” rwasezeraniwe abatowe baguma ari abizigirwa gushika ku rupfu . ​ — 1 Pet .
Ese ukuntu ubwitonzi nk’ubwo ari umuhezagiro ku bandi !
Yona abonye ko ataco ashoboye gufasha , yaciye amanuka mu gice c’ubwo bwato co hasi yiryamirayo .
Bamwe mu Bayuda bashobora kuba barakoze cane mu kuringaniza ibarabara rija mu gihugu cabo c’amavukiro no mu kurikuramwo intambamyi kugira ngo abasavyi b’Imana bashobore gushika iyo baja .
Nkiri muto , siniyumvira cane ivyerekeye intumbero y’ubuzima canke ivya kazoza .
Ivyo abari bakoraniye ng’aho bose babonye bongera barumva vyari mu vy’ukuri ibintu vyimbitse vy’Imana .
Dukurikije igitabu Theological Wordbook of the Old Testament , ririmwo ‘ iciyumviro ciyongeyeko c’ugukora ikibereye gukorwa . ’
Weho ubabera umugenzi ameze gute ?
( b ) Ni kubera iki Yehova atazoreka ngo ikibi kibandanye kubaho imyaka yose ?
Gukoresha Nabi Ubuzima Bwacu
Urabona ko Yehova ahemba ‘ abamuronderana ubwira . ’
▪ “ Tubwire : Ivyo bizoba ryari ? ”
Nimba ari ko biri , ni igiki none cogufasha kuguma wihanganye , ukizigira Yehova uherejeko ?
Kugira ntibandukize abandi , baririnda kubegera cane .
Nimba uri muri abo , numenye neza ko Yehova akenguruka cane uwo mutima wo kwitanga , kandi ko atazovyibagira . ​ — Heb .
Uwitwa Ilaria aba mu Butaliyano , avuga ati : “ Abavyeyi banje bararyoherwa n’imiziki numviriza .
Ariko rero , Abalewi bose b’abacuraranzi ntibari abahinga .
Iyo fi ita amagi aho twokwita ku birenge vy’ako gakoko maze ikigabo n’ikigore bikaguma biyacunga neza .
Mu gukora ibitangaro bitari bike mu gihugu hose , harimwo n’ugukiza abarwaye , ukugaburira abashonje , uguhagarika inkubi z’imiyaga , eka mbere no mu kuzura abapfuye , Yezu yarerekanye kandi ivyo Ubwami bw’Imana buzokora .
“ Babiloni Akomeye ” yāgīrwa n ’ “ ibintu bisesemye ” ibihe ?
URUPAPURO 17 • INDIRIMBO : 84 , 72
Mu vy’ukuri , bisobanura yuko umugabo n’umugore baba bagize umuryango mushasha , uno ukaba ari wo uca uza imbere y’imiryango bakomokamwo .
Aha hepfo , niwandike ikintu giheruka kuba , nk’ikibazo co kw’ishure , aho wakoze neza mugabo uwundi muntu agakora neza cane .
Kubera yuko abantu nk’abo batabona Imana n’amaso nya maso yabo , bakora ibintu nk’aho yoba itabona ivyo bariko baragira .
Uhereye mu Buraya bwo mu Buseruko ukaja muri Amerika yo Hagati gushika muri Afrika , abakirisu b’umutima rugabo bararindutse baribuka urupfu rwa Yezu mu bihe vy’intambara canke mu gihe igikorwa caba kibujijwe .
Abavyeyi n’abandi bo mw’ishengero bashobora gute gufasha abana b’ivyangazi ‘ kwisubirako ? ’ ​ — Luka 15 : 17 .
Hazoteba hagere ko “ Adamu wa nyuma ” akora nk ’ “ impwemu itanga ubuzima ” ku bantu muri rusangi .
3 : 27 , 28 ; 1 Yoh . 3 : 17 .
Vyongeye , niwiyumvire ukuntu umugore yokwumva amerewe amenye yuko umugabo wiwe yamuhemukiye mu kuraba amasanamu y’ibiterasoni .
Ingorane zihanze abubakanye badasangiye abana INABIBONDO WO MURI OSTRALIYA YITWA MARGARET , * avuga ati : “ Uwahoze ari umugore w’umugabo wanje yabwira abana biwe ngo ntibakore ikintu na kimwe ndababwiye , naho kwoba ari ukubabwira nti : ‘ Ntimwibagire kwiyugumura . ’ ”
Ni nde agira ngw Agwē !
Uwo mugore yagumye agendana n’Imana , kandi haciye igihe umugabo wiwe yarifatanije na we mu gukora ukugomba kwa Yehova .
Turafashanya guteka hanyuma tugafungurira hamwe , kandi abahungu bacu barakunda gusoma cane ibitabu . ” ​ — John na Jenniffer . [ Ifoto ]
Ku gisenge cayo kimeze nk’umubirikira wubitse hari igitoboro gicamwo umuco .
Yamara , Yobu avuga ati : “ Kugeza aho nzopfira , sinzokwigera mva ku [ “ kutadohoka ” , NW ] kwanje ” .
Arashobora guhaguruka agasubira muri iryo siganwa .
Umuntu umwe yabanje kwanka kugamburuka ni Namani .
Paulo yongeyeko yuko Imana “ [ it ] abirekeye ngaho , itagira ico kuyishingira intahe , kuko yama ibagirira neza , ibaha imvura iva mw ijuru , n’ibihe vy’ivyimburo vyiza , ibahāza ivyo kurya , yuzuza imitima yanyu umunezero ” . — Ivyakozwe 14 : 17 .
Yitwa Shetani ( Umunanyi ) , Mucokoranyi ( Mureganyi ) , Inzoka ( icitiranwa c’Umuhumvyi ) , Uwosha abandi be n’Umunyabinyoma .
Kugira ngo uwo mukurambere amfashe , yararondeye umuryango aho i Escuintla wokwemera kumpa indaro kandi ukamfasha kwitaba amakoraniro ajanye no gusenga .
Igihe twempi twariko tuva aho hantu , twarahuye n’umusore ameze neza cane yariko atahuka avuye ku kazi , akaba yari kw’ikinga .
□ Ubutegetsi bwa wa Muganwa w’Amahoro buzogirira iki abantu ?
Neza na neza , ni gute abungere bazi utuntu n’utundi bashobora kumenyereza abandi kurangura ibikorwa bashingwa mw’ishengero ?
Haheze igihe kinaka , inkuru nziza yarakwiragiye hirya no hino mu gihugu cose .
Umaze kubona neza akazi wohitamwo gukora , uba ukeneye impanuro ngirakamaro .
Turizigiye yuko uwakoze ikibi atazomera nk’Abisirayeli , abo umuhanuzi wa Yehova yavuzeko ibi bikurikira : “ [ Narahamagaye ntimwitavye ] , n’igihe navuga [ ntimw ] umvise ; ariko mugakora ivyo mbona kw ari bibi , mukitoraniriza ibitannezera . ” — Yesaya 65 : 12 .
Nimutume mu rugo haba ahantu harangwa amahoro
Umwana w’Imana ari we Yezu yari azi yuko dukwiye kwitega ico kintu , kuko yabwiye abigishwa biwe ati : ‘ Impwemu y’ukuri izobarongora mu kuri kwose . ’
Loti yaragerageje kujijura nya bagabo , ariko biba ivy’ubusa .
Nitwiyemeze kutareka ngo imihazuko y’ivy’ubucuruzi ihungabanye amahoro yacu canke ay’ikorane .
‘ Nimuhariranire ’
Subira urabe ivyo Zaburi 106 : 32 , 33 ivuga . Hagira hati : “ Vyongeye , batera ishavu kuri ya mazi ya Meriba , ku buryo bigendera nabi Musa bivuye kuri bo .
Ariko rero , birashoboka ko umuntu arenza urugero muri uwo muce .
Umuvukanyikazi umwe yavuze ati : “ I muhira be no ku Ngoro y’Ubwami ni ho hantu honyene abana banje bamenyera yuko ukwimara inambu y’umubiri kw’abasangiye igitsina be n’uguhuza ibitsina hagati y’abatubakanye ari bibi mu nyonga z’Imana . ”
“ Mudakoresheje . . . ijambo ritahurika bitagoranye , homenyekana gute ibiriko biravugwa ? ” ​ — 1 Abakorinto 14 : 9 .
Twahavuye dufata ingingo yo kuza turitwaza akuma gatanga ubushuhe gakoreshwa n’umuyagankuba kugira mw’ijoro hagume hasusurutse .
Uwo Kuro kandi yobohoje Abayuda bagizwe inyagano akanashigikira isanurwa ry’urusengero rwabo rweranda .
Ni igiki codufasha guhindura ibikenewe ?
Ivyo bintu vyabaye mu kinjana ca mbere bituboneshereza gute ku vyerekeye ugukiza ku gitangaro kuba muri iki gihe ? — Matayo 15 : 30 , 31 .
Igihe Rinat yasubiza ako gasakoshi nya mugore , yarayaharuye maze aca abwira nyina wa Rinat yuko habuzemwo amasomu 200 ( nk’amarundi 6.000 ) .
Ukwifatanya n’abagize “ ubusho buto ” b’intahemuka , abafise umuhamagaro wo kuba mw’ijuru , kwaratumye abagize “ izindi ntama ” , abafise icizigiro co kuzoba kw’isi ibihe bidahera , bamenyerezwa mu bintu bihambaye .
N’ikindi kandi , uburyo abantu bakira ubwo butumwa biraba ikintu Kirisitu Umwami yofatirako canke yorabirako mu gucira imanza abantu .
Abatubatse izabo kubera yuko batararonka uwo bubakana abereye barakunda kuza baragira irungu .
* Kubera iki none Ivyabona vya Yehova bavuga ko yatikijwe mu 607 B.G.C . ?
Umwumwe wese muri twebwe arashobora gutahura ivyerekeye ico kimenyetso kigizwe n’ibintu vy’ido n’ido c ’ “ insozero y’ivy’isi . ” ​ — Matayo 24 : 3 - 7 .
Noba mfise agatima ko kugirira neza abafise amabanga mw’ishengero , kumbure nkabigira nizigiye kumenyekana canke kuronka uduteka twiyongereye ?
Nkako , nk’uko umwe muri bo yabivuze , ubuzima bwabo “ ntibwari ubwo kwidibamira . ”
Ivyo abamarayika bifuza kubirunguruka . ” — 1 Petero 1 : 1 - 5 , 10 - 12 .
Muri ya Bibiliya y’isi nshasha yasubiwemwo mu 2013 ( mu congereza ) , mu gice kivuga ngo “ Insobanuro z’imvugo zo muri Bibiliya ” hadondora umuhanuzi hati : “ Ni umuntu bicako kugira imigambi y’Imana imenyekane .
Dawidi yari uwudasanzwe mu buryo bw’uko yari umucuraranzi akaba n’umuryoshamvugo .
Ivya Samusoni vyari biheze .
Kuba Yehova yagumye agira akigoro ko kubogora Abisirayeli b’abacumuzi bitwigisha iki ?
Ku bw’ivyo rero , amajambo yo muri Bibiliya yasa n’ayadatahurika ni ho yaza yaranguka mu buryo bukomeye haciye ibinjana nka cumi !
Umugenzi si umuntu muzinanye gusa .
Icandikano VAT 4956 kivuga ku murongo wa gatatu giti : “ Ukwezi kwari guherereye kw’itambwe 1 ry’ukuboko uciriye mu nkokora [ canke dogere 2 ] imbere y’urunyenyeri Virginis ß . ”
Yehova ntazoduheba ” .
Igitabu ca Bibiliya c’Imigani kiragabisha ku bijanye no gukengera abavyeyi .
Kubera iki abantu bica amatwi ntibumve imburi ziguma zitangwa , bagasa n’abagomba kwisamburirako nk’impene ?
Aho gutsimbataza ukubumbwa n’ivyo bafise , bahitamwo kwishimira amahera be n’ivyo bashobora kuyaguramwo .
None ko benshi muri abo batsimvyi bo mu ntango batavuga igifaransa , bari gushobora gute kwihanganira intambamyi z’ururimi , uburyo buke be n’ukuba bari ukwa bonyene ?
Vyongeye , ububi bw’umuntu bwari bwarabaye ndanse , kandi isi yari yuzuye ubukazi .
Ubwo buryo rikora bushobora kuba ari bwo bwafashije Yozefu kubona imbere y’igihe yuko gusambana cari ikintu kibi kandi kitabereye , ni ukuvuga icaha ku Mana .
Muri iyo sinema harerekanwa imikogote ikwegwa n’amafarasi be n’imiduga ya kera cane , hamwe n’abasumyi be n’uduhungu dutembereza ibinyamakuru vyo kugurisha bari mu bikorwa vyabo vya misi yose .
Ese ukuntu ari umuhezagiro kuba twironkera ibinyamakuru , udutabu , ibitabu , amavidewo be n’amayagwa yo kuri internet aremesha ugusenga kw’ukuri !
Turashobora kwama tuganira n’Imana tukayibwira akari ku mutima be n’ukuntu twiyumva .
Yezu na Yehova bategerezwa kuba ari babiri batandukanye .
( b ) Ico kintu cabaye cari gifise insobanuro iyihe kuri Yezu ?
Haraciye imyaka 2.000 Yezu agendeye urusengero rw’i Yeruzalemu .
Babonye ko ndi impumyi , baciye bansomera muri Yesaya 35 : 5 ahagira hati : “ Ico gihe amaso y’impumyi azohumuka , kandi amatwi y’ibipfamatwi azozibuka . ”
Imbuto zimwe zigwa ku rutare .
Aho woronkera impanuro ngirakamaro kuruta izindi zose
Canke ushobora gufata ingingo yo kugira amahinduka ahambaye yo muri kamere kubera ufise icipfuzo co kubaho uhuza n’inyobozo ziva ku Mana ubu usigaye wemera .
Nkako , benshi barateye intambwe zo kworosha uburyo bwabo bwo kubaho kugira ngo bashobore guhebera ubusuku umwanya wiyongereye .
Abo bavyeyi baratahuye yuko abana bakeneye gutsimbataza ukwizera Umuremyi wabo .
MU BUMANUKO HARI IBIBARAFU VYINSHI
Ni igiki kizodufasha kurokora umuvukanyi wacu ?
Iyo mpinduro irabereye kubera yuko Imana ishobora gutuma icika ikintu ico ari co cose ishaka kuba .
Emwe , ni uko nyene bigenda !
Ukuntu wozeza abandi amabanga
Yehova “ niwamurondera , azoreka umuronke ”
Vyoba vy’ukuri bishoboka ko twiyegereza Yehova ?
Mu gihugu ca Esupanye ibintu vyari vyifashe ukundi , na canecane bitumwe n’abantu bitwa abagitane abo Borrow atatevye kugiranira na bo ubucuti bukomeye kubera yari azi ururimi rwabo .
Nishuye nti ‘ Oya ! ’
Ni kubera iki ugukenera ubutungane ari ikintu gisanzwe kiturimwo ?
Uko inkuru mpererekano zibivuga , Nimurodi yapfuye urupfu rubi .
Ugukurikirana ibintu nk’ivyo be n’ingeso nk’izo biramutse bidakosowe , birashobora gutuma umuntu akora icaha gikomeye , maze amaherezo ntabe acemerwa na Yehova .
Igituma Rebeka akora ibintu muri ubwo buryo , ntikivugwa .
Ayo majambo ashobora kuba yerekeza ku guhonyorera kugirwa mu nyuma , umuzabibu umaze kugira amashami menshi kandi ukaba umaze kugira udusoko tw’inzabibu umuntu ashobora kubona neza .
Isi yoba itakivayo ?
Na twebwe nyene turamutse dutsimbataje umutima wo gutinya Imana , bizotugendera neza .
None womurwanya gute ?
Ubwo Bwami buzoshitsa kandi umugambi Segaba w’ibiriho vyose Yehova afise , uwo na wo ukaba ari uguhindura isi Iparadizo aho abantu beza bazoshobora kwibera ibihe bidahera .
Rimwe na rimwe haraza umuvukanyi avuye ahandi agashikiriza insiguro y’icese mu kibanza caba cakoswe .
Bibiliya itubwira iti : “ Imana [ nti ] gira nkunzi , mugabo mw’ihanga iryo ari ryo ryose umuntu ayitinya kandi agakora ivy’ubugororotsi iramwemera . ”
Namwishuye nti : “ Nta n’umwe atazi ko ari Imana . ”
Iyo tugamburutse amategeko n’ingingo ngenderwako zigororotse za Yehova , tuba twerekanye ko tumwizigira kandi ko twipfuza kugiranira na we ubucuti burangwa amahoro .
Ariko igihambaye kuruta , ukugamburuka kwawe gutuma Umuvyeyi wawe wo mw’ijuru ahimbarwa , maze akaguhezagira mu buryo bwiza igitangaza .
Ariko nticabujije ko nakira ibitabu bibiri bifasha kwiga Bibiliya .
Naho bemera kwakirwa n’abo basangiye ukwemera , nta n’umwe “ [ b ] ikoreza umuzigo uzimvye . ” ​ ​ —⁠ 1 Tes .
Mu nyuma mu 1968 , Glenn yaratumiwe kuri Beteli gukora ivy’ukuzimya imiriro i Brooklyn .
Vyaraboneka yuko batatwanka ahubwo ko batwumvira akagongwe kubera amarushwa twari turimwo .
Yamara , mw’ijoro rya nyuma Yezu yamaze ngaha kw’isi , inyuma gato y’aho abigishirije icigwa c’ukwicisha bugufi mu kuboza ibirenge , “ [ haravyutse ] impāri muri bo , z’uwo bagereranyako kw ar’umukuru uw’ari we ” .
Yehova avuga ati : “ Ūbakorako aba akoze ku mbone y’ijisho ry [ anj ] e ” .
Emwe , twoyagira nyene , kandi na Yezu yari abizi .
Ariko sinashaka guhagarika ubutsimvyi . ”
Nitwafata izo ngingo tubijanisha n’isengesho bizodufasha gushikama maze twirinde kudohoka .
Hari umuporofeseri umwe wo muri kaminuza yavuze yuko mu ntango y’imyaka y ’ 1900 , abantu bemera ko bitosubiye gushoboka ko haba intambara kubera ko “ abantu bari basirimutse cane birenze . ”
Vyongeye , ndakenera kuba ndi ahantu hatekanye .
Ikintu gihambaye cane mu vyo gufata ingingo , ni ijwi ryo mu mutima twarazwe .
Ishirahamwe Hollywood rirazi ukuntu ryotuma impengamiro yose iba ikintu coryungura ryoshikiriza .
Imana izohagurukira abasiga iceyi izina ryayo . ​ — Soma Zaburi 83 : 17 , 18 .
Bibiliya ivuga yuko abagwa mu mutego wo gukunda amahera “ bitobekeranisha hose imibabaro myinshi . ” ​ — 1 Timoteyo 6 : 10 .
TWIGIRA IKI KURI . . .
Abagize ishengero bose , baba abato , abakuze be na bashasha , barashobora kugira uruhara muri uwo muce wo gusenga Yehova .
Nasubijeyo nti : “ Nta muntu n’umwe wo mu Bushinwa tuzinanyi . ”
Brigitte na Renate ni abavukanyikazi bakirisu .
Ngira icipfuzo co kuba umumisiyonari
Ariko rero ku bagabitanya , abo bantu batwara ubwo butumwa basohora “ agacūku k’urupfu ” .
Arabwira isinzi ry’abantu ati : “ Ntegerezwa kumenyesha n’ibindi bisagara inkuru nziza y’ubwami bw’Imana ” .
Mu nyuma , n’intumwa za Yezu zamubajije ziti : “ Mukama , iki gihe ni ho ugira usubize ubwami Isirayeli ? ” ​ — Ivyak . 1 : 6 .
Nugaragaze ubutungane mu gushinga intahe ku bantu bo mu mice yose yo mu kibano
Ahubwo riho , kubera ko igitigiri c’abahukana kiguma kiduga bwampi , birerekana ko abantu benshi babona ko umubano w’ababiranye ari ikintu kidahambaye umuntu ashobora guheba abishatse . ​ — 2 Tim .
Wokora iki ubu kugira ngo witegurire ico kintu kiba rimwe mu mwaka ?
Ariko kubera ko Yehova adukunda , yaratoreye umuti ico kibazo c’umuryango w’abantu .
Yezu yoba yashaka kuvuga yuko uwo mugabo w’umutunzi atari akwiye kugira utwigoro kugira ngo kazoza kiwe kazobe gatekaniwe ?
Naho uwo mutwe utaramutse gato cane , bituma ka gatara karushiriza gukayangana ibice hafi 50 kw’ijana ugereranije n’uko kokayanganye utugaragamba turi ku buringanire bumwe !
None Yehova si we akugiye imbere ? ”
Naho abari kuri iryo hwaniro bashobora kuba bari munsi y’abo , nta gukeka ko baruta Ivyabona bababa 65.000 bari muri Leta Zunze Ubumwe za Amerika ico gihe .
Nimba abantu badashoboye gucungera ivyago vy’ivyaduka , ni nde none abishoboye ?
Nk’uko raporo imwe yagizwe mu 1997 ivyerekana , umuntu 1 kuri 5 mu bageze mu zabukuru b’Abanyakiba , usanga ari abo mu migwi nk’iyo , aho baronkera abagenzi , ugufatwa mu mugongo be n’imfashanyo ngirakimazi ituma baguma bibereyeho neza .
Naho ibiremwa vyo kw’isi usanga bitandukanye cane , bikurikiza urutonde rumeze kumwe mu kuraga kamere zavyo ibibikomotseko , ivyo bikaba vyaratumye ubwoko nyamukuru bw’ibinyabuzima budahindagurika uko imyaka yagiye irarengana .
Nk’akarorero , igihe Paulo n’abamisiyonari bagenziwe bari i Filipi , barabonye umugore yitwa Lidiya maze batangura kumubwira inkuru nziza .
6 Vuba isi igiye kuba Iparadizo !
Biboneka yuko Luka , kubera ko yari umuganga , avuga ivyerekeye ukwo kuvura uruguma kwadondowe na Yezu , ushizemwo ugukoresha umuvinyu bwa muti wo kwica imigera , amavuta bwa muti wo kugabanya ububabare be n’ibijanye no gutenga uruguma . ​ — Luka 10 : 30 - 37 .
N’igihe nyene abami baba bahemukiye Yehova , yarashobora gutuma batsinda abansi babo , akabigira ku bw’izina ryiwe .
Naca numva mbabaye , nkabona ko ntazovayo .
Fata ukwo kuntu ubukuru bubonwa ukugereranye n’ukwo Yezu Kirisitu yigishije .
Twisunze ururimi rwo mu ntango , igihe Yehova yavugana na Aburahamu be na Musa , yarakoresheje ijambo ryo mu giheburayo rikunze guhindurwa ngo “ Ndakwinginze . ”
Kuki bubakana gusa n’abo basangiye ukwizera ?
Yamara , abakirisu bose bategerezwa kugendera muri ya nzira y’ubuzima bafatanye mu nda .
Bibiliya igenewe kwigisha abantu bose , mugabo twebwe abasavyi ba Yehova ni twe canecane tuyiha agaciro .
Nta gukeka ko yashaka gufatira ku kosho gakomeye ijisho rifise .
Ivyanshikiye biratuma mbandanya gushingira intahe Yehova ntahemuka , kuko kuri we “ vyose birashoboka . ” ​ — Mat .
Yezu yama nantaryo agaragariza icubahiro abandi .
Tuvuge iki ku bijanye n’Abisirayeli ?
Abahinga bashitse kuri ivyo bintu bafatiye ku giterwa co mu bwoko bwa sinapi citwa Arabidopsis thaliana .
Woba ukurikiza ingabisho zishingiye kuri Bibiliya zerekeye Internet ?
Kuko dutembagaza ivyiyumviro n’ikintu cose gihanitse gihagurukirijwe kurwanya ubumenyi bw’Imana . ”
Inyuma y’amezi atandatu , twarimukiye i Oswestry muri iyo ntara nyene ya Shropshire , kubera ko twashoboye gukota ahantu twagize iyororero ryacu bwite ritoya .
Umutima Imana ifise wo guharira ivyaha ukwiye kuwubonamwo icitegererezo c’ukuntu ukwiye gufata abandi bantu .
Ubwa mbere , Ezekiyeli yabonye ko ayo magufa yari ‘ yumye ’ canke “ yumye cane . ”
Ubugunge , kunyuruza , ukubesha , ubugome , hamwe n’ukwiba na vyo nyene bireze muri iki gihe .
Nimba rero inyiyumvo zica intege zitumye umara igihe kinaka udakora vyinshi mu murimo w’Imana nk’uko uvyipfuza , nusenge ku bijanye n’ico kintu .
Ni umuhora uwuhe Yezu ariko arakoresha mu kutugaburira muri iki gihe , kandi ni kubera iki bihambaye ko tumenya uwo muhora ?
Abantu barabona ubwiza bwiwe igihe amanutse “ mu murima w’ibiyōba ” , maze bagaca bamuzana aho Salomo akambitse . ​ — Indirimbo ya Salomo 1 : 6 ; 2 : 10 - 15 ; 6 : 11 .
Abakirisu bari basanzwe bakorera abandi be n’abakirisu b’abashumba bategerezwa gukorana umwete mu gukorera ba shebuja babo .
Ntimushobora kwiyumvira amahoro be n’ugutekanirwa mfise ! ” .
Ni ibiki vyashitse mu Bayuda mu 66 G.C . ?
Dawidi yarizigiye Yehova n’umutima wiwe wose
Bamwebamwe kugira ngo bagume bakurikiza urutonde rw’ingene bategekanije gukoresha amahera , basanze bikenewe ko bagira ivyo bagabanije mu bintu bimwebimwe .
Ni kubera iki ubwo bugurano bumara akanyota ?
Ivyo vyatumye jewe na Darren turonka akanya ko kumira amate no kuganira . ”
Abashakashatsi John T .
* Mugabo ibatisimu yatangwa n’abayoboke ba Yezu yarimwo ikintu gishasha .
Nk’akarorero , abahinga bamwebamwe batanga iciyumviro c’uko indimi zitabayeho bukwi na bukwi , ariko ko zagiye ziratera imbere zivuye ku rurimi rwa mbere na mbere .
Hanyuma karamera nk’akabunda , kagaca gatangura kugendagenda gasoboka muri ako karere kuzuye umusenyi .
Dushobora gute kumenya abasenga b’ukuri ?
Bibiliya ivuga iti : “ Nkako , inzu yose yubakwa n’umuntu , mugabo uwubatse ibintu vyose ni Imana . ”
Ariko rero , kenshi vyarambabaza igihe abanyamuhana bansavye kuvuga icongereza aho kwirigwa ndigora ngerageza kuvuga ururimi rwabo !
Utwo dutsi ntituri mu mutwe ahubwo turi mu nda .
Kugira akigoro gakomeye ngo ukoreshe ururimi rw’ibimenyetso vyerekana ko ukunda abavukanyi n’abavukanyikazi bacu b’ibipfamatwi be n’uko ububaha .
Mu masaha 24 aheze , ni igiki neza na neza noba nakoze cerekana ko nkunda kandi nubaha uwo twubakanye ?
Paulo rero ‘ yarabaye uwa mbere mu vyo gutera iteka ’ abasuku bagenziwe . ​ — Rom . 12 : 10b .
Igihushanye n’ivyo , bibiri vya bitatu vy’ayandi mashirahamwe barabiyeko , basanze ahagarikiwe n’abantu biyemera cane , ivyo bikaba vyaratumye ayo mashirahamwe ahomba canke ntatere imbere . ”
Umwanditsi wa Zaburi ashobora kuba yari afise ku muzirikanyi ivyo bintu vyabaye igihe yavyurirwa umutima wo kuvuga ati : “ Igikorwa [ ca Yehova ] n’icubahiro , n’ubgiza , ukugororoka kwiwe kwamah’ibihe bidashira .
Uko ibintu bitera bidabuka muri ino misi y’iherezo y’ivy’iyi si , ni ko n’ibintu vyotuma umuntu yidodomba vyoshobora gutera vyongerekana .
Mugabo rero hariho ikintu kidasanzwe abakirisu bo mu ntango bari bamenyereye , na co akaba ari ukwibuka urupfu rwa Kristu .
Dawidi n’abantu biwe bagarutse bakabona ivyabaye , baciye baturikisha bararira .
Ku bw’ivyo , naho urupfu rutari mu mugambi Imana yari ifitiye abantu mu ntango , rwaratumye Yehova aronka akaryo ko kwerekana ko afise ububasha bwo gutuma n’abapfuye basubira kuba bazima .
Abari barabiriye abagore b’abanyamahangakazi barigaye babigiranye ukwicisha bugufi maze barakosora inzira zabo zitabereye .
Naho ari ukwo , abahinga ntibaratahura neza na neza ingene iyo nyoni igira urwo rugendo rutangaje rwose .
ICO BIBILIYA IVUGA : “ Umuntu wese atebuke kwumva , atebe kuvuga . ” ​ — Yakobo 1 : 19 .
Raba ukuntu yabibukije ibimenyamenya vyari bizwi .
Bill Yacos yandemesheje kubigenza gutyo nyene no gukorana mu busuku n’abavukanyi na bashiki bacu .
Umuntu yohava yiyumvira gutyo .
Yehova yarigishije Ivyabona vyiwe ukuntu bokwigisha ukuri kwo muri Bibiliya mu buryo bukora ku muzirikanyi no ku mutima .
Nk’uko irya nkuru yo mu ntango ivyerekana , abantu benshi baremera ko bashobora kuvugana n’abapfuye be n’uko amakuru baronka biciye ku vy’ubupfumu aba avuye ku bapfuye .
Ni kubera iki Yezu yazuye abantu naho n’ubundi boruhiye gusubira gupfa ?
Ivyo Yezu yavuze muri Yohani 5 : 22 , 23 birerekana neza ico kintu . Yavuze ati : “ [ Data nta ] n’umwe acira urubanza , mugabo uguca imanza kwose yagushikirije Umwana , kugira bose batere iteka Umwana nk’uko batera iteka Se .
Nta muduga wo kumujana .
Inyuma ya Pentekote , ni igiki Abakirisu bagize kugira bongereze umunezero wabo ?
Ubwo bwoko bwabaye muri ako karere kuva kera cane imbere y’uko Abasupanyoli bahashinga intwaro ya gikoloni .
Wa mugabo w’intahemuka Bowazi yari azi neza uwo muce mwiza wa kamere z’Imana , kubera ko yabwiye wa Munyamowabukazi Rusi yitwararikana urukundo inabukwe yari yarapfakaye , ati : “ Uhoraho akwishure ivyo wakoze , uhabge impēra ishitse n’Uhoraho ” .
Ntituramenya ingene tuzohunga .
Intwaro z’abantu zaragerageje uburyo bwose bubaho bwo gutegeka .
Ukwo ni ko bigenda igihe dutanguye kwiga rwa rurimi rutunganye rwerekeye ukuri kwo muri Bibiliya .
Mu kudondora ibintu biranga ukuntu urwinjiriro rw’urwo rusengero rwubatswe , agatabu kamwe kavuga ibirwerekeye ( The Story of the Old Cathedral ) , akasohowe n’abakuru b’urwo rusengero , kavuga gati : “ Hejuru y’urubaraza , hariho agace keza cane kubatswe nk’inyabutatu , hagati na hagati yako hakaba hashishimweko rya zina ry’Imana ridakwiye kuvugwa , iriri mu bidome vy’igiheburayo bininibinini bikuyengejweko inzahabu . ”
“ Kubera iki wakekeranije ? ”
Incuro zibiri zose , Yezu yarirukanye abadandaza n’ibidandazwa vyabo , arabakura mu rusengero .
Kuronsa ibifungurwa n’uburaro abo bavukanyi n’abavukanyikazi benshi biyongereye bari bitanze kuza gukora bavyishakiye , vyarahaye abagize umuryango wa Beteli uturyo two kwitanga rwose ngo baterere agacumu k’ubumwe muri iyo poroje .
Kurindira Yehova ntibitera ishavu nk’ukurindira umuduga watevye .
Ico gitabu , icanditswe n’umuganga Luka , kirimwo inkuru ikora ku mutima yerekeye igikorwa abakirisu baranguye mu kiringo c’imyaka 28 , kuva mu 33 G.C . gushika mu 61 G.C .
Mu bihe bimwebimwe , imigwi y’abamamaji yararinganijwe , mu yindi na yo havukamwo amashengero matomato .
Urabona ko Ubwami bw’Imana buzotuma ivyo igomba bikorwa kw’isi , atari ivyo abantu bishima kandi bahahamira ubukuru bagomba .
Nta n’umwe , yaba Musa canke Aroni , yari gushobora kugira ico avugiye abo bantu ico gihe .
Gukora ivyo Imana igomba no kumenya ko duhimbara Segaba w’ibiriho vyose ni vyo bizana umunezero nyakuri kandi uramba .
Mu myaka itari mike , perezida w’urwego rw’i Pensilivaniya yaba kandi ari imbere mu bagize Inama Nyobozi .
Ni igiki kidakwiye kwirirwa kiratuma Abakirisu b’abizerwa bavurunganirwa , kandi ni ukubera iki ?
Wa muganga Luka na we yaraherekeza intumwa Paulo mu ngendo ziwe .
Nitwasaba Yehova ubukerebutsi n’inkomezi tumwizeye , azobituronsa . ​ — Yak .
INDIRIMBO : 85 , 134
Akenshi usanga ababijejwe babwirizwa gushira ibidunduri mu mabarabara yo mu gisagara kugira ngo batume abashoferi bagabanya umuvuduko .
Kubera ko twebwe abantu twaremwe “ mw’ishusho y’Imana , ” turatandukanye n’ibikoko kuko dushobora kugaragaza kamere nk’iz’Imana , nk’akarorero urukundo , ubutungane n’ubukerebutsi .
Biri n’ico bivuze kubona Bibiliya igabisha canecane abakirisu b ’ “ abatunzi bo mu vy’iki gihe ” ngo boye “ kwibona ” .
• Guca munsi y’ingazi biratera umukoshi
Ni igiki kitwemeza y’uko Imana itarenza uruho rw’amazi ku bubi ?
Yoba azobishikako ?
Iyo wumva , ni nde yari kumwaka ikinga ga yemwe !
Mugabo , basubiye kugutakambira ukabumva uri mw ijuru , ukabarokora ibihe n’ibihe kubg’imbabazi zawe ” .
Uwo mwaka wose nagumye niyumvira ibijanye n’umurimo w’ubumisiyonari .
Ivyo bimaze kurangira , abahinga mu vy’ukuvuguta baca bubakira hejuru ya nya shashara maze bakareka ico bubatse kikuma .
Yezu yari azi neza yuko igihe abantu bahagiritse kubaho , baba “ [ a ] ta co bashoboye mu rupfu . ” ​ — Yesaya 26 : 14 , NW .
Ego ni ko , Abayuda b’inyagano bararonka ivyo bari bakeneye ku mubiri . Ariko none ivy’impwemu vyo bite ?
Twizigiye vy’ukuri Umuremyi wacu , nta kizotuma tumaramara .
Uwundi muntu atagumije amaso ku gashimwe ni Dema , uwakorana n’intumwa Paulo .
Paulo yahimirije ati : “ Bene Data , umuntu n’iyo yobonekakw icaha , mwebge ab’impwemu [ “ mubogore , ” NW ] ūmeze artyo . ”
Wewe wiyumvira iki kuri izo nyifato zitandukanye ?
Ikiyago cakurikiye kirerekana neza ko Bowazi yari arajwe ishinga n’ukuntu uwo munyamahangakazi Rusi ata co yari yirengeje .
Sinshaka gusubira kumubona ” .
N’ikindi kandi , narashikiwe n’ibintu bitari bike vyatumye mbwirizwa gusuzuma imvo zituma nemera Imana ; guca ku ntebe y’ishure vyaratumye rero ndushiriza kujijuka ku bijanye n’ivyo nemera . ” — Rose .
Twipfuza gufasha abantu kwizera Yehova Imana , babone ko abaho koko kandi ko bashobora kumwiyegereza .
Dushobora gute kumenya neza ikiri mu mutima w’umutohoji ?
Ahubwo , Paulo yamamaje ‘ Kirisitu yamanitswe , ’ ari vyo amahanga yateye akagere ngo ni “ ubupfu ” butagira uko bungana .
Nimubandanye Kubigisha Inzira ya Yehova
Ntazoduhemukira .
UKO umwanya waguma urengana , ni ko David yarushiriza gushavura .
NI KUKI none umuntu yoshaka guhindura idini canke ivyo yemera ?
Aba ni abo mw’ishengero rya Lyndale bari hanze y’Ingoro y’Ubwami yabo nshasha
( b ) Abakirisu b’abacungezi bashobora gute kurimbanya ikenerwa ry’ukugorora ibigoramye n’ikenerwa ry’ukuvuga ikorane neza ?
Niwumvire ico umutima wawe ukubwira .
Isengesho rivuye ku mutima rizodufasha kandi kuguma dufise uburimbane mu bwenge kugira ngo amarushwa turimwo ntaturengere .
Niwigane uburorero bumwebumwe bwerekana yuko igitabu Ivyo Bibiliya yigisha ari ngirakamaro .
Uko ico kintu kirushiriza kuba hafi y’ijisho ry’ako gatangurirwa , ni ko ako gashishwa karushiriza kukibona ivyezeri .
Mu kiringo c’amayinga atari make , imisi yose mu gatondo no ku mugoroba , ico kigatanya Goliyati w’Umufilisitiya yaracokora ingabo za Isirayeli , akazihigisha ngo zirungike intangamarere barwane .
Naho bomushiramwo impemu zingana gute , izo mpemu ntizoshobora gutuma utugingo ngengabuzima twapfuye dusubira kuba tuzima .
Ica kabiri ni Abagalatiya 2 : 20 , ikimfasha kumenya ko Kristu Yezu ‘ yanyiguze . ’
Mu buryo nk’ubwo nyene , uwukiri muto akironka uruhusha rwo kugendesha umuduga yoshobora kwumva afise ubwoba bw’uko azohava agira isanganya , canecane igihe azi ibitigiri vyerekana yuko abakiri bato batwara imiduga ari bo bakunda kugira amasanganya kuruta abakuze .
Intumwa Paulo yahimirije abakirisu bagenziwe ati : “ Umuntu wese avugane ivy’ukuri na mugenzi we ” .
Ni abambuzi kubera basaba ibiguzi birenze urugero abashaka kugura ibitungwa vyo gutangako ibimazi .
Frank avuga ati : “ Kubera ukuntu ibintu vyifashe kw’isi , abantu benshi bararajwe ishinga n’ivya kazoza .
Ntureke ngo Shetani yonone ubucuti ufitaniye n’Imana .
Ego ni ko , Yehova ntiyaduhaye inkingi y’igicu be n’iy’umuriro kugira ngo zituyobore zitujana mw’isi nshasha .
9 , 10 . ( a ) Ni mu buryo ki abarorerezi bashobora kuba isoko ry’indemesho mw’isiganwa risaba ukwihangana ?
Narabajije uwo twari dupfunganywe nti : “ Ico uriko urasoma ni igiki ? ”
Iyo miryango ntigereranya ya miryango 12 igize Isirayeli yo mu buryo bw’impwemu .
Dutsimbataje inyifato yo mu mutima nk’irya ya Yezu , ntituzotakaza umunezero wa Yehova naho ibintu bitama nantaryo bishika uko twavyitega n’igihe tuvyitegeyeko .
Ni nk’aho rero tuba turiko turakura tuva ku kuba urugemwe tuja ku kuba umukirisu ahumuye , tukaba nk ’ igiti c’inganzamarumpu .
“ Kwemera gukosorwa ni ikintu gihambaye kidufasha gukura mu vyiyumviro .
Nimuze rero twiyemeze kugamburuka uburongozi bwiwe mu mice yose y’ubuzima .
Turakwiye kubandanya twihata kandi tugakurikiza ubuyobozi Imana iduha . Mu Baroma 12 : 2 hagira hati : “ Mureke gushushanywa n’ivy’iki gihe , ahubwo muhindurwe mu guhindura umuzirikanyi wanyu ukaba musha , kugira mwiyemeze neza ukugomba kw’Imana kwiza , kwemerwa kandi kutagira akanenge ukwo ari kwo . ”
Rimwe na rimwe , turashobora kwumva biturengeye canke ata vyo dushoboye igihe duhawe igikebere gishasha , canke tugashobora kuba turiko dutakaza uburindutsi bwo kubandanya igikorwa cacu c’ukwamamaza Ubwami , uko duhangana n’ukutanegwa ibintu canke ukurwanywa kurushiriza kwongerekana mu cibare cacu .
Yari afise umutumba mutoyi cane n’amaboko magufi .
Izo mvugo zompi zerekeza ku bacamanza bo muri Isirayeli .
Noba nzosubira kubona barumunanje ? ’
Vyoba ari vyiza ku Mukirisu kurondera kuvurwa ku gitangaro igihe arwaye indwara ibabaza canke kumbure idakira ?
Umukenyezi umwe twari kumwe ageze mu zabukuru yaratanguye kuririmba ayingira ururirimbo rwatunganijwe n’Ivyabona vya Yehova mu gihe ca ya Ntambara ya kabiri y’isi yose .
Yezu yari azi ko atari vyiza kugerageza Yehova yiteze ko abamarayika bomutabaye igihe yokoze ibintu nk’uko yishakiye .
Ariko rero , Yehova yari yaragabishije imbere y’igihe yuko uwo wese yobaye umwami ‘ atokwirondereye amafarasi menshi ’ kandi ko ‘ atogize umukimba w’abagore , kugira ngo ntibaze bahindure umutima wiwe . ’
Ni kuki ari ngirakamaro ko umuntu ahitamwo neza abo vyifatanya ?
Biragaragara ko igikorwa co kwamamaza yaranguye imbere ya rya Segenya carimwo no kuburira abantu .
Ntureke rero ngo ico kibanza kiwukurye .
Ku vyo gukunda bene Data , mukundane rwose [ canke , “ mugiriranire igishika kirangwa ikibabarwe ” , NW ] ” . — Abaroma 12 : 9 , 10 .
Igitabu kimwe ( Zoos in the 21st Century ) kivuga giti : “ Mw’isi aho amashamba cimeza ariko arahona , abanyagihugu na bo bakaguma bijukira ibisagara , kugira ngo abantu benshi babone ibikoko usanga baja kubirabira mu bibanza bitungirwamwo . ” Ivyo ushobora kuhasanga
Nk’akarorero , “ umumarayika Gaburiyeli [ yaratumwe ] n’Imana mu gisagara c’i Galilaya citwa Nazareti ” .
Ico cago Nowa yababwira ko kizoza , babona ko ari ikintu kitabaho kandi kidashoboka !
Bibiliya ivuga iti : “ Iki ni co urukundo rw’Imana rwerekaniweko mu bitwerekeye , kuko Imana yatumye Umwana wayo w’ikinege mw’isi . ”
Dushobora gute gukunda Imana muri ico gihe nyene tukayitinya ?
Vyashikirijwe n’umwanditsi wa Be maso !
Abizera ko urupfu rwiwe rwo kwitangako inkuka rushoboye kubacungura bariteze kuzokurwako igicumuro n’urupfu maze bakiberaho ibihe bidahera mw’Iparadizo hano kw’isi .
Muri utwo turorero twose , urabona ko Yehova yitwararitse kuronsa abo bose bamurondera akaryo ko kumumenya .
Umuvukanyi Russell yari azi neza yuko atoshoboye guhata umuco ngo ukayanganire ku gitabu c’Ivyahishuriwe , nk’uko nyene ingenzi idashobora gutuma izuba riseruka igihe caryo kitaragera .
Umuhanuzi w’Imana yakiriye gute ubutumire yahawe na wa mutama , kandi ivyo vyagize ingaruka iyihe ?
Ariko none ‘ mugenzi wacu ’ ni nde ?
Incabwenge imwe mu vya Bibiliya yavuze iti : “ Imana ntiyitandukanya n’Ijambo ryayo .
Baratanga umwanya wabo , inguvu zabo n’ubutunzi bwabo kugira ngo bateze imbere ugusenga gutyoroye .
Igihe rero haje ayandi mahinduka biratesha umutwe . ”
Tugeze hafi y’umupaka , twasanze abasoda ba leta badukikuje .
Ivyo vyatumye abantu bagamburuka bashobora gukurwako akaga kabashikako k’ugukora icaha n’ugupfa kavuye ku kugambarara kwa Adamu .
Ariko hirya no hino kw’isi , abantu barahanzwe n’ikibazo c’umuyagankuba n’igitoro .
Ku bw’ivyo , turakeneye kwirinda ngo ntitwoshwe n’ivyiyumviro twahora dufise kera canke ibindi bintu .
Ivyo Yehova yaremye , yarabishingiye ingingo zituma bikorana .
Abantu Bose Boba Bazoteba Bakangana ?
Umusoda wo mu gisoda ca Hitler yasokoroye inkoho yiwe ntoya , ayimfatirako mu musaya , maze ambaza ati : “ Uremeye gupfa ?
Canke ashobora kuba yayanditse yiyumvira abaririmvyi b’Abalewi .
Muri Bibiliya , Imana irasigura ico twokora ngo tuyihimbare , igituma ireka hakabaho ikibi , be n’ico izokorera abantu muri kazoza .
Ni kubera iki bihambaye kugira gutyo ?
Mu bisanzwe , icipfuzo bafise ku mutima , ni uko abana babo batoshikirwa n’ingorane nk’izo .
Nk’akarorero , mu Banyefeso 4 : 29 havuga yuko imvugo mbi ari “ ibiyago [ “ biboze , ” NW ] . ”
Abantu canke amashirahamwe bagize antikristu barakwiragiza ibinyoma , bagahakana ko Yezu ari Kristu canke Mesiya , bakagerageza kugoreka isano riri hagati y’Imana n’Umwana wayo Yezu Kristu .
15 , 16 . ( a ) Ugukorera ku mugaragaro kwacu hamwe n’ugusagamba kwacu mu vy’impwemu bimara iki , ariko ivyo vyoba bikwiye kuduhagarika umutima ?
Naho ico gihe umuvukanyi Russell ari we ahanini yashikiriza insiguro , yari azi ko “ ata muntu aba mudasubirizwa , ” kubera ko ‘ ico gikorwa atari ic’umuntu ; ari ic’Imana . ’
Amaherezo , abitanze 382 baramamaje babigiranye umwete mu vyibare vyari bimaze kuvugwamwo inkuru nziza gake cane .
Tweho bite ? Igihe turanguye ikintu ciza cane , ubwo ntihari aho Yehova aba ‘ aturetse kugira ngo atugeze , ’ maze ibiri mu mitima yacu bije ahabona ?
( a ) Igihe wiyegurira Yehova , wamusezeraniye iki ?
6 : 64 ​ — Igihe Yezu yatora Yuda Isikariyoti yoba yari azi yuko yomuhemukiye ?
Damasiko
Gutahura ko umukirisu wese “ azokwikorera umutwaro wiwe bwite , ” bituma twubahiriza uburenganzira abandi bafise bwo kwifatira ingingo .
Tuvugishije ukuri ivyo birashoboka , kubera ko Bibiliya ivuga yuko “ ibintu bibi bishikira bose ! ”
Rimbura akarorero k’umugabo yitwa Henry be n’umugore wiwe Suzanne .
Icagezwe c’urukundo mu mitima
Ntituzi uko abo bakurambere bose bitwa , ariko biragaragara ko batahura akamaro k’isengesho .
Uwo ari we wese ashimye gutanga intererano kugira ngo ashigikire igikorwa co kwigisha Ivyabona barangura , barahimbarwa no kuyakira .
( 5 ) Beerens , M .
Ivyo bintu hamwe n’ibindi vyaragize uruhara rukomeye mu ntunganyo Imana yashizeho kugira ngo abantu bironkere ingabire ruheta .
Ku musi ugira indwi Imana inonosora ibikorwa vyayo yakoze ; iruhuka ku musi ugira indwi ibikorwa vyayo vyose yakoze . ”
Ku bw’ivyo , Umukirisu w’ukuri ntahebera ubuzima bwiwe imigambi kanaka y’isi .
Arashobora kandi kubona imbere y’igihe ivya kazoza kubera ko ‘ ahera kw’itanguriro akavuga ivy’iherezo , agahera no mu bihe vya kera akavuga ibitaraba ; akavuga ati Imigabo yanje izohama ’ .
Vyongeye mu mico kama imwimwe , vyitezwe ko umushitsi abanza kwanka igihe atumiwe rimwe canke kabiri ; mu yindi na ho , wanse bifatwa ko udashima .
Igihe ba bagenzi batatu ba Daniyeli banka gusenga igishushanyo amahero , uwo mwami aca ategeka ko batabwa mw’itanure ryaka umuriro .
Ni igiki cari gihaze ?
Ariko ntiwumve , urakwiye kumukosora igihe akoze amakosa akomeye .
Ico gitabu kivuga kandi giti : “ Bakwiye guca bahamagara imodoka rusehabaniha igihe izo ntandara zirengeje iminota itanu , igihe uwo muntu aciye asubira gufatwa ubwo nyene , canke igihe adaciye atora akenge inyuma y’iminota mikeyi izo ntandara zirangiye . ”
Mugabo ni twe twihitiramwo ukuntu duserura ishavu tuba dufise .
Ariko nariyumvira nti : ‘ Ngiye kwica abantu kandi Bibiliya ivuga ngo “ Ntukice . ”
Twinshi muri two duciye tuvuga duti : ‘ Ivyo si vyo ’ .
Ivyo birashobora gutuma uba umuturi wa Yehova , nk’uko vyari no ku bandi bantu bo mu gihe ca kera .
Ariko ubu hari abarenga 200.000 hamwe n’Abanyabeteli amajana bashigikira igikorwa co kwamamaza kirokora ubuzima .
Ego canke oya ?
Batanguye gukorera Yehova mw’isi iganzwa na Shetani .
Abo bavukanyi b’ingenzi bahanuye abo muri iryo shure kuba abantu bitwararika abandi , bagafata abandi nk’uko Kirisitu yabafata , bakongera bakemera igikorwa ico ari co cose bashinzwe .
Akarorero k’agahomerabunwa ko kudatera iteka ubukuru bwo mu vya gitewokarasi bwashinzwe n’Imana kari aka Kora .
Kandi na zo twarazironse !
Hari abamana urwo rugamba mu mutima , bakabura ico bofata n’ico boreka .
Ica kabiri cari cerekeye amahundo indwi y’intete nziza be n’amahundo indwi y’intete yonze .
Iyo kamaze gukura ubwo buhinga ntibuba bugikora .
Ubu kuruta ikindi gihe , “ iherezo ry’ibintu vyose riregereje . ”
( Soma Abagalatiya 5 : 19 - 21 . )
N’iyo nyene ni imice ihambaye ya ya porogarama yo kutwigisha kugendera mu nzira ya Yehova .
Yehova Imana ashaka ko tutitinya kwama tumubwira ingorane zacu .
Serugo yokwisunga iki mu guhitamwo ishengero umuryango wojamwo ?
6 : 3 — Ni mu buryo ki izina ry’Imana ritamenyeshejwe Aburahamu , Isaka na Yakobo ?
Iyo nyigisho yatumye hatsimbatara umugenzo wo kwihutira kubatiza inzoya zivutse .
Kuvuga izindi ndimi vyoba biva ku Mana ?
Elifazi yabajije ati : “ Umuntu vyoshoboka bite kw aba uwera ?
Shetani ahenda abantu gute ?
Ukubigenza gutyo bizotuma twironkera ijwi ryo mu mutima ryiza .
None ushobora gute kuronka abagenzi nyakuri ?
Umunara w’Inderetsi ( mu gifaransa ) wo ku wa 15 Ruheshi 1983 , urupapuro rwa 30 - 31 , uratanga amakuru yo kurimbura yerekeye abubatse .
Ivyo vyanditswe , bishizwe hamwe n’Ivyanditswe vy’Igiheburayo , vyarujuje ibitabu vya Bibiliya vyemerwa ko vyahumetswe .
Uko uwo muhungu w’imfura yoba yaravyakiriye kwose , uwumviriza wese yari ahanganye n’iki kibazo ngo ‘ Wewe woba uzonezeranwa n’abanezerwa mw’ijuru igihe hari umucumuzi yihanye ? ’
Narakoreye kandi ku Ngoro z’amaterano i New York City .
Yezu yashimitse gute ku kuntu ukubona ko ibintu vyihutirwa kwobaye gukenewe ?
Abantu barashavura igihe hariho intambamyi zituma bataronka akazi kanaka , batiga amashure manaka , bataronka uburaro bunaka canke ibindi bintu vyankenerwa .
Tuzirikanye ku vyashikiye Hezekiya , twoshobora kubona ko dukwiye gukuraho ikintu cose cogeramira ubucuti dufitaniye n’Imana canke codusamaza ku buryo tutitwararika ugusenga kw’ukuri .
Ariko none , ubwo vyoba biranga ubukerebutsi kurondera kumenya ikintu cose coba kidukwegereye ?
Vyongeye , Dawidi ubwiwe yari umunyembabazi , tukaba tuzi yuko Yehova agirira imbabazi abagira imbabazi .
Nimuze nyabuna dukore duhuza n’amajambo yahumetswe agira ati : “ Umunyabwenge ni uwubonye ivyago akihisha , mugabo abantu batazi utuntu n’utundi bararengana bakabwirizwa kwibonerako . ” ​ — Imig .
Intumwa Paulo ituburira iti : “ [ Im ] pwemu [ i ] vuga [ i ] vyeruye yuko mu bihe bizoza bamwe bazota ivyizerwa , bagashira umutima ku vy’impwemu zizimiza no ku vy’inyigisho z’abadayimoni . ”
Ese ukuntu amaherezo igihe akavura kaguye bumva baruhuriwe cane !
Hamwe tutoronka imfashanyo iranga urukundo iva kuri Yehova , nta n’umwe yomucaruka .
Abasomyi ba Bibiliya bamwebamwe ni ko biyumviriye .
Ariko rero , mu myaka ya 1990 , hari ikintu cabaye cagize ico gikora cane ku buzima bw’abantu barushiriza kwongerekana bo muri ayo mazinga .
Uwo mwubakanye arafise ikintu gihamba - ye agomba kukubwira . Woba none witeguriye kumwumviriza ?
4 : 3 , 4 , 10 .
Dukwiye Kuzamba Mana Dute ?
Twisunze iyo ngingo mfatirwako , umwe Jodie twavuga mu kiganiro gitangura , yari akwiye gutwara ya mahera kubera yuko benshi mu bo mu kibano ciwe canke mu “ gisagara ” abamwo , biboneka rwose ko boyatwara .
Abamamaji b’Ubwami bo mu gihe ca none barafise ibikoresho Paulo atari afise mu gihe c’ubusuku bwiwe .
Ijambo ry’Imana ridukura amazinda riti : “ Ingero z’ukwicisha bugufi bo n’ukwubaha Uhoraho ni zo butunzi n’icubahiro n’ubu [ zima ] ” . ​ — Imigani 22 : 4 .
Intumwa Paulo yanditse ati : “ Sinkundira umugore . . . kw aganza umugabo , arikw atekereze .
Igihe haba hari igice c’umugende cononekaye cane , abahinga baca babanza gukevya amazi kugira bahakore .
Kurondera agatabu karimwo amajambo akunda gukoreshwa .
Yehova ariratira “ abiwe ” .
Hejuru iburyo , agakobwa : © Bruno Morandi / age fotostock ; ibubamfu , umugore : AP Photo / Gemunu Amarasinghe ; hepfo iburyo , impunzi : © Sven Torfinn / Panos Pictures
Abagize isezerano rishasha bobwirijwe kandi kurobanuzwa impwemu nyeranda .
Abo bapolisi bavuze yuko jewe , abavyeyi banje na mukurwanje tutokwangajwe turamutse twifatanije n’umugambwe w’Abanazi .
Yariko araca irya n’ino ca kimenyetso c’ukuhaba kwiwe be n’ic’insozero y’ivy’iyi si .
Dukwiye “ [ kubandanya d ] usaba Imana ” mw’isengesho ukwizera n’ugutahura kandi tugakomeza utwigoro twacu mu vy’ukwiyigisha ibijanye n’ibibazo ivyo ari vyo vyose canke inkeka izo ari zo zose .
Kubera yuko wari wakozwe ata mwambiro ushizwemwo , wari ubase kandi ukecagurika kandi wategerezwa kumanyagurwa kugira ugabanganywe .
Biri n’ico bivuze kubona intumwa Paulo yarahumekewe kugira ngo ibivugwa muri Zaburi 112 : 9 avyerekeze ku bakirisu bo mu kinjana ca mbere .
Urabona yuko mu canditswe turiko turihweza Yezu yavuze ati : “ Munyigireko ” .
INDIRIMBO ZIKORESHWA : 134 , 24
Tom : Twari tumaze amezi atandatu gusa twubakanye igihe umukenyezi wanje Yoonhee yamenya ko yibungenze .
Umutwe mukuru umwe w’intashankuru The Star yo muri Johannesburg muri Afirika y’Epfo , usomwa ngo : “ Umusi wo mu buzima bw ’ ‘ igihugu kirushirije kuba kigandaguzi mw isi . ’
Aburahamu yabwiye Sara ati : “ Nyarutsa !
Iyo fi ahanini ikingirwa n’urukoba rwayo .
Avuga ati : “ Abandi bariko barandaba , ngize gutya , mbona igugu ry’abantu bampagaze hejuru .
“ Igihe ukunda umuntu ntiwibanda ku tunenge twiwe , ahubwo wibanda ku kigoro agira arondera gukosora ibintu . ” ​ — Aaron .
Ariko mu bindi bihe na ho , abagabo barezwe na ba sebibondo bakara cane kandi batanyinyuka usanga na bonyene bakunze guca bafata abana babo muri ubwo buryo nyene .
Imana yatanze urwo rutonde rw’ibisabwa kugira yerekane ko ishaka yuko abagenywe bakora bisunga ingingo ngenderwako ziri hejuru .
Ariko rero , Paulo yagabishije ati : “ [ Ubumenyi ] burakakīsha , arik’urukundo rurubaka . ”
Bisubiye , mu gihe tudatahura ingingo ngenderwako z’ishimikiro bimwe binogangije kandi ngo tuzemere , ntitwoshobora gufata ingingo ziranga ubukerebutsi kandi ukwizera kwacu kwoshobora guhungabana bitagoranye .
Ubu ko dufise ivyo vyiyumviro bitandukanye ku vyerekeye ukwizera , nimuze turondere inyishu z’ibi bibazo bikurikira :
Yezu yagaragaje gute ukwihangana n’ubuhanga vya wa Mubumvyi Ahambaye ?
Dalia aramamaza kandi inkuru nziza mu kurungika ubutumwa akoresheje telefone yiwe ngendanwa .
Yehova yarishuye amasengesho ya Dawidi kubera ko yari umusavyi wiwe w’intahemuka .
Igihe Yezu Kirisitu yari kw’isi , “ yaricishije bugufi , araganduka no gushitsa ku rupfu , kand’urupfu rwo ku [ “ giti c’ukubabarizwako , ” NW ] . ”
Lisa yarakorana n’abandi mu busuku , akabatumira aho aba , akongera akarondera abagenzi bashasha .
No kuri twebwe kirakenewe nk’ukwo nyene .
Kukaba nkako , hafi ibice 65 kw’ijana vy’umubiri w’umuntu bigizwe n’amazi .
Aho kuvuga ukwo turihatira kugamburuka .
Milton yavuze ati : “ Kuva nkiri muto , dawe yaranteguye mu bijanye n’ivyigwa vy’indimi , bino nkaba narabikunze cane ku buryo igihe nari mfise imyaka 12 ari gake nahagarika ivyigwa vyanje ngo nje kuryama imbere y’isaha zitandatu z’ijoro ” .
14 : 31 - 34 .
Ariko rero , abasukurira Yehova baracitse kw’icumu muri ayo marushwa . ​ — Mariko 13 : 14 - 20 .
Ni kubera iki dukwiye kwitwararika ibivugwa muri ico gitabu co muri Bibiliya ca Yeremiya ?
RAJESH aba i Paliyad , ikigwati kimwe co mu Buhindi .
Ukwo si ko bizogenda ku barobanuwe , abafise icizigiro co kuba mw’ijuru , be no kuri bagenzi babo bafise icizigiro co kuba kw’isi .
Ariko rero , biratomoye ko dukeneye kuba abantu barobanura igihe duhitamwo abo twizigira .
Mbere yaragerageza no kubuza abandi kugaragaza ubwakiranyi . ​ — 3 Yoh .
Duhingura ibikoresho vyo kwigisha
Gukura gushika ku buhumure na vyo nyene bisaba kugira akigoro ko kuzigama ukutadohoka kwawe .
iyo mpanuro itangwa n’ikinyamakuru Corriere della Sera .
Ni isano irihe riri hagati y’uruhara Yezu afise be n’urwo abanega bakirisu bafise ?
( b ) Ni akaranga akahe ca gisagara kigereranya mw’Iparadizo ?
Twese turashaka kwiyumvamwo ko abandi , na canecane abo dukunda , bashima utwigoro twacu .
Mu vy’ukuri , twovuga ko ico ari ikintu ciza cane kubera yuko ari vyiza kurondera kubona ibintu ufatiye no kuntu uwundi abibona .
Nyene gushikiriza iyo nsiguro yasubiyemwo aya majambo ya Yezu : “ Ni mwunamure amaso yanyu murābe imirima , irēze igeze kwimbura ” .
Ikintu caza ubugira kabiri inyuma y’umwete yari afise mu busuku turangura , wari umwete yakorana ibikorwa yari ajejwe ku nzu y’abamisiyonari .
Nta mwikeko nk’uyo tugira , ngo tugaye abatari Ivyabona .
Ni umutego uwuhe utaboneka uri muri kimwe mu bikorwa vy’uruyeri vya Shetani , kandi ni impanuro iyihe ibereye hano iri mu Migani ?
Imisi yose nama nshaka kumenya vyinshi ku vyerekeye Umuremyi wanje kandi narubaha Bibiliya , naho ata na kimwe nari ndayiziko .
Hari abasubiramwo ico canditswe kugira berekane yuko Yezu na Se ari babiri mu baperesona batatu bagize Imana imwe .
Muri ibi bihe vya vuba , abanyasiyansi biyumviriye yuko umuco ugizwe n’uduhimba dutoduto cane tutaboneka .
Biyumvira yuko yokoresheje amayagwa ari muri co mu vyigwa yoshikirije .
Uwubakanye n ’ “ Umugore Atizera ”
Amaja mu mpera y’umurimo wiwe yari amaze igihe kirekire arangura , yarapfungiwe mw’izinga Patimo ‘ ahorwa ijambo ry’Imana no gushingira intahe Yezu ’ .
“ Twiyuhagire ubuhumane bgose bg’umubiri n’ubg’umutima , kuba abera tugushikishe kwubaha Imana . ” ​ — 2 AB’I KORINTO 7 : 1 .
Dusoma duti : “ Igihe kiragera , Kayini azana ishikanwa ku vyeze mu ndimiro , ngw abishikanire Uhoraho .
Kwiyegurira Imana bishikana ku gahimbare
Vuga ukuntu twoshobora kuvyakira mu buryo butandukanye budashimishije igihe duhawe impanuro , wongere usigure igituma abungere bakirisu bategerezwa kubandanya kugerageza kudufasha .
Kukaba nkako , ubuyobozi bwiza ni ntahara .
Igihe cose naramubona ariko arayisoma . Ariko mawe yandeze nk’umugatolika kandi imisi yose ku w’iyinga yaranjana mu misa .
Iyo bakurikiza ubuyobozi Imana yari yabahaye , bari kugira agahimbare kamaho .
Bukeye amabutike yose yaragaragara . ” ​ — Paul wo muri Zimbabwe .
Nugerageze gukorana mu busuku n’abamamaji batandukanye .
Yezu aramusubiriza umutima mu nda ati : “ Musazawe arazuka . ”
Igitabu kimwe ( In the Steps of St .
Umubano w’abubatse nk’uwo woba ushobora kuroranirwa ?
Wewe ubona inyishu z’ibibazo bihambaye nk’ivyo zifise agaciro kangana iki ?
Baremera icese kandi yuko we yagennye Umwana wiwe , Yezu Kirisitu kuba umuragwa w’ibintu vyose , n’uko yamushinze ubukuru bwose mw ijuru no kw isi .
Biboneka ko abo bantu bari mu rwego rw’abacuraranzi ba mbere .
Ariko rero , Imana yahavuye itangura kurema , ubu hakaba haciye imyaka idaharurika .
Umuhango ushobora kwizigira Yamara , hariho ubundi buhanuzi buriko buraranguka mu buryo bwibonekeje muri iki gihe cacu .
Utwana tubiri dutoduto na two turiko turamenyerezwa .
Yamara rero , twaragira ibihe vyiza turi kumwe n’abavukanyi kandi twarakunda cane ubusuku .
Huzuye urushanga . ”
• Ni mu buhe buryo abasavyi b’Imana bazotonda urugamba ?
455 B.G.C . , ‘ icagezwe co kuvyura Yerusalemu ’
Yamara , dutegerezwa kugamburukira Imana kandi tukama tuyizigira .
‘ Iyo misi muze muyigire mikuru yo kuninahaza Uhoraho , kandi muze munezerwe rwose ’ . ​ — GUSUBIRA MU VYAGEZWE 16 : 15 .
Kuko na Kristu atishimishije ubwiwe . . .
SUMATRA
Ukwihangana kwa Yehova Imbere y’Umwuzure
Imana yari yaratoranije mwene abo , kandi kuri Pentekote yo mu 33 G.C . , yari yarabagize ihanga rishasha ryo mu buryo bw’impwemu , ari ryo ‘ Isirayeli y’Imana . ’ — Ab’i Galatiya 6 : 16 ; Luka 18 : 7 ; Ivyakozwe 10 : 34 - 45 ; 1 Petero 2 : 9 .
Yari gukora iki none ?
Utwo tugingo ngengabuzima hamwe n’ukwo kuntu dufatanye rwose ni igitangaza .
( 2 )
ICOBAFASHA GUTORA INYISHU : Nimusome 2 Abami 18 : 6 .
Bibiliya irakwigisha ukuntu wokwiyegereza Imana
Agira ati : “ Kumenya ivyandikano vyari bikwiye kuja mw’Isezerano rishasha be n’ibitari bikwiye kujamwo , ni ikintu kitigeze gifatirwa ingingo n’inama n’imwe y’idini canke umuntu n’umwe . . .
Mu nyuma , igihe Senakeribu yariko arasenga imana yiwe y’ikinyoma , abahungu biwe baramugandaguye . — Yesaya , ikigabane ca 36 n’ica 37 .
Ni ibiki bituma abavyeyi bamwebamwe baremesha abana babo kurindira kubatizwa ?
Vy’ukuri , na twebwe nyene turashobora kuguma mu kutadohoka kwacu naho turi abanyagasembwa .
Imwe muri izo nkuru ni iya Ananiya na Safira , abo bakaba bari umugabo n’umugore bo mw’ishengero rya gikirisu ryo mu kinjana ca mbere ry’i Yeruzalemu .
Reka turabe ibijanye n’ikirere be n’utugingo ngengakamere .
Ivyo bivana na Salomo .
Aburahamu yoba yarakosowe mu vyo yavuze ?
Nimuze rero tugume dushingira ivyiyumviro vyacu kuri kazoza kakaka kabikiwe intahemuka za Yehova bose .
Ku gatwe k’igice co mu Buraruko bwa Amerika y’Epfo hari agace k’ubutaka kinjira mw’ibahari kitwa Guajira .
Rimwe muri ayo mashengero yakoresha iyo nyubakwa ryabwirijwe kuza riragira Ikoraniro ry’insiguro y’icese isaha imwe n’igice zo mu gitondo .
Naragendeye umuryango wabo kugira ndabahumurize , mugabo ni bo bahavuye bampumuriza bakoresheje Ivyanditswe .
Amajambo agaragaza impuhwe arashobora kuremesha urwaruka ruriko rurarwana n’akosho konona k’urunganwe .
Ivyo biterwa n’ico ishirahamwe rimwe ryita “ inyifato ikwiragiye mu bantu benshi . . . yo kubona ko abageze mu zabukuru baba ata co bakimaze , ata co binjiza kandi bazeye uburaro n’uburamuko ku bandi ” .
Yavuze ati : “ Nabonye ari ikibanza ciza kandi ko igikorwa kihakorerwa ari ngirakamaro ” .
Ubwa mbere , amadini aratuma Imana itaninahazwa biciye ku nyigisho z’ikinyoma .
( b ) Yehova ahimbarwa na bande ?
Woba uriko uragira uruhara rushimishije koko muri iryo yimbura riteye umunezero ?
Boba ari abatunzi canke ba rurangiranwa ?
Abo bari Abayuda n’abatari Abayuda bemera , abo Imana yacaguye ngo babe ubwoko bwatowe kugira “ [ b ] umenyeshe hose kamere z’agahebuza ” z’umwe yabahamagara . ​ — 15 / 11 , urupapuro rwa 24 - 25 .
Izo nyiyumvo baseruye zijanye n’ibintu vyabaye mu kiringo c’imyaka nk’igihumbi , uhereye mu gihe ca wa muhanuzi Musa ugashika mu gihe c’inyuma ya bwa bunyagano bw’i Babiloni .
Nk’akarorero , Ijambo ry’Imana ryigisha yuko abubakanye ari bo gusa bakwiye kurangura amabanga mpuzabitsina , yuko ukumarana inambu y’umubiri kw’abasangiye igitsina kutemerwa n’Imana , be n’uko guterwa amaraso no gufata ibiyayuramutwe ku bwo kwinezereza bibuzwa n’amategeko ya Yehova .
Kubera ko dukikujwe n’ibintu bihumanye , ntivyoroshe ko tuguma turi beranda .
Kugira ngo ukingire umubano wawe , nuyage n’uwo mwubakanye kandi musenge muri kumwe .
Muri ubwo buryo nyene , ibigirwamana kenshi bidondorwa mu Vyanditswe ko ari ‘ umwanda . ’
28 Elisha yarabonye imikogote y’umuriro — Woba nawe uyibona ?
Warabonye ukuntu ukuri kwo muri Bibiliya kwagiye kuratomorwa wongera uribonera ukuntu igice kiboneka c’ishirahamwe ry’Imana cagiye kiraryohorwa .
Ni co gituma Yezu yuhiriye kuri uwo mugani iyi nkeburo yo gusozera igira iti : “ Ukwo ni ko bigenda ku muntu yirundaniriza ubutunzi mugabo atari umutunzi ku Mana ” . ​ — Luka 12 : 21 , NW .
Ivyo bikorwa , ushizemwo n’ic’uguhindura abantu abayoboke cakozwe n’abamisiyonari benshi b’abizerwa muri iyo myaka yo mu ntango , ni co catumye haba iyongerekana ryiza tubona ubu muri Peru , Ivyabona bo muri ico gihugu bakaba bavuye ku 283 mu 1953 , bashika ku Vyabona 83.000 bariho ubu .
Twarongeye kuvyura ubugenzi bwacu , hanyuma duca turanywana .
Ariko ntidukwiye kwigera tureka ngo ugukunda amaronko , ukwisamaza , canke ukubura ugushimishwa bitume tutitegura , tuba abarorerezi gusa , canke ngo tuje turasiba amakoraniro . — Luka 8 : 14 .
Mu vy’ukuri , ibintu bikeyi vyerekeye kahise ka Aradi biriho ubu , turabikuramwo ivyigwa bihambaye .
Ibisigarira vy’amabarabara abo ba Etrusques baciye n’ubu biracariho .
Ariko rero turakwiye kwihatira gushira mu ngiro ivyo Bibiliya ivuga ku bijanye no gutera iteka abandi .
Biragaragara ko ibintu vyabwirizwa guhinduka .
Mugabo igihe bashikije ico cipfuzo mu buryo butaranga ubukerebutsi , birashobora kugabanya ubukomezi bafise bwo kwirwanira mu vy’impwemu .
Ariko none Yehova yakoze iki ?
Muri iyo myaka , abavukanyi benshi vyarabagora cane gushika ahabera amahwaniro .
Antoni : Urakoze .
Sibongili ni umupfakazi w’Umukirisu w’umutinyutsi wo muri Swazilande .
Baranyubaha .
Uwo mugwi mutoyi ni wo uhagarikiye igikorwa co kwamamaza Ubwami kirangurwa kw’isi , ugahagarikira n’itangwa ry’imfungurwa z’ivy’impwemu igihe kigeze .
Izina ry’icubahiro “ papa ” intumwa Petero nta n’iryo yigeze amenya .
None Imana yavyifashemwo gute ku bijanye n’imigambi y’abo bantu b’abagarariji baba i Babeli ?
Ku bw’ivyo rero , ntabwirizwa guhishurira abo bantu barondera kugirira nabi abasavyi b’Imana aho nya batasi bari .
Kumbure Paulo yariko kandi yiyumvira ingene mu rugo habaye biturutse ku vyo Lowisi na Ewunike bakoze .
Abo Nowa yigisha bari baratwawe n’ivyabo be n’ibibahimbara ku buryo bw’uko “ [ batagize ] ico bamenya kugeza ah’umwuzure waziye ubatwara bose ” . ​ — Matayo 24 : 38 , 39 .
Yamara , igihe dushoboye kubakangura mu buryo bw’impwemu ku buryo batahura ubutumwa nyakuri bwo muri Bibiliya , barashobora kwungukira ku Bwami bw’Imana .
Ariko rero , ivyo vyandikano vyari bizimvye , akaba ari co gituma atari bose bashobora kuvyironsa .
Nari umuyobozi aserukira ikompanyi mpuzamakungu imwe mu rwego rw’intara .
Ni ukwiyumvira kutari kwo ukuhe dushaka kwirinda , kandi ni ibibazo ibihe dushobora kwibaza ?
Raba igitabu Annuaire des Témoins de Jéhovah 1992 , urupapuro rwa 95 - 184 .
Naho vyari ukwo , narafashe ingingo yo gukora ivyo nshoboye vyose mu kwamamaza Ubwami .
Avuga ati : “ Igihe umubabaro wo mu ntango umaze kurangira , amaganya uba usigaranye aca asubirirwa n’inkomezi Yehova akuronsa be n’urukundo akugaragariza .
Intumwa Petero ivyo yarabishimitseko mw’ikete ryiwe rigira kabiri .
Abarinzi bari bafise ubuhinga budasanzwe bwo gusambisha .
Ese ukuntu ubwo ari uburyo bwiza bwo gutuma ivyiyumviro vy’Imana vyiyandika mu mizirikanyi no mu mitima yacu !
Dushitse , uwo muryango waramenyekanishije ku mugabo yitwa Heinrich Reiff , rikaba ryari irya mbere ndamubonye .
Yigana ati : “ Gukorera mu mahanga vyatumye nibonera ukuntu Yehova akwegēra mw’ishirahamwe ryiwe abantu bo mu moko yose no mu mico kama yose .
Budakeye na kabiri , twe na dawe twaratanguye kwitaba amakoraniro ya gikirisu .
Iyo nkuru ivuga gusa abagabo bavutse kuri ukwo kumarana inambu y’umubiri uko bitagirwa .
Muri iyo myaka yose , naguma ngendana na vya “ bitabu vya Bibiliya . ”
Ariko rero , ikigabu cose bashinzwe caba ari ikintu gitegerezwa kurangurwa n’umuryango , kandi twaramara amasaha menshi tubafasha gutegura insiguro zabo . ”
Ni ibintu ibihe umuntu ategerezwa kurimbura igihe afata ingingo yuko yoba yohaguma canke yoba yokwimuka igihe hari uruhamo ?
Biboneka ko n’ivy’iyi si mbi bibwirizwa kuvaho .
Imana yipfuriza ako kazoza abantu benshi bashoboka , harimwo mbere n’abo vyagoye mu buzima . ​ — 1 Timoteyo 2 : 3 , 4 .
Kugenderanira n’uwo mwipfuza kuzoreshanya muri kumwe n’abandi bantu babereye birashobora kukurinda
Icizigiro cacu ca kazoza kirajanye n’ibikorwa bihambaye kandi bikwiriye gushimwa bijanye n’umugambi w’ibihe bidahera w’Imana .
Ivyo vyatumye kw’isi haboneka ubukirisu bwononekaye kandi bw’urwigano .
Uwahemukiwe asanga ari wenyene atari avyiteze , ubuzima bwiwe bwahindutse rwose .
Yamara , yaritavye ihwaniro ry’intara maze araronka igitabu Ivyo Bibiliya yigisha .
Ukwo kuntu usanga abapfakare bakunda kuvyifatamwo ni kimwe mu vyerekana igituma benshi muri bo baca babona yuko gusubira kwabirana n’abandi bagore ari wo muti w’irungu baba barimwo , naho baba bahakwa gusanga batanguje ubucuti n’uwundi muntu gihutihuti .
Abatanga banezerewe
Igihe uriko wiga ico kiganiro wongera uzirikana no kuri iki , numenye neza yuko akigoro ako ari ko kose ugira urondera gufasha abameze nk’intama kugira ngo bagaruke mu ruhongore rwa gikirisu atari ak’impfagusa .
Niwiyegereze Imana — “ Mugume musaba , muzohabwa ” 11
Nakare “ Umwami Imana . . . ntigomba ko hagira abahona , arikw igomba ko bose bihana ” .
ABAKURU bamwe b’amadini y’abiyita abakirisu bigisha ugutinya Imana , akenshi babigira bisunze inyigisho idashingiye ku Vyanditswe ivuga yuko ngo Imana ihanira abanyavyaha ibihe vyose mu muriro udahera .
Waba uzorokoka ya “ marushwa ahambaye ” canke uzozurwa , ese ukuntu bizoba bihimbaye kwironkera ‘ ubuzima nyakuri ’ !
Nk’uko vyagenze kuri Yezu , bazuka bafise umubiri w’impwemu . ​ — Soma Yohani 14 : 1 - 3 ; 1 Abakorinto 15 : 42 - 45 .
Uno muvukanyi yaciye ubwo nyene atuma urupapuro rw’ugusaba gusukurira kuri Beteli . ”
Iyo nkuru ivuga amakosa Dawidi yakoze idaca ku ruhande , ni ikimenyamenya c’uko Bibiliya ari Ijambo ry’Imana ryahumetswe .
Ubu Sarah afise abana babiri yivyariye .
Umuntu umwe yahoze ari umuhakanamana yiyemereye ati : “ Ivyaremwe biranjijura ko Imana ishaka yuko abantu babaho bamerewe neza be n’uko rero itazoreka ngo imibabaro ibandanye ibihe bidahera .
Nurabe neza ko inyama zahiye neza , kandi ntiwigere ufungura imfungurwa zononekaye .
Iragi ryanje ryo mu vy’impwemu
Iyo ni yo ncuro ya mbere muri zine ayo majambo aboneka muri Bibiliya , kandi ivyo vyanditswe uko ari bine birashobora kugira ico bikoze kuri kazoza kacu , mbere bikanavuga uko kazomera .
Ivyo bica bidufasha gutahura impamvu abantu vyabananiye gutuma ivyo kw’isi bimera neza .
Ariko hamwe nokwinumira , ivyo noba ndavyirinze , kandi nta muntu n’umwe mw’ishengero azokwigera agira ico amenya ’ .
Kw’ishure sinabitora rwose , kandi uko imyaka yagiye irarengana naratanguye kwiyumvamwo yuko ata co maze imbere y’abandi .
Ico gitabu ca Yesaya , icanditswe n’uwo muhanuzi ubwiwe , kivuga ivyabaye mu kiringo c’imyaka 46 , kuva nko mu 778 B.G.C . gushika mu gihe kinaka c’inyuma yo mu 732 B.G.C .
Habakuki arakuwe amazinda yuko umugororotsi azobandanya kubaho , ariko ko umwansi atazoreka guhanwa .
Ni utwigoro utuhe Abisirayeli benshi bo mu gihe ca kera babwirizwa kugira kugira ngo bitabe imisi mikuru yabera i Yeruzalemu ?
Gikwiye gukomeza ukwizera kwacu yuko Imana ishobora gusubiza bazima abantu amamiliyoni bapfuye yibuka mu bwenge bwayo butagira agahaze . — Yohana 5 : 28 , 29 ; Ivyakozwe 17 : 31 .
Ni co gituma yamara umwanya yigisha abana biwe ivyerekeye Yehova Imana n’amategeko yiwe .
Intumwa Paulo ntiyariko avuga ibijanye n’abo Mesiya akomokako .
Kubera ko nakunda icigwa c’ivy’imibumbe n’ikirere , nahisemwo gukora icuma rugagamisha bita telesikope yo mu bwoko bw’izikoresha ahanini ikiyo .
( b ) Ukwo gusigwa iceyi kwoba kugabanya agahimbare kabo ?
Nkako , dutegerezwa gufata umwanya wo kurishirako umutima canke kurisoma n’ijwi ritoyi , ni ukuvuga kurizirikanako .
Abo baganga babiri mu vy’ukubaga , barongowe mu buryo burimwo ubuhanga n’umuganga mu vy’ukubaga ava mu Bwongereza afise umutima ukunze wo gukorana natwe , bararanguye igikorwa kigoye bimwe bidasanzwe c’ukubaga umwana w’Icabona umutsi wiwe w’umutima utwara amaraso mu mubiri vyasaba ko ugira ico uhinduweko .
Raba kandi ikiganiro kivuga ngo “ Nuremeshe ababuze , nk’uko Yezu yabigize ” , mu Munara w’Inderetsi wo ku wa 1 Munyonyo 2010 .
Gusoma no kuganira kuri ivyo vyanditswe vyo muri Bibiliya , vyoshobora kuba bihagije .
Kubera ari “ Umucamanza w’isi yose ” agororotse , yari yarabonye ibiri mu mitima y’abo bantu bose , aramenya ukuntu ububi bwabo n’ukwononekara kwabo vyari vyaramaze gutsimbatara .
Ntibadohotse , n’igihe nyene bari muri Siberiya . . . .
Ariko none ayo majambo nkwegavyiyumviro yoba asobanuye iki , kandi ni kuki twovuga ko atanga iremezo ry’uko twebwe ubu tugira agahimbare , umwishimiro n’umwete vyongerekanye ?
Kugira “ ivyiyumviro vya Kristo birimwo ibiki , ” kandi ni akigoro akahe ivyo bisaba ?
Sullivan ( batazira Bud ) hamwe na Lyman Swingle , bose bakaba barigeze kuba mu bagize Inama Nyobozi .
Arongerako , ati “ Ico utazi ni uko ata n’umunezero na mukeyi w’ukurya n’ukunywa n’ukuryama binyongerereza ubu , uruta uwo nari mfise nkiri umukene .
Ivyo vyose bikorwa kubera iki ?
29 “ Ndacariho ”
Ibicapo vy’amadini bikunze kwerekana Yezu ari uruyoya , umuntu agoyagoya kandi adafungura bihagije , canke bikamwerekana ari umuntu yibabaza , yemera ata kuryogora ikintu ico ari co cose kimushikiye .
Abahiganwa babura agashimwe mu gihe gusa batirutse bakurikiza amategeko canke mu gihe batarangije iryo siganwa .
Merodaki - baladani
Bwari bwo bwa mbere nshikirwa n’ikintu gisaba ko ngira ivyo mpevye kugira nkurikire Kristu , nkaba nari mfise imyaka 16 .
Dusoma duti : “ Hahirwa umuntu atagendera mu nama z’ababi , adahagarara mu nzira y’abanyavyaha , aticarana n’abacokoranyi .
Kubera agomba ko “ abantu bose bakizwa bagashika ku kumenya ivy’ukuri , ” yaritwararitse ivy’uko Ijambo ryiwe rishikira ubwoko muntu bwose .
Mu bihe bimwebimwe , ingorane zacu Shetani azigiramwo uruhara gute , yamara ni icizigiro ikihe dushobora kugira ?
( b ) Abakirisu bakiri bato bahimbara gute Yehova be n’abakirisu bagenzi babo ?
Muri Amosi ikigabane ca 9 hahishura iki ku vyerekeye ikigongwe c’Imana ?
Umwe mu Vyabona b’impunzi yavuze ko iryo teraniro ryari ikimenyamenya c’ubumwe n’urukundo birangwa mu Vyabona vya Yehova mw’isi yuzuye amacakubiri .
Abahitamwo kuba aba Yehova bibaviramwo iki ?
Yaranavuze ati : “ Ndazi yuko ivyo wize ku vyerekeye Yehova ari vyo vyatumye uba umukenyezi abushitse , bitavuye ku kuntu warezwe . ”
Birumvikana , hakwiye kugirwa akigoro kugira umuntu atanguze urwigo mu gitabu Ubumenyi Bujana mu Buzima Budashira .
Uko biri kwose , vyarahumuriza kumenya yuko abantu batazokwigera basubira gupfira mu ntambara .
Haraheze imyaka hafi 2.000 Yezu Kristu avuze ibijanye n’icago cashikiye abantu 18 bapfuye igihe umunara wabagwako .
Si twe tuzobona isi iravuyeko ubukozi bw’ikibi , iterabwoba n’ibiturire !
Ubuto ni igihe co kugira amahitamwo ahambaye .
None ukwo kwoba ari ukwifata ruto ?
Umugabo n’umugore ba mbere bari bafise umubiri utagira akanenge be n’ubushobozi bwo kwihitiramwo .
Yeruzalemu Ikwiranye n’Izina Ryayo
Kubatizwa “ mw’izina rya Data wa twese ” bisobanura iki ?
Asa yari umwami agira gatatu yatwaye Yuda inyuma y’aho ya miryango cumi yari igize ubwami bwo mu Buraruko bwa Isirayeli itandukaniye na Yuda .
Iyo migera irateba igashika mu gitigu c’uwo muntu igaca igwirirana .
Iyo mvugo irerekana ko naho tutisuka mu vy’abandi , dukwiye kurondera kumenya no gutahura abavukanyi bacu be n’ivyo bakeneye .
Ni gute Yehova yacunguye , akarongora akongera agakingira abasavyi biwe bo mu bihe vya kera ?
Mu bihugu bimwebimwe , abantu babwirizwa kurindirizwa ku rutonde rw’abagirirwa inyigo za Bibiliya .
3 , 4 . ( a ) Dutegerezwa gukora iki kugira ducike abakuze mu buryo bw’impwemu ?
Yanditse ati : “ Nuko dukurikire ivy’amahoro n’ivyo gukomezanya : ntimusenyure igikorwa c’Imana kubg’ivyo kurya .
Muri ibi biganiro bibiri , turabona ingene Kristu yigishije abayoboke biwe kwunga ubumwe no kurengera ivyoshobora kubacanishamwo .
Adondorwa ko ari we “ bushobozi bg’Imana . . . n’ubgenge bg’Imana ” , ari bwo bukerebutsi bwayo .
Woca ubona ko uwayihinguye yayikoze “ itagira akanenge ” ariko ko hari uwundi muntu canke ikindi kintu vyawononye .
Ni ibiki bishobora gushika igihe abivugisha ko bakorera Imana bashize ivy’amaronko mu kibanza ca mbere mu buzima ?
Mbere no mu turere aho akazi keza kagoye kuronka , usanga abakozi b’inzirabugunge , bafise ubuhanga be n’abanyamwete bibagendera neza kuruta abandi .
Icerekana ko ico kintu cari ikidasanzwe , ni abana bavuye muri ukwo guhuza ibitsina .
Ku muntu w’agatima kabi , nta kintu gisa n’ikigororotse , n’igihe mbere ku wubona ibintu mu buryo bwiza ubuzima bwoba ari bwiza .
Ikizoba gifise umutwe uvuga ngo “ Niwiyegereze Yehova ” , kizokwerekana ivyigwa imirongo minaka yo muri Bibiliya ishobora kutwigisha ku vyerekeye Yehova .
Isandugu ryabikwamwo amagufa , amajambo aharangatuwe , be n’isenga riboneka inyuma : Tubikesha Israel Antiquities Authority
Inyuma y’aho , baradutumira kwivunira umusase hamwe n’umuryango w’Abamishi ugizwe n’abantu 12 .
Ni kubera iki abo bagabo bishwe ?
Ntibitangaje kuba umwanditsi w’amazaburi avuga ko uwo mugeni ‘ aninahaye rwose ’ !
Bitegerezwa kuba vyaramubabaje cane igihe umuhungu wiwe Amoni yahitamwo kudakurikira akarorero kiwe keza .
Bibiliya y’ikirundi ihindura iryo jambo ngo “ umurimyi ” w’ibiti vy’imisukomora , aho kuvuga ngo “ umutobozi ” w’insukoni z’ibiti vy’imisukomora .
Nta gukeka ko ata kindi kintu kikwereka ko ufise agaciro coza kiguhimbara kuruta ico .
( b ) n ’ ‘ ubuzima bwacu bwose ’ ?
IVYIZA NAHAKUYE : Ubu ndumva ko nahumanutse , ndi muzima , kandi ko mbayeho koko .
Nimba asa n’uwubabaye , biroroshe gutahura igituma .
Nuhitemwo ubuzima !
Umwete ni “ ukwumva ushashaye cane canke ushimishijwe bimwe bikomeye no gukurikirana ikintu kinaka . ”
Sinipfuza ko ibikorwa nkora inyuma y’akazi vyotuma ntakora igikorwa canje neza ng’aha , mugabo ndipfuza kuronka umwanya wiyongereye wo gufasha abantu .
Nimba uri umuvyeyi , woba utegekanya umwanya wo kwigisha abana bawe ibijanye na Data wa twese munyarukundo wo mw’ijuru ?
Nk’uko ikiganiro gikurikira kivyerekana , ukugamburuka nk’ukwo kuragaragaza inyifato dufise kuri Yezu , ari we shebuja wa ‘ wa mushumba . ’
Ushobora gute gutahura Bibiliya ?
Ni kubera iki twokurikira Yezu ?
Abahakanyi barashobora kutubera akandi kaga mu vy’impwemu .
Emwe , kwemera Yezu kandi ukabatizwa mw’izina ryiwe bisigura kwemera uruhara arangura mu bijanye n’ubucuti dufitaniye n’Umuremyi !
Abantu baremwe mw’ishusho y’Imana .
Vyongeye , biratwigisha kubona ingene Imana yishura amasengesho yacu , bigatuma turushiriza kuyiyegereza .
Bemera kandi ko yikwije ata kintu na kimwe abantu bashobora kuyikorera , kandi ko itaba mu nsengero zubatswe n’amaboko y’abantu .
Woshobora gutuma abantu bagira uruhara mu kiyago ukoresheje mwene ubwo buryo .
Nk’akarorero , rimbura ivya Hezekiya uw’ingeso nziza .
Dukwiye guca dukora duhuza n’ubuyobozi Yehova atanga naho vyoba bigoye kubwemera .
Nk’uko incabwenge imwe ibivuga , Yezu yaba yavuze mu giheburayo kimenyerewe canke mu giharameya , ijambo yakoresheje kuri “ Data ” ni ijambo rifitaniye isano cane n’arya majambo aranga igishika y’umwana , ari ko ‘ kajambo k’umwana ’ .
Aratahura neza kuruta iryungane riri mw’Isengesho ry’Umukama dusoma duti : “ Ivyo ushaka bigirwe kw’isi nko mw’ijuru . ”
Canke nk’uko Bibiliya Yera ibivuga , “ uhereye ibihe bidashira , gushitsa ibihe bidashira , ni wewe Mana . ”
Mu nyuma , yarasubiye i Yeruzalemu .
Bibiliya yoyo iduhimiriza gukunda ubumenyi no kwironsa ubukerebutsi n’ugutahura .
Igitabu kimwe ( Wrecks , Wreckers and Rescuers ) kivuga yuko hariho abantu wasanga bashinga mwene ivyo bitara kugira bazimize amato ngo aze ku nkengera ziriko ibitandara vy’amabuye , maze asabe bisahurire .
Ntibikenewe ko akantu kose mugaharirako n’imitsi ikaranda .
Imbere y’aho sinari bwigere nicarana mu mahoro n’umuzungu , ikitovugwa co ni ugusangira na we akajumbu turi mu rugo iwe .
No muri ubwo Bwami bwo mw’ijuru ni ukwo nyene .
Aho hari umupfasoni yakunda kumpa utwo ntamira .
Turakura icigwa kuri ca gitangaro Yezu yakora igihe yasaba Petero na Andereya ngo bamukurikire .
Raba n’ikiganiro kivuga ngo “ Indero yaroye he ? ”
Mu gihe ishavu rirekeranywe , naho ryoba ritewe n’impamvu yumvikana , ryoshobora gutuma duhuruduka kandi Yehova ivyo ni twe yobibaza . — Itanguriro 34 : 1 - 31 ; 49 : 5 - 7 ; Guharūra 12 : 3 ; 20 : 10 - 12 ; Zaburi 106 : 32 , 33 .
Imbere ya vyose , burafise igisata kijejwe ubuyobozi gifise ububasha kandi gikora neza kirongowe na wa Mwami yimitswe ari we Yezu Kirisitu .
Insobanuro y’amajambo yariko arasoma , yarakoze ikintu gikomeye kuri we ku buryo ubuzima bwiwe bwaciye buhinduka kuva ico gihe .
Ivyabona vya Yehova barahimbarwa cane no gufasha abandi kwungukira ku buyobozi bwo mu Vyanditswe .
Abari baciriwe urwo gupfa mu nyuma barabahinduriye babacira gupfungwa ubuzima bwose .
Gutahura Bibiliya birahimbara umutima wacu
Yarasohoye kandi integuro zitatu z’icongereza z’igikunze kwitwa Isezerano rishasha , zikaba zarimwo n’igisomwa c’ikilatini kugira ngo abakuru b’idini bacifashishe mu kwiga .
Ese ukuntu vyokworoha kureka ibintu nk’ivyo bikaniga inyungu zo mu vy’impwemu mu buzima bwabo ! — Matayo 13 : 22 .
“ Uruzabibu rwa Vino [ Ibira ] ”
Birashoboka ko buba butandukanye n’ubwo umuntu aba amenyereye .
Nk’akarorero , nta gihe kirekire cane kirahaca abahinga mu vya siyansi bubuye ibimenyamenya vyerekana ko isi n’ijuru vyagize intango .
Ariko rero , imirongo ikikije ayo majambo yavuze , hamwe n’imihango itangwa n’Ijambo ry’Imana , birerekana ko yashaka kuvuga ko aboro bokwamyeho magingo uru runkwekwe rw’ibintu rukiriho .
Abahinga barigeze gutandukanya izo fi n’udukoko two muri ubwo bwoko , duca turazimangana mu masaha 24 gusa .
Mugabo kuri Eliya we , kari gafise ikintu kinini gasobanura .
Uruhara urukundo rurangura
Ico conyene cari gikwiye kugira ngo umwana wiwe wo mu vy’impwemu Gayo amenye ko ryanditswe n’intumwa Yohani .
Kugira ngo sebibondo aronke icomufasha gutsinda izo ntambamyi zivuzwe aho haruguru , yotumbera muri Bibiliya .
Ni igiki abantu bibuka kuri Yezu ?
( b ) Ni ibibazo ibihe tuja gusuzuma muri iki kiganiro ?
Kubera ko cari casamye umubano wiwe .
Umwami Yehoshafati “ [ yara ] rondeye Yehova n’umutima wiwe wose . ” ​ — 2 Ngo .
ni ukumenyerezwa ukuhe abamamaji b’Ubwami baronse ?
Imitima yabo yaciye itangura kururumba kubera yariko ‘ abasigurira ’ Ivyanditswe . ​ — Luka 24 : 32 .
( b ) Ni abantu abahe woba uzi n’ubu bakiri abanyamwete muri ico gikorwa ?
Mw’ijambo ryashikirijwe icese bise Itangazo ry’i Rustenburg , indongozi z’amadini ziyemereye ziti : “ Bamwebamwe muri twebwe barakoresheje cane Bibiliya ukutari kwo kugira ngo bashigikire intwaro karyanishamiryango , bituma benshi bemera yuko ishigikiwe n’Imana . ”
Uwo Munyashunemukazi yoba yizera ko Elisa yoshobora kugirira agahungu kiwe nk’ukwo nyene ?
Incahagati y’imyaka y’amavuka : 33,5
Yosuwa yari azi yuko Yehova yashikije imihango yatanze .
Mu nyuma , nyina wiwe yaciye yubakana na Winton Fraser , maze bavyarana umuhungu bise Sidney .
Yehova kandi yari azi yuko Yeruzalemu n’Ubuyuda vyari mu misi yavyo ya nyuma , kandi ntiyipfuza ko Baruki ata umurongo muri ico gihe kigoye .
Ivyo tuzi ni ‘ udusunwa gusa tw’inzira z’Imana , ’ kandi “ ivyo twumva ku biyerekeye [ ni ] utwongoshwe gusa . ”
Ukwizigira Imana kwa Dawidi kwagumye gukomeye , maze amaherezo uwo mwami arakira indwara yiwe .
Barabandanije kumenyekanisha ivy’iryo hwaniro gushika ku mugoroba buca iryo hwaniro riba .
Igihe yatangura gukorera Yehova Imana , umuryango wiwe waramurwanije maze biba ngombwa ko aja kuba ahandi .
Intumwa Paulo yarasubiyemwo inkuru y’ivyashikiye Abisirayeli i Shitimu kugira ngo ibere akarorero ko kuburira abakirisu b’i Korinto ha kera , igisagara cari kizwi cane ko kibayeho mu buryo buranga ubushegabo .
Aho guhagarikwa umutima n’umuhero w’isi , bahavuye bizigira badakeka yuko Imana igiye gukuraho ingorane zisinzikaje abantu maze itume isi isubira kuba iparadizo .
Ariko rero naho turi abanyagasembwa , turashobora guhuza ijwi ryacu ryo mu mutima n’ingingo ngenderwako z’Imana .
Yama anezerwa atubonye , kandi twaramaze umwanya tuganira na we kuri Bibiliya .
Haffner , akaba atanga inyigisho zijanye n’amagara , mu gitabu yanditse kivuga ibijanye n’ukuyaga n’abana ivy’igitsina ( Beyond the Big Talk ) , avuga ati : “ Abavyeyi benshi bambwiye yuko baguriye umwana wabo ataragera mu buyabaga igitabu kivuga ivyerekeye igitsina canke amahinduka aba ku mwana acinjira mu buyabaga , bagisiga mu cumba ciwe , bica biherera aho . ”
Harry akiri muto ntiyatahura na gato igituma Imana y’urukundo ireka abantu bagashikirwa n’imibabaro .
Rebeka arica imigambi ya Esau mu guhimiriza Yakobo guhunga gushika ishavu rya mwenewabo riheze .
Aho harimwo amazina y’abakirisu barobanuwe bakiri kw’isi bafise icizigiro co kuzoba mw’ijuru .
Imbere yuko Yezu arungika abigishwa biwe kwamamaza , yarabakoranirije hamwe maze arabaha ubuyobozi bw’ido n’ido .
Ni kubera iki ico kibazo utokibwira Yehova Imana mw’isengesho ?
Bibiliya idukebura mu buryo buranga ubukerebutsi iti : “ Ntimuzimire : kubana n’ababi kwonona ingeso nziza ” .
Umwigisha Ahambaye ari we Yehova aratuma tuba abashoboye ubusuku .
Kubera yuko ivy’isi birushiriza kwunyuka , ese ukuntu bisubiriza umutima mu nda kumenya yuko vuba Yehova agiye kuzana isi nshasha yiwe igororotse !
Gaciye kavuga n’ijwi ritoyi ririmwo ukwiyagiriza gati : “ Mbabarira mawe , nibagiye . ”
Abo bagabo bari bararwanye muri ya Ntambara ya kabiri y’isi yose kandi biyumvira ukutari kwo Ivyabona kubera yuko batagize aho bahengamiye muri iyo ntambara .
Hari abubakanye bo mu gice ca Ositaraliya yo mu Burengero giherereye mu Bumanuko bari barakukurutse , ari bo Arthur Willis n’umukenyezi wiwe Mary , bahora baza kumfasha mu kiringo c’amezi atatu akurikirana yo mu kiringo c’akabeho gakegake .
Dawidi , uwari umuntu ahimbara umutima w’Imana , yoba yarafata abanyagano biwe bunyamaswa , nk’uko bamwe babivuga bafatiye kuri 2 Samweli 12 : 31 no ku 1 Ngoma 20 : 3 ?
Yezu yariko yereka Mariya yuko Umwana w’Imana yarobanuwe ategerezwa gukurikiza ubuyobozi buvuye kuri Se wiwe wo mw’ijuru .
Ariko uwo murabi yiyemerera ko “ naho abo mw’idini ry’Abayuda bemera ijuru , igitabu cabo Torah ata vyinshi kivuga ku bijanye n’ijuru . ”
Ezira yarazirikanye ku buhanuzi bwa Yeremiya maze yerekana ko iyo “ myaka mirongwirindwi ” yarangiye igihe ‘ Uhoraho yakangura umutima wa Kuro umwami w’i Buperesi ngo ashinge ko babitangaza . ’
Ikindi gihe na ho , nategerezwa gukurwamwo ikivyimba kinini cari ku gasaho gahingura urûzirûzi rubungabunga imbuto z’umugabo kugira zigume ari nzima .
Nimba imikazo yo mu buzima iriko iragutwara urugero runaka rw’umunezero , ni kuki utoraba nimba ushobora kuremururwa mu kugira ivyo uhindura ?
Ayo majambo yo muri Yosuwa 1 : 9 ni yo yatowe ngo abe icanditswe c’umwaka wa 2013 .
Ariko rero , ikwiye kuba ihinduwe neza kandi itagiramwo amakosa .
Imiryango itari mike irasomera hamwe igihimba kinaka co muri Bibiliya .
Aho kubategeka nk’ibirobǒti , Yehova yarabigishije akoresheje iteka .
Bibiliya ivuga iti : “ Muri [ Yezu ] , turaronka ukubohorwa biciye ku ncungu tubihawe n’amaraso y’uwo , egome , ukubabarirwa amakosa yacu . ” ​ — Ef .
Bukeye , umugore wiwe n’abakobwa biwe baca batangura kugosora bongera bayungurura ( 10 ) .
Canke wokwiyumvira ubuhanga ushobora kuzotsimbataza mu bijanye n’utugenegene , mu vy’ubwubatsi , mu vy’umuziki , kibure mu bindi bintu udashobora kuronkera umwanya mu buzima bwo muri iki gihe usanga budaha umuntu n’akanya ko guhema .
Birashoboka kandi yuko yazirikanye ku majambo Yehova yabwiye ya nzoka mw’itongo ry’i Edeni : “ Nzoshira inyankane hagati yawe n’uyu mugore , no hagati y’uru [ but ] o rwawe n’urwiwe : ruzogukomeretsa umutwe , nawe uzorukomeretsa igitsintsiri . ” .
Bosiko : Mu bisanzwe , hari abantu bigeze kuvuga ko Umwami Dawidi atabayeho .
Igikowa co kwamamaza carabandanije kuvamwo ivyiza naho abakuru b’amadini bama baturwanije .
Ubusuma bwa Akani ntibwari agacumuro gatoya . Bwakweze akarambaraye
IVYO YACIYEMWO : UMUCURARANZI W’UMUZIKI WITWA HEAVY METAL
Ni uburyo ubuhe bwo kuyihanganira mwasanze buvamwo ivyiza kuruta ? [ Igicapo ku rup . 18 ] [ Ifoto ku rup . 20 ]
Ariko rero , turakeneye kubanza kumenya ibintu bituma turuha .
Mu gihe intambwe ya kabiri inaniwe gutunganya iyo ngorane , ni ho rero abacungezi b’ishengero bajamwo nya kujamwo mu ntambwe igira gatatu .
Kimwe mu vyo Patricia yize ni uko Imana ifise izina , na ryo akaba ari Yehova .
Naho azi amakosa yacu , Bibiliya ivuga ku bimwerekeye iti : “ Uhoraho , wokwama wibuka ibigabitanyo , Bgirukiro , ni nde yohava akazohagarara adatsinzwe ? ” .
Igihe twaba dushitse ku ngazi z’inzu yinaka , twarakura ayo mabotine maze tugakunkumurira hasi ivyo bibarafu .
Kandi igihe ivyo bintu bitumye tuba abibona , bironona ubucuti tuba dufitaniye na we .
Uwo muvukanyikazi yari azi neza yuko nya mucungezi aza kuza , ari na co gituma yari akirindiriye .
Ariko rero , imvo nyezina yatumye bapfa ni uko bosheje ku “ muriro urahuwe ahandi , uwo [ Yehova ] atabageze ” .
None muri ico gihe nyene , abaherezi bo muri Isirayeli bariko bamara iki ?
Ukubumbwa n’ivyo mfise bindonsa n’iyindi mihezagiro
Nuhuze ivyabashikiye n’ibintu binaka biriko biragushikira mu buzima .
Igihe uwo murwayi wiwe yari muri koma yagarura ubwenge , yararavye mu maso ha Jonathan maze aca avuga amajambo yo kumutuka yerekana ukuntu yamye agaya Abanyakoreya .
Mugabo bari bakeneye kandi impanuro n’ubuyobozi bibafasha kubona yuko ingendo bari barahisemwo yari yo nziza , kandi ko ugucumukura n’ukwihangana bari baragize bitari ivy’ubusa .
Igihe ivyo bifungurwa vyarigatwa n’umuriro ku gitangaro uwo mumarayika abikojejeko inkoni yiwe , Gideyoni yaciye atahura ko nya mumarayika yaserukira Yehova koko .
Gushika uyu musi igituma gakora hamwe n’imigambi yako nta wubizi .
Abakirisu baratera iteka kandi bakubaha abavyeyi babo , ariko ntibagira uruhara mu manza zishingiye ku vyo kwiyegereza ba sekuruza bapfuye kugira ngo babakingire canke ku vyo kurondera gutoneshwa n’ibimana vy’ibinyarugo . ​ — 1 / 12 , urupapuro rwa 20 - 23 .
Uwo murongo wo muri Bibiliya werekana yuko sebibondo na inabibondo bompi bafise uburenganzira bwo gukoresha ubukuru bafise ku bana babo .
• Kuba dufise ijwi ryo mu mutima binyuranye gute n’iciyumviro c’uko twabayeho biciye kw’ihindagurika ?
Nipfuza ko batahura ukuntu kwirengagiza ingingo ngenderwako z’Imana vyangizeko ingaruka mbi .
Ico gihe Stephany yari afise imyaka 19 . Yarahamenyaniye n’umusore w’Umunyabeteli yitwa Paul Norton .
Nukate urupapuro rukurikira maze uruzinge .
Abisirayeli barababaje Yehova mu gukurikirana ingendo y’ubugarariji mu bugaragwa .
Mu yindi mvugo uko ubona ibintu kurahambaye cane !
Ivyo Herodote yanditse ni ivy’ukuri ku rugero rungana iki ?
Impanuro Yehova atanga zoba zaragufashije kwirinda ingorane ?
Muri ubwo buryo , abantu b’abagororotsi bazokizwa , basubizwe ku kutagira agasembwa . — Yohana 3 : 17 .
Ibintu vyodufasha gufata ingingo nziza
Avuga ati : “ Mu ntango , naragize ingorane zo kwiga ururimi rwaho , kumenyera ikirere caho , kurwara malariya , amibe be n’izindi nzoka zo mu nda .
Ijambo ry’Imana rivuga yuko twohungira mw’izina rya Yehova .
Mbega ukuntu ari icigwa gikomeye ku bantu ba Yehova muri iki gihe !
Bikunda ahantu hari akazuba , hatari umuyaga mwinshi kandi hasusurutse , nk’iruhande y’uruhome .
Ku bw’ivyo , nimuze turabe neza yuko ivu ry’umutima wacu w’ikigereranyo ritigera riguma , riba urutare canke rirengerwa n’amahwa , ariko rigume ryoroshe kandi ari ryinshi .
None ni ivyigwa bihambaye ibihe iyo mvugo ngereranyo itwigisha ?
Kubera yuko Yehova yaraganye yuko azohumanura isi mu kuyikuramwo abo bose bariko bayitosekaza bongera bayisakambura .
Naho ari ukwo , hariho imvo zumvikana zotuma tugira icizigiro .
Igihe ducitse intege canke dufise intuntu , turipfuza kwiyegereza umuntu ashobora gutahura ukuntu ivyacu vyifashe akongera akifatanya natwe mu mubabaro .
Uko ivyabo vyifashe be n’ububangukirwe bafise usanga bitandukanye .
Ayandi mabarabara yaca i Roma ni iryitwa Via Salaria be n’iryitwa Via Flaminia , ayo yompi akaba yaja amaja mu Buseruko agenda agana ku Kiyaga Adiriya , ivyo bigatuma umuntu ashobora kuja mu karere ka Balkans be no mu karere k’Uruzi Rhin be n’ak’Uruzi Danube .
1 ku 32.711
Uko turushiriza kwiga ivyerekeye Yehova kandi tukibonera ukuntu aduhezagira , ni ko ubugenzi dufitaniye na we burushiriza gukomera .
Nta mvo n’imwe ikomeye ihari yotuma twemera ko mu kinjana ca kane habaye umugambi mu kinyegero wo guhindura canke gukuraho igice na kimwe co mu Vyanditswe vyahumetswe n’Imana .
10 : 10 ; Heb .
None ishirahamwe rya Yehova ryabona gute uwo mugore yaba ukwa wenyene ?
Vyongeye , Bibiliya ivuga ko ubuzima budahera ari ingabirano , atari igihano .
We n’umuryango wiwe ni bamwe mu bantu b’imvukira bo mu bwoko bw’Abamapuce .
“ Mu gihe ca Amurafeli umwami w’i Shinari , na Ariyoki umwami w’i Elasari , na Kedolawoma umwami w’i Elamu , * na Tidali umwami w’i Goyimu , abo bami bā [ ra ] teye . ”
Umugambi afise ni uwo gutuma umuryango w’abantu bagamburuka usubira kuronka ubuzima mw’Iparadizo .
Igitabu c’Ivyahishuwe kiravuga “ isinzi rinini ” ry’abazorokoka iyo ntambara .
Biroroshe ko dufata minenerwe wa muziki udufasha kuririmba igihe turi ku materaniro adasanzwe y’umusi umwe , ku materaniro y’umuzunguruko , no ku mahwaniro y’intara .
( a ) Paulo yashimitse ku kibazo nyamukuru ikihe ?
Mu Vyahishuriwe 16 : 15 harerekana ko hariho isano hagati ya Harumagedoni n’ukuza kwa Yezu nk’igisuma .
“ Vuga , kuko umusavyi wawe ariko arumviriza ”
José avuga ati : “ Inyifato abandi bakurambere baciye bagira yarantangaje .
Kubera yuko ukwisigura akenshi usanga gukoreshwa muri ubwo buryo , abantu ntibahuta barakwemera .
Nta mazinda , twebwe twize ivyerekeye Ubwami bw’Imana biciye ku twigoro twabo , turakenguruka yuko bihanganye mu gushitsa ibanga bashinzwe na Yezu rigira riti : “ Nuko ni mugende , muhindure [ abantu bo mu ] mahanga yose abigishwa , . . . mubigishe kwitondera ivyo nabageze vyose . ”
1 , 2 . ( a ) Ni ibintu ibihe vyabaye mu kinjana c’icumi B.G.C . vyagerageje ukudahemuka kw’abasavyi b’Imana ?
Ni we Antikristo , ahakana Data wa twese n’Umwana ” . ​ — 1 Yohana 2 : 22 .
Urukundo wari ufitiye ukuri ubwa mbere rwari ruhambaye , mugabo uko igihe cagiye kirarengana , vyarabaye ngombwa ko ugira urukundo rugera ibwina kugira ngo wihanganire izindi ngorane zagiye ziragerageza ukwizera kwawe .
Mu kwerekeza kw’ibanga uwumva ubwo butumire afise ryo kuvuga ati : “ Ingo ! ” , Umunara w’Inderetsi ( mu congereza ) wo ku wa 15 Myandagaro 1934 , ku rupapuro rwa 249 wagize uti : “ Abagize umugwi wa Yonadabu bategerezwa kwifatanya n’abagize umugwi wa Yehu w’ikigereranyo , ni ukuvuga abarobanuwe , bakaja kwamamaza ubutumwa bw’ubwami , naho ari ivyabona vya Yehova batarobanuwe . ”
Ikindi kintu ca nyuma umuntu akwiye kurimbura , yamara na co nyene kikaba gihambaye , ni ukuntu abantu bo mu kibano babona amahitamwo aba yagize .
Ivyo “ binyankomezi vy’impwemu vy’ibibisha ” si uburyo gusa abantu bapfa kwiyumvira ikibi , ahubwo ni ibiremwa vy’impwemu bikomeye kandi vy’ibibisha .
Gusoma Bibiliya no kuzirikana ku vyo dusoma birashobora kudushwirura ko ivyo Imana yasezeranye bizoranguka .
Vyongeye , nta gukeka ko Nowa yabwira abantu ikintu kimwe rudende cotumye barokoka , akabasubiriramwo ivyo Imana yamutegetse iti : “ Uze winjir [ e ] mu bwato . ”
Ikoraniro rigirwa buri mwaka , 15 / 6
Muri The New Testament and Psalms in Zulu ( Isezerano Risha na Zaburi mu Kizulu ) [ integuro yo mu 1986 ] , izina ry’icubahiro ngo Imana ( uNkulunkulu ) ryakoreshejwe inkǎbakabanywe n’izina rya bwite ( uMvelinqangi ) , iryo Abazulu batahura ko rivuga ‘ sekuru mukuru asengwa biciye ku basekuru ba kimuntu . ’
Nimba urinywa igihe uriko urafungura canke ugiheza gufungura , nuhebe ako kamenyero .
Amahoteli yararonkeje uburaro n’imfungurwa abari baje bavuye mu bindi bihugu , mugabo haca haraza n’abandi bantu ibihumbi batari bitezwe .
Yezu Kristu yabwiye abayoboke biwe ati : “ Utegerezwa gukunda Yehova Imana yawe n’umutima wawe wose n’ubuzima bwawe bwose n’umuzirikanyi wawe wose n’inkomezi zawe zose . ”
Umuposolo Paulo abwirizwa kuba yǐyumvira ico gishikiragihe hamwe yatanga iyi nkeburo : “ Ntimwibagire kugirira neza abashitsi : kuko bamwe bāgize bartyo bāhaye indāro abamarayika batabizi . ”
Naciye mfata ingingo yo gusenga Imana ivugwa muri Bibiliya .
Birashoboka rero ko Paulo yariko yerekeza kuri iyo nkuru iri mu Guharūra 16 : 5 , 23 - 27 igihe yandika ati : “ Umuntu wese avuga izina rya Yehova avavanure n’ibitagororotse . ”
Ubugeni Yezu Yatashe
Baremera icese ubusegaba bwa Yehova , bakagamburukira Kirisitu ko ari we Mwami wabo akaba n’Umucunguzi wabo , kandi mu buzima bwabo bakorohera igikorwa c’impwemu y’Imana , ari yo nguvu yayo ikora .
( a ) Kumenya ijwi rya Yehova birimwo n’iki ?
Abakirisu b’inkerebutsi bakoresha ububasha bw’ururimi mu guhumuriza abadendebuwe n’umubabaro no kwirura ababuze .
IGIPFUKISHO : Tuyikesha ROE / Anglo - Australian Observatory , ifoto yafashwe na David Malin
Ivyo bisigura yuko ukeneye kumarana umwanya na bo , na munini mbere , atari ukuza uramarana na bo akanya gatogato gusa .
Mu buryo butari buke butangaje , amazi yo mu biyaga yateguriwe kubungabunga ubuzima .
Igikorwa yakora nticabuze kubonwa n’abategetsi barwanya Ivyabona vya Yehova .
Mugabo Yehova araduha icizigiro ciza igitangaza .
Ni ingorane iyihe yashitse mu kinjana ca mbere ?
Yaraha abayoboke biwe ubuyobozi butomoye akongera akabakosora igihe bikenewe .
Yongeyeko ati : “ Uwushoboye kuvyemera navyemere . ”
Ni co gituma yaciye aja i Hamburg mu Budagi kwiga igiheburayo n’ikigiriki .
BELIZE
• Mu bihe vy’umubabaro , dushobora gute kuronkera agahimbare mu gukora ivyo Imana igomba ?
Kwirirwa uracumukura uriha amadeni y’igihe kirekire kandi asaba inyungu nini ku bintu udashobora kwironsa koko , ni ubwoko bw’ubuja buteye umubabaro ! ​ — Imigani 22 : 7 .
Kuba intahemuka ku Mana bituma ubuzima bugira intumbero
URUPAPURO 30
Ntitwama dufise amakuru yose
Mikaheli rero yaririnze gukora ivyo adafitiye ububasha , mbere n’igihe yari asomborokejwe .
Abarigize barimbuye bongera baragurisha iyo micungwe , bituma wa mugabo n’umugore baronka udufaranga bongera baragira amahoro yo mu mutima .
Nimba wipfuza kuba umukurambere mugabo hakaba haciye imyaka utaramuba , nubandanye kwizigira Yehova .
▪ Noshobora gute kuvyifatamwo neza mu ngorane z’ivy’ubutunzi ?
Urwo rutonde rwose uko rungana ruzosamburwa gushika ku mushinge .
( a ) Ni ibiki bikwiye gutuma abakurambere bamenyereza abandi ?
Ubuhuni ni bwo buteye ako kaga .
Ukwihangana gucira inzira ubutungane
• Ni mu buryo bumwebumwe ubuhe dushobora kuryohora ijwi rituvugiramwo ?
• Twokora iki kugira ngo turushirize kubona ko ibintu vyihutirwa ?
Mw ’ ​ Itanguriro 24 : 28 - 67 harigana igice gisigaye ca ya nkuru y’umusuku wa Aburahamu , umwe yavugwa mu kiganiro c’imbere y’iki .
Inyuma y’urupfu rwa Yezu , abigishwa baragamburuka n’umutima rugabo itegeko yabahaye ryo kumushingira intahe “ i Yerusalemu , n’i Yudaya hose , n’i Samariya , no gushitsa ku mpera y’isi ” .
Yohani yandika ati : “ Ni hagira umuntu akora icaha , dufise Umwitsa kuri Data wa twese , ni Yesu Kristo umugororotsi , kand’uwo ni we mpongano y’ivyaha vyacu . ”
Hari abo usanga bashira umutima ku vyo bashaka kwumva igihe bariko bahabwa impanuro .
• Kwosa imibavu vyoba bifise ikibanza mu gusenga kw’ukuri muri iki gihe ?
Nta kibanza Yezu yigeze aha ukutumvikana canke ukwirema ibice mu bigishwa biwe ; eka mbere ntiyigeze abarekurira gusobanura uko bishakiye ukuri kuva ku Mana kugira ngo baguhuze n’imigenzo y’abo bohuye ishingiye ku mico kama canke kw’idini .
Vyongeye , wokora iki kugira ngo witegurire neza gutahura insobanuro y’ico kintu gihambaye ?
Haciye imyaka ibiri , ubwato Titanic bwarasavye .
Benshi muri abo bantu bakundwa , twe na Sybil twababona nk’abana n’abuzukuru bacu bo mu vy’impwemu .
Urumva rero yuko akamwemwe kariko karabasya kubera amadini atari agishoboye kwongera kubabuza kuronka Bibiliya .
Jewe n’umukenyezi wanje ntitwari bwigere twiyumvira yuko umusi uri izina twokwitiranije amajambo “ umwigisha ” n ’ “ imbeba ” .
