NjengeKosi yomBuso kaZimu wezulwini , uJesu Krestu uzobuqeda msinya ubumbi ephasini , alenze ipharadesi lapho abantu bazokuphila khona unomphela .
12 , 13 . ( a ) Yini eyatjhukumisela uJeremiya bona athi : “ UJehova usisabelo sami , ” begodu ngimuphi umoya egade anawo ?
Eminyakeni engaba yi - 3 000 eyadlulako , umphorofidi u - Eliya wabiza u - Elitjha bona azomsiza .
AboFakazi bakaJehova bazokuthabela ukukurhelebha ufunde bona ungatjhidela njani kuZimu ngesifundo seBhayibhili .
▪ Usithemba Kangangani Isazelo Sakho ?
Mumoya ofanako naloya ekukhulunywe ngawo kwebe - Efesu 2 : 2 , ethi : ‘ Ngesikhatheso benisathathekile nikhamba ngokonakala kwephaseli nidoswa phambili mbusi wemimoya emimbi esemkhathini , umoya loyo obusa kumadodana angamthobeliko uZimu . ’
Sikima , ubhajadiswe . ” — IZE . 22 : 16 .
Kwesithathu , uJesu uthandaza ngokubuyelelweko malungana nobunye bethando abubawela abafundi bakhe , njengombana kunjalo ngaye noYise .
65 : 2 .
“ Ubekezelele . . . izitja afanele azithukuthelele ” bona alungiselele ‘ izitja zomusa ’ — okusigaba sekoroyi .
Ithulusi elihle khulu lokurhelebha iimndeni ihlale ‘ ikulungele ’ ukufika kweNdodana yomuntu litjhentjho elikhulu elenziwe ehlelweni lemihlangano yaqobe veke elathoma ukuberega ngoJanabari 1 , 2009 .
Ukusilingeka kwakho kungakwenza uzizwe kwanga ukulotjha uJehova akusisiqunto esihle .
Njengombana umberego wokutjhumayela uqakatheke kangaka kithi , kufuze sinikele ngesikhathi sethu esinengi , amandla nokutjheja ngendlela esingakghona ngayo .
NANYANA bangathandaza , abanye abantu bayazaza bona uZimu ukhona .
BekunaboFakazi aba - 2 380 kwaphela enarheni yoke — abanengi bebaziimfiki ezivela ePoland .
Godu isiporofido seBhayibhili siveza indlela ukusahlelokhu okuzokuthoma ngayo .
IBhayibheli alisifihleli lokho uMosi ebekasolo akucabanga .
25 : 6 ) Umpristi uFiniyasi bekazokwenzani ?
Iinkhozi zakhe zihlala zithabile ngombana zithanda ukusiza abanye .
Ngokuza kwakho esiKhumbuzweni uzokuba nethuba lokubona ukuthi ukufa kwakaJesu bekuqakatheke kangangani .
Ihlangano kaJehova isenzela izinto ezinengi khulu ezingasisiza nasifundako .
Njengombana ngiragela phambili ngeemfundo zami esikolweni seBhayibhili , ngakghona ukwenza amatjhuguluko .
UJean - David obuya eFrance yena - ke watlola wathi : “ Satjhumayela esitradeni sinye ama - awara amanengi tle !
( b ) Wafunda ini umnakwethu weThailand ngomsebenzakhe ?
Kodwana lokhu kuvimbela ubunye ; labo abezwa umuntu ozikhakhazisako bangaba nekwele .
6 , 7 . ( a ) Hlathulula izinto uDanyela aqalana nazo ngesikhathi aseBhabhele . ( b ) UDanyela wakuveza njani bona uvuthiwe ?
Ngemva kokuhlongakalelwa ngunina angakalindeli , wagandeleleka khulu .
“ UZimu . . . uzosula iinyembezi emehlwenabo . Ukufa angekhe kusaba khona . ” — IsAmbulo 21 : 3 , 4 .
Lezo bekuzizenzakalo ezingokomoya eziqopha umlando kuwe .
Unomnqopho wokufunda iBhayibhili qobe langa ?
Khuyini ngokukhethekileko eyenzekako nje ephasini ngesizo lomoya kaJehova ocwengileko ?
Ngiyiphi indlela yokucabanga ethandwa babantu abanengi begodu kubayini bacabanga njalo ?
Emhlanganweni waqobe mnyaka wango - 2016 we - Watch Tower Bible and Tract Society of Pennsylvania uMfowethu uStephen Lett olilunga lesiHlopha esiBusako watjhaphulula iculo elitjha lokubhina , elinesihloko esithi “ Bhinelani UJehova Ngethabo ” , watjho ukuthi kungasikade sizabe siyisebenzisa emihlanganweni yethu .
26 620 809
Yeke , nengabe kuyadivoswa ngebanga lokuthi omunye umKrestu abhalelwe kuthembeka , ibandla liloke lizokubambisana nabo .
Nathi - ke singazifumana sesidiselwa ziinhliziyo .
Kubayini kufuze itjhebiswano esinalo noJehova lihlale lizikile ?
( IzA . 3 : 5 , 6 ) Navane sivula iinhliziyo neengqondo zethu nasifunda iBhayibheli neencwadi esiziphiwa yihlangano kaJehova , sizokuthola umkhanyo wemiphumela yezinto ezisezako sikwazi nokuhlala emtlhaleni .
Bengiyinto yokudlala ebantwaneni , bakhwela bazehlela phezu kwami ngombana babona ukuthi akunalitho engingalenza .
Alo , abanye bazisebenzise njani iinluleko ezisemTlolweni ? Yini abayenzileko bona bahlale banokuthula noJehova nabanye abantu , nokobana bahlale banakho ngeenhliziyweni zabo ?
Yini le eyakara umrhubi kangaka ngoJehova beyamenza wakubuyelela kanengi ukuthi uJehova akadunyiswe ?
Nesithanda abantu esikunye nabo , angekhe sibaqale njengabantu abaphasi namtjhana sikhulume nabo ngokudelela .
Sathi nasithoma ukufunda njalo , ngafunda ukuthi ibizo lakaZimu uMninimandla woke nguJehova .
17 Kubayini Kufuze Uphe UMuntu Onakho Koke ?
Safudukela ethresteni elihlanu kwedorobho leTallinn e - Estonia nalo beliyingcenye ye - USSR .
Ipendulo libanga elenza uDavidi wathabela ukutjhidelana noJehova begodu wabizwa bona ‘ mumuntu ovumelana nehliziywakhe ’ nokobana wazindla ngokudephileko ngeemsebenzi kaJehova nangobuhlobo bakhe noZimu .
Ababonisi besigodi kufuze sibamukele nabazosivakatjhela .
Abathobekileko bazokudla ilifa lephasi , begodu bazokufumana ithabo nokuthula okukhulu . ”
[ Iinthombe ekhasini 16 ]
UDaniel nekamajadu nezabelo zakhe zebandleni , uSarah kanengi bekabanikela isizo .
Abagijimi abasesebatjha abazokungenela ama - Olimphiki bayazikhandla , bazibandula ama - awara ambalwa qobe langa njengombana bazilungiselela ukujamela iinarha zemakhabo , kukulapho iintanga zabo zitetemuka ebumnandini .
Alo uyini umphumela wokuba nethando elinjalo ?
Hlala Uphapheme !
Isibonelo , ungakholelwa ngokuqinileko bona ubufebe — ukuya emsemeni kwabantu ababili abangakatjhadani — akukalungi .
Ebujamweni obunjalo , ipendulo ekhanyako esekelwe eBhayibhilini ngobujamo bakho ingafaneleka .
Ukuthembela kwakho kuJesu njengoMbusi kuthuthukiswa njani kuqala okuhlangabezwane nakho kwakhe ephasini ?
Malungana nokubuya kwakhe ngemihla yokuphela , uJesu wathi : “ Iinhlupheko ngesikhatheso zizabe zizimbi khulu , zingalingani nalezo ezakhe zabakhona kusukela ekuthomeni kwephasi bekwaba kunjesi nezingasoze zaba khona godu . ”
Nokho , ungazibuza : ‘ Kghani iBhayibheli liyasitjela ukuthi ukuphela kuzokufika nini ?
NGO - 1905 usosayensi odumileko u - Albert Einstein nezinye izazi ezinengi zesayensi bebakholelwa bona indawo yoke inomthala owodwa — i - Milky Way yethu .
Indaba le , besekukade yabikezelwa emtlolweni othi : ‘ Kuzakuthi emuva kwalokho ngithululele umoyami kibo boke abantu . Amadodanenu namadodakazenu azakuphorofida ; . . .
Simthanda kwemhlolo uZimu , sifuna nokumlalela abe asibumbe , ngani ngoba sazi kuhle ukuthi imiyalwakhe izuzisa thina .
Ufuna iindaba ezimnandi zitjhunyayelwe ephasini loke , nathi usimema bona sihlanganyele emberegweni lo .
Bekutlhogeka ahlale amunye .
Lokhu akusingebanga lokobana unehlonipho edluleleko ngomseme .
Lokhu kungaba sitjhijilo kezinye iinarha .
Ukuba ngewebukhosini beGibhide khona bekungcono ngani nakumadaniswa nokuba ‘ nguKrestu ’ namkha ‘ Ozesiweko ’ kaJehova ?
Loke ithabo liyanda begodu ubuhlungu buyaphunguka nenginaye . ”
Kokuthoma , cabanga ngomzalwana osesemutjha omKrestu osekafunda isiporofido sakaHosiya ehlelweni lesifundo sakhe somuntu mathupha .
Angithi iBhayibheli liyatjho ukuthi , “ ukholwa ngilokho okuzwileko ; NW . ”
Wazi kuhle bonyana abantu banesono “ uyakhumbula bonyana silithuli nje . ” — IRhubo 103 : 8 , 9 , 14 .
( IRhubo 145 : 18 , 19 ) IliZwi lakhe iBhayibheli , lisikhuthaza bona sikhulume naye ngananyana yini esitshwenyako .
Yeke , isihloko esilandelako sizokukhuluma ngokuthi amadoda nabafazi bangaliqinisa njani iboda elingokomfanekiso elivikela umtjhado wabo .
Nakakubethako ukubetha “ ngeswazi ” elikufaneleko .
Umlayezo ebekatjhumayela ngawo bewuthinta “ abaneenhliziyo ezaphukileko . ”
UPowula nabakhambisani basifumana njani isinqophiso somoya ocwengileko ?
Ingomuso elinjalo uZimu ulifunela abantu abanengi ngendlela okungakghoneka ngayo , ngitjho nalabo ebebangaphili ngeenkambisolawulo zaKhe . — 1 KuThimothi 2 : 3 , 4 .
UJesu wasabela njani ?
( Bud ) Sullivan , ombonisi womnyango .
Kwamambala , uKrestu ukukwenziwa samuntu kokuhlakanipha ! — Iziy .
INdodana kaZimu , uJesu , beyazi bona siyawatlhoga , ngombana yathi ebafundini bayo : “ Umoya . . . uzanidosela kilo loke iqiniso . ”
UKrestu uyikhambela njani phambili indlela ‘ yokulunga ’ ?
Nako umphorofidi uSamyela azakuriyada ukufika eGiligali , uSawula wagcina selaphela nehliziyo .
( b ) Yini engaphadlhula amaKrestu phakathi ?
Omunye udade we - Asia onomraro wokutjhentjhatjhentjha kwamazizo ( bipolar ) wathaba nekafunda indaba yokuphila yomzalwana owakhonza njengesithunywa sevangeli owaqalana ngokuphumelelako nomraro ofanako .
Ungafumana iimpendulo ezanelisako zeembuzo leyo esahlukweni - 11 sencwadi ethi Khuyini Kwamambala Okufundiswa YiBhayibhili ?
Nokho , ngokufundisisa iBhayibhili , singazithokozela iindima zakaJehova njengoMluleki ohlakaniphileko , uMphulusi onamandla , noMuphi onomusa , ukubala ezimbalwa kwaphela .
Bobabili kufuze badlale iindima zabo ‘ banyamanye . ’
NjengoBaba onethando , uJehova bekakhona , ukhona nje , begodu uzokusolo anabantu bakhe .
Nasitjhidelena noJehova ipilwethu iba ngencono begodu siba babantu abathabileko .
( Nerh . 3 : 12 ) Kunokuthi baziphathe njengamadodakazi womBusi , benza umsebenzi ebewenziwa babantu abaphasi .
Matewu 28 : 19 , 20
Yakhe yathi : “ Yizwa ilizwi lesibawo sami , lokha nangilila kuwe [ “ Jehova , ” NW ] . ”
Mina noMairambubu bese sijayele ukuya eBalykchy .
UJesu begade asiza abafundi bakhe bazwisise ukuthi ukutshwenyeka okungakafaneli , okunganatlhogeko namkha okukhulu khulu , akuzilungisi izinto .
Sitjhisakalela ukukhulekela kweqiniso . — 1 Thi .
Louis , eMissouri .
Ukubulunga iindaba zomuntu mathupha ziyifihlo kusiza njani ekubulungeni umoya omuhle ebandleni ?
“ Yembathani isirhawu , ukulunga , ukuthobeka , ubumnene nokubekezela .
“ Babadosiphambili Benu ”
Kuyatjho ukuthi uJehova bekathabe kwamambala nekabumba iNdodanakhe okungiyo yodwa ngakwabo !
Msinyana uKoresi wakhupha umlayo obewuvumela amaJuda aseleko bona abuyele enarheni yekhabo .
Lemuka ubujamo bamambala obubandakanyekako .
UPowula wathi umbonisi kufuze abe “ mumuntu okwazi ukuphatha kuhle umuzi wakhe , akwenze ngokuzithoba , khona abantwabakhe bazamthobela . ”
Besele azongibuyisela embhedeni isivakatjhi nesithi , “ Kubayini ungamvumeli u - Elva abe khona nesifundako . ”
Ukuphila kwami bekutjharagene .
1 : 6 ) Ngitjho nemiTlolweni yesiHebheru zintathu kwaphela iincwadi ezikhuluma ngoSathana okutjho ukuthi uMphikisi .
Yini u - Abrahamu azoyithabela ePharadesi ?
Amezwi la bekasekelwe kilokho aqalana nakho .
Ngisiphi isifungo inengi lethu elasenza ? Singahlala njani sithembekile ?
IMegido beyiyingcenye yeNarha Yesithembiso uJehova uZimu ayinikela ama - Israyeli .
8 , 9 . ( a ) Ngisiphi isibonelo esihle sokuphikelela emisebenzini emihle esisifumana kuSolomoni ?
Ningathoma ngokuthi ilunga ngalinye lomndeni lifunde ukumadanisokho .
Abantu abathanda uZimu sibabona ngokuba nomusa nangokusiza abanye abantu .
Ngitjho nanyana uZimu anganakho ukulinganiselwa kokuzwisisa isikhathi njengathi , singakwazi ukuzwisisa amabizo awasebenzisako nekabikezela izenzakalo ezizokwenzeka ngesikhathi esithileko .
Ngaphezu kwalokho , ngisiza ngisebenzise okunganani iphesenti linye lalokho ebengikutjho esiteji eminyakeni engaphezu kwama - 30 edlulileko . ”
Nathi namhlanjesi sisalindele iimphorofido ezikhuluma ngomBuso kaJehova bona zizaliseke .
UJehova ufuna woke umhlobo wabantu uphile ngokungapheliko
Ngakhulela eLos Angeles , eCalifornia , e - U.S.A . , besakhelene nabantu abahlukahlukeneko ebebadume ngobungebengu obunengi neendakamizwa .
* ( Funda uGenesisi 3 : 15 . )
Nokho , ukuthanda uZimu neNdodanakhe ethandekako kwasitjhukumisela bonyana senze amatjhuguluko amakhulu endleleni esicabanga ngayo nemikghweni yethu ukwenzela bona sithabise uZimu ngokuzeleko .
UMPOSTOLI UPOWULA nekatlolela amakholwa akunye nawo , watjho ngokubuyelelweko bona unethemba lokobana uZimu noKrestu bazowuthokozela umoya egade utjengiswa mabandla .
( Qala iingaba 11 - 14 )
Wabaqinisekisa ngokuthi usabathemba ngokubanikela iiyeleliso ngomsebenzi oqakathekileko wokufundisa abantu .
Ngezinye iinkhathi singakhutjwa bese siyatherezela siphelelwe mamandla .
Umfazi wesibili “ okhululekileko ” lo nguSara , umka - Abrahamu .
Okunye ebekwenzeka , abantu bebafundelwa umThetho kaZimu okunganani ama - awara amathathu ekuseni .
Amezwi la atjhiwo mumuntu amjayeleko ebekalinga ukumtjhiriya , kodwana uBebe amlimaza kunokobana amduduze .
Abarholi bekolo bakwa - Israyeli neRoma bakhela uJesu iqhinga lokumbulala , begodu inengi lesitjhaba lamala .
Khulukhulu nesibanjwe ‘ micabango etshwenyako , ’ sitlhoga isikhuthazo esisifumana emihlanganweni yebandla , lapho uJehova asiqinisa ‘ ngenduduzwakhe ’ begodu asekele ukuzimisela kwethu ukuhlala sithembekile . — Rha .
( Iziyema 17 : 1 , Contemporary English Version ) IBhayibhili ithi indoda kufuze ihloniphe umkayo .
Umkakhe uthi : “ Sifunde ukuqakatheka kokuthandaza ndawonye qobe nokusebenzisa isiluleko seBhayibhili sokuba nethando lamambala nokubekezelelana .
Basamukela isikhuthazo somdala begodu benza ngokuvumelana naso .
Kungebangelo asebenza budisi kangaka , alwela ukuthi abanakwabo bahlale batjhidelene noZimu . Begodu bekangakatalelwa bona enze lokho .
Isifebe sizokuragela phambili sinamandla begodu silinge ukwenza amakhosi enze nanyana yini esiyifunako , bekube kulapho uZimu afaka umqondo othileko eenhliziyweni zawo .
Qala bona kusithabisa kangangani bona uJehova usebenzisa umoyakhe ukusisiza bona senze iimsebenzi eemkhulu nehlukahlukeneko esiyiphathisiweko !
Ilanga , eliyikwekwezi lisinikela isibonelo sento etjhugululwa ibe mamandla .
Itjhentjho elinjalo lizokuthintha ukuziphatha , iinqunto zethu nakho koke esikwenzako .
Umsebenzi ‘ ka - Elija ’ owabikezelwako lo wenziwa ngokuvumelana nentando kaZimu njengendlela yokubona loyo egade anguMesiya .
ISIGUBUZESO : Ukufakaza endaweni yomphakathi eFrankfurt , eJarimani
Abantwabo ngibo abazokwenza iphasi libe yipharadeyisi .
Njengombana anganaye umlingani womtjhado angathululela kuye isifuba , amaKrestu angakatjhadi arhuluphele ukuthembela kuJehova ngokuzeleko . ( Iziy .
Ukufanekisa lokho , cabanga godu ngesibonelo sokudla .
UMaria wabaleka esibhedlela ukwenzela bona avikele umntwanethu ongakabelethwa .
Njengombana isiphorofidwesi sabikezela , ama - Israyeli athunjwa isikhathi eside .
Bobani abasisizwe “ esibizwa ngebizo lakhe ” uJakopo akhuluma ngabo kuzEnzo 15 : 14 ?
Emsebenzini wesifunda , sathabela ukuhlala neemndeni eemnengi ehlukahlukeneko .
( b ) Abantu bathi nabadalwako benziwa baba nasiphi isifiso ?
USathana yena - ke akayingeni yokuthi abantu bayakholwa kuthi ukhona namkha awa .
( Gen . 3 : 6 , 7 , 17 - 19 ) Nathi njengombana siphila nabantu bephasi abangathokoziko nje , singazifumana sele singasaziboni izinto uJehova asenzele zona .
Isibonelo salokho kungaphambi kobana ama - Israyeli angene eNarheni yesiThembiso , uMosi nakazawayelelisa ngokuthi : “ Ziyeleleni ningayengwa bese niyaphambuka nilotjhe abosingazimu benibakhothamele ngombana itukuthelo kaSomnini izokuvutha phezu kwenu . ” ( Dut .
Uzizwa njani ngekonzwakhe ?
Ngemva kokuqala iindlela zokuphila neenhlangano ezihlukahlukeneko , ngaqiniseka ukuthi into engcono khulu engingayenza ngokuphila kwami bekukukhamba ngibukele iplanethi ehle le ngaphambi kobana abantu bayitjhabalalise .
4 : 1 - 3 , 13 ; 5 : 6 - 8 .
Isifungo somtjhado ( Qala sigaba 14 )
Ngani , ngoba kumnqopho kaJehova bona woke umuntu “ okholwa kiyo [ indodana ] abe nepilo engapheliko ” ! ​ — Jwa . 3 : 16 .
Loyo osesihlalweni sobukhosi wathi : ‘ Qala , ngenza koke kube kutjha ! ’ ”
3 , 4 . ( a ) Ngibaphi abantu abavuswa ngaphambi kobana abapostoli bakaJesu babelethwe ?
Iqiniso kukuthi iBhayibheli ayitjho ukuthi nange ungaphayoni awumlotjhi uJehova .
Akakho obekathatha iinhlabano athi batjho uvikela inarha yekhabo ngombana bebahlala kamnandi eendaweni zabo .
malungana nendlela uJehova akulibalela ngayo ?
Namhlanjesi - ke thina sisemgijimweni wepilo , ngapha siqalene nabaphikisi abafuna ukusithikazisa bebasidule phasi , basilahlekisele ithabo lethu nomtlomela wethu wengomuso .
NENGIQALANA NEHLEKELELE
Nengisejele , ngaba mngani omkhulu wesibotjhwa ebesaziwa khulu kwezepolotiki emphakathini loyo .
Nokho , pheze boke banamazizo wokobana indlela engcono khulu yokwenza lokhu , akusikukhuluma ngazo , kodwana kuphila ngedlela esibonelo kwabanye .
Endabenethu le , sizokudemba yokuthi kubayini kufuze sihlubule ubuntu obudala , kubayini kurhaba ukwenza njalo , begodu kubayini singakghona ukubuhlubula nanyana besele sizike kangangani emikhubeni emimbi .
Singazifundisa ukuthokoza besihlale sinjalo ngokuzindla ngezinto uJehova asenzele zona bese siyamthokoza .
Kodwana ikhona ipendulo .
Kungenzeka ukuthi isisebenzesi sabhalelwa ukuletha isilinganiso sekoroyi esavumelana ngaso nomqatjhaso . Amezwi la athi : “ Kwathi sekudlule amalangana ngiqedile ukuvuna , kwafika uHoshayahu indodana kaShobay , yafika yangemuka isembatho sami . . . .
* ngifunda ngeendaba zabantu abatjhugulula ukuphila kwabo .
UGloria bekasebenza emakhitjhini , ahlwengisa izindlu ezimbalwa ngelanga .
Wahlala amalanga amahlanu ngekumbeni yababangwa neenzibi esibhedlela , ngaphambi kobana ahlongakale .
( b ) Kubayini kufuze singazibuyiseleli namtjhana sibambelane amavunda ?
IINGOMA : 63 , 43
10 : 23 ) Godu uSathana ulawula iphaseli , ngalokho abantu angekhe bakghona ukuletha ukuthula ephasini . — 7 / 1 , ikhasi 16 .
UmThetho kaMosi bewuhlukanisa abantu abanobulepheru ebantwini abaphilileko .
“ Kodwana nina azange nifunde uKrestu ngendlela enjalo , ngombana sele nezwa ngaye benafundiswa ngaye ngokweqiniso elikuJesu . ” — 4 : 20 , 21 .
Wabulala oyedwa namtjhana ngaphezulu wabanakwabo lakaHezekiya .
USathana watjhijila umthethobulungiswa wobukhosi bakaJehova mhla ahlubukako .
Umnqophwami kubasiza bona balemuke iinzuzo ukuphila ngomthetho kaZimu malungana nomseme okunazo ngokomzimba , engqondweni nangokwamazizo .
Okukarisako , ngokukhamba kwesikhathi atjhentjha umkhumbulwawo akholwa nguye .
( Funda 2 KwebeKorinte 11 : 23 - 28 . )
9 , 10 . ( a ) Ngokuya kwencwadi kaDuteronomi 4 : 5 - 8 , umthetho bewuwahlukanisa njani ama - Israyeli kwezinye izizwe ?
Ngiyiphi enye indlela uJehova asitjengisa ngayo ukuthi uyasithanda ?
Ukulwisana Kwabantu Nokufa 4
Nomsa : Ngaphambi kobana ngikhambe , kukhona okhunye engifuna ukukuhlanganyela nawe .
Abazitjheji iinyeleliso ezimenyezelwa ziinceku zakaZimu .
Kungombana uMariya bekasizukulwana sakaNathani indodana kaDavida .
Uyakhumbula nangikuvakatjheleko , ngakubuza bona kubayini uZimu avumela ukutlhaga kuragele phambili nengabe unamandla wokukuqeda .
Kunalokho , ngokuyihloko kutjho bona sikhetha ukubalekela ukukwata .
Enye indlela esingalingisa ngayo uMosisi kuhlawulela ithando lokuzidela ngabanye .
( IRhubo 34 : 15 , [ 34 : 14 NW ] ) Nasiragela phambili senza ukuthula nabanye sizokuba nobungani nabodade nabazalwana begodu lokho kuzosenza sibe yinyanda yinye .
Godu , nanyana singalinga ngamandla kangangani , kufuze qobe langa sibawe ukulitjalelwa nange sibhalelwa ukuba ngabacwengileko , sitjheje bona sisesezizoni nokobana ukuvunyelwa kwethu bona sibizwe ngegama lakaZimu elicwengileko kulilungelo elikhulu ngendlela engeze yahlathululwa . — Funda 1 Jwanisi 1 : 8 , 9 .
Babona ituthuko ethabisa kwamambala .
32 : 28 .
Kodwana bengazi kuhle ehliziywenami bona lokho engikwenzako akukalungi .
Kwamambala , kwanga kungaba sifiso esivela ehliziyweni yomunye nomunye wethu ukulandela isiluleko seBhayibhili esithi : “ Nengabe niyagoma namtjhana niyasela , kwenzeni koke , ze kudunyiswe uZimu . ” — 1 Kor .
Ukulalela uZimu yindaba yokufa nokuphila .
Qala bona u - Esewu bekalindelwe lilifa elikarisa kangangani !
Ngasikhathi khekube budisi ukuthembeka emalungeni womndenethu .
Ngokukhamba kwesikhathi umma lo wazisola ngendlela enza ngayo , yeke watlola incwadi wayisa e - ofisini legatja .
Ngitjho nanyana kunjalo , uJanny wenza ikamuro laba lihle begodu laba yindawo efuthumeleko .
Kungaba kukwenza okuthileko , mhlamunye ukunikela ngesipho , ukungenela umkhakha othileko nofana ukudela ezinye izinto .
Ngezinye iinkhathi , walinga ukuzibandakanya eentweni abazenzako , kodwana ilunga lomndeni ngalinye beliqinile ekungathintanini naye .
Semakhulu weminyaka , amasondo asolo arhatjha ifundiso yakaZiqu - ntathu , athi uBaba neNdodana bayinto yinye .
Namtjhana bewuzokuthukwa newucabanga ngomphumela ozokuba khona ?
Ngilokho - ke okwenza uJesu watjela abadosi phambili bamaJuda abakhohlakeleko wathi kibo : “ Ngalokho ngiyanitjela bonyana umbuso wezulu uzokususwa kini unikelwe abantu abazokuthela iinthelo . ”
Wathi , “ Ngiyanazi !
Nebezwa indlela uPitrosi ahlathulula ngayo amezwi lawo , abalaleli abanengi “ bahlabeka eenhliziyweni . ”
Ngisiphi isibonelo esihle esibekwa madoda akhethiweko ebandleni ?
Nanyana kunjalo , uJehova uZimu wakwenza kwakhanya ukuthi u - Adamu angadli emthini munye kwaphela , wamyelelisa ngokuthi nakangadla emthini loyo uzokufa .
kaNovember 2009 , amakhasi 12 - 14 .
Ipilo ingasigandelela bona sitjhidelane nalabo abangayihloniphi imithetho kaZimu yokuziphatha , kodwana lokho akutjho bona kufuze nathi sizinikele ezenzweni ezimbi .
Ungaphelelwa lithemba .
Ngokukhanyako , ngokwemfundiso esizitholileko kube netlhogeko bona incwadethu yeengoma ilungiswe .
Ukuzotha akusiyinto esingavele siyihlathulule ngendlela evumelana nathi .
“ Kodwana akabawe ngokukholwa , angazazi . ” — JAK .
3 : 1 , 6 ; Mat .
Abafundisi bebawanyefula ama - colporteur , bawabiza abathengisi beencwadi abangatjho litho .
( Funda uJoromiya 29 : 11 . )
Soke siyabona kwanjesi ukuthi kulula kangangani ukudoswa zizintwezi bezisenze sidlale ngomusa kaZimu !
Ngokurhunyeziweko : Iinceku zakaZimu ezithembekileko zekadeni zisemathuneni , zilele ubuthongo bokufa , azizwa litho , zilinde ivuko . — UMtjhumayeli 9 : 5 , 6 ; IZenzo 24 : 15 .
UZimu ulalela labo abathobekileko . ​ — IRhubo 138 : 6 .
Kuliqiniso bona asikakateleleki ukubulunga ukuphumula kweSabatha namtjhana ukuthatha amakhambo waqobe ukuya emgidingweni eJerusalema .
BAMBALWA abantu abathabela ukubhadela umthelo .
Kusukela ebuntwaneni bakhe , uJesu wasitjhiyela isibonelo sokuthobeka .
Okuyokwenza uJehova afake isandla , lilungelo analo njengoMnikazi wendawo yoke .
Babelethi , sizani abantwana benu bavikele ikholo labo ( Qala isigaba 17 )
Khuyini - ke iBhayibhili ethi izokuphela ?
Lokho ekufundisako kungakutjhiya ubambe ongenzasi .
Ukuhlola kutjengisa bona kutlhogeka umnyaka neenyanga ezihlanu bona iphasi livuselele okusetjenziswa babantu ngomnyaka .
“ Gcinani ukulunga okufaneleko emabandleni nitjengise ukwethembeka nesirhawu omunye komunye . ” — ZAK .
Nekabuyako , ufumana abangani bakhe bakobukhulu ubuthongo .
Khuyini ebangele abanye baphelelwa mazizo wokurhaba ?
UMzalwana uKnorr bekasebenza ngokusemandlenakhe bona umsebenzi womBuso kaZimu wenzeke ngezinga elikhulu .
Nasingalalela abazalwanaba nabasitjela ngezenzakalo abazibonileko kungasenza simthembe khudlwana uJehova .
Wabona ukuthi umsebenzi lo uzokudla isikhathi sakhe sokutjhumayela .
Ngeencwadi .
▪ Linga iindlela ezitja zokutjhumayela kwabanye
Ngasikhathi bekuba budisi , nganingoba bekhe bangavumelani neminye imibono yeBhayibheli .
Ngeembono ephefumulelweko eyanikelwa abathembekileko bekadeni , uJehova usirhelebha bona sibe nesithombengqondo sezulu begodu sizwisise nobuhlobo bethu nalabo abahlala khona .
UMSEBENZI WOKUBHODA
Enye yendlela zokuthola ilwazi elinjalo kukuthi ukhethe bona uzokufunda ini .
Njengombana sivumela umoya ocwengileko usebenze ngokutjhaphulukileko emaphilweni wethu , uzokukhiqiza kithi isithelo esiletha ipumuzo kwabanye nesidumisa uZimu .
Umlayezo womBuso uziindaba ezimnandi ebantwini — kwamambala , “ iindaba ezimnandi . ”
Into ekufuze siqiniseke ngayo kukuthi nakunguDeveli naye angekhe anyefise izandla zakhe nakuziwa endabeni yokuthi alisise amaKrestu umsebenzawo awuthunywe nguZimu .
Qala bona umlayezo lo wamkhuthaza kangangani uJwanisi !
Ngokudlulileko , besicabanga ukuthi ukwahlulelwa kwabantu bona bazizimvu namkha ziimbuzi kuzokwenzeka hlangana naso soke isikhathi semihla yokuphela kusukela ngo - 1914 kuya phambili .
I - Spastic quadriplegia lihlobo lokukhubazeka kobuqhopho okumbi khulu ; okungabangela ukuqina kwezandla neenyawo nentamo erephelelako .
Godu sikhuluma nangalokho okuzosisiza bona sihlale siyithokoza iBhayibhili .
UThimothi wathoma ukuqalisisa njengombana uPowula noSilasi bethula iinqophiso ezitja ezivela emkhandlwini wamaKrestu eJerusalema begodu bakha nokukholwa kwabazalwana be - Ikhoniyo .
Kubayini ngasikhathi uJehova angayiphenduli ngokurhabako imithandazo yethu ?
Ngale kwalokho besingekhe sibe nethemba .
Nasiza endabeni yokukhuluma , iBhayibheli lithi : ‘ Soke sineemphoso ezinengi . ’
Umbuzo lo uqakatheke kwamambala , khulukhulu kilabo abahlongakalelwe balingani babo bomtjhado .
Thina aboFakazi nasitjhatjhululwako ngo - 1951 , naye watjhatjhululwa .
URichard , oneminyaka ema - 65 , wasuka e - United States ngo - 2010 wathuthela eGuam .
Nanyana kunjalo , ngomnyaka ka - 1993 , isiqhema sabarhubhululi savumbulula ilitje lakade khulu elinomtlolo otjhugululwe ngokuthi “ Indlu kaDavida . ”
UStephanie kufuze abulunge amandlakhe ukuwasebenzisela izinto aziqala njengeziqakatheke khulu , njengeemhlangano yobuKrestu nekonzo yesimini .
Kodwana uJesu wabakhalima boke njalo , uJakopo , uJwanisi , uPitrosi nabanye abapostoli ngokufuna ‘ ukuba namandla ’ phezu kwabanakwabo . — Mar .
Ngemva kobana uNuwa abe neminyaka ema - 500 , umkakhe wambelethela amadodana amathathu — uShemi , uHamu noJafete .
Izehlakalo ezilitjhumi kucocwa ngazo esihlokwenesi nesilandelako .
IBhayibheli lithi kufuze sifunde ukuba “ nesirhawu , ” ngitjho nanyana singakabelethwa naso .
Kanti enye kuziphatha kwethu kokuhlonipha uZimu .
UMarie - Paule weCanada , oneminyaka eyi - 74 , uthi , “ Mina nendodakwami mvanje sithuthele efledzeni .
UJustice John Paul Stevens Wekhotho Ephakemeko ye - U.S . watlola ukuthi umthelela onjalo “ awusongeli nje kwaphela ukwenza izinto ngokomthetho kaRhulumende kodwana nethemba labantu bawo . ”
U - Hezekiyeli wathunjwa ngomnyaka ka - 617 ngaphambi kokubelethwa kwakaJesu .
Kwesihlanu , kuphazima .
Esingaqiniseka ngakho kukuthi uJehova uzayibusisa yoke imizamwethu yokutjhumayela ngesikhathi esihle abantu abatholakala ngaso .
Abantu abaleleko ngokujayelekileko abenzi litho .
Ngemva kwalokho ababhini bathatha ama - awara amanengi bahlolisisa lokho ebazabe bakubuyekeza bese ekugcineni bawarikhode estudio e - Patterson , e - New York .
NOVEMBA 12 - 18 , 2012
UPitrosi athukiwe wathi awa angimazi .
Kwamambala , woke amalunga webandla atlhoga isikhuthazo , kubandakanye abarhuweleli namaphayona abenza ikonzwabo ngokuthembeka qobe mnyaka .
( Qala umtlolo ongenzasi . ) ( b ) Sibuqinisa njani ubuhlobo bethu noJehova ?
IINGOMA : 93 , 96
Bezibambe imimoya emine yephasi khona kungazukuba khona ummoya ovunguzako ephasinapha namkha elwandle nanyana uphephule umuthi . ”
Lokhu kusenze ‘ saziwa nguye . ’ — 1 Kor .
IiNdawo NeziNdlu : Iindawo nezindlu ezingathengiseka zinganikelelwa ihlangano esetjenziswa boFakazi bakaJehova ngokwenza isipho esinqophileko nofana nekuyindawo yokuhlala , kunganikelwa ngeenzuzo zayo kukulapho iragela phambili isebizweni lomninikazi nekasaphilako .
Inengi lingathi kunjalo nganingoba kunento ebizwa ngokuthi mphefumulo ongafi .
UJesu nabazesiwekwaba bakha uMbuso kaZimu , olithulusu uZimu azokutjhabalalisa ngalo uSathana . — Luka 12 : 32 ; Rom .
Abazalwana beJapan nabo balinda bekwaba sikhathi esifaneleko sokutjela abantwabo ngendaba yevuko .
Wabeka ukuphepha komntwanakhe ngaphezu kwananyana yini bese wasa umndenakhe eGibhida .
Khesithi udorhodere uthe ungazihlanganisi nomuntu onobulwelwe obuthileko obuthathelanako nobubulalako .
Zoke iingozi okukhulunywe ngazo esihlokweni esigadungileko zivela kuye , zihloselwe ukusiphambukisa endleleni eyisa ekuphileni okungapheliko .
42 : 2 , 6 .
Iimpendulo zeBhayibhili zeembuzo engehla zizokucatjangelwa lapho .
( Rha . 90 : 2 ) YiBhayibhili kwaphela esisiza bona sazi ngemisebenzi kaZimu yesikhathi esidlulileko neyagadesi begodu yembule nalokho azokwenza esikhathini esizako .
Ngokutjheja izintwezi , uJesu bekaqiniseka ukuthi “ iphasi lizakukholwa bona ungithumile . ” ​ — Funda uJwanisi 17 : 15 - 21 .
IKosi izakwiza neengilozi zayo ezicwengileko eziziinqarhanqarha , izogweba boke , ibalahle ngomlandu boke abanyaza uZimu , ngebanga lezenzo zoke zokunyaza abazenzako , nangamezwi amadinyana abawakhuluma banyefula uZimu . ”
Bekube seminyakeni yabo - 1920 , isiqhenyana sabaFundi beBhayibheli * besisolo sitjhumayela e - Australia khulukhulu magega neligu , emadorobheni nendaweni enganamanzi epheze ilingane nencenye ye - United States .
( b ) Khuyini etlhogekako ngo - Israyeli ongokomfanekiso bona akghone ukubusa noKrestu ezulwini ?
UMNQOPHO : Sivikela ‘ isizukulwanesi ’ besinqophise nabantu kuMesiya
Isigaba 6 : “ Ukuza ” kwakaKrestu ( NgesiGirigi , erʹkho·mai ) kuhlukile ‘ kunokuba khona ’ kwakhe ( pa·rou·siʹa ) .
Khuyini ezosiqinisekisa bona umBuso kaZimu uzowufeza umnqophwakhe ngephasi ?
Umoya Ocwengileko Usipha Amandla Wokulwa Nesilingo Nokudana , 1 / 1
Nawunokuthula , lokho kuzokuphumela ekutheni abanye bakuthabele ukulotjha nawe uZimu bebathabele nokuthula .
( Funda uNumeri 16 : 5 . )
Wona umqondo wamezwi athi umuntu ‘ wakosontjhaba ’ awusatjho litho kiboFakazi bakaJehova , abanganandaba nokobana abantu abaphakathi kwabo ngebaziphi iintjhaba .
Kubayini kungakafuzi sitshwenyeke ngesibalo salabo abadlako esiKhumbuzweni ?
Kungokufanako nangezinye iimfanelo zakaZimu uJesu azambula kubafundi bakhe nekasephasini .
Ngelinye ilanga umpostoli uPowula nakasemhlanganweni othileko ngekamerweni eliphezulu eTrowasi , nje ebizwa ngokuthi yi - northwest Turkey .
Abadala bangalingisa isibonelo sakaPowula , nakufanelekako bangakhamba neenceku ezikhonzako nabayokwelusa umhlambi .
( Jobho 42 : 1 , 2 ) Vele kwaba njalo .
Kusafana - ke nakithi , iBhayibheli isitjela ukuthi ephasini elitjha sizokufumana imisongo emitjha eneenqophiso ezitjha .
AmaKrestu azesiweko ‘ abelethwa kabutjha ethembeni eliphilako ’
ULeticia uthi : “ Bengingayithathi imisebenzi efuna bona ngizibophe isikhathi eside ngokuhlala endaweni yinye .
Esikhathini esinengi , iMitlolo ikhuluma , ingasi ngehliziyo yomuntu yenyama , kodwana ngehliziyo engokomfanekiso .
UHerbert Senior
Kwanga singaragela phambili sitjengisa bona siyasithabela isiphwesi ngokusisebenzisa ngendlela ephazimulisa uZimu begodu siragele phambili nokuhlonipha indlela abanye abasebenzisa ngayo ikululekwabo .
IBhayibheli lithi : “ Vulani iinhliziyo zenu ngokupheleleko . ”
Ngitjho nanyana sesiwathethe woke namkha amanye wamagadango lawo , kusatlhogeka sitjheje ukucabanga nokuziphatha kwethu .
16 : 20 .
Bekubudisi kwabanengi balabo egade bakhona ukukhandela iinyembezi zabo zethabo !
Kodwana uSara bekalotjha uZimu weqiniso , uJehova .
Umzalwana osesemutjha ojayele ukukhamba naye wafunda ukuthi woke amalunga webandla kufuze azizwe athandwa . — Rom .
9 - 11 . ( a ) Ngiziphi iimfundo eziqakathekileko esingazifunda endabeni kaTjhebhina ?
Akhe siqale indaba kaManowarhi egade angewekoro yakwaDani , obekahlala emzini weTsora kwa - Israyeli wekadeni .
Begodu lokho kunengqondo , khulukhulu nasiqala umongo wesiphorofidwesi .
Akakho ozazibuza bona , ‘ Kghani ukufa kusiphetho sakho koke ? ’
Abadala banamhlanjesi kufuze bayelelise nekutlhogekako .
Sikhulekela kilo njani ?
Ngo - 1976 , ngabekwa njengelunga leKomidi Yegatja eFrance .
Uthi : “ [ NginguJehova ] , libizo lami - ke lelo ! ”
Iphasi elitjha lokulunga sesiliqale nje !
Ngokwesibonelo , mva nje inengi lama - ofisi wabo wegatja amancani ahlanganisiwe ukwenzela bona kuncitjhiswe umsebenzi wokungamela bekuthuthukiswe izinga okufezwa ngalo ukutjhumayela iindaba ezimnandi zomBuso .
Nesele ufikelele umnqopho ohloniphekako lo , uzokufuna ukuba khona qobe ube lirhelebho , ungaphundwa yinyanga ungayi ekonzweni .
Kunokobana enze njalo wangitjengisa ukuthi ufisa ukungirhelebha . ”
Nakuya amasotja weRoma azakukhamba abuyele emva !
Kghani kungombana ikosi gade imbhini kwaphela ?
Kuqakatheke ngani ukuthi sitjhidele kuJehova ?
Abanye bangathi : “ Ungathi ungibona ngiphiphila kangaka , uthi angikunikele ukudla kwethu kokugcina , uthi awurhaphi nje ? ”
IINGOMA EZIZOKUVUNYWA : 123 , 95
Kodwana angeze sakghona ukufunda zoke iincwadi zethu ngesikhathi esilinganako .
Indlela ebekakuthabela ngayo yangenza ngathi akakaphili kuhle ehloko .
‘ Bekayazi Indlela ’ ( UG . Pierce ) , 12 / 15
15 : 1 - 5 .
Watjela iimvakatjhi ezivela eenarheni ezi - 85 bona zithabela ubunye obukhethekileko bephasi mazombe .
Siyawasekela na amadoda uJehova awakhethe bona adose abantu bakhe phambili ?
Msinyana ngemva kokubhabhadiswa kwakhe , uLeticia waphekelela udade oliphayona onokuhlangabezanwe nakho edorobheni eliseqajana , lapho batjhumayela khona inyanga yoke .
IKHASI 20 • IINGOMA : 129 , 134
Omunye umzalwana osekaneminyaka eyi - 20 amsizi uthi yena : “ Ilungelweli lidlula nanyana ngiliphi engakhe ngalicabanga . ”
Okhunye okulisizo bujamo obufaneleko , mhlamunye isibili nesisodwa sifunda ndawonye umtlolo welanga namkha iBhayibhili .
Inengi labayi - 144 000 selihlongakele labe laya ezulwini .
‘ Amadoda amadala ’ lawo awalibaleli nofana asule izono , ngombana akekho umuntu onikelwe ilungelo lokobana alibalele omunye umuntu isono asenze kuZimu .
“ Kunomngani wamambala osekela ngcono kunomfo . ” — IzA .
Namkha bekufuze alandele okuseBhayibhelini , nanyana bekungaba budisi nje ukuphila ngemali encani , anyamezelele nokuhlatjwa ngamagama ?
Abanye bakulemukile ukuthi iNdodana kaZimu , uJesu , yafundisa abalandeli bayo ngokuthi kufuze bathande izitha zabo .
Njengo - Abrahamu nathi kufuze sifunde ngoJehova .
Phela nencwadi yeVangeli lakaMatewu beyiphelela emsongweni munye kwaphela .
Sele uzifundile iinhloko zamva ezigadangiswe yinceku ethembekileko ezimalungana nokusebenzisa ithungelelwano lezokuthintana ?
Njengomalusi nakatlhogomela umhlambakhe , abadala kufuze bavikele izimvu abaziphathisiweko ( Qala isigaba 8 )
Ukulinda UJehova Litshwayo Lokuba Nekholo
Kuliqiniso , iimfundwezo bezitlhoga isizo elingeziweko bona zithuthuke eqinisweni .
Njengombana aqalene nobujamo obubudisobu , u - Asa uyathandaza .
Kodwana uDanyela akhenge ayingene yabantwabo , kangangobana bekathandaza bekube kathathu ngelanga kuJehova .
Abadala bangamsiza bona azi iinkambiso zakaJehova ezizomsiza athathe iinqunto ezihlakaniphileko .
Ngalokho - ke nasitjhumayelako sitjhengisa ukuthi siyamthanda , besithanda nabantu esitjhumayela kibo .
Qala bona uJehova uzokuthaba kangangani ukukunikela umvuzo wekambo yakho yokuthembeka ! — ISam .
Ungasebenzisa neliZwi lakaZimu ukubona ukuthi ukukholwa kwakho kunzinzile na . ​ — Funda uJakopo 1 : 25 ; 2 : 24 , 26 .
Kodwana soke singakghona ukusiza abazalwana nabodade abalupheleko , namkha imindeni esemirarweni .
( Funda uNerhemiya 13 : 23 , 24 . )
Wanikela abadala ithuba lokumqinisekisa ngethando lakaJehova .
Wanikelwa nelungelo elikhethekileko lokubeletha abantwana .
Kwathi ngokukhamba kwesikhathi uJakopo namadodanakhe nasebafudukela eGibhide , bakhamba nemindenabo . — Gen .
‘ Akakho noyedwa owaziko bona uBaba ngubani ngaphandle kweNdodana nalabo iNdodana ezimisele ukumambula kibo . ’ — LUKA 10 : 22 .
Njengombana kutjengiswe ekhasini 16 , kubayini ubunye bamaKrestu beburara ?
( Funda iRhubo 2 : 11 , 12 . )
Yini engiqinisekisa ngokuthi esikufunda eBhayibhelini kuhlala kusiza ? ’ — Isa .
Kungebangelo ngifumana induduzo abangani bami nabalila nami .
Siyabaqinisekisa nokuthi boke “ abalungileko nabanesililo ” uJehova uyabezwa .
Ngaba siphofu ngalahlekelwa namsebenzi .
I - The Tobacco Atlas ithi , “ Abososayensi bayavuma bona ukubhema igwayi kulimaza woke amalunga womzimba begodu kwandisa amathuba wokugula nokufa . ”
Sizokudemba neyokuthi yini esingayenza ukwenzela bona sihlule ukuba marhamaru ephasini elizele abantu abathanda imali nokuthi singamlotjha njani uJehova ngeenhliziyo zethu zoke .
18 , 19 . ( a ) Ukuzihlukanisa nomuntu owenza okumbi kunikela ubufakazi bokuhloya ini ?
Linga ukuzwisisa indlela abazizwa ngayo .
Kuzokufuze kube njalo nebantwini abatjha abazibekela imigomo yokukhonza uJehova begodu babeke nomsebenzakhe qangi ekuphileni kwabo .
Bese , njengombana kutjengiswe esiphorofidweni sakaJesu esimalungana neenhlupheko ezimbi , bazokubuthelwa ezulwini .
Hlangana neenzuzo ebekazithola emsebenzinakhe , yindlu ekulu , ikoloyi , iimberegi , nokusa abantwabakhe eenkolweni eziphambili .
Ukuphila kwethu ngokuvumelana nelwazi lelo kudlala indima eqakathekileko ekutjengiseni bona sesimazi ngokuseduze uZimu .
( IRhubo 103 : 3 , 4 , 12 ) UJehova usikhalima ngeendlela ezahlukeneko .
IKosi yathi kibo : “ UBaba wami uhlala asebenza njalo , nami kufanele ngisebenze . ”
Ngitjho nanyana kunjalo , kunokulandula bona uZimu ukhona , uCharles Darwin wathi : “ Isiphetho esifaneleko kimi kubonakala ngasuthi sikukobana ingqondo yomuntu ayikwazi ukuzwisisa yoke into . ”
ekhasini 27 . )
Kwaba ziindaba ezimnandi khulu lezo kibo !
Abakhethiweko bakhuthalele ukufundisa abantu ngesihlengo nokuthi bangazuza njani kiso .
( 2 Sam . 13 : 1 , 14 , 28 , 29 ) U - Absalomu weba ubukhosi bakaDavidi , kodwana amano wakhe wokuketula umbuso abhalelwa , begodu wabulawa nguJowabi . ( 2 Sam .
Udadwethu bekanesineke ekuhlanganyeleni nami amaqiniso weBhayibhili .
Kodwana kusukela lokho babona imiphumela emihle yokuthi ngibe nguFakazi .
Nakuyindlela afanelwa ngayo ayihlathululeki !
Yeke kufuze sihlale sililindile ilanga lakaJehova ngombana lingafika nanyana kunini . Kufuze senze koke esingakwenza bona sililungele .
Kwanga singadzimelela ekuzimiseleni kwethu ukulalela isikhuthazo sakaJehova esithi : “ Nasi indlela .
Umpostoli uPowula wathi amaKrestu anjengabantu abagijima ibanga elide . Nabazaliqeda ibangeli kufuze balahle koke okungabaphungulela ibelo namkha kubajamise .
Njengombana kuseduze bona kwenzeke izenzakalo ezikarisakwezi , yini ekufuze sizimisele ukuyenza ?
‘ Isibopho Sobunye Sokuthula ’
Isipho Esiligugu
Sekuminyaka abantu bakaJehova bazwisisa ukuthi nawuthi umKrestu akukafuzi ulwe nabantu besinye isitjhaba .
Imithi ye - oliva leyo ifanekisela abantu ‘ ababili ’ abazeswe ngamafutha wobukhosi okuMbusi uZerubhabeli noMphristi oMkhulu uJotjhuwa . Kuthiwa ‘ bajame phambi [ kwakaJehova ] , umniniphasi loke . ’ ( Zak .
Wayidlulisela esiqhemeni sezazi zephasi mazombe sabantu abanekghono , abasebenza ngaphasi kokusekelwa yi - Maecenas Foundation for Ancient Art neNational Geographic Society , banikelwa umsebenzi obudisi wokubuyisela nokulungisa i - codex , ezinye zeengcenye zazo esele zenziwe iinqetjhana .
Imisongo Emihleni YeBhayibheli , No .
( Qala ibhoksi elithi “ Iindlela Zokusebenzela Uzimu Isikhathi Esizeleko . ” )
UJehova uthi : “ Njengombana amazulu aphakamile kunephasi , zinjalo neendlela zami kunezenu nemicabangwami iphakamile kuneyenu . ” ( Isa .
Cabanga ngo - Alex , * owahlala iminyaka eyi - 19 ejele leBrazil ngebanga lamacala wokusahlela .
Saqatjha indawo yokufihla ihloko engehla kwefekthri yamaplanka .
UJehova uthembisa ukuqeda izipi bekube phakade .
Ngokwesibonelo , cabangela indlela uJehova asebenzelana ngayo nendoda elungileko uLoti .
Ngokwesibonelo ku - Eksodosi 34 : 27 , siyafunda : “ UJehova waragela phambili wathi kuMosisi : ‘ Zitlolele phasi amezwi la , ngombana kungebanga lamezwi la ngenza isivumelwano nawe no - Israyeli . ’ ”
Ngathi nangizwa bona kutlhogeka abantu abazokwakha eBethel yeSewula Afrika , ngafaka isibawo , ngamukelwa .
3 : 9 ) Akhuthi uyaqala bona sibusiseke kangangani , silotjha uJehova ngobunye !
Ngubani ongayazi ? ” — Jer .
Lezi ziimbonelo ezimbalwa ezitjengisa ukuthi ukulandela iinkambiso zakaZimu kuzosisiza sithathe iinqunto ezitjengisa ukuthi siyamthanda .
Ngebanga lekholo lakhe , wasinda esabuleni yobuhlungu begodu ekugcineni wafumana umvuzo ophazimulako .
119 : 111 , NW . ) Siyayithabela na imiyalo kaJehova , namkha siyiqala njengomthwalo ophula amahlombe ?
Ihloswakhe kwemathomeni beyikukuthi abantu baphile isiphelani ephasini babe bantwana bakhe abalalelako .
Ebekubonakala kwabanye kulidondolo kwaphela , kwaphila ngamandla kaZimu !
( a ) Iinzuzo zomhlatjelo zingafaniswa njani ?
Kuthiwani nengabe awuthelelani amanzi nomzalwana othileko ebandleni ngebanga lobuntu benu obungafani ?
Kungenzeka sebajayele ukucabanga njalo .
Isivivinyweso sakhiwa mibuzo eemthathu , engarhunyezwa ngokobana ini , nini , begodu bobani .
Okuhle kunakho koke , kukuthi uJehova naye uzabe azikhakhazisa ngawe !
Begodu uJesu nekabhabhadiswako , ilizwi elivela ezulwini laqalisa kuye njengeNdodanakhe .
Ngibuphi ubufakazi esibubonako bokuthi mbala isiHlopha esiBusako ngiso esifeza isabelwesi ?
Zakhamba neenkolelo zazo zamala namasiko wokubusa kwabantu . ​ — Gen .
UJesu wathi : “ Funani qangi umbuswakhe nakho koke ukulunga kwakhe , nje - ke koke lokhu [ izinto esizitlhogako ] nakho nizakuphiwa khona . ”
Kungokuvumelana nomongo lo lapho iBhayibhili itjho khona ukobana : “ Ubusisiwe loyo ongakalali ubuthongo . ” — ISam .
27 : 30 - 38 .
Kwathi bona uMariya alethe izibulo lakhe eJerusalema njengombana uMthetho kaMosi uthi bekufuze azomethula kuJehova , umphorofidikazi u - Ana “ weza , waphakamisa uZimu bewakhuluma ngomntwana kibo boke ebebalindele ukuhlengawa kweJerusalema . ”
AboFakazi abanengi bathola imiphumela emihle ekonzweni le yokutjhumayela .
Umhlangano owabanjwa ngo - 1234 eTarragona , eSpain , ngaphasi kwelawulo kaJames I waba nemikhandela efanako . . . .
20 : 9 ) Qala bona uJeremiya sibonelo esihle kangangani kithi , khulukhulu labo bethu abakhonza uZimu esimini ebudisi !
Kukanengi sizwa ngabantu abathi nabathandazako uZimu wabaphendula .
Imitlolo yesandla eyaziwa nangemisongo yeLwandle Elifileko yahlala iminyaka eminengi , ingaphakathi kwemijeka yedaka ebulungwe erholweni elisendaweni eyomileko
Enye yeenkambisolawulo ezinjalo ifumaneka kuzAga 18 : 13 , ithi : “ Nanyana ngubani ophendula indaba ngaphambi kobana ayizwe , lokho kubudlhadlha nehlazo kuye . ”
Mbala , ngizakuba nesisa kuye . ”
Nanyana kunjalo , khonapho bebangakaphephi .
‘ Iinhlupheko ezimbi ’ zithoma nini ?
Kubayini singaphetha ngokobana kusukela ngekhulu lokuthoma leemnyaka kuragele phambili bekuhlale kunamaKrestu azesiweko wamambala ephasini ?
Wavuka kuhle , wakhalima isiwuruwurweso nelwandle , wathi : “ Thula uthi du ! ”
( Funda u - 1 Pitrosi 1 : 8 , 9 . )
▪ Baphathe Kuhle Abantu Obatjhumayezako
Wabeka isibonelo esipheleleko sokubekezela ngetjiseko ekonzweni .
Isihlokwesi sizokukhuluma ngeendlela eentathu uKrestu atjengisa ngazo bona bekaphapheme hlangana nokuphila kwakhe kwephasini , endabeni ngayinye sizokuhlola iindlela ezisebenzako esingalingisa ngazo isibonelo sakhe .
3 : 9 ) Nesenza iminikelo yokusekela umsebenzakhe , sisuke sinikela uJehova lokho okungokwakhe . ( 1 Kron .
Funda iRhubo 45 : 2 , 18 ; [ 45 : 1 , 17 , NW ] .
Abantu bakhe ephasini mazombe bamlotjha ngendlela ayithandako .
Kwathi ngesinye isikhathi uJesu afundisa abafundi bakhe isifundo esiqakathekileko , wase wathikaziswa mrhali omunyapha .
UJesu bekazi ukuthi uDeveli uzokwenza koke angakwenza ukuze enze abantu bangasaboni ukuqakatheka kokuhlala balindile . ( Zef .
Ngimaphi amagadango aqinileko atlhogekako nesifikelwa ziimfiso ezimbi ?
Ngokungafani nazo zoke iinthombe ezifanekisela abosingazimu abangaphiliko beGibhide , uJehova , uZimu weqiniso , bekamumuntu wamambala kuMosisi .
Ubulelesi nokungalungi kuzokuphela .
Ngezinye iinkhathi kuyenzeka na kube nomehluko hlangana kwalokho esibonakala singikho ( ‘ umphefumulo ’ ) nalokho esingikho kwamambala ( ‘ umoya ’ ) ?
Kodwana ngokusekelwe emitlolweni esiyifunde namhlanje , ucabanga bona kuyakghoneka ngabanye abantu abalungileko bona baye ezulwini , kungilapho abanye abantu abalungileko bazokuphila ngokungapheliko ephasinapha ?
Umukghwa lo wathoma ukungitshwenya bengaba mkhulu . ”
Isiqhenyaneso sabazalwana nabodade abakhethelwe ukubusa , sitjhiswa kuthanda uZimu sisizwa namumoya ocwengileko , satjhumayela iindaba ezimnandi zomBuso kaZimu nanyana siqalene nobudisi .
UJesu wabutjengisa njani ubuntobo ?
Isibonelo , ungathi : “ Abantu abanengi namhlanjesi bacabanga bona zomseme ezenziwa ngomlomo akusingezomseme zamambala .
Ekonzwenethu yobuKrestu , singatjengisa amazizo wokurhaba ngokudzimelela emsebenzinethu , njengokucabanga ngokuthi ngiziphi iindaba , iimbuzo , namtjhana ukwazisa okungakara abantu esihlangana nabo .
Watjhiya ibutho lakhe bona lifele edakeni , waphunyurha amasotja wama - Israyeli wafumana indawo enganalo idaka , watjhinga endaweni ayazi kuhle ukuthi inabakhozi bakhe .
Ngiyakuthanda ukuditjha nabantu abatjha bebandleni
Ngebanga lokuthi akhenge ngikuzwisise kuhle ebebakhuluma ngakho , ngaqunta ukukhamba .
Nathi uJehova uyazilalela iinthembiso esizenzako .
Nengabe omunye wabo uyawa , omunye angakghona ukumvusa . ” — UMtjhumayeli 4 : 9 , 10 .
Abanye babona ngasuthi uZimu akakuboni lokho abakwenzako .
Khuyini okusehliziywenakho ? ’
“ Ngingabasiza njani abanye abantu ? ”
Yini ebeyiyitja ngokutjhumayela ?
UkuThula KwemiNyaka EyiKulungwana — Nangale Kwayo !
Into angakupha yona lingomuso elibangela amatlhuwo wodwa , phela naye isiphetho sakhe siyahlahlathelisa ! — IsAmbulo 20 : 10 .
Ziphuluse - ke , nengabe uyiNdodana kaZimu ! Yehlika esigodweni sokutlhoriswapho ! ”
Khuyini engakurhelebha bona uzuze esilayweni osifumanako ?
Akhuluma phambi kwekomidi yeSenate e - U.S . uDr .
Ngaphezu kwalokho sithokoza uJehova noJesu ngokusithanda nokusitlhogomela .
Okwamangaza uJosué , ngemva kweenyanga ezine wadoselwa nguJavier umtato .
Umberego lo wona bewungeze wabalula .
Abantu abangaphezu kwaka - 210 000 bebasemhlanganweni bese kuthi abanye babo bawulalele nge - video tie line .
IKosi uJosiya , obekasizukulwana sakaHezekhiya waphila ngemithetho kaJehova ‘ ngehliziywakhe yoke . ’ ( 2 Kron .
Sithoma ngamezwi atlolwe kuMatewu 24 : 29 , uJesu udzimelela ezenzakalweni ezenzeka esikhathini sethu .
UChris watjela uGavin bona iBhayibheli linomlayezo oqakathekile begodu ukulifunda kuzomrhelebha azwisise isifundo bhedere .
Kunokukhubeka msinyana , uphethe ngokuthi umzalwana akasafaneleki ukubamdala , ungazama na ukutjhiyela izinto kuJesu ihloko yebandla bona ahlulele ?
Kodwana kuthiwani nengabe simaqili endleleni esikhuluma nesenza ngayo , sibangele esikholwa naye bona abawe irhelebho kuZimu ?
Ngasebenza ngetanka ephehla amanzi atjhisako namakhaza ibuye iphehle nesitimu ema - ofisini weBethel eBrooklyn
Khumbula , uDavidi wathi nekafihla izono zakhe , ‘ amathambakhe aluphala ngebanga lokunghonghoyila kwakhe ilanga loke . ’
“ Abantu bebalindile , begodu boke bebazibuza eenhliziyweni malungana noJwanisi , bona akasinguMesiya na . ” — LUKA 3 : 15 , THE EMPHATIC DIAGLOTT .
Kunezinto ezinengi ezithabisako ezenzeke epilwenami begodu uJehova ungibusise khulu . ”
Labo abalotjha uZimu ndawonye kufuze babe yikolo yinye . — 1 Korinte 1 : 10 , 11 .
Kghani kufuze ucobeke amathambo , uphethe ngokobana umoya kaZimu awukunqophisi ?
UHutter bekafuna ukufaka nelimi lesiHebheru elisuselwa emiTlolweni yamaKrestu yesiGirigi .
Ngakhulela endaweni enabantu abagandelelekileko .
6 , 7 . ( a ) Imimoya namagagasi okwathusa uPitrosi singakufanisa nani ?
Ungazizwa njani ngesiphweso ?
Ngahlwengisa nendlela egade ngiqaleka ngayo .
Singakghona nokuberega noMbumbi wethu sirhelebhe abafowethu nabodadwethu bathuthuke .
Amakhulu weminyaka ngemva kwesikhathi saka - Abela , uZimu wasebenzisa umhlatjelo wemvana enganabala ukutjengisa umhlatjelo weNdodanakhe opheleleko , “ iMvana kaZimu , ” iingazi zayo ezinganamlandu ezizokuphalaka .
Okuthabisako , ngo - 2006 uCheri wazinikela kuJehova begodu wabhajadiswa emhlanganweni waboFakazi eHong Kong .
4 : 14 ; IzE . 20 : 5 – 21 : 18 .
28 : 18 ; Fil .
UJesu umazi kuhle uZimu .
Enye yazo kuthiwa iveza uJehu , nofana omunye weenthunywa zakhe akhothamele ikosi ye - Asiriya uShalimaneseri III njengesenzo sokuyihlonipha .
Ngalokho singakghona nesilalela “ iindlela zakaJehova ” begodu singamtjhiyi . — Funda u - 2 Samuweli 22 : 21 , 22 .
Isibonelo sakaMikha sisifundisani ?
UStephanie uthi , “ Ngenza irhubhululo eenThaleni ezikhuluma ngokukhonza la kunetlhogeko khona . ”
UJesu nekayiphendulako wenza umfanekiswakhe odumileko wendoda ebeyikhamba isuka eJerusalema iya eJerikho eyabhudungelwa yatjhiywa “ ife isigiyani . ”
Ukutjheja bona sinesono kusenza sibandule isazela sethu esizositjhukumisela bona senze okufaneleko lokha nekuthoma ukwakheka isifiso sokona engqondweni nenhliziyweni yethu .
UJesu wathi abantu nabazakuzwisisa kuhle akufundisako kufuze basizwe .
Kuhlekuhle , bona singaziphathi ngokwendlela yephaseli , namkha silivumele lisibandule , kufuze siyihlole ngokuthembeka indlela esicabanga ngayo , amazizwethu azikileko , imigomo yethu , nendlela esikhamba ngayo .
Ngemva kwalokho , amaKrestu amatjha la ‘ azinikela efundisweni yabapostoli . ’
Kodwana ababelethi kungabazuzisa ukwazi bona kutjho ukuthini ukwenza umfundi .
Kwamambala , uMtjhejisikhathi Omkhulu unakho koke ukuhlakanipha nawo woke amandla .
Godu uDeveli akazithandi ‘ ezinye izimvu , ’ ezisekela abazesiweko begodu ezisethubeni lokufumana ukuphila okungapheliko — ithemba uSathana angasanalo .
Bakholelwa ukuthi iBhayibheli laphunyeleliswa kukuthi liyincwadi ekhamba yodwa , eliliZwi lakaZimu nokuthi uZimu uyibulunge bekwaba kunamhlanjesi .
U - Antonio , oneminyaka ema - 32 , uthi : “ Esikhathini esinengi ngiyathinteka nengibona uJairo aveza ikholo lakhe . ”
( Funda u - Eksodusi 23 : 9 . )
Akhucabange u - Abrahamu aneminyaka engaba yi - 125 ananya , atjhinga phezulu entabeni .
Kamva watlola wathi : “ Ngikghona ukwenza yoke into ngaloyo ongiqinisako . ”
Ngo - 1955 , safudukela eKemi , idorobho letlhagwini .
Nanyana bengisesemsanyana , ngaqunta ukufunda isiCambodia , khona ngizokukhuluma nabantwanaba ngoJehova .
Nengabe umKrestu ukhetha ukutjhada , kufuze atjhade nakholwa naye .
Zibathunywa bakaKrestu , kungebangelo ziba nesandla ekufundiseni abantu amaqiniso weBhayibheli begodu babasiza bona babe nobungani noJehova .
Kuyakhanya ukuthi wezwa ngeenhlobo zakhe .
▪ Khonza UZimu Ngokwethembeka Nanyana Uqalene ‘ Nobunzima Obunengi ’
20 : 25 .
Kungenzeka ukusaba bona isidiribe sizokudluliselwa eendlalifeni zakaNabhothi , kwenza u - Izebeli wahlela bonyana kubulawe amadodana kaNabhothi .
Bekakhamba iphasi loke , akhuthaza abafowabo nabodadwabo abamaKrestu .
Kodwana uJehova wabavulela indlela yokuba maJuda angokomoya . — Rom .
Isenzo sesiGirigi esitjhugululwe ngokuthi “ langazelela ” sitjho ukuzilula ngendlela engakajayeleki ukuze ubambe into .
Ngokwesibonelo , amabandla amanengi ingasikade bekafunda incwadi ethi Sondela KuJehova Esifundweni SeBhayibheli Sebandla .
( a ) Liyini itjhebiswano ?
Ipi esiyilwako le angekhe siyithumbe thina ngokwethu . Siyithumba ngoJehova .
Sizokucoca ngalokho esihlokweni esilandelako .
“ Kiloyo ohlezi esihlalweni sobukhosi nakiyo iMvana akube lidumo , iphazimulo namandla ngokungapheliko nini nanini . ” — ISAM .
“ Isiqubuthu esikhulu ” sibabantu abavela kizo zoke iintjhaba abazokusinda “ ekuhluphekeni okukhulu , ” okuzakuphela kunye nepi ye - Arimagedoni . — IsAmbulo 7 : 9 , 14 .
Njengombana umfutho weengazi zami wehla nje , ngalibuza ukuthi , “ Uyathoma na ukubona umuntu ofako ngami solo kwaba nguwe ? ”
( b ) Ngiziphi iingcenye zobuntu obutjha ezisencwadini yebeKolose 3 : 10 - 14 ?
KuJehova uGoliyadi bekafana nawo woke omunye umuntu , alingana nobutjhontjhwani obungapatlaka nanyana kunini !
Kghani lokhu kutjho bona uSolomoni bekangaseqisela amehlo isinqophiso sakaZimu angajeziswa , nofana bona nathi singenza njalo ?
Umtlhago Uzokupheliswa Njani ?
( Rha . 42 : 5 ) Mhlamunye ‘ ufisa umsebenzi omuhle ’ begodu ngalokho ‘ ufuna ukuba mbonisi . ’
Nokho , ngiyazibuza ukuthi kubayini lokho kubudisi kangaka .
Encwadini yeZenzo , sifunda umlandelande wezehlakalo zokuthusela nokuhlaselwa kwamaKrestu , zithoma pheze ngemva kweemmangaliso ezenzeka ngePentekoste laka - 33 C.E .
Elinye ibanga kungaba kukobana ukhanuka ikululeko ngesilinganiso esithileko .
Nakagandelela lokhu , ilizwi elisekhophyutheni liyakhuluma , “ IBhayibheli lithembisa ukuthi iphasi lizokuba yipharadesi lapho kuzabe kungekho khona ukugula nokufa , IsAmbulo 21 : 4 . ”
Ngitjho nanyana kungathiwa bekazizwa ngendlela le , wenze koke angakwenza bona anikele be asekele ukulotjhwa kwakaZimu ngeqiniso .
Ujayele ukubanikela njani abanye isiluleko ?
Bebaphila “ phakathi ” kwesitjhaba seenhlubuki .
IBhayibhili alisitjeli ngokobana uJesu wavelaphi kwaphela .
ISIGUBUZESO : Umzalwana we - Istanbul utjhumayeza umuntu orhuna iinhluthu , bekamkhambisele nencwajana ethi Iindaba Ezimnandi
Kghani ukulungisa ukucabanga namtjhana iimnqopho yakho kuzokuvumela ufumane ukuhlakanipha okungeziweko ?
Nasele senza njalo asisabi mdaka othambileko .
AboFakazi bakaJehova bemphakathini wangekhenu bangakuthanda ukukusiza bona nawe ulithole isizo leengilozi ezikuthandako .
Wayifundela yesi - 2 Korinte 1 : 3 4 , ethi : ‘ UYise wesirhawu noZimu wenduduzo yoke , osiduduza kizo zoke iinhlupheko zethu . ’
UJehova nguye ohlele isihlengo khona abantu abalalelako bazokutjhaphuluka esonweni nekufeni .
▪ “ Okhamba nabahlakaniphileko uzokuhlakanipha , kodwana oberegelana neendlhayela kuzomkhambela kumbi . ” — IZIYEMA 13 : 20 .
Singacabanga ngendlela uPowula nabakhambisani bakhe ebebazizwa ngayo ngoLukasi “ udorhodere othandekako , ” nomtloli wencwadi yezEnzo , njengombana bekahlala abatlhogomela ngezokwelatjhwa . — Kol .
Iingidi zeemtjhado ephumelelako zitjengisa lokho .
Ngaphezu kwakho koke , ithabo lethu lisekelwe ebuhlotjeni bethu noZimu .
Ngakelinye ihlangothi , ungazizwa ufuna ukubeka umlinganakho umlandu .
Kuthi abanye bethu basaphila ipilo engcono ngebanga lokuthi abaqalani nokutlhoriswa bunqopha .
Msinyana ngemva kwalokho , ngebanga lehlelo lethelevitjhinelo , indodanami yathathwa .
Msinyana ngemva kwalokho ngatjhiya idorobha elikhulu lapho bengihlala khona begodu ngafudukela edorobheni la bekuphayona khona uSandra . ”
Ngomnyaka ka - 50 uPowula nabakhambisani bakhe bavakatjhela eFilipi .
Ukuthobeka nokuzikhakhazisa akuhlangani njengamanzi ne - oli .
Ngokwesibonelo , nasithanda uZimu nabomakhelwana bethu , lokho kuzosenza sifune ukutjhumayela ‘ ivangeli lomBuso . ’
Ibandla lamaKrestu wokuthoma lahlangabezana namuphi umraro , begodu kwenzekani ngomnyaka ka - 1919 ?
Namhlanjesi , thina sinokunengi okudlula lokho u - Abrahamu agade anakho .
Eminye yemifanekiso le isiphorofido namkha ifanekisela okuthileko .
( Num . 12 : 3 ) Inceku ethobekileko le yaphathiswa umthwalo omkhulu esitjhabeni sakwa - Israyeli .
Kusebaleni - ke ukuthi akafuni sicabange ngokuziphatha okumbi ngokwamabhayi .
Sikhuluma nje mina sengihlala edorobheli leBelgorod begodu abazalwana balapha bayangisekela tle .
UJunia uthi : “ Ngokuvamileko kuyasiza abantu baba nawe nangezinye iinkhathi , ingasi ngeenkhathi ezikhethekileko kwaphela . ”
Kibe umpostoli uPowula wamane watlola bona ubaba ( namkha umma ) kufuze akhulise untwana efundisweni kaZimu , lokho bekuzabe kuyinto eliqiniso nehlakaniphileko .
UThimothi bekangasilivila .
UDavida begade anabanye abangani ebebathembekile begodu banaye qobe , ngitjho nalokha aqalene neenkhathi ezibudisi .
INARHA ABELETHELWA KIYO : DOMINICAN REPUBLIC
UDavida : Kuyakarisa lokho .
Kodwana zikhona izinto elisizo ongazenza .
( IRhubo 78 : 69 ) Lokhu kutjho khona - ke bonyana umlayezo lo , utjengisa ukuthi akunamniningwana namunye wamaledere la womThetho ongeze wazaliseka .
U - Israyeli ongokomfanekiso “ nezinye izimvu ” babambisene kimuphi umsebenzi ?
Kodwana bekufuze silifunde ilimeli silizwisise ngombana besinabantu abambalwa esibafundisa iBhayibheli .
Khona kubayini kufuze silihlwengise qobe ?
Ithando “ linyamezelela koke , ” kungakhathaliseki ukuthi senziwa izinto ezimbi , siyatlhoriswa , namkha silingwa ngananyana yini .
Isibonelo , umnganakhe uMariya nekathela amafutha abizako ehloko neenyaweni zakhe , abanye babuza : “ Kudlalelwani ngamafutha kangaka na ? ”
UCristina , iphayona lesikhathi esizeleko , uthi : “ Kanengi ngizifumana ngimonakalela abanye .
Iinthombe nemigwalo kaPowula eseencwadini zethu sekumane kuziinthombe ezitjengisa ukuthi kungenzeka bekanjani .
Kwathi ngesikhathi uSathana atjengisa uJesu “ yoke imibuso yephasi , ” kungenzeka wasebenzisa umbono , ngebanga lokuthi , angeze kwakghonakala ukubona imibuso yoke ujame kinanyana ngiyiphi intaba ekhona ephasinapha .
Yini esiyifunda kuRerhobhowamu ekukhulunywa ngaye eBhayibhelini ?
Nokho , nasi into okufuze siyitjheje : Sebenzisa nanyana ngisiphi isiluleko kuwe ngokwakho , ingasi kumlinganakho .
Ungalithathi kancani ilungelo lakho lokusebenzisana noZimu ngokutjhumayela ngebizo lakhe nangomBuswakhe nange unethuba lokwenza njalo .
Bebasolo benza njalo bekwaba ziinyanga ezimbili .
FEBHERBARI 25 , 2013 – MATJHI 3 , 2013
U - Adamu no - Eva nabantwana babo boke bebanelungelo lokuthabela ukuphila isiphelani .
Njengombana amabharasi agedlisa umakhiwo , kunjalo nangokukwatelana nokubambana ngehliziyo omunye nakenze umtjhapho . Kungakhula bekube sezingeni lokuthi kube budisi ukulibalela .
Nokho ngezinye iinkhathi bengibhalelwa ukuthabisa uJehova .
4 : 20 - 24 ; 1 Pit .
Ngemva kwesikhathi , ngathola ukuthi abommaba bebakhukhuthisa iincwadi zaboFakazi eJarimani ebeyibuswa maNazi lokha umsebenzi wokutjhumayela uvinjelwe ngaphambi kwePi yePhasi yesiBili .
Nasekabatjela ngezinto abazozithola emaphethelweni womsebenzi lo wathi : “ Kwamambala ngiqinisile ngithi kini : Loyo okholwa kimi , uzakwenza ngitjho izinto ezikulu kunalezi ngombana ngiya kuBaba . ”
Omunye nakakutjela ukuthi eminye yemithetho urhulumende ayibekileko kufuze isuswe namkha itjhugululwe , akukafuzi umsekele kilokho nofana uphikisane naye .
Zikhona izinto ezingasi ngezamambala ozilandelako ?
Kwathi nanyana sekudlule iminyaka ema - 350 ngemva komThwalela , uNowa bekasolo ayibambile . ( Gen .
Iminyaka emine ngaphambi kokubelethwa kwami , ababelethi bami bahlangana neenthunywa zevangeli zamaMormon .
Nanyana gade aserholweni , bekaqiniseka bona uZimu uzomsiza .
9 : 9 ) Ngikho iBhayibheli lithi kwabatjhadileko : “ Ningagodlelani , ngaphandle kwalokha nanivumeleneko begodu kungekwesikhatjhana . ”
Ngikho sithi kunabantu okusafuze bathuthukele ekuvuthweni .
Yini okufuze siyikhumbule ?
Kungaba kuhle nange anganivakatjhela nomndenakho .
15 : 2 , 3 ; Jak .
IRhalani 146 : 8 ligandelela inzuzo ezidlula zoke yokukhamba endleleni yokulunga .
Soke siyazi ukuthi abangani esikholwa nabo baphila nesono .
Ngomporofidi wakhe u - Isaya , uJehova watjela ama - Israyeli wathi : “ Imicabango yenu akusiyo imicabango yami , neendlela zami akusizo iindlela zenu . ”
Ngizwa ubuhlungu njalo ngakhumbula amezwi kaJesu athi : “ Nibusisiwe lokha nabanithukako , banizuma bebakhulume koke okumbi ngani . . .
Emihleni kaJesu abantwana bebabiza abobababo ngokuthi Abba .
10 , 11 . ( a ) Kubayini uJesu atjela abafundi bakhe ‘ bona bayelele ’ ?
Inga - kghani ngiyawaberegisa amathuba engiwafumanako bona ngenzele uJehova okungeziweko ? ’
Usibangela ukutlhaga ?
Abangiphetheko balwa nami bebalinga ukungikatelela bona ngingalisi .
Nokho , ngokuqinisekileko njengomKrestu awufuni ukwenza into enjalo .
Thina besifisa ngeenhliziyo zethu zoke bona sihlale sinje , siyindoda nomfazi bekube phakade .
Kwathi ngo - 1916 wasungula isiqhema sama - Wolf Cubs ( namkha ama - Cub Scouts ) ebeyingeyabasana abalingana nami .
Umpostoli uPowula wanikela buphi ubufakazi bekholo nesibindi ?
Mbala , uJehova usebenzisa umoyakhe ocwengileko ukuqinisa iinceku zakhe bona zikghodlhelele itjhutjhiso nokobana zenze ngokuhlakanipha nezivelelwa budisi .
4 : 2 - 8 .
( Funda 2 Korinte 13 : 5 . )
Usebenzisa igunyelo ukufikelela umnqopho kaJehova ngokuvumelana nesikhathi uZimu asihlelileko .
NeliZwini lakaZimu imbala , ukufa kubizwa ‘ ngesitha . ’
UJesu wakhuluma ngesiqhema sesibili sabathembekileko abazokufumana umvuzo womBuso wezulwini .
Imininingwana le ivumelana nalokho esikufunda eMitlolweni .
Isabula ebeyisetjenziswa lisotja elimRoma ngesikhathi uPowula nakatlola incwadakhe , beyimasenthimitha ama - 50 ubude begodu beyenzelwe abantu abalwa basemaduzelana .
Ilangelo libizwa nangokuthi siphelo , njengombana kucocwe ngalo esihlokweni sangaphandle somagazini lo .
Nanyana iqakathekile ekonzwenethu , itjiseko iyodwa ayikaneli bona idosele abantu kuZimu .
Nokho , kuthiwani nengabe iimzamakho ayitheli msinyana ?
Abafazi labo abamaKrestu bekhulu lokuthoma kungenzeka bebangacabangi bona balandela uSathana , kodwana izenzo zabo bezitjengisa lokho .
UJobhi bakalungile begodu anesirhawu ekuberegelaneni neenceku zakhe .
Khuyini ukuphambukiswa ?
Kwamambala , umhlangano loyo wenza amatjhuguluko .
Kodwana omunye nomunye ngedlhego lakhe : Kuzokuthoma uKrestu ntangi bese kuthi nabuyako , kuvuke labo abangebakhe .
Lokho kuqakathekile nakithi namhlanjesi ngombana siphila esikhathini lapho ukukholwa nethemba kuyindlala khona .
20 : 6 .
Intaba , engepumalanga yeJerusalema , ihlukana ngomqondo wokobana uJehova uhloma obunye ububusi , kodwana obungaphasana .
Uthi : “ Ukubona ithabo labazalwana nabodadabo kwangenza ngafuna ukuba nokuphila okunjengekwabo . ”
1 , 2 . ( a ) Kubayini uSathana anganaso isirhawu ngabazesiweko ‘ nangezinye izimvu ’ ?
Kodwana ungacabangi ukuthi kuSathana bekamqala njengesiputuputwana esihle somntwana , ngombana bekazi kuhle ukuthi umntwana loyo nakakhulako uzokuba nguMesiya othenjisiweko .
UJehova watjengisa lokho ebekatlhayela ngakho nakathi : “ Akusikuhle bona umuntu ahlale yedwa .
UZimu weqiniso Mbumbi wazo zoke izinto .
Kubayini kungathatha isikhathi ukufikelela esiquntweni emhlanganweni wabadala ?
Bekakhuluma ngamaKrestu awapha ngesihle amanye amakholwa atlhagileko .
Kghani uyamvumela uJehova akhulume nawe malanga woke ngokufunda iliZwi lakhe iBhayibheli ?
Umnqopho lo ulihlathulula kuhle ithando lakaZimu begodu angeze watshwila nanini .
Isigeso sisasibona nanamhlanjesi , nanyana sikhamba sihluka nje — kuye ngendawo ohlala kiyo .
Ngokungafani nokuphila kwethu kwagadesi okufitjhani , uZimu uhlathululwa ‘ njengolikhaya lethu lokuphephela eenzukulwaneni ngeenzukulwana . ’
Nonina lika - Anna ngokufanako wamfundisa iindlela eziberegisekako .
Godu , landelela begodu uzisebenzise ekuphileni kwakho kwaqobe langa izinto ozifundako .
Kubayini kuqakathekile ukucabanga ngokuzinikela kwethu kuJehova ?
Wabuye watlola wathi : “ Ngitjengisa ukukholwa kwakho ngaphandle kwemisebenzi , nami ngemisebenzami ngizakutjengisa ukukholwa kwami . ”
UJobhi no - Abrahama bebanaliphi ilwazi ngokufa nevuko ?
Waya kilabo egade baphethe umnyanya wathi kibo : “ Yenzani nanyana yini akutjhoko . ”
Ngabuyela eJapani ngayokuhlela kuhle izinto zami .
U - Esewu khenge abuthokozele ubuzibulo bakhe begodu khenge atjengise bona umthanda kwamambala uZimu .
Phela - ke incwadi enamakhasi ama - 128 le inguphambana nazo .
Abanye babantu abatjha baraga iimfundo zeBhayibheli , lokho kwenza abantu baphile ipilo engcono khulu .
Kwangathi soke singaba khona ngokuthokoza okudephileko ngelungiselelo lakaJehova uZimu ngobupristi bobukhosi obuzokuzuzisa soke isintu .
Ukuhlola kwethu kutjengise ukuthi ama - Easter akasiwo umnyanya wobuKrestu .
Kangangani - ke ngathi esinesono , kithi kuqakatheke khulu bona sibalekele ukuzikhukhumeza nokuzibona ngasuthi siqakatheke ukudlula abanye !
Namhlanjesi , abantu basebenzisa amandla lawo ngokwenza iimbulawo eziseqophelweni eliphezulu beba morose nebhoduluko .
Godu sizokuqala nemithwalo esinayo njengemindeni nebandla malungana nabathandekako bethu esebaluphele .
1 , 2 . ( a ) Bekuzokuba njani ukuphila kube iBhayibheli belingekho ?
( Esithombeni esingesinceleni ) UKaren
( AbaKhokheli 10 : 7 , 8 ) Ngaphezu kwalokho , UJafta bekangathelelani amanzi nabafowabo nabarholi bakwa - Israyeli .
UJehova yena - ke umdlula kude khulu umbumbi omumuntu .
Kodwana ngiyayithanda iBethel kangangobana angifuni ukubeka ilungelo lami engozini ngokutjhada . ”
19 : 7 , NW .
Ezinye iimfuneko zikuTitosi 1 : 5 - 9 noJakopo 3 : 17 , 18 .
Wangezelela ngokuthi : “ Ngemva kwalokho , ubaselwa mazizo welaka , uzisole , udane , bewuphelelwe nalithemba . ”
Kwesinye isikhathi ngifisa kwanga ngingatjho amahlaya kuhlekwe , namkha ngizwisiswe nengikhulumako , kodwana kuyabhala . ”
Ngokufanako , nanyana ngikuphi ukulindelwa okungasikho malungana nokuphela akulitjhugululi iqiniso lokobana le , ‘ mimihla yokuphela . ’ — 2 Thimothi 3 : 1 .
Nesihlangana nomuntu kokuthoma , sivame ukwakha iimbono esekelwe kilokho esikuzwileko nokuhlangabezanwe nakho kwethu kwesikhathi esidlulileko lokho okungahlangani ndawo nomuntu ophambi kwethu .
( b ) Ungaqalana njani neenlingo ngokuphumelelako ?
Singakubalekela njani ukucabanga njengabantu abangamlotjhiko uZimu ?
UWillie waphendula wathi , “ Ubabakho usesirhogweni ! ”
Qala bona kuqakatheke kangangani - ke ukuzivumela bona unqotjhiswe liLizwi lakaZimu nokuba nombono ofaneleko ngemali !
Ithando lisinikela umfutho wokuragela phambili sitjhumayela nanyana siqalene neentjhijilo
Wena ungakghona na ukubamukela nanyana yakho indlu ingasiyikulu ?
emafwini wezulwini kusiza onjengendodana yomuntu [ uJesu ] ; wanikelwa ilungelo lokungena koMdala Wamalanga [ uJehova uZimu ] , bamtjhideza phambi Kwakhe .
Iimbonelo Ezaba Nomthelela Ekuphileni Kwami
Indlela Ongaphunyurha Ngayo Emimoyeni
( Isa . 55 : 8 , 9 ) Phela yena akasihlolisisi ngombana afuna ukusigwebela imitjhaphwethu , kunalokho usihlolisisa ngombana afuna okuthileko okuhle kithi .
Umrholo wethu usenza sikghone ukuphila ipilo ebulula , nokuthi sikghone ukukhonza ePhilippines umnyaka woke . ”
Indaba le izwakala kuhle - ke nje , ukwenza isifungo kuZimu akusiyinto yokudlala .
Ngokukhamba kwesikhathi uJehova wacocisana neengilozi zakhe malungana nendlela engcono khulu yokukhohlisa u - Arhabi bona ahlanganyele epini egade izokuqeda ukuphila kwakhe .
Sabuza ujenerali ukuthi , “ Alo kuzokwenzekani nakungenzeka sibonwe masotja karhulumende , angekhe na acabange ukuthi nathi siyahlanganyela ipini le ? ”
Nangakusasa kwakhona nabaqeda ukugoma ukudla kwekuseni , uLana waphendula eminye imibuzo yeBhayibheli .
Khumbula ukuthi linjani ingomuso lezoni ezingatjhugulukiko .
( Funda yoku - 1 Samuweli 1 : 4 - 8 . )
Kwamambala , amanye wamatjhuguluko namkha izehlakalo , zenzeka ngeenkhathi ezihlukahlukeneko — kuthi lezo ezivezwe ebhoksini zenzeka esikhathini esidlulileko ngezinga elithileko .
Azimisele ukubulunga ukuthembeka kuZimu , uJobhi wagegeda ukuqala umfazi bekube kulapho arhalela ukuya naye emsemeni .
IBhayibheli limadanisa umlayezo lo nesinanja , nalithi : “ Isinanja esineengidija ezinobudisi obungaba makhilogremu amatjhumi amane nahlanu , sawulukela phezu kwabantu sehla ezulwini . Abantu bahlambalaza uZimu ngebanga lobuhlungu besinanja ngombana besisabeka kokufa . ” — IsAmbulo 16 : 21 .
Nanyana sikuthabela ukuhlangana nokucoca nabafowethu nabodadwethu abasivakatjheleko , kungaba kungabahloniphi nasizokubaphatha ngasuthi baziintatanyiswa .
Kusukela mhlokho , abakhulileko abanengi baba nomthelela omuhle kimi hlangana neenkhathi ezihlukahlukeneko zokuphila kwami .
OKUBUZWAKO NGABOFAKAZI BAKAJEHOVA — Kubayini Nibizwa Ngokuthi NiboFakazi BakaJehova ?
Bese kwathi ngo - 2005 banikelwa imvumo , yokobana batjhugululele iBhayibheli emalimini IsiThala ebesele sitjhugululelwa kiwo .
AboFakazi bakaJehova basaragela phambili nokutjhumayela umlayezo loyo , balingisa neendlela ebezisetjenziswa nguJesu nabafundi bakhe .
‘ UZimu obonako ’ ukuqalile nawe .
Amadoda la ahlukana nabafazi bobutjha babo benzelela ukuthi batjhade nabafazi abancazana abanye bebaze batjhade nabafazi abalotjha abosingazimu .
Ngalokho - ke , khuyini ezokurhelebha umphathi weSifundo seSithalasokulinda bona amede kuhle ukukhulumela kwakhe nokwebandla bonyana umhlangano ube ngowakhako kibo boke ?
Kodwana umukghwa loyo wamtshwenya ngombana bekangasabacabangeli abanye . ”
Kodwana uJesu uqalise kuZimu njengoBaba bese waqalisa kuye njengeNdodana .
Kuthe bona uMzalwana uRutherford ayifunde ivaliwe ukuthi umzalwana lo usesenamavunda , wamtjela emehlweni ukuthi uDeveli udlala ngaye .
25 : 34 - 40 .
Bona lokho kuliqiniso namtjhana awa , umthandazo kaJesu osibonelo — ngezinye iinkhathi obizwa ngokobana Mthandazo weKosi namtjhana uBabethu wezulwini — uhlangana neminye abantu abangayizwisisiko .
UJulia oneminyaka eli - 16 uthi , “ Ngiphatha iincwadi zehlangano esikhwameni sami sesikolo begodu ngiyabalalelisisa abantwana engifunda nabo nabahlathulula ngezinto abazikholelwako .
Ezinye izimvu nje zakha inengi ‘ lomhlambi owodwa ’ ngaphasi koburholi bakaKrestu .
Ukuphela kwendlela esingawela ngayo eqhingeneli kuqala ikonzwethu kuZimu njengephaliswano , ukuzimadanisa nabanye .
Ngelinye ilanga walalela njengombana umjikelezi akhulumela uJakopo 4 : 17 : “ Okwaziko ukwenza okuhle ahluleke kukwenza , uyona . ”
Kodwana , kuhle ukuthi inengi lamaKrestu atjhadileko liyazithola iinsombululo zemiraro leyo ngombana livumela uZimu alinqophise .
Njengombana amalanga athusako lawo adosa , afikelela eemvekeni , abaziinyanga , wenza njani bona angalahlekelwa lithemba ?
Ngiziphi ezinye iinzuzo zokungarhabi ukutjhada ?
Kusasele amatjhumi weminyaka ngaphambi kuka - 1914 , abakhulekeli bakaJehova bamemezela eentjhabeni bona ukuphela ‘ kweenkhathi ezibekiweko zeentjhaba ’ kuzokufika ngomnyaka loyo nokobana iphasi lizokungena esikhathini semiraro eemkhulu .
Isiporofido sakaSamuweli sazaliseka uDavidi asesemncani .
Njengesokana , uLeo bekanekareko kezesayensi .
Godu ngokurhuwelela kwakhe njengombana enza , uJesu wazalisa iRhalani 22 : 1 .
Ngemva kweminyaka eyi - 250 , isikhumbeso besesibhabhuke njengento engasathenjwa . .
Ekuthomeni kwelanga lesithathu lokubumba , uJehova wasebenzisa umoyakhe ocwengileko ukuveza indawo eyomileko , mhlamunye asebenzisa amandla wemvelo wephasi ngokwalo ukusunduza iinarhakazi bona zivele elwandle egade ligubuzese iphasi loke . ( Gen .
Ngaphezu kwalokho , wathumela iinthunywa zakhe bona zikhuthaze abantu kizo zoke iindawo bonyana babe nokuthula naye nekusakghonekako .
IRhubo 37 : 9 lithi : “ Abarhuluphela [ “ kuJehova , ” NW ] bazakuzuza inarha . ”
Ngiyamthokoza uJesu ngokunginikela ilwazi elidephileko ngoZimu ongivikelako . ”
2 IBhayibhili iyakulahla na ukuzithabisa ngokomseme ?
Ipikiswano leyo yararululwa njani ?
Isibawo sami samukeleka , ngathoma ukuberegisa ihlelo elitjheli ngenyanga eyodwa . ”
Nomsa : Nalokho godu bekusitjhijilo esikhulu .
( b ) Singafundani nasingahlolisisa iRhubo 147 ?
Ngiziphi izinto esingasebenzela ukuthuthuka kizo , begodu ziqakatheke ngani ?
Ngombana iminyaka eminengi , wasaba begodu walalela uJehova , owambusisa khulu .
UJesu wathi : “ Ngombana uZimu walithanda kangako iphasi [ lesintu ] , wabe wanikela ngeNdodana yakhe ekukuphela kwayo , khona kuzakuthi kiloyo okholwa ngiyo . . . abe nobuphilo obungapheliko . ”
Ngokwesibonelo , kufuze sihlale sizikhakhazisa ngokuba boFakazi bakaJehova .
Yaporofida : “ Mhlana iNdodana yoMuntu izako ngobukhosi bayo neengilozi zoke , izahlala esihlalweni sayo sobukhosi .
Umbono Ofaneleko Ngemitjhapho , No . 6
Ilandiswa nguSara van der Monde
Nangifika eWolweni , ngahlangana nabanye aboFakazi nabo ebebaphikiswa mindenabo .
Abadala angekhe bakwenzele isiqunto , kodwana bangakusiza uthathe igadango elizokuthabisa isikhathi esinabileko . — 2 Kor .
Ngaduduzwa kukwazi bona bekangangiqali njengotjhodako ngombana ngingakatjhadi .
Kubayini kufuze silwele ukuphila ipilo abantu abayiqala njengepilo evamileko , ephasini esekuseduze bona liphele ?
Ngisiphi isiyeleliso esisifumana kuLukasi 21 : 34 , 35 ?
Nasingahlala sicabanga ngalokho uKrestu azosenzela khona , siyazibasela , khona sizokutjela abanye ngakho . — IRhubo 45 : 1 ; 49 : 3 .
Kwenzeka njani lokho kubantu ekhebathandana ?
Kwamambala uMariya waba nokwaneliseka okukhulu khulu nakacabangela ilungelo uJehova amnikele lona ekuphileni — ilungelo lokukhulisa nokubandula indodana eyaba nguMesiya .
Akekho umKrestu okufuze aqale ikonzo enjalo njengengakaqakatheki namtjhana eyehlisa isithunzi , ngombana iligugu khulu kuJehova . — Heb .
Nasele sibuhlubulile ubuntu obudala , kufuze simbathe ubuntu obutjha .
Thandazela ukuhlakanipha .
Ubunye babantu bakaZimu budumisa uJehova .
Liqiniso , umlinganakho kungenzeka angabi nazo iimfanelo ezithileko nofana amakghono umlinganakho wokuthoma ebeka nawo .
Kulalela siphi isiluleko okungasisiza sibalekele ‘ ukuhlubuka silandele uSathana ’ ?
Kodwana ngebanga lokuthi siyamthemba begodu siyamthanda , qobe ngaphambi kobana sithathe isiqunto sifuna isizo lakhe besenze koke okusemandlenethu bona sifumane bona yena uJehova ucabangani ngesiqunto esizosenza .
Indaba kaDiyotrefe le ikubeka ebaleni ukuthi abantu abazikhakhazisako nabarharhela iinkhundla bangaba nomthelela oyingozi khulu ebandleni .
Msebenzi ebekawenza asese sephasini .
Khewucabange ngobunye godu ubujamo obubudisi .
Ngokwesibonelo , eCanada , pheze amadoda amathathu kwalitjhumi akhabetjhwa namtjhana atlhoriswa balingani bawo .
Kubayini ‘ nezinye izimvu ’ singazuza emfanekisweni wamatlawu alitjhumi ?
Nakaqala emva abe akazisoli nakancani uthi : “ UJehova bekangipha koke engikutlhogako , ngesikhathi engikutlhoga ngaso . ”
( a ) Ngiziphi izenzakalo ezenzeka ngaphambi komhlangano owahlelwa nguJesu ?
Abanengi abakhe basuswa ekuhlanganyeleni nje bavuma ngokutjhaphulukileko bona amagadango aqinileko athathwa mindenabo nabangani babo abasiza bona balise iimtjhapho yabo .
Ngokufanako , ihliziyo yomKrestu engokomfanekiso itlhoga ukuvikelwa emandleni wesono .
UJehova wabusisa uRute ngendoda nangendodana .
UBongani : Utjhejile na ukuthi iveseli ligandelela ukupha okufuze omunye nomunye akulindele ukukwamukela ?
Njengombana sifundile , sifuna ukukhumbula kuhle bona kubayini kufuze sibe nehlonipho esuka ehliziyweni ngesikholwa nabo .
Besithumela neenkhokhelo eenarheni ezifuna iincwadi .
Phakathi nekhambo labo , u - Oripa wabona ukuthi kungcono abuyele ekhabo kwaMowabi .
UPowula watjengisa bona ngomoya kaZimu nomhlatjelo wesihlengo weNdodanakhe , uZimu wenza okuthileko uMthetho kaMosisi ebewungekhe ukghone ukukwenza .
Ungabasiza njani abantwabakho bona bangalitjhiyi iqiniso ?
UJehova angasisiza sitjhuguluke , senze izinto ezimthabisako .
Nesibasekela ngokuthembeka labo ababekwe bona basidose phambili , sisuke sitjengisa uJehova noJesu ukuthi siyabathokoza ngakho koke abasenzele khona .
Azange beziphathwe nasithukuthezi nofana ziphele amandla .
Okuthabisako kukobana ngokukhamba kwesikhathi udade lo walemuka bona ukucabanga kwakhe bekungakalungi begodu wenza amatjhuguluko amakhulu .
UMichael nekasesikolweni samabanga aphakamileko , umnganakhe wathoma ukufunda iBhayibhili naboFakazi BakaJehova .
Akhohlwa ukuthi uZimu nguye owatjhaphulule ebugqilini beenkolo zamala , wawanikela ithuba lokuthi amlotjhe .
ILizwi lakaZimu linjengemayini yedayimani ekhiqizako .
Abantu bakaJehova bayayisebenzisa ithekhnoloji yephaseli ekutjhumayeleni .
Nawenzela umuntu isipho akukafuzi kube yinto ekulu .
Abanye bakwata bathelwe mamanzi lokha abadala nebabatjela ngalokho okufuze basebenzele kikho .
1 : 5 - 7 , 12 - 16 ; 2 : 1 - 10 .
Singakwenza lokho ngokujwayelana neemfanelo zakhe , sizindle ngazo , begodu ngemva kwalokho sizilingise ekuphileni kwethu .
Ngiziphi iimfundo eziqakathekileko esingazifunda emitlolweni le ?
UJehova unjengomrabho begodu uJesu unjengesiqu somuthi we - oliva ongokomfanekiso lo .
( Rhu . 83 : 3 - 5 [ 83 : 2 - 4 , NW ] ) Isizukulwana somfazi lo bekufuze sivikelwe bona singasilaphali namkha sirhayilwe .
‘ Ngebanga lokuzinikela kwabantu ngokuzithandela , akadunyiswe [ uJehova ! ] ’
Ngamezwi lawo , uZimu bekaqinisekisa uJesu bonyana izinto azenzako ziyamthabisa .
( 1 AmaKhosi 8 : 22 - 53 ) Uzabe utjhaphile nawungalibala ukuzindla ngomthandazo kaJesu osibonelo .
Uyini umnqopho wokwenza “ ilwazi leqiniso ” laziwe ?
10 , 11 . ( a ) Ukuzikhukhumeza kungabonakala njani ?
Engakubonako kwangithinta ihliziyo . ”
23 : 2 .
Khuyini okwenze amanye amaKrestu ona ?
Kodwana ulindele iinceku zakhe bona zithembele kuye ngokupheleleko — ingasi ephasini lakaSathana elidlulako . — Heb .
Ngubani odale koke lokhu ?
Lingisa isibonelo sakaJesu : Funda endleleni uJesu abandula ngayo abafundi bakhe .
Qala bona uDavidi wathaba kangangani ngokulitjalelwa isono sakhe noBhathisheba !
Ngithi abatjhumayela umlayezo olungileko , iindaba ezimnandi zomBuso .
USarah gade afuna ukunakwa , begodu gade akufumana eemfundweni zeBhayibhili zakaDaniel .
Akhenge avumele abantu ebekakhelene nabo ukuthi bamtjhentjhe .
( Genesisi 10 : 8 - 12 ) Kodwana uNowa yena khenge alise ukukholelwa kuZimu .
Ngokwesibonelo , uMsongo ka - Isaya owatholakala hlangana nemisongo yeLwandle leTswayi , uneminyaka eyi - 1 000 ukhona , mdala ukudlula eminye imitlolo ekhona .
U - Anny Mavambu , owangimukela bona ngibe yindodakwakhe naphezu koburhole bami , waba mamehlwami .
( IRhubo 37 : 37 , 38 ) “ Omsulwa ” uyamazi uJehova nendodanakhe begodu uyamlalela enze nentandwakhe .
Nasicabanga ngokukholwa kwaka - Inogo singatjhukumiseleka bona sizibuze ukuthi , iphaseli siliqala ngendlela uZimu aliqala ngayo na .
Umthetho wesivumelwano somThetho bewuqiniswa ngeengazi zesilwana ; isivumelwano esitjha sona siqiniswa ngeengazi zakaJesu ezaphalakako .
Ngapha bebafundisa ukuthi uJesu uyiNdodana kaZimu , kodwana abantu bebazi ukuthi ubulewe .
Singenza koke bona sithembele kuJehova ngokumbawa ngomthandazo asiphe amandla wokukghodlhelela . Simbawe nokuthi singaphelelwa lithabo leemfundiso zakhe .
Ababelethi abamaKrestu bangazwakalisa ukuthokoza okufanako nebabona abantwababo “ bakhamba eqinisweni . ”
Ngelanga lethu lomtjhado .
Isiphethweso besisekelwe emaphuzwini amabili .
wesibiliso ?
Begodu neembusiso zesihlengo zizokuhlala unomphela .
Ngokukhamba kwesikhathi wembulela ihlanganwakhe efaniswa nomkakhe , ukuthi uzokuthumela umuntu ‘ ozokutshidlha ’ uDeveli begodu enzele abantu abalalelako ithemba lokuthabela lokho abatjhadikazi bokuthoma elabalahlekelako , okukuphila ngokungapheliko ephasini , ebekuyihloso kaJehova yekuthomeni . — Jwa . 3 : 16 .
Akhenge alise ukuhlangana ngitjho nanyana bewatjhutjhiswa mbuso wamaRoma nabarholi bamasonto wamaJuda .
UJehova ungibusisile tle . — Rhu .
Njengombana sitjhidela khulu esikhathini sokuphela , sitlhoga khulu ukuthembela eLizwini lakaJehova .
Ngathana u - Adamu neenzukulwana zakhe bawulalela umthetho kaZimu , bebangekhe babe nesono , ngitjho nokufa imbala bengekhe kwababamba .
Sikhuthazwa bona sizidele sifumane nokwamukelwa nguJehova neembusiso asiphathele zona .
Kungatjho bona uyawazi umthwalo wefanelo oqakathekileko wokuba ngomunye waboFakazi BakaJehova .
( b ) Thina - ke sifundani kilokhu ?
Lokhu kuyinzuzo kwamambala .
Akusiziinhluthu ngokwazo , kodwana lokho ebezikujameleko , okubuhlobo obukhethekileko uSamsoni ebekanabo noJehova njengomNaziri , ebebumthombo wamandlakhe .
Okwanje angidliwa sisazelo , begodu sengingatjho bona okwanje ngiphila kamnandi .
Isiporofido esimalungana neemveke ezi - 70 zomnyaka sakubikezela lokhu . — Dan .
Nekunjalo , kutjho ukuthi uzokuvumelana nemiTlolo ngalokho ekutjhoko ngoThimothi .
Kubekwe ibhorodo elinetshwayo le JW.ORG labekwa lapho solo kwathoma ukwakhiwa , begodu libonakala lula ebantwini abadlula ngendlela leyo
Godu ngokukhanyako wathi : “ Ingasiwoke othi kimi , ‘ Kosi , Kosi ’ ozangena embusweni wezulwini , kodwana ngilabo abenza okufunwa nguBaba osezulwini .
( b ) Ngikuphi okutlhoga izandla engcenyeni yehlangano kaJehova esephasini ?
UJehova uZimu naye uyamhlulukela umfazi wokukholwa lo , uzimisele nokumvusa ephasini elitjha , epharadesi .
Ngalokho sitjengisa ithando elingasimarhamaru ngoZimu nangabomakhelwana bethu .
IKHASI 7 • IINGOMA 114 , 117
Nekaphorofida ngesiphelo uJesu wathi abantu “ bazakuyatha ngevalo ngalokho okuzokwehlela iphasi loke ngombana umkhambathi wezulu uzakunyakaziswa . ”
15 : 30 ; Eze .
Umpostoli lo wahlathulula indlela umoya kaZimu ongasiza ngayo amaKrestu ekulweni kwawo namandla wesono ukwenzela bona aphile ngokuvumelana nentando kaJehova afumane nokwamukelwa nguye .
UJehova wathi : “ Ningasilaphazi inarha eniphila kiyo ngombana iingazi ziyayisilaphaza inarha . ” — Num .
UZakhele : Iye , kungaba yintwehle leyo .
Ngesikhatheso kufuze bona amadoda la bekararekile .
Nekanikela itshwayo ‘ lokuphela kwephasi , ’ uJesu wathi : “ Abanengi . . . Bazathengisana . ”
Kufuze bona kusitjhijilo ukuba nethemba ebujamweni obunjengalobu .
Kubonakala sengathi uGidiyoni yena bekangaziqali ‘ njengengorho . ’
Nekalapho , wabulawa .
Kusisiza bona singazicabangi ngasuthi siqakatheke ukudlula abanye nasihlonitjhwako .
Ngomnyaka ka - 1473 ngaphambi kokubelethwa kwakaKrestu , isitjhaba sakwa - Israyeli bese sisenarheni yakwaMowabi silungele ukuyama uMlambo iJordani bona siye eNarheni yesiThembiso .
45 : 13 ) Ibizo lesiGirigi elitjhugululwe ngokobana “ idumo ” eBhayibhilini lidlulisela umqondo wehlonipho , ukuqakatheka nokuba ligugu .
Bengidosa emhlweni .
Bakwa - Conrow , bobane njalo baya esiKolweni seGilyadi babelwa njengeenthunywa zevangeli ePeru .
Ababelethi batjengisa ukuthi bathembela kuJehova lokha nabasebenzisa iBhayibheli ukubandula umntwana .
Isikhathi sobutjha sikhathi esihle kwamambala sokusebenzela uJehova .
Amezwi la atjengisa ukuthi bona sibe bafundi bakaKrestu , sitlhoga isizo lakaZimu .
Into le iyafana - ke nomuntu ophela amandla sekusele kancani bona afike eligweni .
3 : 1 , 2 ) Ekuthomeni bewungafunga ukuthi ayikho into engabaqeda amandla .
Abanye bangatshwenywa magulo namkha bangezwa ubuhlungu ngebanga lokuhlongakalelwa .
Kelinye ikhambo lethu bengikhamba nabangani bami abamaphayona ngekoloyami , sathi nasiseTexas safumana ingozi ikoloyami yafihlika yaphela .
SinoSandra siyathoma epilwenethu ukuthaba ngalendlela ! ”
Njengomdala odzubhulwe eengabeni ezingehla abonisa : “ Ikonzo yesimini msebenzethu oyihloko . ”
Ipi ye - Arimagedoni izoziqeda ziphele nya izipi . — IRhubo 46 : 8 , 9 .
NoJesu ngokuvuma kwakhe ukuba sihlengo , kubufakazi bokuthi uyasithanda .
Kuzakuthi mhla indaba yobukhosi bakaJehova iphenduleka kuhle , soke sizithobe ekubuseni kwakhe okulungileko .
Bayafunda ukuthi ikululekwabo ikhamba ibe nala igcina khona nokuthi iinqunto abazithathako zizokuba nomphumela , kungaba mphumela omuhle namkha kube mphumela omumbi .
Cabangela ukulandisa kwamaswaphelo okukhuluma ngoPowula encwadini yeZenzo , njengombana kutlolwe kuZenzo isahluko 28 .
6 , 7 . ( a ) UmKrestu ovuthiweko ubonakala njani ?
Tjhidela kuZimu ngokusebenzisa ibizo lakhe , ngokuthandaza kuye , ngokufunda iliZwi lakhe nangokwenza okumthabisako
Kwathi ngemva kweminyaka ema - 27 kudlule iPentekoste langomnyaka ka - 33 , abafundi bakaJesu bebangatjho bona “ ilizwi leqiniso , okutjho ivangeli ” lifikelele amaJuda nabaTjhili nakikho “ koke okudaliweko ngaphasi komthunzi welanga . ” — Kol .
Angekhe wazi indlela abantu abazokusabela ngayo emitlolweni okhethwe kuhle .
Ngokukhamba kwesikhathi wabuyela ekhaya , lapho kancanikancani ngamtlhogomela bewaba ngcono .
Qobe nyanga , amakhulu wabantu avakatjhela amatafulethu wabomagazini , siwabeka hlanu kwendawo ekhamba abantu abanengi
Yeke bebanamalungelo adlula wabazalwana babo abangasizizakhamuzi zeRoma .
“ Ilimi labahlakaniphileko liyapholisa . ” — IZIYEMA 12 : 18 .
Ithando lobuzalwana : lithando elinamandla elifunyanwa phakathi kwamalunga womndeni nofana umngani otjhidelene naye .
Bazokuhlanganisa nalabo abavuselwe ekuphileni kwephasini abazokuba nethemba lokuphila ngokungapheliko .
Uthi uninakhe obekaneminyaka ema - 86 obekarhwahlaphazwe magulo angapheliko , bekasolo atjhumayela ngomtato .
Esingakutjho kukuthi yena usibusisile ! ”
( Duteronomi 10 : 17 - 19 ) Ngitjho nanyana kunjalo , kuyakhanya bona u - Abrahama noLoti benza okungaphezu kwalokho ngokukhamba kwesikhathi okwaba yifuneko yomthetho .
Uthi : “ Akunantwembi ebengiyenza , sekukukuthi bekunezinto ebezingangiphathi kuhle .
Ngokulemuka bona ngezinye iinkhathi kuneendlela ezimbalwa ezilungileko esingakhetha kizo .
Abantu abathanda ubulungiswa balulukela ilanga lapho uJehova azokuqeda ukungabi nobulungiswa okusebantwini okubangelwe nguSathana nephasi lakhe elikhohlakelekweli .
U - Anwar wabhabhadiswa ngo - 1998 .
[ Isithombe ekhasini 14 ]
UBhowazi wamphendula ngokumnikela ihlathululo engeziweko wathi : “ Ngibikelwe koke okwenzele unosokanakho [ omfelokazi uNawomi ] . . . kwanga [ uJehova ] angakwandisela kilokho okwenzileko . ” — Rut .
Sinonakwami sizithabele tle iimbusiswezi , ngasuthi siyabhudanga !
Thina - ke kufuze sisabele njani nakasikhalimako ?
3 Iinyeleliso ZeBhayibheli Zisaqakathekile Namhlanjesi ?
Soke sinoBaba munye . ”
Banengi abantu abamsebenzela isikhathi esinengi abazizwa ngalendlela .
Kodwana angikabi ukuthola ukuthi sihlangana njani no - 1914 .
Esihlokweni sokuthoma sizokudemba yokuthi kuhlekuhle mumuntu onjani othanda uZimu .
Msinyana uZimu uzokuletha iphasi elitjha elinokulunga lelo elizokuhlalwa ngilabo abakhetha ukuthanda uZimu nabahlala nabo kwaphela . NjengeKosi kaZimu yezulwini , uJesu uzokulungisa umonakalo . ( Isa .
Kodwana bebenzani ?
Khuyini ongayenza bona ube yingcenye yekusasa elithenjisiwekwelo ?
Isiphorofido esikuDanyela isahluko 4 satlolwa bona abantu bazi ukuthi ‘ ongoPhezulu unamandla phezu kwemibuso yabantu . ’
Kubayini ilungiselelo lakaZimu lesihlengo lingelomusa begodu lingakasifaneli ?
UDavid Splane , ongomunye wesiHlopha esiBusako , wahlathulula ekulumweni elandelako bona amaKrestu weqiniso asolo ahlonipha iLizwi lakaZimu .
( Funda KwebeRoma 12 : 1 , 2 , NW ) Beregisa isikhathesi ukucabangisisa kuhle bona kubayini ukuba ngomunye waBoFakazi BakaJehova kuqakathekile kuwe .
IKHASI 23 • IINGOMA : 61 , 43
• Kufuze kwenziweni ukubulunga ukuthula nesiphathwe kumbi ?
Abadala bangasilingisa njani isibonelo sakaNerhemiya baqinise izandla zabanye ebandleni ?
Wala zoke iimbawo zendawo abazalwana ebebanethemba lokwakha kiyo .
IDrama etja le gade ilingana ne - “ Photo Drama ” — ama - awara abunane — begodu beyidlaliswa isiqephu nesiqephu ngokulandelana kobusuku .
5 : 11 , 13 ; 2 Jwa . 11 .
Kazi uJehova sele aquntile ukuthi uzolibhubhisa nini iphasi lakaSathana elikhohlakelekweli .
Abanye babantu bakaZimu abakhe basahlelwa madimoni bafumene isiphephelo kuJehova ngokubiza ibizo lakhe ngokuzwakalako .
I - The New Catholic Encyclopedia ithi : “ Ukubhajadiswa kuqakathekile bona umuntu aphuluswe .
Ukudumisana nokuba nehlonipho kuhlobene njani ?
Ngemva kobana u - Adamu azithiya amagama iinlwana , uJehova akhenge angenele , abe sibhidla mnyanya aqalele phasi ikululeko ka - Adamu yokukhetha .
Watjho atjhidela uBaba ebusweni wathi kuye , “ Uhlaleleni ungangihlahli ngetlabha wena tjhatjha ndina ! ”
UJesu wathi : “ Ngiyanitjela - yi , bona umthelisi wabuyela ekhaya elitjalelwe izono , ingasi umFarisi ; ngombana loyo naloyo ozikhulisako , uzokwehliswa , loyo naloyo ozithobako uzaphakanyiswa . ” — Luka 18 : 9 - 14 .
Inga - kghani bekakhambela ilize ?
Kubonakala kwanga uBharinabhasi walemuka bonyana uMarkosi unokungahlaliseki , waqunta bona uzombandula .
Ngaphezu kwalokho , “ ithando liyabekezela ” begodu “ linesisa . . . alibibhi imilandu . ”
Nabathoma ikhambo labo lemangweni , uMosi watjelwa bona ‘ akhethe [ amadoda ] anekghono , asaba uZimu , athembekileko nazonda ukufunjathiswa bese uwabeka bonyana abe ziinduna . ’
13 : 30 , 38 , 41 .
10 Iinkhathi Ezibhedere Zitjhidele !
Njengombana umdala amlalela , kwakhanya bona umzalwana lo usesenethando elidephileko ngoJehova .
Njengombana kwaba khona amaKrestu asindako ngesikhathi kubhujiswa iJerusalema , nanje kuzakuba ‘ nesiqubuthu esikhulu ’ esizokusinda nakufika ihlekelele yephasi loke .
Khulukhulu nasisakhulako .
UMesiya uzokuhlatjwa , kodwana amathambo wakhe ngeze aphulwe .
Kunalokho kuzakhe kube nesikhathi sokukhokha umoya nakuphela ukuhlaselwa kokuthoma .
( Phawula ngesithombe esisekhasini 21 . )
Akhucabange nganangu uMzalwana uW .
Isibonelo salokho nguKim .
Njengekosana , wafundiswa “ koke ukuhlakanipha kweGibhide . ”
Ubuntu bethu njengeenkhonzi ezimaKrestu bulungiswa emihlanganweni yethu , ngitjho njengombana singabawa umuntu othungako bona asilungisele izambatho zethu bona siqaleke ngcono .
Yenza abantwabakho bazizwe ngendlela efanako , batjele qobe uthi “ ngiyanithanda . ”
Kungakhathaliseki ukuthi baphakathi kwabantu namkha babodwa , amadoda kufuze ahlale abatjela amagama amnandi abafazi bawo , kucace ukuthi baligugu kangangani kiwo . ( IzA .
( IzAga 1 : 8 ) Nanenza ukukhulekela komndeni , basize bathande ukufunda ngoJehova nangeBhayibheli .
Immangaliso zakaJesu bezitjengisani ?
Akusibo boke abanethemba lezulwini abayingcenye ‘ yenceku ethembekileko nehlakaniphileko . ’
Umpostoli uPowula watlolela amaJuda wangesikhathi sakhe ebekabhalelwa kukwenza ngokwalokho akufundisako , wathi : “ Alo - ke , wena ofundisa abanye kubayini ungazifundisi wena na ? ”
Singasilingisa njani isibonelo sama - Israyeli aphendukako ?
Iyini Indima Kababa ?
Ilifa lethu elingokomoya lisivikela engozini yokutjhebisana namadimoni ngokuzithandela , ngombana siyazi ukuthi uZimu wazilahla izenzo zeBhabhiloni zokusebenzelana nemimoya . ( Isa .
“ Kancanikancani ngathoma ukutjheja bona kunoBaba onguZimu onesirhawu . ”
9 , 10 . ( a ) Bobani ngokukhethekileko esifuna ukuhlala sithembekile kibo ?
Kuyakhanya - ke ukuthi ikambiso le yokungatjhadi ayikagunyazwa nguZimu begodu amaKrestu nakafuna ukutjhada angenza njalo .
Ukubalekela lokho , kufuze sibe nesikhathi esinengi senza imisebenzi yomBuso kaZimu .
Sazi njani ukuthi uZimu akakasidaleli ukuthi sigandelelane ngemali ?
9 - 11 . ( a ) Ngibuphi ubujamo obumaphorodlha abanye abangaqalana nabo ?
Isikolo sendawo sinabantwana abanengi kangangobana uVictor kwafuze enzele indodakazakhe ideske bona ikwazi ukuya esikolweni .
Kwathi umnyaka ungakapheli nokuphela , isibilesi sabona isiqhema esincani siba libandla elinabarhuweleli abama - 24 .
( a ) KwebeGalatiya 6 : 4 isikhuthaza bona senzeni ?
3 : 12 , 13 ) Njengombana siziindalwa ezihlakaniphileko siyawazi umnqopho kaZimu ngathi .
Isimu ingakusiza njani bona uqinise ukukholwa kwakho ?
Kghani lokhu sekutjho ukuthi iingilozi azibasizi abantu ?
Bengihlala ngizizwa ngamukelekile . ”
Ukukholwa ngehliziywakhe yoke ukuthi “ iphasi neenkanuko zalo kuyadlula ; kodwana loyo owenza intando kaZimu unokuphila okungapheliko . ”
U - Asa noJehotjhafathi
Kuneenzathu ezintathu nanzi .
( IRhubo 92 : 13 - 15 ; [ 92 : 12 - 14 , NW ] ) Ukungabi nepilo kuhle kwakanakwakhe kwamphungulela isikhathi sokulotjha uZimu , kodwana akhenge kumqedele ithabo lakhe .
Siba bangani abatjhidelene khulu begodu sithabele ukuba ndawonye .
Yeke ummoya bewungena hlangana neengodwezo .
• Gidiyoni ?
( Rhu . 115 : 16 ) Ngapha usinikela okuya ngethunjini kunye nezinye izinto ezisiphilisako .
54 : 17 .
Ngahlela umhlangano omkhulu endaweni okuculelwa kiyo i - opera .
Njengombana kanengi bekwenzeka , ikoloyi msinyana yaphuka , saragela phambili sakhamba ngeenyawo .
Iinceku zakaZimu ezithembekileko zingalindela na bona uZimu avuse abantu abahlongakeleko esikhathini esizako ?
USathana utjhwile na bona unamandla ukudlula uZimu ?
Imilando le iqinisa ukukholwa kwethu , begodu ifakazela ukuthi zoke iinthembiso zakaZimu zizokufezeka nakanjani ! .
Nesala izenzo ezinjalo , abanye babangani neenhlobo zethu bangahlekisa ngathi namtjhana basiphikise .
Bengineembuzo eemnengi ngalokho ebengikufunda .
Ngemva komhlangano loyo isiHlopha esiBusako saqunta ukuthi woke umuntu omtjhugululi weencwadi zethu akabandulwe .
Ngathi ngiseLondon ngahlangana no - Albert Schroeder obekafundisa esiKolweni seGiliyadi , kamva owaba lilunga lesiHlopha esiBusako .
Siyini isisombululo ?
Watjhabalalisa iSodoma neGomora noFaro namabuthwakhe .
13 : 1 , 7 .
Bazosilalela na isinqophiso sakaJehova esikhanyako ?
Nanyana kunjalo , akukafaneli ukukhuthaza ukusetjenziswa kwemikhiqizo yezepilo nofana iimonyo ngaphambi nangemva kwemihlangano eWolweni lomBuso nofana emihlanganweni emincani nofana yesigodi .
UJehova wambusisa uSara ngokukholwa kwakhe
Lokha nangineenyanga ezisithandathu ubudala , ubabami wahlongakala , okwatjhiya umma nemisebenzi eminengi okufuze ayitlhogomele .
Athembe ukuthi nakaphenduka ngeqiniso uJehova uzomlibalela , abe amsize nokuthi aphile nemiphumela yalokho akwenzileko .
Iphuluso isame ekubizeni ibizo lakaJehova ngekholo , kodwana abantu angeze bakghone ukwenza njalo nesingatjhumayeliko kibo .
Umzalwana uNsomba wahlongakala ngesikhathi kusatlolwa isihlokwesi aneminyaka ayi - 83 .
Umpostoli uPowula wathi : “ UZimu uyamthanda loyo [ opha ] ngethabo . ”
Kuyavunywa ukuthi ituthuko yokulwisana nobugebengu iyabonakala kwezinye iindawo zephasi .
( a ) Ngubani okufuze adose phambili ekutjengiseni idumo ?
Abanye bangenela amajima wokwakha woMbuso .
( b ) Kubayini kuqakathekile ngobandulwako bona athembeke emsebenzini anikelwe wona ?
Ababelethi abadlulisele iimfundwezo ngokuphumelelako benze ngokuvumelana nehlelo lakaJehova lokunqophisa .
Lokho kwatjho bona amaKrestu bekufuze atjhumayele ebantwini boke ephasini .
Ubukhosi bakhe nokusindiswa kwethu kuqakatheke ngokulandelana kwakho .
Ukwenza lokhu kuzosisiza sibe nomoya womrhalani owathi : “ Qala bona ngiwuthanda kangangani umthetho wakho !
Yeke , kghani uSathana bekathembe bona uzomlinga ngepilo ehle ebekazoyithola kuFaro namkha ku - Abhimeleki ?
Bese sizitjela ukuthi ngebanga lalokho esikukholelwako , ukuhlanganyela kwethu emnyanyeni loyo kungaziphatha kabuhlungu iinhlobo zethu , kuhlazise nalabo abamenyiweko .
Nakukutjhumayela khona angekhe sakulisa ngombana sinesibindi .
UJEHOVA UZIMU , Mthomi womtjhado , ngokuqinisekileko kufuze simhloniphe .
Into ekufuze yenziwe yintanga etja kubekezela , akukafuzi iphele ihliziyo nayingakaphathiswa imisebenzi eminengi .
“ Unganyefisi Izandla Zakho , ” Sept .
ngesikhatjhana esincani .
UJorge wathi angakuthabela ukufunda nathi iBhayibheli .
Emalangeni ama - 40 , uJesu wabonakala kubafundi bakhe , aqinisa ikholo labo begodu ababhincela umsebenzi omkhulukazi wokutjhumayela obegade ubalindele .
Inga - kghani ngiqala ukuba mnene njengetshwayo lokuba buthakathaka namkha lokuba namandla ?
7 “ Thembela KuJehova , Wenze Okulungileko ”
UBABA nomma babonana kokuthoma ngo - 1919 emHlanganweni wabaFundi beBhayibheli ebewuse - Cedar Point , e - Ohio , e - U.S.A .
Kwamva abafundi batjhidela kuJesu bambuza : “ Sibangelwe yini singakghoni ukuqotha umoya omumbi lo ? ”
Ubayini umphumela nasilawulwa ( a ) sisono ?
Bona ufumane imininingwana engeziweko , qala isahluko 2 sencwadi le , egadangiswa boFakazi bakaJehova
Singakutjengisa njani ukuqiniseka kwethu bona isiphelo sizakufika ingasikade ?
Ipendulo yeBhayibheli ngu - awa .
Iingazi zemvana ebezifafazwa emagosenini weminyango nemalendleleni bezisindisa ipilo yabantu .
Ungalindela bona iimbholwezo zibuthelelane ngokweembala yazo — ezihlaza ndawonye , ezisarulani ndawonye nezinye ngokufanako ?
UJehova uyasisiza bona ‘ simlotjhe sibambisene . ’ ( Zef .
Sobabili sathoma ukuphayona ngomhlaka 1 Novemba 1947 .
Iimbonelo zeMitlolo zitjengisa bona uJehova udlulisela umusa wakhe wethando — ithando lamambala — kilabo esele banobuhlobo naye .
11 : 13 .
