Hobane’ng ?
Joang ?
Joang ?
Ha ho mohla e kileng ea eba ’ nete .
E !
F .
Che .
H .
Hobane’ng ?
*
Ho thoe’ng ka uena ?
E .
Phello ebile efe ?
Nahana ka likotsi tse latelang :
Ha etsahala’ng ?
Mohlomong ha ho joalo .
R .
Che !
Che !
Che !
Ho ka ’ na ha se be joalo .
Nahana ka mehlala e seng mekae .
Che .
A re nahaneng mehlala e ’ maloa .
Sena se bolela’ng ?
Che !
A re boneng .
Ke tla mo etsetsa mothusi , motlatsi oa hae . ”
Hobane’ng ?
Phello ebile efe ?
4
2
Joale u lokela ho etsa joang ?
Leha nyenyane .
“ Bonang !
Re tseba seo joang ?
Ha ho le joalo , neng ?
Tsebo .
Thuto ?
Na le uena oa tšoaneleha ?
Empa hobane’ng ?
Phoso e hlahile kae ?
Ke seoa sefe ?
Ka ho hlakileng ha ho joalo .
Le hanyenyane !
Sehlooho se latelang se tla hlalosa .
Phello ebile efe ?
Sena se bolela’ng ?
Re ka etsa seo joang ?
Uena u nahana eng ?
Seo ke ’ nete joang ?
Ka tsela efe ?
Ho hang ha ho bonolo !
Hlokomela mehlala ena e ’ maloa .
Mabitso a fetotsoe .
Ntlha ea bohlokoa ke efe ?
Molao oo ke o moholo oa pele .
Thuto .
E re ke hlalose .
Mabitso a mang a fetotsoe .
Jesu o itse : “ Rata oa heno joalo ka ha u ithata . ”
Empa ho na le ho eketsehileng .
Nahana ka mohlala ona .
Ke hobane’ng ha ho le joalo ?
Hoa tšoana le kajeno .
Hobane letsoho la hao le ne le le boima ho ’ na nyene le bosiu . ”
Mabitso a mang a fetotsoe sehloohong sena .
Ke joang re ka etsang see ?
NAHANA ka pono ena .
Ke hobane’ng ha see e le sa bohlokoa hakaale ?
O ile a thusoa ke eng ?
Ena ke eona taelo e khōlō ka ho fetisisa le ea pele . ”
Lethathamo la Tse ka Hare
Ho hlile ho joalo !
Ke hobane’ng ha see e le sa bohlokoa ?
Empa hokae ?
Ho thoe’ng ka rōna ?
3
Nahana ka se latelang .
Tharollo e ile ea e - ba efe ?
Bona buka ea Bibele — Lentsoe la Molimo Kapa la Motho ? , e hatisitsoeng ke Lipaki Tsa Jehova .
Bibele ha e bolele .
E hatisitsoeng ke Lipaki Tsa Jehova empa hona joale ha e sa hatisoa .
Se ke ua tela !
Re tseba joang ?
U NAHANA JOANG ?
Ho feta moo , le se ke la bitsa mang kapa mang ntat’a lōna lefatšeng , kaha Ntat’a lōna o mong , Oa leholimo .
Etsa lipatlisiso .
E na le melemo efe ?
Re ka tseba see joang ?
1
Hlalosa .
Ba ne ba tla etsa’ng ?
SEHLOOHO SE SEKOAHELONG
( Sheba tlas’a LITHUTO TSA BIBELE > LIPOTSO TSA BIBELE LIA ARAJOA )
Jehova ke lebitso la Molimo le hlahang ka Bibeleng .
Thato ea hao e ke e etsahale lefatšeng , joalokaha e etsahala leholimong . ”
Bibele e re “ booatla bo tlameletsoe pelong ea moshanyana . ”
© 2016 Watch Tower Bible and Tract Society of Pennsylvania
Makasine ena ha e rekisoe .
Ho hatisoa ha eona ke karolo ea mosebetsi oa ho ruta Bibele o etsoang lefatšeng lohle o tšehetsoang ka menehelo ea boithatelo .
Ha u batla ho ntša monehelo , kena ho www.jw.org / st .
Moo NW e tlang ka mor’a taba e qotsitsoeng , seo se bontša hore phetolelo e tsoa ho New World Translation of the Holy Scriptures — With References ea puo ea Senyesemane .
“ Ho tšoenngoa ke lipelaelo ka pelong ea motho ho tla etsa hore e thulame , empa lentsoe le molemo le etsa hore e thabe . ”
5
© 2017 Watch Tower Bible and Tract Society of Pennsylvania
RATA BATHO
12 , 13 .
17 , 18 .
6 , 7 .
8 , 9 .
14 , 15 .
19 , 20 .
Re ka ithuta eng tlalehong ee ?
( Bala Ba - Heberu 11 : 8 - 12 . )
( Bala Ba - Heberu 11 : 17 - 19 . )
1 , 2 .
3 , 4 .
9 , 10 .
15 , 16 .
7 , 8 .
Bontša .
18 , 19 .
20 , 21 .
Fana ka mehlala .
16 , 17 .
5 , 6 .
10 , 11 .
2 , 3 .
Fana ka mohlala .
13 , 14 .
11 , 12 .
Ke uena ea nang le mantsoe a bophelo bo sa feleng . ”
Le ke ke la sebeletsa Molimo le Leruo . ”
Joale , itlhahlobe hore na u ka arabela lipotso tse latelang :
( b ) Re tla buisana ka eng sehloohong se latelang ?
1 - 3 .
( Bona mantsoe a botlaaseng ba leqephe . )
E tla ba tlhohonolofatso e kaakang !
Ka morero ofe ?
Seo se akarelletsa eng ?
4 , 5 .
Motho a ka nketsa’ng ? ”
( b ) Ho phahama lipotso life ?
Kena , thabong ea morena oa hao . ”
O ne a tla etsa’ng ?
( b ) Re tla hlahloba lipotso life ?
11 - 13 .
Na u e mong oa bona ?
Ke ne ke tla etsa joang ?
17 - 19 .
Ba ne ba batla ho kholiseha hore kea tseba kamoo qeto ea ka e tebileng ka teng .
Ho thoe’ng ka uena ka bouena ?
Jesu o itse : “ Ha ho motho ea ka tlang ho ’ na , ha a sa huloe ke Ntate ea nthomileng . ”
Ke lebaka le leholo hakaakang la nyakallo !
Sehloohong se latelang ho tla tšohloa eng ?
Re tla tšohla lipotso life ?
O ile a etsa eng ?
Ke rata ho ba har’a ba fihlang pele Holong ea ’ Muso , ’ me ke tlohe le ba ho qetela , haeba ho khoneha .
Re ithuta eng ?
( b ) Re tla hlahloba eng sehloohong se latelang ?
Empa ho ile ha latela eng ?
Re tla tšohla eng sehloohong se latelang ?
Empa boiteko boo bo ne bo tšoaneleha .
O ile a folisa lifofu , liritsa , balepera le lithōlō .
6 - 8 .
Empa e moholo har’a lōna e lokela ho ba mosebeletsi oa lōna .
Re tla hlahloba eng sehloohong se latelang ?
8 - 10 .
Bakreste - ’ moho le ’ na ba ntšehelitse ’ me sena se ntšelisitse haholo .
Le rōna re ka etsa se tšoanang .
U ke ke ua lumella ea tšepahalang oa hao hore a bone sekoti . ”
Re etsa seo joang ?
Ka sebele o ile a se fumana .
3 : 14 .
A re hlahlobeng litsela tse tharo .
3 : 17 .
3 : 15 .
3 : 10 .
2 : 2 .
2 : 7 .
3 : 18 .
( b ) Ho tla tšohloa eng sehloohong see ?
5 : 12 .
□ Ho etsahala’ng ka rōna ha re e - shoa ?
6 : 4 .
8 : 10 .
( b ) Joale re tla tšohla lipotso life ?
Ke eng e tla re thusa ho mamella ?
2 : 15 .
4 : 16 .
4 : 4 .
4 : 5 .
15 : 4 .
Re tla tšohla eng sehloohong se latelang ?
4 : 18 .
5 : 8 .
13 : 4 .
4 : 13 .
4 : 1 - 7 .
4 : 12 .
1 : 3 .
“ Molimo ke lerato . ”
Ke afe maqheka ao ?
5 : 1 .
2 : 12 .
4 : 11 .
5 : 5 .
2 : 4 .
3 : 13 .
2 : 3 .
4 : 6 , 7 .
3 : 16 .
12 : 1 .
28 : 19 , 20 .
23 : 14 .
3 : 5 , 6 .
2 : 3 , 4 .
6 : 10 .
1 : 5 .
1 : 24 .
7 : 9 .
▪ Ke hobane’ng ha Molimo a lumella mahlomola ?
4 : 8 .
2 : 8 .
2 : 21 .
( Bala Matheu 24 : 37 - 39 . )
2 : 17 .
10 : 24 , 25 .
13 : 17 .
6 : 33 .
41 : 10 .
Re lokela ho phelela lithapelo tsa rōna .
3 : 9 .
6 : 8 .
11 : 6 .
6 : 19 .
( Bala Baheberu 13 : 5 . )
6 : 1 .
12 : 13 .
5 : 16 .
( Bala 2 Timothea 3 : 1 - 5 , 13 . )
( Bala Pesaleme ea 40 : 8 - 10 . )
5 : 11 .
3 : 12 .
40 : 8 .
13 : 5 .
4 : 15 .
24 : 13 .
11 : 9 .
( b ) U ikemiselitse ho etsa’ng ?
6 : 13 .
( Bala Pesaleme ea 97 : 10 . )
Seo ha sea ka sa thabisa Jehova .
15 : 58 .
4 : 16 , 17 .
( b ) Ke lipotso life tse tla tšohloa sehloohong see ?
2 : 18 .
( Bala Baheberu 13 : 4 . )
3 : 1 .
10 : 31 .
( Bala Pesaleme ea 19 : 7 - 11 . )
( Bala Baefese 5 : 15 , 16 . )
( E bale . )
5 - 7 .
( Bala Matheu 13 : 52 . )
Jesu o ile a bontša joang hore o ne a rata batho ba bang ?
5 : 14 , 15 .
1 : 17 .
3 : 13 , 14 .
27 : 11 .
8 : 21 .
Moea o paka le moea oa rōna hore re bana ba Molimo . ”
1 : 20 .
ha u le tšimong ?
5 : 9 .
( Bala 2 Likronike 34 : 1 - 3 . )
• Morero oa Molimo ke ofe ka lefatše ?
( Bala 1 Timothea 6 : 17 - 19 . )
15 : 28 .
Hoa tšoana le kajeno .
6 : 9 , 10 .
9 : 7 .
( Bala Jakobo 1 : 5 - 8 . )
( Bala Baroma 15 : 7 . )
144 : 15 .
133 : 1 .
6 : 9 .
8 : 23 .
( Bala Baroma 13 : 1 , 2 . )
( Bala Jeremia 10 : 23 . )
12 : 12 .
( Bala 1 Bakorinthe 2 : 10 . )
Na Satane o nepile ?
( Bala Juda 4 . )
148 : 12 , 13 .
( Bala Genese 3 : 15 . )
( Bala 1 Bakorinthe 6 : 9 - 11 . )
48 : 17 .
28 : 20 .
Na ruri eo ke ntho e ka etsahalang ?
Re ithuta’ng ?
( Bala 2 Bakorinthe 13 : 5 . )
U ikemiselitse ho etsa’ng ?
( Bala 1 Bakorinthe 15 : 58 . )
Dorkase “ o ne a tletse liketso tse molemo le limpho tsa mohau . ”
( Bala Joshua 24 : 15 . )
Bala Matheu 6 : 33 .
1 : 22 .
( Bala Liproverbia 3 : 5 , 6 . )
( Bala Baheberu 11 : 24 - 27 . )
6 : 12 .
“ Lentsoe la Molimo lea phela ’ me le fana ka matla . ” — BAHEB .
Litemana tseo li tšoantša Lentsoe la Molimo le seipone seo ho sona re ka iponang ka tsela eo Jehova a re bonang ka eona .
Ke ile ka qala ho ipotsa hore na seo ke se bonang ka ’ na ha sea fapana le seo Jehova a se bonang na .
Qalong ke ile ka hana maikutlo ao a macha .
Ke ne ke ntse ke nka hore ke tla be ke lebella ntho e khōlō haholo haeba ke nahana hore Jehova a ka nthata .
Ke ne ke ntse ke e - na le pelaelo ea hore na ruri Jehova a ka nthata , empa ke ile ka qala ho nahana ka sehlabelo sa thekollo sa Jesu .
Joale ho ile ha re etlo ! ho ’ na hore Jehova o ’ nile a ’ mamella nako e telele , a mpontša ka litsela tse ngata hore oa nthata .
E ne eka ke ntse ke hatakela sehlabelo seo Jehova a mphileng sona ka maoto .
( Bala Bakolose 3 : 13 . )
Na u balile ka hloko limakasine tsa morao - rao tjee tsa Molula - Qhooa ?
32 Lipotso Tse Tsoang ho Babali
( Bala 2 Bakorinthe 1 : 3 , 4 . )
( Bala Tite 2 : 3 - 5 . )
( Bala Baroma 7 : 21 - 23 . )
( Bala Esaia 63 : 11 - 14 . )
31 Nalane ea Rōna
BAAHI
BAHOELETSI
( Bala Pesaleme ea 1 : 1 - 3 . )
30 Lipotso Tse Tsoang ho Babali
Re phela nakong e thabisang .
( Bala Baroma 7 : 21 - 25 . )
BO - PULA - MALIBOHO BA KAMEHLA
( Bala 2 Petrose 2 : 5 . )
( Bala Esaia 48 : 17 , 18 . )
( Bala Baefese 4 : 1 - 3 . )
LITHUTO TSA BIBELE
( Bala Baheberu 13 : 7 , 17 . )
Ka Bibeleng , lithaba li ka emela mebuso .
PALE EA BOPHELO
32 Re U Lome Tsebe ?
103 : 8 .
13 Lipotso Tse Tsoang ho Babali
Lōna bo - ntate , le se ke la khentša bana ba lōna , e le hore ba se ke ba nyahama . ”
U tšoarele batho ba bang ka bolokolohi .
NALANE EA RŌNA
Re tla tšohla’ng sehloohong see ?
( Sheba setšoantšo se qalong )
( Sheba serapa sa 7 )
( Sheba ntlha e qetellong ea sehlooho . )
( Sheba serapa sa 13 le 14 )
( Bala 2 Timothea 1 : 7 . )
Nahana ka mehlala ena e ’ meli :
Re tlil’o tšohla’ng sehloohong see ?
( Bala 1 Bathesalonika 5 : 1 - 6 . )
( Sheba serapa sa 14 )
E boetse e fumaneha ho www.jw.org / st
30 Nalane ea Rōna
16 : 24 .
( Sheba serapa sa 15 )
( Bala Luka 21 : 1 - 4 . )
( Sheba serapa sa 8 - 10 )
( Sheba serapa sa 15 le 16 )
( Sheba serapa sa 16 )
( Sheba serapa sa 11 )
( Sheba serapa sa 12 )
Re tl’o tšohla lipotso life sehloohong see ?
( Bala Pesaleme ea 32 : 8 . )
( Bala Tšenolo 14 : 6 , 7 . )
( Bala 1 Bathesalonika 2 : 13 . )
O tla ahlola ba tlaase ka ho loka , ’ me o tla fana ka khalemelo ka ho loka molemong oa ba bonolo ba lefatše . ”
Ho ka ’ na ha e - ba le mabaka a ’ maloa a seo .
Jesu o ile a re : “ Moo letlotlo la hao le leng teng , le pelo ea hao e tla ba hona teng . ”
“ Ho thaba batho bao Molimo oa bona e leng Jehova ! ” — PES .
( Sheba serapa sa 6 le 7 )
( Bala Jakobo 5 : 14 - 16 . )
Jehova ke Molimo oa ’ nete .
SEO BIBELE E SE BUANG
RE KA BOELA RA ITHUTA ENG BIBELENG ?
MAKASINE ENA ea Molula - Qhooa , e tlotlisa Jehova Molimo , ’ Musi oa bokahohle .
E khothatsa batho ka litaba tse molemo tsa hore ’ Muso oa Molimo oa leholimo o tla tloha o felisa bokhopo bohle ’ me o fetole lefatše paradeise .
E khothalletsa batho hore ba lumele ho Jesu Kreste , ea ileng a shoa e le hore re ka fumana bophelo bo sa feleng le eo hona joale a busang e le Morena oa ’ Muso oa Molimo .
Haesale makasine ena e hatisoa ho tloha ka 1879 ’ me ha e jele paate litabeng tsa lipolotiki .
Bibele ke mohloli oa litaba tsa eona .
’ Muso oa hao o ke o tle .
31 Lipotso Tse Tsoang ho Babali
1 : 16 .
LIPINA : 95 , 13
Ke mpho efe e khōlō ka ho fetisisa eo Jehova a ileng a e fa batho ka lebaka la mosa oa hae o sa tšoanelang ?
Re ka bontša joang hore ha re sa laoloa ke sebe empa re laoloa ke mosa o sa tšoanelang ?
Re fumana litlhohonolofatso life ka lebaka la mosa o sa tšoanelang oa Jehova ?
1 , 2 . ( a ) Pheta papiso ea mong’a tšimo ea morara . ( b ) Papisong ee , mong’a tšimo o bontšitse mosa o sa tšoanelang joang le ho ba seatla se bulehileng ?
Le mōna hobane ke le seatla se bulehileng ? ’ — Mat .
( Bala 2 Bakorinthe 6 : 1 . )
Ke hobane’ng ha Jehova a ile a bontša batho mosa o sa tšoanelang , hona o o bontšitse joang ?
Ho bolela’ng ho re mosa o sa tšoanelang oa Jehova ‘ o bontšitsoe ka litsela tse sa tšoaneng ’ ?
( Sheba litšoantšo tse qalong . )
Moapostola Petrose o ile a ngola a re : “ Ka tekanyo eo e mong le e mong a amohetseng mpho ka eona , le e sebelise ho sebeletsaneng joaloka batsamaisi ba khabane ba mosa o sa tšoanelang oa Molimo o bontšitsoeng ka litsela tse sa tšoaneng . ”
Mosa o sa tšoanelang oa Jehova o re tsoela molemo joang , hona re ka bontša joang hore rea o ananela ?
( Bala 1 Johanne 1 : 8 , 9 . )
Mosa o sa tšoanelang oa Molimo o re tsoela molemo joang ?
Litsela tseo Molimo a bontšang mosa o sa tšoanelang ka tsona : Tlotla ea ho bolelloa litaba tse molemo ( Sheba serapa sa 11 )
Batlotsuoa ba thusa ba “ linku tse ling ” joang hore Jehova a ba nke ba lokile ?
( Bala Daniele 12 : 3 . )
Jehova o re buletse monyetla ofe ka mosa oa hae o sa tšoanelang ?
Mosa o sa tšoanelang o ka re thusa joang “ ka nako e nepahetseng ” ?
Mosa o sa tšoanelang oa Jehova o re tsoela molemo joang ?
Re na le tšepo efe ka lebaka la mosa o sa tšoanelang oa Molimo ?
( Bala Pesaleme ea 49 : 7 , 8 . )
Bakreste ba bang ba pele ba ile ba sebelisa mosa o sa tšoanelang oa Molimo hampe joang ?
Petrose o ile a fana ka temoso efe e matla ?
Kaha Jehova o re bontšitse mosa o sa tšoanelang , re tlameha ho etsa’ng ?
Re tla bua ka mosebetsi ofe oa bohlokoa sehloohong se latelang ?

20 : 24 .
LIPINA : 101 , 84
Mosa o sa tšoanelang oa Jehova o lokela ho re susumelletsa ho etsa’ng ?
Ho boleloa ha ‘ litaba tse molemo tsa ’ muso ’ ho bontša mosa o sa tšoanelang oa Molimo joang ?
Jehova o tla bontša mosa oa hae o sa tšoanelang joang lefatšeng le lecha ?
Moapostola Pauluse o ile a bontša joang hore o ananela mosa o sa tšoanelang oa Molimo ?
KE KA nepo hore ebe moapostola Pauluse o ile a re , ‘ Mosa o sa tšoanelang oa Molimo o neng o lebile ho ’ na ha ea ka ea e - ba lefeela . ’
( Bala 1 Bakorinthe 15 : 9 , 10 . )
Pauluse o ne a filoe mosebetsi ofe o khethehileng ?
( Sheba setšoantšo se qalong . )
( Bala Baefese 3 : 5 - 8 . )
Ke hobane’ng ha re ka re ‘ litaba tse molemo tsa ’ muso ’ ke litaba tse molemo tsa “ mosa o sa tšoanelang oa Molimo ” ?
Ke joang re bolelang litaba tse molemo tsa mosa o sa tšoanelang oa Molimo ha re ruta ba bang ka thekollo ?
Ke hobane’ng ha ho hlokahala hore batho ba boelane le Molimo ?
Moapostola Johanne o ile a ngola a re : “ Ea bontšang tumelo ho Mora o na le bophelo bo sa feleng ; ea sa mameleng Mora a ke ke a bona bophelo , empa khalefo ea Molimo e sala holim’a hae . ”
9 , 10 . ( a ) Kreste o file barab’abo ba tlotsitsoeng boikarabelo bofe ?
Ke litaba life tse molemo tseo re ka li rutang batho mabapi le thapelo ?
Batho ba bangata ba tloaetse ho rapela hobane feela thapelo e ba thoba maikutlo , empa ha ba lumele hore Molimo o araba lithapelo tsa bona .
Ba lokela ho tseba hore Jehova ke Molimo ea “ Ea Utloang thapelo . ”
Mopesaleme Davida o ile a re : “ Uena Ea Utloang thapelo , batho ba nama eohle ba tla tla ho uena .
13 , 14 . ( a ) Ke tlotla efe eo batlotsuoa ba tla e thabela nakong e tlang ?
( b ) Ke mosebetsi ofe o babatsehang oo batlotsuoa ba tla o etsetsa batho ?
Jehova o tla bontša ba “ linku tse ling ” mosa o sa tšoanelang joang nakong e tlang ?
Batho ba limilione ba ileng ba shoa ba e - s’o ka ba ithuta ka Molimo , le bona ba tla tsosoa .
Ke’ng eo re lokelang ho e hopola ha re etsa mosebetsi oa boboleli ?
Re ka bontša joang hore re ananela mosa o sa tšoanelang oa Jehova ?
Bibele e re : “ Pōpo le eona e tla lokolloa bokhobeng ba ho bola ’ me e be le tokoloho e khanyang ea bana ba Molimo . ”
Ha re bolela litaba tse molemo ka cheseho , re bontša hore re ananela mosa o sa tšoanelang oa Jehova !
SETŠOANTŠO SE SEKOAHELONG :
BA BILENG TENG SEHOPOTSONG ( KA 2015 )
“ Le batle ’ muso oa [ Molimo ] le sa khaotse , ’ me lintho tsena le tla li ekeletsoa . ” — LUKA 12 : 31 .
LIPINA : 40 , 98
Phapang ke efe pakeng tsa lintho tseo re li hlokang le tseo re li batlang ?
Ke hobane’ng ha re sa lokela ho hahamalla lintho tse bonahalang ?
Ke’ng e u kholisang hore Jehova a ka khona ho u fa lintho tseo u li hlokang letsatsi le letsatsi ?
Tse ling tsa lintho tseo batho ba li batlang ke life ?
Satane o sebelisa “ takatso ea mahlo ” joang ?
Hopola temoso ena ea moapostola Johanne , e reng : “ Lefatše lea feta ’ me ho joalo le ka takatso ea lona . ”
Ho etsahala’ng ka batho ba qetang nako e ngata ba bokella lintho tse bonahalang ?
Re ithuta’ng mohlaleng oa Baruke ?
8 , 9 . ( a ) Ke hobane’ng ha re sa lokela ho tšoenyeha haholo ka lintho tseo re li hlokang ?
( b ) Jesu o ne a tseba hore batho ba hloka eng ?
Bala Matheu 6 : 25 .
Jesu o ile a re ke ntho efe e ka sehloohong eo balateli ba hae ba lokelang ho e rapella ?
Re ithuta’ng tseleng eo Jehova a hlokomelang linonyana ka eona ?
Bala Matheu 6 : 26 .
Re lokela ho talima “ linonyana tsa leholimo ka hloko . ”
Ke eng e bontšang hore re ba bohlokoa ho feta linonyana ?
Ke eng eo motho a ke keng a e etsa ka ho tšoenyeha ?
Bala Matheu 6 : 27 .
15 , 16 . ( a ) Re ithuta’ng tseleng eo Jehova a hlokomelang likhahla tsa naha ka eona ?
( Sheba setšoantšo se qalong . ) ( b ) Re lokela ho ipotsa lipotso life , hona hobane’ng ?
Bala Matheu 6 : 28 - 30 .
Ke’ng e ka ’ nang ea senya kamano ea rōna le Jehova ?
Bala Matheu 6 : 31 , 32 .
Jehova o tseba’ng ka rōna , hona o tla re etsetsa’ng ?
Ke hobane’ng ha re sa lokela ho tšoenyeha ka lintho tse ka ’ nang tsa etsahala nakong e tlang ?
Bala Matheu 6 : 34 .
( b ) U ka etsa’ng e le hore u khone ho finyella pakane ea hao ?
Ke eng e tla u thusa ho ba le kamano e ntle le Jehova ?
LIPINA : 136 , 129
tšusumetso ea Diabolose ?
moea oa lefatše ?
mefokolo ea rōna ?
Ke hobane’ng ha re lokela ho ela hloko nako le se etsahalang ?
Ke hobane’ng ha Jesu a ile a re barutuoa ba hae ‘ ba lule ba lebetse ’ ?
Ke hobane’ng ha re nka ka ho teba temoso ea Jesu ?
( a ) Ke hobane’ng ha re lumela hore hona joale Jesu oa tseba hore na Armagedone e tla tla neng ?
( b ) Le hoja re sa tsebe hore na matšoenyeho a maholo a tla qala neng , re kholisehile ka eng ?
( Bala Habakuke 2 : 1 - 3 . )
Fana ka mohlala o bontšang hore boprofeta ba Jehova bo phethahala ka nako eo a e boletseng .
Boprofeta ba Jehova bo ’ nile ba phethahala ka nako eo a e boletseng !
Ha nako e ntse e ea , Jehova o ile a re ho Abrahama : “ Tseba hore ruri peō ea hao e tla ba bajaki naheng eo e seng ea eona , e tla lokela ho ba sebeletsa , ’ me ka sebele ba tla e hlorisa ka lilemo tse makholo a mane . ”
Ke hobane’ng ha re kholisehile hore Jehova o tla sireletsa batho ba hae ?
7 , 8 . ( a ) Mosebetsi oa molebeli e ne e le ofe mehleng ea boholo - holo , hona re ithuta’ng ho see ?
( b ) Fana ka mohlala oa se ka ’ nang sa etsahala haeba balebeli ba ka robala mosebetsing .
Batho ba bangata kajeno ha ba lemohe eng ?
10 , 11 . ( a ) Ke’ng seo re lokelang ho se qoba , hona hobane’ng ?
( b ) Ke’ng e u bontšang hore Diabolose o etsa hore batho ba se ke ba ela hloko boprofeta ba Bibele ?
Ke hobane’ng ha re sa lokela ho lumella Diabolose hore a re thetse ?
Jesu o ile a re lemosa , a re : “ Le lule le [ itokisitse ] , hobane Mor’a motho o tla ka hora eo le sa nahaneng hore e ka ba eona . ”
Moea oa lefatše o ama batho joang , hona re ka o qoba joang ?
Ke temoso efe eo re e fuoang ho Luka 21 : 34 , 35 ?
( Bala Luka 21 : 34 , 35 . )
Ho ile ha etsahala’ng ka Petrose , Jakobo le Johanne , ’ me seo se ka re etsahalla joang ?
Ho Luka 21 : 36 Jesu o ile a re laela hore re etse’ng ?
( Bala Luka 21 : 36 . )
Re ka netefatsa joang hore re itokiselitse liketsahalo tse larileng ka pele ?
Mor’abo rōna e mong kopanong o ile a mpotsa hore na nka thabela ho bolella batho litaba tse molemo .
Ha re le moo morali’abo rōna e mong o ne a re tšoarela Sekolo sa Sontaha , ’ me a re ruta Bibele a sebelisa buka ea The Harp of God .
A re tlohele kahlolo ho Jehova ’ me rōna re thabele ho bolella ba bang litaba tse molemo . ”
Mor’abo rōna e mong ea hōlileng o ile a nthuta hore ka linako tse ling re lokela ho mamella e le hore ho fana ho re tlisetse thabo .
Mosali oa hae o ne a sa rate Lipaki Tsa Jehova .
Qetellong lelapa leo kaofela le ile la kolobetsoa .
Re ne re sa tsebe hore baruti ba na le tšusumetso e matla hakana .
Ke ne ke qala ho palama sekepe , kahoo ke thabile .
Ka lilemo tse hlano , re ile ra bolela litaba tse molemo lihlekehlekeng tse ka thōko moo ho se nang Lipaki .
Ba ne ba atisa ho re fa litlhapi , li - avocado le makotomane .
Hoa thabisa ho bona kamoo ba bang ba neng ba nka likabelo tsa bona ka ho teba kateng .
Ha re fihla moo ke ile ka khahloa ke morali’abo rōna oa moromuoa ea motle haholo ea bitsoang Maxine Boyd .
Ka mohlala , motseng oa Potala Pastillo , ho ne ho e - na le malapa a mabeli a Lipaki a neng a e - na le bana ba bangata ’ me ke ne ke tloaetse ho ba letsetsa lekolilo .
O ne a le mothating oa ho ea kabelong ea hae Ecuador , ’ me a re ho rōna : “ Na le ntse le nkhopola tjee ?
Nathan Knorr , ea neng a eteletse pele Lipaki Tsa Jehova ka nako eo , o ile a tla Puerto Rico .
Hamorao o ile a nkhalemela ka matla , ’ me a re ke mo phoqile .
Ntate ha aa ka a amohela ’ nete ha ’ na le ’ Mè re e amohela .
Mosali oa ka o ile a hlokahala ka 2011 .
Ke labalabela ho mo bona hape tsohong ea bafu .
Ba bang ba tla ho tla buisana le ’ na ka litaba tsa botho kapa mathata a lelapa .
Kae kapa kae moo re sebeletsang Jehova teng , re na le monyetla oa ho mo rorisa .
Pale ea bophelo ea Leonard Smith e hlaha Molula - Qhooeng oa April 15 , 2012 .
LIPINA : 36 , 11
Ke hobane’ng ha re re lenyalo ke mpho e tsoang ho Molimo ?
Ka mor’a hore Adama a etse sebe , ho bile le mathata afe manyalong ?
Ke’ng e ka thusang Mokreste ho khetha hore na o kena lenyalong kapa che ?
1 , 2 . ( a ) Lenyalo le simolohile joang ?
( b ) Banyalani ba pele ba ne ba lokela ho lemoha eng ka lenyalo ?
( Bala Genese 2 : 20 - 24 . )
Morero o ka sehloohong oa lenyalo e ne e le ofe ?
Morero o ka sehloohong oa lenyalo e ne e le ho tlatsa lefatše .
Ho ile ha etsahala’ng ka banyalani ba pele ?
Re ithuta’ng tseleng eo Adama le Eva ba ileng ba arabela Jehova ka eona ?
U ka hlalosa Genese 3 : 15 joang ?
( a ) Ho ’ nile ha etsahala’ng ka manyalo ka mor’a borabele ba Adama le Eva ?
( b ) Bibele e re banna le basali ba lokela ho etsa’ng ?
Ho ’ nile ha etsahala’ng ka lenyalo ho tloha mehleng ea Adama ho fihlela ka Moroallo ?
Jehova o ile a etsa’ng ka batho ba khopo ba mehleng ea Noe , hona re ithuta’ng ho se ileng sa ba etsahalla ?
( a ) Litsong tse ngata , ke liketso life tse neng li tloaelehile tsa boitšoaro bo bobe ?
( b ) Abrahama le Sara ba re behetse mohlala ofe o motle ?
( Bala 1 Petrose 3 : 3 - 6 . )
Molao oa Moshe o ne o sireletsa Baiseraele joang ?
( Bala Deuteronoma 7 : 3 , 4 . )
12 , 13 . ( a ) Banna ba bang ba ne ba tšoara basali ba bona joang mehleng ea Malakia ?
( b ) Kajeno , ho etsahala’ng haeba mora kapa morali oabo rōna a etsa bofebe le molekane oa motho ?
Molao o ’ nile oa phetha karolo efe ?
( a ) Bakreste ba lokela ho talima lenyalo joang ?
Jesu o ile a re’ng ka masoha ?
A boela a re : “ Empa haeba ba se na boitšoaro , ba ke ba kene lenyalong , kaha ho molemo ho kena lenyalong ho e - na le ho chesoa ke takatso . ”
18 , 19 . ( a ) Mokreste o lokela ho nyalana le motho ea joang ?
( b ) Re tlil’o tšohla eng sehloohong se latelang ?
LIPINA : 87 , 3
Molimo o file banna le basali boikarabelo bofe ?
Ke hobane’ng ha e le habohlokoa hore banyalani ba tšoarane ka lerato le ka mosa ?
Bibele e ka thusa banyalani joang ha ba e - na le mathata ?
Le hoja ka tloaelo ka letsatsi la lenyalo banyalani ba thaba , ke’ng seo ba lokelang ho se lebella ?
Banyalani ba lokela ho bontša mefuta efe ea lerato ?
Banyalani ba lokela ho ba le lerato le matla hakae ?
Pauluse o ile a re : “ Banna , le tsoele pele le rata basali ba lōna , feela joalokaha Kreste le eena a ile a rata phutheho ’ me a inehela bakeng sa eona . ”
( Bala Johanne 13 : 34 , 35 ; 15 : 12 , 13 . )
4 , 5 . ( a ) Boikarabelo ba monna ke bofe ka lapeng ?
( b ) Basali ba lokela ho talima bohlooho joang ?
( c ) Banyalani ba bang ba ile ba lokela ho etsa liphetoho life ?
Ha ke nyaloa ke ile ka tlameha ho ithuta ho itšetleha ka monna oa ka .
Ka linako tse ling ho ne ho se bonolo hakaalo , empa ho etsa lintho ka tsela ea Jehova ho re thusitse hore re momahane . ”
Joale ho thata le ho feta ha ke se ke nyetse , kaha liqeto tseo ke li etsang li ama le mosali oa ka .
Lerato e ba “ tlamo e phethahetseng ea bonngoe ” joang ha banyalani ba qabana ?
7 , 8 . ( a ) Bibele e fa banyalani keletso efe tabeng ea ho kopanela liphate ?
( b ) Ke hobane’ng ha banyalani ba lokela ho tšoarana ka mosa ?
( Bala 1 Bakorinthe 7 : 3 - 5 . )
Ha ho molekane ea tšoanetseng ho qobelloa kapa ho tlamelloa ho kopanela liphate .
Ke hobane’ng ha re sa lokela ho bontša thahasello ho batho bao e seng balekane ba rōna ?
10 , 11 . ( a ) Tlhalo e atile hakae ?
( b ) Bibele e re’ng ka karohano ?
( c ) Ke’ng e ka thusang balekane hore ba se ke ba potlakela ho arohana ?
Ke’ng e ka ’ nang ea etsa hore banyalani ba batle ho arohana ?
Ke mabaka afe a utloahalang a ka ’ nang a etsa hore banyalani ba arohane ?
Bibele e laela Bakreste bao balekane ba bona e seng barapeli ba Jehova ho etsa’ng ?
( Bala 1 Bakorinthe 7 : 12 - 14 . )
15 , 16 . ( a ) Bibele e fana ka keletso efe ho basali ba Bakreste ba nyetsoeng ke banna ba sa lumelang ?
( b ) Mokreste o lokela ho etsa’ng haeba molekane ‘ ea sa lumelang a khetha ho mo tlohela ’ ?
Moapostola Petrose o eletsa basali ba Bakreste hore ba ikokobeletse banna ba bona , “ e le hore , haeba leha e le bafe ba sa mamele lentsoe , ba ka hapuoa ka ntle ho lentsoe ka boitšoaro ba basali ba bona , kahobane e bile lipaki tse boneng ka mahlo tsa boitšoaro ba lōna bo hloekileng hammoho le tlhompho e tebileng . ”
Bibele e re : “ Haeba ea sa lumelang a tloha , a ke a tlohe ; mor’abo rōna kapa morali’abo rōna ha a bohlankeng tlas’a maemo a joalo , empa Molimo o le bitselitse khotsong . ”
Banyalani ba Bakreste ba lokela ho etelletsa eng pele ?
Ke’ng e ka thusang Bakreste hore ba atlehise manyalo a bona ?
10 : 9 . [ 1 ] ( serapeng sa 5 ) Mabitso a fetotsoe .
[ 2 ] ( serapeng sa 13 ) Sheba sehlomathiso se reng “ Bibele e Nka Tlhalo le Karohano Joang ? ” bukeng ea “ Le Ipoloke Leratong la Molimo . ”
BO - PULA - MALIBOHO
LIPINA : 45 , 70
U ka etsa’ng e le hore u hatele pele moeeng ?
U ka etsa’ng hore u se fele pelo ha u ntse u hatela pele moeeng ?
U ka ’ na ua etsa liphetoho life tse ka u thusang tšebeletsong ?
1 , 2 . ( a ) Boprofeta bo ho Esaia 60 : 22 bo phethahala joang matsatsing aa a ho qetela ?
( b ) Hona joale ho hlokahala’ng liphuthehong tsa batho ba Jehova ?
“ E MONYENYANE o tla fetoha ba sekete , ’ me ea fokolang e be sechaba se matla . ”
Ho hatela pele moeeng ho bolela’ng ho uena ?
Bala 1 Timothea 3 : 1 .
Bacha ba ka sebelisa matla a bona joang tšebeletsong ea Jehova ?
( Bala Liproverbia 20 : 29 . )
6 - 8 . ( a ) Mocha e mong o ile a thusoa ke eng ho fetola tsela eo a talimang tšebeletso ea hae ka eona , hona phello e ile ea e - ba efe ?
( b ) Re ka etsa’ng e le hore ‘ re latsoe ’ me re bone hore Jehova o molemo ’ ?
Litlhohonolofatso tsa hae li ntšusumelitse ho ikakhela ka setotsoana tšebeletsong , ’ me seo se ntlisetsa litlhohonolofatso tse eketsehileng . ”
( Bala Pesaleme ea 34 : 8 - 10 . )
Ke hobane’ng ha e le habohlokoa hore u be le moea oa ‘ ho leta ’ ?
Re lokela ho hlaolela litšoaneleho life , hona ke hobane’ng ?
Bohle ka phuthehong ba ka bontša joang hore baa tšepahala ?
U ka etsisa mohlala oa Josefa joang ha ba bang ba u tšoara ka leeme ?
U ka etsa’ng ha ba bang ba u tšoara ka leeme ?
14 , 15 . ( a ) Ke hobane’ng ha re lokela ho ‘ ela hloko ’ tsela eo re rutang ka eona ?
( b ) U ka ’ na ua etsa’ng ho ikamahanya le maemo tšimong ea heno ?
( Sheba setšoantšo se qalong le lebokose le reng , “ Na U ka Thabela ho Leka Mokhoa o Fapaneng ? ” )
Re ka etsa’ng hore re atlehe bopaking ba phatlalatsa ?
17 , 18 . ( a ) U ka thusoa ke’ng hore u be le sebete sa ho paka phatlalatsa ?
( b ) Tsela eo Davida a neng a ikutloa ka eona ka Jehova e ka u thusa joang ?
Re ile ra boela ra kōpa Lipaki tse ling hore li re hlahlelle . ”
Hona joale Eddie o thabela ho paka phatlalatsa .
( Bala 1 Timothea 4 : 15 . )
Ba tla bua ka khanya ea borena ba hao , ba tla bua ka matla a hao , hore ba tsebise bara ba batho liketso tsa [ hao ] tse matla le khanya ea bokhabane ba borena ba [ hao ] . ”
Haeba u fuoe boikarabelo ka mokhatlong oa Jehova , u ka thusa ba bang joang ?
Hona joale Venecia o re : “ Ho paka ka fono hoa atleha ! ”
Mosali oa ka o ile a hlokahala lilemong tse tharo tse fetileng , ’ me selemong se fetileng mora oa ka o ile a hlaheloa ke kotsi a ba a hlokahala . ”
Ke le ngolla tjena ka mor’a lilemo tse peli ke se ke le Mokreste - ’ moho le lōna . ”
LIPINA : 93 , 96
Ke hobane’ng ha re lokela ho thusa liithuti tsa Bibele hore li rate ho ithuta Lentsoe la Molimo ?
Re ka etsa’ng ho thusa ba bacha hore ba buisane le beng ba matlo le batho ba bang ?
Ke hobane’ng ha baholo ba lokela ho koetlisa bao e tla ba balisa ba mohlape oa Molimo ?
Ke hobane’ng ha re lokela ho koetlisa ba bang hore ba hatele pele moeeng ?
3 , 4 . ( a ) Pauluse o ile a re ho ithuta Mangolo ho amana joang le ho beha litholoana tšebeletsong ?
( b ) Re lokela ho etsa’ng pele re khothalletsa liithuti tsa rōna tsa Bibele hore li be le kemiso ea ho ithuta Bibele ?
U ka thusa seithuti sa hao joang hore se be le kemiso ea ho ithuta Bibele kamehla ?
U ka ’ na ua ipotsa , ‘ Nka koetlisa seithuti sa ka joang hore se be le kemiso ea ho ithuta Bibele kamehla ? ’
Se khothalletse ho bala tokollo e ’ ngoe le e ’ ngoe ea Molula - Qhooa le Tsoha !
( a ) U ka thusa seithuti sa hao joang hore se rate Lentsoe la Molimo ho tsoa pelong ?
( b ) Seithuti se nang le kananelo se ka ’ na sa ikutloa joang ?
Jesu o ile a koetlisa baapostola ba hae joang ?
8 , 9 . ( a ) Jesu o ne a buisana le batho joang tšebeletsong ea hae ?
( b ) Re ka thusa bahoeletsi ba bacha joang hore ba etsise mohlala oa Jesu ha ba buisana le batho ?
10 - 12 . ( a ) Jesu o ile a etsa’ng ho thusa batho ba amohetseng litaba tse molemo ?
( b ) Re ka thusa bahoeletsi ba bacha joang hore ba chorise tsebo ea bona ea ho ruta Lentsoe la Molimo ?
13 , 14 . ( a ) U ithuta’ng mehlaleng e ka Bibeleng ea ba ileng ba itella ba bang ?
( b ) U ka etsa’ng ho koetlisa bahoeletsi ba bacha le bana hore ba rate bara le barali babo bona ?
Ke hobane’ng ha e le habohlokoa hore baholo ba thuse barab’abo rōna ho hatela pele ka phuthehong ?
16 , 17 . ( a ) Pauluse o ile a etsa’ng ho koetlisa Timothea ?
( b ) Ke joang baholo ba ka koetlisang bao e tla ba balisa ba phutheho nakong e tlang ?
Ke hobane’ng ha re lokela ho thahasella ho koetlisa ba bang tšebeletsong ea Jehova ?
Ke hobane’ng ha re ka kholiseha hore boiteko ba rōna ba ho koetlisa ba bang tšebeletsong ea Jehova bo tla atleha ?
Ha le tlohela taelo ea Molimo , le khomarela neano ea batho . ” — Mar . 7 : 6 - 8 .
LIPINA : 81 , 32
Jehova o ile a matlafatsa Moshe , Asa le Nehemia joang ?
Jehova o re matlafatsa joang kajeno ?
Re ka etsa’ng ho matlafatsa bara le barali babo rōna ?
Na u ee u ikutloe ka tsela e kang ee eo morali oabo rōna a ikutloang ka eona ?
( b ) Ke’ng e ka ’ nang ea etsa hore matsoho a rōna a tepelle ?
Ka mohlala , e bua khafetsa ka letsoho .
Ke’ng e ka u susumetsang le ho u matlafatsa hore u mamelle ’ me u thabe ?
( b ) Re tlil’o tšohla eng ?
Bala Sofonia 3 : 16 , 17 .
Empa ha letsoho la Moshe le khathala ’ me le qala ho tepella , Baamaleke ba ne ba hlōla .
( b ) Molimo o ile a araba thapelo ea Nehemia joang ?
( Bala Nehemia 1 : 10 ; 2 : 17 - 20 ; 6 : 9 . )
Na u ua lumela hore Jehova o sebelisa ‘ matla a hae a maholo le letsoho la hae le matla ’ ho matlafatsa bahlanka ba hae kajeno ?
10 , 11 . ( a ) Satane o etsa’ng ho leka ho re nyahamisa ?
( b ) Jehova o sebelisa’ng ho re matlafatsa ?
O sebelisa mebuso , baeta - pele ba bolumeli le bakoenehi ho re etselletsa le ho re sokela .
13 , 14 . ( a ) Mor’abo rōna e mong o ile a matlafatsoa ke’ng ka mor’a ho shoeloa ke mosali ?
Ho rapela le ho ba le thuto ea botho ho nthusitse haholo .
Hona joale kea hlokomela hore ke habohlokoa hore motho a be le kamano e ntle le Jehova pele a hlaheloa ke mathata . ”
LIPINA : 60 , 38
Jakobo le Ragele ?
Josefa ?
Pauluse ?
Molimo o re thusa joang hore re loantše lira tsa rōna ?
O boetse o re tataisa ka lingoliloeng tse thehiloeng Bibeleng , liboka le likopano .
Re lokela ho etsa’ng e le hore re se ke ra hlōloa ke bobe ?
( b ) Re tlil’o tšohla mehlala efe ?
Ke hobane’ng ha Jakobo a ile a khona ho mamella , hona o ile a putsoa joang ?
( Bala Genese 32 : 24 - 28 . )
( Sheba serapa sa 10 le 11 )
Ke’ng e ileng ea thusa mocha e mong le morali oabo rōna hore ba loantše litakatso tse fosahetseng ?
Qetellong o re : “ Seo se nthusitse ho lemoha hore nka lula ke tšepahala .
Ke leboha Jehova haholo ka ho sebelisa mokhatlo oa hae ho re qobisa likotsi letsatsi ka leng tsamaisong ena e khopo . ”
Nka hape mohlala oa morali’abo rōna e mong oa United States .
O ile a ngola , a re : “ Ke rata ho le leboha ka ho re fa seo re se hlokang le hona ka nako e loketseng .
Hangata ke utloa eka lihlooho tsena li ngoletsoe ’ na ka ho khetheha .
E se e le lilemo joale , ke loantšana le takatso e matla ea ntho eo Jehova a e hloileng .
Ka linako tse ling , ke batla ho inehela .
Kea tseba hore Jehova o mosa ebile o oa tšoarela , empa kaha ke na le takatso ena e matla ke nka hore ha ho letho le ka nthusang .
Bothata bona bo ama ntho e ’ ngoe le e ’ ngoe eo ke e etsang . . . .
( a ) Pauluse o ne a ikutloa joang ka mathata ao a tobanang le ’ ona ?
Bala Baroma 7 : 21 - 25 .
LIPINA : 34 , 61
Re ithuta’ng Molaong oo Molimo a neng a o file Baiseraele ?
( Bala Deuteronoma 22 : 5 . )
Ke’ng e ka re thusang ho etsa liqeto tse nepahetseng ha re khetha moaparo ?
Ke neng moo ka ho khetheha re lokelang ho apara ka tsela e loketseng ?
Ke ’ nete hore liaparo tse loketseng sebakeng se seng , li ka ’ na tsa se lokele ho se seng .
Bala 1 Bakorinthe 10 : 31 .
Bala Bafilipi 2 : 4 .
( Bala 1 Bakorinthe 10 : 32 , 33 . )
Ke’ng e ka ’ na ea ameha tabeng ea hore na mor’abo rōna o hōlisa litelu kapa che ?
Molao oa Moshe o ne o laela banna hore ba hōlise litelu .
Tsela eo re aparang le ho itlhopha ka eona e lokela ho ama ba bang joang ?
LIPINA : 41 , 69
A nahana hore liithuti kaofela li lumela hore lintho li iphetotse . ”
Morali’abo rōna oa Fora eena o re : “ Matichere aa makala sekolong hore ebe ho na le bana ba ntseng ba lumela seo Bibele e se rutang . ”
Ke li balile ka makhetlo a mangata . ”
Lihlooho tseo li mpontša hore bo - rasaense ba leka ho kopitsa lintho tsa tlhaho , empa ha ba khone ho li etsisa ka ho feletseng kaha li entsoe ka tsela e rarahaneng . ”
Ke hobane’ng ha Molimo a batla hore u sebelise matla a hao a ho nahana ?
( Bala Baroma 12 : 1 , 2 ; 1 Timothea 2 : 4 . )
Ke ile ka tlameha ho nahanisisa ka se boleloang ke lijo tse neng li jeoa ka Paseka ! ”
Ke’ng e entseng hore morali’abo rōna a ikutloe ka tsela ee ?
Re ne re phelisana ka khotso , re momahane re bile re ratana . ”
Ha ba bang bona ba khaolitse ho lumela hore Molimo o teng ka lebaka la lintho tse mpe tseo malumeli a li etsang .
O phaella ka ho re : “ Ke tsota esita le kamoo lintho tse nyenyane tse phelang li rarahaneng kateng . ”
O ile a re : “ Ntlo e ’ ngoe le e ’ ngoe e hahoa ke motho ea itseng , empa ea hahileng lintho tsohle ke Molimo . ”
LIPINA : 88 , 115
Ke hobane’ng ha e le habohlokoa hore le tsebe bana ba lōna hantle ?
Ba lokela ho e hlaolela hanyane ka hanyane . ”
O mpotsa lipotso tse kang : ‘ Bibele e re’ng ka taba ee ? ’
‘ Na u ua se lumela ? ’
‘ Ke hobane’ng ha u se lumela ? ’
O batla hore ke arabe ka mantsoe a ka , eseng hore ke phete seo eena le ’ Mè ba mpoleletseng sona .
Ha ke ntse ke hōla , o batla hore ke hlalose taba ka ho pharaletseng . ”
( Bala Luka 2 : 46 . )
Ba ile ba araba lipotso tsohle tsa ka ka Bibele . ”
( Bala Deuteronoma 6 : 5 - 8 ; Luka 6 : 45 . )
Kahoo , haeba lintho tse rarahaneng tse phelang li tsoa linthong tse sa rarahanang , ke hobane’ng ha liphoofolo tsee tsa boholo - holo tsa leoatleng li ne li rarahane ka tsela eo ?
Taba eo e ile ea nkhahla haholo , ’ me ka e bolella mora oa ka . ”
A ntan’o ba kōpa hore ba mo etsetse kofi .
O re : “ Ba ile ba e etsa ka hloko .
Ha ke ba botsa hore na ke hobane’ng ha ba bile hlokolosi joalo ha ba e etsa , ba ile ba re ke hobane ba batla ho nketsetsa kofi eo ke tla e thabela .
Ke ile ka ba hlalosetsa hore Molimo le eena o ile a kopanya likhase tse sa tšoaneng ka hloko , e le hore re thabele bophelo . ”
Hona na molumo oa sefofane o tšoana le oa nonyana ha e bina ?
Joale ke mang ea bohlale , na ke moetsi oa sefofane kapa ke ’ Mōpi ea entseng linonyana ? ”
Ntate e mong o re : “ U se ke ua tsoafa ho leka litsela tse ncha . ”
Ho tloha ba sa le banyenyane haholo , ke ne ke qeta metsotso e 15 letsatsi ka leng ke ithuta le bona , ntle le ka matsatsi a liboka .
Ha nako e ntse e ea , boholo ba tsona bo ile ba arajoa libokeng kapa ha re tšoere borapeli ba lelapa le ha ke etsa thuto ea botho .
Ke kahoo e leng habohlokoa hore batsoali ba tsoele pele ho ruta bana . ”
Etsang hore bana ba lōna ba bone hore Jehova ke oa sebele ho lōna .
Ba re : “ Re boetse re bolella morali oa rōna e moholo hore a tšepe Jehova ka ho feletseng , ’ me a phathahane tšebeletsong ea ’ Muso le hore a se ke a tšoenyeha haholo .
Ha a bona lintho li raroloha , o oa hlokomela hore Jehova o oa re thusa .
Sena se matlafalitse tumelo ea hae le ho etsa hore a tšepe Bibele le ho feta . ”
Sehloohong sa pele re tl’o bona kamoo re ka matlafatsang tumelo ea rōna kateng .
Joalokaha ho boletse Thomas McLain
E reng ke le qoqele hore na ho tlile joang hore re fihle tabeng ena .
KE HLAHETSE motseng oa Wichita , Kansas , U.S.A . , ka la 10 December , 1936 , ’ me ke ’ na e moholo lapeng la bana ba bane .
Ha lesole le leng le feta ngaka eo e ile ea le hoeletsa ea re , “ Ak’u tl’o otla lekoala ke lena ! ”
Lesole leo le ne le bona hore ngaka eo e tahiloe , eaba le re ho eona , “ E ea hae u il’o robala ! ”
Ka mor’a moo ba itsamaela .
Ntate o ne a e - na le libaka tse peli tseo ho kutoang moriri ho tsona motseng oa Wichita , ’ me ngaka eo e ne e kuta ho tsona !
Ke ea le batsoali ba ka kopanong Wichita lilemong tsa bo - 1940
Jehova o ile a hlohonolofatsa boiteko ba bona ka hore ho thehoe phutheho moo .
Qetellong , morali’abo rōna ea seng a hōlile o ile a qala ho tla libokeng .
Re ile ra abeloa ho ea ba bo - pula - maliboho ba khethehileng motseng oa Walnut Ridge , Arkansas .
Eaba ka 1962 , re fumana memo ea ho ea tlelaseng ea bo37 sekolong sa Gileade .
Morali oa rōna oa pele , e leng Kimberly o ile a hlaha nakoana ka mor’a moo , oa bobeli , e leng Stephany a tla hlaha ka mor’a likhoeli tse 17 .
Re ne re tloaetse ho tsoa re il’o robala litenteng , ebe re ba le moqoqo o monate ha re orile mollo .
Re ne re atisa ho mema batho ba tšebeletsong ea nako e tletseng .
Barali ba rōna ba ne ba labalabela seo haholo .
Ba ile ba tšoha eaba baa lla ba re ba batla re ithute .
Mokhatlo oa Molimo o ile oa re thusa ho ba hōlisa e le hore ba tšabe Jehova .
Ka lekhetlo le leng ha ba etetse moo hape , Kimberly o ile a kopana le mohlankana e mong ea neng a sebetsa le Paul , e leng Brian Llewellyn .
Kahoo ba ile ba lula ba lokolohile ho fihlela ba le lilemo li 23 .
Ka nako e tšoanang , Brian le Kimberly ba ile ba amoheloa Bethele e London ’ me hamorao ba isoa Bethele e Malawi .
Letsatsi ka mor’a hore re ee Setsing sa Thupelo sa Watchtower se Patterson , Linda o ile a letsa a re tlalehela hore ’ Mè o hlokahetse .
Ha re tloha moo , ra ea Zimbabwe le Zambia .
Ka 2006 , Brian le Kimberly ba ile ba fallela haufi le rōna e le hore ba tl’o hōlisa barali ba bona ba babeli , e leng Mackenzie le Elizabeth .
Paul le Stephany ba ntse ba le Malawi , ’ me Paul ke setho sa Komiti ea Lekala .
LIPINA : 124 , 79
Ke hobane’ng ha ho ka ’ na ha hlokahala hore re fetole tsela eo re talimang balichaba ka eona ?
Re ka etsa’ng ho bontša balichaba mosa ?
Ke ne ke sa tloaela boemo ba moo ba leholimo .
Ke ile ka lla ha ke tloha boema - fofaneng ’ me ke qala ho utloa serame . ”
( Bala Exoda 23 : 9 . )
Bajuda ba buang Segerike ba ile ba korotla ka hore bahlolohali ba bona ba ne ba hlokomolohuoa .
Ebang rea elelloa kapa che , kaofela re susumetsoa ke litso tsa rōna .
( Bala 1 Petrose 1 : 22 . )
E - ba le mamello ho ba ntseng ba leka ho ikamahanya le maemo a naheng e ncha .
Qalong , re ka ’ na ra se ke ra utloisisa hantle tsela eo ba etsang lintho kapa ba nahanang ka eona .
( Sheba serapa sa 16 le 17 )
Batho ba tsoang linaheng tse ling ba ka etsisa mohlala oa Ruthe joang ?
Tabeng ea pele , o ile a bontša hore o hlompha meetlo ea naheng eo ka hore a kōpe tumello ea ho khoahlapisa .
[ 1 ] ( serapeng sa 1 ) Lebitso le fetotsoe .
LIPINA : 142 , 92
Na u e mong oa ba ntseng ba ithuta puo e ’ ngoe ?
( Bala Nehemia 13 : 23 , 24 . )
( b ) Re ka finyella sepheo sa rōna joang ?
Re lokela ho hopola hore lintho tse ling tseo re ithutang tsona ha re lokisetsa ho ea tšimong le libokeng , kapa ho ea fana ka puo ha lia tobisoa ho rōna .
Kaha kelello ea ka e amehile ka puo , seo ke se balang hase khone ho thopothela pelong ea ka .
Ke kahoo , ke iphang nako ea ho bala Bibele le lingoliloeng tse ling ka puo ea ka . ”
Muriel o re : “ O ne a tsoafa ho ea tšimong ea puo e ’ ngoe , le hoja pele a ne a thabela ho paka ka Sefora , e leng puo eo a e antseng letsoeleng . ”
Serge o re : “ Ha re hlokomela hore ha re le tlhokahalong seo se mo sitisa ho hatela pele , re ile ra etsa qeto ea ho khutlela phuthehong eo re tsoang ho eona . ”
Tiisa hore ’ nete e finyella bana ba hao pelo ( Sheba serapa sa 14 le 15 )
Empa re boetse re ba le nako ea ho itlhakisa le ea ho etsa lipapali ka Selingala , e le hore ba natefeloe ho ithuta puo eo . ”
Ikitlaelletse ho ithuta puo ea moo u lulang ’ me u arabe ka libokeng ( Sheba serapa sa 16 le 17 )
Re boetse re iketselitse pakane ea ho ea libokeng tsa Sefora hanngoe khoeling , ’ me ha re ileng phomolong re nka monyetla oo ho ea kopanong ea puo ea rōna . ”
( Bala Baroma 15 : 1 , 2 . )
Re ka bontša joang hore re rata Lentsoe la Molimo ?
LIPINA : 81 , 134
( Bala Tšenolo 21 : 3 - 6 . )
13 : 14 .
Abrahama le ba lelapa la hae ba ile ba etsa’ng hore ba lule ba le matla tumelong ?
Thapelo e ka matlafatsa tumelo ea rōna joang ?
( Bala 1 Johanne 5 : 14 , 15 . )
Baprofeta ba bang ba ile ba mamella liteko life ka lebaka la tumelo ea bona ?
Ha ba bang ba kang Elia , “ ba ile ba lelera mahoatateng le lithabeng le mahaheng le maphaong a lefatše . ”
( Bala Baheberu 12 : 3 . )
LIPINA : 54 , 125
Mohlala oa Noe o re thusa joang ho utloisisa se boleloang ke ho ba le tumelo ?
Re ka bontša joang hore re na le tumelo ?
Ke hobane’ng ha tumelo le lerato e le tsa bohlokoa ?
Baheberu 11 : 1 e hlalosa tumelo joang ?
Ua bona hore tumelo ea hae e ile ea sebetsa hammoho le mesebetsi ea hae ’ me ka mesebetsi ea hae tumelo ea hae e ile ea etsoa e phethahetseng . ”
Ka mohlala , Johanne o ile a re : “ Ea bontšang tumelo ho Mora o na le bophelo bo sa feleng ; ea sa mameleng Mora a ke ke a bona bophelo , empa khalefo ea Molimo e sala holim’a hae . ”
( Bala Luka 10 : 21 . )
Tumelo ke ea bohlokoa hakae ha e bapisoa le lerato ?
Jakobo o ile a botsa barab’abo ba batlotsuoa a re : “ Molimo o khethile mafutsana mabapi le lefatše hore e be a ruileng tumelong le majalefa a ’ muso , oo a o tšepisitseng ba mo ratang , na ha ho joalo ? ”
Ha lekhasi le hlaha ’ me le hlahisa litholoana , joale le mofoka oa bonahala . ”
LIPINA : 116 , 102
Jehova o ne a tšepisitse batho ba hae eng , hona ke hobane’ng ha tšepiso ee e ne e ikhetha ?
Na Baiseraele ba ne ba tla ke ba boele ba rapele Molimo ka tsela e amohelehang ka ho feletseng ?
Kahoo , ha ho bonahale eka batho ba Jehova ba ile ba ba botlamuoeng ba Babylona e Moholo ka 1918 .
( Bala 1 Petrose 2 : 9 , 10 . )
( Bala Matheu 13 : 24 , 25 , 37 - 39 . )
Ruri ba ne ba le botlamuoeng ba Babylona !
Na Bakreste ba ’ nete ba ne ba tla ke ba rapele Molimo ka bolokolohi le ka tsela eo a e amohelang ?
LIPINA : 101 , 93
Batlotsuoa ba ile ba lokolloa neng botlamuoeng ba Babylona ?
( Bala Tšenolo 18 : 4 . )
Liithuti Tsa Bibele li ne li cheseha !
Mor’abo rōna Rutherford o ile a re kōpa hore re lokisetse ho tšoara likopano metseng e ’ maloa e ka bophirimela ho United States , ’ me re romele libui ho ea khothatsa barab’abo rōna . ”
13 : 15 .
LIPINA : 121 , 45
Kahoo , ke lula ke lla ’ me ke khetha ho ithōlela .
Ke ikutloa ke se na thuso . ”
O ile a ’ mamela ka kutloelo - bohloko ha ke mo hlalosetsa maikutlo a ka .
’ Me a nkhopotsa lintho tse ntle tseo ke li etsang .
A boela a nkhopotsa hore Jesu o itse e mong le e mong oa rōna ke oa bohlokoa ho feta lirobele tse ngata .
Ke lula ke nahana ka temana eo , ’ me e nkama maikutlo .
Re ithuta’ng tseleng eo Jehova , Jesu le Pauluse ba ileng ba khothatsa ba bang ka eona ?
( Bala Moeklesia 4 : 9 , 10 . )
Re ithuta’ng tseleng eo Jesu a ileng a tšoara baapostola ba hae ka eona ?
Moapostola Pauluse .
Ka mor’a hore a pholletse le likarolo tseo ’ me a khothatse ba moo ka mantsoe a mangata , a kena Greece . ”
( Bala Baheberu 10 : 24 , 25 . )
( Bala 1 Bathesalonika 5 : 12 , 13 . )
Ruri a re khothatsa haholo ! ”
Andreas ea nang le bana ba babeli , o re : “ Ha u babatsa bana , u ba thusa hore ba hōle moeeng le maikutlong .
U ba nolofalletsa ho amohela keletso eo u ba fang eona .
Le hoja bana ba rōna ba tseba hore na se nepahetseng ke sefe , ba tloaela ho se etsa ha re lula re ba babatsa . ”
( Bala Luka 21 : 1 - 4 ; 2 Bakorinthe 8 : 12 . )
( Bala Tšenolo 2 : 18 , 19 . )
Ke nka hore tsela e mosa eo u buileng ka eona ha u le sethaleng le ha re ne re buisana , ke mpho e tsoang ho Jehova . ”
[ 1 ] ( serapeng sa 1 ) Mabitso a mang a fetotsoe .
LIPINA : 105 , 107
( b ) Re tlil’o tšohla eng sehloohong see ?
Liphutheho li ile tsa rua molemo joang ha li latela tataiso ea sehlopha se busang ?
Bala Liketso 16 : 4 , 5 .
( Bala 3 Johanne 9 , 10 . )
( Bala Matheu 5 : 23 , 24 ; 18 : 15 - 17 . )
LIPINA : 114 , 113
Ke ntse ke re re metsoalle . ’
Bibele e re laela hore re be teng libokeng kamehla .
Kaho .
Na u sebelisa jw.org ha u le tšimong le nakong ea borapeli ba lelapa ?
( Bala Baroma 14 : 12 . )
le bukana ea Ke Bo - mang ba Etsang Thato ea Jehova Kajeno ?
Ke hobane’ng ha re lokela ho leboha Jehova ?
Re na le mabaka a mangata a ho leboha Jehova !
Se boetse se re bontša kamoo ho ba le tšepo ho re tsoelang molemo kateng .
Joalokaha ho boletse Denton Hopkinson
Ka nako eo , ke ne ke le lilemo li robeli .
Ntate o ne a sa batle ha ’ Mè a bua le ’ na ka lintho tseo a ithutileng tsona .
Leha ho le joalo , ke ne ke batla ho tseba , ’ me ke botsa lipotso , kahoo re ne re ithuta le ’ Mè ha Ntate a le sieo lapeng .
Le ’ na ke ile ka etsa qeto ea ho inehela ho Jehova .
’ Mè o ile a re ke bue le mohlanka ho baena ( eo hona joale a seng a bitsoa molebeli oa potoloho ) .
Ka mor’a likhoeli tse ’ nè , ke ile ka qalella ho sebetsa le mor’abo rōna e mong .
Eaba ’ Mè o sebetsa le morali’abo rōna e mong phuthehong e’ngoe .
Ka 1951 , ke ile ka etsa kōpo ea ho ea Sekolong sa Bibele sa Gileade sa Watchtower .
Ha ke ntse ke le teronkong ke ile ka fumana memo ea ho ba sehlopheng sa bo22 sa Sekolo sa Gileade .
Ka mor’a moo , ke ile ka fetela sekolong South Lansing , New York .
Ke na le Janet ho se seng sa lihlekehleke tsa Philippines
Re ntse re sebeletsa ofising ea lekala ea Lipaki Tsa Jehova motseng oa Quezon
LIPINA : 38 , 7
U ka ba le khotso e tsoang ho Molimo joang ?
Phutheho e ka u thusa joang hore u fokotse ho tšoenyeha ?
( Sheba setšoantšo se qalong . ) ( b ) Re tl’o ithuta’ng sehloohong see ?
Empa re ka etsa seo joang ?
A tsoela pele ka ho re : “ Lahlela moroalo oa hao ho Jehova , O tla u tšehetsa . ”
Thapelo e ka re thusa joang ha re tšoenyehile ?
Bala Bafilipi 4 : 6 , 7 .
Le uena u ka ikutloa ka tsela ena .
( Bala Matheu 11 : 28 - 30 . )
8 - 12 .
“ Lerato , thabo , khotso . ”
“ Tiisetso , mosa , molemo . ”
“ Tumelo . ”
“ Bonolo , boitšoaro . ”
Jesu o ne a bolela’ng ha a re : “ Le ka mohla le se ke la tšoenyeha ” ?

BAFILIPI 1 : 10 , 11
MOEKLESIA 7 : 16
MATHEU 14 : 23
Boha pōpo ea Jehova .
PESALEME EA 104 : 24 , 25
Leka ho lula u thabile .
LIPROVERBIA 17 : 22
Ikoetlise kamehla .
1 TIMOTHEA 4 : 8
MOEKLESIA 4 : 6
( b ) Ke mehato efe eo u ka e nkang e le hore u fokotse ho tšoenyeha ?
Lebitso la hae le bolela “ KE TLA BA SEO KE TLA BA SONA . ”
Ke hobane’ng ha u ka kholiseha hore ho ba le kamano e ntle le Jehova ho ka u thusa ?
( a ) Re ka lahlela matšoenyeho a rōna ho Molimo joang ?
LIPINA : 136 , 139
Re ka kholiseha joang hore Jehova o putsa bahlanka ba hae ?
Jehova o ile a hlohonolofatsa bahlanka ba hae joang nakong e fetileng ?
Jehova o re hlohonolofatsa joang mehleng ee ?
1 , 2 . ( a ) Lerato le tumelo li amana ka tsela efe ?
Empa , ho tseba hore Jehova o tla re putsa ho re tsoela molemo joang ?
( Bala Matheu 6 : 33 . )
Jesu o ile a bontša hore balateli ba hae ba tla putsoa haeba ba itela ( Sheba serapa sa 5 )
Ka le leng moapostola Petrose o ile a botsa Jesu a re : “ Re siile lintho tsohle ’ me ra u latela ; re tla fumana eng ? ”
Thutong ea hae ea Thabeng , Jesu o ile a re : “ Thabang ’ me le tlōle ke thabo , kaha moputso oa lōna o moholo maholimong ; etsoe ba ile ba hlorisa baprofeta ka tsela eo pele ho lōna . ”
Moshe o ile a re ho Baiseraele : “ Jehova o tla le hlohonolofatsa naheng eo Jehova Molimo oa lōna a le fang eona e le lefa hore le e rue , haeba feela ruri le mamela lentsoe la Jehova Molimo oa lōna e le hore le ele hloko ho phetha litaelo tsena tsohle tseo ke le laelang tsona kajeno .
Etsoe ruri Jehova Molimo oa lōna o tla le hlohonolofatsa feela joalokaha a le tšepisitse . ”
Jehova o ile a hlohonolofatsa Josefa joang ?
Eaba o reha oa bobeli lebitso la Efraime , hobane , ho qotsa mantsoe a hae , ‘ Molimo o nkatisitse naheng ea ho sohlokeha ha ka . ’ ”
Bibele e re : “ Ka lebaka la thabo e neng e behiloe ka pel’a hae o ile a mamella thupa ea tlhokofatso , a sa natse lihlong . ”
Ha ho potang hore Jesu o ne a thabisoa ke ho halaletsa lebitso la Molimo .
Jehova o ikutloa joang ka seo re mo etsetsang sona ?

Kahoo , haeba ka lerato re thusa ba mahlomoleng , ho tšoana le ha re alima Jehova ’ me o tšepisa hore o tla re putsa .
( Bala 1 Johanne 3 : 19 , 20 . )
Re fumana mahlohonolo afe mehleng ee ?
Bahlanka ba Jehova ba ikutloa joang ka tsela eo a ba hlohonolofatsang ka eona ?
Ka mohlala , Bianca ea lulang Jeremane o re : “ Ha ke khaotse ho leboha Jehova ka tsela eo a nthusang le ho ntšehetsa ka eona .
Neng le neng ha ke tela ho itseng bakeng sa ho mo sebeletsa , o ntlhohonolofatsa ka ho menahaneng . ”
E le hore ke lule ke le matla , ke na le buka eo ke e balang khafetsa eo ho eona ke ngotseng litemana tsa Bibele le lintlha tse tsoang libukeng tsa rōna .
Buka ena ea ka ke e bitsa ‘ Mokhothatsi oa ka . ’
Ho nyahama ha rōna hona joale ke ha nakoana haeba re tsepamisa likelello litlhohonolofatsong tsa Jehova tse tlang .
Jehova o lula a ikemiselitse ho re thusa , ho sa tsotellehe maemo ao re leng ho ’ ona . ”
Leha ho le joalo , e ka ’ na eaba u hopola kamoo Jehova a ileng a u hlohonolofatsa kateng le kamoo a hlohonolofalitseng ba bang .
LIPINA : 46 , 127
Ke joang Pauluse le Bakreste ba bang ba mehleng ea hae ba ileng ba lokolloa sebeng le lefung ?
( Bala Baroma 6 : 1 , 2 ) Empa ke joang a neng a ka re ‘ ba shoele mabapi le sebe ’ le hoja ba ntse ba phela lefatšeng ?
Ke khetho efe eo e mong le e mong oa rōna a lokelang ho e etsa ?
O ile a re : “ Empa ’ na ke oa nama , ke rekisitsoe tlas’a sebe .
Ke hobane’ng ha re lokela ho tšepahala ?
( Bala Liproverbia 14 : 5 ; Baefese 4 : 25 . )
( Sheba serapa sa 19 )
LIPINA : 45 , 36
( Bala Baroma 4 : 20 - 22 . )
Bala Baroma 8 : 4 - 13 .
( Bala Liketso 18 : 2 - 4 ; 20 : 20 , 21 , 34 , 35 . )
Batho ba bangata ba etela motse oa Aveiro o ka leboea ho naha ea Portugal e le hore ba bone matamo a letsoai .
Sehloohong sena , re tla ithuta kamoo re ka ananelang mpho ea bolokolohi eo Molimo a re fileng eona , le kamoo re ka e sebelisang ka tsela e mo khahlisang .
Sehlooho sa pele se hlalosa seo boinyenyefatso bo leng sona le seo bo seng sona .
LIPINA : 133 , 63
Noe ?
Davida ?
Jehova o batla hore re sebelise bokhoni ba rona joang ?
Ho hlakile hore Jehova o batla hore re etse lintho tse tsoelang rona le ba bang molemo .
Bokhoni ba rona bo lekanyelitsoe ka tsela efe ?
( Bala Pesaleme ea 37 : 3 . )
Noe o phetse lefatšeng le neng le “ tletse pefo ” le boitšoaro bo bobe .
Ha u hanyetsoa mosebetsing oa boboleli ( Sheba serapa sa 6 - 9 )
6 , 7 . ( a ) Ke’ng seo Noe a neng a ke ke a khona ho se etsa ?
( b ) Maemo a rona a tšoana joang le a Noe ?
Le rona re phela lefatšeng le tletseng bokhopo leo re tsebang hore Jehova o tšepisitse ho le felisa .
Re ke ke ra qobella batho ho amohela “ litaba tse molemo tsa ’ Muso . ”
Seo Noe a neng a ka khona ho se etsa : Ho e - na le hore Noe a nyahamisoe ke lintho tseo a neng a ke ke a khona ho li etsa , o ile a phathahana ka lintho tseo a neng a ka khona ho li etsa .
Re ka etsisa mohlala oa Noe joang ?
Davida o ile a etsa’ng ha seo se etsahala ?
Ha u tšoenngoa ke libe tsa nakong e fetileng ( Sheba serapa sa 11 - 14 )
11 , 12 . ( a ) Ke’ng seo Davida a neng a ke ke a khona ho se etsa ka mor’a ho etsa sebe ?
Re ka ithuta’ng mohlaleng oa Davida ?
Ha u kula ( Sheba serapa sa 15 )
Re ithuta’ng mohlaleng oa Anna ?
O ne a lokela ho tlohella lintho matsohong a Jehova .
Nahana ka mor’abo rona ea bitsoang Malcolm , ea ileng a lula a tšepahala ho fihlela a shoa ka 2015 .
Ho e - na le ho tšoenyeha haholo ka lintho tseo re ke keng ra khona ho li etsa , re lokela ho nahana ka tseo re ka khonang ho li etsa . ”
( b ) U ikemiselitse ho sebelisa temana ea selemo ea 2017 joang bophelong ba hao ?
Temana ea Selemo ea 2017 : “ Tšepa Jehova ’ me U Etse se Molemo ” ​ — Pesaleme ea 37 : 3
LIPINA : 62 , 65
Bolokolohi ba ho ikhethela ke’ng ?
Re ka bontša joang hore re hlompha liqeto tsa ba bang ?
4 , 5 . ( a ) Ke mang oa pele eo Molimo a ileng a mo fa bolokolohi ba ho ikhethela , hona o ile a bo sebelisa joang ?
( b ) Ke potso efe eo re lokelang ho ipotsa eona ?
Karabo ea potso ena e tla bontša hore na re letetsoe ke bokamoso bofe .
Molimo o ile a tlisa liphoofolo ho motho hore a li rehe mabitso .
Le rona re ka khetha ho sebeletsa Jehova .
Ke’ng seo re sa lokelang ho se etsa ka mpho eo re e filoeng ea ho ikhethela ?
Nka hore u file motsoalle oa hao mpho ea bohlokoa .
Re ka qoba joang ho sebelisa bolokolohi ba rona hampe ?
( Bala 1 Petrose 2 : 16 . )
Re ithutang molao - motheong o fumanoang ho Bagalata 6 : 5 ?
Hopola molao - motheo o fumanoang ho Bagalata 6 : 5 .
U ka bontša joang hore u ananela bolokolohi boo Molimo a re fileng bona ba ho ikhethela ?
LIPINA : 38 , 69
Ke hobane’ng ha ho le bohlokoa ho inyenyefatsa ?
Ho inyenyefatsa ho akarelletsa’ng ?
( a ) Batho ba bangata ba nahana’ng ka ho ikokobetsa ?
Ho ikokobetsa kapa ho inyenyefatsa ho bolela’ng ?
( Bala Liproverbia 11 : 2 . )
Fana ka mehlala e hlahang ka Bibeleng .
Ke hobane’ng ha re lokela ho qoba ho ahlola ba bang ?
Re ka ithuta’ng mohlaleng oa Jesu ha re fuoa kabelo e ncha ?
( Sheba serapa sa 12 - 14 )
LIPINA : 48 , 95
ha re nyatsoa kapa re rorisoa ?
( Bala Mikea 6 : 8 . )
Re tlil’o tšohla eng sehloohong see ?
( Bala Bagalata 6 : 4 , 5 . )
( Bala Moeklesia 11 : 4 - 6 . )
Re lokela ho beha lithahasello tsa ba bang pele ho tsa rona .
Re ka thusoa ke’ng hore re lule re e - na le boinyenyefatso ?
LIPINA : 123 , 53
Batho ba nka mosebetsi oo ba o etsang joang ?
Ke hobane’ng ha ho le thata ho ba bang ho abela ba bang mosebetsi ?
O ile a bolella Nathane hore a re ho Davida : “ Hase uena ea tla nkahela ntlo eo ke tla lula ho eona . ”
Davida o ile a etsa’ng ha a utloa taelo eo Jehova a neng a fane ka eona ?
Bala 1 Likronike 22 : 5 .
( Bala Numere 11 : 24 - 29 . )
Che , ke lakatsa eka batho bohle ba Jehova e ne e ka ba baprofeta , hobane Jehova o ne a tla beha moea oa hae ho bona ! ”
( Bala Bafilipi 2 : 20 - 22 . )
3 Morero oa Jehova o Tla Phethahala !
Joalokaha ho boletse Douglas Guest
Ofisi ea lekala e ile ea re romella limakasine tse 800 hore re li sebelise tšimong .
Ke ile ka ruta litoropong tse kang Manaus , Belém , Fortaleza , Recife le Salvador .
Ka August 1964 re ile ra fihla Lisbon Portugal .
Ke oona feela tsela eo re ka etsang mosebetsi oo Jesu a ileng a laela barutuoa ba hae hore ba o etse e leng oa ho bolela litaba tse molemo tsa ’ Muso oa Molimo ! ”
Ka la 25 October , 2015 nakong eo ka eona sehlooho sena se neng se lokisetsoa ho ea hatisoa , Mor’abo rona Douglas Guest o ile a hlokahala a ntse a tšepahala ho Jehova .
LIPINA : 152 , 22
matlafatsoa ke moea o halalelang ?
tataisoa ke Lentsoe la Molimo ?
Ke’ng e ileng ea matlafatsa Moshe hore a etelle Iseraele pele ?
Moea o halalelang o ile oa matlafatsa banna ba khethiloeng ke Molimo .
“ Moea oa Jehova oa aparela Gideone . ”
“ Moea oa Jehova oa qala ho sebetsa ho Davida . ”
Ke hobane’ng ha Molimo a ne a batla hore batho ba hae ba hlomphe baeta - pele Iseraele ?
( Bala Baheberu 1 : 7 , 14 . )
Molao oa Molimo o ile oa tataisa Moshe joang ?
Lentsoe la Molimo le ne le tataisa baeta - pele ba hae .
Bibele ha e bua ka Molao o neng o filoe Baiseraele e re ke ‘ molao oa Moshe . ’
11 , 12 . ( a ) Joshua le marena a mang a neng a busa batho ba Molimo ba ne ba lokela ho etsa’ng ?
“ Eitse hang ha morena a utloa mantsoe a buka ea molao , kapele - pele a hahola liaparo tsa hae . ”
Ho hlakile hore ba ne ba tataisoa ke Jehova .
Ke hobane’ng ha Jehova a ne a khalemela ba bang ba baeta - pele ba batho ba hae ?
Maemong a mang , Jehova o ne a ba khalemela kapa a ba tlosa .
( Bala Matheu 23 : 10 . )
Ke’ng e bontšang hore Jesu o ne a matlafatsoa ke moea o halalelang ?
Moea o halalelang o ile oa matlafatsa Jesu .
( Sheba serapa sa 17 )
Hang ka mor’a hore Jesu a kolobetsoe , “ mangeloi a tla ’ me a qala ho mo sebeletsa . ”
Lihora tse seng kae pele ho lefu la hae , “ lengeloi le tsoang leholimong la bonahala ho eena ’ me la mo matlafatsa . ”
Jesu o ile a sebelisa Lentsoe la Molimo joang bophelong ba hae leha a ruta ?
Lentsoe la Molimo le ile la tataisa Jesu .
Ke ha lefeela hore ebe se ntse se nthapela , hobane se ruta litaelo tsa batho e le lithuto . ”
Ha ho ea molemo , haese a le mong , Molimo . ”
“ Hang - hang lengeloi la Jehova la mo otla , hobane ha aa ka a tlotlisa Molimo ; a jeoa ke libōkō ’ me a shoa . ”
Sehlooho se latelang se tla araba lipotso tsena .
Ho ka etsahala hore ebe tokomane ena ke e ngotsoeng ke Moshe ho tloha qalong .
LIPINA : 125 , 43
Ke hobane’ng ha khetho eo e ne e le ea bohlokoa ho bona le ho Jehova ?
Kaha e ne e le sehlopha se busang , ba ne ba fana ka tataiso liphuthehong tsohle . — Lik . 15 : 2 .
5 , 6 . ( a ) Moea o halalelang o ile oa thusa sehlopha se busang joang ?
( c ) Lentsoe la Molimo le ile la tataisa sehlopha se busang joang ?
Ntlha ea pele , moea o halalelang o ne o thusa sehlopha se busang .
Ntlha ea boraro , Lentsoe la Molimo le ne le tataisa sehlopha se busang .
Ke hobane’ng ha re ka lumela hore Jesu o ne a tataisa Bakreste ba mehleng ea baapostola ?
( a ) Jesu o ile a khetha “ lekhoba le tšepahalang le le masene ” neng ?
Ka 1919 , e leng lilemo tse tharo ka mor’a lefu la Mor’abo rona Russell , Jesu o ile a khetha “ lekhoba le tšepahalang le le masene . ”
Molula - Qhooa oa July 15 , 2013 o ile oa hlalosa hore “ lekhoba le tšepahalang le le masene ” ke sehlopha se senyenyane sa barab’abo rona ba batlotsuoa .
Sehlopha se busang , lilemong tsa bo - 1950
Joale ebe re ka arabela potso ea Jesu joang e reng : “ Ha e le hantle ke mang eo e leng lekhoba le tšepahalang le le masene ? ”
Moea o halalelang o thusitse Sehlopha se Busang joang ?
Ke hobane’ng ha mosebetsi oo o atleha hakaale ?
( Bala Johanne 17 : 17 . )
Re ka bontša ka tsela efe hore re hopola Sehlopha se Busang ?
Bala Baheberu 13 : 7 .
Ke hobane’ng ha u ikemiselitse ho latela Moeta - pele oa rona Jesu ?
Jesu ha aa ka a lahla balateli ba hae ha a khutlela leholimong .
’ Me o tla re tataisetsa bophelong bo sa feleng .
Ha ho moeta - pele leha e le ofe ea ka re tšepisang seo .
Ho tloha ka 1955 mokhatlo oo o ile oa bitsoa Watch Tower Bible and Tract Society of Pennsylvania .
Ea bobeli : ‘ O tla boela a re bulele tsela ea ho tsoa . ’
“ Ke o boletse ; ke tla boela ke o tlise .
LIPINA : 147 , 149
1 , 2 . ( a ) Jehova o entse hore re tsebe eng ?
MANTSOE a qalang ka Bibeleng a re’ng : “ Tšimolohong Molimo o ile a bōpa maholimo le lefatše ” a bonolo empa ke a bohlokoa .
( c ) Re tl’o bua ka lipotso life ?
’ Me ke hobane’ng ha sehlabelo sa Jesu sa thekollo e le sona se ka etsang hore morero oa Molimo o phethahale ?
Jehova ke ’ Mopi ea hlollang .
Jehova o ne a file Adama le Eva limpho life ?
( Bala Jakobo 1 : 17 . )
Molimo o ne a boetse a batla ho etsa’ng ?
Ho joalokaha eka o ne a re : ‘ Na u bolela hore ha le khone ho etsa seo le se batlang ? ’
Empa Jehova o khomarela litekanyetso tsa hae ; ha ho mohla a li fetohelang .
Ho etsahetse’ng ka bana ba Adama ?
Bala Deuteronoma 32 : 4 , 5 . )
Bala Johanne 3 : 16 .
Ke hobane’ng ha thekollo e le mpho ea bohlokoa hakaale ?
Thekollo e butse monyetla ofe ?
Jehova o ile a itela haholo e le hore a fane ka thekollo .
Jehova e tla ba “ lintho tsohle ho e mong le e mong ” neng ?
LIPINA : 148 , 109
Re ka bontša joang hore re rata lebitso la Jehova ?
Ka tsela eo re itšoarang ka eona .
( Bala 1 Petrose 1 : 15 , 16 . )
Ke hobane’ng ha Jehova a ka re nka re le ba lokileng le hoja re sa phethahala ?
O amohela barapeli ba inehelang ho eena .
Jesu o ne a bolela’ng ha a re : “ Thato ea hao e ke e etsahale ” ?
Thekollo e entse hore ho be le monyetla ofe bakeng sa bafu ?
Morero oa Molimo ka “ bongata bo boholo ” ke ofe ?
( a ) Jehova o re fa litlhohonolofatso life hona joale ?
( Bala Liketso 3 : 19 - 21 . )
Lerato la Jehova le bolela’ng ho uena ?
“ Rea tseba ’ me re lumetse lerato leo Molimo a nang le lona ho rōna .
Molimo ke lerato . ”
Na ho ka etsahala hore ka linako tse ling re fetole liqeto tseo re li entseng ?
Sehlooho sena se tla re thusa ho araba lipotso tseo .
Leha ho le joalo , Jehova o ile a hlokomela hore marena ao a ne a mo rata ka lipelo tsohle .
Na Molimo o tla nka re mo rata ka lipelo tsohle ho sa tsotellehe liphoso tseo re li etsang ?
32 Nkho ea Letsopa e Nang le Lebitso le Hlahang ka Bibeleng
Joalokaha ho boletse William Samuelson
Ntate - moholo Alfred le ntate oa ka
Re ne re lula polasing e nyenyane ka bochabela ho South Dakota .
Re ne re nka ho hlokomela mohlape le ho lema e le lintho tsa bohlokoa empa e ne e se tsona tse tlang pele bophelong .
Ka 1934 batsoali ba ka ba ile ba kolobetsoa ’ me ea e - ba Lipaki Tsa Jehova .
Ntate oa ka , Clarence , e ne e le mohlanka oa phutheho ( eo hona joale a bitsoang mohokahanyi oa sehlopha sa baholo ) phuthehong ea rona e nyenyane Conde , South Dakota .
’ Na le ausi oa ka Dorothy , re ile ra ba bahoeletsi ha re le lilemo li tšeletseng .
Ha ke le pula - maliboho ka 1952
Re ne re lula re ea likopanong tse kholo le tse nyenyane .
Bibele e re : “ Ea tsamaeang le batho ba bohlale o tla hlalefa . ” Batho ba lelapa leso ba ile ba bontša hore ba bohlale ka ho ntšehetsa ha ke ba pula - maliboho .
Dorothy le eena e ile ea e - ba pula - maliboho .
Ha ba ne ba ea liphuthehong tse pel’a heso , ka linako tse ling ba ne ba mpitsa hore ke tsamaee tšimo le bona .
Ha ke sa tsoa fihla Bethele , ke eme pel’a teraka ea polasi
Re seea - le - moeeng sa WBBR le Mor’abo rona Franz
Ke batho ba 15 kapa 20 feela ba tsoang Bethele ba ileng ba sebeletsa polasing eo .
Boholo ba rona re ne re le bacha ’ me re na le tsebo e fokolang ka mosebetsi .
Mor’abo rona Peterson o ne a ipabola mosebetsing oa hae oa Bethele le tšebeletsong ea tšimo .
’ Na le Angela le Etta Huth
’ Na le Angela ka 1975 , nakoana pele re hlahisoa thelevisheneng
Ka mor’a lilemo tse tharo , re ile ra fuoa kabelo ea ho sebeletsa Bethele .
Kea thaba ha ke kopana le liithuti tse tsoang linaheng tse fapaneng
LIPINA : 46 , 18
Ke hobane’ng ha re lokela ho hlompha Jehova le Kreste ?
Batho ba bopiloe “ ka setšoantšo sa Molimo . ”
8 , 9 . ( a ) Lipaki Tsa Jehova li talima bolaoli joang ?
( Bala 1 Timothea 5 : 17 . )
Leha e le hore le bitsoe ‘ baeta - pele , ’ kaha Moeta - pele oa lōna o mong , Kreste .
Mang kapa mang ea iphahamisang o tla kokobetsoa , ’ me mang kapa mang ea ikokobetsang o tla phahamisoa . ”
LIPINA : 81 , 70
Ke hobane’ng ha re sa lokela ho etsetsoa liqeto ke batho ba bang ?
( a ) Ke’ng e ka re thusang ho etsa liqeto ka bohlale ?
Ke’ng e ka re thusang ho etsa liqeto ka bohlale ?
( Bala Bagalata 4 : 17 . )
( Bala 2 Bakorinthe 1 : 24 . )
Kaha baholo ba rata Bakreste - ’ moho le bona , ba ba thusa hore ba iketsetse liqeto ( Sheba serapa sa 10 le 11 )
Re lokela ho etsa liqeto ka bohlale .
Baholo le bona ba lokela ho ipha nako ea ho etsa lipatlisiso .
Na lelapa la ka le tla thaba ?
Hona na ho tla bontša hore ke na le mamello le mosa ? ’
Ke hobane’ng ha Jehova a lebeletse hore re iketsetse liqeto ?
Asa , Josafate , Ezekiase , Josiase
LIPINA : 52 , 65
Ho sebeletsa Jehova ka pelo e feletseng ho bolela’ng ?
Ke morena ofeng eo u ka batlang ho mo etsisa har’a marena ao a mane , hona hobane’ng ?
Re tlo tšohla’ng ?
( Bala 2 Likronike 14 : 11 . )
Kapa u tla etsa’ng ?
Josafate mora oa Asa o ile “ a ’ na a tsamaea tseleng ea ntata’e Asa . ”
( Bala 2 Likronike 20 : 2 - 4 . )
( Bala Esaia 37 : 15 - 20 . )
( Bala 2 Marena 20 : 1 - 3 . )
( Bala 2 Likronike 34 : 18 , 19 . )
LIPINA : 11 , 61
Asa le Josafate
Ezekiase
Josiase
Ho nahanisisa ka mehlala ea marena a mane a Juda ho ka re thusa joang ?
( Bala 2 Likronike 16 : 7 - 9 . )
Re ka ithuta’ng liphosong tsa Asa ?
O utloisisa maemo a rona ’ me oa re rata .
( Bala 2 Likronike 32 : 31 . )
( Bala 2 Likronike 35 : 20 - 22 . )
Bibele e re mantsoe a Neko a ne ‘ a tsoa molomong oa Molimo . ’
Ha re nahanisiseng ka mehlala ena e hlahang ka Bibeleng ’ me re ananele sohle seo Jehova a re fileng sona !
3 “ U Phethe Boitlamo Boo u bo Etsang ”
U entse boitlamo ho Jehova ka lintho tse kae ?
Ho thoe’ng ka boitlamo ba ho inehela kapa boitlamo ba lenyalo ?
Ha re kholisehile hore re tšoeroe ka leeme , sena se ka leka tumelo , botšepehi le boikokobetso ba rona .
“ Lefatše lea feta ’ me ho joalo le ka takatso ea lona , empa ea etsang thato ea Molimo o hlola ka ho sa feleng . ” ​ — 1 JOH . 2 : 17 .
LIPINA : 134 , 24
Jehova o tla etsa’ng ka batho ba khopo le mekhatlo e tletseng bobolu ?
Bibele e re : “ Lefatše lea feta . ”
Batho ba khopo ba re ama joang ?
Jehova o tla etsa’ng ?
( Bala Pesaleme ea 37 : 10 . )
Bakeng sa hore ba tloaetseng ho etsa se kotsi ba ipate moo . ”
Ba lokileng ba tla rua lefatše , ba tla lula ho lona ka ho sa feleng . ”
“ Ba bonolo ” le “ ba lokileng ” ke bo - mang ?
Mekhatlo e tletseng bobolu e re ama joang ?
Mekhatlo e tletseng bobolu e re ama joang ?
Mekhatlo eo ea bolumeli ba bohata e tla felisoa .
( Bala Tšenolo 6 : 14 . )
Ke’ng e re kholisang hore lefatše le lecha le tla hlophiseha ?
Mekhatlo e tletseng bobolu e tla nkeloa sebaka ke’ng ?
Ka mor’a Armagedone , na ho tla ba le mokhatlo lefatšeng ?
Kahoo ‘ lefatšeng le lecha ’ ho tla ba le tlhophiso .
Ke liketso life tse mpe tse tloaelehileng moo u lulang , hona li ama uena le lelapa la hao joang ?
Liketso tse mpe li re ama joang ?
Re ithuta’ng kahlolong eo Jehova a ileng a e tlisetsa Sodoma le Gomora ?
Jehova o tla etsa’ng ka batho ba etsang liketso tse mpe ?
( Bala 2 Petrose 2 : 6 - 8 . )
Liketso tse mpe li tla nkeloa sebaka ke’ng ?
( Bala Pesaleme ea 46 : 8 , 9 . )
A felise le bofutsana .
Ke lintho life tse tla felisoa ?
Fana ka mohlala . ( b ) Re ka etsa’ng e le hore re se ke ra felisoa hammoho le lefatše lee le khopo ?
Nahana ka mehlala ena .
LIPINA : 112 , 89
Mikea 7 : 7
Liproverbia 19 : 3
Matheu 18 : 15
“ NA MOAHLOLI oa lefatše lohle a ke ke a etsa se nepahetseng ? ”
O ne a tseba hore Jehova ke mohloli oa toka le ho loka .
Tumelo ea Mokreste e ka lekoa joang ?
Rea tseba hore re tla tšoaroa ka ho hloka toka kapa leeme ke batho bao eseng Lipaki .
Nahana ka se ileng sa etsahalla Mor’abo rona Willi Diehl .
Ka 1946 , o ile a ba sehlopheng sa borobeli Sekolong sa Gileade se neng le se le New York , U.S.A .
Ka mor’a moo , e ile ea e - ba mopotolohi Switzerland .
Re tla ithuta’ng sehloohong see le se latelang ?
Sehloohong sena re tl’o bua ka se ileng sa etsahalla setloholoana sa Abrahama e leng Josefa .
10 , 11 . ( a ) Ke joang Josefa a ileng a tšoaroa ka leeme ?
Bala Genese 40 : 14 , 15 .
( Bala Matheu 5 : 23 , 24 ; 18 : 15 . )
Ha mopesaleme a bua ka “ ea tsamaeang ka mokhoa o se nang molato , ” o ile a re ke “ ea sa etselletsang ka leleme la hae .
Ha aa ka a beha Jehova molato ka boemo boo a neng a le ho bona .
Habohlokoa le ho feta ke hore ha aa ka a lumella hore liphoso tsa batho ba bang li senye kamano ea hae le Jehova .
Ke hobane’ng ha re lokela ho atamela ho Jehova le ho feta ha re tšoaroa ka leeme ka phuthehong ?
Re ka bontša joang hore re tšepa “ Moahloli oa lefatše lohle ” ?
U ka bala pale ea bophelo ba Mor’abo rona Willi Diehl ho Molula - Qhooa oa November 1 , 1991 , tlas’a sehlooho se reng , “ Jehova ke Molimo oa ka , oo ke o Tšepang . ”
BA BILENG TENG SEHOPOTSONG ( KA 2016 )
LIPINA : 63 , 59
boinehelo ba hao ?
boitlamo ba hao ba lenyalo ?
( Sheba setšoantšo se qalong . ) ( b ) Re tl’o araba lipotso life sehloohong see ?
Batho ba batlang ho phetha litšepiso tseo ba li etselitseng Jehova ba ka ba etsisa .
Ke hobane’ng ha ho phetha tšepiso eo re e etselitseng Jehova e le taba ea bohlokoa ?
Re ka ithuta’ng ka Jafeta le Anna ?
2 , 3 . ( a ) Boitlamo ke’ng ?
( b ) Mangolo a re’ng ka ho etsa boitlamo ho Molimo ?
U phethe boitlamo boo u bo etsang . ”
( a ) Ho tšepisa Molimo ntho e itseng ke taba e tebileng hakae ?
( b ) Re tl’o ithuta’ng ka Jafeta le Anna ?
Morali oa Jafeta o ne a lokela ho etsa’ng ?
( a ) Ho ne ho le thata hakae hore Jafeta a phethe seo a se tšepisitseng Molimo ?
Jafeta o ile a re : “ Ke ahlamisitse molomo oa ka ho Jehova , ’ me ha ke khone ho koeneha . ”
Ho ile ha etsahala’ng ? ( b ) Boitlamo ba Anna bo ne bo tla ama Samuele joang ?
Na u phetha boitlamo ba hao ho Jehova ?
Boinehelo ba hao ( Sheba serapa sa 10 )
Kannete u ile oa thabisa Jehova haholo .
Boitlamo ba lenyalo ( Sheba serapa sa 14 )
Boitlamo bo bong ba bohlokoa boo motho a ka bo etsang , ke ba lenyalo .
Bibele e re’ng ka ho hlalana le ho arohana ?
( Bala 1 Bakorinthe 7 : 10 , 11 . )
Banyalani ba bang ba re : “ Ho tloha ha re ne re qala ho ithuta bukana ena , maqhama a rona a lenyalo a tiile ho feta leha e le neng pele . ”
Video eo e tlile hantle ka nako !
Hona joale lenyalo la rona le atlehile . ”
18 , 19 . ( a ) Batsoali ba bangata Bakreste ba khothalletsa bana ba bona ho etsa’ng ?
( b ) Ho thoe’ng ka batho ba tšebeletsong e khethehileng ea nako e tletseng ?
Boitlamo ba tšebeletso e khethehileng ea nako e tletseng ( Sheba serapa sa 19 )
Ha se batho ba khethehileng empa tšebeletso eo ba e etsang ke eona e khethehileng .
Sheba sehlomathiso se reng “ Bibele e Nka Tlhalo le Karohano Joang ? ” bukeng ea “ Le Ipoloke Leratong la Molimo . ”
LIPINA : 150 , 10
Na Ea Matla ’ Ohle o thabisoa ke letho ka hore ebe u lokile , kapa o rua letho ka hore ebe u etsa hore tsela ea hao e be e sa tšoauoeng phoso ? ”
( b ) Baiseraele ba ile ba hlola lebotho la Jabine joang ?
( Bala Baahloli 4 : 14 - 16 . )
Molapo o phoroselang oa Kishone oa ba hohola . ”
Sheba sehlooho se reng “ Ho Tšoenyeha ka Chelete ” se hlahang ho Molula - Qhooa oa July 1 , 2015 .
LIPINA : 110 , 2
Deuteronoma 32 : 4
1 Petrose 5 : 5
Matheu 6 : 14
1 , 2 . ( a ) Nabothe le bara ba hae ba ile ba hlaheloa ke’ng ?
( b ) Sehloohong see re tl’o ithuta lintho life tsa bohlokoa mehlaleng e ka Bibeleng ?
Nabothe e ne e le monna ea joang , hona ke hobane’ng ha a ile a hana ho rekisetsa Morena Akabe serapa sa morara ?
Nabothe o ne a tšepahalla Jehova le hoja a ne a phela har’a Baiseraele ba neng ba etsisa Morena Akabe le mosali oa hae ea khopo e leng Mofumahali Jezebele .
Bala 1 Marena 21 : 1 - 3 .
O ile a mo araba ka tlhompho a re : “ Ke ho sa utloahaleng ponong ea Jehova , hore ke u fe lefa la baholo - holo ba ka . ”
Akabe o ile a ikokobetsa .
Ke hobane’ng ha ho ikokobetsa ho ne ho ka thusa ba lelapa la Nabothe le metsoalle ea hae ?
( Bala Deuteronoma 32 : 3 , 4 . )
( b ) Ho ikokobetsa ho ka re thusa joang ?
U tla etsa’ng haeba baholo ba etsa tsebiso ea qeto eo u sa lumellaneng le eona ?
Re tl’o hlahloba tlaleho efe , hona hobane’ng ?
Petrose o ile a thusoa joang , hona see se hlahisa lipotso life ?
Bala Bagalata 2 : 11 - 14 .
Na ba ne ba tla ho lumella hore ho ba khopise ?
Petrose o ile a fuoa boikarabelo bofe ka mor’a hore Jehova a mo tšoarela ?
Ho e - na le hoo , o ile a bululeloa hore a ngole libuka tse peli tsa Bibele .
3 Thusang Baphaphathehi ho ‘ Sebeletsa Jehova ka Thabo ’
Sehlooho sa bobeli se tla re thusa ho hlokomela kamoo batsoali ba baphaphathehi ba ka sebelisang melao - motheo ea Bibele kateng ha ba etsa liqeto tse tla tsoela bana ba bona molemo .
LIPINA : 84 , 73
Re ile ra bona ha batho ba thunyana ’ me ba bang ba baleha .
’ Na le batsoali ba ka le bana beso ba 11 , re ile ra baleha re sa nka letho haese liaparo tse ’ meleng .
’ Na le ba bang re ne re le libakeng tse fapa - fapaneng . ”
Ho tlile joang hore Jesu le barutuoa ba hae e be baphaphathehi ?
O ile a re : “ Ha ba le hlorisa motseng o mong , le balehele ho o mong . ”
Ke ne ke le lilemo li 12 ka nako eo .
Maoto a ka a ne a ruruhile hoo ke ileng ka bolella ba lelapa leso hore ba ntšiee .
Re ne re rapela letsatsi le leng le le leng , re tšepile hore Jehova o tla re thusa .
Kahoo ba ne ba sebana , ba tahoa , ba becha , ba utsoa ebile ba etsa boitšoaro bo bobe . ”
( Bala 1 Johanne 3 : 17 , 18 . )
( b ) Ke hobane’ng ha re lokela ho ba le mamello ha re ba thusa ?
Re lokela ho bontša hore rea ba rata .
( b ) Ba ka bontša joang hore ba ananela thuso eo ba e fuoang ?
Re ka thusa bara le barali babo rona ba baphaphathehi joang ?
( Sheba lirapa tsa 11 - 13 )
Ho e - s’o ee kae , barab’abo rona bao e ile ea e - ba bo - pula - maliboho .
( a ) Ke hobane’ng ha barab’abo rona ba baphaphathehi ba lokela ho etsa hore kamano ea bona le Jehova e tle pele bophelong ba bona ?
Ha re hloke lintho tse ngata ! ’ ” ​ — Bala 1 Timothea 6 : 8 .
Ha re ba tšoara hantle , ba tla bona hore Jehova oa ba rata ebile o ba utloela bohloko .
Batho ba bangata ba tsoa linaheng tseo mosebetsi oa rona oa boboleli o thibetsoeng .
O re : “ Bara le barali babo rona ba ile ba re amohela joalokaha eka re beng ka bona . Ba ile ba re fa lijo , liaparo , bolulo le chelete ea ho palama .
Ha ho na motho ea ka amohelang batho bao a sa ba tsebeng ntlong ea hae , hobane feela a kena kereke le bona .
Empa Lipaki Tsa Jehova li ile tsa nkamohela . ” — Bala Johanne 13 : 35 .
Hang ha motho ea tsoang naheng e ’ ngoe a fihla , baholo ba lokela ho latela tataiso e hlahang bukeng ea Ho Hlophisetsoa ho Etsa Thato ea Jehova , khaolong ea 8 , serapeng sa 30 .
Ha ba ntse ba emetse karabo e tsoang lekaleng , baholo ba ka mo botsa lipotso ka bohlale mabapi le phutheho le tšebeletso ea hae e le hore ba mo tsebe haholoanyane .
“ Ha ho letho le nthabisang ho feta lintho tsena , hore ebe ke utloa hore bana ba ka ba tsoela pele ho tsamaea ’ neteng . ” ​ — 3 JOH . 4 .
LIPINA : 88 , 41
Batsoali ba ka ruta bana ba bona joang ?
Ke’ng eo bo - ntate ba lokelang ho e ela hloko ha ba etsa qeto ea hore na malapa a bona a tla ea libokeng tsa puo efe ?
Re ka thusa malapa a falleletseng linaheng tsa habo rona joang ?
1 , 2 . ( a ) Bana ba lulang linaheng tseo e seng tsa habo bona ba kopana le mathata afe ?
( b ) Re tla hlahloba lipotso life sehloohong see ?
Empa ha ke qala ho ea sekolong , ke ile ka thahasella puo ea naheng eo re falleletseng ho eona .
Bana ba bangata ba kile ba kopana le bothata bo tšoanang le ba Joshua .
Rona re ka ba thusa joang ?
3 , 4 . ( a ) Batsoali ba ka beha mohlala o motle joang bakeng sa bana ba bona ?
( b ) Ke’ng seo batsoali ba sa lokelang ho se lebella ho bana ba bona ?
Ha bana ba lona ba bona hore le ‘ batla ’ muso pele , ’ ba tla tšepa Jehova ka linako tsohle .
12 : 43 . Le se ke la hlokela bana ba lona nako .
Bana ba hao ba ka rua molemo joang ka ho ithuta puo ea hao ?
Haeba bana ba hao ba joalo , leka ho ithuta puo ea sebakeng seo .
Ka tsela e tšoanang , haeba ngoana oa hao a bua puo e ’ ngoe hantle ho feta ea habo , e ka ba hantle hore u ithute puo eo .
Haeba u boemong bo tšoanang , u ntse u ka khona ho thusa bana ba hao hore ba ithute ka Jehova ’ me ba mo rate .
Empa kaha ’ Mè o ne a lula a ithuta , a rapela a bile a tšoara borapeli ba lelapa beke e ’ ngoe le e ’ ngoe ka puo eo re e buang , re ile ra utloisisa hore ho bohlokoa ho ithuta ka Jehova . ”
Ke joang batsoali ba ka rutang bana ba buang lipuo tse peli ?
( a ) Ke mang ea lokelang ho etsa qeto ea hore na lelapa le kopanela phuthehong efe ?
Empa haeba ba sa ee libokeng tsa puo eo ba e utloisisang hantle , ho ka etsahala hore ba se ke ba rua molemo .
( Bala 1 Bakorinthe 14 : 9 , 11 . )
Batsoali ba ka etsa’ng ha ho le tjee ?
Jehova o ile a re fa karabo eo re sa e lebellang .
Re ile ra hlokomela hore bana ba rona baa pulufalloa ha ba ile libokeng tsa puo ea rona , kahoo ra etsa qeto ea ho ea libokeng tsa puo ea moo re falleletseng teng .
Re ne re ea le bona libokeng le tšimong re bile re memela bara le barali babo rona ba phutheho ea rona e ncha lijong le maetong a boithabiso .
Re ne re batla hore ba rate Jehova ho feta hore ba tsebe puo ea rona . ”
Samuel o boetse o re : “ ’ Na le mohats’a ka re ile ra ’ na ra ea libokeng tsa puo ea rona e le hore re tsoele pele re na le kamano e ntle le Jehova .
Kaha re ne re le maphathaphathe , hangata re ne re lula re khathetse .
Empa Jehova o ile a re hlohonolofatsa .
Bana ba rona kaofela ba tšebeletsong ea nako e tletseng . ”
Kristina o re : “ Le hoja ke ne ke tseba puo ea batsoali ba ka hanyenyane , ha ke le libokeng e ne eka e ncha .
Bacha , na le lona le batla ho kopanela phuthehong ea puo ea moo le falleletseng teng ?
Nadia , ea sebeletsang Bethele o re : “ Ha ’ na le bana beso re ntse re hola , re ne re batla ho kopanela phuthehong ea puo ea moo re seng re lula teng . ”
Nadia o boetse o re : “ Hona joale rea bona hore batsoali ba rona ba re thusitse ka hore ebe ba ile ba re ruta puo ea bona ’ me ba ea le rona libokeng tsa puo ea bona .
Hona joale re khona ho thusa batho ba bangata hore le bona ba tsebe Jehova . ”
( b ) Batsoali ba ka fumana thuso joang bakeng sa ho ruta bana ba bona ?
( Bala Liproverbia 1 : 8 ; 31 : 10 , 27 , 28 ) Ho ntse ho le joalo , kaha batsoali ba bang ha ba tsebe puo e buuoang moo ba falleletseng teng , ba ka ’ na ba hloka ho thusoa .
Batsoali le bana ba bona ba ka fumana molemo ho bara le barali babo rona ka phuthehong ( Sheba lirapa 18 , 19 )
( b ) Batsoali ba lokela ho tsoela pele ba etsa’ng ?
Ba ne ba lula ba nthusa ho lokisetsa lipuo tsa ka ’ me ke ne ke ithuta lintho tse ngata ho bona .
’ Me ho ne ho e - ba monate nako le nako ha re ikhatholla . ”
Batsoali , kopang Jehova hore a le thuse ’ me le sebetse ka thata ho thusa bana ba lona .
( Bala 2 Likronike 15 : 7 . )
Ho thusa bana ba lona ho rata Jehova e lokela ho ba ntho ea bohlokoa ho feta lintho tseo le li batlang .
Joalokaha ho boletse Walter Markin
Empa ka 1946 e ne e le hona ke utloisisang lithuto tsa Bibele hantle .
E - re ke le phetele .
Butle - butle ke ile ka ithuta puo ea matsoho ’ me ka thabela ho bapala le bana ba bang .
Ke etsa bopaki ba phatlalatsa lilemong tsa bo - 1950
Ka 1950 , ke ile ka fallela Vancouver .
O ile a nka sengoliloeng a ba a re o batla hore ke kopane le Gary , e leng mohats’a hae .
Hamorao ke ile ka khutlela Saskatoon .
Qetellong , ba bahlano ba bona ba ile ba kolobetsoa .
E mong oa bona e ne e le Eunice Colin .

’ Na le Eunice ka 1960 le ka 1989
Ha a bolella batsoali ba hae hore o batla ho kolobetsoa , ba ile ba re : “ Ha u ka ba Paki feela , u tla lokela ho re tsoela ka ntlo . ”
O ile a mpha pompong eaba o kopa hore re be metsoalle .
Ha re nyalana ka 1960 , batsoali ba hae ha baa ka ba tla lechatong la rona .
Mora oa ka Nicholas le mosali oa hae Deborah , ba sebetsa Bethele e London
Faye le James , Jerry le Evelyn , Shannan le Steven
Hona joale re Phuthehong ea Calgary ea Puo ea Matsoho ’ me ke moholo phuthehong eona eo .
LIPINA : 60 , 135
Re ka etsa’ng hore re lule re rata Jehova ?
Re ka etsa’ng hore re rate Lentsoe la Molimo haholoanyane ?
Ke hobane’ng ha ho le bohlokoa hore re rate Bakreste - ’ moho le rona ?
E ka ’ na eaba ke’ng e ileng ea etsa hore lerato la Bakreste ba bang le fokotsehe ?
Batho ha ba sa rata Molimo hakaalo .
Rata Jehova ( Sheba serapa sa 10 )
( Bala Pesaleme ea 119 : 97 - 100 . )
Rata Lentsoe la Molimo ( Sheba serapa sa 14 )
Letsatsi pele Jesu a shoa , o ile a re : “ Ke le fa taelo e ncha , hore le ratane ; le lōna le ratane feela joalokaha ke le ratile .
Bohle ba tla tseba ka sena hore le barutuoa ba ka , haeba le e - na le lerato har’a lōna . ” — Joh . 13 : 34 , 35 .
Moapostola Johanne o ile a re : “ Ea sa rateng mor’abo , eo a mo boneng , a ke ke a rata Molimo , eo a e - s’o mo bone . ”
Rata Bakreste - ’ moho le uena ( Sheba serapa sa 17 )
Re ka bontša Bakreste - ’ moho le rona joang hore rea ba rata ?
Bala 1 Bathesalonika 4 : 9 , 10 .
21 : 15 .
LIPINA : 128 , 45
Joale ba le lahlela , empa ba se ke ba hlola ba khona ho le hula ka lebaka la litlhapi tse ngata haholo . ” — Joh .
21 : 1 - 6 .
( b ) Mor’abo rona e mong oa Thailand o ile a ithuta’ng ka mosebetsi oa hae ?
Empa ke ne ke qeta nako e ngata mosebetsing hoo ke neng ke se na nako ea ho sebeletsa Jehova .
Qetellong ke ile ka bona hore ke lokela ho fetola tsela eo ke etsang lintho ka eona e le hore mosebetsi oa Jehova o tle pele bophelong ba ka . ”
Mor’abo rona eo o ile a etsang ?
O re : “ Ka mor’a selemo ke ile ka qalella ho rekisa ice cream seterateng .
Qalong ke ile ka hula ka thata licheleteng ’ me ka utloa ke batla ho tlohela khoebo eo .
Batho bao ke neng ke sebetsa le bona ba ne ba ntšeha , ba mpotsa hore na hobane’ng ha ke ne ke nahana hore ho rekisa ice cream ho molemo ho feta ho lokisa lik’homphieutha .
Ke ile ka rapela Jehova , ka mo kopa hore a nthuse ho mamella le ho nthusa hore ke be le nako e ngata ea ho mo sebeletsa .
Ho e - s’o ee kae , lintho li ile tsa loka .
Ke ile ka ithuta hore na bareki ba ka ba rata ice cream e joang ’ me ka ithuta ho etsa ice cream e monate .
Ka mor’a nakoana , ice cream eo ke neng ke e rekisa e ne e rekoa kaofela letsatsi le letsatsi .
Ha e le hantle , ke ne ke fumana chelete e ngata ho feta ha ke ne ke lokisa lik’homphieutha .
Ke thabile haholo hobane hona joale ha ke sa imeloa kelellong joaloka ha ke ne ke lokisa lik’homphieutha .
Ntho ea bohlokoa le ho feta ke hore ke na le kamano e ntle le Jehova . ” — Bala Matheu 5 : 3 , 6 .
Ka mor’a hore a kolobetsoe , o ile a re : “ Ke ikoahlaela hore ebe ke ile ka senya nako e ngata hakana pele nka bona hore ho sebeletsa Jehova ke eona feela ntho e thabisang le ho feta boithabiso ba lefatše . ”
Hobane ho ke ke ha khoneha hore re qete nako e ngata re sebeletsa Jehova re bile re ntse re batla maruo .
Jesu o ile a re : “ Ha ho eo e ka bang lekhoba la benghali ba babeli ; kaha o tla hloea e mong ’ me a rate e mong , kapa o tla khomarela e mong ’ me a nyelise e mong .
( Bala 1 Bakorinthe 2 : 14 . )
( Sheba serapa sa 18 )
Sheba sehlooho se reng “ Na Boithabiso ba Hao bo U Tsoela Molemo ? ”
Leha ho le joalo , re ne re ntse re ipha nako ea ho ea tšimong kamehla . ”
Re ne re utloa bohloko le ho feta ha re nahana ka ho arohana le batho bao re ithutang Bibele le bona . ”
Empa khoeli hamorao ba ile ba fumana litaba tse monate .
Miriam o re : “ Re ile ra khethoa re le bo - pula - maliboho ba khethehileng .
Re ile ra thaba haholo ha re khona ho tsoela pele kabelong ea rona . ”
Ba ile ba tšepa tšepiso ea Molimo e hlahang ho Pesaleme ea 37 : 5 e reng : “ Rōlela tsela ea hao ho Jehova , U itšetlehe ka eena , ’ me o tla nka bohato . ”
Re se re phela bophelo bo bobebe ’ me ha re haelloe ke letho le molemo . ”
Ke eng e ba thabisitseng haholo ?
9 Rata Matlotlo a Tsoang ho Jehova ka Pelo Eohle
LIPINA : 38 , 56
Ke hobane’ng ha malapa a lokela ho lebella ho ba le mathata ?
Re kholisehile hore Jehova o re batlela se molemo feela joalokaha a ile a etsa joalo ka bahlanka ba hae ba mehleng ea khale . — Bala Jeremia 29 : 11 , 12 .
Sheba serapa sa 9 le sa 12 )
( Bala 1 Samuele 1 : 4 - 7 . )
( Bala Pesaleme ea 145 : 18 , 19 . )
“ Moo letlotlo la lōna le leng teng , lipelo tsa lōna le tsona li tla ba moo . ” — LUKA 12 : 34 .
LIPINA : 153 , 104
Kahoo , leka ho thuisa ka hore na u ka etsa’ng e le hore u rate matlotlo ana haholoanyane .
Bala Matheu 13 : 45 , 46 .
Na oa hlokomela hore na perela eo e ne e le ea bohlokoa hakae ho eena ?
( Bala Mareka 10 : 28 - 30 . )
( a ) Ke hobane’ng ha moapostola Pauluse a ile a re mosebetsi oa boboleli ke “ letlotlo . . . lijaneng tsa letsopa ” ?
Morali’abo rona Irene o re : “ Ha ho letho le ka nthabisang ho feta mosebetsi ’ ona . ”
Sheba lirapa 11 le 12 )
‘ Pokello . . . ea letlotlo ’ eo Jesu a buileng ka eona ho Matheu 13 : 52 ke eng , hona re lokela ho etsa’ng hore pokello eo e hole ?
Moea o halalelang o ka re thusa joang ?
Nahana ka se ileng sa etsahalla mor’abo rona Peter .
O ile a ba a botsa Peter a re : “ Mpolelle hee moshana , hana buka ea Daniele e ngotsoe ka puo efe ha e ne e qala ho ngoloa ? ”
tsa likhoeli tse fetileng , ke ile ka fumana sehlooho se bontšang hore buka ea Daniele e fela e ngotsoe ka Searame .
Ha re etsa joalo , re tla ba le ‘ letlotlo le sa feleng le ka mohla maholimong , moo lesholu le sa atameleng kapa hona hore tšoèlè e je .
Etsoe moo letlotlo la rōna le leng teng , lipelo tsa rōna le tsona li tla ba moo . ’ — Luka 12 : 33 , 34 .
“ ’ Na le mor’abo rona eo ke neng ke sebetsa le eena re ne re sa utloane .
Ka lekhetlo le leng banna ba bang ba babeli ba ile ba re fumana re kharumelana . ” ​ —⁠ CHRIS .
“ Morali’abo rona eo ke neng ke tloaetse ho ea tšimong le eena o ile a khaotsa ho tsamaea le ’ na .
Bothata ke hore ke ne ke sa tsebe le hore na ke fositse hokae . ” ​ —⁠ JANET .
E mong oa bona o ile a re fonanisa eaba ke se ke bua ka eena athe ha a e -⁠ s’o koale fono . ” ​ —⁠ MICHAEL .
Qoaketsano ena ea bona e ile ea nyahamisa bahoeletsi ba bang . ” ​ —⁠ GARY .
“ Le se ke la khenelana tseleng . ”
“ Merero ea senyeha moo ho se nang lekunutu . ”
Michael o re : “ Mor’eso o ile a ntšoarela e le kannete . ”
Hona joale ba bolela litaba tse molemo ’ moho ba thabile .
Phapang ena e ka bonahala e le nyane , empa e ka baka mathata a maholo . ”
Ke ne ke utloa a ntena eaba ke ipolella hore ha ke na ho bua le eena hantle .
‘ O ne a sa ntlhomphe eaba ke bona ho sa hlokahale hore ke mo hlomphe le ’ na . ’ ”
O re : “ Ke ile ka soaba haholo ha ke hlokomela hore ke entse phoso .
Ke ne ke lokela ho nahana taba ena ka tsela e ’ ngoe .
Ke ile ka bua le Jehova ka taba ena , eaba ke rekela morali’abo rona eo mpho e nyenyane , ka ba ka mo ngolla molaetsa ke kopa tšoarelo .
Re ile ra lokisa litaba , ra hakana ra ba ra lumellana hore e fetile .
LIPINA : 46 , 136

Ke hobane’ng ha ho hlokahala hore Jehova a tlose qoso bobusing ba hae ?
( Bala Pesaleme ea 83 : 18 ) Adama le Eva ha baa ka ba lumela ho busoa ke Jehova ’ me hamorao batho ba bang le bona ba ba etsisa .
Ho bohlokoa hakae hore re tšehetse bobusi ba Jehova ?
Ka sebele , ho tloha letsatsing la ha baholo - holo ba rōna ba robala lefung , lintho tsohle li tsoela pele hantle feela joaloka ho tloha tšimolohong ea pōpo . ”
Jehova o ile a re’ng ho eena ?
Re ka ithuta’ng linthong tse ileng tsa etsahalla Jobo ?
LIPINA : 112 , 133
Lebaka le leng ke hore Jehova o lerato .
Baholo le bo - ntate ba ka etsisa Jehova joang ?
Pesaleme ea 147 e khothalletsa barapeli ba Molimo hore ba rorise Jehova .
Ke’ng e ileng ea susumelletsa mopesaleme hore a batle hore re rorise Molimo ?
Bacha ba bangata e ba bo - pula - maliboho .
“ Iketsetseng metsoalle ka maruo a sa lokang . ” — LUKA 16 : 9 .
LIPINA : 32 , 154
Re ka etsa’ng hore re se ke ra phathahana ka ho batla maruo ?
Ke hobane’ng ha ho tla lula ho e - na le mafutsana lefatšeng mehleng ee ?
Bala Luka 16 : 1 - 9 .
Ke’ng eo re ithutang eona mantsoe aa ?
Re tseba joang hore Jehova o ne a sa rera hore batho ba etse chelete ?
Bala Luka 16 : 10 - 13 .
Fana ka mohlala oa kamoo batho ba bang bontšang kateng hore ba rata Jehova ka maruo a bona a sa lokang .

Ke joang Abrahama a ileng a bontša hore o tšepa Molimo ?
( b ) Re ka bontša joang hore re mamela keletso ea Pauluse ?
Timothea o ne a e - na le tumelo .
Ka mor’a hore Pauluse a bitse Timothea “ lesole le khabane la Kreste Jesu , ” o ile a re ho eena : “ Ha ho monna ea sebeletsang e le lesole ea ikenyang likhoebong tsa bophelo , e le hore a ka fumana kamohelo ea ea mo ngolisitseng e le lesole . ”
Ke ntho efe eo re ke keng ra e lebala ?
Jehova o hlohonolofatsa batho ba etsang ‘ mesebetsi e metle . ’
Re tla haha matlo a matle ka thepa ea boleng bo holimo ea lepolanka , lejoe le lesenke ’ me e tla fumaneha mahala .
LIPINA : 121 , 75
MORALI’ABO RONA SUSI o re : “ Esita le ka mor’a selemo mora oa rona a hlokahetse , re ntse re utloile bohloko bo tebileng . ”
Kamehla khotso ea hae e ne e lebela lipelo tsa rona le likelello tsa rona . ” — Bala Bafilipi 4 : 6 , 7 .
Jesu o ile a bontša joang hore o utloela batho bohloko ?
Haeba u hlokahalletsoe , u ka tšelisoa ke Mangolo a latelang :
( Bala 1 Bathesalonika 5 : 11 . )
Ke’ng eo re lokelang ho e hopola ka tsela eo batho ba utloang bohloko ka eona ?
Esita leha motho a ka leka ho hlalosa kamoo a ikutloa kateng , ha ho bonolo hore batho ba bang ba utloisise hantle hore na o re’ng .
Kea hlokomela hore ha ke motoai - toai . ”
Morali’abo rona Junia o re : “ Ha ke fumana molaetsa o mokhutšoanyane o tšelisang kapa Bakreste - ’ moho le ’ na ba kopa hore ke ba chakele , ke tšeliseha haholo .
Kea hlokomela hore baa nthata ebile baa ntsotella . ”
Morali’abo rona Dalene o re : “ Ka linako tse ling ha baralib’abo rona ba tl’o ntšelisa , ke ee ke ba kope hore ba rapele le ’ na .
Le hoja ha ba qala ho etsa thapelo mantsoe a bona a thothomela , ka mor’a ho bua lipolelo tse seng kae , mantsoe a bona aa tiea ebe ba etsa thapelo e nthobang pelo .
Ha ke bona tsela eo ba ratang Jehova kateng le kamoo ba ntsotellang kateng , tumelo ea ka ea matlafala . ”
“ Motsoalle oa ’ nete o lerato ka linako tsohle , ’ me ke mor’abo motho ea tsoaletsoeng ha ho e - na le mahlomola . ”
Mor’abo rona e mong o re : “ Ke ne ke tseba hore ke tla utloa bohloko haholo ha letsatsi leo re nyalaneng ka lona le fihla .
’ Me ho ile ha fela ha e - ba boima .
Empa batho ba hlokahalletsoeng ba hloka ho tšelisoa ka linako tsohle , eseng feela ka matsatsi a khethehileng .
Morali’abo rona Junia o re : “ Lintho tseo batho ba ileng ba nketsetsa tsona leha e se ka letsatsi le khethehileng , li nthusitse haholo hore ke tšelisehe . ”
Ba entse hore ke utloe hore Jehova oa nthata . ”
Ke hobane’ng ha lintho tseo Jehova a li tšepisang li re tšelisa ?
Bibele e re : “ O tla metsa lefu ka ho sa feleng , ’ me ka sebele ’ Musi Morena Jehova o tla hlakola meokho lifahlehong tsohle . ”
Mangolo a mang a ka re tšelisang ke Pesaleme ea 20 : 1 , 2 ; 31 : 7 ; 38 : 8 , 9 , 15 ; 55 : 22 ; 121 : 1 , 2 ; Esaia 57 : 15 ; 66 : 13 ; Bafilipi 4 : 13 le 1 Petrose 5 : 7 .
Sheba le sehlooho se reng “ Tšelisa ba Hlokahaletsoeng , Joalokaha Jesu a Ile a Etsa ” se hlahang ho Molula - Qhooa oa November 1 , 2010 .
“ Ha re tsebe hore na re re’ng ho lona . Empa tsebang hore rea le rata .
Rona re ke ke ra utloisisa hore na le ikutloa joang , empa Jehova eena oa utloisisa ebile o tla le matlafatsa .
Re na le tšepo ea hore lithapelo tsa rona li tla le thusa . ”
“ E se eka Jehova a ka le matlafatsa nakong ena e boima . ”
“ E se eka le ka tšelisoa ke ho tseba hore Jehova o ntse a mo hopola ’ me o tla hopola lintho tsohle ka eena ebe oa mo tsosa . ”
“ Hona joale Jehova oa mo hopola hobane o ne a tšepahala ’ me o tla mo tsosetsa Paradeiseng . ”
“ Ha ho mantsoe a ka hlalosang kamoo le utloileng bohloko kateng , empa re lebeletse ho bona ha Jehova a mo tsosa .
Re sitoa ho hlalosa thabo eo re tla beng re e thabile . ”
Nakong ea matšoenyeho a maholo , Bakreste ba tla tšepa Jehova ho e - na le hore ba leke ho itšireletsa
Mohoeletsi o buisana le mosebetsi ka Bibele serapeng sa liapole motseng oa Grójec .
LIPINA : 104 , 152
( b ) Re ka ithuta’ng ho Pesaleme ea 147 ?
( Bala Pesaleme ea 147 : 5 . )
Eseng hobane feela u le pula - maliboho , empa hobane u morali oa ka ea inehetseng ho ’ na .
Kannete ke ile ka tšeliseha . ”
Jehova o qala pele ka ho re matlafatsa tumelong .
12 , 13 . ( a ) Re lokela ho qoba ho etsa’ng e le hore Jehova a re thuse ?
Empa Jehova “ o kokobetsa ba khopo . ”
“ Jehova o khahlisoa ke ba mo tšabang , ba letelang mosa oa hae o lerato . ”
O beha khotso naheng ea hao . ”
( Sheba lirapa 15 - 17 )
15 - 17 . ( a ) Ka linako tse ling re ka ikutloa joang ka mathata a rona , empa Jehova o re thusa joang ka Lentsoe la hae ?
Mehleng ena , Jehova o re thusa ka Lentsoe la hae , e leng Bibele .
( Bala Pesaleme ea 147 : 19 , 20 . )
LIPINA : 89 , 140
U ka thusoa ke’ng hore u tle u thabe ka moso ?
Ho ba pula - maliboho ho ka u tlisetsa litlhohonolofatso life ?
Bacha , e ka ’ na eaba lea tseba hore pele motho a qala leeto , o lokela ho tseba hore na o tla ea kae .
Bophelo bo tšoana le ho nka leeto .
U tseba joang hore Jehova o batla hore u thabe ?
Jehova o u khothalletsa ho etsa’ng ?
Jehova o u khothalletsa ho etsa liqeto life ?
’ Mopi oa hao ke “ Molimo oa lerato , ” “ ea thabileng , ” ea bileng a bopileng batho “ ka setšoantšo sa hae . ”
Ha u mo etsisa , u tla thaba .
Jesu o ne a thabisoa ke’ng ?
Jesu Kreste o behetse bacha mohlala o motle .
Empa Jesu o ne a boetse a e - na le kamano e ntle le Jehova hobane o ne a ithuta Mangolo .
“ Merero ea senyeha moo ho se nang lekunutu , empa ha baeletsi ba le bangata ho na le se finyelloang . ”
Joaloka mosebetsi o mong le o mong , u lokela ho ipha nako ea ho ithuta ho o etsa .
Qalong ke ne ke se na lithuto , empa ka mor’a hore ke fallele sebakeng se seng , ke ile ka ba le lithuto tse ’ maloa le pele khoeli e fela .
E mong oa batho bao ke ithutang Bibele le bona o ile a qala ho tla libokeng .
Mohlala , Jacob ea Amerika Leboea , o re : “ Ha ke le lilemo li supileng , bana ba bangata bao ke kenang le bona ka tlelaseng ba ne ba bua Sevietnamo .
Kaha ke ne ke batla ho ba ruta ka Jehova , ke ile ka leka ho ithuta Sevietnamo .
Ke ne ke ithuta sona ka ho bapisa Molula - Qhooa oa Senyesemane le oa Sevietnamo .
Ka boela ka ba le metsoalle ea liphuthehong tsa Sevietnamo .
Ha ke le lilemo li 18 ke ile ka ba pula - maliboho .
Eaba hamorao ke ea Sekolong sa Bibele sa Barab’abo Rōna ba Masoha .
Sekolo sena se nthusitse ho phetha kabelo eo ke nang le eona hona joale kaha ke ’ na feela moholo phuthehong ea Sevietnamo .
Batho ba bangata ba buang Sevietnamo baa makala ha ba utloa ke bua puo ea bona .
Ba ’ memela lijong ’ me ke khona ho ithuta Bibele le bona .
Ba bang ba bile ba kolobelitsoe . ” — Bapisa le Liketso 2 : 7 , 8 .
Ke qalile ho ba pula - maliboho ka mor’a hore ke qete sekolo .
Ke rata ho khothatsa bacha ba phutheho ea heso ’ me kea thaba ha ke bona ba hatela pele .
Ka mor’a hore ke ee Sekolong sa Bibele sa Barab’abo Rōna ba Masoha , ke ile ka fuoa kabelo e ncha .
Le hoja ke e - s’o fumane motho ea qetellang a kolobetsoa , bahoeletsi ba bang ba ba fumane .
Ho na le menyetla e mengata ea ho sebeletsa Jehova .
Ho ba pula - maliboho ho ka u thusa joang ho sebeletsa Jehova haholoanyane ?
Mor’abo rona Kevin o re : “ Haesale ke batla ho sebeletsa Jehova ho tloha ha ke sa le monyenyane .
Kahoo , ha ke le lilemo li 19 ke ile ka qala ho bula maliboho .
Eaba ke sebetsa le mor’abo rona e mong oa sehahi e le hore ke iphelise .
Ke ile ka ithuta ho kenya marulelo , lifensetere le mamati .
Hamorao ka qeta lilemo tse peli ke sebetsa le sehlopha sa Bakreste - ’ moho le ’ na ba neng ba thusa bara le barali babo rona ba hlahetsoeng ke likoluoa ka ho ba hahela Liholo Tsa ’ Muso le mahae .
Eitse ha ke utloa hore ho hlokeha baithaopi bakeng sa ho haha Liholo Tsa ’ Muso naheng ea Afrika Boroa , ke ile ka ithaopela ho ea , eaba kea amoheloa .
Mona Afrika Boroa re haha Holo ea ’ Muso ka mor’a libeke tse seng kae libakeng tse fapaneng .
Ke phela hamonate le batho ba sehlopha seo ke sebetsang le sona hoo e kang ke ba lelapa leso .
Re lula ’ moho , re ithuta Bibele ’ moho ebile re sebetsa ’ moho .
Hape , ho ba monate ha re ile tšimong le Bakreste - ’ moho le ’ na ba sebaka seo re leng ho sona .
Lintho tseo ke ileng ka rera ho li etsa bophelong ha ke sa le monyenyane li nthabisitse ka tsela eo ke sa kang ka e hlokomela . ”
Ho sebeletsa Bethele ho etsa hore motho a thabe hobane ha e le hantle o sebeletsa Jehova .
Ka mor’a selemo le halofo , kopo ea ka ea ho e’a sebetsa Bethele e ile ea amoheloa , eaba kea ea .
Ke ile ka ithuta ho sebelisa mechine e hatisang lingoliloeng le ho sebetsana le lik’homphieutha .
Ke natefetsoe ke ho sebetsa Bethele hobane mosebetsi oo re o etsang o thusa batho ho ba le kamano e ntle le Jehova . ”
Kholiseha hore Jehova o batla hore u ‘ tšoare ka tieo bophelo ba sebele , ’ e leng hore o batla hore u thabele bokamoso .
( Bala 1 Tim .
Ka mor’a moo , u rere ho etsa lintho tse tla mo thabisa .
Haesale Satane a tseba tsela eo batho ba etsang lintho ka eona ho tloha ha ba qala ho boptjoa .
U ka hana mashano a hae joang ?
U lokela ho iphumanela eona . ”
Jesu o ile a re : “ Le se ke la tšaba ba bolaeang ’ mele ’ me ka mor’a moo ba sa khone ho etsa letho le fetang moo . ”
O ntse a u thetsa . ’
Mamela Jehova ’ me u mo tšepe maemong ’ ohle .
3 Na U Ikemiselitse ho Leta U sa Fele Pelo ?
Sehlooho se latelang se tla bua ka kamoo Jehova a ka etsang lintho tseo batho ba sa li lebellang e le hore a phethahatse lintho tseo re sa li nahanang .
27 Re Lokela ho ba le Lerato
LIPINA : 78 , 139
Re lokela ho leta joaloka sehoai seo .
Re ithuta’ng ho moprofeta Mikea ?
( Bala Mikea 7 : 1 - 3 . )
Haeba re na le tumelo joaloka Mikea , re tla ikemisetsa ho letela Jehova .
Kahoo re ‘ mamella ka botlalo ’ me re tiisetsa ka thabo . ’
Abrahama o ile a tlameha ho ema lilemo tse ngata pele litloholo tsa hae , Esau le Jakobo li hlaha ( Sheba lirapa 9 le 10 )
Nahana ka Abrahama le Sara .
Ke hobane’ng ha Abrahama a ne a sa lokela ho fela pelo ?
Empa nahana hore na o tla ikutloa joang ha a tsosoa ’ me a fumana lefatše e le paradeise .
O ne a e - na le tumelo e matla ho Jehova .
Molimo o ne a hopotse se molemo ka morero oa ho etsa joaloka letsatsing lena ho boloka batho ba bangata ba phela . ”
( b ) O thusitsoe ke’ng hore a se fele pelo ?
Ke hobane’ng ha Davida a ne a ikemiselitse ho leta a sa fele pelo ?
Ke tla binela Jehova , etsoe o sebetsane le ’ na ka mokhoa o putsang . ”
( Bala 2 Petrose 3 : 9 . )
Ke’ng e tla re thusa hore re se ke ra fela pelo ?
LIPINA : 76 , 141
Re ithuta’ng ka se ileng sa etsahalla moapostola Pauluse ha a le Filipi ?
( Bala Liketso 16 : 8 - 10 . )
Nakoana ka mor’a hore a fihle Macedonia , o ile a isoa teronkong .
Ke hobane’ng ha Jehova a ile a lumella hore Pauluse a hlaheloe ke ntho ee ?
Eena le Silase ba ile ba “ rapela ’ me ba rorisa Molimo ka pina . ”
4 , 5 . ( a ) Maemo a rona a ka tšoana le a Pauluse joang ?
( b ) Maemo a Pauluse a ile a fetoha joang ?
Maemo a bona a ile a fetoha ka potlako .
Re tl’o hlahloba’ng sehloohong see ?
( Bala 1 Petrose 5 : 6 , 7 . )
Ka linako tse ling a ka re etsetsa lintho re sa lebella .
Jehova o ile a romela lengeloi le ileng la bolaea masole a Sankeribe a 185000 ka bosiu bo le bong .
( a ) Re ithuta’ng linthong tse ileng tsa etsahalla Josefa ?
Jehova o ile a etsa lintho tseo Josefa a neng a sa li lebella ho hang .
Hape , hopola hore na ho ile ha etsahala’ng ka Sara , nkhono oa Josefa .
Ke’ng eo re ka kholisehang hore Jehova o tla re etsetsa eona ?
( Bala Esaia 43 : 10 - 13 . )
Ka lebaka leo , ha se habonolo re tla nyahama kapa hona ho tšoenyeha .
LIPINA : 83 , 129
Ke’ng e etsang hore re ikhethe ?
Ke joang re ka tlohelang lintho tse mpe tseo re neng re li etsa le ho li tlohellela ruri ?
Ka 1939 Lipaki tse 6 000 li ne li le literonkong Jeremane moo li neng li hlorisoa ka sehloho . ”
Hape , le hloekisitse lebala hantle haholo .
Empa ntho e kholo eo ke e boneng ke hore le kopane le le merabe e mengata . ”
Ke’ng e etsang hore Lipaki Tsa Jehova li fapane le batho ba bang ?
Bohlola .
Empa eare ha ke ntse ke khelella ho ea pele boitšoarong bona , ka utloa ke jeoa ke bolutu le ho feta . ”
O ile a tsoela pele ka boitšoaro boo ho fihlela a le lilemo li 23 .
Ho se hloeke .
O re : “ Butle - butle ka li lemalla hoo ke neng ke tatela hore mosali eo ke neng ke lula le eena a tsoe ka tlung e le hore ke li shebelle . ”
Mor’abo rona Stephen o thusitsoe ke’ng hore a fetohe ?
O re : “ Lelapa la ka le ile la thaba .
Mor’abo rona Stephen e se e le mohlanka ea sebeletsang ’ me mosali oa hae o se a e - na le lilemo tse seng kae e le pula - maliboho ea kamehla .
Empa ha mor’abo rona Hans a ntse a hola , e ne e se motho ea bonolo .
Ke ile ka khothatsoa ke Lengolo la Esaia 55 : 7 le reng : ‘ Motho ea khopo a tlohele tsela ea hae ’ le la 1 Bakorinthe 6 : 11 leo ha le bua ka batho ba bakileng le reng : ‘ Leha ho le joalo ke seo ba bang ba lōna ba neng ba le sona . ’
Ka lilemo tse ngata Jehova o ’ nile a nthusa ka moea oa hae o halalelang hore ke fetohe . ”
Lentsoe la Molimo le moea o halalelang li ka re thusa ha rea libokeng le nakong eo re li lokisetsang .
Sheba khaolo ea 25 bukeng ea Lipotso — Bacha Baa Botsa — Likarabo Tse Sebetsang , Buka ea 1 .
LIPINA : 43 , 106
( Bala Bakolose 3 : 10 - 14 . )
O ile a re ha ho “ Mogerike kapa Mojuda , lebollo kapa ho se bolle , osele , Moskitha , lekhoba , motho ea lokolohileng . ”
( a ) Bahlanka ba Jehova ba lokela ho tšoara batho ba bang joang ?
( Sheba setšoantšo se qalong . ) ( b ) Ho bile le melemo efe ?
Empa ka mor’a hore a ee libokeng tsa Lipaki Tsa Jehova o ile a re : “ Le hoja boholo ba batho ba neng ba le moo , e ne e le Majapane , ba ile ba nkamohela ka mofuthu joalokaha eka ke motsoalle oa bona eo ba mo qetetseng khale . ”
Ekare u naheng e ’ ngoe empa u ntse u le naheng ea heno .
Hape u tla hlokomela kamoo Lipaki Tsa Jehova li momahaneng kateng . ”
( Sheba serapa sa 10 )
Ha re ba balla Tšenolo 21 : 3 , 4 kapa Pesaleme ea 37 : 10 , 11 , 29 , ba ne ba re mamela ka hloko .
Re leboha Jehova haholo . ” — Bala Liketso 10 : 34 , 35 .
Bala Liproverbia 22 : 4 .
Jesu o re behetse mohlala ofe oa ho ba bonolo le ho mamella ?
Jesu o ne a le “ maikutlo a bonolo . ”
Pauluse o ile a ngolla balumeli - ’ moho le eena hore na ba lokela ho etsa’ng ho bontša hore ba bonolo ba bile ba na le mamello .
Esita le joalokaha Jehova a ile a le tšoarela ka bolokolohi , le etse joalo le lōna . ”
Ke hobane’ng ha ho le bohlokoa hore re be bonolo ’ me re be le mamello ?
A boela a re : “ Haeba le tsoela pele ho bontša leeme , le etsa sebe . ”
Ke hobane’ng ha ho le bohlokoa hore re ikapese lerato ?
Hape “ lerato lea tiisetsa ’ me le mosa . . . . Ha le ikhohomose . ”
TIISETSO
MOSA
MOLEMO
TUMELO
BONOLO
BOITŠOARO
Pauluse o ile a re motho ea seng lerato ha se “ letho . ”
Lerato le ka tsela ena , eseng hore re ratile Molimo , empa hore o ile a re rata ’ me a romela Mora oa hae e le sehlabelo sa poelano bakeng sa libe tsa rōna . ”
Jesu o lerato ho feta motho e mong le e mong .
O ile a re : “ Ha ho ea nang le lerato le leholo ho lena , hore motho a nehelane ka moea oa hae molemong oa metsoalle ea hae . ”
Re tl’o hlahloba hore na re ka ba etsisa joang .
Johanne o ile a re : “ Bana ba banyenyane , a re se keng ra rata ka lentsoe kapa ka leleme , empa re rate ka ketso le ’ nete . ”
Ke ile ka utloa bohloko haholo .
Empa ka ipotsa hore na nka etsisa Jesu joang le hore na eena a ka be a ile a etsa’ng haeba a ne a le boemong boo .
Kahoo , ka etsa qeto ea hore ke tlohele taba eo ’ me ke se ke ka nahana ka thata ka eona .
Ka mor’a nako , ke ile ka tseba hore ’ mè eo o ne a imetsoe kelellong ka lebaka la bokulo bo neng bo mo tšoere .
Kahoo , ka nahana hore e ka ’ na eaba o ne a buile hampe ka ’ na hobane a ne a imetsoe kelellong , eseng hobane a ne a batla .
Ho nahanisisa ka tsela eo Jesu a neng a le lerato ka eona leha a ne a utloisoa bohloko ho ile ha nthusa hore le ’ na ke rate mosebetsi - ’ moho le ’ na le hoja a ne a nkutloisitse bohloko . ”
Jesu o ile “ a ikhokhotha . . . ho isa lefung ” molemong oa rona .
Re ka fumana melemo efe ha re bontša hore re lerato ?
KHOTSO : Haeba re ‘ mamellana ka lerato , ’ ho ba le “ tlamo e kopanyang ea khotso ” pakeng tsa rona le Bakreste - ’ moho le rona .
Khotso ena e teng pakeng tsa rona le Bakreste - ’ moho le rona ke eona e etsang hore re fapane hole le batho ba lefatše lena ba se nang khotso .
Kopanong ea 1941 motse - moholo oa Mexico
Ka le hlahlamang , batho ba neng ba tlile ba ne ba le bangata ho feta litulo tse neng li le teng . ”
Bara le barali babo rona ba phutheho e ’ ngoe ba ile ba re : “ Ho hole hoo ho se nang le lipalo tsa lifono . ”
Ba bang bona ba ne ba robaletsa Liholong Tsa ’ Muso .
Ka 2016 , batho ba neng ba le teng Sehopotsong naheng ea Mexico ba ne ba le 2 262 646 .
E hlalosa kamoo Josefa a ileng a ikutloa kateng ha a utloa hore Maria o imme .
3 Na U Khona ho Itšoara ?
Ho ba le kutloelo - bohloko ho bolela’ng ?
LIPINA : 83 , 52
1 , 2 . ( a ) Ho hloka boitšoaro ho ka etsa hore batho ba etse’ng ?
Empa rona ha rea phethahala .
Re ka ithuta’ng mohlaleng oa Jehova ?
U ka etsa’ng hore u itokisetse maemo a ka etsang hore u tlole melao ea Jehova ?
Mor’abo rona Luigi o ile a etsahalloa ke’ng , hona re ithuta’ng mohlaleng oa hae ?
Batsoali ba ka thusa bana ba bona joang hore ba khone ho ithiba hore ba se ke ba etsa lintho tseo Jehova a sa li rateng ?
U ka thusa bana ba hao joang hore ba khone ho ithiba hore ba se ke ba etsa lintho tseo Jehova a sa li rateng ?
LIPINA : 142 , 12
( Bala Exoda 34 : 5 - 7 . )
( b ) Ke hobane’ng ha taba ea ho qenehela batho e le bohlokoa ?
( a ) Ke hobane’ng ha Jehova a ile a romela mangeloi motseng oa Sodoma ?
( Bala Exoda 22 : 26 , 27 . )
Bibele e re : “ Jehova Molimo oa baholo - holo ba bona a ’ na a romeletsa khahlanong le bona ka manģosa a hae , a romeletsa nako le nako , hobane o ne a qenehela batho ba hae le sebaka sa hae sa bolulo . ”
Ha a ba bona o ile a ‘ qala ho ba ruta lintho tse ngata . ’
Ho e - na le hoo , re lokela ho leka ka hohle ho ba thusa hore ba be le kamano e ntle le Molimo .
Thusa batho ba bang .
Lentsoe ho qenehela kapa ho utloela bohloko le ka bolela “ ho utloa bohloko hammoho . ”
Thusa batho linakong tsa likoluoa .
Jehova ke mohlala o motle oa ho utloela batho bohloko .
“ E - ba sebete u be matla ’ me u nke bohato .
LIPINA : 60 , 29
Ke joang bacha le batsoali ba ka bontšang hore ba sebete ?
1 , 2 . ( a ) Solomone o ile a fuoa mosebetsi ofe oa bohlokoa ?
O ne a lokela ho ba sebete e le hore a etse mosebetsi oo .
E ka ’ na eaba ke’ng eo Solomone a ileng a ithuta eona ho ntate oa hae ?
Ke hobane’ng ha Solomone a ne a lokela ho ba sebete ?
( Bala 1 Likronike 28 : 20 . )
Ke hobane’ng ha re lokela ho ba sebete ?
Ke’ng eo u e ratang ka tsela eo Josefa a ileng a etsa lintho ka eona ?
Rahaba le eena o ile a ba sebete .
Hore ebe Jesu o ne a le sebete , ho ile ha thusa baapostola ba hae joang ?
A re bueng ka maemo ao ho ’ ona ho hlokehang hore re be sebete , e leng ka lapeng le ka phuthehong .
( b ) Bacha ba ka ba etsisa Moshe joang ?
Jehova o tla boela a ba thuse ho hlokomela ba malapa a bona .
( Sheba serapa sa 13 ho ea ho 17 )
O re : “ Ha ke ntse ke hola ke ne ke le lihlong haholo , ke tšaba ho bua le batho ha ke le libokeng le tšimong . ”
Empa batsoali ba hae le ba bang ka phuthehong ba ile ba mo thusa hore e be pula - maliboho ea kamehla .
O re : “ Batho bao e seng Lipaki ba khothalletsa bacha ho kena sekolo e le hore ba be le maruo ba be ba tume .
Batsoali ba Bakreste le bona ba lokela ho ba sebete .
Lengolo la Pesaleme ea 37 : 25 le la Baheberu 13 : 5 le ka thusa batsoali joang ?
( Bala Pesaleme ea 37 : 25 ; Baheberu 13 : 5 . )
Mor’abo rona e mong ea nang le bana ba babeli o re : “ Batsoali ba bangata ba qeta nako le chelete e ngata ba thusa bana ba bona hore ba kenelle lipapaling , ba ikhatholle le hore ba kene sekolo .
Ho bohlokoa le ho feta hore re qete nako le chelete ea rona re thusa bana ba rona hore ba sebeletse Jehova , e leng ntho e tla ba thusa hore ba be le kamano e ntle le eena .
Re thabela ho bona bana ba rona ba sebeletsa Jehova . Re boetse re thabela ho sebetsa le bona . ”
Fana ka mehlala ea maemo a re hlokang hore re be sebete ka phuthehong .
Morali’abo rona ea holileng o hloka ho ba sebete maemong afe ?
( a ) Barab’abo rona ba lokela ho ba sebete joang ?
( Bala Bafilipi 2 : 13 ; 4 : 13 . )
Re khothalletsa barab’abo rona bohle hore ba be sebete ’ me ba sebetse ka thata ka phuthehong .
Kahoo , a re beng sebete ’ me re sebeletseng Jehova .
LIPINA : 116 , 142
le ile la fetolelloa lipuong tse fapaneng ?
baeta - pele ba lekile ho le thibela ?
batho ba ne ba sa batle hore le fetoleloe ?
1 , 2 . ( a ) Bophelo bo ne bo tla ba joang hoja Bibele e ne e le sieo ?
Moapostola Petrose o ile a qotsa mantsoe a Esaia 40 : 8 .
( Bala 1 Petrose 1 : 24 , 25 . )
( Bala Tšenolo 14 : 6 . )
Hamorao , liphetolelo tse ling le tsona li ile tsa sebelisa lentsoe “ MORENA , ” ka Mangolong a Segerike a Bakreste .
Ke hobane’ng ha Phetolelo ea Lefatše le Lecha e ikhetha ?
( b ) Septuagint ea Segerike ke eng ?
( Bala Pesaleme ea 119 : 162 - 165 . )
Musiamo oa Libibele o ile oa buloa ntlo - kholo e Warwick , New York , U.S.A ka la 3 April , 2017 .
Sebaka sa lipontšo tsa mesebetsi ea bonono se bitsoa “ Lebitso la Molimo ka Bibeleng . ”
Re u memela hore u etele musiamo ona le limusiamo tse ling tse ntlo - kholo .
Re kopa u kene ho www.jw.org e le hore u ingolise .
Kena tlas’a MABAPI LE RŌNA > LIOFISI LE BOITSEBISO BO MABAPI LE HO ETA .
ha u fana ka puo ?
O ile a bala 2 Bakorinthe 1 : 3 , 4 e reng : “ Ntate oa mehauhelo e bonolo le Molimo oa matšeliso ’ ohle . . . ea re tšelisang matšoenyehong ’ ohle a rōna . ”
Barab’abo rona ba fanang ka lipuo ba na le boikarabelo bofe ?
Re motlotlo hore ebe Jehova o re file Bibele .
Sheba lebokose le reng “ Liphetoho Bophelong ba ka . ”
Le bale kamehla
Nahanisisa ka lintho tseo u li balileng
Sebelisa likeletso tseo u ithutileng tsona
Nka nako ha u etsa lipapiso , ha u bala Mangolo leha u a hlalosa , ’ me u a sebelise hantle
“ Ke ne ke se ke e - na le lilemo tse ka bang 15 ke kolobelitsoe .
Ka letsatsi le leng ha ke le libokeng , sebui se ile sa bua ka Lengolo la Jakobo 1 : 23 , 24 .
“ Ka mor’a matsatsi a seng makae , ke ile ka bala Lengolo le ileng la fetola tsela eo ke neng ke nahana ka eona .
Ke Lengolo la Esaia 1 : 18 . Le re Jehova o re : ‘ Joale , tloong ’ me re lokiseng litaba pakeng tsa rōna . . . .
Le hoja libe tsa lōna li ka ba joaloka sekareleta , li tla soeufala joaloka lehloa . ’
E ne eka Jehova o re ho ’ na : ‘ Victoria , a re lokise litaba .
Kea u tseba ebile ke tseba libe tsa hao . Empa ke tseba pelo ea hao . Kea u rata . ’ ”
“ Ke ile ka hlobaela bosiung boo .
Empa e ne eka ke re ho eena : ‘ Ha u nthate ka tsela e lekaneng .
Sehlabelo sa Mora oa hao ha sea lekana hore se tlose libe tsa ka . ’
Empa ka mor’a hore ke nahanisise ka sehlabelo sena , ke ile ka hlokomela kamoo Jehova a nthatang kateng . ”
Lihloohong tsena re tl’o hlahloba lipono tseo Zakaria a ileng a li bona , e leng pono ea botšelela , ea bosupa le ea borobeli .
31 E - ba Mokreste ea Mosa
Joalokaha ho boletse Olive Matthews
E re ke qale pele ka ho le bolella pale ea bophelo ba ka .
KE HLAHILE ka 1923 motseng oa Hemsworth , o Yorkshire , naheng ea Engelane .
Lebitso la hae ke Robert .
Selemong se latelang ke ile ka khethoa hore ke be pula - maliboho e khethehileng le Mary Henshall .
Re ile ra romeloa tšimong e sa sebetsoeng khafetsa seterekeng sa Cheshire .
Ke ile ka kopana le Arthur Matthews ka 1946 .
Ka mor’a moo ra qala ho ngollana mangolo .
Re Hemsworth ka mor’a lenyalo la rona ka 1949
Abuti oa ka le mohats’a hae Lottie ba ne ba se ba ntse ba le Northern Ireland e le bo - pula - maliboho ba khethehileng .
Ka 1952 , bone ba rona re ile ra ea kopanong ea setereke e neng e tšoaretsoe Belfast . Mor’abo rona e mong o ile a re amohela kaofela lelapeng la hae .
Bosiung boo , bone ba rona re ile ra robala ka koloing .
E ile ea e - ba ntlo ea rona ka mor’a moo .
Bo - rapolasi ba mosa ba ile ba re lumella ho paka k’haravene eo mapolasing a bona .
Re ne re thabela mosebetsi oa rona oa potoloho .
Kopano ea pele ea machaba naheng ea Ireland e ne e tšoaretsoe Dublin ka 1965 .
Batho ba 3 948 ba ile ba e - ba teng kopanong eo ’ me ha kolobetsoa ba 65 .
Arthur o lumelisa mor’abo rona Nathan Knorr kopanong ea 1965
Arthur o lokolla Buka ea ka ea Lipale Tsa Bibele Gaelic ka 1983
Ka 2011 ofisi ea lekala ea Brithani e ile la kopanngoa le ea Ireland eaba rona re isoa Bethele e London .
O ne a tšoeroe ke lefu la Parkinson .
Lilemong tsa ho qetela tsa bophelo hae ke ile ka nyahama , ka utloa bohloko ka ba ka siama .
Ho feta mathateng a tšoanang le ana ho u atametsa haufi le Jehova .
“ A re se keng ra rata ka lentsoe kapa ka leleme , empa re rate ka ketso le ’ nete . ” — 1 JOH . 3 : 18 .
LIPINA : 72 , 124
Lerato la ’ nete ke le joang ?
“ Lerato le se nang boikaketsi ” ke le joang ?
Jehova o bontšitse joang hore o rata batho ?
Jehova o ile a bontša hore o rata batho le pele a bopa Adama le Eva .
Re ka bontša joang hore re rata batho e le kannete ?
6 , 7 . ( a ) “ Lerato le se nang boikaketsi ” ?
Re lokela ho ipotsa potso efe ?
( Bala Matheu 6 : 1 - 4 . )
( Bala Baroma 12 : 10 . )
Re ka babatsa batho ka tsela e se nang boikaketsi joang ?
Re lokela ho etsa’ng ha re amohela baeti ?
Amohela baeti .
( Bala 1 Johanne 3 : 17 . )
Bopa khotso .
( Bala Baroma 12 : 17 , 18 . )
Re ka bontša joang hore re tšoarela ka bolokolohi ?
Itelle Bakreste - ’ moho .
Lerato la ’ nete ke la bohlokoa hakae ?
Lerato le bohlokoa ho feta makhabane a mang kaofela .
LIPINA : 125 , 135
Ke “ sabole ” efe eo Jesu a ileng a re o tla e tlisa ?
U ka lula u tšepahala ho Jehova joang ha beng ka uena ba hanyetsa tumelo ea hao ?
3 , 4 . ( a ) Lithuto tsa Jesu li ile tsa ba le liphello life ?
Jesu o ile a re : “ Le se ke la nahana hore ke tletse ho tlisa khotso lefatšeng ; ke tletse ho tlisa sabole , eseng khotso .
Kaha ke tletse ho baka karohano , ho motho khahlanong le ntat’ae , le morali khahlanong le ’ m’ae , le mosali e mocha khahlanong le ’ m’ae matsale .
Balateli ba Jesu ba ile ba mamella eng ?
Bakreste ba ka thusa bana ba bona ho hlompha motsoali eo e seng Paki joang ?
Ho e - na le hoo , ba hlalosetse hore ba lokela ho iketsetsa qeto ea hore na ba tla sebeletsa Jehova kapa che .
Bua ka bonolo .
Bibele e re : “ Seo le se buang kamehla e ke e be se nang le mosa . ”
( Bala 1 Petrose 3 : 1 , 2 , 16 . )
Rera esale pele .
U ka etsa’ng haeba u ikutloa u le molato ka hore ebe ha u utloane le beng ka uena ?
Jehova oa tseba hore taeo ea hae e tla ruisa bohle molemo , ho akareletsa le mofosi ea khaotsoeng .
( Bala Baheberu 12 : 11 . )
Bahoeletsi ba paka ka litoroli phatlalatsa toropong e ’ ngoe motse - moholo Lagos , o mong oa metse e meholo ka ho fetisisa Afrika .
LIPINA : 120 , 117
Boemo ba Baiseraele ka nako eo e ne e le bofe ?
( Bala Zakaria 1 : 3 , 4 . )
Khaolo ea bohlano ea lengolo la Zakaria e qala ka pono e makatsang .
( Bala Zakaria 5 : 1 , 2 . )
Bala Zakaria 5 : 3 , 4 .
8 - 10 . ( a ) Kano ke’ng ?
Pono ea botšelela ea Zakaria e re thusa ho hlokomela eng ?
( Bala Zakaria 5 : 5 - 8 . )
( Bala Zakaria 5 : 9 - 11 . )
LIPINA : 17 , 136
Mosebetsi o moholo o ntseng o tsoela pele mehleng ee o etsa hore u ikutloe joang ?
( Bala Zakaria 6 : 1 - 3 . )
Jehova o ntse a sebelisa mangeloi ho sireletsa le ho matlafatsa batho ba hae
7 , 8 . ( a ) Lithaba tse peli li emela’ng ?
( b ) Ke hobane’ng ha li entsoe ka koporo ?
Ke hobane’ng ha lithaba tseo li entsoe ka koporo ?
Bapalami ba likoloi ke bo - mang , hona ba fuoe mosebetsi ofe ?
( Bala Zakaria 6 : 5 - 8 . )
( Bala Zakaria 6 : 9 - 12 . )
( Bala Zakaria 6 : 13 . )
Kahoo , borapeli ba ’ nete bo tla be bo tsosolositsoe ka ho feletseng .
( Bala Zakaria 6 : 15 . )
Empa mantsoe a Jehova a ne a profeta ntho e kholo e neng e tla etsahala mehleng ea rona .
Jehova a ke ke a lebala mesebetsi eo re mo etsetsang eona ( Sheba lirapa 18 le 19 )
NTATE oa John o kolobelitsoe lilemong tsa bo - 1950 a kolobeletsoa toropong ea Gujarat , India .
Ha ’ mè eo a amohela lengolo , a hlokomela leqeba monoaneng oa John ’ me a kopa ho mo thusa .
O ile a ea ho moruti oa hae , ’ me a mo botsa lipotso tse tšoanang le tseo a li botsitseng Paki eo a neng a buisana le eona .
Mpontše moo Bibele e reng Jesu ha se Molimo .
Mpontše moo e reng ha rea lokela ho rapela Maria .
Mpontše . ”
John ha aa ka a hlola a ea kerekeng e K’hatholike .
3 Binelang Jehova le Thabile
Ho na le lintho tsa bohlokoa tseo re ka ithutang tsona ka metse ea setšabelo ea mehleng ea Baiseraele .
LIPINA : 9 , 138
’ Mino o bohlokoa hakae borapeling ba rona ?
( b ) Re lokela ho binela Jehova joang , hona ke bo - mang ba lokelang ho li hula nthau ?
Balla mantsoe a eona holimo ka lentsoe le phefa .
( a ) Ho bula molomo haholo ho ka u thusa joang hore u khone ho bina ka lentsoe le phefa ?
( Sheba lirapa 11 ho ea ho 14 )
Hemela holimo
( Bala Esaia 12 : 5 . )
LIPINA : 49 , 65
( Bala Pesaleme ea 34 : 22 . )
( Bala Numere 35 : 24 , 25 . )
( Bala Joshua 20 : 4 . )
O ile a re : “ Ntho eona ena , ho etsoa ha lōna hore le hlomohe ka tsela ea bomolimo , ho hlahisitse ho tiea ho hoholo hakaakang ho lōna , e , ho itlosa molato ha lōna , e , khalefo , e , tšabo , e , tlholohelo , e , cheseho , e , ho lokisoa ha phoso ! ”
O re : “ Ke ile ka khaotsa ho ikutloa ke le molato .
Ke hobane’ng ha re lokela ho tšabela ho Jehova ?
Na Jehova ke setšabelo sa hao ?
LIPINA : 21 , 69
Re ka etsisa Jehova joang ha batho ba re foselitse ?
1 , 2 . ( a ) Jesu o ne a ikutloa joang ka Molao oa Jehova ?
Empa phoso e ne e le efe ?
( b ) Taba ee e re ruta’ng ka Jehova ?
( Bala Liketso 20 : 26 , 27 . )
Ke hobane’ng ha Bakreste ba lokela ho hlompha bophelo ?
( Bala Numere 35 : 20 - 24 . )
Joale , e - eang , ’ me le ithute hore na sena se bolela eng , ‘ Ke batla mohau , eseng sehlabelo . ’
Etsoe ke tlil’o bitsa baetsalibe , eseng batho ba lokileng . ”
U lokela ho qala pele ka ho kopa Jehova hore a u fe bohlale .
Kahoo , o re ruta ka Jehova le melao - motheo ea hae .
Baralib’abo rona ba babeli ba bua ka Bibele le motho ea rekisang toropong ea Tipitapa
LIPINA : 60 , 26
Moapostola Pauluse o ile a lemosa barapeli ba Jehova ka eng ?
Fana ka mohlala oa tsela eo batho bao e seng barapeli ba Jehova ba nahanang ka eona , le hore na menahano eo re ka e qoba joang
Hlokomelang : mohlomong ho ka ba le e mong ea tla le nka joaloka phofu ea hae ka filosofi le thetso ea lefeela ho ea ka neano ea batho , ho ea ka lintho tsa motheo tsa lefatše eseng ho ea ka Kreste . ”
“ Nka ba motho ea lokileng leha ke sa lumele ho Molimo . ”
( Bala Pesaleme ea 10 : 4 . )
“ U ntse u ka thaba leha u se na bolumeli . ”
( Bala Matheu 5 : 3 . )
Jehova o na le tokelo ea ho re etsetsa melao hobane ke eena ea re bopileng .
Joale , haeba leihlo leo la hao le letona le etsa hore u khoptjoe , u le honye ’ me u le lahlele hōle le uena . ”
Jesu o ile a re : “ Ha ho eo e ka bang lekhoba la benghali ba babeli ; kaha o tla hloea e mong ’ me a rate e mong , kapa o tla khomarela e mong ’ me a nyelise e mong .
( Bala 1 Bathesalonika 2 : 13 , 19 , 20 . )
“ Batho ba ka khona ho itharollela mathata . ”
Re ka etsa’ng ho qoba menahano ea lefatše ?
LIPINA : 32 , 134
Malapa a ka etsa’ng e le hore a fumane moputso ?
( b ) Ke’ng e tla re thusa ho lula re letetse ka tjantjello litlhohonolofatso tseo Jehova a tl’o re tlisetsa tsona ?
Re ka etsa’ng haeba ho ka hlaha boemo boo ho bona re lokelang ho ba seli haholo ?
Ho qoba ho mamela lipina le ho qoba ho shebella lifilimi tse buang ka boitšoaro bo litšila ho ka re thusa ho loantša litakatso tse fosahetseng .
Tsoelang pele le mamellana le ho tšoarelana ka bolokolohi haeba leha e le mang a e - na le sesosa sa pelaelo khahlanong le e mong .
Esita le joalokaha Jehova a ile a le tšoarela ka bolokolohi , le etse joalo le lōna .
( Bala Moeklesia 7 : 21 , 22 . )
10 , 11 . ( a ) Ke hobane’ng ha ho le kotsi ho ba mona ?
Bibele e re : “ Lerato lea tiisetsa ’ me le mosa .
Lerato ha le boulele . ”
Le rona re ka ba mosa le ho ba lerato joaloka Jonathane .
Lōna banna , le ’ ne le rate basali ba lōna ’ me le se ke la ba halefela ka matla .
Lōna bana , le mamele batsoali ba lōna nthong e ’ ngoe le e ’ ngoe , etsoe sena se khahlisa haholo Moreneng .
Mor’abo rona o lokela ho etsa’ng haeba molekane oa hae eo e seng Paki a sa mo hlomphe ?
( Sheba lirapa 13 ho ea ho 15 )
Bibele e re : “ Mang kapa mang ea tšoarang lipolelo tsa hae o na le tsebo , ’ me motho ea nang le temoho o na le moea o khutsitseng . ”
3 “ Kea Tseba Hore o Tla Tsoha ”
Lihlooho tsena li tla re thusa ho ba le tšepo ea hore bafu ba tla fela ba tsohe .
11 : 11 .
LIPINA : 129 , 154
Ke tlaleho efe e ka Bibeleng e ileng ea kholisa Maretha hore ho tla ba le tsoho ea bafu ?
Joaloka Maretha , u lebeletse ho bona liketsahalo life tse thabisang ?
Empa o ile a re : “ Kea tseba hore o tla tsoha . ”
Hamorao mora oa hae o ile a kula ’ me a shoa .
( Bala 1 Marena 17 : 17 - 24 . )
( Bala 2 Marena 4 : 32 - 37 . )
Petrose o ile a thusa mosali e mong oa Mokreste joang ?
Ka nako e ’ ngoe moapostola Pauluse o ne a le motseng oa Troase oo hona joale o bitsoang Turkey ’ me moo o ne a le sebokeng se neng se tšoaretsoe kamoreng e ka holimo .
Mohlankana e mong ea bitsoang Eutikase o ne a mametse a lutse fensetereng .

Leha ho le joalo , ha ho bolele hore Molimo eena a ke ke a khona ho tsosa motho .
( Bala Jobo 14 : 13 - 15 . )
LIPINA : 111 , 12
( b ) Ke hobane’ng ha thuto ea tsoho e le bohlokoa hakaale ?
Empa na tsoho ke e ’ ngoe ea lithuto tseo u li ratang ka ho fetisisa ?
( Bala 1 Bakorinthe 15 : 12 - 19 . )
Haeba re lumela joalo , re tla be re fapane le Basaduse ba neng ba sa lumele ho hang hore bafu ba ka tsosoa .
Ke joang boprofeta bo hlahang ho Pesaleme ea 118 bo neng bo bua ka Jesu ?
“ Lihahi ” li ne li sa lumele hore Jesu ke eena Mesia ( Sheba serapa 7 )
Ke joang Jesu e neng e tla ba “ hlooho ea sekhutlo ” ?
Jesu e ne e tla ba “ hlooho ea sekhutlo ” joang empa Bajuda ba ile ba mo bolaea ?
( a ) Pesaleme ea 16 : 10 e buile ka eng esale pele ?
( Bala Liketso 2 : 29 - 32 . )
( Bala Liketso 2 : 33 - 36 . )
( Bala Liketso 13 : 32 - 37 , 42 . )
Ho na le lintho tseo re sa li tsebeng mabapi le “ linako kapa mehla eo Ntate a e behileng ka taolo ea hae . ”
Pauluse o ile a re “ Kreste o tsositsoe bafung , litholoana tsa pele ho ba robetseng lefung . ”
Ho tla etsahala’ng ka batlotsuoa ba bang nakong ea ho ba teng ha Kreste ?
Haeba tumelo ea rōna ke hore Jesu o ile a shoa eaba o tsoha hape , kahoo , hape , ba robetseng lefung , . . . o tla ba tlisa hammoho le eena . . .
Rōna ba phelang ba ntseng ba setse ho fihlela ho beng teng ha Morena ka tsela leha e le efe re ke ke ra raka ba robetseng lefung ; hobane Morena o tla theoha leholimong ka mohoo o laelang , . . . ’ me ba shoeleng bonngoeng le Kreste ba tla tsoha pele .
Batlotsuoa ba tla be ba ntse ba phela nakong ea matšoenyeho a maholo ba tla “ nkeloa marung . ”
Joalokaha ho boletse Felix Fajardo
Athe ha u ka khutla teng , ke tla u roba maoto ana . ”
Ho li bala ho ile ha etsa hore ke batle ho ba molateli oa Jesu Kreste . — Joh .
10 : 27 .
Ka nako eo , batsoali ba ka ba ile ba batla hore ke khutlele lapeng .
E mong oa Lipaki tseo o ile a tla lapeng ’ me a re hlalosetse hore na Bibele e re’ng ka ‘ matsatsi a ho qetela . ’
O ile a re memela ho tla thutong ea Bibele e neng e tla tšoareloa motseng o mong o haufinyane .
Bosiu bo ile ba batla bo e - sa tšekhe ! re ntse re tšohla Bibele .
Ke ile ka araba ka re : “ E ! Kea batla . ”
Ke ne ke kholisehile hantle hore ke batla ho ba ‘ lekhoba la Monghali , Kreste . ’
Ka la 15 February , 1946 , re ile ra kolobetsoa re le babeli feela nokeng e ’ ngoe e haufinyane .
Ba ha Cruz ba ile ba ’ memela ho ea lula le bona Angat .
O ne a e fana ka Senyesemane ’ me ’ na ke ne ke e akaretsa ka puo ea Setagalog .
Ke ile ka ba e mong oa ba ileng ba fuoa memo .
Hoseng ke ne ke sebetsa kichineng .
Ka mor’a ho fumana lengolo la Gileade , ke ile ka sebetsa ke le pula - maliboho e khethehileng ka nakoana toropong ea Bronx e New York City .
Beke ka mor’a hore re nyalane re ile ra chakela phuthehong e sehlekehlekeng sa Rapu Rapu .
Ke fetolela puo ea mor’abo rona Albert Schroeder
Re ile ra qetella re rekile le setša sa ntate eane ea ileng a re : “ Rona Machaena rea reka ha re rekise . ”
O ne a ka holela ka har’a mothapo oa popelo ( fallopian tube ) kapa ka popelong .
Kahoo , leseanyana le ke ke la phela .
Loop e nang le koporo e nyenyane ha e na matla a makaalo a ho thibela pelehi . ”
LIPINA : 130 , 88
tseba lingoliloeng tse halalelang ?
susumelletsoa ho lumela ?
hlalefisetsa poloko ?
( a ) Ho bolela’ng ho ‘ susumelletsoa ho lumela ’ ?
( b ) Ke’ng e re bontšang hore Timothea o ile a susumelletsoa ho lumela hore Jesu ke Mesia ?
Ho nka nako hore motho a be le tumelo e matla .
( Bala Baroma 12 : 1 . )
Re thaba haholo ha a re botsa lipotso .
Ke ne ke tla tšoenyeha haeba a ka lumela ntho e ’ ngoe le e ’ ngoe , a sa botse letho . ”
Na ba utloa Bibele e hlalosa lintho ka tsela e utloahalang ?
U lokela ho etsa’ng ho thusa ngoana oa hao hore a be le tumelo e matla ?
Morali’abo rona Stephanie ea nang le barali ba bararo o re : “ Ho tloha ha barali ba ka ba sa le banyenyane , ke ne ke atisa ho re , ‘ Na ke bolella bana ba ka hore na ke kholisoa ke’ng hore Jehova o teng , hore oa re rata le hore melao ea hae e nepahetse ?
Na bana ba ka baa bona hore ehlile ke rata Jehova ? ’
Nke ke ka lebella hore bana ba ka ba be le tumelo haeba ’ na ke se na eona . ”
Bohlale bo fapane le booatla . ”
Ke bona bohlale bo hlokehang e le hore motho a bolokehe .
( Bala Liproverbia 24 : 14 . )
Ke hobane’ng ha ho le bohlokoa hore batsoali ba lule ba thusa bana ba bona ?
( Sheba lirapa 14 ho ea ho 18 )
( Bala Mareka 12 : 30 . )
Batsoali ba ka thusa bana ba bona joang ho ba “ hlalefisetsa poloko ” ?
Kena tlas’a LITHUTO TSA BIBELE > BACHA .
LIPINA : 41 , 89
U ka etsa’ng hore u sebeletse poloko ea hao ?
Ke hobane’ng ha ho kolobetsoa ho le bohlokoa hakaale ?
U lokela ho lula u hopola taba ena hobane ha u tsebe mathata a tla u hlahela ka moso .
Empa ha a se a le lilemong tsa bocha ’ me litakatso tsa bocha li se li le matla , o lokela ho kholiseha hantle hore ho mamela melao ea Jehova ho tla mo thusa haholo . ”
( b ) Bafilipi 4 : 11 - 13 e u ruta’ng ?
Ho ‘ sebeletsa poloko ea hao ka tšabo le thothomelo ’ ho bolela’ng ?
Jehova o batla hore u be motsoalle oa hae .
( Sheba lirapa 8 ho ea ho 11 )
Ke lintho life tse u thusitseng ho utloisisa Bibele haholoanyane ?
Nka Etsa Joang Hore ke Natefeloe ke ho Bala Bibele ? ”
( Bala Bafilipi 4 : 6 . )
Le uena e ka u thusa .
Ke’ng e ka u thusang ?
Ka linako tse ling ke ee ke ipuele feela ke re , ‘ Ka letsatsi le leng ha ke ntse ke ithuta Bibele le motho . . .
’ Ebe ka mor’a moo , ke itsoella pele ka litaba tsa ka .
Le hoja ke ne ke sa bue le bona hakaalo - kaalo ka Bibele , ba bangata ba batla ho tseba hore na ke etsa’ng ha ke ithuta Bibele le batho .
Ka linako tse ling ba mpotsa lipotso mabapi le Bibele .
Kahoo , ho ba bonolo ho buisana le bona ka Bibele haeba ke etsa joalo .
Ka mor’a moo , ke ee ke utloe ke thabile haholo . ”
Kahoo , tsela eo ke itšoereng ka eona e tla etsa hore ba ’ mamele kapa ba se ke ba ’ mamela ha ke bua le bona ka Bibele hobane ke ’ na feela Paki eo ba e tsebang .
Empa haeba re bua le bona re phutholohile , re bonahala hore re kholisehile ka litaba tseo re ba bolellang tsona , ba ka re hlompha . ”
Jesu o ile a re : “ Haeba mang kapa mang a batla ho ntšala morao , a ke a itatole ’ me a nke thupa ea hae ea tlhokofatso a ntatele a sa khaotse . ”
© 2018 Watch Tower Bible and Tract Society of Pennsylvania
27 Bona Phapang Pakeng tsa Batho ba Sebeletsang Jehova le ba sa mo Sebeletseng
LIPINA : 152 , 67
Esaia 40 : 26
Matheu 11 : 28 - 30
2 Bakorinthe 12 : 9 , 10
Re ithuta’ng Lengolong la Esaia 40 : 26 ?
Bala Esaia 40 : 26 .
Ha ho motho ea kileng a khona ho bala linaleli tsohle tse teng sepakapakeng .
Ke’ng e re kholisang hore Jehova a ka khona ho re matlafatsa ?
Bala Esaia 40 : 28 .
Bala Esaia 40 : 29 .
A boela a re : “ Le tla fumanela meea ea lōna khatholoho .
Etsoe joko ea ka e mosa le mojaro oa ka o bobebe . ”
Sebui se ne se bua ka tsela e mosa hoo ke ileng ka lla .
Puo eo e ile ea nkhopotsa hore ke lokela ho lula ke e - ba teng libokeng . ”
Moapostola Pauluse o ne a bolela’ng ha a re : “ Ha ke fokola , joale ke ha ke le matla ” ?
Bala Esaia 40 : 30 .
O ile a re : “ Ka uena nka matha khahlanong le sehlopha sa bafutuhi .
Bala Esaia 40 : 31 .
Empa na Jehova o ne a lahlile Josefa ?
Mohlala o mong ke oa Davida .
Bala Baefese 4 : 26 .
Kapa na re tla mamela keletso ea Bibele ea hore re lokise litaba kapele ?
Molimo oa mo rata .
Ha u bua le eena u ka ’ na oa qala ka ho re : ‘ Ha ke tsebe haeba ke tla be ke feteletsa lintho , empa maobane ha re ne re bua , ke ile ka ikutloa . . .
O ile a re : “ Qetellong ka bolela sebe sa ka ho uena , ’ me phoso ea ka ha kea ka ka e koahela . ”
LIPINA : 149 , 99
Sehopotso se u tsoela molemo joang ?
Re tl’o araba lipotso life sehloohong see ?
( 4 ) Na ho na le mohla re tla tšoara Sehopotso ka lekhetlo la ho qetela ?
( Bala Johanne 3 : 16 ; 17 : 3 . )
( a ) Jesu o ile a rapella eng bosiung ba pele ba Lijo Tsa Shoalane Tsa Morena ?
( b ) Ke’ng e bontšang hore Jehova o ile a araba thapelo ea Jesu ?
( Bala Johanne 17 : 20 , 21 . )
( Bala Ezekiele 37 : 15 - 17 . )
Re ka etsa’ng hore phutheho e lule e momahane ?
( Bala Matheu 18 : 35 . )
Re ka bontša joang hore re ‘ mamellana ka lerato ’ ?
Ho e - na le hoo , o ile a re re “ mamellane ka lerato . ”
Re tseba joang hore ho na le mohla re tla tšoara Sehopotso ka lekhetlo la ho qetela ?
( Bala Pesaleme ea 133 : 1 . )
Banyalani ba babeli ba bo - pula - maliboho ba laela lingoliloeng sefofaneng motseng oa Riberalta .
LIPINA : 95 , 2
Ke hobane’ng ha Jehova a batla hore re mo fe lintho tsa rona tsa bohlokoa ?
Mokhatlo oa Jehova o sebelisa chelete ea monehelo joang mehleng ee ?
JEHOVA ke Molimo ea fanang .
Ke hobane’ng ha re fa Jehova lintho tseo re nang le tsona ?
( Bala Liproverbia 29 : 21 . )
Boholo ba rona re fana ka menehelo boinotšing .
( Bala 2 Bakorinthe 8 : 18 - 21 . )
Le ka boela la sheba mekhoa eo ka eona le ka nolofatsang bophelo e le hore le eketse nako eo le e qetang le sebeletsa Jehova .
Ha u fana ka monehelo , u tšehetsa mosebetsi o etsoang lefatšeng ka bophara ( Sheba lirapa 14 - 16 )
Kahoo , ka linako tse ling re ikutloa re le metoaitoai ebile re lebala kamoo mosebetsi oa Jehova o leng mongata kateng .
Empa ka mor’a ho shebella Khaso ea JW , re ile ra hopola hore re karolo ea mokhatlo oa bara ba motho .
Bara le barali babo rona ba mona ba thabetse khaso ena haholo .
Hangata ka mor’a ho shebella khaso ena ea khoeli le khoeli , re ee re utloe ba re ba utloa eka ba se ba tseba litho tsa Sehlopha se Busang .
Hona joale ba ikutloa ba le motlotlo ho feta leha e le neng pele hore ebe ke karolo ea mokhatlo oa Molimo . ”
( Bala Liproverbia 11 : 24 , 25 . )
Sehlooho see se u thusitse joang ?
LIPINA : 75 , 73
Ke tsela eo Jehova a re bopileng ka eona .
Ea ratang mosali oa hae oa ithata , kaha ha ho motho ea kileng a hloea nama ea hae ; empa oa e fepa le ho e baballa . ”
( Bala Baroma 12 : 3 . )
Ke’ng e ka re thusang hore re se ke ra ithata ho tlola kapa ra rata chelete le menyaka ho feta tekano ?
Pauluse o ile a re batho e tla ba “ ba ratang chelete . ”
Le hoja batho ba bangata ba ke ke ba ipuela ’ nete feela joaloka ntate eo , ba ikutloa joaloka eena .
Agure o ile a re’ng ka borui le bofutsana ?
( Bala Moeklesia 5 : 12 . )
O ile a re : “ E le hore ke se ke ka khora eaba kea u latola ’ me ke re , ‘ Jehova ke mang ? ’ ”
O ne a lula a re , ‘ Ke na le mohiri ea molemo ka ho fetisisa . ’
Joale kaha le ’ na ke se ke le pula - maliboho , re sebeletsa Motho a le mong , e leng Jehova . ”
Ke’ng e ka re thusang hore re se ke ra ithata ho tlola kapa ra rata chelete le menyaka ho feta tekano ?
( Sheba lirapa 7 , 13 le 18 )
Empa e re ha ba mo rate ho hang . ”
Ke’ng e ka re thusang hore re se ke ra ithata ho tlola kapa ra rata chelete le menyaka ho feta tekano ?
LIPINA : 61 , 53
Re ka etsa’ng hore re se ke ra ba baithati
Re boetse rea tseba hore lerato “ ha le ithorise , ha le ikhohomose . ”
Kahoo , ke ne ke ba mamela .
Kaha ke ne ke hlokomela hore baa nthata , ho ne ho e - ba bonolo hore ke batle ho ba khahlisa . ”
( Bala Johanne 13 : 34 , 35 . )
( Bala Esaia 11 : 6 , 7 . )
U ka bala lipale tsa bophelo ba bona lihloohong tse reng “ Bibele e Fetola Batho ” tse hlahang ho jw.org .
Re tsebise batho hore re Lipaki Tsa Jehova .
3 Etsisa Noe , Daniele le Jobo
28 Molimo o re Thusa Hore re Thabe
LIPINA : 120 , 54
Daniele ?
Jobo ?
9 , 10 . ( a ) Ke joang re ka mamelang Molimo le ho ba le tumelo joaloka Noe ?
( Bala Malakia 3 : 17 , 18 . )
( b ) Jehova o ne a ikutloa joang ka Daniele ?
( b ) Batsoali ba ka ithuta eng ho batsoali ba Daniele ?
( Bala Jobo 1 : 9 , 10 . )
19 , 20 . ( a ) Re ka etsisa Jobo joang ?
LIPINA : 43 , 133
1 - 3 . ( a ) Ke’ng e tla re thusa ho lula re tšepahala nakong ee ea bofelo ?
( Bala Daniele 6 : 7 - 10 . )
Jobo e ne e se Moiseraele .
( Bala Jobo 31 : 24 - 28 . )
( Bala Pesaleme ea 11 : 5 ; 26 : 4 . )
Joale ipotse : ‘ Na ke tseba Jehova hantle joalokaha Noe , Daniele le Jobo ba ne ba mo tseba ? ’
Ntate oa ntate moholo oa Noe e leng Enoke , le eena o ile “ a tsamaea le Molimo oa ’ nete . ”
Jesu o ile a re : “ Ntat’a lōna Abrahama o ile a thaba haholo ka tebello ea ho bona letsatsi la ka . ”
Thabo ea rona ha e hlalosehe . ”
Etsoe Molimo o re senoletse tsona ka moea oa hae . ”
Jesu o ile a re : “ Ke le boleletse lintho tsena , e le hore thabo ea ka e ka ba ho lōna ’ me thabo ea lōna e be e feletseng . ”
O roetse tuku ea setso
LIPINA : 84 , 5
Motho ea nang le kamano e ntle le Molimo ke ea joang ?
( 3 ) Ho ba le “ kelello ea Kreste ” ho ka re thusa joang ho matlafatsa kamano ea rona le Molimo ?
( Bala 1 Bakorinthe 2 : 14 - 16 . )
Pauluse o re khothalletsa ho ba le kamano e ntle le Molimo .
Bibele e re’ng ka batho ba nang le kamano e ntle le Molimo ?
Re ka holisa setsoalle sa rona le Jehova joang ?
Re ka ithuta’ng ho Jakobo le Maria ? (
Re ka ithuta’ng ho Jakobo le Maria ? (
( Bala Luka 1 : 46 - 55 . )
( Bala Esaia 63 : 9 ; Mareka 6 : 34 . )
Morali’abo rona Rachel oa Brazil o re : “ Kaha ke ne ke rata feshene , ke ne ke sa apare ka tsela e hlomphehang .
Le hoja ho ne ho se bonolo ho etsa liphetoho , ke ile ka thaba ’ me bophelo ba ka ba ntlafala . ”
Joale ha re etsisa Jesu , re tla etsa lintho joaloka Jehova .
Ba ile ba re : “ Re lipaki tsa lintho tsohle tseo a ileng a li etsa . ”
Re tla rua molemo ofe ka ho nahana joaloka Kreste ?
LIPINA : 136 , 10
Ho nahana joaloka Jesu ho ka u tsoela molemo joang ?
Leha ho le joalo , o ne a sa nke ho sebeletsa Jehova e le eona ntho e tlang pele bophelong ba hae .
O re : “ Ha ho letho le phoso leo ke neng ke le etsa . Empa ke ne ke etsa lintho feela ho ea ka tloaelo .
Empa ho ne ho e - na le ntho e haellang . ”
O re : “ E ne eka ha ho letho leo ’ na ke le tsebang .
Ke ile ka nahana ka re , ‘ Haeba ke batla ho ba hlooho e nepahetseng bakeng sa mosali oa ka , ke lokela ho etsa liphetoho . ’ ”
O re : “ Ke ile ka ithuta Bibele khafetsa - khafetsa eaba ke qala ho e utloisisa .
Taba ea bohlokoa le ho feta ke hore ke ile ka ba le kamano e ntle le Jehova . ”
( 3 ) Ho lula re e - na le kamano e ntle le Jehova ho ka re tsoela molemo joang ?
( b ) Sepheo sa rona e lokela ho ba sefe ha re ithuta Lentsoe la Molimo ’ me re nahanisisa ka lintho tseo re ithutileng tsona ?
( b ) Ke mohlala ofe o hlahang ka Bibeleng oa motho eo re ka mo etsisang ?
12 , 13 . ( a ) Re ka thusoa ke’ng ho mamela keletso e ho Baroma 15 : 5 ?
Nahana ka moapostola Petrose .
( Bala 2 Petrose 1 : 5 - 8 . )
Ho nahana lintho ka tsela eo Jesu a nahanang ka eona , ho tla ama tsela eo re itšoarang ka eona ha re le mosebetsing kapa sekolong .
Jesu o ne a tla etsa’ng boemong boo ?
( E bale . ) ‘ Mesebetsi e shoeleng ’ eo re lokelang ho e qoba ke efe ?
Na liqeto tsa ka li tla nthusa hore ke be le kamano e matla le Jehova , ke ikemisetse ho mo sebeletsa ’ me ke “ be le khotso le batho bohle ” ?
Khetha ho sebeletsa Jehova .
Ke hobane’ng ha u ikemiselitse ho holisa kamano ea hao le Jehova ?
Ke khotsofetse ebile ke thabile . ”
3 Bakreste ba Lokela ho Kolobetsoa
Moapostola Petrose o ile a khothatsa Bakreste ba mehleng ea hae a re : “ Bontšanang kamohelo ea baeti . ”
Re ka etsa’ng hore batho ba thabele ho re amohela malapeng a bona ?
Re lokela ho itšoara joang ha re khalemeloa ?
Re tla araba lipotso tseo sehloohong sena .
“ Ke hobane’ng ha u lieha ?
Ema , u kolobetsoe . ” — LIK . 22 : 16 .
LIPINA : 59 , 89
Bakolose 1 : 9 , 10
Moeklesia 12 : 1
Jakobo 4 : 17
Batsoali ba batla ho kholiseha ka eng pele bana ba kolobetsoa ?
BLOSSOM BRANDT o re : “ Ka likhoeli tse ngata ke ile ka bolella batsoali ba ka hore ke batla ho kolobetsoa .
Ke ile ka kolobetsoa ka la 31 December , 1934 . ”
Bala Matheu 28 : 19 , 20 .
5 , 6 . ( a ) Ho latela tsela eo Bibele e hlalosang Timothea ka eona , e ka ’ na eaba o kolobelitsoe a le mokae ?
( Bala Bakolose 1 : 9 , 10 . )
( Bala Jakobo 4 : 17 . )
Ke hobane’ng ha taba ee e le bohlokoa ?
A bolella Jehova hore o thabile hore ebe moralinyana oa hae o entse qeto ea ho inehela ho Eena . ”
LIPINA : 7 , 56
1 Petrose 3 : 20 , 21
Matheu 28 : 19 , 20
Liketso 22 : 16
( Bala 1 Petrose 3 : 20 , 21 . )
Bala Liketso 8 : 35 , 36 .
Ke hobane’ng ha re sa lokela ho qobella mang kapa mang hore a kolobetsoe ?
Haeba u motsoali , e ka ’ na eaba u ile oa ipotsa : ‘ Na ngoan’aka o se a loketse ho kolobetsoa ?
Ea pele e re : “ Motheong oa sehlabelo sa Jesu Kreste , na u baketse libe tsa hao ’ me u inehetse ho Jehova ho etsa thato ea hae ? ”
LIPINA : 124 , 119
Ho ba le kamohelo ea baeti ho ne ho tla ba tsoela molemo joang ?
Re ka etsa’ng hore batho ba thabele ho re amohela malapeng a bona ?
( Bala 3 Johanne 5 - 8 . )
Ha mor’abo rona e mong oa Korea a hopola mohla a neng a amohetse batho ba tlileng Likolong Tsa Puso ea Molimo o re : “ Qalong ke ne ke le lesisitheho ho ba amohela hobane ’ na le mohats’a ka re ne re sa tsoa nyalana ebile ntlo ea rona e le nyenyane .
Empa re ile ra thaba haholo ho ba amohela .
Kaha re ne re sa tsoa nyalana , re ile ra ithuta hore batho ba sa tsoa nyalana ba ka thaba ha ba sebeletsa Jehova ’ moho . ”
Ke hobane’ng ha re lokela ho amohela batho ba sa tsoa fihla liphuthehong tsa rona ?
( Bala Luka 10 : 41 , 42 . )
Mantsiboeeng a mang mohats’a ka o ne a hlile a hlolohetsoe hae ’ me le boiteko ba ka ba ho mo thusa ha boa ka ba atleha .
Ha hora ea bosupa e fetile ka metsotso e 30 ha e - ba le motho ea kokotang monyako .
E ne e le morali’abo rona ea neng a tl’o amohela baromuoa .
O ne a re tletse le lilamunu tse tharo .
Re ile ra kopa hore a kene eaba re mo fa metsi .
Ka mor’a moo , re ile ra etsa tee .
Haeba u tšaba ho amohela baeti , ha u mong .
Moholo e mong oa Brithani o re : “ Ho tloaelehile hore motho a tšohe ha a lokisetsa ho amohela baeti .
Empa joaloka lintho tse ling tseo re li etsetsang Jehova , melemo ea ho ba amohela e mengata ho feta tsela eo re ka tšoenyehang ka eona .
Ke thabela ho lula le baeti re inoella kofi ’ me re qoqa . ”
Moholo e mong o re : “ Ha ke mema batho , ke ba utloisisa hamolemo , ke ba tseba haholoanyane ke be ke tsebe hore na ho tlile joang hore e be Lipaki . ”
Mohats’a e mong oa barupeli o ile a nthusa hore ke khobe matšoafo .
O ile a re ha eena le mohats’a hae e ne e le bapotolohi , libeke tseo ba neng ba li thabela ke tseo ba neng ba li qeta ba le ha motho oa mofutsana ea ratang Jehova a bile a mo sebeletsa joaloka bona .
Ke ile ka hopola mantsoe a Bibele ao ’ Mè a neng a atisa ho a bua a reng : ‘ Ho ja meroho moo ho nang le lerato , ho molemo . ’ ”
( Bala Liproverbia 25 : 21 , 22 . )
Batho ba memmeng , ba lokisetsa baeti ba bona ( Sheba serapa 20 )
Mopesaleme Davida o ile a re : “ Jehova , ke mang eo e tla ba moeti tenteng ea hao ? ”
Re boetse re lokela ho hlompha setso sa batho ba bang .
Ke hobane’ng ha ho le bohlokoa hore re ‘ bontšane kamohelo ea baeti ’ ?
Barab’abo rona ba babeli ba fana ka pampitšana ho ntate ea nkileng thepa ea ho penta . O lutse borokhong bo ka pel’a Kaštilac , e leng mohaho oa khale o haufi le toropo ea Split
LIPINA : 125 , 117
U tla choatla lintho tsa bohlokoa . ”
( Bala Tite 2 : 11 - 14 . )
Graham o ile a mo kopa hore a ithute Bibele le eena .
Moholo eo o ile a re : “ Bothata ba Graham e ne e le boikhohomoso .
O ne a lula a tšoaea - tšoaea liphoso baholo ba ileng ba sebetsa litaba tsa hae ha a tla khaoloa .
Ka mor’a ho bala le eena lithuto tse seng kae , re ile ra buisana ka Mangolo a buang ka boikhohomoso le hore na bo ka re ama joang .
Lentsoe la Molimo le ile la thusa Graham ho hlokomela hore o lokela ho fetoha .
O ile a hlokomela hore o ne a fahluoe ke ‘ leballo , ’ e leng boikhohomoso le hore o na le bothata ba ho tšoaea - tšoaea liphoso eaba kapele - pele oa fetoha .
O ile a qala ho ea libokeng kamehla , ho ithuta Bibele ka ho teba le ho rapela letsatsi le letsatsi .
O ile a re : ‘ Ke na le lilemo ke le Paki ea Jehova . Ke ne ke bile ke le pula - maliboho .
( Bala Luka 4 : 22 . )
Moapostola Petrose o ile a re : “ Lisang mohlape oa Molimo o tlhokomelong ea lōna , eseng ka ho qobelloa , empa ka ho rata ; eseng ka lebaka la lerato la leruo la ho se tšepahale , empa ka tabatabelo ; eseng ka ho rena ka thata holim’a bao e leng lefa la Molimo , empa le e - ba mehlala ho mohlape . ”
( Bala Esaia 11 : 9 . )
LIPINA : 64 , 120
Batsoali ba ka etsa’ng ho holisa bana ka tsela eo Jehova a e batlang ?
( Bala Baheberu 12 : 5 - 11 . )
Ngoana a ka thusoa ke’ng hore a khone ho ikhalemela ?
4 , 5 . ( a ) Ke hobane’ng ha ho ikhalemela ho le bohlokoa bakeng sa hore re apare “ botho bo bocha ” ?
( Bala Bafilipi 4 : 13 . )
Re ka etsa’ng hore re be liithuti tse khothetseng tsa Lentsoe la Molimo ?
Ka hore u mamele Jehova .
Mor’abo rona e mong ea lilemo li 21 o re : “ Ke leboha haholo hore ebe batsoali ba ka ba ile ba nkholisa ka tsela eo ba entseng ka eona .
( b ) Lelapa le leng le ile la rua molemo ofe ka ho mamela Jehova ?
Lilemo hamorao o ile a khutlisetsoa ka phuthehong .
Kamano ea rona le eena e matla haholo . ”
( b ) Re ka etsa’ng hore baholo ba nolofalloe ke ho etsa mosebetsi oa bona ?
Ke ile ka fela ka etsa joalo ’ me ha baa ka ba nkahlola kapa ba ’ nyenyefatsa .
Kamehla ha liboka li tsoa , ho sa tsotellehe hore na ba phathahane hakae , e mong oa bona o ne a mpotsa hore na ke ntse ke e - ea joang .
Ka lebaka la lintho tseo ke ileng ka li etsa nakong e fetileng , ho ne ho le thata hore ke lumele hore Jehova oa nthata .
Leha ho le joalo , nako le nako Jehova o sebelisa baholo hammoho le phutheho ho mpontša hore oa nthata .
Ke rapella hore le ka mohla ke se ke ka mo furalla . ”
Haeba u fetoha hore u etse se molemo , na ho phahamisoa ho ke ke ha e - ba teng ?
Empa haeba u sa fetohe hore u etse se molemo , sebe se laletse monyako , ebile sea u lakatsa ; na u tla se laola ? ”
Kahoo a re ‘ mameleng taeo ’ me re hlalefe . ’
3 U ka ba le Tokoloho ea ’ Nete Joang ?
Batho ba bangata ba batla tokoloho .
Bakreste ba lokela ho ba le maikutlo afe ka tokoloho ?
15 Etsisang Jehova ka ho Khothatsa Batho ba Bang
8 : 36 .
LIPINA : 65 , 52
Batho ba na le bolokolohi ba mofuta ofe , hona hobane’ng ?
Ho tlile joang hore re se hlole re e - ba le tokoloho ea ’ nete ?
Batho ba lokela ho tšepa Jehova le ho mo hlompha e le hore ba tle ba natefeloe ke bophelo .
Haeba ba sa mo mamele , ke bona ba tla iketsetsa qeto ea hore na ntho e nepahetseng le e fosahetseng ke efe . ’
Adama le Eva ba ne ba e - na le bolokolohi bo tšoanang le ba moqhobi eo .
Re lokela ho etsa’ng e le hore re be le bolokolohi ba ’ nete ?
O ile a re : “ Haeba le lula lentsoeng la ka , ka sebele le barutuoa ba ka , le tla tseba ’ nete , ’ me ’ nete e tla le lokolla . ”
Empa re tla lokoloha ho eng ?
Ke joang bolokolohi boo Jesu a buileng ka bona bo ka etsang hore re lokolohe e le kannete ?
Re ka etsa’ng hore re lokolohe e le kannete ?
( Bala Baroma 8 : 1 , 2 , 20 , 21 . )
LIPINA : 11 , 137
( c ) Re lokela ho ipotsa lipotso life ?
( Sheba tlas’a LIPUISANO LE LIPHIHLELO > HO MAMELLA LITEKO . )
Lintho tsohle li lumelloa ke molao ; empa hase lintho tsohle tse hahang . ”
Re ithuta’ng ho Noe le lelapa la hae ?
Ba ne ba phela har’a batho ba khopo ba bileng ba hlokang boitšoaro .
Jehova o re laetse hore re etse’ng mehleng ee ?
( Bala Luka 4 : 18 , 19 . )
Joale kea utloisisa hore na Lengolo la Jakobo 4 : 8 le bolela’ng ha le re : ‘ Atamelang ho Molimo , ’ me o tla atamela ho lōna . ’
Ke ne ke tseba hore ke fumane ntho eo esale ke e batla , e tla nkhotsofatsa bophelo bohle . ”
Pula - maliboho e khethehileng e bua le motho ka Bibele libakeng tse hole motseng oa Balykchy
BA BILENG TENG SEHOPOTSONG ( KA 2017 )
1 : 3 , 4 .
Baapostola ba ile ba khothatsa Bakreste - ’ moho le bona joang ?
Jehova o ile a khothatsa Noe joang ?
( b ) Jehova o ile a khothatsa Jesu joang ?
Ezekiase o ile a re’ng ha a khothatsa batho bohle ba Juda ?
Jafeta o ile a khoehla mangole ha a hopola tšepiso eo a e entseng .
Petrose o ile a ‘ matlafatsa barab’abo ’ joang ?
Empa ke u etselitse thapeli hore tumelo ea hao e se ke ea fela ; ’ me uena , hang feela ha u khutlile , u matlafatse barab’eno . ” — Luka 22 : 31 , 32 .
LIPINA : 121 , 119
Ke bo - mang ntle le baholo ba ka re khothatsang ?
Ke bo - mang ba hlokang ho khothatsoa , hona hobane’ng ?
Bala Esaia 32 : 1 , 2 .
Jesu o behetse baholo mohlala ofe ?
Ka hona cheseha ’ me u bake . ”
Ka mor’a moo , ka kopana le morali’abo rona e mong ea ileng a bua le ’ na ka mosa . E ne e le eona ntho eo ke neng ke e hloka .
Morena Solomone o itse : “ Lentsoe le buuoang ka nako ea lona e nepahetseng le molemo hakaakang !
Ho khanya ha mahlo ho thabisa pelo ; tlaleho e ntle e nontša masapo . ”
LIPINA : 89 , 24
Re tl’o ithuta’ng sehloohong see ?
Ho na le mabaka a mararo .
Etsoe u nthabisitse , Jehova , ka lebaka la mosebetsi oa hao ; Ke hoeletsa ka thabo ka lebaka la mesebetsi ea matsoho a hao . ”
Ha se hore u lokela ho ba motho e moholo hore u ikemisetse ho lula u rata Jehova .
Liproverbia 21 : 5 e re : “ Merero ea ea khothetseng e tlisa molemo . ”
Kahoo , ha u qala u sa le mocha ho ba le merero e metle eo u batlang ho e fihlela ka moso , merero eo e tla atleha .
Hoja ke ile ka ithutela ho ba akhente , nka be ke khola chelete e ngata , empa kaha ke ne ke tl’o qeta boholo ba nako ke theohetse , ke ne ke sa tl’o khona ho ba pula - maliboho . ”
Mor’abo rona Luca o ile a etsa joalo .
17 , 18 . ( a ) Jehova o batla hore ho etsahale’ng ka bacha ?
Satane ke sera sa rona .
Ke hlahetse motseng o monyenyane oa Liberty , o Indiana naheng ea Amerika .
Ke hlahlama bana ba bararo , e leng abuti le likhaitseli tse peli .
Ntlo e entsoeng ka likoqo eo re neng re lula ho eona
Lapeng re ne re le bana ba supileng ’ me ke ithutile lintho tse ngata ka temo
Ke ne ke hlile ke sa e utloisise .
Ba ne ba batla hore ke be lesole bophelo bohle ba ka .
E ne e le seboka se senyenyane seo ho sona batho ba neng ba ithuta Bibele le ho e tšohla .
Ke ile ka ba bolella hore ke tla inahana .
Lilemo pele ho moo , ha ke botsa ’ Mè ka Lipaki o ile a re : “ Oh , ba rapela monna - moholo e mong ea bitsoang Jehova . ”
Ke ile ka hlokomela hore Lipaki li mputse mahlo .
Jesu o ne a phethahetse a bile a le matla ho feta monna ofe kapa ofe oa sehanyata .
Ke qalile ho ba pula - maliboho ka 1958 .
Lebitso la hae ke Gloria .
Ha ho mohla nkileng ka ikoahlaela ho etsa qeto eo . Gloria ke lehakoe la pelo ea ka .
Le hoja re sa ka ra lahla tšepo , ho ne ho hlakile hore re tla lokela ho leta nako e telele .
Re ne re rata tšebeletso haholo .
Ke ile ka ithuta Bibele le morali oa bona le mokhoenyana oa bona .
’ Mè le morali e ile ea ba Lipaki .
Re ne re e - na le metsoalle ea bohlokoa phuthehong ea batho ba basoeu .
Sehlopha se mabifi sa Ku Klux Klan ( KKK ) , se ne se susumetsa khethollo ea merabe le lintoa ’ me se hlaheletse haholo ka nako eo .
Ka 1962 , ke ile ka memeloa ho ea Sekolong sa Tšebeletso sa ’ Muso se neng se le South Lansing , New York .
Leha ho le joalo , ke ile ka hlahlobeloa mosebetsi k’hamphaning ea lifono e Pine Bluff .
Haeba ba ne ba ka amohela kopo eaka , ke ne ke tla be ke le motho oa pele e motšo oa ho sebeletsa khoebo eo .
O ile a re : “ Re labalabela hore u ee sekolong e le hore ha u khutla u tl’o re ruta . ”
Ha Gloria a hopola nako eo re bileng le eona Pine Bluff o re : “ Ke ne ke rata tšimo ea moo haholo .
Ke ne ke e - na le lithuto tsa Bibele tse 15 ho ea ho tse 20 .
Re ne re sebetsa tšimo hoseng ebe ka mor’a moo re ea lithutong letšehare kaofela . Ka linako tse ling ho fihlela ka bo - 11 bosiu .
Mor’abo rona Leon Weaver , eo hona joale e leng mohokahanyi oa Komiti ea Lekala la United States le eena o ile a koptjoa ka nako eo hore e be molebeli oa potoloho .
Ke ne ke tšohile ha ke koptjoa hore ke be molebeli oa potoloho .
Mehleng eo , molebeli oa potoloho o ne a fuoa thupelo e nyenyane .
Ka letsatsi le leng mokhatlo oa KKK o ile oa etsa mohoanto toropong eo re neng re e etetse ea Tennessee .
Khoeling e hlahlamang re ile ra qala mosebetsi oa rona Bethele .
Haesale Gloria e le lehakoe la pelo ea ka ho tloha ha re nyalana
’ Na le Gloria re rata bophelo ba Bethele .
Ke bile setho sa Sehlopha se Busang ka 1999 .
Esaia 32 : 17 e re : “ Mosebetsi oa ho loka ha ’ nete e tla ba khotso ; ’ me tšebeletso ea ho loka ha ’ nete , e be khutso le tšireletseho ho isa nakong e sa lekanyetsoang . ”
Ea bobeli , re lokela ho kopa Jehova hore a re fe moea o halalelang .
O thusitsoe ke’ng ?
Ke ile ka mo lumelisa ka puo ea hae .
O ile a makala eaba o re : ‘ Nka u thusa ka’ng ?
Ke ile ka kopa ho kopana le Mokomishinara e Moholo .
O ile a mo letsetsa eaba oa tla ’ me a ntumelisa ka puo ea hae .
Ka mor’a moo , a ’ mamela ka hloko ha ke mo hlalosetsa ka mosebetsi o khothalletsang khotso oo Lipaki Tsa Jehova li o etsang . ”
‘ Ha e le e mobung o motle , ena ke . . . ba behang litholoana ka mamello . ’ — LUKA 8 : 15 .
LIPINA : 68 , 72
Ke’ng e tla re thusa ho beha litholoana ka mamello ?
( Sheba setšoantšo se qalong . ) ( b ) Jesu o ile a re’ng ka ho ruta “ sebakeng sa habo ” ?
Ha tali e antša ba khutlela hae ba iketlile .
Ba re botšepehi ba bara le barali babo rona bo ba susumelletsa ho mamella le hore ba be sebete tšimong .
Ba boetse ba re mohlala oa bona o ba ama lipelo .
Re tl’o hlahloba lipotso life tse tharo , hona hobane’ng ?
Empa ha ho na mosebetsi o mong oo nka o etsang ntle le ona . ”
Bala Johanne 15 : 1 - 5 , 8 .
Ke oa ho ruta batho ka ’ Muso oa Molimo .
Bala Luka 8 : 5 - 8 , 11 - 15 .
Re ka ‘ beha litholoana ka mamello ’ joang ?
Etsoe kea ba pakela hore ba chesehela Molimo ; empa eseng ho ea ka tsebo e nepahetseng . ”
Re ka etsisa Pauluse joang ?
( Bala Moeklesia 11 : 6 . )
Ha re khutlela , batho ba tloaetseng ho feta moo ba ile ba re botsa ba re : ‘ Le ntse le ipatile kae ?
Re ne re le hopotse . ’ ”
Ba ba ba ikopela limakasine . ”
Ke hobane’ng ha u ikemiselitse ho ‘ beha litholoana ka mamello ’ ?
15 : 8 .
LIPINA : 53 , 60
( Bala Johanne 15 : 1 , 8 . )
Jesu o ile a re ho baapostola ba hae : “ Ntate o tlotlisoa ka sena , hore le ’ ne le behe litholoana tse ngata . ”
( b ) U ikutloa joang ka monyetla oo u nang le oona oa ho halaletsa lebitso la Molimo ?
Ho boetse ho nthusa hore ke ikemisetse ho tsoela pele ke bolela ka ’ Muso . ”
( a ) Ke lebaka lefe le etsang hore re bolele ka ’ Muso le hlahang ho Johanne 15 : 9 , 10 ?
Bala Johanne 15 : 9 , 10 .
Re ka bontša joang hore re batla ho lula leratong la Kreste ?
Ka Bibeleng , Noe o hlalosoa e le “ ’ moleli . ”
( a ) Ke lebaka lefe le hlahang ho Matheu 22 : 39 le etsang hore re bolele ka ’ Muso ?
13 , 14 . ( a ) Ke mpho efe eo ho buuoang ka eona ho Johanne 15 : 11 ?
Ea pele , thabo .
( Bala Johanne 15 : 11 . )
( a ) Ke mpho efe eo ho buuoang ka eona ho Johanne 14 : 27 ?
Ea bobeli , khotso .
( Bala Johanne 14 : 27 . )
( a ) Ke mpho efe eo ho buuoang ka eona ho Johanne 15 : 15 ?
( b ) Baapostola e ne e tla lula e le metsoalle ea Jesu joang ?
Ea boraro , setsoalle .
( Bala Johanne 15 : 14 - 16 . )
Re ka kholiseha hore Jehova o arabela lithapelo tsa rona ( sheba serapa 18 )
LIPINA : 150 , 32
U ithutile’ng ka sera sa rona ?
Moapostola Petrose o hlalosa Satane Diabolose e le “ tau e purumang , ” ha Johanne eena a mo bitsa “ noha ” le “ drakone . ”
( Bala Jakobo 4 : 7 . )
Batho ba lumelang mashano ana ba qeta bophelo bohle ba bona ba batlana le “ Maruo ” ho e - na le ho sebeletsa Molimo .
Re lokela ho tseba sera sa rona Diabolose , empa ho hang ha rea lokela ho mo tšaba .
Haeba re mo hanyetsa , o tla re baleha .
LIPINA : 79 , 140
Lihlomo tsa moea ke life ?
Bala Baefese 6 : 14 .
Batsoali ba ka le metsoalle ea ka baa tseba hore ba ka ntšepa . ”
Empa ho na le melemo e mengata . U tla itšepa , u be le kamano e ntle le Jehova ’ me batho ba u ratang ba tla u hlompha . ”
Matheka a tlangoe ka ’ nete ( Sheba lirapa 3 - 5 )
Ke ne ke ikutloa ke le mosesaane ke bile ke nyahame . ”
Ba bang ba bana bao ke kenang le bona ka tlelaseng ba ile ba qala ho sebelisa lithethefatsi , ba bang ba tlohela sekolo .
Ho ne ho le bohloko ho bona kamoo bophelo ba bona bo senyehileng kateng .
Jehova o re sireletsa e le kannete . ”
O re : “ Kamehla kea ikhopotsa hore ke jere lebitso la Jehova le hore ho khalla lintho tseo bana ba bang ba li etsang , ke tsela eo Satane a ntlhaselang ka eona .
Ha ke hlola liteko tse joalo , ke ikutloa ke le motlotlo . ”
Tšireletso ea sefuba e leng ho loka ( Sheba lirapa 6 - 8 )
Bala Baefese 6 : 15 .
Kahoo , ke tseba hantle hore na nka ba thusa joang .
Ha ke lokiselitse , ke khona ho bua le bona ka lintho tse tla ba tsoela molemo . ”
Ke etsa bonnete ba hore ke bala lingoliloeng tsohle tse ngoletsoeng bacha .
Ha ke etsa joalo , ho ba bonolo hore ke ba thuse ka temana ea Bibele kapa ke ba khothalletse ho kena ho jw.org . ”
Maoto a roale lihlomo tsa litaba tse molemo ( Sheba lirapa 9 - 11 )
E meng ea ‘ metsu e tukang ’ ea Diabolose ke efe ?
Bala Baefese 6 : 16 .
Empa hona joale kea lokisetsa ’ me ke leka ho araba habeli kapa hararo .
Le hoja ho se bonolo ho arabela , ke ikutloa ke thabile ka mor’a hore ke arabele .
Hape , bara le barali babo rona baa nkhothatsa .
Kamehla ha ke khutla libokeng , ke khutla ke kholisehile hore Jehova oa nthata . ”
Thebe e kholo ea tumelo ( Sheba lirapa 12 - 14 )
Bala Baefese 6 : 17 .
Helmete ea poloko ( Sheba lirapa 15 - 18 )
U ka etsa’ng ho ntlafatsa bokhoni ba hao ?
Ke hlokometse hore ba thabela ho mamela ha ba bona hore u rata Bibele ebile u kholisehile hore ke ’ nete le hore u sebetsa ka thata hore u ba thuse . ”
Sabole ea moea ( Sheba lirapa 19 - 20 )
Jehova a ka re thusa hore re eme re tiile khahlanong le sona .
( Bala 2 Bakorinthe 8 : 13 - 15 . )
LIPINA : 72 , 119
Ho rata barab’abo rōna ho bolela’ng ?
Ke hobane’ng ha re lokela ho tsoela pele re rata barab’abo rōna ?
Re ka bontša joang hore re rata barab’abo rōna ?
Ke hobane’ng ha Pauluse a ile a ngolla Bakreste ba Baheberu lengolo ?
( Bala Baheberu 10 : 36 - 39 . )
Ke hobane’ng ha re lokela ho thahasella buka ea Baheberu ?
Temana ea selemo ea 2016 ke efe , hona ke hobane’ng ha e loketse ?
Bakreste ba ’ nete ba utloisisa hore ho rata barab’abo bona ho bolela’ng ?
Re lokela ho etsa’ng hona joale pele matšoenyeho a maholo a qala ?
A re ke re hlahlobeng tse tšeletseng tsa tsona .
Ho amohela baeti ho bolela’ng ?
“ Le se ke la lebala ho amohela baeti . ”
( Bala Baheberu 13 : 2 . )
Re ka etsa’ng e le hore re ‘ lule re hopola ba litlamong tsa chankana ’ ?
“ Lulang le hopotse ba litlamong tsa chankana . ”
( Bala Baheberu 13 : 3 . )
Re ka bontša joang hore re hlompha lenyalo ?
“ Lenyalo le ke le hlomphehe har’a bohle . ”
Ha re khotsofalla seo re nang le sona re tla nolofalloa ho etsa’ng ?
Ho “ ba sebete ” ho re thusa joang hore re rate barab’abo rōna ?
Re ka etsa’ng e le hore re tsoele pele ho bontša hore re rata barab’abo rōna ?
LIPINA : 121 , 63
Lerato leo Kreste a re ratang ka lona le re susumelletsa ho etsa’ng ?
Lerato leo Molimo a re ratang ka lona le re susumetsa joang hore re rate barab’abo rōna ?
Ke hobane’ng ha taba ea hore Molimo o oa re tšoarela e re susumelletsa hore re tšoarele barab’abo rōna ?
( Bala 2 Bakorinthe 1 : 20 . )
Taba ea hore Kreste o oa re rata e lokela ho re ama joang , hona e tla re susumelletsa ho etsa’ng ?
Ho ka ’ na ha etsahala’ng haeba re se hlokolosi ?
Re ka ipotsa lipotso life likhoeling tsee tsa Sehopotso , hona likarabo tsa tsona li ka re susumelletsa ho etsa’ng ?
( Bala Luka 14 : 12 - 14 . )
Ke’ng eo re lokelang ho e hopola ?
Lerato leo Molimo a re ratang ka lona le ile la thusa Lily joang hore a mamelle mefokolo ea Carol ?
‘ Mpho ea Molimo e ke keng ea hlalosoa le e sa lefelloeng ’ e u susumelletsa ho etsa’ng ?
LIPINA : 109 , 108
Ke’ng e ikhethang eo moprista a neng a e etsa ka Pentekonta , hona seo se ile sa phethahatsa mantsoe a moprofeta Joele joang ?
Bala Liketso 2 : 2 - 4 .
Re tseba joang hore batlotsuoa ha ba tlotsoe ka tsela e tšoanang ?
Bakreste ba kholisoa joang hore ke batlotsuoa , hona seo se ba thusa joang ?
Motlotsuoa a ka ’ na a ipotsa lintho life , empa ke eng seo le ka mohla a sa se belaelleng ?
Tsela eo motho a nahanang ka eona e fetoha joang ha e e - ba motlotsuoa , hona e fetoloa ke mang ?
Batlotsuoa ba ikutloa joang ka bophelo ba bona ba lefatšeng ?
LIPINA : 65 , 122
Zakaria 8 : 23 e phethahala ka tsela efe ?
Ke hobane’ng ha re ke ke ra tseba hantle hore na ke bo - mang bao e tla ba karolo ea ba 144 000 ?
Ke temoso efe eo batlotsuoa ba lokelang ho nahanisisa ka eona , hona hobane’ng ?
Batlotsuoa ba lokela ho inka joang ?
Batlotsuoa ha baa lebella eng , hona hobane’ng ?
Re lokela ho tšoara ba jang bohobe le ho noa veine Sehopotsong joang ?
( Sheba lebokose le reng , “ Lerato ‘ ha le Itšoare ka Mokhoa o sa Hlompheheng . ’ ” )
Jesu o ile a bolella barutuoa ba hae hore kaofela ha bona ke “ bara ba motho . ”
Ho se nkele batho ba itseng holimo ho re sireletsa joang ?
Ke hobane’ng ha re sa lokela ho tšoenyeha ka palo ea batho ba jang bohobe le ho noa veine Sehopotsong ?
“ Jehova o tseba ba hae . ”
Bibele e re’ng ka palo ea batlotsuoa ba tla beng ba ntse ba le lefatšeng ha matšoenyeho a maholo a qala ?
Ke’ng eo re lokelang ho e utloisisa ka ba 144 000 ba khethiloeng ke Jehova ?
Ba ile ba sebelisa batlotsuoa ba seng bakae ho ngola Mangolo a Segerike a Bakreste .
U ithutile’ng sehloohong see ?
LIPINA : 75 , 74
o re atametsang haufi le Molimo le batho ba bang ?
o re sireletsang ?
Le hoja Jehova e le Molimo ea phahameng ka ho fetisisa , o bontša batho lerato ka tsela efe ?
Jehova o ile a fa Adama mosebetsi ofe , hona hobane’ng ?
Ka mohlala , o ile a re Adama a rehe liphoofolo mabitso .
Bahlanka ba bang ba Molimo ba ’ nile ba etsa’ng ho phetha thato ea hae ?
Re fuoe monyetla oa ho kopanela mosebetsing ofe , hona na Jehova o ne a hloka thuso ea rōna ho o etsa ?
Moapostola Pauluse o ile a re : “ Ha re sebetsa hammoho le eena , re boetse re le kōpa ka tieo hore le se ke la amohela mosa o sa tšoanelang oa Molimo ’ me la lahleheloa ke morero oa oona . ”
Mora oa Molimo oa letsibolo o ile a re o ikutloa joang ka ho sebetsa le Ntate oa hae ?
Franco , eo le eena a lulang Italy , o re : “ Ho ithuta Bibele le ho ba teng kamehla libokeng ho re hopotsa kamoo Jehova a re ratang kateng le hore o ananela sohle seo re mo etsetsang sona , le hoja re ka ’ na ra bona eka hase letho .
Ho sebeletsa Molimo ho etsa hore bophelo ba ka bo be le morero ’ me hoa nthabisa . ”
Hore ebe Jesu le Jehova ba ’ nile ba sebetsa ’ moho ka lilemo tse ngata , ho ile ha ba thusa joang ?
Re tla ithuta hore na ke hobane’ng ha e le habohlokoa ho mo tšepa le ho latela litaelo tsa hae .
Ke’ng e tla etsa hore re atamele ho Jehova le ho ba bang haholoanyane lefatšeng le lecha ?
Mosebetsi oa boboleli o re sireletsa joang ?
Mosebetsi oa boboleli o nthusa hore ke lule ke ikokobelitse ’ me o mpha monyetla oa hore ke itšetlehe ka Jehova le ka Bakreste - ’ moho le ’ na . ”
Ke’ng e bontšang hore moea oa Molimo o oa re thusa mosebetsing oa boboleli ?
U ne u tla etsa mosebetsi oo nako e kae ?
Mosebetsi oa boboleli o amana joang le morero oa Jehova ka batho ?
Ke joang re mamelang taelo e khōlō ea Molimo ha re etsa mosebetsi oa boboleli ?
Ea bobeli , e joaloka eona , ke ena , ‘ U rate moahelani oa hao joalokaha u ithata . ’ ”
Ka sebele ke tlotla e khōlō ho etsa seo Jehova a re laelang sona le ho ba basebetsi - ’ moho le eena ! ”
’ Mè le Ntate ba ne ba sa tsamaee kereke , empa ba re ’ na le banab’eso ba supileng re ee kerekeng .
Ke ile ka e bala , ’ me ka utloa hore lebitso la Molimo ke Jehova .
Nakoana ka mor’a moo , ka abeloa ho khanna thuto ea buka ea phutheho .
Ke ne ke mema ’ Mè le banab’eso hore ba tle thutong ea buka eo ke e khannang , ’ me ba tla .
Ntate eena o ne a sa li kene .
Libeke tse peli hamorao ke ile ka ea khotla , ’ me moahloli a re : “ Hoja lintho li ne li etsoa ho ea ka ’ na , ke ne ke tla u ahlolela ho hlola bophelo bohle teronkong .
Na ho na le seo u ka se buang ? ”
Ka ea ho motšoaruoa e mong oa senatla ea neng a eme fensetereng a shebile ka ntle , ka fihla ka ema pel’a hae .
Eaba o re ho ’ na , “ U tšoaretsoe’ng , Mashoto ? ”
Ka re , “ Ke Paki ea Jehova . ”
Eaba ke re , “ Lipaki Tsa Jehova ha li ee ntoeng ho ea bolaea batho . ”
Ka re , “ Ke lumellana le uena . ”
Motšoaruoa eo a re , “ Ke qetile lilemo tse 15 ke le teronkong e ’ ngoe , ’ me ha ke le moo , ke ne ke bala libuka tse ling tsa lōna . ”
Tšimo ea rōna e ne e hlophisitsoe ka tsela eo .
Ke ile ka re , “ Kea utloa , feela nke ke ka ea sesoleng . ”
Ke ile ka qotsa lengolo la 2 Timothea 2 : 3 ’ me ka re , “ Ke se ke ntse ke le lesole la Kreste . ”
Nakoana ka mor’a moo , ke ile ka ea sebokeng sa ba lakatsang ho ea Bethele , kopanong e neng e tšoaretsoe Cincinnati , Ohio .
Ke ’ nile ka ba le metsoalle e mengata Bethele le phuthehong .
Ke ithutile ho bua Sechaena sa Mandarin ’ me ke thabela ho pakela batho ba se buang ha ke le seterateng .
Bekeng e latelang , o ile a mpha selefouno ea hae ’ me a re , “ Bua le motho ke enoa , ea Chaena . ”
Ka re , “ Ha ho na motho eo ke mo tsebang Chaena . ”
Ke se ke khutletse Chaena . ”
Ka re , “ Chaena ? ”
Nakoana ka mor’a moo , ngoan’abo Katie le eena o ile a nyamela .
Ha Molimo a rata , metsoalle le ba lelapa leso ba ileng ba hlokahala ba tla tsosoa lefatšeng le lecha .
LIPINA : 91 , 22
Lintho tseo Abrahama a neng a li tseba le tse ileng tsa mo hlahela li ile tsa matlafatsa tumelo ea hae joang ?
Abrahama o ile a etsa’ng ho matlafatsa kamano ea hae le Molimo ?
U ka etsisa Abrahama joang , e le hore u matlafatse kamano ea hao le Jehova ?
E ka ’ na eaba ho tlile joang hore Abrahama a tsebe Jehova , hona phello e ile ea e - ba efe ?
Lintho tse ileng tsa hlahela Abrahama li ile tsa matlafatsa tumelo ea hae joang ?
Lintho tse ileng tsa mo hlahela .
Re lokela ho etsa’ng e le hore re tiise setsoalle sa rōna le Jehova ?
Ke hobane’ng ha Abrahama a ne a tšoenyehile ka Sodoma le Gomora , hona Jehova o ile a mo thusa joang ?
Abrahama o tla thabela lintho life Paradeiseng ?
U ikemiselitse ho etsa’ng , hona re tlil’o tšohla eng sehloohong se latelang ?
E se eka kaofela ha rōna re ka ikemisetsa ho etsisa tumelo ea Abrahama .
( Bala Baheberu 6 : 10 - 12 . )
Sehloohong se latelang , re tlil’o tšohla mohlala oa batho ba bang ba bararo ba tšepahalang , bao e ileng ea e - ba metsoalle ea Molimo .
LIPINA : 106 , 118
Re ka ithuta’ng setsoalleng sa Molimo le Ruthe ?
Ke hobane’ng ha Morena Ezekiase e bile motsoalle ea haufi oa Jehova ?
Ke lintho life tse thusitseng Maria , ’ mè oa Jesu hore e be motsoalle oa Jehova Molimo ?
( Bala Ruthe 2 : 12 . )
Batho ba qeaqeang ho inehela ho Jehova ba ka ’ na ba thusoa ke eng ?
Hlalosa boemo boo Ezekiase a hōletseng ho bona .
( b ) Ke hobane’ng ha re sa lokela ho halefela Molimo ?
( c ) Ke hobane’ng ha re sa lokela ho nka hore tsela eo re hōlisitsoeng ka eona e tla etsa hore re etse lintho ka tsela e itseng ?
Bacha ba bangata ba ithuta ka Jehova , ho sa tsotellehe tsela eo ba hōlisitsoeng ka eona ( Sheba serapa sa 9 le 10 )
Ke’ng e ileng ea etsa hore Ezekiase e be e mong oa marena a lokileng a Juda ?
( Bala 2 Marena 18 : 5 , 6 . )
Batho ba bangata kajeno ba etsisitse Ezekiase joang ?
Ke hobane’ng ha e ka ’ na eaba ho ne ho le thata hore Maria a amohele boikarabelo boo a bo fuoang , empa o ile a re’ng ho Gabriele ?
Liketsahalong tseo ka bobeli , Maria o ile a mamela , a beha lipolelo tseo ka hloko pelong ea hae , ’ me a nahanisisa ka tsona . — Bala Luka 2 : 16 - 19 , 49 , 51 .
Re ka etsisa tumelo ea Maria ka tsela efe ?
Mohlomong u ile ua thabela ho sebeletsa Jehova haholoanyane ka mor’a hore u kolobetsoe .
Jesu o ile a re : “ Tloong ho ’ na , lōna bohle ba sehlang le ba imetsoeng , ’ me ke tla le khatholla .
O re : “ Ho nkutloisa bohloko ho bona boemo ba mosali oa ka bo ntse bo mpefala ’ me ha ho bonolo ho mo hlokomela , leha ho le joalo , ha ke lumelle seo hore se nkamohe thabo tšebeletsong ea Molimo .
Ho tseba hore Jehova ke eena ea mphileng bophelo le hore o bōpile batho hobane a e - na le morero , ho etsa hore ke mo rate ’ me ke mo sebeletse ka pelo eohle .
Ke lula ke phathahane mosebetsing oa boboleli ’ me ke leka ho lula ke nahana ka lintho tseo ’ Muso oa Molimo o tla re etsetsa tsona , e le hore ke se ke ka felloa ke thabo . ”
Jehova o fane ka sehlabelo sa thekollo , se re fang monyetla oa hore re phele re thabile .
Ha e le hantle , “ Molimo o ratile lefatše haholo hoo a ileng a fana ka Mora oa hae ea tsoetsoeng a ’ notši , e le hore e mong le e mong ea bontšang tumelo ho eena a se ke a timetsoa empa a be le bophelo bo sa feleng . ”
Ka ntan’o inehela ho eena , ’ me ka etsa qeto ea ho tlohela mosebetsi k’hamphaning eo ke e sebelelitseng ka lilemo tse 28 , eaba ke kenela tšebeletso ea nako e tletseng . ”
Na u sa hopola lintho tseo u neng u li etsa pele u ithuta ka Jehova ?
Moapostola Pauluse o ile a hopotsa Bakreste ba Roma hore e ne e le “ makhoba a sebe , ” empa joale e se e le “ makhoba a ho loka . ”
O re : “ Ha nako e ntse e ea , ke ile ka hlokomela hore Molimo ke Ntate ea lerato le ea mohau .
Ho sebeletsa Jehova ho entse hore ke thabe ho feta le ha e le neng pele . ”
LIPINA : 125 , 62
Jonathane o ile a bontša joang hore o oa tšepahala ho Jehova ?
Re ka bontša joang hore re tšepahala ho Molimo haeba re nka hore motho ea itseng ea boholong ha a tšoaneloe ke tlhompho ea rōna ?
Re ka bontša joang hore re tšepahala ho Jehova ha ba bang ba re tšoara ka leeme kapa ba sa re utloisise ?
Ke’ng e neng e thatafalletsa Baiseraele hore ba tšepahale ho Molimo pusong ea Saule ?
Jonathane o ile a tšoara ntate oa hae joang ?
Ke hobane’ng ha re lokela ho hlompha ba fuoeng matla a ho laola ?
Lerato leo re ratang Molimo ka lona le re thusa joang hore re tšepahale ho eena ?
Ho tšepahala ho Molimo ho ka re thusa joang ha re e - na le mathata ka lapeng ?
Saule o ile a tšoara Jonathane joang ?
Re lokela ho etsa’ng haeba mor’abo rōna a re tšoara ka leeme ?
Sehlooho see se u thusitse joang ?
Re lokela ho tšepahala ho mang ?
Ke hobane’ng ha Jonathane a ile a tšoara Davida ka tsela e fapaneng le ea Abnere ?
Ke eng e ka re thusang hore re tšepahale ho Molimo , hona hobane’ng ?
Phoso ea Abishai e re ruta ntlha efe ea bohlokoa ?
Morali’abo rōna e mong o ile a lula a tšepahala ho Molimo joang ha a tobane le boemo bo thata ?
Re ithuta’ng mohlaleng oa Abnere , Absalome le Baruke ?
U ka bontša joang hore u tšepahala ho Jehova le ho batho bao u ba ratang ?
Ke hobane’ng ha Hushai a ne a lokela ho iteta sebete e le hore a tšepahale ho Molimo ?
Ke ile ka rapela Molimo hore a mphe sebete sa hore ke se ke ka koenehela qeto eo ke e entseng .
Hona joale ha ho sa tšoana le pele , kaha ke khona ho ba etela khafetsa . ” — Bala Liproverbia 29 : 25 .
Sehlooho see se u thusitse joang ?
Re tla boela re bone hore na mamello e tla re thusa lintlheng life .
LIPINA : 86 , 54
Mohlala oa Jafeta le morali oa hae o ka re thusa joang hore re hanele tšusumetso e mpe ea batho ba re potolohileng ?
Ke melao - motheo efe ea Bibele e ka u thusang ho rarolla liqabang ?
Sehlooho see se u thusitse joang hore u itele e le hore u sebeletse Jehova haholoanyane ?
Jafeta le morali oa hae ba ile ba tobana le boemo bofe bo thata ?
Mohlala oa Jafeta le morali oa hae o ka re thusa joang kajeno ?
Batho ba mehleng ee ba joang , hona re lokela ho etsa’ng ?
Jafeta o ile a etsa kano efe , hona e ne e akarelletsa eng ?
Mantsoe a Jafeta a ho Baahloli 11 : 35 a bontša joang hore o ne a e - na le tumelo ?
Boholo ba rōna re tšepisitse Jehova eng , hona re ka bontša joang hore re tšepahalla tšepiso eo ?
LIPINA : 135 , 139
Ke’ng e tla re thusa ho mamella liteko ?
Re na le mehlala efe ea ba ileng ba mamella ?
Ho mamella ho ka re thusa joang ?
Lira tsa rōna ke Satane , lefatše la hae le ho se phethahale .
( Bala Luka 21 : 19 . )
Mamello ke eng ?
Ke joang lerato le re susumelletsang ho mamella ?
Jehova ke “ Molimo ea fanang ka mamello le matšeliso . ”
Esita le Jesu o ile a ikutloa ka tsela eo .
Ke hobane’ng ha re lokela ho hlahloba mohlala oa “ ba mameletseng ” ?
Ho na le batho bao re ka ba etsisang ba ileng ba mamella .
Re ithuta’ng mohlaleng oa likerubime tse ileng tsa behoa Edene ?
Ke’ng e ileng ea thusa Jobo ho mamella liteko ?
( Bala 2 Bakorinthe 1 : 6 . )
“ A re nahanelaneng hore re susumeletsane leratong le mesebetsing e metle , re sa tlohele ho bokana ha rōna . ” — BAHEBERU 10 : 24 , 25 .
LIPINA : 20 , 119
seo se re tsoela molemo joang .
re thusa ba bang joang .
re etsa hore Jehova a ikutloe joang .
( Sheba setšoantšo se qalong . ) ( b ) Re tlil’o tšohla eng sehloohong see ?
Li ile tsa re matlafatsa haholo tsa ba tsa re tiisa tumelo . ”
Ke eng e re khothatsang le ho re matlafatsa ha re le libokeng ?
Liboka lia re khothatsa .
( Bala Johanne 10 : 16 . )
Le hoja ke opeloa ke lengole , ke na le mathata a pelo ’ me ke tšoeroe ke lefu la tsoekere , kamehla ke khutla libokeng ke ikutloa ke hlaphohetsoe ho fapana le ha ke ne ke ea .
Kaha ke na le bothata ba litsebe mochine oa ka o hōlisang molumo o ile oa nthusa ho utloa bohle ha ba bina , eaba ke bina le bona .
Ho ba teng libokeng ho re thusa joang hore re fe Jehova tlotla e mo tšoanelang ?
Jehova o ikutloa joang ha re mamela taelo ea hae ea hore re be teng kamehla libokeng ?
Liboka li re thusa joang ho ba le kamano e ntle le Jehova le Jesu ?
Ha re ba teng libokeng , re bontša joang hore re ikemiselitse ho mamela Jehova ?
Phoka ke tlhohonolofatso e tsoang ho Jehova .
Ka ho le letšehali : Ntlo ea baitlami e Zaragoza , Spain ; ka ho le letona : Phetolelo ea Bibele ea Nácar - Colunga
Ke hopola ke rapela , ke re , “ Kea leboha Jehova hore ebe ha ua ka ua ntahla le hore ebe u nthusitse ka litsela tse ngata hore ke fumane seo ke neng ke ntse ke se batla , e leng ho tseba ’ nete ea Bibele . ”
Ke ile ka re : “ Empa Molimo eena o tla re’ng ? ”
LIPINA : 33 , 137
Jehova o ikutloa joang ka mebuso ea lefatše ?
Re lokela ho etsa’ng ha re tobana le boemo bo batlang hore re nke lehlakore ?
Re ithuta’ng mohlaleng oa bahlanka ba Jehova ba tšepahalang , ba ileng ba lula ba sa nke lehlakore ?
Re ka mamela Molimo le babusi ba lefatše joang ?
Re bontša joang hore ha re kenelle lipolotiking tsa lefatše ?
( b ) Ke hobane’ng ha re lokela ho itlhomella esale joale ho lula re sa nke lehlakore ?
Re lokela ho tšoara ba boholong pusong joang ?
Re lokela ho qoba ho ba le boikutlo bofe ?
Re ka etsa’ng hore re “ be seli ” leha ho le joalo re “ hloke molato ” ha re tobana le teko ea ho nka lehlakore ?
( Bala Matheu 10 : 16 , 17 . )
Re lokela ho qoba eng ha re buisana le batho ?
Moqoqong .
Ho rata maruo .
Re ithuta’ng mohlaleng oa bahlanka ba tšepahalang ba Molimo ba ileng ba lula ba sa nke lehlakore ?
“ Ho thuisa ka Liproverbia 27 : 11 , Matheu 26 : 52 le Johanne 13 : 35 ho ile ha matlafatsa boikemisetso ba ka ba ho hana ho ea sesoleng .
Litemana tsena li ile tsa boela tsa nthusa hore ke lule ke khobile matšoafo ha ke qosoa . ” — Andriy oa Ukraine .
“ Esaia 2 : 4 e nthusitse hore ke lule ke sa nke lehlakore .
“ Le boloke khotso mahareng a lōna . ” — MAREKA 9 : 50
LIPINA : 39 , 77
Jesu o fane ka keletso efe e ka re thusang ho rarolla liqabang ka khotso ?
Mokreste a ka ’ na a ipotsa lipotso life pele a etsa qeto ea hore na o tla rarolla qabang e pakeng tsa hae le Mokreste e mong joang ?
Mehato e meraro e ho Matheu 18 : 15 - 17 e ka re thusa joang ho rarolla liqabang ?
Ke mehlala efe ea liqabang e tlalehiloeng ho Genese , hona ke hobane’ng ha e le ea bohlokoa ?
Tšusumetso ea Satane e ile ea ata joang lefatšeng , hona phello e bile efe ?
Jesu o ile a ruta balateli ba hae hore ba itšoare joang ha ho e - na le liqabang ?
6 , 7 . ( a ) Ke hobane’ng ha e le habohlokoa ho rarolla liqabang ka potlako ?
( b ) Bahlanka bohle ba Jehova ba lokela ho ipotsa lipotso life ?
Ntate oa rōna ea leholimong o tla utloa thapelo eo , a be a e arabe . — 1 Johanne 5 : 14 , 15 .
Re lokela ho etsa’ng ha ba bang ba re utloisa bohloko ?
( Bala Liproverbia 10 : 12 ; 1 Petrose 4 : 8 . )
( a ) Qalong morali’abo rōna e mong o ile a itšoara joang ha a bueloa mantsoe a hlabang ?
( b ) Ke litemana life tse ileng tsa mo thusa hore a boele a thabe ?
11 , 12 . ( a ) Mokreste o lokela ho etsa’ng ha a hlokomela hore mor’abo “ o na le ho hong khahlanong ” le eena ?
“ Kaofela re khoptjoa hangata . ”
Mor’abo rōna e mong o ile a etsa’ng ha a tjolietsoa , hona re ithuta’ng mohlaleng oa hae ?
14 , 15 . ( a ) Re lokela ho sebelisa keletso e ho Matheu 18 : 15 - 17 neng ?
( b ) Jesu o ile a fana ka mehato efe e meraro , hona sepheo sa rōna e lokela ho ba sefe ha re e latela ?
Ke hobane’ng ha ho latela mehato eo Jesu a faneng ka eona e le tsela e atlehang le e lerato ea ho rarolla liqabang ?
Batho ba phehellang ho bōpa khotso ba tla fumana litlhohonolofatso life ?
LIPINA : 141 , 97
molaetsa oo li o phatlalatsang le hore na ke hobane’ng ha li o phatlalatsa ?
litsela tseo li o phatlalatsang ka tsona ?
ho bolela litaba tse molemo lefatšeng lohle ?
Mantsoe a Jesu a ho Matheu 24 : 14 a hlahisa lipotso life ?
Ho Matheu 28 : 19,20 Jesu o laetse balateli ba hae hore ba etse lintho life tse ’ nè ?
Ho bolela’ng ho ba “ batšoasi ba batho ” ?
Re lokela ho araba lipotso life tse ’ nè , hona hobane’ng ?
Bala Luka 4 : 43 .
Re tseba joang hore baruti ba Bokreste - ’ mōtoana ha ba phatlalatse molaetsa o nepahetseng ?
Ha rea lokela ho bolela litaba tse molemo ka sepheo sefe se fosahetseng ?
( Bala Liketso 20 : 33 - 35 . )
Jesu le barutuoa ba hae ba ne ba phatlalatsa litaba tse molemo joang ?
Boiteko ba likereke tsa Bokreste - ’ mōtoana ba ho phatlalatsa litaba tse molemo bo fapana joang le ba bahlanka ba Jehova ?
Ke tsona feela tse phatlalatsang hore Jesu o qalile ho busa e le Morena ka 1914 .
Litaba tse molemo li lokela ho phatlalatsoa ho isa bohōleng bofe ?
Ke’ng e bontšang hore Lipaki Tsa Jehova li phethahatsa boprofeta ba Jesu ba hore litaba tse molemo li tla boleloa lefatšeng lohle ?
Websaete ea rōna e fumaneha ka lipuo tse fetang 750 .
Re tseba joang hore Molimo o tšehetsa Lipaki Tsa Jehova ka moea oa hae o halalelang ?
17 , 18 . ( a ) Ke’ng e re kholisang hore Lipaki Tsa Jehova ke tsona tse bolelang litaba tse molemo tsa ’ Muso kajeno ?
( b ) Ke’ng e re thusang ho bolela litaba tse molemo ?
LIPINA : 117 , 114
Ke eng e ka etsang hore re sitoe ho rua molemo linthong tseo Jehova a re fang tsona ?
Ke litlhahiso life tse ka re thusang hore re rue molemo likarolong tsohle tsa Bibele ?
Re ka rua molemo joang ha re bala lingoliloeng tse ngoletsoeng bacha le batho bao e seng Lipaki ?
1 , 2 . ( a ) Lipaki Tsa Jehova li ikutloa joang ka Bibele ?
( b ) U rata karolo efe ka Bibeleng ?
3 , 4 . ( a ) Re ikutloa joang ka lingoliloeng tsa rōna ?
( b ) Ke lingoliloeng life tse ngoletsoeng batho ba itseng ?
Re ka kholiseha hore Jehova oa thaba ha re etsa’ng ?
Ke hobane’ng ha re lokela ho ikemisetsa ho amohela lithuto tsohle ha re bala Bibele ?
E bale u ikemiselitse ho amohela lithuto tsohle .
Nka li sebelisa joang e le hore ke thuse ba bang ? ’
( b ) Re ka sebelisa lintlha tseo joang ho thusa ba bang ?
12 , 13 . ( a ) Re ka ipotsa lipotso life ha re etsa lipatlisiso ?
( b ) Fana ka mohlala oa kamoo ho etsa lipatlisiso tsa se neng se etsahala ha Lengolo le itseng le ngoloa , ho ka re hlokomelisang lithuto tse sa tobang .
E ngoletsoe hokae , hona neng ?
Lingoliloeng tse ngoletsoeng bacha li ba thusa joang , hona ba bang ba ka rua molemo joang ka ho li bala ?
Ke hobane’ng ha Bakreste ba hōlileng ba lokela ho bala lihlooho tse ngoletsoeng bacha ?
Likhatiso tsa rōna li boetse li thusa bacha joang ?
( Bala Moeklesia 12 : 1 , 13 . )
Re ka rua molemo joang ha re bala likhatiso tse ngoletsoeng batho bao e seng Lipaki ?
Re ka bontša joang hore re ananela lintho tsohle tseo Jehova a re fang tsona ?
LIPINA : 69 , 57
Liqeto tseo re li etsang li ka re ama joang le ba bang ?
Re ka tseba joang hore na Jehova o batla hore re etse’ng , ha ho se na molao o tobileng ?
Ke’ng e ka re thusang ho tseba hore na Jehova o ikutloa joang ?
E meng ea melao e ka Bibeleng ke efe , hona ho e mamela ho re tsoela molemo joang ?
2 , 3 . ( a ) Ke hobane’ng ha Bibele e sa re fe melao ea ntho e ’ ngoe le e ’ ngoe ?
Ke’ng e ka re thusang ho etsa liqeto tse nepahetseng ?
Re ka tseba joang hore na Jehova o thabisoa ke eng boemong boo ho se nang molao o tobileng ka Bibeleng ?
( Bala Matheu 4 : 2 - 4 . )
Ke’ng e ka re thusang ho etsa liqeto tse nepahetseng ?
Re ka ipotsa lipotso life ha re ntse re ithuta Bibele ?
Ke eng e ka re thusang ho tseba hore na Jehova o nahana joang ?
Fana ka mohlala oa kamoo ho tseba hore na Jehova o nahana joang ho ka re thusang kateng ho etsa liqeto tse nepahetseng .
( Bala Luka 18 : 29 , 30 . )
U ka tseba joang hore na tsela e itseng ea ho apara e thabisa Jehova kapa che ?
( c ) Re lokela ho etsa’ng pele re etsa qeto ea bohlokoa ?
( Bala Genese 6 : 5 , 6 . )
Re rua molemo joang ha re etsa liqeto tse thabisang Jehova ?
Ke ’ nete hore ho tla ’ ne ho be le ntho e itseng e ncha eo re tla ithuta eona ka Jehova .
ka lapeng ?
LIPINA : 61 , 52
Ke hobane’ng ha re lokela ho lula re etsa liphetoho le ha re se re kolobelitsoe ?
Ke hobane’ng ha Jehova a batla hore re sebetse ka thata ho hlōla mefokolo ea rōna ?
Re ka etsa’ng e le hore re lumelle Lentsoe la Molimo hore le ’ ne le re fetole ?
1 - 3 . ( a ) Ke mefokolo efe eo re ka ’ nang ra thatafalloa ho e fetola le ha re se re kolobelitsoe ?
( b ) Re ka ’ na ra ipotsa lipotso life ?
Ke hobane’ng ha re hloleha ho khahlisa Jehova ka linako tsohle ?
6 , 7 . ( a ) Ke’ng e re thusang ho ba le kamano e ntle le Jehova le hoja re sa phethahala ?
( b ) Ke hobane’ng ha re sa lokela ho khaotsa ho kōpa Jehova hore a re tšoarele ?
Re lokela ho etsa’ng haeba re batla hore Lentsoe la Molimo le tsoele pele ho re fetola , hona re ka ’ na ra ipotsa lipotso life ?
Ke hobane’ng ha Jehova a batla hore re sebetse ka thata ho hlōla mefokolo ea rōna ?
Re lokela ho etsa’ng e le hore re khahlise Jehova ?
( Sheba lebokose le reng , “ Bibele le Thapelo li Fetotse Bophelo ba Bona . ” )
Ke hobane’ng ha re sa lokela ho nyahama haeba re sa khone ho etsa liphetoho kapele ?
Ke hobane’ng ha re kholisehile hore Bibele e ka re thusa ho etsa liphetoho bophelong ba rōna ?
[ 1 ] ( serapeng sa 1 ) Lebitso le fetotsoe .
Morali’abo rōna Maria Victoria o ne a rata ho seba ba bang .
Russell : “ Ke thusitsoe ke ho rapela Jehova le ho bala Bibele letsatsi le letsatsi .
Hape , ho thuisa ka 2 Petrose 2 : 11 le ka likeletso tsa baholo le hona ho ile ha nthusa . ”
Maria Victoria : “ Ke ne ke lula ke rapela Jehova hore a nthuse ho laola leleme la ka .
Ke ile ka boela ka hlokomela hore ke lokela ho khaotsa ho tloaelana le batho ba ratang ho seba ba bang .
Pesaleme ea 64 : 1 - 4 e ile ea nthusa ho hlokomela hore ha ke batle ho ba e mong oa bao batho ba bang ba rapellang hore ba sireletsoe ho bona !
Ke ile ka boela ka hlokomela hore ho lula ke seba ho tla etsa hore ke be mohlala o mobe ho ba bang , ’ me ho tla nyefola lebitso la Jehova . ”
Linda : “ Ke ile ka itloaetsa lipampitšana tsa rōna e le hore ke be malala - a - laotsoe ho li tsamaisa .
Bohle re na le mefokolo e ka utloisang ba bang bohloko .
LIPINA : 89 , 26
hore na Jehova o khetha batho bao a batlang ho ba bōpa joang ?
hore na ke hobane’ng ha Jehova a bōpa batho ba hae ?
hore na Molimo o bōpa batho ba mo mamelang joang ?
Ke hobane’ng ha Jehova e le Sebōpi se seholo ka ho fetisisa ?
Re ka etsisa boikutlo ba Baiseraele ba bakileng joang ?
Jehova o khetha batho bao a batlang ho ba bōpa joang ?
( Bala 1 Samuele 16 : 7b . )
Ho tšepa Jehova joaloka Sebōpi sa rōna ho lokela ho ama tsela eo re shebang ( a ) batho ba tšimong ea rōna joang ?
Hamorao , ke ile ka kopana le lelapa le leng leo ke ileng ka le rata ka lebaka la tsela eo le etsang lintho ka eona .
Eaba ka letsatsi le leng ke utloa taba e ileng ea ’ makatsa , ea hore ke Lipaki Tsa Jehova !
Boitšoaro ba lona bo ile ba ntšusumetsa hore ke itlhahlobe hore na ke hobane’ng ha ke sa rate Lipaki .
Kapele ke ile ka hlokomela hore boikutlo ba ka bo susumetsoa ke lintho tseo batho ba li buang le ho se tsebe seo e leng ’ nete . ”
Ke hobane’ng ha re ananela khalemelo ea Jehova ?
( Bala Baheberu 12 : 5 , 6 , 11 . )
Jehova o re ruta joang kajeno , hona o tla tsoela pele ho re ruta joang nakong e tlang ?
Jesu o ile a etsisa mamello ea Sebōpi sa rōna Jehova joang ?
( Bala Pesaleme ea 103 : 10 - 14 . )
Davida o ile a bontša ka litsela life hore ke letsopa le bonolo , hona re ka mo etsisa joang ?
Jehova o sebelisa moea o halalelang le phutheho ea Bokreste joang ho re bōpa ?
Le hoja Jehova e le eena ea re bōpileng , o bontša joang hore o hlompha bolokolohi ba rōna ba ho ikhethela ?
Liithuti tsa Bibele li ka bontša joang hore li batla hore Jehova a li bōpe ?
( a ) Ke eng e u khahlang ka hore ebe Jehova ke Sebōpi ?
( b ) Re tla araba lipotso life sehloohong se latelang ?
LIPINA : 60 , 22
Ke mekhoa efe e ka etsang hore re se ke ra mamela Jehova ?
Ke litšobotsi life tse ka re thusang ho lula re le letsopa le bonolo ka matsohong a Molimo ?
Batsoali ba Bakreste ba ka bontša joang hore ba ntse ba bōptjoa ke Jehova ?
Ke hobane’ng ha Molimo a ile a re Daniele ke “ monna ea khahlehang haholo , ” hona ke joang re ka tšepahalang joaloka Daniele ?
( Bala Jeremia 18 : 6 . )
Ke mekhoa efe e ka re thatafatsang lipelo ?
Liproverbia 4 : 23 e re : “ Ho feta tse ling tsohle tse lokelang ho lebeloa , u sireletse pelo ea hao , kaha mehloli ea bophelo e tsoa ho eona . ”
( Bala 2 Likronike 26 : 3 - 5 , 16 - 21 . )
Ho ka etsahala’ng haeba re tloaetse ho etsa sebe ?
7 , 8 . ( a ) Baiseraele ba ile ba bontša kotsi ea ho fokolloa ke tumelo joang ?
( b ) Re ithuta’ng mohlaleng oa bona ?
Ke hobane’ng ha re lokela ho lula re hlahloba tumelo ea rōna , hona re ka etsa seo joang ?
Ke eng e ka re thusang hore re tšoane le letsopa le bonolo ka matsohong a Jehova ?
Tšebeletso ea tšimo e ka re thusa ho hlaolela litšobotsi life , hona li ka re tsoela molemo joang ?
Batsoali ba lokela ho etsa’ng haeba ba batla ho atleha ho bōpa bana ba bona ?
Batsoali ba lokela ho etsa’ng ha ngoan’a bona a khaoloa ?
( Bala 1 Bakorinthe 5 : 11 , 13 . )
Ke hobane’ng ha re lokela ho mamela Jehova kamehla , hona seo se tla re tsoela molemo joang ?
LIPINA : 138 , 112
Ke ka tsela efe Molimo oa rōna e leng “ Jehova a le mong ” ?
Re ka bontša joang hore re rapela “ Jehova a le mong ” ?
Re lokela ho etsa’ng ho boloka khotso le bonngoe ka phuthehong ?
( b ) Ke hobane’ng ha Moshe a ile a bua mantsoe ao ?
Oa Ikhetha .
Poleloana “ Jehova a le mong ” e boetse e bolela’ng , hona Jehova o ile a paka seo joang ?
Ha a Fetohe Ebile oa Tšepahala .
8 , 9 . ( a ) Jehova o batla hore barapeli ba hae ba etse’ng ?
( b ) Jesu o ile a hatisa bohlokoa ba mantsoe a Moshe joang ?
( Bala Mareka 12 : 28 - 31 . )
10 , 11 . ( a ) Re ka bontša joang hore re inehetse ho Jehova ka ho feletseng ?
( b ) Bahlankana ba Baheberu ba neng ba le Babylona , ba ile ba bontša joang hore ba inehetse ho Jehova ka ho feletseng ?
Re lokela ho etsa’ng haeba re batla ho inehela ho Jehova ka ho feletseng ?
Meharo e ka ama kamano ea rōna le Jehova joang ?
Ke hobane’ng ha Pauluse a ile a hopotsa Bakreste hore Molimo oa bona ke “ Jehova a le mong ” ?
16 , 17 . ( a ) Ho ntse ho phethahala boprofeta bofe kajeno , hona phello ke efe ?
( b ) Ke eng e ka senyang bonngoe ba rōna ?
18 , 19 . ( a ) Ke keletso efe e hlahang ho Baefese 4 : 1 - 3 ?
( b ) Re ka etsa’ng ho thusa phutheho hore e lule e momahane ?
Re ka bontša joang hore rea utloisisa hore “ Molimo oa rōna ke Jehova a le mong ” ?
Ho na le batšoasi ba litlhapi ba bangata metseng e ithatikileng ka lebōpo la Trinidad le Tobago .
Lipaki Tsa Jehova li tloaetse ho buisana le batšoasi ba litlhapi moo
LIPINA : 121 , 75
Ke hobane’ng ha mokhatlo oa Molimo o ikhetha ?
Bibele e bontša joang hore kaofela ha rea phethahala ?
Re ka etsa’ng ha re siteloa ba bang le ha ba bang ba re siteloa ?
Bibele e ile ea bolela esale pele joang hore batho ba Jehova ba tla eketseha ?
Bahlanka ba Molimo ba bontšitse joang hore baa ratana ?
( Bala Mikea 4 : 1 , 3 . )
Sena se ba thusitse ho lula ba “ hloekile maling a batho bohle . ” — Liketso 20 : 26 .
Ke hobane’ng ha ho eketseha ha batho ba Jehova e le ho hlollang ?
Ke hobane’ng ha ka linako tse ling ba bang ba ka ’ na ba re utloisa bohloko ?
( Bala Baroma 5 : 12 , 19 . )
Haeba u ne u phela mehleng ea Eli le bara ba hae , u ka be u ile ua itšoara joang ?
Davida o ile a etsa libe life tse tebileng , hona Jehova o ile a mo tšoara joang ?
( a ) Moapostola Petrose o ile a hlōleha joang ho phethahatsa tšepiso ea hae ?
( b ) Ke hobane’ng ha Jehova a ile a tsoela pele ho sebelisa Petrose le ka mor’a hore a etse phoso ?
Jesu o ile a etsa’ng ha Judase Iskariota le Petrose ba mo utloisa bohloko ?
Bibele e ile ea bolela’ng esale pele mabapi le bahlanka ba Jehova kajeno ?
Re lokela ho etsa’ng ha motho e mong a re siteloa ?
13 , 14 . ( a ) Ke hobane’ng ha re lokela ho mamellana ?
( b ) Re lokela ho lula re nahana ka tšepiso efe ?
Jesu o ile a re re lokela ho etsa’ng ha ba bang ba re siteloa ?
Josefa o re behetse mohlala ofe o motle ?
Re lokela ho etsa’ng ha ba bang ba re siteloa ?
( Bala Matheu 5 : 23 , 24 . )
Na botšepehi ba bona bo ile ba ba tsoela molemo ?
Re hlokomela sena ha re bala seo Bibele e se buang ka temoho le bohlale .
Liproverbia 3 : 13 - 15 e re : “ Ho thaba motho ea fumaneng bohlale , le motho ea fumanang temoho , etsoe ho ba le bona e le leruo ho molemo ho feta ho ba le silevera e le leruo ’ me ho ba le bona e le lihlahisoa ho molemo ho feta khauta .
Ke ba bohlokoa haholo ho feta likorale , ’ me lintho tse ling tsohle tseo u li thabelang li ke ke tsa lekanngoa le bona . ”
Ho thoe’ng ka botšepehi ?
Kaha ke ne ke le mookameli , ke ne ke tlameha ho fa motho ea lefisang lekhetho tjotjo , e le hore a tlōlise bolotsana boo mahlo .
Ka lebaka leo , ke ile ka tloaela ho se tšepahale .
Ke behetse bara ba ka ba babeli mohlala o motle , ’ me ke khona le ho sebeletsa ka phuthehong .
Ho basebeletsi ba lekhetho le ho batho ba bang bao ke sebetsang le bona , ke tsebahala ke le motho ea tšepahalang . ”
Ruthe o ile a fallela Iseraele moo a neng a tla rapela Molimo oa ’ nete .
